### PR TITLE
PR to test recent cherry picks to branch-2.8  (do not merge)

### PR DESCRIPTION
**Pull request by michaeljmarshall**
PR to trigger tests for a large number of cherry picked commits.

### CODE REVIEW

**Comment by michaeljmarshall** [comment]
```
Note: Google Test filter = AuthPluginTest.testOauth2
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from AuthPluginTest
[ RUN      ] AuthPluginTest.testOauth2
2023-02-23 06:19:06.359 INFO  [140305976601280] AuthPluginTest:346 | PARAMS: {
        "type": "client_credentials",
        "issuer_url": "https://dev-kt-aa9ne.us.auth0.com/",
        "client_id": "Xd23RHsUnvUlP7wchjNYOaIfazgeHd9x",
        "client_secret": "rT7ps7WY8uhdVuBTKWZkttwLdQotmdEliaM5rLfmgNibvqziZ-g07ZH52N_poGAb",
        "audience": "https://dev-kt-aa9ne.us.auth0.com/api/v2/"}
2023-02-23 06:19:06.384 ERROR [140305976601280] AuthOauth2:223 | Response failed for getting the well-known configuration https://dev-kt-aa9ne.us.auth0.com./ Error Code 60: SSL certificate problem: certificate has expired
/pulsar/pulsar-client-cpp/tests/AuthPluginTest.cc:350: Failure
```
The python test must have some issues that were not introduced by these commits, so I'll ignore the failures for now.

**Comment by michaeljmarshall** [comment]
Interesting error in the CLI integration test:

```
2023-02-23T06:39:24.5394144Z 06:39:24.539 INFO  [main] o.a.p.t.MockitoCleanupListener@40 - Cleaning up Mockito's ThreadSafeMockingProgress.MOCKING_PROGRESS_PROVIDER thread local state.
2023-02-23T06:39:24.5395772Z 06:39:24.539 INFO  [main] o.a.p.t.FastThreadLocalCleanupListener@53 - Cleaning up FastThreadLocal thread local state.
2023-02-23T06:39:24.5409002Z 06:39:24.540 WARN  [main] i.n.u.c.FastThreadLocalThread@84 - Unexpected exception:
2023-02-23T06:39:24.5409842Z java.lang.RuntimeException: It's not thread-safe to get 'threadLocalMap' which doesn't belong to the caller thread
2023-02-23T06:39:24.5411084Z 	at io.netty.util.concurrent.FastThreadLocalThread.threadLocalMap(FastThreadLocalThread.java:80) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
2023-02-23T06:39:24.5411744Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
2023-02-23T06:39:24.5412249Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
2023-02-23T06:39:24.5412823Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
2023-02-23T06:39:24.5413272Z 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
2023-02-23T06:39:24.5414018Z 	at org.apache.pulsar.tests.FastThreadLocalStateCleaner.cleanupAllFastThreadLocals(FastThreadLocalStateCleaner.java:107) ~[buildtools-2.8.5-SNAPSHOT.jar:2.8.5-SNAPSHOT]
2023-02-23T06:39:24.5415025Z 	at org.apache.pulsar.tests.FastThreadLocalStateCleaner.cleanupAllFastThreadLocals(FastThreadLocalStateCleaner.java:134) ~[buildtools-2.8.5-SNAPSHOT.jar:2.8.5-SNAPSHOT]
2023-02-23T06:39:24.5415961Z 	at org.apache.pulsar.tests.FastThreadLocalCleanupListener.onBetweenTestClasses(FastThreadLocalCleanupListener.java:54) ~[buildtools-2.8.5-SNAPSHOT.jar:2.8.5-SNAPSHOT]
2023-02-23T06:39:24.5416939Z 	at org.apache.pulsar.tests.BetweenTestClassesListenerAdapter.checkIfTestClassChanged(BetweenTestClassesListenerAdapter.java:40) ~[buildtools-2.8.5-SNAPSHOT.jar:2.8.5-SNAPSHOT]
2023-02-23T06:39:24.5417896Z 	at org.apache.pulsar.tests.BetweenTestClassesListenerAdapter.onBeforeClass(BetweenTestClassesListenerAdapter.java:35) ~[buildtools-2.8.5-SNAPSHOT.jar:2.8.5-SNAPSHOT]
2023-02-23T06:39:24.5418791Z 	at org.apache.pulsar.tests.FastThreadLocalCleanupListener.onBeforeClass(FastThreadLocalCleanupListener.java:27) ~[buildtools-2.8.5-SNAPSHOT.jar:2.8.5-SNAPSHOT]
2023-02-23T06:39:24.5419543Z 	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:167) ~[testng-7.3.0.jar:?]
2023-02-23T06:39:24.5420357Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122) ~[testng-7.3.0.jar:?]
2023-02-23T06:39:24.5420732Z 	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
2023-02-23T06:39:24.5421258Z 	at org.testng.TestRunner.privateRun(TestRunner.java:764) ~[testng-7.3.0.jar:?]
2023-02-23T06:39:24.5421699Z 	at org.testng.TestRunner.run(TestRunner.java:585) ~[testng-7.3.0.jar:?]
2023-02-23T06:39:24.5422129Z 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384) ~[testng-7.3.0.jar:?]
2023-02-23T06:39:24.5422600Z 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378) ~[testng-7.3.0.jar:?]
2023-02-23T06:39:24.5423076Z 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337) ~[testng-7.3.0.jar:?]
2023-02-23T06:39:24.5423515Z 	at org.testng.SuiteRunner.run(SuiteRunner.java:286) ~[testng-7.3.0.jar:?]
2023-02-23T06:39:24.5423981Z 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) ~[testng-7.3.0.jar:?]
2023-02-23T06:39:24.5424481Z 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) ~[testng-7.3.0.jar:?]
2023-02-23T06:39:24.5424959Z 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218) ~[testng-7.3.0.jar:?]
2023-02-23T06:39:24.5425417Z 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140) ~[testng-7.3.0.jar:?]
2023-02-23T06:39:24.5425840Z 	at org.testng.TestNG.runSuites(TestNG.java:1069) ~[testng-7.3.0.jar:?]
2023-02-23T06:39:24.5426240Z 	at org.testng.TestNG.run(TestNG.java:1037) ~[testng-7.3.0.jar:?]
2023-02-23T06:39:24.5426801Z 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283) ~[surefire-testng-3.0.0-M3.jar:3.0.0-M3]
2023-02-23T06:39:24.5427507Z 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75) ~[surefire-testng-3.0.0-M3.jar:3.0.0-M3]
2023-02-23T06:39:24.5428205Z 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120) ~[surefire-testng-3.0.0-M3.jar:3.0.0-M3]
2023-02-23T06:39:24.5428969Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384) ~[surefire-booter-3.0.0-M3.jar:3.0.0-M3]
2023-02-23T06:39:24.5429757Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345) ~[surefire-booter-3.0.0-M3.jar:3.0.0-M3]
2023-02-23T06:39:24.5430435Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126) ~[surefire-booter-3.0.0-M3.jar:3.0.0-M3]
2023-02-23T06:39:24.5431069Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418) ~[surefire-booter-3.0.0-M3.jar:3.0.0-M3]
```

**Comment by michaeljmarshall** [comment]
While it's not great that the tests timed out, I am going to consider this a passing set of tests and will push the commits.

**Comment by tisonkun** [comment]
@michaeljmarshall do we have any plan to release a 2.8.5? I found 2.8.x is end-of-life according to the existing [release policy](https://pulsar.apache.org/contribute/release-policy/#supported-versions).

**Comment by michaeljmarshall** [comment]
> @michaeljmarshall do we have any plan to release a 2.8.5? I found 2.8.x is end-of-life according to the existing [release policy](https://pulsar.apache.org/contribute/release-policy/#supported-versions).

@tisonkun - I was under the impression a release line was EOL until discussed on the ML. I'll ask now.

**Pull request closed without merging**
