### PR TITLE
Upgrade Gson version 2.8.6 to 2.8.9

### LINKED ISSUE #13607: Vulnerability in gson version 2.8.6
**Is your enhancement request related to a problem? Please describe.**
gson version 2.8.6 is vulnerable to desirealization of untrusted data, as shown here:
https://security.snyk.io/vuln/SNYK-JAVA-COMGOOGLECODEGSON-1730327

**Describe the solution you'd like**
Upgrade gson version to 2.8.9

### PR DESCRIPTION
**Pull request by mattisonchao**
Fixes #13607

Master Issue: #13607

### Motivation

see #13607

### Modifications

- Upgrade Gson version 2.8.6 to 2.8.9

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API: ( no)
  - The schema: ( no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: ( no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 
 
- [x] `no-need-doc`

### CODE REVIEW

**Review by Shoothzj — CHANGES_REQUESTED** [review]
we should also change version in license file

**Comment by mattisonchao** [comment]
> we should also change version in license file

done.

**Review by lhotari — APPROVED** [review]

**Review by Shoothzj — APPROVED** [review]

**Pull request merged**
