### PR TITLE
Rollback protobuf version to 3.5.1

### LINKED ISSUE #8013: PR check failed by license
Currently, the PR check failed by the license check:

```
com.google.protobuf-protobuf-java-3.11.4.jar unaccounted for in LICENSE
com.google.protobuf-protobuf-java-util-3.11.4.jar unaccounted for in LICENSE
com.google.protobuf-protobuf-java-3.5.1.jar mentioned in LICENSE, but not bundled
com.google.protobuf-protobuf-java-util-3.5.1.jar mentioned in LICENSE, but not bundled
protobuf-java-3.11.4.jar unaccounted for in lib/presto/LICENSE
protobuf-java-util-3.11.4.jar unaccounted for in lib/presto/LICENSE
protobuf-java-3.5.1.jar mentioned in lib/presto/LICENSE, but not bundled
protobuf-java-util-3.5.1.jar mentioned in lib/presto/LICENSE, but not bundled

It looks like there are issues with the LICENSE/NOTICE.
##[error]Process completed with exit code 2.
```

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <rxl@apache.org>

### Motivation

Due to protobuf version conflicts and incompatibility issues, first roll back the protobuf version, and then resend a new pull request to fix this problem.

### Modifications

- Rollback protobuf version to 3.5.1

### CODE REVIEW

**Review by jiazhai — APPROVED** [review]

**Comment by jiazhai** [comment]
@wolfstudy Please help add proper labels and milestone for this PR.

**Comment by wolfstudy** [comment]
```
[INFO] Running org.apache.pulsar.functions.instance.JavaInstanceRunnableTest
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 0.334 s <<< FAILURE! - in org.apache.pulsar.functions.instance.JavaInstanceRunnableTest
[ERROR] testStatsManagerNull(org.apache.pulsar.functions.instance.JavaInstanceRunnableTest)  Time elapsed: 0.018 s  <<< FAILURE!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.pulsar.functions.proto.Function$SourceSpec$InputSpecsDefaultEntryHolder
	at org.apache.pulsar.functions.proto.Function$SourceSpec.internalGetInputSpecs(Function.java:8843)
	at org.apache.pulsar.functions.proto.Function$SourceSpec.getInputSpecsCount(Function.java:8850)
	at org.apache.pulsar.functions.instance.InstanceUtils.calculateSubjectType(InstanceUtils.java:98)
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.<init>(JavaInstanceRunnable.java:164)
	at org.apache.pulsar.functions.instance.JavaInstanceRunnableTest.createRunnable(JavaInstanceRunnableTest.java:61)
	at org.apache.pulsar.functions.instance.JavaInstanceRunnableTest.testStatsManagerNull(JavaInstanceRunnableTest.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

It seems that this problem is caused by the version conflict of protobuf. Currently, the protobuf version of pulsar uses 3.11.4, but the version used in bk is still 3.5.1

**Review by codelipenghui — APPROVED** [review]

**Comment by wolfstudy** [comment]
Due to protobuf version conflicts and incompatibility issues, first roll back the protobuf version, and then resend a new pull request to fix this problem

**Pull request merged**
