### PR TITLE
[improve][pip] PIP-367: Propose a Contributor Repository for Pulsar

### PR DESCRIPTION
**Pull request by liangyepianzhou**
### Motivation
See proposal for detail.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [x] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by StevenLuMT** [comment]
Our XHS team(@liangyepianzhou @AuroraTwinkle @StevenLuMT @cai152) will submit a few to [pulsar-java-contrib](https://github.com/StevenLuMT/pulsar-java-contrib) as a primer to let everyone know the role of this library

**Comment by dave2wave** [comment]
Using a website building repository template as the basis for this effort is confusing.

**Comment by liangyepianzhou** [comment]
@dave2wave @eolivelli Enrico and I had some discussions in emails. These discussions led me to refine my ideas and create a prototype of the project in the new repository. [0] This project prototype will show what we want to do better than the documentation. 

[0] - https://github.com/StevenLuMT/pulsar-java-contrib

**Comment by liangyepianzhou** [comment]
As the initial contributors, we have drafted a contribution plan. We will gradually improve this contributor repository in accordance with this plan.

https://github.com/StevenLuMT/pulsar-java-contrib/issues/7

**Comment by liangyepianzhou** [comment]
@lhotari  How should this proposal be handled in the future? Will it be merged with other voted proposals, or will it be closed?

**Review by lhotari — APPROVED** [review]
merging since the PIP has been approved in https://lists.apache.org/thread/td0j8l1c3l93nny0m5smnsdmb91j1n2y .

**Pull request merged**
