### PR TITLE
[website] Update PMC and committer info in team.js

### PR DESCRIPTION
**Pull request by Jennifer88huang**
### Motivation
Some new PMC and committers are not added to the team page.

### Modifications
Add new PMC and committers info in the team.js file.

### CODE REVIEW

**Comment by tuteng** [comment]
run cpp tests
run java8 tests

**Comment by tuteng** [comment]
run java8 tests

**Comment by Jennifer88huang** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by Jennifer88huang** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Pull request merged**
