### PR TITLE
[Issue 5399][docs] Update KubernetesSecretsTokenAuthProvider docs

### LINKED ISSUE #5399: Create documentation for KubernetesSecretsTokenAuthProvider
Currently, the `KubernetesSecretsTokenAuthProvider` used by the K8S runtime is not documented at all. This should be documented along with details of how it works and the new functionality to add the CA as well

### PR DESCRIPTION
**Pull request by Jennifer88huang**
Fixes #5399 

### Motivation
The `KubernetesSecretsTokenAuthProvider` used by the K8S runtime is not documented. 

### Modifications
- Document how `KubernetesSecretsTokenAuthProvider`  works and add CA.
- Refine other content to be clear and concise.
- Refine the structure and headings.

### CODE REVIEW

**Comment by Jennifer88huang** [comment]
@addisonj could you please help check the content from L206-208? Any comment is highly appreciated.

**Comment by Jennifer88huang** [comment]
1. What does "the function shares a namespace and potentially schedule across clusters." mean in L257?
2. While refining the content throughout, I found that we need to update the content in v2.6.0-v2.6.2 as well. When the update in the master is ready, will update those in v2.6.x as well.

**Comment by Jennifer88huang** [comment]
@Huanli-Meng could you please help review, thank you.

**Review by wolfstudy — APPROVED** [review]
LGTM +1

**Pull request merged**
