### PR TITLE
doc: added contributor over time

### PR DESCRIPTION
**Pull request by juzhiyuan**
### Motivation

Added Contributor Over Time for Pulsar since 2016-09-07.

### Modifications

- Added that graph to the README file.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

  - Does this pull request introduces a new feature? No

### CODE REVIEW

**Review by eolivelli — CHANGES_REQUESTED** [review]
Good idea

Is there a way to link a dynamically generated chart?

**Comment by juzhiyuan** [comment]
> Is there a way to link a dynamically generated chart?

Ya, but this feature is not stable currently, once it's finished, I will file a new PR. How about this?

**Comment by juzhiyuan** [comment]
Hi @eolivelli, I just updated this PR and using a Dynamical URL :)

**Comment by Yiyiyimu** [comment]
> Hi @eolivelli, I just updated this PR and using a Dynamical URL :)

Hi @juzhiyuan I think you could update the URL format 😁

**Comment by juzhiyuan** [comment]
@eolivelli @Yiyiyimu Hi, just updated with the dynamic graph :)

**Comment by codelipenghui** [comment]
The pr had no activity for 30 days, mark with Stale label.

**Comment by Yiyiyimu** [comment]
Hi @codelipenghui I think this PR is updated and ready to review

Screenshot:
image

**Comment by tisonkun** [comment]
Closed. This is included at https://pulsar.apache.org/community/#section-community now.

**Pull request closed without merging**
