### PR TITLE
Change ContextClassLoader to NarClassLoader in AdditionalServlet

### PR DESCRIPTION
**Pull request by mattisonchao**
### Motivation

It's ``AddtionalServelt`` side change, like #11270 

### Modifications

Change context class loader through Thread.currentThread().setContextClassLoader(classLoader) before every protocol handler callback, and change it back to original class loader afterwards.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API: ( no)
  - The schema: ( no)
  - The default values of configurations: ( no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 

- [x] `no-need-doc`

### CODE REVIEW

**Comment by BewareMyPower** [comment]
Could you add a test to verify this change?

**Comment by mattisonchao** [comment]
@BewareMyPower  I will do that.

**Comment by mattisonchao** [comment]
@BewareMyPower 

I have added test.

**Review by codelipenghui — APPROVED** [review]

**Review by BewareMyPower — APPROVED** [review]

**Review by Jason918 — APPROVED** [review]

**Review by Demogorgon314 — APPROVED** [review]

**Pull request merged**
