### PR TITLE
[cleanup][doc] Counterpart of pulsar-site PR-345

### PR DESCRIPTION
**Pull request by tisonkun**
Master Issue: #18103

This is the counterpart of https://github.com/apache/pulsar-site/pull/345.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by tisonkun** [comment]
I'm going to stop the sync while doing #19064. Then we don't have to always do this two sides updates.

**Review by momo-jun — APPROVED** [review]
LGTM

**Review by HQebupt — APPROVED** [review]

**Comment by tisonkun** [comment]
Thanks for your reviews!

**Comment by michaeljmarshall** [comment]
LGTM, thanks @tisonkun!

**Comment by lhotari** [comment]
@michaeljmarshall @tisonkun  I think it's a bad idea to remove the information from SECURITY.md. Having some duplication of information is useful in this case. I'd suggest reverting the changes that were made to SECURITY.md in this PR.

**Comment by tisonkun** [comment]
@lhotari That can be fine, while `Security Policy details and supported versions of Apache Pulsar` is unrelated to security topics before and now.

**Comment by tisonkun** [comment]
A reference is https://github.com/apache/.github/blob/main/.github/SECURITY.md that for most other Apache projects I am involved in, I simply leave `SECURITY.md` missing so it fallbacks to the Foundation-wise one. Since we have a dedicated page I pasted the link into the file and it looks well.

If you'd prefer to make some duplicates, I don't object to it, as I expect the content to be quite stable.

**Pull request merged**
