### PR TITLE
[ISSUE-9168] DOCS: Update the batch delay default value

### LINKED ISSUE #9168: What's the batch Delay default value
image
In this annotation, the default value is 10 ms.
But in this code, the default value is 1.
image

Which value is recommended? It seems scheduly task execs per 1 ms easily cause the application OOM

### PR DESCRIPTION
**Pull request by sijia-w**
Fixes #9168

### CODE REVIEW

**Review by Huanli-Meng — APPROVED** [review]
LGTM, one more question, will other releases also need to be updated?

**Comment by Jennifer88huang** [comment]
@sijia-w Thanks for your contribution.
Except code, the values in `client-libraries-go` and `client-libraries-cgo` also need updating for different versions.

**Comment by sijie** [comment]
@sijia-w Can you rebase this pull request?

**Comment by Jennifer88huang** [comment]
@sijia-w Could you rebase this pull request when you read the message? Thank you.

**Pull request closed without merging**
