### PR TITLE
[Broker]support ranger

### LINKED ISSUE #8553: [Pulsar Broker] support apache ranger
**Is your feature request related to a problem? Please describe.**
Currently, Pulsar only support stores authorization policies under local-zookeeper. Is it possible to support [ranger](https://github.com/apache/ranger), apache ranger can provide a framework for central administration of security policies and monitoring of user access.

### PR DESCRIPTION
**Pull request by ltamber**
Fixes #8553

### CODE REVIEW

**Comment by cckellogg** [comment]
Thanks for your contribution but I think that this authorization plugin should not be part of the main code base. It could live in its own repo and then users can package or include it if they want to use it.

**Comment by complone** [comment]
@ltamber 

https://github.com/aries-demos/dataops/tree/master/stack-hooks/before-INSTALL/scripts/ranger



The following example illustrates the following scenario

> solved problem

    Unified authority control for hdfs, yarn, hive, spark, hbase, storm, kafka, atlas, solr, etc.
Managed data flow
    - ```ranger-admin``` is responsible for strategy storage and provision of http restful api extensions to provide strategy and modification services
    - ```ranger-usersync``` focuses on synchronizing user and user group data from ldap to ranger
    - ```ranger-tagsync``` is responsible for synchronizing the tags on the atlas to ranger
> Data flow of the plug-in
   - After the plug-in is allowed, http periodically (30 seconds by default) downloads the policy from ranger-admin to the local /etc/ranger
    - Through the parsing strategy, it is similar to a big hashmap. When the request comes, filter (checkPermission) for permission control
    - The result log is written back to solr, hdfs (the new version of kafka is not enabled)


*Pulsar is also here as a component that requires permission verification. Maybe you can synchronize the tags marked by Pulsar on Atlas to ranger based on ranger-tagsync?*

**Comment by codelipenghui** [comment]
The pr had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale and conflict. Please rebase and resubmit the patch if it's still relevant.

**Pull request closed without merging**
