### PR TITLE
Remove redundant signSafeMod

### LINKED ISSUE #10081: Remove redundant signSafeMod
Remove signSafeMod in ConnectionPool, use MathUtils.signSafeMod instead.

### PR DESCRIPTION
**Pull request by Technoboy-**
Fix #10081

### CODE REVIEW

**Review by aahmed-se — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by eolivelli** [comment]
committed to master branch, thank you @Technoboy-

**Comment by codelipenghui** [comment]
@eolivelli It's better to add the assignees and milestone before merging the PR, this will make it easier to count the contributions of contributors, which will be used as a basis for promoting the committer in the future.

**Comment by eolivelli** [comment]
@codelipenghui thanks.
I am used to BK script that does everything automatically

I won't forget in the future

**Comment by codelipenghui** [comment]
@eolivelli It's great if Pulsar can help a script to assign the assigness automatically

**Comment by eolivelli** [comment]
@codelipenghui I will start a discussion on dev@

**Pull request merged**
