### PR TITLE
[website]The website cannot get the swagger version file

### PR DESCRIPTION
**Pull request by tuteng**
### Motivation

After multiple versions of rest API are currently supported, a prefix is added to the route of the online environment when it is displayed. resulting in the js file not being available.

image

### Modifications

* Change js file search to a relative path

### Verifying this change

Click http://pulsar.apache.org/admin-rest-api/js/getSwaggerByVersion.js 404 not found
Click http://pulsar.apache.org/admin-rest-api/../js/getSwaggerByVersion.js OK

### CODE REVIEW

**Comment by tuteng** [comment]
@merlimat I found that some versions of swagger files have not been generated, please generate these files when the website is published. 

image

http://pulsar.apache.org/swagger/2.3.0/
http://pulsar.apache.org/swagger/2.3.1/
http://pulsar.apache.org/swagger/2.3.2/
http://pulsar.apache.org/swagger/2.4.0/
http://pulsar.apache.org/swagger/master/

**Comment by tuteng** [comment]
run java8 tests

**Comment by sijie** [comment]
@tuteng for those swagger files, don't we need to generate the swagger files manually and add the the source repo?

**Comment by sijie** [comment]
run java8 tests

**Comment by tuteng** [comment]
> @tuteng for those swagger files, don't we need to generate the swagger files manually and add the the source repo?

It seems to have been ignored in file [gitignore](https://github.com/apache/pulsar/blob/master/site2/.gitignore).

**Comment by sijie** [comment]
@tuteng can you update the gitignore rule to exclude non-master swagger files? so that we can add the non-master swagger files in the repo hence we don't need to generate it again and again.

**Comment by tuteng** [comment]
run java8 tests
run cpp tests

**Comment by sijie** [comment]
run java8 tests

**Comment by tuteng** [comment]
run java8 tests

**Comment by tuteng** [comment]
run java8 tests

**Comment by tuteng** [comment]
run java8 tests

**Pull request merged**
