### PR TITLE
[fix][broker] Fix to avoid TopicStatsImpl NPE even if producerName is null

### LINKED ISSUE #15471: NPE during get topic stats
### screenshot
image

### which version do you use
compile the master code for test

### content
I think it's a regression by https://github.com/apache/pulsar/pull/12401 when client `isSupportsPartialProducer` is false.
@equanz please have take a look

### PR DESCRIPTION
**Pull request by equanz**
Fixes #15471

### Motivation

Please see https://github.com/apache/pulsar/issues/15471 .

### Modifications

* if producerName is null, then fall back to `supportsPartialProducer=false`
  - currently, producerName is required when`supportsPartialProducer=true`, because stats are aggregated by producerName
* allow null producerName on getPublishers

### Verifying this change

- [x] Make sure that the change passes the CI checks.

* Add tests for null producerName

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below or label this PR directly.

Need to update docs? 
  
- [x] `no-need-doc` 

This PR is one of the fixing issues.

### CODE REVIEW

**Comment by Technoboy-** [comment]
> Why the produceName is null?

Get it from the issue comment.

**Comment by Technoboy-** [comment]
I think the root cause is here :
https://github.com/apache/pulsar/blob/ca614e0fcc87b751204a97a081c7f00545b3f87b/pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/TopicStatsImpl.java#L234-L238
We should set `producerName` for the `newStats `

**Comment by equanz** [comment]
> I think the root cause is here :

Yes. I think so too.

> We should set producerName for the newStats

I think we can't set producerName in this section, because old client's partitioned producer can have different producerName between internal producers. https://github.com/apache/pulsar/pull/12401

**Comment by Technoboy-** [comment]
> > I think the root cause is here :
> 
> Yes. I think so too.
> 
> > We should set producerName for the newStats
> 
> I think we can't set producerName in this section, because old client's partitioned producer can have different producerName between internal producers. #12401

Ok, make sense.

**Review by Technoboy- — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
