### PR TITLE
[Client]Fix AutoUpdatePartitionsInterval setting problem

### PR DESCRIPTION
**Pull request by RobertIndie**
### Motivation
In setting autoUpdatePartitionsInterval, just on the first call to partitionsAutoUpdateTimerTask were set up. But the next recheck schedule is still using the default parameters. This PR fixes the problem.

### Modifications

* Set timeout delay for partitionsAutoUpdateTimerTask recheck schedule

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Review by sijie — APPROVED** [review]

**Comment by wolfstudy** [comment]
```
Error:  Tests run: 3, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 68.687 s <<< FAILURE! - in org.apache.pulsar.functions.worker.PulsarFunctionPublishTest
Error:  testPulsarFunctionBKCleanup(org.apache.pulsar.functions.worker.PulsarFunctionPublishTest)  Time elapsed: 20.043 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.functions.worker.PulsarFunctionPublishTest.testPulsarFunctionBKCleanup() didn't finish within the time-out 20000
```

/pulsarbot run-failure-checks

**Comment by wolfstudy** [comment]
@RobertIndie Can you help to check test case of `testPulsarFunctionBKCleanup`?

**Review by codelipenghui — APPROVED** [review]

**Comment by wolfstudy** [comment]
It seems that there is a problem with this pr change, which will cause every error to be reproduced stably. @RobertIndie Can you help check the problem?

**Pull request merged**
