### PR TITLE
Add Debezium Postgresql integration test

### PR DESCRIPTION
**Pull request by willome**
Provide new CDC/Debezium Postgresql Integration test. Only Mysql one was present.

### CODE REVIEW

**Comment by tuteng** [comment]
Can you add a more detailed test? For example, actively insert a piece of data into PostgreSql, then receive it use consumer, and finally compare the fields.

**Comment by jiazhai** [comment]
retest this please

**Comment by jiazhai** [comment]
@willome Thanks for the work. lgtm. It would be better to enhance these 2 test cases if possible.

**Comment by willome** [comment]
This test is a copy/paste of the Mysql one. I have tried to add some data in the Postgres db but unfortunately I can't connect to the docker postgres container (jdbc:postgresql://host:port/dbname). I have tried with localhost, DebeziumPostgresqlContainer.NAME. Maybe I need to change the pg_hba.conf. Any idea ?
```
@Override
    public Map<String, String> produceSourceMessages(int numMessages) throws Exception {
        String SQL = "INSERT INTO inventory.products VALUES (default,'scooter','3-wheel scooter')";
        String urlConnect = String.format("jdbc:postgresql://%s:%s/%s", "localhost",
                sourceConfig.get("database.port"), sourceConfig.get("database.dbname"));
        try (Connection conn = DriverManager.getConnection(urlConnect, (String) sourceConfig.get("database.user"),
                (String)  sourceConfig.get("database.password"));
// connection failure
             PreparedStatement pstmt = conn.prepareStatement(SQL))
        {
```

**Comment by sijie** [comment]
@jiazhai @tuteng can you please review this pull request again?

**Comment by jiazhai** [comment]
> This test is a copy/paste of the Mysql one. I have tried to add some data in the Postgres db but unfortunately I can't connect to the docker postgres container (jdbc:postgresql://host:port/dbname). I have tried with localhost, DebeziumPostgresqlContainer.NAME. Maybe I need to change the pg_hba.conf. Any idea ?

@willome Thanks for the update. 
because test framework is using docker containers, we should use `DebeziumPostgresqlContainer.NAME`, and run it in the same docker network that setting by `withNetworkAliases` in the code.

**Comment by sijie** [comment]
@aahmed-se before you merging any pull request, can you please double check the whole conversation? This pull request is 2 months old and there are comments that are not addressed.

**Pull request merged**
