### PR TITLE
[pulsar-client-cpp] Fix Dockerfile

### PR DESCRIPTION
**Pull request by magrain**
### Motivation

Delete unnecessary files when creating docker image.

### Modifications

Delete tar file after zlib make.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by codelipenghui** [comment]
retests this please

**Comment by codelipenghui** [comment]
retest this please

**Comment by massakam** [comment]
rerun cpp tests
rerun integration tests

**Comment by jerrypeng** [comment]
rerun integration tests

**Comment by massakam** [comment]
rerun integration tests

**Comment by hrsakai** [comment]
rerun integration tests

**Pull request merged**
