### PR TITLE
[improve][broker]Use subscribeRateLimiterLock to update subscribeRateLimiter

### PR DESCRIPTION
**Pull request by AnonHxy**
### Motivation

`subscribeRateLimiter` is mutable, so use `subscribeRateLimiterLock` to update `subscribeRateLimiter`

### Modifications

Use `subscribeRateLimiterLock` to update `subscribeRateLimiter`

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

  
- [x] `no-need-doc`

### CODE REVIEW

**Comment by Technoboy-** [comment]
Seems that no need to do this.

**Comment by AnonHxy** [comment]
It seems a little like this PR: https://github.com/apache/pulsar/pull/15601.  But when I inspected the detail of the code , I find 
there is no follow-up actions after the `subscribeRateLimiter ` object changing. So it seems that no need to do this.  I will closed this PR. Thanks a lot @[Technoboy](https://github.com/Technoboy-)

**Pull request closed without merging**
