### PR TITLE
[Docs]Auto generate pages for pulsar-admin

### PR DESCRIPTION
**Pull request by tuteng**
### Motivation

After implementing this tool https://github.com/apache/pulsar/pull/5738, we need to use this tool to automatically generate the documentation of pulsar-admin.

### Modifications

* Add a script to automatically generate document pages of pulsar-admin
* Add em tag for markdown file of pulsar-admin

### Verifying this change

image

### CODE REVIEW

**Comment by tuteng** [comment]
run cpp tests
run java8 tests

**Comment by tuteng** [comment]
run cpp tests

**Comment by tuteng** [comment]
run java8 tests

**Comment by tuteng** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Pull request merged**
