### PR TITLE
[Issue #6709] Support non-durable subscription for pulsar-client cli

### LINKED ISSUE #6709: unsubscribe option for pulsar-client cli
**Is your feature request related to a problem? Please describe.**
After running `pulsar-client consume` the subscription is kept active and it is not possible to unsubscribe without using the admin interface.

**Describe the solution you'd like**
The option to unsubscribe after consuming. eg:
pulsar-client consume -s testsub --unsubscribe persistent://my/pulsar/topic

**Describe alternatives you've considered**
Using pulsar-admin it's possible to unsubscribe but this requires the user has access to the admin interface.

**Additional context**
none

### PR DESCRIPTION
**Pull request by 315157973**
Fixes #6709

### Motivation
After running pulsar-client consume the subscription is kept active and it is not possible to unsubscribe without using the admin interface.

### Modifications
Add subscriptionMode option for cli

### Verifying this change
unit tests:
PulsarClientToolTest
PulsarClientToolWsTest

### CODE REVIEW

**Review by sijie — APPROVED** [review]

**Comment by lhotari** [comment]
The PulsarClientToolWsTest introduced by this PR is flaky. I have created issue #9437 with links to recent test failures.

**Pull request merged**
