### PR TITLE
[docs] Refine description of two examples in "Functions API" doc

### PR DESCRIPTION
**Pull request by Jennifer88huang**
### Motivation
This file will be deprecated when "Pulsar Functions(new)" is ready, yet the two examples might be used in somewhere. So I just refine it for future use.

### Modifications
Refine description of the two examples while reading.

### CODE REVIEW

**Comment by Jennifer88huang** [comment]
Is there any comment on this?

**Comment by sijie** [comment]
retest this please

**Comment by Jennifer88huang** [comment]
run integration tests
run java8 tests

**Comment by Jennifer88huang** [comment]
run integration tests

**Pull request merged**
