### PR TITLE
[pulsar-proxy] Clean up deprecated Zookeeper client

### PR DESCRIPTION
**Pull request by liketic**
The Zookeeper client related classes are already deprecated and not used any more. We can clean up now.

### CODE REVIEW

**Comment by srkukarni** [comment]
run java8 tests

**Comment by srkukarni** [comment]
@liketic can you merge with master as well as check if the java8 unittests failures are genuine?

**Comment by liketic** [comment]
@srkukarni Will do soon.

**Comment by jiazhai** [comment]
run java8 tests

**Comment by liketic** [comment]
run java8 tests
run integration tests

**Pull request merged**
