### PR TITLE
[Authorization] Support GET_METADATA topic op after enable auth

### PR DESCRIPTION
**Pull request by yuruguo**
### Motivation
Currently, we can get the internal stats of a topic through `bin/pulsar-admin topics stats-internal tn1/ns1/tp1` and also get ledger metadata by specifying flag `--metadata`.

However I found that `PulsarAuthorizationProvider` lacks support for topic operation `GET_METADATA` when verifying the role's authorization, code as below: 
https://github.com/apache/pulsar/blob/08a49c06bff4a52d26319a114961aed6cb6c4791/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L1162-L1164
https://github.com/apache/pulsar/blob/08a49c06bff4a52d26319a114961aed6cb6c4791/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java#L567-L596

The purpose of this PR is to support role with `lookup` topic authorization to `GET_METADATA` of ledger.

### Documentation 
- [x] `no-need-doc`

### CODE REVIEW

**Comment by yuruguo** [comment]
@lhotari @eolivelli @codelipenghui @freeznet PTAL

**Comment by yuruguo** [comment]
@lhotari @codelipenghui @gaoran10 PTAL

**Review by codelipenghui — COMMENTED** [review]
@yuruguo Could you please help add a test? The change looks good to me.

**Review by eolivelli — APPROVED** [review]
LGTM 

@michaeljmarshall please take a look as you are working on this topic during these days

**Comment by yuruguo** [comment]
> @yuruguo Could you please help add a test? The change looks good to me.

Okay :)
Done, PTAL

**Comment by yuruguo** [comment]
@merlimat @hangc0276 PTAL

**Review by freeznet — APPROVED** [review]
LGTM

**Review by michaeljmarshall — APPROVED** [review]
LGTM. My one additional thought is that the added test is more complex than necessary, and that complexity will increase the time required to run this pretty simple test. I think there is a test Authentication Provider that would make it easier to test authorization without needing to explicitly test authentication, but I could be wrong.

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
