### PR TITLE
[Branch-2.10] [fix] [broker] Fix bookeeper packages npe

### PR DESCRIPTION
**Pull request by horizonzy**
image

The `zookeeperServers` already deprecated, we recommend  `metadataStoreUrl`. 
In `BookKeeperPackagesStorage`, it still use `zookeeperServers`, didn't compatible with `metadataStoreUrl`, so it will throw NPE.

I notice that there are two PRs already fix it, but it only in Branch-2.11, so move it to Branch-2.10.
#14384, #14595

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by Technoboy- — APPROVED** [review]

**Comment by BewareMyPower** [comment]
@horizonzy I reverted this PR in branch-2.10. It looks like this PR brings an incompatibility issue.

**Comment by BewareMyPower** [comment]
@horizonzy I cherry-picked this PR again. See https://github.com/apache/pulsar/commit/1df5734a3898d371a9d75d921ecb6d73b2847a71. It seems like the bug can be fixed by cherry-picking https://github.com/apache/pulsar/pull/16969.

**Comment by horizonzy** [comment]
Fine.

**Pull request merged**
