### PR TITLE
Added docs for using schema in Python client lib

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Following up from #3391, adding user docs for defining the schema in Python client library.

### CODE REVIEW

**Comment by sijie** [comment]
run cpp tests
run integration tests

**Comment by merlimat** [comment]
run cpp tests
run integration tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests
run integration tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Pull request merged**
