### PR TITLE
Use simple GC settings when running integration tests

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Services started in integration tests are using a very aggressive GC config, with many threads and trading more memory for pause times. 

Additionally, multiple variables are being passed in the wrong way to the bookie container, resulting in bookies using the default Xmx of 2 GB.

### CODE REVIEW

**Comment by merlimat** [comment]
run integration tests

**Comment by codelipenghui** [comment]
run integration tests

**Comment by aahmed-se** [comment]
run integration tests

**Comment by jiazhai** [comment]
run java8 tests
run integration tests

**Comment by aahmed-se** [comment]
run java8 tests
run integration tests

**Comment by codelipenghui** [comment]
run integration tests

**Comment by merlimat** [comment]
run integration tests

**Comment by aahmed-se** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Pull request merged**
