### PR TITLE
[Cherry-pick] Use get instead of join to avoid getting stuck

### PR DESCRIPTION
**Pull request by Technoboy-**
Cherry pick #11597 .

## Motivation
join() will not time out, when network jitter occurs, it is easy to cause the thread to get stuck forever

## Modifications
Use get(timeout) instead of join() to avoid getting stuck

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
Lgtm

**Comment by Technoboy-** [comment]
As AdminResource and ResourceQuotasBase are not using CompletableFuture, so don't need to modify.

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
