### PR TITLE
updated link to Yahoo's open source website

### PR DESCRIPTION
**Pull request by gyehuda**
### Motivation 

The current docs pointed to yahoo.github.io, which we decommissioned a while ago. I propose pointing this to the new webpage at opensource.yahoo.com.

### Modifications

I just changed the URL

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

No

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
No

### CODE REVIEW

**Comment by codelipenghui** [comment]
run java8 tests
run integration tests

**Comment by codelipenghui** [comment]
run Java8 tests

**Comment by codelipenghui** [comment]
run  Integration Tests

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by gyehuda** [comment]
Any suggestions for how to update the link? I just want to repoint it to a site with content (opensource.yahoo.com). Thanks.

**Comment by sijie** [comment]
@gyehuda your change is great. those comments are used for triggering CI tests. currently our ASF jenkins CI is not stable. so we have to re-trigger CI tests. sorry for the confusion.

**Pull request merged**
