### PR TITLE
[fix][Admin CLI docs] Sync the description and default value of `--processing-guarantees`

### PR DESCRIPTION
**Pull request by momo-jun**
### Motivation

To keep https://pulsar.apache.org/tools/pulsar-admin/ the single source of truth for Pulsar admin, the CLI reference doc pages have been deprecated, such as https://pulsar.apache.org/docs/reference-pulsar-admin/ or https://pulsar.apache.org/docs/next/io-cli.

However, the reference doc pages for Pulsar functions/sources/sinks do have some content that Pulsar admin CLI docs don't offer, for example, the description and the default value of `--processing-guarantees`.

### Modifications

Add the missing description and the default value of `--processing-guarantees` for sources, sinks and functions.

The preview looks good.
image
image
image

### Documentation
  
- [x] `doc`

### CODE REVIEW

**Comment by Anonymitaet** [comment]
Can you attach local preview screenshots?

**Comment by momo-jun** [comment]
> Can you attach local preview screenshots?

Local preview is not available yet. @urfreespace will modify the required procedures/commands.

**Review by freeznet — APPROVED** [review]

**Comment by Anonymitaet** [comment]
@momo-jun seems that the screenshots are previewed on a code editor rather than HTML page?

**Comment by momo-jun** [comment]
> @momo-jun seems that the screenshots are previewed on a code editor? are they HTML pages?

Yes, it's a preview version in VScode of the generated .md file. 
@urfreespace Do you know the follow-up actions to preview these .md files in HTML pages?

**Review by gaoran10 — APPROVED** [review]

**Comment by momo-jun** [comment]
@SignorMercurio - just a double-check to resolve the conflict. Can I keep my changes and append the line298 `+ " #Java, Python, Go"` you added in #16853?
image

**Comment by SignorMercurio** [comment]
@momo-jun Of course yes. Note that there's a leading whitespace  in `" #Java, Python, Go"`.

**Review by urfreespace — APPROVED** [review]

**Review by Anonymitaet — APPROVED** [review]

**Pull request merged**
