### PR TITLE
[Doc] Add *Kinesis sink connector guide* 

### PR DESCRIPTION
**Pull request by Anonymitaet**
Fix https://github.com/apache/pulsar/issues/5015

### CODE REVIEW

**Comment by tuteng** [comment]
run cpp tests
run java8 tests

**Comment by Anonymitaet** [comment]
run java8 tests

**Comment by Anonymitaet** [comment]
run java8 tests

**Comment by Anonymitaet** [comment]
run java8 tests

**Comment by Anonymitaet** [comment]
run integration tests
run java8 tests

**Comment by Anonymitaet** [comment]
run java8 tests

**Comment by Anonymitaet** [comment]
run integration tests
run java8 tests

**Comment by Anonymitaet** [comment]
run integration tests

**Pull request merged**
