### PR TITLE
[pulsar-client] support input-stream for trustStore cert

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation
#6760 introduced support of dynamic cert loading by supporting input stream for tls cert and key file. It mainly used by container usecase. This usecase also requires dynamic loading for truststore certs and user can't store trust-store cert into file-system. So, add support to load truststore cert dynamically using input stream.

### Modification
add support to load truststore cert dynamically using input stream.

### CODE REVIEW

**Comment by aahmed-se** [comment]
@rdhabalia any update on this ? will this also support CA authority ?

**Comment by rdhabalia** [comment]
@aahmed-se this PR is mainly adds the support to load trust-store certs from input-stream rather file-system and this is needed for users who run their applications in container and can't keep certs into file-system.
and this PR is already ready to merge.
can we please review and merge it.

**Review by aahmed-se — APPROVED** [review]

**Comment by aahmed-se** [comment]
@rdhabalia there seem to be some tls failures that need to fixed.

**Comment by rdhabalia** [comment]
@aahmed-se I checked it seems pulsar PR builds are unstable and they are failing in most of the PRs. Failures don't seem related to this PR.

**Comment by wolfstudy** [comment]
Move this change to 2.6.2, because the #8117 depends on this pr.

**Pull request merged**
