### PR TITLE
[Issue 3475][pulsar-client] Add cluster checking before operating tenants with it

### PR DESCRIPTION
**Pull request by murong00**
### Motivation

Fix https://github.com/apache/pulsar/issues/3475

### Modifications

Add cluster checking before operating tenants with it.

### CODE REVIEW

**Comment by murong00** [comment]
@merlimat Thanks, I will fix it later.

**Comment by murong00** [comment]
@merlimat @sijie PTAL, thanks!

**Comment by sijie** [comment]
run java8 tests

**Comment by murong00** [comment]
run java8 tests

**Pull request merged**
