### PR TITLE
[cleanup][ml] ManagedCursor clean up.

### PR DESCRIPTION
**Pull request by dao-jun**
### Motivation

Code clean up.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by Technoboy-** [comment]
Hi @dao-jun Could you merge the pr at least two reviews approval?

**Comment by codelipenghui** [comment]
@dao-jun The PR touched the critical path of Pulsar, we should wait for more reviewers to review the PR. If a PR get merged with one reviewer and merged in a few hours, the committers will lost the chance to review your PR and new potential risks might introduce to the Pulsar codebase. Now, so many companies are relaying on the stable release, even if this is a trivial changes to cleanup the managed cursor, give more time for other reviewer will still benefit Pulsar. WDYT?

**Comment by dao-jun** [comment]
> @dao-jun The PR touched the critical path of Pulsar, we should wait for more reviewers to review the PR. If a PR get merged with one reviewer and merged in a few hours, the committers will lost the chance to review your PR and new potential risks might introduce to the Pulsar codebase. Now, so many companies are relaying on the stable release, even if this is a trivial changes to cleanup the managed cursor, give more time for other reviewer will still benefit Pulsar. WDYT?

got it

**Comment by lhotari** [comment]
> > @dao-jun The PR touched the critical path of Pulsar, we should wait for more reviewers to review the PR. If a PR get merged with one reviewer and merged in a few hours, the committers will lost the chance to review your PR and new potential risks might introduce to the Pulsar codebase. Now, so many companies are relaying on the stable release, even if this is a trivial changes to cleanup the managed cursor, give more time for other reviewer will still benefit Pulsar. WDYT?
> 
> got it

@dao-jun It seems that this was merged without more reviews. I added a comment to the commit:
https://github.com/apache/pulsar/commit/532b0d9063474bd1c7ae8ac7cf5bd2d56b002164#r140287388
> does this change have a side-effect where it creates PositionImpl objects? A lot of effort has been put into reducing object allocations so that's why this could be causing a regression in that area.

**Comment by dao-jun** [comment]
@lhotari 
> It seems that this was merged without more reviews

Yes, my bad

**Comment by lhotari** [comment]
> > It seems that this was merged without more reviews
> 
> Yes, my bad

@dao-jun I'd recommend reverting the change that I have pinpointed in the comment https://github.com/apache/pulsar/commit/532b0d9063474bd1c7ae8ac7cf5bd2d56b002164#r140287388 , assuming that it creates new PositionImpl instances which were avoided before this change was made. /cc @codelipenghui

**Comment by dao-jun** [comment]
@lhotari I've replied your comment, https://github.com/apache/pulsar/commit/532b0d9063474bd1c7ae8ac7cf5bd2d56b002164#r140303950

**Pull request merged**
