### PR TITLE
[Issue 4510] A host can't connect and won't try other hosts again in multi-hosts service url configuration

### PR DESCRIPTION
**Pull request by kaynewu**
Fixes #<[4510](https://github.com/apache/pulsar/issues/4510)>

Master Issue: #<[4510](https://github.com/apache/pulsar/issues/4510)>

### Motivation
A host can't connect and won't try other hosts again in multi-hosts service url configuration

### Modifications

Check if the serverUrl is reachable when the client resolve Hosts

### CODE REVIEW

**Comment by jiazhai** [comment]
@kaynewu Thanks for fix this issue. would you please help add a tests for this case? There is a integration tests `AdminMultiHostTest` could be referenced.

**Comment by kaynewu** [comment]
Ok, my pleasure! I’ll work on it.Thanks Kaynewu 发自我的iPhone------------------ Original ------------------From: Jia Zhai  <notifications@github.com>Date: Sun,Jan 5,2020 9:00 PMTo: apache/pulsar <pulsar@noreply.github.com>Cc: kaynewu <wuzhongbomail@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [apache/pulsar] [4510] A host can't connect and won't try otherhosts again in multi-hosts service url configuration (#5986)@kaynewu Thanks for fix this issue. would you please help add a tests for this case? There is a integration tests AdminMultiHostTest could be referenced.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/apache/pulsar/pull/5986?email_source=notifications\u0026email_token=ABKRBCXMGBO2A5ILZTD2EI3Q4HKYHA5CNFSM4KCOPPD2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIDWOGA#issuecomment-570910488",
"url": "https://github.com/apache/pulsar/pull/5986?email_source=notifications\u0026email_token=ABKRBCXMGBO2A5ILZTD2EI3Q4HKYHA5CNFSM4KCOPPD2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIDWOGA#issuecomment-570910488",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by kaynewu** [comment]
> @kaynewu Thanks for fix this issue. would you please help add a tests for this case? There is a integration tests `AdminMultiHostTest` could be referenced.

A tests has been add in 'PulsarServiceNameResolverTest' , please have check!
thanks

**Comment by kaynewu** [comment]
> @kaynewu Thanks for fix this issue. would you please help add a tests for this case? There is a integration tests `AdminMultiHostTest` could be referenced.
@jiazhai 
A tests has been add in 'PulsarServiceNameResolverTest' , please have check!
thanks

**Comment by jiazhai** [comment]
@kaynewu Would you please help rebase on latest master? seems the former merge brings a lot of un-related changes in.

**Pull request closed without merging**
