### PR TITLE
[docs] Fix link issue for "Authentication and authorization in Pulsar" 

### LINKED ISSUE #5753: [Doc] link for  TLS Authentication on Proxies is dead
Expected behavior
Show a page / Enabling TLS Authentication on Proxies 
Actual behavior
404
Steps to reproduce
1、Open https://pulsar.apache.org/docs/zh-CN/security-authorization/
2、Click a link for  Enabling TLS Authentication on Proxies

### PR DESCRIPTION
**Pull request by belinda-wong**
Fixes #5753 

### Motivation

The link is dead. 

### Modifications

changed to: 
see ["Enabling TLS Authentication on Proxies"](security-tls-authentication.md#enable-tls-authentication-on-proxies)

### CODE REVIEW

**Comment by Jennifer88huang** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by Jennifer88huang** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by Jennifer88huang** [comment]
run java8 tests

**Pull request merged**
