### PR TITLE
[ Issue 14633] [pulsar-broker] Fix metadata store deadlock.

### LINKED ISSUE #14633: setupTopicPublishRateLimiterMonitor() can block forever, causing deadlock for metadata store operations
**Describe the bug**

(https://github.com/apache/pulsar/blob/2b3e8aeb5a1c259e0325e5a91dc5d7e20c6ee569/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L594)

This can block forever, causing metadata operations to deadlock.

"metadata-store-6-1" #61 prio=5 os_prio=0 cpu=139825.70ms elapsed=81027.01s tid=0x00007f1598001000 nid=0x8b waiting for monitor entry  [0x00007f15a7805000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at org.apache.pulsar.broker.service.BrokerService.setupTopicPublishRateLimiterMonitor(BrokerService.java:562)
        - waiting to lock <0x00000003018b1c30> (a org.apache.pulsar.broker.service.BrokerService)
        at org.apache.pulsar.broker.service.AbstractTopic.updatePublishDispatcher(AbstractTopic.java:920)
        at org.apache.pulsar.broker.service.AbstractTopic.updatePublishDispatcher(AbstractTopic.java:807)
        at org.apache.pulsar.broker.service.AbstractTopic.updateMaxPublishRate(AbstractTopic.java:770)
        at org.apache.pulsar.broker.service.persistent.PersistentTopic.onPoliciesUpdate(PersistentTopic.java:2424)
        at org.apache.pulsar.broker.service.BrokerService.lambda$null$81(BrokerService.java:1807)
        at org.apache.pulsar.broker.service.BrokerService$$Lambda$1326/0x00000008408bc440.accept(Unknown Source)
        at java.util.Optional.ifPresent(java.base@11.0.13/Optional.java:183)
        at org.apache.pulsar.broker.service.BrokerService.lambda$null$82(BrokerService.java:1807)
        at org.apache.pulsar.broker.service.BrokerService$$Lambda$1325/0x00000008408bc040.accept(Unknown Source)
        at java.util.concurrent.CompletableFuture.uniAcceptNow(java.base@11.0.13/CompletableFuture.java:753)
        at java.util.concurrent.CompletableFuture.uniAcceptStage(java.base@11.0.13/CompletableFuture.java:731)
        at java.util.concurrent.CompletableFuture.thenAccept(java.base@11.0.13/CompletableFuture.java:2108)
        at org.apache.pulsar.broker.service.BrokerService.lambda$null$83(BrokerService.java:1802)
        at org.apache.pulsar.broker.service.BrokerService$$Lambda$678/0x0000000840655840.accept(Unknown Source)
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387)
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159)
        at org.apache.pulsar.broker.service.BrokerService.lambda$handlePoliciesUpdates$84(BrokerService.java:1798)
        at org.apache.pulsar.broker.service.BrokerService$$Lambda$677/0x0000000840655440.accept(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(java.base@11.0.13/CompletableFuture.java:714)
        at java.util.concurrent.CompletableFuture.postComplete(java.base@11.0.13/CompletableFuture.java:506)
        at java.util.concurrent.CompletableFuture.complete(java.base@11.0.13/CompletableFuture.java:2073)
        at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$null$7(ZKMetadataStore.java:139)
        at org.apache.pulsar.metadata.impl.ZKMetadataStore$$Lambda$226/0x000000084034fc40.run(Unknown Source)
        at org.apache.pulsar.metadata.impl.AbstractMetadataStore$TaskWrapper.run(AbstractMetadataStore.java:99)
        at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.13/Executors.java:515)
        at java.util.concurrent.FutureTask.run(java.base@11.0.13/FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.13/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.13/ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(java.base@11.0.13/Thread.java:829)

**To Reproduce**
No reliable way to reproduce the problem, though we have seen this in production deployment.

**Expected behavior**
This method should not block.

### PR DESCRIPTION
**Pull request by bharanic-dev**
Fixes #14633 

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

### Motivation

https://github.com/apache/pulsar/blob/2b3e8aeb5a1c259e0325e5a91dc5d7e20c6ee569/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L1757

makes a blocking call to metadatastore operation (stack trace below) while holding a lock (due to the synchronized keyword). But the callback that completes the future can't execute (metadata-store executor is a single threaded executor) because the callback is blocked waiting for the lock held by this thread.

"pulsar-backlog-quota-checker-30-1" #88 prio=5 os_prio=0 cpu=662.90ms elapsed=81026.81s tid=0x00007f17031ce000 nid=0xa4 waiting on condition  [0x00007f15a631e000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.13/Native Method)
        - parking to wait for  <0x00000007c1f55408> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.13/LockSupport.java:234)
        at java.util.concurrent.CompletableFuture$Signaller.block(java.base@11.0.13/CompletableFuture.java:1798)
        at java.util.concurrent.ForkJoinPool.managedBlock(java.base@11.0.13/ForkJoinPool.java:3128)
        at java.util.concurrent.CompletableFuture.timedGet(java.base@11.0.13/CompletableFuture.java:1868)
        at java.util.concurrent.CompletableFuture.get(java.base@11.0.13/CompletableFuture.java:2021)
        at org.apache.pulsar.broker.resources.BaseResources.get(BaseResources.java:86)
        at org.apache.pulsar.broker.resources.NamespaceResources.getPolicies(NamespaceResources.java:105)
        at org.apache.pulsar.broker.service.BacklogQuotaManager.getBacklogQuota(BacklogQuotaManager.java:70)
        at org.apache.pulsar.broker.service.BacklogQuotaManager.getBacklogQuota(BacklogQuotaManager.java:82)
        at org.apache.pulsar.broker.service.BacklogQuotaManager.getBacklogQuotaLimitInSize(BacklogQuotaManager.java:101)
        at org.apache.pulsar.broker.service.persistent.PersistentTopic.isSizeBacklogExceeded(PersistentTopic.java:2502)
        at org.apache.pulsar.broker.service.BrokerService.lambda$monitorBacklogQuota$69(BrokerService.java:1611)
        at org.apache.pulsar.broker.service.BrokerService$$Lambda$713/0x00000008406a9840.accept(Unknown Source)
        at org.apache.pulsar.broker.service.BrokerService$$Lambda$709/0x00000008406a8840.accept(Unknown Source)
        at java.util.Optional.ifPresent(java.base@11.0.13/Optional.java:183)
        at org.apache.pulsar.broker.service.BrokerService.lambda$forEachTopic$68(BrokerService.java:1599)
        at org.apache.pulsar.broker.service.BrokerService$$Lambda$708/0x00000008406a8440.accept(Unknown Source)
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387)
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159)
        at org.apache.pulsar.broker.service.BrokerService.forEachTopic(BrokerService.java:1597)
        at org.apache.pulsar.broker.service.BrokerService.monitorBacklogQuota(BrokerService.java:1608)
        - locked <0x00000003018b1c30> (a org.apache.pulsar.broker.service.BrokerService)
        at org.apache.pulsar.broker.service.BrokerService$$Lambda$320/0x00000008403f4840.run(Unknown Source)
        at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:32)
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
        at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.13/Executors.java:515)
        at java.util.concurrent.FutureTask.runAndReset(java.base@11.0.13/FutureTask.java:305)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@11.0.13/ScheduledThreadPoolExecutor.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.13/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.13/ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(java.base@11.0.13/Thread.java:829)

https://github.com/apache/pulsar/blob/0a91196dcc4d31ae647867ed319b8c1af0cb93c6/pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java#L78

### Modifications

The synchronized keyword was added as part of https://github.com/apache/pulsar/pull/8045. This causes the deadlock. The synchronized is not really required as the topic datastructure is a concurrentHashMap.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

The fix was also verified in production. After deploying the broker deadlocks and restarts went away.

### Documentation
- [x] `no-need-doc` 

Internal fix. Not user visible.

### CODE REVIEW

**Comment by Jason918** [comment]
> The synchronized keyword was added as part of #14367.

It's added in #8045

**Review by Jason918 — COMMENTED** [review]
I think this `synchronized` is used to avoid concurrent invoke from timer and admin api.
We should call like 
`backlogQuotaChecker.execute(safeRun(this::monitorBacklogQuota));` in `org.apache.pulsar.broker.admin.impl.BrokersBase#backlogQuotaCheck`

**Comment by bharanic-dev** [comment]
> 

Ah, that makes sense. I will make the change suggested.

**Comment by bharanic-dev** [comment]
@Jason918 PTAL when you get a chance.

**Review by codelipenghui — APPROVED** [review]
Nice catch!

**Review by hangc0276 — APPROVED** [review]
Good job.

**Review by 315157973 — APPROVED** [review]

**Review by Jason918 — APPROVED** [review]

**Review by Shoothzj — APPROVED** [review]

**Pull request merged**
