### PR TITLE
[broker][monitoring][fix] fix `pulsar_subscription_msg_ack_rate`

### PR DESCRIPTION
**Pull request by tjiuming**
### Motivation

Currently, in branch 2.9, when set `exposeTopicLevelMetricsInPrometheus=true` and `exposeConsumerLevelMetricsInPrometheus=true`,  the value of `pulsar_subscription_msg_ack_rate` is always 0.0. The PR is supposed to fix it.

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Comment by HQebupt** [comment]
Why not cherry pick from master ?

**Comment by tjiuming** [comment]
> Why not cherry pick from master ?

Toooooo many conflicts to cherry-pick

**Comment by tjiuming** [comment]
@mattisonchao PTAL

**Review by mattisonchao — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
