### PR TITLE
fix some LGTM alerts

### PR DESCRIPTION
**Pull request by 1m2c3t4**
### Motivation

LGTM has raised some alerts during analysis of apache/pulsar (https://lgtm.com/projects/g/apache/pulsar/alerts/?mode=tree).

### Modifications

- Fixed 1 `Array index out of bounds` error in AbstractMetrics
- Fixed 3 cases of `Hashed value without hashCode definition` in NamespaceService
- Fixed 1 `Reference equality test of boxed types` in Policies
- Fixed 1 `Wrong NaN comparison` in ProducerStatsRecorderImpl
- Fixed 16 cases of `Inconsistent equals and hashCode` where equals had been overridden but hashCode was not

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API: ( no)
  - The schema: ( no )
  - The default values of configurations: (no)
  - The wire protocol: ( no)
  - The rest endpoints: (no)
  - The admin cli options: ( no)
  - Anything that affects deployment: (no )

### Documentation

  - Does this pull request introduce a new feature? ( no)

### CODE REVIEW

**Comment by merlimat** [comment]
retest this please

**Comment by merlimat** [comment]
run java8 test

**Comment by sijie** [comment]
run java8 test

**Comment by sijie** [comment]
run java8 tests

**Comment by 1m2c3t4** [comment]
It is not clear to me why that test is failing. ReplicatorTest passed for me locally, and after rebasing against master it still passed. It also doesn't look like something that would be related to the changes I made.

**Comment by sijie** [comment]
@1m2c3t4 replicator test is a flaky test.

// run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by 1m2c3t4** [comment]
Thanks for reviewing and merging @sijie @merlimat @rdhabalia

**Pull request merged**
