### PR TITLE
[client] Provide a clock for generating publish timestamp for producers

### PR DESCRIPTION
**Pull request by sijie**
*Motivation*

Currently producers uses `System.currentTimeMillis()` as publish timestamp by default.
However at some use cases, producers would like to a different way for generating publish timestamp.
E.g. in a database use case, a producer might be use HLC (Hybrid Logic Clock) as publish timestamp;
in integration tests, it might require the producer to use a deterministic way to generate publish timestamp.

*Changes*

This PR introduces a `clock` in building the client. This allows applications to override the system clock
with its own implementation.

*Verify the change*

Add unit test to test customized clock in both batch and non-batch cases.

### CODE REVIEW

**Comment by wolfstudy** [comment]
LGTM +1

**Comment by merlimat** [comment]
The change is fine, though it should be noted that the publish timestamp is being used in a couple of scenarios: 
 * TTL enforcement
 * Timestamp based seeks (eg: seek back 4h from CLI). 

Changing the clock source will then alter these features.

**Comment by sijie** [comment]
@merlimat updated the javadoc. PTAL

**Comment by sijie** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
run java8 tests

```
2019-06-21\T\03:52:43.502 [ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 173.029 s <<< FAILURE! - in org.apache.pulsar.functions.worker.PulsarFunctionStateTest
2019-06-21\T\03:52:43.503 [ERROR] setup(org.apache.pulsar.functions.worker.PulsarFunctionStateTest)  Time elapsed: 147.575 s  <<< FAILURE!
io.grpc.StatusRuntimeException: INTERNAL: http2 exception
	at io.grpc.Status.asRuntimeException(Status.java:530)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:699)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jiazhai** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by jiazhai** [comment]
mark this for 2.4.1 since this bring conflict of #4671

**Pull request merged**
