### PR TITLE
[fix][client] fix debug level

### PR DESCRIPTION
**Pull request by lordcheng10**
### Motivation
fix debug level

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Comment by lordcheng10** [comment]
@aloyszhang PTAL,thanks!

**Review by aloyszhang — APPROVED** [review]

**Review by Technoboy- — APPROVED** [review]

**Review by mattisonchao — APPROVED** [review]

**Review by RobertIndie — APPROVED** [review]

**Review by Shoothzj — APPROVED** [review]

**Pull request merged**
