### PR TITLE
[managed-ledger] close bk-client factory gracefully

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation
User can create tools on bookkeeper using ManagedLedger factory which provides [constructor](https://github.com/apache/pulsar/blob/master/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java#L121) to create ml-factory using self-managed bookkeeper (it's not used by broker).
So, in case of self-managed bk-client, ML-Factory couldn't shutdown it gracefully and we see issue: #4573

### Modification
- ML-Factory creates `DefaultBkFactory` to create self-managed bk-client and shutdowns same bk-client while closing the resource. 

cc: @yjshen

### CODE REVIEW

**Comment by sijie** [comment]
@yjshen please help review it and confirm if this pull request can address your problem or not.

**Comment by yjshen** [comment]
LGTM, thank you for working on this!

**Comment by sijie** [comment]
moved to 2.4.1 since 2.4.0 rc is cut.

**Comment by codelipenghui** [comment]
Since we need fix some issue and start 2.4.0-candidate-2, so move this pr back to 2.4.0.

**Pull request merged**
