### PR TITLE
Fixed # fixed string concatation in loop.

### PR DESCRIPTION
**Pull request by mattisonchao**
### Motivation

String is immutable objects and will affect performance when connected in a loop.

### CODE REVIEW

**Review by 315157973 — APPROVED** [review]
LGTM

**Review by lhotari — APPROVED** [review]

**Review by eolivelli — COMMENTED** [review]
Did you see some measurable improvement?

I am saying this because recently JVM handle string concatenation better that using StringBuilder in same cases and forcing a concatenation strategy sometimes it is not the best option.

That said I am not against this change, but I just want to know if this is the result of some static code analysis or it is fixing a real problem. You know the motto 'don't fix things that are not broken

**Comment by mattisonchao** [comment]
> Did you see some measurable improvement?
> 
> I am saying this because recently JVM handle string concatenation better that using StringBuilder in same cases and forcing a concatenation strategy sometimes it is not the best option.
> 
> That said I am not against this change, but I just want to know if this is the result of some static code analysis or it is fixing a real problem. You know the motto 'don't fix things that are not broken

Thanks for your suggestion, Could you provide me with some material on how the JVM improves the performance of string concatenation? I didn't find it~

**Comment by mattisonchao** [comment]
> Did you see some measurable improvement?
> 
> I am saying this because recently JVM handle string concatenation better that using StringBuilder in same cases and forcing a concatenation strategy sometimes it is not the best option.
> 
> That said I am not against this change, but I just want to know if this is the result of some static code analysis or it is fixing a real problem. You know the motto 'don't fix things that are not broken

Yes, I test it in a small example. when you use a string connection inline, the JVM will translate it to `StringBuilder` and invoke the `append` method to handle it.
the bytecode is as follows:
` L0
    LINENUMBER 6 L0
    LDC "abc"
    ASTORE 1
   L1
    LINENUMBER 7 L1
    NEW java/lang/StringBuilder
    DUP
    INVOKESPECIAL java/lang/StringBuilder.<init> ()V
    ALOAD 1
    INVOKEVIRTUAL java/lang/StringBuilder.append (Ljava/lang/String;)Ljava/lang/StringBuilder;
    LDC "d"
    INVOKEVIRTUAL java/lang/StringBuilder.append (Ljava/lang/String;)Ljava/lang/StringBuilder;
    INVOKEVIRTUAL java/lang/StringBuilder.toString ()Ljava/lang/String;
    ASTORE 1
   L2
    LINENUMBER 10 L2
    GETSTATIC java/lang/System.out : Ljava/io/PrintStream;
    ALOAD 1
    INVOKEVIRTUAL java/io/PrintStream.println (Ljava/lang/String;)V
   L3
    LINENUMBER 11 L3
    RETURN
   L4
    LOCALVARIABLE args [Ljava/lang/String; L0 L4 0
    LOCALVARIABLE a Ljava/lang/String; L1 L4 1
    MAXSTACK = 2
    MAXLOCALS = 2`

**Comment by mattisonchao** [comment]
> Did you see some measurable improvement?
> 
> I am saying this because recently JVM handle string concatenation better that using StringBuilder in same cases and forcing a concatenation strategy sometimes it is not the best option.
> 
> That said I am not against this change, but I just want to know if this is the result of some static code analysis or it is fixing a real problem. You know the motto 'don't fix things that are not broken

But if you try to connect String in a loop, they will create a lot of StringBuilder Object.
the bytecode is as follows:

```java
 L0
    LINENUMBER 6 L0
    LDC "abc"
    ASTORE 1
   L1
    LINENUMBER 7 L1
    ICONST_0
    ISTORE 2
   L2
   FRAME APPEND [java/lang/String I]
    ILOAD 2
    BIPUSH 10
    IF_ICMPGE L3
   L4
    LINENUMBER 8 L4
    NEW java/lang/StringBuilder
    DUP
    INVOKESPECIAL java/lang/StringBuilder.<init> ()V
    ALOAD 1
    INVOKEVIRTUAL java/lang/StringBuilder.append (Ljava/lang/String;)Ljava/lang/StringBuilder;
    LDC "d"
    INVOKEVIRTUAL java/lang/StringBuilder.append (Ljava/lang/String;)Ljava/lang/StringBuilder;
    INVOKEVIRTUAL java/lang/StringBuilder.toString ()Ljava/lang/String;
    ASTORE 1
   L5
    LINENUMBER 7 L5
    IINC 2 1
    GOTO L2
   L3
    LINENUMBER 10 L3
   FRAME CHOP 1
    GETSTATIC java/lang/System.out : Ljava/io/PrintStream;
    ALOAD 1
    INVOKEVIRTUAL java/io/PrintStream.println (Ljava/lang/String;)V
   L6
    LINENUMBER 11 L6
    RETURN
   L7
    LOCALVARIABLE i I L2 L3 2
    LOCALVARIABLE args [Ljava/lang/String; L0 L7 0
    LOCALVARIABLE a Ljava/lang/String; L1 L7 1
    MAXSTACK = 2
    MAXLOCALS = 3
```

**Comment by eolivelli** [comment]
@mattisonchao I am pretty sure that this code is not for JDK11.

when you build this code with JDK11 with target = 11 the result will be very different.

btw we are still building Pulsar for JDK8, so the change is good for me

**Comment by mattisonchao** [comment]
> @mattisonchao I am pretty sure that this code is not for JDK11.
> 
> when you build this code with JDK11 with target = 11 the result will be very different.
> 
> btw we are still building Pulsar for JDK8, so the change is good for me

Sorry, It's my mistake.
I re-run the code using Java 15 and its bytecode is as follows.
```java
// class version 59.0 (59)
// access flags 0x21
public class Test {

  // compiled from: Test.java
  // access flags 0x19
  public final static INNERCLASS java/lang/invoke/MethodHandles$Lookup java/lang/invoke/MethodHandles Lookup

  // access flags 0x1
  public <init>()V
   L0
    LINENUMBER 1 L0
    ALOAD 0
    INVOKESPECIAL java/lang/Object.<init> ()V
    RETURN
   L1
    LOCALVARIABLE this LTest; L0 L1 0
    MAXSTACK = 1
    MAXLOCALS = 1

  // access flags 0x9
  public static main([Ljava/lang/String;)V
   L0
    LINENUMBER 3 L0
    LDC "abc"
    ASTORE 1
   L1
    LINENUMBER 4 L1
    ICONST_0
    ISTORE 2
   L2
   FRAME APPEND [java/lang/String I]
    ILOAD 2
    BIPUSH 8
    IF_ICMPGE L3
   L4
    LINENUMBER 5 L4
    ALOAD 1
    INVOKEDYNAMIC makeConcatWithConstants(Ljava/lang/String;)Ljava/lang/String; [
      // handle kind 0x6 : INVOKESTATIC
      java/lang/invoke/StringConcatFactory.makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite;
      // arguments:
      "\u0001d"
    ]
    ASTORE 1
   L5
    LINENUMBER 4 L5
    IINC 2 1
    GOTO L2
   L3
    LINENUMBER 7 L3
   FRAME CHOP 1
    RETURN
   L6
    LOCALVARIABLE i I L2 L3 2
    LOCALVARIABLE args [Ljava/lang/String; L0 L6 0
    LOCALVARIABLE str Ljava/lang/String; L1 L6 1
    MAXSTACK = 2
    MAXLOCALS = 3
}
```

**Comment by mattisonchao** [comment]
> @mattisonchao I am pretty sure that this code is not for JDK11.
> 
> when you build this code with JDK11 with target = 11 the result will be very different.
> 
> btw we are still building Pulsar for JDK8, so the change is good for me

You are right. The JVM handles string concatenation better than using StringBuilder in some cases.
The doc is here: https://docs.oracle.com/javase/9/docs/api/java/lang/invoke/StringConcatFactory.html#makeConcat-java.lang.invoke.MethodHandles.Lookup-java.lang.String-java.lang.invoke.MethodType-

**Comment by mattisonchao** [comment]
Finally, thank you for your suggestions. My friend ~ @eolivelli   👍

**Pull request merged**
