### PR TITLE
[#3944][dashboard]Dashboard authentication support for JWT token

### PR DESCRIPTION
**Pull request by skyrocknroll**
Signed-off-by: Yuvaraj Loganathan <uvaraj6@gmail.com>

<--
### Contribution Checklist
 * Added support for jwt token authentication. 
*  Feature is documented
* Added logging

### CODE REVIEW

**Comment by skyrocknroll** [comment]
@sijieg please review

**Comment by sijie** [comment]
run java8 tests

**Comment by skyrocknroll** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by skyrocknroll** [comment]
locally it works and does not break.

**Comment by sijie** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by skyrocknroll** [comment]
run java8 tests

**Comment by skyrocknroll** [comment]
[ERROR] Failed to execute goal com.mycila:license-maven-plugin:3.0:format (default-cli) on project dashboard-docker-image: Execution default-cli of goal com.mycila:license-maven-plugin:3.0:format failed: Cannot read header document src/license-header.txt. Cause: Resource src/license-header.txt not found in file system, classpath or URL: no protocol: src/license-header.txt

**Comment by jerrypeng** [comment]
rerun tests

**Comment by jerrypeng** [comment]
run java8 tests
run integration tests
rerun cpp tests

**Comment by jerrypeng** [comment]
run java8 tests
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by skyrocknroll** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by skyrocknroll** [comment]
WOW :1st_place_medal:  All the tests passed

**Pull request merged**
