### PR TITLE
[fix][test] Fix flaky test V1_ProducerConsumerTest#testActiveAndInActiveConsumerEntryCacheBehavior.

### PR DESCRIPTION
**Pull request by lordcheng10**
### Motivation
image
In PR: https://github.com/apache/pulsar/pull/17273, when the read position is updated, the ManagedLedgerImpl#onCursorReadPositionUpdated method will be called, and finally ManagedCursorContainer#cursorUpdated will be called, thus making the slowestReaderPosition change:

https://github.com/apache/pulsar/blob/0c7a0d144d9e527fbd25a1d738715934fbcf38ab/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L2633-L2639

Therefore, in testActiveAndInActiveConsumerEntryCacheBehavior, as long as the server pushes data to the client, the slowestReaderPosition will change.

So here the receive queue of the slower-subscriber is set to 1 to prevent the slowestReaderPosition from changing even if the subscription is not consumed.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/lordcheng10/pulsar/pull/31

### CODE REVIEW

**Review by Technoboy- — APPROVED** [review]

**Review by aloyszhang — APPROVED** [review]
LGTM

**Comment by lordcheng10** [comment]
@tisonkun PTAL,thanks!

**Review by tisonkun — APPROVED** [review]

**Pull request merged**
