### PR TITLE
[cleanup][broker] remove unneeded use of cleanCacheAndCloseReader

### PR DESCRIPTION
**Pull request by zhanghaou**
### Motivation

refer to this comment: https://github.com/apache/pulsar/pull/20613#discussion_r1241023422

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by zhanghaou** [comment]
Please take a look. @poorbarcode  @Technoboy-  @mattisonchao

**Comment by mattisonchao** [comment]
Please help clarify who'll close it.

**Comment by zhanghaou** [comment]
> Please help clarify who'll close it.

image

**Comment by coderzc** [comment]
We should not remove `cleanCacheAndCloseReader` here since the caller did not handle the exception future.

**Comment by zhanghaou** [comment]
> We should not remove `cleanCacheAndCloseReader` here since the caller did not handle the exception future.

Oh, you are right, make some code clean up.

**Pull request closed without merging**
