### PR TITLE
[improve][txn] Move checked exception into builder when newTransaction.

### PR DESCRIPTION
**Pull request by mattisonchao**
### Motivation

Submit this PR to discuss if we can accept moving this checked exception into the builder to avoid adding more useless try-catch blocks.

In practice, we should create the new transaction like this:

```java
final TransactionBuilder transactionBuilder;
try {
    transactionBuilder = client.newTransaction();
} catch (PulsarClientException e) {
    // handle this exception.
    return;
}
CompletableFuture<Transaction> txnFuture = transactionBuilder
        .withTransactionTimeout(1, TimeUnit.MINUTES)
        .build();
```
But this exception only throws by 

```java
 public TransactionBuilder newTransaction() throws PulsarClientException {
    if (!conf.isEnableTransaction()) {
        throw new PulsarClientException.InvalidConfigurationException("Transactions are not enabled");
    }
    return new TransactionBuilderImpl(this, tcClient);
}
```
Therefore, even if we enabled the transaction, we still need to handle this checked exception. Maybe we can move this checked exception into the builder or make this exception to be runtime to avoid writing the more useless try-catch blocks.

```java
client.newTransaction()
      .withTransactionTimeout(1, TimeUnit.MINUTES)
      .build()
      .thenCompose(transaction -> {
          // do somethings
      }).exceptionally(ex -> {
          // handle exception
      });
```
It is better, isn't it?

### Modifications

- Moving checked exceptions into the builder.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by congbobo184 — APPROVED** [review]
please add a test for it

**Review by eolivelli — APPROVED** [review]
LGTM

We should discuss on the ML, we dot not strictly need a PIP, but we should let the people know and chime in

**Comment by eolivelli** [comment]
@nicoloboschi PTAL

**Comment by mattisonchao** [comment]
The discussion email has been sent. https://lists.apache.org/thread/x3tqvosy6vgom5v45hr60nqslpfx42o7

**Review by RobertIndie — APPROVED** [review]

**Review by wenbingshen — APPROVED** [review]
nice work!

**Review by nicoloboschi — APPROVED** [review]

**Pull request merged**
