### PR TITLE
[pulsar-test] enable pooled netty allocator for unit-tests

### LINKED ISSUE #11750: Flaky-test: BrokerClientIntegrationTest.testConsumerWithPooledMessagesWithReader
BrokerClientIntegrationTest is flaky. The testConsumerWithPooledMessagesWithReader test method fails sporadically.

[example failure](https://github.com/apache/pulsar/pull/11748/checks?check_run_id=3399716676#step:9:2325)

```
Error:  testConsumerWithPooledMessagesWithReader(org.apache.pulsar.client.impl.BrokerClientIntegrationTest)  Time elapsed: 2.234 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertTrue(Assert.java:45)
	at org.testng.Assert.assertTrue(Assert.java:55)
	at org.apache.pulsar.client.impl.BrokerClientIntegrationTest.testConsumerWithPooledMessagesWithReader(BrokerClientIntegrationTest.java:1004)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by rdhabalia**
Fixes #11750

### Motivation
It fixes #11750 which has flaky test that fails because test checks if consumed payload is allocated in direct-memory and it doesn't give a guarantee to allocate message in direct-memory as default allocator is not pooled and therefore, sometime client accepts messages in non-pooled (heap-memory) allocator and test fails to validate message buffer type.

### CODE REVIEW

**Comment by lhotari** [comment]
It looks like there's a test which isn't compatible with pooled allocator. This test is failing:
```
Error:  Tests run: 7, Failures: 1, Errors: 0, Skipped: 6, Time elapsed: 4.129 s <<< FAILURE! - in org.apache.pulsar.broker.service.TransactionMarkerDeleteTest
Error:  testMarkerDelete(org.apache.pulsar.broker.service.TransactionMarkerDeleteTest)  Time elapsed: 0.018 s  <<< FAILURE!
java.lang.UnsupportedOperationException: direct buffer
	at io.netty.buffer.PooledUnsafeDirectByteBuf.array(PooledUnsafeDirectByteBuf.java:226)
	at org.apache.pulsar.broker.service.TransactionMarkerDeleteTest.testMarkerDelete(TransactionMarkerDeleteTest.java:122)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

It can be fixed by changing [line 108 in TransactionMarkerDeleteTest](https://github.com/apache/pulsar/blob/3fcfb22e71c9774f710d659030d4af01eb05c956/pulsar-broker/src/test/java/org/apache/pulsar/broker/service/TransactionMarkerDeleteTest.java#L108) from `ByteBuf payload = PooledByteBufAllocator.DEFAULT.buffer(0);` to `ByteBuf payload = PooledByteBufAllocator.DEFAULT.heapBuffer(0);`.

**Review by lhotari — APPROVED** [review]

**Comment by lhotari** [comment]
I pushed the fix to TransactionMarkerDeleteTest to this PR since it would be nice to get this PR merged asap to improve CI stability.

**Review by eolivelli — APPROVED** [review]
LGTM

I hope that this change won't introduce instability due to other leaks in the tests

**Comment by rdhabalia** [comment]
> I hope that this change won't introduce instability due to other leaks in the tests

I agree. one of the issue with  `-Dpulsar.allocator.pooled=true` is test starts leaking due to test-failure or missed to close/cleanup broker/client then we will see memory failure soon. So, I was thinking to revert back `-Dpulsar.allocator.pooled=false` and keep direct-memory check in if condition but before that this PR is merged now. let me create a PR and we can merge it if that makes sense.

**Pull request merged**
