### PR TITLE
remove legacy znode when delete namespace or tenant forcefully

### LINKED ISSUE #11195: Force delete tenant or namespace left un-used znode
**Describe the bug**
when delete a namespace or tenant forcefully,  there are some znodes not cleaned under `/manager-ledger`

**To Reproduce**
1. create a new tenant
```shell
bin/pulsar-admin tenants create force-delete
```
2. create a new namspace
```shell
bin/pulsar-admin namespaces create force-delete/force-delete
```
3. create a new topic
```shell
bin/pulsar-admin topics create force-delete/force-delete/topic
```
4. delelete namespace forcefully
```shell
 bin/pulsar-admin namespaces delete -f force-delete/force-delete
```

**Expected behavior**
znode under `/managed-ledger` path related to the deleted namespace should also be cleaned 

**Screenshots**
After force delete namespace `force-delete/force-delete`
image

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by aloyszhang**
Fixes #11195

### Motivation

Fix metadata not cleaned after delete namespace or tenant forcefully.

### Modifications
**For force delete of namespace**
Add delete for znode  `/managed-ledger/tenant/namespaces/persistent` , `/managed-ledger/tenant/namespaces/non-persistent` and  `/managed-ledger/tenant/namespaces`  if exist.

**For force delete of tenant**
Add delete for znode  `/managed-ledger/tenant` if exist.

### Verifying this change

This change added tests and can be verified as follows:

Add new test for force delete of namespace in `AdminApiTest.testDeleteNamespaceForcefully`
Extended test for force delete of tenant.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API: ( no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by aloyszhang** [comment]
@murong00 @BewareMyPower PTAL

**Review by BewareMyPower — APPROVED** [review]

**Comment by BewareMyPower** [comment]
LGTM, could you confirm if the ZK related API could be replaced with the metadata store API? @merlimat

**Review by sijie — APPROVED** [review]

**Comment by aloyszhang** [comment]
@BewareMyPower Do we need more discuss about this pull request?

**Comment by BewareMyPower** [comment]
I think we can merge it first.

**Pull request merged**
