### PR TITLE
[feature][pulsar-broker]: Add additional servlet support to broker

### PR DESCRIPTION
**Pull request by Demogorgon314**
### Motivation
Currently the broker does not support additional servlet, but some plugins need to add custom web routes on the broker.

### Modifications
Add additional servlet support to broker

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Review by sijie — APPROVED** [review]

**Comment by Anonymitaet** [comment]
@Demogorgon314 thanks for your great work. Would you like to add docs accordingly? Then you can ping me to review, thanks

**Comment by Demogorgon314** [comment]
> @Demogorgon314 thanks for your great work. Would you like to add docs accordingly? Then you can ping me to review, thanks

I think maybe we only need to add docs in the specific plugin?

**Comment by Anonymitaet** [comment]
@BewareMyPower @codelipenghui 

I've discussed w/ @Demogorgon314 and we have the following issues. Could you please help answer? Thanks

1. If we want to add docs for this PR, the docs are targeted for the developers who want to develop a plugin (for example, KoP), should we add this kind of docs to the **Development** chapter on the Pulsar doc website?

2. @BewareMyPower after you developing KoP, did you write this kind of docs? If so, where did you add? Thanks

**Comment by BewareMyPower** [comment]
@Anonymitaet AFAIK, there's no related docs. IMO, I agree to add this kind of docs to the Development chapter on the Pulsar doc website.

**Review by codelipenghui — APPROVED** [review]

**Comment by Anonymitaet** [comment]
@Demogorgon314 thanks for your great work. Would you like to add docs accordingly? Then you can ping me to review, thanks

**Comment by Demogorgon314** [comment]
> @Demogorgon314 thanks for your great work. Would you like to add docs accordingly? Then you can ping me to review, thanks
Thanks, I will add the docs later when I finish my work at hand.

**Comment by Anonymitaet** [comment]
Confirmed w @codelipenghui, @Demogorgon314 could you please help add the parameter and its description here (https://pulsar.apache.org/docs/en/next/reference-configuration/#broker) **before EOD 8/9**？Then you can ping me review, thanks

**Comment by Demogorgon314** [comment]
@Anonymitaet The docs is added in #11590 , please help me review, thanks.

**Pull request merged**
