### PR TITLE
Fixed links to RPM/Deb package signature files

### LINKED ISSUE #3370: CPP Client RPM sha512 links are broken
Hey folks,

sha512 signature RPM links for cpp client (the ones here: https://pulsar.apache.org/docs/en/client-libraries-cpp/) are broken on some mirrors, e.g. a mirror link for devel RPM is leading to 404: http://ftp.tudelft.nl/apache/pulsar/pulsar-2.2.1/RPMS/apache-pulsar-client-devel-2.2.1-1.x86_64.rpm.sha512

As mentioned by @merlimat these should only be fetched from Apache servers to guarantee authenticity, so website links need to be fixed.

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Fixes #3370 . The links should point to ASF dist server as the source of truth for package signatures.

### CODE REVIEW

**Comment by merlimat** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by jiazhai** [comment]
run integration tests

**Comment by merlimat** [comment]
run integration tests

**Pull request merged**
