### PR TITLE
Set default ensemble size to 2 in service conf, to match broker.conf

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

The values for `managedLedgerDefaultEnsembleSize`, `managedLedgerDefaultWriteQuorum` and `managedLedgerDefaultAckQuorum` are set to `1-1-1` in `ServiceConfiguration`. 

The actual default is set to `2-2-2` in `broker.conf`. These default settings should be matching.

### CODE REVIEW

**Comment by codelipenghui** [comment]
retest this please

**Comment by codelipenghui** [comment]
run cpp tests

**Comment by wolfstudy** [comment]
run java8 tests 
run cpp tests
run integration tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
run cpp tests
run java8 tests

**Comment by wolfstudy** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
> org.apache.pulsar.broker.service.BrokerBkEnsemblesTests.testCrashBrokerWithoutCursorLedgerLeak

run java8 tests

**Pull request merged**
