### PR TITLE
unload bundle causes topic fence, OpAddEntry NPE appears in addComple…

### PR DESCRIPTION
**Pull request by lightzhao**
…te. #17737

Fixes #unload bundle causes topic fence, OpAddEntry NPE appears in addComplete

Master Issue: #17737 

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [ ] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by lhotari — CHANGES_REQUESTED** [review]
by-passing this check doesn't make sense.

Why is the ledger null in the first place? Please share a stacktrace and more context about the issue.

**Comment by lhotari** [comment]
please see https://github.com/apache/pulsar/pull/15090/files#r846562410

**Comment by lhotari** [comment]
duplicates #15090

**Comment by lhotari** [comment]
This is a problem that should be fixed, but it would need a proper fix.

**Comment by lightzhao** [comment]
> by-passing this check doesn't make sense.
> 
> Why is the ledger null in the first place? Please share a stacktrace and more context about the issue.

OK, I'll take a look. Thank you

**Pull request closed without merging**
