### PR TITLE
Pulsar IO: implement --retain-key-ordering (KEY_SHARED subscription) for Sinks

### PR DESCRIPTION
**Pull request by eolivelli**
### Motivation
Currently (2.9) you cannot use a KEY_SHARED subscription for Pulsar Sinks.
You can already do it for Functions, by using `--retain-key-ordering`

### Modifications

This patch implements `--retain-key-ordering` for Sinks, the same way we do for Functions

### Verifying this change

This patch added tests

### Documentation

- [x] `doc-required`

### CODE REVIEW

**Review by lhotari — APPROVED** [review]
LGTM

**Review by nicoloboschi — APPROVED** [review]
+1

**Review by dlg99 — APPROVED** [review]

**Review by merlimat — APPROVED** [review]

**Comment by zzzming** [comment]
LGTM

**Review by michaeljmarshall — APPROVED** [review]

**Comment by Anonymitaet** [comment]
Hi @eolivelli for the doc side, the parameter explanation has been added to code files and shown on the pulsar-admin page (https://pulsar.apache.org/tools/pulsar-admin/2.10.0-SNAPSHOT/#sinks)

image

But this PR is still labeled w/ `doc-required`, do we need to explain/highlight it in Pulsar documentation?
If no, can you label this PR w/ `doc` since it already contains doc changes, thanks.

**Comment by eolivelli** [comment]
Cool!
I didn't know that we generate that documentation automatically!

I removed the doc label

**Pull request merged**
