### PR TITLE
Differentiate authorization between source/sink/function operations

### PR DESCRIPTION
**Pull request by srkukarni**
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #<xyz>

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #<xyz>

### Motivation

When doing any source/sink/function operation, we currently don't distinguish between sources, sinks and functions. However sources, sinks and functions are different operations, with different endpoints and often require different auth handling. This pr introduces a couple of new interfaces for checking auth for sources and sink operations.

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by jerrypeng** [comment]
@srkukarni my concern with this PR is BC.  Currently, if a user has "functions" permission, the user can run sources, sinks, and functions. With this change, a user has to now have the specific entitlement of sources/sinks to run them as well.

**Comment by srkukarni** [comment]
@jerrypeng That is indeed a concern. Any ideas on how to solve it?

**Comment by srkukarni** [comment]
Coming to think more about it, the existing sources/sinks will continue to run fine. Thus upon upgrade of cluster, things still will work ok, except that newer sources/sinks will need additional permissions. Couldn't that just be notes in upgrade process?

**Comment by jerrypeng** [comment]
@srkukarni can you add a note to the release notes about this?

**Comment by srkukarni** [comment]
Added

**Comment by wolfstudy** [comment]
cherry-pick the pull request to `branch-2.6`(2.6.1)

**Pull request merged**
