### PR TITLE
[fix] [admin] fix incorrect state replication.connected on API partitioned-topic stat

### PR DESCRIPTION
**Pull request by poorbarcode**
### Motivation

Pulsar will merge the variable `PartitionedTopicStatsImpl.replication[x].connected` by the way below when we call `pulsar-admin topics partitioned-stats`

``` java
this.connected = this.connected & other.connected
```

But the variable `connected` of `PartitionedTopicStatsImpl.replication` is initialized `false`, so the expression `this.connected & other.connected` will always be `false`.

Then we will always get the value `false` if we call `pulsar-admin topics partitioned-stats`.

### Modifications

make the variable `` of `PartitionedTopicStatsImpl` is initialized `true`

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: 
- https://github.com/poorbarcode/pulsar/pull/82

### CODE REVIEW

**Review by liangyepianzhou — APPROVED** [review]
Good catch!

**Comment by coderzc** [comment]
It seems that line-298 also needs to be changed.

**Comment by gaoran10** [comment]
I'm not sure why need to use the symbol `&`, if the metric change to `false`, it will always be false.

**Comment by poorbarcode** [comment]
Hi @gaoran10 

> I'm not sure why need to use the symbol &, if the metric change to false, it will always be false, maybe we can use the latest value directly.

Good idea, already fixed

**Comment by poorbarcode** [comment]
>  It seems that line-298 also needs to be changed.

fixed, Thanks

**Review by coderzc — APPROVED** [review]

**Review by congbobo184 — APPROVED** [review]

**Review by Technoboy- — APPROVED** [review]

**Pull request merged**
