### PR TITLE
[improve][build] Upgrade docker-maven-plugin to 0.45.0

### PR DESCRIPTION
**Pull request by nodece**
### Motivation

docker-maven-plugin keeps up to the latest version.

### Modifications

- Improve `docker-push` profile
- Remove tag goal, because build goal includes tag feature
- Upgrade docker-maven-plugin to 0.45.0

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Comment by lhotari** [comment]
@nodece does this make  #22754 and #22609  obsolete? Please close them in that case.

I forgot the reason why the tag goal is removed. please add a description.

**Comment by nodece** [comment]
@lhotari Thanks, Done.

**Review by shoothzj — APPROVED** [review]

**Review by lhotari — COMMENTED** [review]
LGTM

**Comment by lhotari** [comment]
@nodece One of the problems with the profile refactoring is that it breaks the current release process documented at https://pulsar.apache.org/contribute/release-process/#release-pulsar-30-and-later. I think that it would be better to revert the changes related to moving the profile to docker/pom.xml since many might have internal releases that break as a result.

**Comment by lhotari** [comment]
> If we push the image in the docker/pulsar or docker/pulsar-all directory, this PR will break the release process, otherwise, it works fine in the docker directory.
> 
> Usually, we will push images in the docker directory, what do you think?

well, the release process uses `-pl docker/pulsar,docker/pulsar-all`. It will break. Many others might have copied the similar command that is used in https://pulsar.apache.org/contribute/release-process/#release-pulsar-30-and-later .

**Comment by nodece** [comment]
@lhotari https://github.com/apache/pulsar/pull/23093 will fix that.

**Pull request merged**
