### PR TITLE
Replicated subscriptions - Create snapshots

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

3rd part of changes for PIP-33.  Includes the creation of the snapshots when the replicated subscriptions feature is enabled.

### CODE REVIEW

**Comment by merlimat** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by zymap** [comment]
> ### Motivation
> 3rd part of changes for PIP-36. Includes the creation of the snapshots when the replicated subscriptions feature is enabled.

@merlimat  PIP-33?

**Comment by merlimat** [comment]
@zymap that's indeed 33 :) . Fixed the description, thanks

**Pull request merged**
