### PR TITLE
[pulsar-client-tools] Adjust PulsarAdminException to ParameterException in cli.

### PR DESCRIPTION
**Pull request by RocMarshal**
### Motivation

Adjust PulsarAdminException to ParameterException in cli, which is more friendly when displaying error messages.

### Modifications

*pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API: (yes / **no**)
  - The schema: (yes / **no** / don't know)
  - The default values of configurations: (yes / **no**)
  - The wire protocol: (yes / **no**)
  - The rest endpoints: (yes / **no**)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / **no** / don't know)

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Review by yuruguo — APPROVED** [review]
Good catch!

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@RocMarshal The change looks good to me, could you please help add a unit test?

**Comment by RocMarshal** [comment]
@codelipenghui @yuruguo Glad to do it. Thanks for the review.

**Comment by RocMarshal** [comment]
@codelipenghui @yuruguo I added the test case for the PR based on your comments.
PTAL,Thank you very much.

**Comment by codelipenghui** [comment]
@RocMarshal Please help resolve the conflicts.

**Pull request merged**
