### PR TITLE
Don't consider deleted schema when checking compatibility

### PR DESCRIPTION
**Pull request by ivankelly**
feca5bbb changed topic delete logic to delete the schema when the
topic is deleted (though this only seems to be enabled for idle topic
GC). This exposed a bug in compatibility checking whereby if the a
subscription tries to attach to the topic, even if using the same
schema as had been used previously, a compatibility exception will be
thrown.

This is because the topic still appears to have a schema, even though
there is no actual schema data, just a tombstone. I've changed the logic
to return no schema if the schema read back is a tombstone.

The issue doesn't affect producers because the check was already
correct there.

I've also updated the check for transitive compatibility to remove the
prefix of schemas before the deleted schema. Previously this was
throwing an NPE on the broker as it couldn't decode the deleted
schema.

This issue was discovered by failures in the healthcheck. The check
period (5 minutes) was longer than the GC period (60 seconds). I would
expect it to hit quite often in other scenarios also.

### CODE REVIEW

**Comment by ivankelly** [comment]
CI won't pass until #4667 is merged.

**Comment by merlimat** [comment]
retest this please

**Comment by merlimat** [comment]
run cpp tests

**Comment by ivankelly** [comment]
rerun java8 tests

**Comment by codelipenghui** [comment]
rerun java8 tests

**Comment by jiazhai** [comment]
rerun java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by ivankelly** [comment]
@sijie @jiazhai @codelipenghui @merlimat you you take another look? I had to change the approach to strip the deleted schemas in getSchema, because a consumer _should_ be prevented from attaching with a schema if there is a producer currently producing without a schema.

**Comment by ivankelly** [comment]
rerun java8 tests

**Comment by ivankelly** [comment]
rerun integration tests

**Pull request merged**
