### PR TITLE
[refactor][broker] Optimize semantics

### PR DESCRIPTION
**Pull request by crossoverJie**
### Motivation

Make the code easier to read

### Modifications

`!isPresent()` -> `isEmpty()`

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository
PR in forked repository: https://github.com/crossoverJie/pulsar/pull/3

### CODE REVIEW

**Comment by lhotari** [comment]
@crossoverJie Please follow the instructions in https://github.com/apache/pulsar/actions/runs/3481081589/attempts/1#summary-9529786678 .

**Comment by crossoverJie** [comment]
PR in forked repository: https://github.com/crossoverJie/pulsar/pull/2

**Comment by crossoverJie** [comment]
> @crossoverJie Please follow the instructions in https://github.com/apache/pulsar/actions/runs/3481081589/attempts/1#summary-9529786678 .

Done, PTAL.

**Comment by RobertIndie** [comment]
@crossoverJie Seems that you haven't enabled the GitHub action in your repo.

**Comment by crossoverJie** [comment]
@rober
PTAL

**Review by RobertIndie — APPROVED** [review]

**Comment by crossoverJie** [comment]
@tisonkun PTAL

**Review by tisonkun — CHANGES_REQUESTED** [review]
I don't encourage barely code refactor since it can bring extra overhead to cherry-pick.

Code can be written in multiple style. As long as we don't have a (checkstyle) rule to assert the usage, it brings little value to do such changes.

@crossoverJie I suggest you spend more time investigating the reported bugs or potential enhancement. Applying your code style preference alongside those efforts. It's my understanding of how ASF's "earn authority" practices.

**Comment by tisonkun** [comment]
If you do have ideas on promoting a code style rule for Apache Pulsar, I suggest:

1. either add a checkstyle rule or integrate with other code style automation;
2. or make a proposal on soft code style rule by:
    1. Read the Coding Guide: https://pulsar.apache.org/coding-guide/
    2. Try to integrate it into the Contribution Guide's Development section: https://pulsar.apache.org/contribute/category/development
    3. Discuss and vote on the dev@ mailing list.

Here are how other communities/projects do it:

* Trino: https://github.com/airlift/codestyle
* TiDB: https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/code-style-and-quality-guide.html
* Kubernetes: https://www.kubernetes.dev/docs/guide/coding-convention/

The primary rule here is: such changes must be converged.

**Pull request closed without merging**
