### PR TITLE
[feat][io] Add support for partitioned tables

### PR DESCRIPTION
**Pull request by Dishwasha**
### Motivation
Databases like PostgreSQL support table partitioning which will
cause the table not to be found in getTableId for jdbc sink/sources.

### Modifications

Adding "PARTITIONED TABLE" to the types passed to getTables fixes this.

### Verifying this change

Unfortunately the test suite doesn't pass for me even before this change,
but I ran the following after re-building the connector and no longer get
the table not found message.

```bin/pulsar-admin sinks create --tenant mytenant--namespace mynamespace --name mysink --archive ./connectors/pulsar-io-jdbc-postgres-2.6.0.nar --inputs mytopic --sink-config-file ./connectors/postgres.yaml --processingGuarantees EFFECTIVELY_ONCE --parallelism 1```

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): no
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no
  - The rest endpoints: no
  - The admin cli options: no
  - Anything that affects deployment: no

### Documentation

  - Does this pull request introduce a new feature? yes
  - If yes, how is the feature documented? not applicable
  - If a feature is not applicable for documentation, explain why?
Supporting partitioned tables shouldn't have to be specifically mentioned in documentation
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

- [x] `doc-required`

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]

**Comment by tisonkun** [comment]
Merging...

Thanks for your contribution @Dishwasha!

Sorry for the late response. This patch is to be released on 2.12.0.

**Comment by momo-jun** [comment]
Hi @Dishwasha, do you have any updates for adding the docs? 
Since 2.11 has been released, now it's good timing to start the doc update in the next version.

**Comment by Dishwasha** [comment]
> Hi @Dishwasha, do you have any updates for adding the docs? Since 2.11 has been released, now it's good timing to start the doc update in the next version.

I am not an active maintainer of this project and made this extremely small contribution over 2 years ago.

**Comment by momo-jun** [comment]
@Dishwasha Thanks for letting me know. 
Ping @danpi to take a look.

**Comment by momo-jun** [comment]
Double-checked with @freeznet, we don't need to update docs for this enhancement. The support for partitioned tables was unexpectedly missed and this PR fulfilled that gap. Refreshing the doc label...

**Pull request merged**
