### PR TITLE
[Doc] Fix doc for chunked message related stats.

### PR DESCRIPTION
**Pull request by RobertIndie**
### Motivation

The current documentation has some incorrect statements in the description of the stats related to chunked messages.

### Modifications

* Fix doc for chunked message related stats.

### Documentation
  
- [x] `doc`

### CODE REVIEW

**Review by Anonymitaet — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Comment by BewareMyPower** [comment]
Add the `release/2.8.4` label to resolve the conflicts related to `ConsumerStats` like https://github.com/apache/pulsar/pull/15674

**Comment by BewareMyPower** [comment]
Remove the label, I'll migrate the code changes when cherry-picking PRs.

**Pull request merged**
