### PR TITLE
Remove broker mode to handle persistent/non-persistent topics separately

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

now, non-persistent topic is not experimental feature anymore so, as per #596 removing broker mode to load only specific type of topics.

### CODE REVIEW

**Comment by rdhabalia** [comment]
rerun cpp tests

**Comment by sijie** [comment]
@rdhabalia it seems that you didn't reply to my comment. this PR removed settings from configurations. these should be well thought and also well documented before merging this PR. otherwise it will cause confusions when people upgraded pulsar

**Comment by rdhabalia** [comment]
@sijie Oops..I missed to check your comment.
> otherwise it will cause confusions when people upgraded pulsar

This configuration was added because this was an experimental feature earlier and this config can avoid any conflict between persistent and np topic. However, this feature is now, matured enough and we know that np topic will not have any impact with persistent topic if they exist together into the same broker.

> these should be well thought and also well documented before merging this PR.

This PR should not have any -ve impact though we can document it. We already have issue created at #596. Do you think we should document it in somewhere in code or website?

**Comment by sijie** [comment]
@rdhabalia I think removing configuration settings is a kind of user impacting behaviors. we should document the removals in release notes.

**Comment by joefk** [comment]
I am not convinced that this should be removed - leave alone document this.

**Comment by rdhabalia** [comment]
@joefk actually it was a part of the plan as @merlimat suggested :https://github.com/apache/pulsar/pull/538#discussion_r129182185
when we introduced this non-persistent feature to remove this config and created issue #596 to track it.
The main argument @merlimat had that isolating based on topic-types did not work well in jms/activeMQ and if n/w bandwidth is the concern then it can be achieved with namespace isolation without impacting other tenants. also, broker doesn't allow more than 1K pending publish req per cnx to throttle on each cnx. so, decided to remove this config once feature is matured and if it's not being used. However, we can also revert the change if this one is really needed.
@merlimat any thought?

**Pull request merged**
