### PR TITLE
[][io-rabbitmq] Add `passive` to io-rabbitmq config options

### PR DESCRIPTION
**Pull request by seeday**
### Motivation

Sometimes I'd like to set rabbitmq connection options, but declaring a queue with different options causes an exception. Passive declaration of a queue makes the rmq client accept whatever options it was given, instead of us having to add a million arguments to the actual rmq connector.

### Modifications

Added a config option to the rmq source, as well as some tests. I think I updated the documentation correctly.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:

 - Added config tests to the relevant files

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API: (yes / **no**)
  - The schema: (yes / no / **don't know**)
  - The default values of configurations: (**yes** / no) adds a new configuration option for rmq sources
  - The wire protocol: (yes / **no**)
  - The rest endpoints: (yes / **no**)
  - The admin cli options: (yes / **no**)
  - Anything that affects deployment: (yes / **no** / don't know)

### Documentation

  - Does this pull request introduce a new feature? (**yes** / no)
  - If yes, how is the feature documented? (not applicable / **docs** / **JavaDocs** / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by codelipenghui** [comment]
@seeday could you please rebase to the master branch? There are some CI tests issues fixed on the master branch.

**Comment by codelipenghui** [comment]
move to 2.7.0 first since no any update.

**Comment by seeday** [comment]
Still a couple failing tests, but they look unrelated as far as I can tell.

**Pull request closed without merging**
