### PR TITLE
[fix][test] Disable ReuseFork for broker group 1

### PR DESCRIPTION
**Pull request by codelipenghui**
Fixes: #16382

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by merlimat — APPROVED** [review]

**Comment by mattisonchao** [comment]
Question: 
Why `ReuseFork` can affect this problem?

**Comment by nicoloboschi** [comment]
I don't think this is a correct fix. the problem in #16382 should be fixed with something like https://github.com/apache/pulsar/pull/15638. I'll try to finish the work in these days

**Comment by nicoloboschi** [comment]
just realized you re-enabled it in https://github.com/apache/pulsar/commit/56f96daf0620ecbd1360d8831eda86e77eaa3b06

**Comment by mattisonchao** [comment]
I think we don't need to cherry-pick this PR to branch 2.9, could you help to confirm it? @codelipenghui

**Pull request merged**
