### PR TITLE
[Branch-2.10] Revert [improve][broker] Require authRole is proxyRole to set originalPrincipal(#19455)

### PR DESCRIPTION
**Pull request by hangc0276**
### Motivation
PR https://github.com/apache/pulsar/pull/19455 introduced break change and has been cherry-picked to release branch-2.10. It will lead to users upgrading to the new release version authenticate failed. We need to revert all the related PRs.

### Modifications
- Revert "[fix][broker] Allow proxy to pass same role for authRole and originalRole (#19557)"
    This reverts commit 4da2487e5c4730732a882734ab09cac38e7c12c5.

- Revert "[fix][broker] Make authentication refresh threadsafe  (#19506)"     
    This reverts commit 26e10536773498cfd0a4514256456795658dd6d8.

- Revert "[fix][test] ProxyWithAuthorizationTest remove SAN from test certs (#19594)"  
    This reverts commit 14152fc5fb61ae7ffef22118fb59f29339fef5fd.

- Revert "[fix][broker] Correct MockAlwaysExpiredAuthenticationState test impl"
    This reverts commit 09f00eea93c019919147ea249201aa9f7930cdbc.

- Revert "[fix][broker] Call originalAuthState.authenticate in ServerCnx"
    This reverts commit 1935f070cf29d727f2b400139f05ba0d35dd5017.

- Revert "[improve][broker] Add test to verify authRole cannot change (#19430)"
    This reverts commit 0231ad30d78956dbc313701f9a20723db8abe0e5.

- Revert "[feat][broker] Cherry-pick tests from (#19409)"
    This reverts commit 557b72dd029c3fd8cc61caafe1ed2c84b97ba641.

- Revert "[improve][broker] ServerCnx: go to Failed state when auth fails (#19312)"
    This reverts commit 467cd3239f116cc20bed059483b03b1edcc131ec.

- Revert "[improve][broker] Require authRole is proxyRole to set originalPrincipal (#19455)"
    This reverts commit 6a599af216f4e7fe09e31732d128eccc9c2d7ec4.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by michaeljmarshall — CHANGES_REQUESTED** [review]
First, this is the wrong thing to change and should not all be reverted regardless of the PMC's decision.

Second, we need consensus on the private mailing list before we merge this.

**Comment by codelipenghui** [comment]
We have an acceptable solution for now. So that we don't need to revert this change, just push a fix to the release branches.
https://lists.apache.org/thread/q1k1krfjr8njdf8t3sy1ht4vg67s4x71 the discussion thread.

And @michaeljmarshall message me in Slack, he will open PR to fix it.

Thanks @hangc0276 and @michaeljmarshall

**Comment by michaeljmarshall** [comment]
@hangc0276, in my view, https://github.com/apache/pulsar/pull/19830 should supersede this PR once it is merged and cherry picked to 2.10. Is there a reason you proposed reverting so many other changes? Thanks.

**Comment by michaeljmarshall** [comment]
I don't think we should revert any of the other commits--I intentionally cherry picked each for a reason. With #19830 merged and cherry picked, the original intention of this PR is fulfilled. Please reopen if I missed something @hangc0276.

**Pull request closed without merging**
