### PR TITLE
Fixed reader cursor seek with disconnection

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Currently the seek() operation will first disconnect all the connected consumers and then reset the cursor. This was due initially to simplify the logic and avoid concurrent operations.

Adding it now, so that consumers won't get disconnected/reconnected while the seek is performed.

### CODE REVIEW

**Comment by codelipenghui** [comment]
@merlimat I have check the logic but not found how to handle that reset cursor to a historical position and then consumer call acknowledgeCumulative() with messageId which is dispatched to this consumer before. If disconnect all consumers while reset cursor, client will create new consumers, that's not going to happen. Maybe i missed something.

**Comment by codelipenghui** [comment]
retest this please

**Comment by merlimat** [comment]
> If we don't disconnect the consumers, how do consumers reset their state? e.g. pending queue, acknowledgement, and etc.

Consumers they won't reset, they just will see the messages restart from an earlier (or later) point in time. I don't believe that should affect the consumer logic since there will be no visible disruption from consumer perspective.

**Comment by merlimat** [comment]
> If disconnect all consumers while reset cursor, client will create new consumers, that's not going to happen

It can still happen, and actually it's more probable to happen the longer the ack is delayed from the receival of the message.

Even if the consumer session is recreated, a consumer can receive a message, then seek it's triggered and then it will call ack-cumulative returning the cursor to the previous position. 

An application that seeks while acking (either individual or cumulative) is bound to unpredictable behavior in any case, irrespective of the disconnection.

**Comment by wolfstudy** [comment]
@merlimat I changed the milestone to 2.4.2.

**Comment by jiazhai** [comment]
seems the [test failures](https://builds.apache.org/job/pulsar_precommit_java8/12631/) related with this change:
```
org.apache.pulsar.compaction.CompactionTest.testCompactorReadsCompacted
org.apache.pulsar.compaction.CompactionTest.testSeekEarliestAfterCompaction
org.apache.pulsar.compaction.CompactorTest.testCompactAddCompact
```

**Comment by jiazhai** [comment]
> > If we don't disconnect the consumers, how do consumers reset their state? e.g. pending queue, acknowledgement, and etc.
> 
> Consumers they won't reset, they just will see the messages restart from an earlier (or later) point in time. I don't believe that should affect the consumer logic since there will be no visible disruption from consumer perspective.

Maybe Sijie was concern about the messages that already cached in consumer client. We may need some handling to clean the cached messages?

**Comment by sijie** [comment]
@merlimat I wasn't sure how is the ordering guaranteed if we don't clean up the cached message. Can you clarify it?

**Comment by sijie** [comment]
Moved this to 2.5.0 since I think it requires some more discussions about the side effect of this change.

**Comment by sijie** [comment]
actually moved to 2.4.3

**Comment by bsideup** [comment]
FYI this one would make [Liiklus'](https://github.com/bsideup/liiklus) life so much easier.
Since Liiklus is not using Pulsar's offset storage, it performs "seek" on every partition, and it causes the other connections to disconnect, and, when they connect.... it seeks again 😂

**Comment by tuteng** [comment]
@merlimat Please rebase

**Comment by tuteng** [comment]
Move to 2.6.0, If it is necessary to merge into 2.4.3, please reply here.

**Comment by bsideup** [comment]
@tuteng this is a major issue when manual offset management is applied and blocks projects like Liiklus, see my previous comment:
https://github.com/apache/pulsar/pull/5278#issuecomment-555088289

It's been re-scheduled many times already, with promises to be fixed in the next patch release, yet the issue is still there and blocks us from progressing with Pulsar 😕

**Comment by tuteng** [comment]
@bsideup I got it, move to 2.4.3, ping @merlimat Please rebase for handle conflict

**Comment by bsideup** [comment]
@tuteng thank you so much!
I will continue keeping my eye on this change and try to test it once merged to double check that the issue is gone (or maybe even before the merge if you can ping me)

**Comment by tuteng** [comment]
run java8 tests

**Comment by sijie** [comment]
---

@codelipenghui @jiazhai @merlimat 

without sending a close consumer command to the client, the client will not clean the pre-fetched items in its queue. Hence resetting a cursor can result in dispatching duplicated items and unexpected behavior.

For example, in the following sequence,

1) a consumer is receiving messages. it already pre-prefetches 5 messages (1, 2, 3, 4, 5).
2) it only calls `receive` once. It receives a message `1`. there are 4 messages in the queue.
3) it calls `reset` to reset to message `0`. it is expecting to receive `1` for next `receive` call. but since 2-5 are still in the client cache. when it calls `receive`, it will receive `2`. 

IMO this violates the guarantee that pulsar provides.  

Looking more into this issue and checking the current implementation, it seems the current implementation seems to be ok and shouldn't have any side-effects on connections.

So I would like to step back and understand a bit more about the *problematic* behavior driving the motivation of this change.

@bsideup you mentioned the followings in your previous comment:

```
Since Liiklus is not using Pulsar's offset storage, it performs "seek" on every partition, and it causes the other connections to disconnect, and, when they connect.... it seeks again 😂
```

Can you clarify what do you observe "it causes the other connections to disconnect"? As far as I know, "close consumer" will not close a multiplexed connection. I am trying to understand what you have observed before.

**Comment by tuteng** [comment]
@bsideup Have you seen this reply from @sijie? It seems that there are still some problems and cannot be merged into 2.4.3.

**Comment by bsideup** [comment]
Hi @tuteng & @sijie,

Thanks for the ping!

> Can you clarify what do you observe "it causes the other connections to disconnect"? As far as I know, "close consumer" will not close a multiplexed connection. I am trying to understand what you have observed before.

I guess "connection" here should not be used as the underlying TCP connection is kept open, rather "session". On reset, Pulsar will close every session. So, the problem is:

1. we have N (where N > 1) "read sessions" open
2. on initialization, the logic performs "seek" operation, so that it starts reading from the offset recorded externally
3. *every* session gets closed when *any* of the sessions performs the seek
4. [go back to 2.]

This behaviour makes it impossible to store offsets outside of Pulsar due to the 2 -> 3 -> 2 loop

**Comment by tuteng** [comment]
@merlimat Do you have time to look at this issue?

**Comment by sijie** [comment]
@bsideup thank you for your updates? Do these N sessions belong to one subscription?

**Comment by bsideup** [comment]
@sijie yes, they listen to the same topic / partition with failover

**Comment by sijie** [comment]
@bsideup sorry. if they are in the same subscription, it is expected that all consumers in the same subscription to reset to the new cursor position if the cursor is reset from a correctness perspective. I see what can be improved here is when the broker disconnects the consumers, it can disconnect the *active* consumers only. For exclusive/failover subscription, it will only reset the consumer that is currently active. This seems to be a correct fix. @codelipenghui @merlimat what do you think?

**Comment by codelipenghui** [comment]
@merlimat I move it to 2.7.0 and feel free to move it back if you want to onboard it in 2.6.0.

**Comment by bsideup** [comment]
@codelipenghui it is sad to see it being moved over and over 😞

It is a blocker for failover subscriptions with external offset management, and the implemented behaviour is rather questionable.

What's the reason to move it (again)?

**Comment by codelipenghui** [comment]
@bsideup Thanks for your feedback, I didn't notice that it is a blocker before. I will move it back to 2.6.0 and could you please take a look at sijie's last comment? Is the approach works for you?

**Comment by codelipenghui** [comment]
@bsideup I have pushed a PR #7141 which based on sijie's comment https://github.com/apache/pulsar/pull/5278#issuecomment-578371324. Could you please help review the changes?

**Comment by bsideup** [comment]
@codelipenghui looks promising! Looking forward to trying it 👍

**Comment by codelipenghui** [comment]
@bsideup PR #7141 is merged. You can try out on the master branch. I will move this PR to 2.7.0 first since we need to prepare the 2.6.0 release.

**Comment by lhotari** [comment]
> PR #7141 is merged. You can try out on the master branch. I will move this PR to 2.7.0 first since we need to prepare the 2.6.0 release.

@codelipenghui  PR #7141 doesn't seem to help with Pulsar Readers since Readers are always using exclusive subscriptions under the covers (https://github.com/apache/pulsar/blob/208af7cd7e718d378707df4aba600be3202e23df/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ReaderImpl.java#L48). Since a Pulsar Reader wraps a Consumer internally, I was thinking of the possibility of using a NonDurable Consumer directly without the Reader "wrapper". However this approach fails because creating NonDurable Consumers remains broken, that I have reported as #7436.

@codelipenghui would it be possible to extend the solution that was made in #7141 to also cover Readers?
I'm having issues with using seekAsync + hasMessageAvailableAsync on Readers. It seems that there are race conditions because of the current solution that  disconnects from the broker side after the seek. The usage of seek + hasMessageAvailableAsync in Readers isn't deterministic at all. There's a separate issue about the issues with hasMessageAvailabe after seek, that's #7796 .

**Pull request closed without merging**
