### PR TITLE
[Broker] Update Authz Check Before Completing Topic Level Policy Operation

### PR DESCRIPTION
**Pull request by michaeljmarshall**
### Motivation

There are several calls in the v2/PeristentTopics endpoint class that are supposed to require tenant admin permission but only verify LOOKUP permission. These endpoints are all annotated with `@ApiResponse(code = 403, message = "Don't have admin permission")`. It seems to me that these should properly verify tenant admin privileges.

### Modifications

* Update the `preValidation` method in the `PersistentTopicsBase` class to run the `validatePoliciesReadOnlyAccess()` for all write operations and to run an appropriate `validateTopicPolicyOperation(topicName, policyName, policyOperation)` check for all methods.
    * When reading through these changes, please make sure that the `PolicyName` and the `PolicyOperation` make sense for the method.
* Remove the few pre-existing authz checks to prevent duplicate checks for authz.
* Add new `PolicyName` for `MAX_MESSAGE_SIZE`.

### Verifying this change

I verified this bug against a pulsar 2.8.0 broker. The broker authenticates the user, but only requires lookup permission, not tenant admin privilege.

I added new tests to cover these changes.

### Does this pull request potentially affect one of the following parts:

This change will introduce authorization checks that require tenant admin privilege instead of just produce/consumer permission. It is a correction in the behavior, as these checks were supposed to take place already (at least the annotations indicate that).

### Documentation

I don't believe any documentation is required, as this only corrects behavior. It would be good to include this fix in the release notes.

### CODE REVIEW

**Comment by michaeljmarshall** [comment]
@sijie, @merlimat, @codelipenghui, @eolivelli, @KannarFr - PTAL

**Comment by eolivelli** [comment]
I would add at least end to end tests

**Review by gaoran10 — COMMENTED** [review]
Overlooks good to me, but I'm not sure there are enough tests to protect these changes.

**Comment by michaeljmarshall** [comment]
@gaoran10 and @eolivelli - thank you for your feedback. In writing the tests, I discovered that my initial comments were overstated. There is an authorization check in the `preValidation` method. The check comes when the `getPartitionedTopicMetadataAsync` is called from the `preValidation` method. In `getPartitionedTopicMetadataAsync`, we run the following check:

https://github.com/apache/pulsar/blob/d57c1d29ffeee7a6f17a77e5d198892c6d1cdd27/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java#L445

This check however does not use the `allowTopicPolicyOperationAsync` method from the `AuthorizationProvider` interface. It instead only verifies that a given role can `lookup` a given topic, and if a role can do that, then they can modify that topic's policies.

It looks like the `allowTopicPolicyOperationAsync` is a recently added method. Now that we have this dedicated method, I think we should use it. Further, note that all of the endpoints I modified are annotated with the following:

```java
@ApiResponse(code = 403, message = "Don't have admin permission")
```

This implies to me that the original design was to only allow modification of the topic policy endpoints by tenant admins, not just roles with produce/consume permission.

Please let me know what you think. Thanks!

**Review by 315157973 — COMMENTED** [review]
It seems that PolicyOperation is not handled in PulsarAuthorizationProvider#allowTopicPolicyOperationAsync, you add these PolicyOperation will eventually be ignored. This feature looks unfinished.

In addition, your unit tests all cover admin permissions. Can they cover PolicyOperation.WRITE permissions?

**Comment by KannarFr** [comment]
> It seems that PolicyOperation is not handled in PulsarAuthorizationProvider#allowTopicPolicyOperationAsync, you add these PolicyOperation will eventually be ignored. This feature looks unfinished.

Correct. The default authZ provider is not using it. I don't think it's unfinished: it's just about missing granularity in the pulsar internal permissions management.

FYI [biscuit-pulsar ](https://github.com/CleverCloud/biscuit-pulsar/blob/master/src/main/java/com/clevercloud/biscuitpulsar/AuthorizationProviderBiscuit.java#L460) (an external authN/authZ provider) uses it.

**Comment by 315157973** [comment]
> > It seems that PolicyOperation is not handled in PulsarAuthorizationProvider#allowTopicPolicyOperationAsync, you add these PolicyOperation will eventually be ignored. This feature looks unfinished.
> 
> Correct. The default authZ provider is not using it. I don't think it's unfinished: it's just about missing granularity in the pulsar internal permissions management.
> 
> FYI [biscuit-pulsar ](https://github.com/CleverCloud/biscuit-pulsar/blob/master/src/main/java/com/clevercloud/biscuitpulsar/AuthorizationProviderBiscuit.java#L460) (an external authN/authZ provider) uses it.

We need a default implementation class

**Comment by KannarFr** [comment]
Sure, but there is currently no permissions management on topics, correct?

**Comment by michaeljmarshall** [comment]
@315157973 and @KannarFr - what is the right path forward here? This PR is at least helpful in adding tests that assert failure when a call is made with insufficient authorization. Do we need some interface implemented or should I close this PR and open a new one with the just the tests? The current implementation actually throws a 401, not a 403 as the annotations indicate, so those might need updating too. Thanks.

**Comment by 315157973** [comment]
@codelipenghui  PTAL

**Comment by codelipenghui** [comment]
The pr had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale and conflict. Please rebase and resubmit the patch if it's still relevant.

**Pull request closed without merging**
