### PR TITLE
limiting batch size to the minimum of the maxNumberOfMessages and maxSizeOfMessages

### PR DESCRIPTION
**Pull request by avimas**
Batch size is not limited to the minimum of the maxNumberOfMessages and maxSizeOfMessages from the BatchRecieve policy.

 1. Batch size is not limited to the minimum of the maxNumberOfMessages and maxSizeOfMessages from the BatchRecieve policy.
I think this issue can be easly fixed by changing the canAdd function in MessagesImpl from:
```
protected boolean canAdd(Message<T> message) {
    if (this.maxNumberOfMessages <= 0 && this.maxSizeOfMessages <= 0L) {
        return true;
    } else {
        return this.maxNumberOfMessages > 0 && this.currentNumberOfMessages + 1 <= this.maxNumberOfMessages || this.maxSizeOfMessages > 0L &&   this.currentSizeOfMessages + (long)message.getData().length <= this.maxSizeOfMessages;
    }
}
```
to (changing the condintion in the else to && instead of ||):
```
protected boolean canAdd(Message<T> message) {
    if (this.maxNumberOfMessages <= 0 && this.maxSizeOfMessages <= 0L) {
        return true;
    } else {
        return (this.maxNumberOfMessages > 0 && this.currentNumberOfMessages + 1 <= this.maxNumberOfMessages) && (this.maxSizeOfMessages > 0L &&   this.currentSizeOfMessages + (long)message.getData().length <= this.maxSizeOfMessages);
    }
}
```

2. When the batch size is higher than the recieveQ of the consumer (I used a batch size of 3000 and a receiveQ of 500) I noticed the following issues:
	a. In a mutliTopic (pattern) consumer the client stops receiving any messages I think it getting paused and never resumed when setting a timeout in the batch policy, only one batch is fetched and the client never resumed.

talked with @codelipenghui  and advised to open this pull request

### CODE REVIEW

**Comment by jiazhai** [comment]
would like to remove it from 2.5.2

**Comment by codelipenghui** [comment]
@avimas Could you please help rebase to the master branch? There are some CI test fix on master branch.

**Comment by avimas** [comment]
> @avimas Could you please help rebase to the master branch? There are some CI test fix on master branch.

Done!

**Comment by codelipenghui** [comment]
@avimas Please rebase again, I can't push to your master branch. It's better to checkout -b a new branch to create a pull request. #7173 has fix some issues with CI tests.

**Comment by avimas** [comment]
@codelipenghui  rebase done, I'll make sure to use a new branch next time.

**Comment by codelipenghui** [comment]
@avimas Could you please take a look at the failed CI tests? look related to this PR.

**Comment by codelipenghui** [comment]
move to 2.7.0 first.

**Pull request merged**
