### PR TITLE
[fix] [broker] disable loadBalancerMemoryResourceWeight by default

### PR DESCRIPTION
**Pull request by thetumbled**
### Motivation

We have deprecated `loadBalancerMemoryResourceWeight` in PR: https://github.com/apache/pulsar/pull/19559, because the memory usage increase all the way until the GC reclaim the space, thus there is no relation between the actual load with the memory usage.
But PR: https://github.com/apache/pulsar/pull/19559 don't remove all usage of this conf, there is still some logic using this deprecated conf. Meanwhile, there is a try to enhance the memory usage collection by Lari (https://github.com/apache/pulsar/issues/21973), so there is possibilty that we may enable this conf again if the memory usage is proved to be related with the actual load.
Based on info aboved, i think that we have better to make the default value of deprecated `loadBalancerMemoryResourceWeight` to 0, in such way we can avoid the interference from the memory usage and waiting for Lari's enhancement.

### Modifications

Change the default value of `loadBalancerMemoryResourceWeight` to 0.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by thetumbled** [comment]
PTAL, thanks. @lhotari @Demogorgon314 @heesung-sn @BewareMyPower

**Comment by thetumbled** [comment]
I start a discussion for this pr: https://lists.apache.org/thread/qpdvyytk8y7x8yzh35jshksnl6498y3r, looking forward to your feedback.

**Review by BewareMyPower — APPROVED** [review]

**Review by Demogorgon314 — APPROVED** [review]

**Review by heesung-sn — APPROVED** [review]

**Pull request merged**
