### PR TITLE
[proxy] Proxy doesn't use the right ca certicate to connect to brokers

### PR DESCRIPTION
**Pull request by sijie**
*Motivation*

Currently proxy uses the proxy ca certicate to connect to brokers.
It is fine if proxy and broker are using th same CA. However if the broker
is using a different CA than proxy, "HTTP 502 Bad Gateway" is returned from proxy
when tlsEnabledWithBroker is set to true.

*Modifications*

Change to use the right CA

*Verify this change*

Confirmed it is working in a production environment with this fix.

The unit tests can be tricky. As all our current testing infra is using same CA.

### CODE REVIEW

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run cpp tests
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Pull request merged**
