### PR TITLE
[fix][schema-understand][docs] Updated example section

### PR DESCRIPTION
**Pull request by mans2singh**
### Modifications

* The document states that <code>**You** application reads the messages</code>.  Updated to state <code>**Your** application reads the messages</code>

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): no
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no
  - The rest endpoints: no
  - The admin cli options: no
  - Anything that affects deployment: no

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [ ] `no-need-doc` 
(Please explain why)
  
- [x] `doc` 
(Your PR contains doc changes)

- [ ] `doc-added`
(Docs have been already added)

### CODE REVIEW

**Review by Anonymitaet — COMMENTED** [review]
Thanks for your contribution!

Would you mind fixing this issue in other doc versions?
image


cc @momo-jun

**Comment by mans2singh** [comment]
@Anonymitaet  - 

Thanks for your review and feedback.

I've update the versioned docs based on your recommendations.  Please let me know if there is anything else required.  

Thanks

**Comment by mans2singh** [comment]
Thanks @Anonymitaet for your time and advice.

**Comment by Anonymitaet** [comment]
@mans2singh thanks for your contribution! Feel free to improve more 😊

**Pull request merged**
