### PR TITLE
[Managed Ledger] Fix the incorrect total size when BrokerEntryMetadata is enabled

### PR DESCRIPTION
**Pull request by BewareMyPower**
### Motivation

When the BrokerEntryMetadata is enabled, the total size in `ManagedLedgerImpl` is inaccurate. Because when the total size is updated in `OpAddEntry#safeRun`, the `dataLength` is the initial size of `data` when `OpAddEntry` is constructed, but `data` could be changed via `setData` method.

The inaccurate total size could affect the retention size validation. Because in `ManagedLedgerImpl#internalTrimLedgers`, the total size reduces by the size of `LedgerInfo`, which is assigned from the `LedgerHandle#getLength()`. Therefore, the total size will become 0 or less before all ledgers are removed.

### Modifications

- Update `dataLength` field in `setData` method.
- Add a `testManagedLedgerTotalSize` test to `BrokerEntryMetadataE2ETest`. It produces 10 messages and trigger the rollover manually so that the first `LedgerInfo` of the managed ledger contains the correct total bytes. Then compare the `totalSize` field with it to verify this fix works.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change added test `BrokerEntryMetadataE2ETest#testManagedLedgerTotalSize`.

### CODE REVIEW

**Comment by codelipenghui** [comment]
@BewareMyPower 

> but data could be changed via setData method.

Can we update the dataLength when calling setData()? We might get different value by readableBytes() which there is a reader read the data from the buffer.

**Comment by eolivelli** [comment]
> @BewareMyPower
> 
> > but data could be changed via setData method.
> 
> Can we update the dataLength when calling setData()? We might get different value by readableBytes() which there is a reader read the data from the buffer.

+1

**Comment by BewareMyPower** [comment]
@codelipenghui @eolivelli done.

**Review by codelipenghui — APPROVED** [review]
Nice catch!

**Pull request merged**
