### PR TITLE
Removed mentions to incubator-pulsar

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Removed mentions to incubator-pulsar

### CODE REVIEW

**Comment by massakam** [comment]
It seems that this part should be removed.
https://github.com/apache/incubator-pulsar/blob/152e5a3ed6e9b9c4c2446a9d893ba8c863d9700c/distribution/offloaders/src/assemble/offloaders.xml#L31-L35

**Comment by merlimat** [comment]
Good catch @massakam. Removed the rerefence to DISCLAIMER

**Comment by merlimat** [comment]
run cpp tests 
run java8 tests

**Comment by merlimat** [comment]
run cpp tests
run integration tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
retest this please

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by merlimat** [comment]
run cpp tests

**Pull request merged**
