### PR TITLE
Add option to support message key and message properties

### PR DESCRIPTION
**Pull request by ltamber**
### Motivation

This change allows a user of the pulsar-client to produce message with key and properties, and print these in the consume output.

### CODE REVIEW

**Comment by ltamber** [comment]
run unit tests

**Comment by sijie** [comment]
retest this please

**Comment by ltamber** [comment]
@sijie It seems that some exception thrown by other unit test.  What should I do ?

**Comment by tuteng** [comment]
run java8 tests

**Comment by tuteng** [comment]
run java8 tests

**Pull request merged**
