### PR TITLE
[fix][admin][doc] Fix set-persistent admin doc

### PR DESCRIPTION
**Pull request by tjiuming**
### Motivation

fix the default value of namespace/topic set-persistent command. see: https://github.com/apache/pulsar/blob/master/pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/PersistencePolicies.java#L34

### Documentation

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by tjiuming** [comment]
image
image
image

**Review by Anonymitaet — APPROVED** [review]

**Review by tisonkun — CHANGES_REQUESTED** [review]
I check the option config for `SetPersistence` command and it shows that the default of `bookkeeper-ensemble` is exact 0. What's your source of changing this default value in docs?

https://github.com/apache/pulsar/blob/05e6f5e3c71426ee30a8ad1852456f7be897bdf3/pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java#L1380-L1382

**Comment by zymap** [comment]
Because we have the default value, I think we can remove the required mark and set the default value as 2, and add the validation for the arguments, then the doc would update to the correct default value automatically.

**Comment by tisonkun** [comment]
@zymap perhaps @tjiuming just integrate this comment into this PR?

**Comment by zymap** [comment]
sounds good

**Comment by tjiuming** [comment]
fixed in https://github.com/apache/pulsar/pull/18999

**Review by tisonkun — APPROVED** [review]
LGTM. Please merge this one after https://github.com/apache/pulsar/pull/18999 gets merged

**Review by liangyepianzhou — APPROVED** [review]

**Comment by momo-jun** [comment]
@tjiuming The source of docs has been moved to [the pulsar-site repo](https://github.com/apache/pulsar-site). Can you pls resubmit a PR to the pulsar-site repo and link back to this one?

**Comment by tisonkun** [comment]
Closing...

I'm going to pick this patch to the site repo later.

**Pull request closed without merging**
