### PR TITLE
Broker considers fail-over consumer priority-level

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

Right now, Broker selects failover consumer based on lexicographical sorting on consumer name. However, one of the user has usecase to switch fail-over consumer (based on hot/cold colo)in a deterministic way without changing/managing consumer-name. Consumer already has priority-level but it's not implemented in Failover consumer which can be useful in certain usecase.

### Modifications

Broker also considers consumer's priority-level while selecting active consumer.

### CODE REVIEW

**Comment by rdhabalia** [comment]
> Can you also clarify on the ConsumerBuilder javadoc how the priority is being used?

yes, added.

**Comment by rdhabalia** [comment]
run java8 tests

**Comment by rdhabalia** [comment]
> how would this impact the assignment across multiple partitions?

priority-level gets configured at consumer level so, each partitioned-consumer will present its priority-level to broker and broker chooses active consumer for each partition. Each partitioned will be a separate topic so, there will not be any behavior difference in case of multiple partitions.

**Comment by merlimat** [comment]
The question is that broker is using ordinal position for consumers to ensure even distribution. 

Simple example: 4 partitions, 2 consumers. With equal priorities, they 

partition | consumer
-------| ----
 t-partition-0 | c-1 
 t-partition-1 | c-2 
 t-partition-2 | c-1 
 t-partition-3 | c-2 

If I set c-1 with higher priority, I would expect to have c1 on all the partitions. however the priority will only affect the sorting, so each partition will see the same list of consumers `[c1, c2]`, ordered by priority, but will keep doing the same assigment as above, given that on partition-3 with chose the consumer index with `N % len(consumers)`

**Comment by rdhabalia** [comment]
@merlimat fixed it.

**Comment by rdhabalia** [comment]
rerun integration tests

**Comment by sijie** [comment]
@rdhabalia can you rebase this issue to latest master?

**Comment by rdhabalia** [comment]
retest this please

**Comment by rdhabalia** [comment]
retest this please

**Comment by rdhabalia** [comment]
retest this please

**Comment by rdhabalia** [comment]
rerun integration tests

**Comment by rdhabalia** [comment]
rerun integration tests

**Comment by rdhabalia** [comment]
rerun integration tests

**Comment by rdhabalia** [comment]
rerun java8 tests

**Comment by rdhabalia** [comment]
rerun java8 tests

**Pull request merged**
