### PR TITLE
[cleanup][broker][Modernizer] fix violations in pulsar-broker

### PR DESCRIPTION
**Pull request by youzipi**
Master Issue: #12271 #16991 

### Motivation

Apply Maven Modernizer plugin to enforce we move away from legacy APIs.

### Modifications

- fix violations in pulsar-broker package.

### Verifying this change

This change is already covered by existing tests, such as *(please describe tests)*.

### Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

- [x] `doc-not-needed` 

### Matching PR in forked repository

PR in forked repository: https://github.com/youzipi/pulsar/pull/2

### CODE REVIEW

**Comment by youzipi** [comment]
@MarvinCai @tisonkun

**Review by tisonkun — APPROVED** [review]
Cool! I think this PR actually closes #16991 and #12271?

**Comment by youzipi** [comment]
> Cool! I think this PR actually closes #16991 and #12271?

yes, we can close these issues.
but there are still some modules not having this check, the list was made one year ago and the amount of modules is continuously growing (ex: pulsar-io modules).

**Comment by tisonkun** [comment]
@youzipi OK. I think we can narrow the scope to what that issue originally has. We can (you can! of course :)) create a new issue to track new effort. IIRC @MarvinCai has lees time to track #12271 and thus keep it open doesn't reflect the situation :)

**Review by MarvinCai — APPROVED** [review]
lgtm, really appreciate your contribution

**Review by codelipenghui — APPROVED** [review]
Thanks for the contribution.

**Comment by tisonkun** [comment]
@codelipenghui you may change the PR description as:

```
* This closes #12271.
* This closes #16991.
```

as mentioned in https://github.com/apache/pulsar/pull/17968#issuecomment-1272287220

**Pull request merged**
