### PR TITLE
Allow building Apache Pulsar on JDK15+ - upgrade Maven Assembly Plugin

### PR DESCRIPTION
**Pull request by eolivelli**
### Motivation
Currently Pulsar does not build on JDK15

### Modifications

- update Maven Assembly plugin
- move maven-git-commit-id plugin execution only inside Pulsar Common (in order to speed up the build)
- upgrading the Maven Assembly Plugin resulted in a different output for the "binaries", I had to update license files
- forced version of Jersey to 2.31 in "Presto" distribution (otherwise the license check failed, because it does not handle different versions between main pulsar binaries and presto distribution inside lib/presto/lib, and this makes sense to me)

### Verifying this change

This change is already covered by existing tests

### CODE REVIEW

**Comment by lhotari** [comment]
> it looks like github actions cached some content, as I cannot reproduce locally license check failures and compilation errors in integration test

@eolivelli  I believe #8361 fixes the grpc version issues in master branch. I cherry picked the commit to another PR that I'm working to test it. #8362 is the reason why master branch got into a broken state.

**Comment by eolivelli** [comment]
Good to know.
Waiting for master to be restored before pushing other changes

**Review by merlimat — APPROVED** [review]

**Comment by eolivelli** [comment]
rebased onto current master, let's see CI again

**Comment by eolivelli** [comment]
@lhotari test failed with this error
`Error:  Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:unpack (unpack) on project pulsar-client: Execution unpack of goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:unpack failed: Plugin org.apache.maven.plugins:maven-dependency-plugin:3.1.1 or one of its dependencies could not be resolved: Could not transfer artifact org.apache.maven.shared:file-management:jar:3.0.0 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/shared/file-management/3.0.0/file-management-3.0.0.jar: Connection reset -> [Help 1]`

probably your fix #8386 will help

**Comment by eolivelli** [comment]
One job fails with
`Error:  Failed to execute goal on project pulsar-io-hbase: Could not resolve dependencies for project org.apache.pulsar:pulsar-io-hbase:jar:2.7.0-SNAPSHOT: Failed to collect dependencies at org.apache.hbase:hbase-server:jar:2.3.0 -> org.glassfish.web:javax.servlet.jsp:jar:2.3.2 -> org.glassfish:javax.el:jar:3.0.1-b06-SNAPSHOT: Failed to read artifact descriptor for org.glassfish:javax.el:jar:3.0.1-b06-SNAPSHOT: Could not transfer artifact org.glassfish:javax.el:pom:3.0.1-b06-SNAPSHOT from/to spring-plugins-release (https://repo.spring.io/plugins-release/): Failed to transfer file https://repo.spring.io/plugins-release/org/glassfish/javax.el/3.0.1-b06-SNAPSHOT/javax.el-3.0.1-b06-SNAPSHOT.pom with status code 502 -> [Help 1]`

**Pull request merged**
