### PR TITLE
[improve][test] replace Whitebox with testing elements

### PR DESCRIPTION
**Pull request by tisonkun**
Master Issue: https://github.com/apache/pulsar/issues/16912
  
- [x] `doc-not-needed` 

cc @Shoothzj @eolivelli @nicoloboschi @Technoboy-

### CODE REVIEW

**Review by MarvinCai — APPROVED** [review]
lgtm

**Review by Shoothzj — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by nicoloboschi — APPROVED** [review]

**Comment by tisonkun** [comment]
Failed on a known flaky test: https://github.com/apache/pulsar/issues/17388

I think this is ready to merge now.

**Pull request merged**
