### PR TITLE
Introduce the packages management interface API

### PR DESCRIPTION
**Pull request by zymap**
---
Master issue: #8676 

*Motivation*

Implementation of the PIP-50.
This PR introduces package management APIs and storage APIs.
The related implement will in the next PR.

*Modifications*

- Add package management APIs
- Add package storage APIs
- Introduce the package type, name, and metadata struct.

### CODE REVIEW

**Comment by jiazhai** [comment]
> The related implement will in the next PR.

@zymap Would you please open a master issue to track the whole work? so the community could know the plans and schedule.

**Comment by zymap** [comment]
@jiazhai Thanks for the reminder. I created a master issue #8676 for it.

**Review by sijie — APPROVED** [review]

**Review by jiazhai — APPROVED** [review]

**Comment by Jennifer88huang** [comment]
@zymap I've added the doc content in https://github.com/apache/pulsar/pull/9071. If there is anything missing, feel free to contact me, thank you.
cc @Anonymitaet

**Comment by Anonymitaet** [comment]
@Jennifer88huang thanks for your contribution, but seems that the contents of the REST API are incorrect.
Could u pls help fix? Thanks

https://pulsar.apache.org/docs/en/next/admin-api-packages/
image

**Comment by Jennifer88huang** [comment]
Sure, I'll check and fix it.

**Comment by Jennifer88huang** [comment]
Fix it in https://github.com/apache/pulsar/pull/9972

**Pull request merged**
