### PR TITLE
[improve][client] Drop jcommander dependency in Pulsar java client

### LINKED ISSUE #18932: [Client] Drop jcommander dependency in Pulsar java client
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

Pulsar add the `jcommander` as dependency in `pulsar-common` module, but it should be an optional dependency because most people don't need it in client side.

### Solution

Make the `jcommander` in `pulsar-common` with `<optional>true</optional>`.

### Alternatives

_No response_

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by etcZYP**
Fixes #18932 

### Motivation

Pulsar add the jcommander as dependency in pulsar-common module, but it should be an optional dependency because most people don't need it in client side.
### Modifications

Make the jcommander in pulsar-common with <optional>true</optional>.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [x] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by tisonkun** [comment]
cc @syhily

**Comment by tisonkun** [comment]
Generally I don't think that you can pass compilation with this change. And it makes usage depends on this feature like https://github.com/apache/pulsar-site/blob/4e4f394960f0632bbc12cfad1a43dc132462464e/tools/pytools/lib/execute/config_doc_generator.py become vague to use.

Please follow https://pulsar.apache.org/contribute/personal-ci/ and attatch the test report here.

**Comment by tisonkun** [comment]
Have you ever verified your changes? How do you verify it? Please provide related description. This change looks in a wrong direction and without further explanation or verification, it won't get merged.

**Review by tisonkun — CHANGES_REQUESTED** [review]
Comments above.

**Comment by tisonkun** [comment]
After a second consideration, this change may work since the downstream users can opt-out the jcommand dependency now. And for config docs generator it's possible that classpath.txt already cover the dependencies. I'll try to verify it.

**Comment by syhily** [comment]
```optional``` means that this dependency is used to compile some classes in this module. If you rely on these classes, you should explicit add the optional dependency in you module.

So we may have to download the jcommander and add to the [classpath](https://github.com/apache/pulsar-site/blob/4e4f394960f0632bbc12cfad1a43dc132462464e/tools/pytools/lib/execute/config_doc_generator.py#L38) instead. Or we can create a new module for generating all the docs as Flink has already done.

**Comment by tisonkun** [comment]
Compile locally fails with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project pulsar-client-original: Compilation failure: Compilation failure:
[ERROR] /home/tison/Brittani/pulsar/pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/CmdGenerateDocumentation.java:[21,28] package com.beust.jcommander does not exist
[ERROR] /home/tison/Brittani/pulsar/pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/CmdGenerateDocumentation.java:[27,2] cannot find symbol
[ERROR]   symbol: class Parameters
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :pulsar-client-original
```

**Comment by tisonkun** [comment]
Compile locally fails with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project pulsar-client-original: Compilation failure: Compilation failure:
[ERROR] /home/tison/Brittani/pulsar/pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/CmdGenerateDocumentation.java:[21,28] package com.beust.jcommander does not exist
[ERROR] /home/tison/Brittani/pulsar/pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/CmdGenerateDocumentation.java:[27,2] cannot find symbol
[ERROR]   symbol: class Parameters
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :pulsar-client-original
```

**Comment by tisonkun** [comment]
Compile locally fails with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project pulsar-client-original: Compilation failure: Compilation failure:
[ERROR] /home/tison/Brittani/pulsar/pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/CmdGenerateDocumentation.java:[21,28] package com.beust.jcommander does not exist
[ERROR] /home/tison/Brittani/pulsar/pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/CmdGenerateDocumentation.java:[27,2] cannot find symbol
[ERROR]   symbol: class Parameters
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :pulsar-client-original
```

**Comment by tisonkun** [comment]
Compile locally fails with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project pulsar-client-original: Compilation failure: Compilation failure:
[ERROR] /home/tison/Brittani/pulsar/pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/CmdGenerateDocumentation.java:[21,28] package com.beust.jcommander does not exist
[ERROR] /home/tison/Brittani/pulsar/pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/CmdGenerateDocumentation.java:[27,2] cannot find symbol
[ERROR]   symbol: class Parameters
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :pulsar-client-original
```

**Comment by tisonkun** [comment]
@nicoloboschi Yes. This's what I proposed in https://github.com/apache/pulsar/issues/18932#issuecomment-1354110598

**Comment by tisonkun** [comment]
Closing...

Inactive.

**Pull request closed without merging**
