### PR TITLE
[Issue 4601,5215][pulsar-io-jdbc]Support   postgresql，sqlserver，mariadb，clickhouse jdbc source sink

### LINKED ISSUE #4601: pulsar connector for clickhouse
ClickHouse is an open source column-oriented database management system capable of real time generation of analytical data reports using SQL queries. It's would be great if we can sink data from pulsar to clickhouse.

### PR DESCRIPTION
**Pull request by huangdx0726**
Support  jdbc source sink,Including  postgresql，sqlserver，mariadb，clickhouse

Fixes #4601 #5215 

### Motivation

Support  almost all  jdbc source sink。

### Modifications

*Describe the modifications you've done.*
add JdbcDriverMapping class，and modify the getDriverClassName method.

### CODE REVIEW

**Comment by huangdx0726** [comment]
Do we provide driver package  ? Isn't it supposed to be provided by users?

**Comment by sijie** [comment]
> Do we provide driver package ? Isn't it supposed to be provided by users?

How do users provide the driver package? For example, if I have a Postgres database, how do I run the JDBC connector?

**Comment by tuteng** [comment]
I think if java's classloader mechanism can be used to load these packages, then the user should provide a driver parameter for the connector to load this jar package. Of course, for different databases, add, delete, update and the query should also be somewhat different, which may require separate processing and additional tests. This is only my idea, and I have not tested it yet.

**Comment by sijie** [comment]
my question is - as a user, how do I upload the driver or configure the driver in order to use this JDBC connector? This is the first question we have to answer for the users. but I don't see how does this pull request address it. So can you show me an example?

**Comment by huangdx0726** [comment]
I think add the YAML file and the  Related packages  to the connectors  folder，Isn't working now？May be i got it wrong。

**Comment by sijie** [comment]
@huangdx0726 

> I think add the YAML file and the Related packages to the connectors folder，Isn't working now？May be i got it wrong。

Not sure if it can work or not.

1) We need a tutorial or an example to show this approach can work.
2) We need documentation to let users know how to configure it.

I don't see this pull request cover any of them.

**Comment by huangdx0726** [comment]
em，I see the documentation ，may be add dependency of driver packages in pom.xml file in current  approach  of pulsar source。

**Comment by huangdx0726** [comment]
I have added the dependency of driver packages in pom.xml file.

**Comment by sijie** [comment]
@huangdx0726 I don't think it is a good idea to put all drivers together. 1) it will make the NAR package very large; 2) it becomes very difficult to manage the dependencies.

**Comment by huangdx0726** [comment]
@sijie  I think so, May I can try loading the driver package before functionworker starting。

**Comment by sijie** [comment]
The approach still has a couple of problems.

1) it only works if you run function worker as part of broker or as separate process. It doesn't work if you run connectors in Kubernetes.

2) it is going to be hard to ensure people place the right jar in the connector directory. especially when you scale up the clusters, how do you ensure people add the right jar in the connector directory?

---

I think a better approach is to have different type of connectors with different drivers.

- create a parent module of pulsar-io-jdbc
- create sub modules. each module inherits the parent module and add different types of drivers. we generate a connector for each module. Thus one connector bundles one driver. Hence we will have `pulsar-io-jdbc-mysql` for mysql driver, `pulsar-io-jdbc-sqlite` for sqlite, and etc.

**Comment by sijie** [comment]
Move this to 2.6.0 since the solution is still unclear and the discussion is still ongoing.

**Comment by huangdx0726** [comment]
> 
> 
> The approach still has a couple of problems.
> 
>     1. it only works if you run function worker as part of broker or as separate process. It doesn't work if you run connectors in Kubernetes.
> 
>     2. it is going to be hard to ensure people place the right jar in the connector directory. especially when you scale up the clusters, how do you ensure people add the right jar in the connector directory?
> 
> 
> I think a better approach is to have different type of connectors with different drivers.
> 
>     * create a parent module of pulsar-io-jdbc
> 
>     * create sub modules. each module inherits the parent module and add different types of drivers. we generate a connector for each module. Thus one connector bundles one driver. Hence we will have `pulsar-io-jdbc-mysql` for mysql driver, `pulsar-io-jdbc-sqlite` for sqlite, and etc.

Ok,I'll try by the approach .

**Comment by vzhikserg** [comment]
@sijie this pulls request can be closed because it was integrated into #6835 that was merged to the master branch.

**Comment by sijie** [comment]
Closed this issue since #6835 was already merged.

**Pull request closed without merging**
