### PR TITLE
[issue 9585][Consumer]delete disconnected consumers to allow auto-discovery

### LINKED ISSUE #9585: The consumer doesn't reconnect to the multi partitioned topic after the topic deletion and recreating
**Describe the bug**
When we delete the multi partitioned topic and recreate it again the  existing connected consumer can't re-subscribe and consume messages. We must kill the consumer and create again.

Note: The multi topic consumer with regex works as expected. The problem is with a regular consumer only. 
Tested on the multi portioned topic only . Suspect the the non-partitioned topics has the same issue

**To Reproduce**
1. Create  multi portioned topic.
2. Create consumer to that topic
3. Delete the topic
4. Recreate it again.

**Expected behavior**
The consumer should discover again the topic and re-subscribe like multitopic consumer with regex.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by mlyahmed**
Fixes #9585 

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by codelipenghui — COMMENTED** [review]
The change looks good, could you please add some tests?

**Comment by mlyahmed** [comment]
yes sure !

**Comment by mlyahmed** [comment]
I should be OK now but the CI workers seem hanging...

**Review by codelipenghui — APPROVED** [review]

**Review by sijie — APPROVED** [review]

**Pull request merged**
