### PR TITLE
[pulsar-admin] Check backlog quota policy for namespace

### PR DESCRIPTION
**Pull request by yuruguo**
### Motivation
We should check the validity of the `option` in command `set-backlog-quota` / `remove-backlog-quota` for namespace and give a more friendly prompt message when executing `./bin/pulsar-admin namespaces set-backlog-quota` / `./bin/pulsar-admin namespaces remove-backlog-quota`.
- the `option` that need to be verified in the command `set-backlog-quota` include: `--limit`,`--type`
- the `option` that need to be verified for the command `remove-backlog-quota` include: `--type`

Currently, the lack of verification for above `option` will directly display the exception.

### Modifications
- Throw `ParameterException` when `IllegalArgumentException` occurs when executing `validateSizeString()` / `BacklogQuota.BacklogQuotaType.valueOf()`

### Documentation
Check the box below and label this PR (if you have committer privilege).

Need to update docs?

- [ ] `doc-required`

(If you need help on updating docs, create a doc issue)

- [x] `no-need-doc`

(Please explain why)

- [ ] `doc`

(If this PR contains doc changes)

### CODE REVIEW

**Comment by yuruguo** [comment]
Please take a look again, thanks :) @eolivelli

**Comment by yuruguo** [comment]
@eolivelli Please take a look again, thanks :)

**Comment by yuruguo** [comment]
@eolivelli Please take a look again, thanks :)

**Review by eolivelli — APPROVED** [review]
LGTM

**Pull request merged**
