### PR TITLE
Implementation of the packages management

### PR DESCRIPTION
**Pull request by zymap**
---
Master Issue: #8676
    
*Motivation*
    
The implementation of the packages management service.
I add a memory storage for testing the service.
    
*Modifications*
    
- Implement the package management service.
- Add a mocked memory storage for testing.
- Add tests for the packages management service.

### CODE REVIEW

**Comment by zymap** [comment]
@sijie @jiazhai @codelipenghui PTAL. Thanks.

**Comment by zymap** [comment]
@sijie @jiazhai @codelipenghui Please take a look when you have time. Thanks!

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
