### PR TITLE
[fix][doc]Fix indentation problem in docker-compose.yaml

### PR DESCRIPTION
**Pull request by liangyepianzhou**
Fix https://github.com/apache/pulsar/issues/18952
### Motivation
There is some indentation problem in docker-compose.yaml.

### Modifications

Fix the docker-compose.yaml.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by michaeljmarshall — APPROVED** [review]
LGTM. @liangyepianzhou - can you confirm that you've tested this change on your machine? Thanks!

**Review by Demogorgon314 — APPROVED** [review]
LGTM.

**Review by RobertIndie — APPROVED** [review]

**Comment by liangyepianzhou** [comment]
@michaeljmarshall I have tested it on my machine.

**Comment by liangyepianzhou** [comment]
@michaeljmarshall I have tested it on my machine.

**Comment by michaeljmarshall** [comment]
Thanks for confirming @liangyepianzhou!

**Pull request merged**
