### PR TITLE
[functions] Add executor for CmdFunctions

### LINKED ISSUE #14386: ImportError: No module named _pulsar
#### Expected behavior

I'm just trying to execute the format-phone-number example in local
I'm using the Python3

I have installed the 
pulsar                   2.0.2
pulsar-client            2.9.1

I'm using bin/pulsar standalone (2.6.0)

I tried to localrun the pulsar function using the below command

bin/pulsar-admin functions localrun \
  --broker-service-url pulsar://localhost:6650 \
  --tenant public \
  --namespace default \
  --py /tmp/format-phone-number.zip \
  --classname phoneValidation.TestEtl \
  --inputs persistent://public/default/in \
  --output persistent://public/default/out \
  --log-topic persistent://public/default/log \
  --state-storage-service-url bk://127.0.0.1:4181

after running the above command I got the following error

**File "/home/karthik/apache-pulsar-2.6.0/instances/python-instance/python_instance_main.py", line 36, in <module>
    import pulsar
  File "/home/karthik/apache-pulsar-2.6.0/instances/python-instance/pulsar/__init__.py", line 102, in <module>
    import _pulsar
ImportError: No module named _pulsar**

### PR DESCRIPTION
**Pull request by yaalsn**
Fixes #14386 

### Motivation

In pulsar function, when the runtime is `Python` or `Java` , commands will start with `python` or `java`  
image
This would be right in general, but sometimes  is not such as `/home/pulsar/jdk17/bin/java`, `python3` and `conda` `pyenv` python virutal env. We need to add a executor to let user to choose.

### Modifications

- Add `--executor` parameter to `CmdFunctions`.
- Add `executor` to `functions.proto`
- Replace `java` and `python` with executor

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:

  - *Extend unit tests for args which contains executor to be parsed*
  - *Added integration tests for function run with executor*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API: (yes / **no**)
  - The schema: (yes / **no** / don't know)
  - The default values of configurations: (yes / **no**)
  - The wire protocol: (yes / **no**)
  - The rest endpoints: (yes / **no**)
  - **The admin cli options**: (**yes** / no)
  - Anything that affects deployment: (yes / **no** / don't know)

### Documentation

Need to update docs? 
  
- [x] `doc`

### CODE REVIEW

**Comment by yaalsn** [comment]
@codelipenghui @Anonymitaet PTAL

**Comment by freeznet** [comment]
Thanks for the contribution, but I think this PR needs more discussion before merge it, as from the Pulsar Functions' user aspect, they dont always know the enviroment settings from the server side, and the user may submit wrong executor path. So it would be better if the executor path be set from the server side (i.e. new configs in Functions Worker configs) but not from the user's side. 
@nlu90 @jerrypeng @wolfstudy PTAL, thanks.

**Comment by Anonymitaet** [comment]
@yaalsn normally after the PR gets approved by other coders (technical perspective), then tech writers will review it from the technical writing perspective. So could you please ping me to review it after gets technical approval? Thanks

**Comment by yaalsn** [comment]
> @yaalsn normally after the PR gets approved by other coders (technical perspective), then tech writers will review it from the technical writing perspective. So could you please ping me to review it after gets technical approval? Thanks

ok, got it 👌

**Pull request closed without merging**
