### PR TITLE
[fix][admin] Fix unWrap Exception when getPoliciesAsync

### PR DESCRIPTION
**Pull request by wenbingshen**
### Modifications
`getPoliciesAsync` may return an exception wrapped as `CompletionException`

### Documentation
  
- [x ] `doc-not-needed`

### CODE REVIEW

**Review by nodece — APPROVED** [review]

**Review by tisonkun — COMMENTED** [review]
@wenbingshen can you share a real-world failure instance with stacktrace?

IIUC `ComplateableFuture#exceptionally` should take the inner exception instead of a `CompletionException`. If so, it's likely something wrong from the dependent future.

**Review by tisonkun — APPROVED** [review]
Sorry. The exception should be always `CompletionException`.

LGTM.

**Review by Technoboy- — APPROVED** [review]

**Pull request merged**
