### PR TITLE
Convert anonymous classes to lambda

### PR DESCRIPTION
**Pull request by vzhikserg**
### Motivation

The anonymous classes were converted to lambda in the places where it improves readability and decreases the lines of code.

### CODE REVIEW

**Comment by merlimat** [comment]
retest this please

**Comment by vzhikserg** [comment]
please let me know if I need to do anything else for this merge request

**Comment by sijie** [comment]
@vzhikserg I think there are some problems in apache CI. somehow the CI status checks are in weird state. We will merge once the CI passed.

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by jiazhai** [comment]
add to 2.4.1 for conflict with #4728

**Pull request merged**
