### PR TITLE
[Issue 3806] Fix NPE while call PartitionedProducerImpl.getStats()

### LINKED ISSUE #3806: NPE in PartitionedProducerImpl##ProducerStatsRecorderImpl
**Describe the bug**
meet NPE while call PartitionedProducerImpl.getStats()

**Screenshots**
image

**Additional context**

In PartitionedProducerImpl, the stats instance(ProducerStatsRecorderImpl) is init like this.
```
stats = client.getConfiguration().getStatsIntervalSeconds() > 0 ? new ProducerStatsRecorderImpl() : null;
```

while  in ProducerStatsRecorderImpl(), all member is set to null;
```
public ProducerStatsRecorderImpl() {
    numMsgsSent = null;
    numBytesSent = null;
    numSendFailed = null;
    numAcksReceived = null;
    totalMsgsSent = null;
    totalBytesSent = null;
    totalSendFailed = null;
    totalAcksReceived = null;
    ds = null;
}
```
so when call PartitionedProducerImpl.getStats(), it will meet NPE
```
@Override
public synchronized ProducerStatsRecorderImpl getStats() {
    if (stats == null) {
        return null;
    }
    stats.reset();      < === 
    for (int i = 0; i < topicMetadata.numPartitions(); i++) {
        stats.updateCumulativeStats(producers.get(i).getStats());
    }
    return stats;
}

void reset() {
    numMsgsSent.reset();   < === 
    numBytesSent.reset();
    numSendFailed.reset();
    numAcksReceived.reset();
    totalMsgsSent.reset();
    totalBytesSent.reset();
    totalSendFailed.reset();
    totalAcksReceived.reset();
}

```

### PR DESCRIPTION
**Pull request by murong00**
### Motivation

Fixes #3806

### Modifications

Initialize `LongAdder` variables by `LongAdder` Object.

### CODE REVIEW

**Comment by murong00** [comment]
@sijie @jiazhai Not so sure about this issue, by the way, also found in `ConsumerStatsRecorderImpl`, I got stuck about the unit test, can you give me some advice? Thanks!

**Comment by sijie** [comment]
>  I got stuck about the unit test, can you give me some advice? Thanks!

you can just add a new test file `PartitionedProducerImplTest` and then test - if you construct a `PartitionedProducerImpl` using the zero arg constructor, it will not get NPE when accessing the variables.

**Comment by jiazhai** [comment]
run integration tests

**Comment by sijie** [comment]
run cpp tests

**Comment by sijie** [comment]
run java8 tests

**Comment by merlimat** [comment]
Merged in 2.3.1 at 
ede6f6e

**Pull request merged**
