### PR TITLE
[Broker] Correct param of delete method for v1 topic

### PR DESCRIPTION
**Pull request by yuruguo**
### Motivation
Currently, the deletion topic method for `v1/topic` has the problem of parameter loss and mismatch as below,
1. `deleteSchema` is missing
https://github.com/apache/pulsar/blob/af1a82d1aaf7965d3080a6d043d5111f0b9015e5/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java#L302-L308
https://github.com/apache/pulsar/blob/af1a82d1aaf7965d3080a6d043d5111f0b9015e5/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java#L263-L270
2. `force` and `deleteSchema` are confused
https://github.com/apache/pulsar/blob/af1a82d1aaf7965d3080a6d043d5111f0b9015e5/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java#L307
https://github.com/apache/pulsar/blob/af1a82d1aaf7965d3080a6d043d5111f0b9015e5/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L1013-L1018

### Modifications
Class: `v1/PersistentTopics`
- Add @QueryParam `deleteSchema` in method `deleteTopic` and `deletePartitionedTopic`
- Correct parameter `force` and `deleteSchema` in method `deleteTopic`

### Documentation  
- [x] `no-need-doc`

### CODE REVIEW

**Review by eolivelli — CHANGES_REQUESTED** [review]
looks good, can we add a test or enhance an existing test ?

**Comment by yuruguo** [comment]
> looks good, can we add a test or enhance an existing test ?

I have added releted tests, ptal again, thx!

**Comment by yuruguo** [comment]
@merlimat @codelipenghui can you help review this pr?

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
