### PR TITLE
[pulsar function] add instanceId and fqn into log message properties

### PR DESCRIPTION
**Pull request by nlu90**
### Motivation

Enrich the published log message with `instanceId` and `fqn` set in properties.

### Modifications

add `instanceId` and `fqn` into log message properties

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

### CODE REVIEW

**Comment by Anonymitaet** [comment]
Thanks for your contribution. For this PR, do we need to update docs?

(The [PR template contains info about doc](https://github.com/apache/pulsar/blob/master/.github/PULL_REQUEST_TEMPLATE.md#documentation), which helps others know more about the changes. Can you provide doc-related info in this and future PR descriptions? Thanks)

**Comment by nlu90** [comment]
@Anonymitaet

There's no doc about the existing property for log topic. It's good to mention the available propperties for a log message, but I don't know where to add this.

**Comment by Anonymitaet** [comment]
@nlu90 how about adding that info [here](https://pulsar.apache.org/docs/en/next/functions-debug/#use-log-topic)?

**Comment by nlu90** [comment]
> @nlu90 how about adding that info [here](https://pulsar.apache.org/docs/en/next/functions-debug/#use-log-topic)?

LGTM. We can add them once the PR is accepted and merged.

**Review by sijie — APPROVED** [review]

**Comment by Anonymitaet** [comment]
@nlu90 thanks. You can ping me if you need a doc review.

**Review by freeznet — APPROVED** [review]

**Comment by sijie** [comment]
@nlu90 you might need to rebase to the latest master to include CI fixes.

**Pull request merged**
