### PR TITLE
[improve][ci] Add `ml` for CI semantic check.

### PR DESCRIPTION
**Pull request by Technoboy-**
### Motivation

As some patches(like #18078 ) are only for managed-ledger, so add this label.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by tisonkun — CHANGES_REQUESTED** [review]
managed-ledger should be covered by `storage` already?

**Review by mattisonchao — APPROVED** [review]
LGTM

**Review by poorbarcode — COMMENTED** [review]
How can I tell `ml` and `storage`?

**Comment by nodece** [comment]
I prefer using `storage` instead of `ml`.

**Comment by tisonkun** [comment]
@lhotari could you answer the question above? Doesn't storage scope already cover `ml` added here?

If it's the case, we should revert this patch.

**Comment by Technoboy-** [comment]
> @lhotari could you answer the question above? Doesn't storage scope already cover `ml` added here?
> 
> If it's the case, we should revert this patch.

We'd better define these by modules.  `storage` convers `ml`, but not accurate.   
In the scope, `broker` covers `admin` and `txn`.

**Comment by tisonkun** [comment]
@Technoboy- then what kind of changes should go into `storage`? Or we can just replace it with `ml`?

Besides, `ml` is easy to be read as "machine learning" while we have the comment and it's a learned knowledge for dedicated developers :)

**Pull request merged**
