### PR TITLE
[Issue 5059][offloaders] Delete offloaded with offloadpolicies

### PR DESCRIPTION
**Pull request by KannarFr**
Master Issue: #5059

### Motivation
Describe deletion max lag and threshold bytes to remove data from offloaded tiered storage.

### Modifications

Will update once it's finished.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - The public API: yes
  - The default values of configurations: yes (introducing new one)
  - The rest endpoints: yes (modifying/adding)
  - The admin cli options: yes (modifying/adding)

### Documentation

  - Does this pull request introduce a new feature? yes
  - If yes, how is the feature documented? not documented
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation. Will do

### CODE REVIEW

**Comment by KannarFr** [comment]
Oh, jcloud already contains `deleteOffloaded` :).

**Comment by sijie** [comment]
loop in @gaoran10 to help review this as well.

**Comment by KannarFr** [comment]
Still WIP, will ping you for review :).

Le mar. 18 févr. 2020 à 20:29, Sijie Guo <notifications@github.com> a
écrit :

**Comment by KannarFr** [comment]
So https://github.com/apache/pulsar/issues/6283 is not done, I thought it was. I need it for this PR.

**Comment by KannarFr** [comment]
Just realized that this if useless because it's retention jobs T_T.

**Pull request closed without merging**
