### PR TITLE
Clean up C++ client curl configuration

### PR DESCRIPTION
**Pull request by michaeljmarshall**
### Motivation

Clean up C++ client curl configuration.

### Modifications

* Remove some settings

### Verifying this change

This is a minor change with well known scope. No additional tests are required.

### CODE REVIEW

**Review by dave2wave — APPROVED** [review]
LGTM

**Review by merlimat — APPROVED** [review]

**Review by BewareMyPower — COMMENTED** [review]
Could you explain the motivation of this PR? The default values of these two configs are 1, which enables strict certificates check. I think it was zero are just to disable the build.

We observed an error like:

```
2022-10-20 02:42:38.545 ERROR [140011702527744] AuthOauth2:223 | Response failed for getting the well-known configuration <xxx>. Error Code 77: error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
```

It seems to be related to this PR, see https://curl.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html

> This trust is based on a chain of digital signatures, rooted in certification authority (CA) certificates you supply. curl uses a default bundle of CA certificates (the path for that is determined at build time)

/cc @freeznet @jiangpengcheng

**Comment by BewareMyPower** [comment]
I have confirmed it's caused by this PR and will revert it from branch-2.7 to 2.11. Though we should encourage users to use new separated `pulsar-client-cpp` and `pulsar-client-python` repos, I will confirm again for these new repos.

### Reproduce

Checkout branch-2.9, run the following command.

```bash
$ pulsar-client-cpp/docker/build-wheels.sh 3.8 cp38-cp38 manylinux2014 x86_64
```

Then `pulsar_client-2.9.3-cp38-cp38-linux_x86_64.whl` will be generated under `pulsar-client-cpp/python/dist`. Then install the wheel in a `ubuntu:20.04` container. 

```bash
docker run -v $PWD:/pulsar -it ubuntu:20.04 /bin/bash
```

```bash
apt update -y
apt install -y python3 python3-pip
pip3 install /pulsar/pulsar-client-cpp/python/dist/pulsar_client-2.9.3-cp38-cp38-linux_x86_64.whl
```

Then run the following script:

```python
#!/usr/bin/env python3
from pulsar import AuthenticationOauth2

auth = AuthenticationOauth2(auth_params_string='''{
    "type": "client_credentials",
    "issuer_url": "https://dev-kt-aa9ne.us.auth0.com",
    "client_id": "xxx",
    "client_secret": "xxx"
}''')
```

Output:

```
2022-11-02 09:28:19.003 ERROR [140425586124608] AuthOauth2:222 | Response failed for getting the well-known configuration https://dev-kt-aa9ne.us.auth0.com. Error Code 77: error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
```

After I reverted this PR, it works.

image

**Comment by BewareMyPower** [comment]
Okay. I will confirm the solution ASAP. We should mention the CVE (even if the details were not reported) when pushing such a PR that might cause regression.

**Comment by BewareMyPower** [comment]
They are restored now. I will confirm the solution soon.

**Comment by michaeljmarshall** [comment]
Thanks @BewareMyPower.

**Pull request merged**
