### PR TITLE
[improve][ci] Update GitHub Workflows to Ubuntu 22.04

### PR DESCRIPTION
**Pull request by dave2wave**
Main Issue: #20727 

### Motivation

Make sure the CI tests are run on the same version of Ubuntu as the docker deployment.

### Modifications

In .github/workflows change the runs on to ubuntu 22.04

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is already covered by existing tests, such as *this changes github workflows*

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: [https://github.com/dave2wave/pulsar]

### CODE REVIEW

**Comment by dave2wave** [comment]
I'm running some of the workflows in my fork.

**Comment by dave2wave** [comment]
CI succeeds other than unrelated OWASP issues. https://github.com/dave2wave/pulsar/actions/runs/5476867438

**Review by michaeljmarshall — APPROVED** [review]
LGTM

**Comment by lhotari** [comment]
This is needed in branch-3.0 due to https://github.com/actions/runner-images/issues/11101

**Pull request merged**
