### PR TITLE
[fix][broker] fix the local police IsolationGroups permanent cover the defaultIsolationGroups

### LINKED ISSUE #16272: [bug][broker] The local police IsolationGroups permanent cover the defaultIsolationGroups
**Describe the bug**
When we set the isolation policy `bookkeeperClientIsolationGroups=group1`  in `broker.conf`  as the `defaultIsolationGroups` for the namespace bundle which in the brokers , and then we set the dynamic isolation policy like `set-bookie-affinity-group public/default --primary-group group2` the IsolationGroups is covered by the local policy.
But after invoke `delete-bookie-affinity-group public/default `,  the `newEnsemble` also choice the bookie from group2.  The correct behavior is when `we delete-bookie-affinity-group `  the namespace isolation policy can rollback to the config in `broker.conf` as default.
The `defaultIsolationGroups` are permanent  covered by the latest local police IsolationGroups.

**To Reproduce**
1. Set the isolation policy `bookkeeperClientIsolationGroups=group1`  in `broker.conf`.
2. Start one broker and create a  topic, producer some message, the newEnsemble will use `defaultIsolationGroups`  and choice the bookies in group1.
3. invoke `bin/pulsar-admin  namespaces set-bookie-affinity-group public/default --primary-group group2`; when the topic create new ledger will use the new policy and choice bookie in group2.
4. invoke `bin/pulsar-admin namespaces delete-bookie-affinity-group public/default`; when the topic create new ledger will use `defaultIsolationGroups`  but not choice bookie in group1 which choice the bookie in group2 always.  The `defaultIsolationGroups` is permanent covered.

**Expected behavior**
The `defaultIsolationGroups` should not be covered.  When we `delete-bookie-affinity-group` and the `bookkeeperClientIsolationGroups` is present in `broker.conf`,  we can use the default isolation policy.

**Additional context**
Use the master branch code.

### PR DESCRIPTION
**Pull request by Nicklee007**
Fixes #16272

### Motivation
Fix the local police IsolationGroups permanent cover the `defaultIsolationGroups`, which will cause even we rollback the local police to empty,  the `defaultIsolationGroups` always use the latest local police IsolationGroups setting and  is not use the setting in broker.conf as default.

The `defaultIsolationGroups` be covered point.
https://github.com/apache/pulsar/blob/0eed84203b23e325ac15d7dc50e1ed6dbdf4fa2a/pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/IsolatedBookieEnsemblePlacementPolicy.java#L141

### Modifications
1.  fix the `defaultIsolationGroups` be covered point 
2. merge the `newEnsemble` and `replaceBookie` method duplication code to `getBlacklistedBookies()` ,to avoid change only cover one method in the future. 
3. add some unit test.
`
### Verifying this change

- [X] `doc-not-needed`

### CODE REVIEW

**Comment by Nicklee007** [comment]
run failure checks

**Review by gaozhangmin — APPROVED** [review]

**Comment by gaozhangmin** [comment]
Good catch

**Review by coderzc — APPROVED** [review]

**Review by Jason918 — APPROVED** [review]
LGTM

**Pull request merged**
