### PR TITLE
[Issue 6761] Correct tokenSecretKey base64 inline description

### LINKED ISSUE #6761: Wrong tokenSecretKey configuration description about using base64 inline
**Describe the bug**
When using base64 line in tokenSecretKey, config should specify like "tokenSecretKey=data:;base64,xxxxxxxxx" but not "tokenSecretKey=data:base64,xxxxxxxxx". Description in documnet is missing a semicolon.

data URI scheme:
https://en.wikipedia.org/wiki/Data_URI_scheme

wrong documents:
https://pulsar.apache.org/docs/en/reference-configuration/

> Configure the secret key to be used to validate auth tokens. The key can be specified like: tokenSecretKey=data:base64,xxxxxxxxx or tokenSecretKey=file:///my/secret.key

https://pulsar.apache.org/docs/en/security-jwt/

>  \# If using secret key
tokenSecretKey=file:///path/to/secret.key
\# The key can also be passed inline:
\# tokenSecretKey=data:base64,FLFyW0oLJ2Fi22KKCm21J18mbAdztfSHN/lAT5ucEKU=

**To Reproduce**
// correct result
apache-pulsar-2.5.0>bin/pulsar tokens create --secret-key 'qcsXyb5eo8c09YXIMJaA97RYPCmIuyTlrN2KcI0zzxM=' --subject admin
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiJ9.L869nKrziQIPkgqIawIh-RxxDelfGIiol1DBhoBl26Y

// wrong result
apache-pulsar-2.5.0>bin/pulsar tokens create --secret-key 'data:base64,qcsXyb5eo8c09YXIMJaA97RYPCmIuyTlrN2KcI0zzxM=' --subject admin
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiJ9.ne2WjK3zY4cecotgUYkU0kkviOyslnCqPDHcPYF-HDc

// correct result
apache-pulsar-2.5.0>bin/pulsar tokens create --secret-key 'data:;base64,qcsXyb5eo8c09YXIMJaA97RYPCmIuyTlrN2KcI0zzxM=' --subject admin
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiJ9.L869nKrziQIPkgqIawIh-RxxDelfGIiol1DBhoBl26Y

**Expected behavior**
Correct tokenSecretKey base64 inline description in documents and examples.

### PR DESCRIPTION
**Pull request by murong00**
### Motivation

Fixes #6761

### Modifications

Correct tokenSecretKey base64 inline description in documents (based master & version 2.5.1) and examples.

### CODE REVIEW

**Comment by jiazhai** [comment]
@murong00 Would you please also fix the "data:base64," in test "TokenAuthWithSymmetricKeys.java"?

**Comment by murong00** [comment]
@jiazhai What do you mean? This pr has been included fix `data:base64,` in `TokenAuthWithSymmetricKeys.java` which is a base test.

**Comment by sijie** [comment]
@murong00 Can you also fix the documentation of 2.5.1?

**Comment by jiazhai** [comment]
> @jiazhai What do you mean? This pr has been included fix `data:base64,` in `TokenAuthWithSymmetricKeys.java` which is a base test.

I found that change. thanks for the work.

**Comment by murong00** [comment]
> @murong00 Can you also fix the documentation of 2.5.1?

Already fixed in this pr.

**Pull request merged**
