### PR TITLE
[hotfix] simplify code

### PR DESCRIPTION
**Pull request by aloyszhang**
### Motivation
Simplify code of `ManagedLedger.getManagedLedgerInfo()`

### Modifications

unify the method of generating `ManagedLedgerInfo` 

### Verifying this change

This change is a  code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: （no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Review by sijie — APPROVED** [review]

**Comment by aloyszhang** [comment]
@Renkai  PTAL

**Comment by aloyszhang** [comment]
@BewareMyPower PTAL

**Review by BewareMyPower — APPROVED** [review]

**Pull request merged**
