### PR TITLE
[Replicated] Add the test for topic replicated and create producer.

### PR DESCRIPTION
**Pull request by congbobo184**
## Motivation
link issue : https://github.com/apache/pulsar/issues/7763
### Verifying this change

Does this pull request potentially affect one of the following parts:
If yes was chosen, please highlight the changes

Dependencies (does it add or upgrade a dependency): (no)
The public API: (no)
The schema: (no)
The default values of configurations: (no)
The wire protocol: (no)
The rest endpoints: (no)
The admin cli options: (no)
Anything that affects deployment: (no)

### CODE REVIEW

**Review by codelipenghui — CHANGES_REQUESTED** [review]
I think there are tests to cover the persistent topic replication cases but not cover the non-persistent topic. I think you should add a test to only cover the non-persistent topic replication case both for the partitioned and non-partitioned topic.

And the test only covers the producer creation can passed, but this can't ensure the replication for the non-persistent topic is works.

**Review by sijie — APPROVED** [review]

**Comment by sijie** [comment]
@codelipenghui Can you review this again?

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
