### PR TITLE
Replaced boost::bind with std::bind

### PR DESCRIPTION
**Pull request by merlimat**
### Modifications

Use C++11 `std::bind` to replace `boost::bind`

### CODE REVIEW

**Comment by jiazhai** [comment]
run cpp tests

**Comment by jiazhai** [comment]
@merlimat Seems jenkins failure is related to the change, may need some replacement:
```
/pulsar/pulsar-client-cpp/tests/BasicEndToEndTest.cc: In member function 'virtual void BasicEndToEndTest_testBatchMessages_Test::TestBody()':
/pulsar/pulsar-client-cpp/tests/BasicEndToEndTest.cc:190:106: error: no matching function for call to 'bind(<unresolved overloaded function type>, const std::_Placeholder<1>&, const std::_Placeholder<2>&, std::__cxx11::string&, int*)'
             msg, std::bind(&sendCallBack, std::placeholders::_1, std::placeholders::_2, prefix, &msgCount));
 ```

**Comment by ivankelly** [comment]
run cpp tests
run integration tests // problably needs a merge of master

**Comment by merlimat** [comment]
run cpp tests

**Pull request merged**
