### PR TITLE
[improve][build] use SLASHSTAR_STYLE for licenses in Java files

### PR DESCRIPTION
**Pull request by tisonkun**
This supersedes #17508.

See also https://lists.apache.org/thread/gwy3ycgsq24r784mk3yv6cbppmbfxgjd.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/tisonkun/pulsar/pull/9

### CODE REVIEW

**Comment by tisonkun** [comment]
cc @BewareMyPower @RobertIndie

**Review by BewareMyPower — APPROVED** [review]

**Review by RobertIndie — APPROVED** [review]

**Comment by tisonkun** [comment]
ping @BewareMyPower @RobertIndie @nicoloboschi @eolivelli @Jason918 tests passed. Although I can always reapply the formatting step, I hope with can have a timely review stage :)

**Comment by tisonkun** [comment]
Thanks for merging this patch. Be aware that we may suffer a period that new patches introduce regression for the JAVADOC_STYLE license header because we don't require the patch to be merged must be up-to-date. But the overall situation should converge.

**Comment by mattisonchao** [comment]
Hi, @tisonkun 
I'm not sure If this change is acceptable for PMCs or needs to vote on. But there is some trouble with cherry-picking new changes to the previous branch.
I'm wondering if we have a good method to resolve the conflict with the previous branch. maybe `mvn initialize license:format` can work properly? I'm not sure...
Anyway, thanks a lot for your contribution, I hope you can answer my question though, thanks!

**Comment by tisonkun** [comment]
@mattisonchao This is not a breaking change from a user perspective. Thus, I don't initialize a formal vote.

I made several discussions on the dev@ list:

* https://lists.apache.org/thread/gwy3ycgsq24r784mk3yv6cbppmbfxgjd
* https://lists.apache.org/thread/jxl6vlgdd460gnnno6o6kpyc4jqc0b2k

... and follow the common [lazy consensus principle](https://community.apache.org/committers/lazyConsensus.html).

To resolve your issues, either run `mvn initialize license:format` on the failure PR, or manually append `*` for new files when cherry-picking.

The new style is started from 2.12 or 2.11 and the whole style will converge finally.

**Comment by mattisonchao** [comment]
Ok, Got it. thanks!

**Pull request merged**
