### PR TITLE
[Tests] Migrate Junit tests and annotations to TestNG

### PR DESCRIPTION
**Pull request by lhotari**
### Motivate

There are some Junit 4 tests among the TestNG tests. There was also one Junit 3 test. 
Junit 3 and Junit 4 assertion library is used in many locations.

The main motivation for this change is to get the current TestNG timeout handling in place for all tests. There are some tests in the pulsar-io-flume module that hang until the build times out. No thread dump gets captured so it's hard to fix the issue. After making this change, it will be possible to observe what causes the test to hang.

### Modifications

Migrate Junit 3 and Junit 4 tests to TestNG.

Migrate Junit 3 and Junit 4 assertion library usage to TestNG
- `junit.framework.Assert` -> `org.testng.Assert`
- `org.junit.Assert` -> `org.testng.Assert`

In TestNG's `Assert.assertEquals`, the order of parameters is different than in Junit. In TestNG, the parameter order is always actual value, expected value. In Junit's Assert, it's the otherway around. Therefore the parameters have to be switched when converting from Junit to TestNG. However, there are some assertions where the order has been invalid when using Junit's assertEquals.

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Comment by lhotari** [comment]
I'll fix a few issues in the migration. It seems that the order of parameters (expected, actual, message) in the assertion libraries is different. Checking and fixing.

**Review by eolivelli — APPROVED** [review]
LGTM

I agree that it is better to have only one single test framework.

**Pull request merged**
