### PR TITLE
[Issue 10669] Add Pulsar_GC_LOG when start broker with bin/pulsar

### LINKED ISSUE #10669: $PULSAR_GC_LOG not working when start broker with bin/pulsar
**Describe the bug**
$PULSAR_GC_LOG missing when start broker with cmd `bin/puslar start broker`
Java GC log is quite useful in production environment, IMHO, It's better take affects by default.

**To Reproduce**
1. Deploy a broker following the instrustions here: https://pulsar.apache.org/docs/en/deploy-bare-metal/
2. Run this command `ps aux | grep PulsarBrokerStarter`, you will get the actual running cmd.
3.  You will find that there is no arguments about gc logs, though $PULSAR_GC_LOG is set in pulsar_env.sh. 

**Expected behavior**
$PULSAR_GC_LOG  should appear in actual running cmd by default.

### PR DESCRIPTION
**Pull request by Jason918**
Fixes #10669 

### Motivation

GC log is useful for production environment, I think it should take affect by default.

### CODE REVIEW

**Review by jiazhai — APPROVED** [review]

**Comment by jiazhai** [comment]
@merlimat @codelipenghui  What do you think of this change?

**Comment by hangc0276** [comment]
@Jason918 For bookie startup, it will be better to add gc log too. In my production env, i have add the gc log for broker, zookeeper and bookie.

**Comment by lhotari** [comment]
Now that we are running on Java 11 for the Docker image in master branch, there's a required change related to `PULSAR_GC_LOG` . It's not currently compatible with Java 11. The logic in `conf/pulsar_env.sh` to set PULSAR_GC_LOG currently handles only Java 8:

https://github.com/apache/pulsar/blob/8d3c0df33e6589bf1ab8cc427409c7d222509237/conf/pulsar_env.sh#L50-L58

there's also similar logic in `bin/function-localrunner` so it probably makes sense to fix that too:

https://github.com/apache/pulsar/blob/c6158e3d3e0e215e0bade91a557dc4bdb63cc297/bin/function-localrunner#L31-L39

**Comment by jiazhai** [comment]
@Jason918 Would you please help update your branch with the latest master? seems the always CI get failed.

**Comment by Jason918** [comment]
> @Jason918 For bookie startup, it will be better to add gc log too. In my production env, i have add the gc log for broker, zookeeper and bookie.

OK, Added gc log for bookie in the updates.

**Comment by Jason918** [comment]
> @Jason918 Would you please help update your branch with the latest master? seems the always CI get failed.

OK, merged with master.
BTW, Is it my commits causing the CI failed?  These updates seems trivial.

**Comment by codelipenghui** [comment]
I agree with the motivation of the PR, it's useful for the production environment. Since we are trying to change the default value, it will make difference in the new Pulsar release, I think it's better to discuss this at the dev email thread first.

**Pull request closed without merging**
