### PR TITLE
[broker][monitor] add `persistent_subscription_consumer_count` for `PersistentSubscription`

### PR DESCRIPTION
**Pull request by tjiuming**
Fixes https://github.com/apache/pulsar/issues/15032

### Motivation

add `persistent_subscription_consumer_count` for `PersistentSubscription` 

Need to update docs? 

- [x] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [ ] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Review by eolivelli — CHANGES_REQUESTED** [review]
Why are we using the Prometheus API ?

Please follow the usual pattern.
If we want to switch to Pure Prometheus API we should discuss this in the community and make a plan

**Comment by tjiuming** [comment]
> Why are we using the Prometheus API ?
> 
> Please follow the usual pattern. If we want to switch to Pure Prometheus API we should discuss this in the community and make a plan

There are already so many Prometheus API usages in pulsar, right?  Do we need to delete all the usages and discuss if we are allowed to use Prometheus API?

**Comment by eolivelli** [comment]
In this case the subscription metrics are handled in another way, let's stick to the pattern, like in #15042

**Comment by tjiuming** [comment]
> In this case the subscription metrics are handled in another way, let's stick to the pattern, like in #15042
> 
> https://github.com/apache/pulsar/pull/15042/files#diff-79bde2a6feed80b6b6b4b6950bc7d4ccd93946a8ec0b40cc1bef2e7b3e498f21R271

I’m confused, how could I know which metrics can be handled by Prometheus and which can't.

**Comment by Anonymitaet** [comment]
@momo-jun a soft reminder: here is a PR w/ doc-required label, could u pls follow up? Thanks

**Pull request closed without merging**
