### PR TITLE
In Java allow messages that compress to <5mb to be sent with batching enabled

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Similarly to what done in #3673, apply the same behavior with or without batching when publishing messages >5MB that can be compressed to fit into the threshold.

### CODE REVIEW

**Comment by merlimat** [comment]
run integration tests

**Comment by merlimat** [comment]
run integration tests

**Comment by merlimat** [comment]
run java8 tests
run integration tests

**Comment by merlimat** [comment]
run java8 tests
run integration tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests
run integration tests

**Comment by merlimat** [comment]
run java8 tests
run integration tests

**Comment by merlimat** [comment]
Merged in 2.3.1 at 
b725d87

**Pull request merged**
