### PR TITLE
[feat][ci] Add C++ and Python client issues and PRs to Multi Clients project

### PR DESCRIPTION
**Pull request by RobertIndie**
### Motivation

Discussion: https://lists.apache.org/thread/prqt4s8zosh87vq077msy4v0vvc0kxsn
Use the Github action to add C++ and Python client issues and PRs to Multi Clients project automatically.

### Modifications

* Add C++ and Python client issues and PRs to Multi Clients project using the github action.

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by HQebupt — APPROVED** [review]

**Comment by HQebupt** [comment]
Good work!

**Review by shibd — APPROVED** [review]

**Review by Demogorgon314 — APPROVED** [review]
Great feature!

**Review by maxsxu — COMMENTED** [review]
Seems the target project is Classic project, and according to the [README](https://github.com/actions/add-to-project#actionsadd-to-project) of `actions/add-to-project@v0.3.0`:

> Note that this action does not support [GitHub projects (classic)](https://docs.github.com/en/issues/organizing-your-work-with-project-boards).

**Comment by RobertIndie** [comment]
Close this PR since this PR does not support the classic project.

**Pull request closed without merging**
