### PR TITLE
[Broker] Fix call sync method in async rest api for internalSetReplicationClusters and internalRemoveReplicationClusters

### PR DESCRIPTION
**Pull request by liudezhi2098**
Master Issue: #13854
### Motivation

Avoid call sync method in async rest API for PersistentTopicsBase#internalSetReplicationClusters.
Avoid call sync method in async rest API for PersistentTopicsBase#internalRemoveReplicationClusters.
### Modifications

- *Use async instead of sync method.*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Need to update docs? 
  
- [x] `no-need-doc`

### CODE REVIEW

**Comment by liudezhi2098** [comment]
@codelipenghui PTAL

**Review by Technoboy- — APPROVED** [review]
LGTM

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
