### PR TITLE
[Doc] Add Notes for *Create Topic*

### PR DESCRIPTION
**Pull request by Anonymitaet**
Fix https://github.com/apache/pulsar/issues/4897

@cumtwwei @sijie could you please help review? Thank you

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@Jennifer88huang thanks for your suggestion, while this note has been added for 3 files and 5 places. 
Since the note is pretty important and easily ignored when users creating topics, we'd better emphasis it and remind users in every "create topic" related section.

**Comment by sijie** [comment]
run cpp tests
run java8 tests

**Comment by Anonymitaet** [comment]
run c++ tests
run java8 tests

**Comment by sijie** [comment]
run cpp tests

**Comment by Anonymitaet** [comment]
@sijie could you please help merge this PR? Thank you

**Pull request merged**
