### PR TITLE
[improve][broker]Restrict the creation of topics with "-partition--x"

### PR DESCRIPTION
**Pull request by zjxxzjwang**
### Motivation
If you actively create a topic with "-partition--x" (x is an integer)(for example, "peisisten://tenant-name/ns-name/topic-name-partition--1"), the topic can be created successfully, and a node with partition 3 will be attached to the zk. But it is not a partition topic

### Modifications

By modifying the isAllowAutoTopicCreationAsync logic () method, when the topic name contains "- partiton - x" (x is an integer), trigger logic returns false
image

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by lhotari** [comment]
Please add a test case for the new functionality

**Comment by zjxxzjwang** [comment]
> 请为新功能添加测试用例
OK, I've added a test case.

**Comment by zjxxzjwang** [comment]
> 请为新功能添加测试示例

OK, I've added a test case.

**Review by lhotari — APPROVED** [review]
LGTM

**Pull request closed without merging**
