### PR TITLE
[doc] Fix warnings 'Header field "Tutorial" is not supported'

### PR DESCRIPTION
**Pull request by sijie**
*Motivation*

Fix warnings 'Header field "Tutorial" is not supported' on building the website

### CODE REVIEW

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by sijie** [comment]
run cpp tests
run java8 tests

**Comment by sijie** [comment]
run cpp tests
run java8 tests

**Comment by Jennifer88huang** [comment]
run cpp tests

**Comment by codelipenghui** [comment]
run cpp tests

**Comment by codelipenghui** [comment]
run cpp tests

**Pull request merged**
