### PR TITLE
[fix][broker] namespace not found will cause request timeout

### LINKED ISSUE #18497: [Bug] `bin/pulsar-admin topics subscriptions` freeze if namespace not exists
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Master version of Pulsar.

### Minimal reproduce step

1. start standalone:
```java
bin/pulsar standalone --num-bookies 2
```

2. query subscriptions with a nonexistent namespace name:

```java
bin/pulsar-admin topics subscriptions persistent://public/not-exist-namespace/my-topic
```

### What did you expect to see?

Namespace not found error.

### What did you see instead?

Freeze until timeout.

```java
null

Reason: java.util.concurrent.TimeoutException
2022-11-16T17:30:44,445+0800 [main] WARN  org.apache.pulsar.common.util.ShutdownUtil - Triggering immediate shutdown of current process with status 1
java.lang.Exception: Stacktrace for immediate shutdown
	at org.apache.pulsar.common.util.ShutdownUtil.triggerImmediateForcefulShutdown(ShutdownUtil.java:52) ~[org.apache.pulsar-pulsar-common-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
	at org.apache.pulsar.admin.cli.PulsarAdminTool.exit(PulsarAdminTool.java:309) ~[org.apache.pulsar-pulsar-client-tools-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
	at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:300) ~[org.apache.pulsar-pulsar-client-tools-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
```

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by labuladong**
Fixes #18497

### Modifications

`internalGetSubscriptions` didn't handle `namespace not found` exception so the web request won't get response, which causes request timout.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:  https://github.com/labuladong/pulsar/pull/13

### CODE REVIEW

**Review by eolivelli — CHANGES_REQUESTED** [review]
good catch!

Could you please add a test case that covers this fix ?

**Comment by labuladong** [comment]
OK, I will add a test.

**Review by RobertIndie — APPROVED** [review]

**Review by tjiuming — APPROVED** [review]

**Review by nodece — APPROVED** [review]

**Review by liangyepianzhou — APPROVED** [review]

**Review by WJL3333 — APPROVED** [review]

**Comment by nodece** [comment]
@eolivelli Could you review this PR again?

**Review by nicoloboschi — APPROVED** [review]

**Comment by labuladong** [comment]
Can this pr be merged?

**Comment by nodece** [comment]
> Can this pr be merged?

Please wait for @eolivelli.

**Review by eolivelli — APPROVED** [review]
Lgtm

**Pull request merged**
