### PR TITLE
Issue #3807: Fix s3 support for s3 api

### LINKED ISSUE #3807: Ledger Offload error when use S3 type
**Describe the bug**
User use setting : 
```
managedLedgerOffloadDriver=S3
s3ManagedLedgerOffloadRegion=us
s3ManagedLedgerOffloadBucket=fio-dev-pulsar-topic-offload
s3ManagedLedgerOffloadServiceEndpoint=https://us-chhq.ceph.*****
``` 
for ledgerOffload, and meet error when start broker:
```
16:53:31.930 [main] INFO  org.apache.bookkeeper.mledger.offload.OffloaderUtils - Found offloader OffloaderDefinition(name=jcloud, description=JCloud based offloader implementation, offloaderFactoryClass=org.apache.bookkeeper.mledger.offload.jcloud.JCloudLedgerOffloaderFactory) from /pulsar/./offloaders/tiered-storage-jcloud-2.2.1.nar
16:53:32.094 [load-factory-class org.apache.bookkeeper.mledger.offload.jcloud.JCloudLedgerOffloaderFactory] INFO  org.apache.bookkeeper.mledger.offload.OffloaderUtils - Loading offloader factory class org.apache.bookkeeper.mledger.offload.jcloud.JCloudLedgerOffloaderFactory using class loader org.apache.pulsar.common.nar.NarClassLoader[/tmp/pulsar-nar/tiered-storage-jcloud-2.2.1.nar-unpacked]
16:53:32.133 [main] INFO  org.apache.bookkeeper.mledger.offload.jcloud.impl.BlobStoreManagedLedgerOffloader - Constructor offload driver: aws-s3, host: https://us-chhq.ceph.*****, container: fio-dev-pulsar-topic-offload, region: us

16:53:33.565 [main] INFO  org.apache.bookkeeper.mledger.offload.jcloud.impl.BlobStoreManagedLedgerOffloader - Connect to blobstore : driver: aws-s3, region: us, endpoint: https://us-chhq.ceph.*****
17:04:35.723 [bookkeeper-ml-scheduler-OrderedScheduler-4-0] INFO  org.apache.bookkeeper.mledger.offload.jcloud.impl.BlobStoreManagedLedgerOffloader - Connect to blobstore : driver: aws-s3, region: , endpoint: https://us-chhq.ceph.*****
17:05:30.681 [offloader-OrderedScheduler-1-0] ERROR org.jclouds.http.handlers.BackoffLimitedRetryHandler - Cannot retry after server error, command has exceeded retry limit 100: [method=org.jclouds.aws.s3.AWSS3Client.public abstract java.lang.String org.jclouds.s3.S3Client.getBucketLocation(java.lang.String)[fio-dev-pulsar-topic-offload], request=GET https://s3.amazonaws.com/fio-dev-pulsar-topic-offload?location HTTP/1.1]
```  
**Additional context**
In Offload, we leverage [jclouds](https://jclouds.apache.org/reference/providers/#blobstore-providers) to support different blob store provider, in which type "s3" and "aws-s3" are different. 
"aws-s3" is for service provided by Amazon S3;
while "s3" is for service that supported S3 API, but may not provided by Amazon S3.
In this code, we need to keep "s3" instead of change it into "aws-s3"
```
    public static BlobStoreManagedLedgerOffloader create(TieredStorageConfigurationData conf,
                                                         Map<String, String> userMetadata,
                                                         OrderedScheduler scheduler)
            throws IOException {
        String driver = conf.getManagedLedgerOffloadDriver();
        if ("s3".equals(driver.toLowerCase())) {
            driver = "aws-s3";       < ====
        }
        if (!driverSupported(driver)) {
            throw new IOException(
                "Not support this kind of driver as offload backend: " + driver);
        }
```

### PR DESCRIPTION
**Pull request by jiazhai**
Fix #3807 
support s3 offload api

### CODE REVIEW

**Comment by jiazhai** [comment]
run java8 tests
run integration tests

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by jiazhai** [comment]
run integration tests

**Comment by merlimat** [comment]
Merged in 2.3.1 at 
eb96f93

**Pull request merged**
