### PR TITLE
cleanup code for ZkBookieRackAffinityMapping

### PR DESCRIPTION
**Pull request by StevenLuMT**
Descriptions of the changes in this PR:

### Motivation

Simple code cleanup

### Modifications

1. no use import  UnknownHostException for ZkBookieRackAffinityMapping

### CODE REVIEW

**Review by Shoothzj — APPROVED** [review]

**Comment by nicoloboschi** [comment]
I see checkstyle shows 63 errors for `pulsar-zookkeeper-utils`, including unused imports. (the one @StevenLuMT is fixing in this PR)
Is there any reason why we don't strictly follow checkstyle and attach it at the compile phase in every sub-projects? @eolivelli @lhotari @codelipenghui @merlimat

**Comment by Shoothzj** [comment]
The master doesn't have this problem at all.

**Comment by Shoothzj** [comment]
> 

In my memory, this config of checkstyle only checks file that modified not every file in the project

**Comment by Shoothzj** [comment]
> I see checkstyle shows 63 errors for `pulsar-zookkeeper-utils`, including unused imports. (the one @StevenLuMT is fixing in this PR) Is there any reason why we don't strictly follow checkstyle and attach it at the compile phase in every sub-projects? @eolivelli @lhotari @codelipenghui @merlimat
In my memory, this config of checkstyle only checks file that modified not every file in the project

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@nicoloboschi I think we have some component have not apply the check style yet.

**Comment by codelipenghui** [comment]
@StevenLuMT could you please help resolve the conflicts?

**Comment by merlimat** [comment]
This class was already deleted/refactored in master branch

**Comment by Anonymitaet** [comment]
@StevenLuMT for the doc side, this PR cleanup codes, so no need to update docs, correct?

**Comment by codelipenghui** [comment]
> This class was already deleted/refactored in master branch

Sorry @StevenLuMT I will close the PR for now

**Pull request closed without merging**
