### PR TITLE
Update website for 2.4.2 release

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <rxl@apache.org>

### Modifications

- Update website for 2.4.2 release

### CODE REVIEW

**Comment by wolfstudy** [comment]
@sijie @jiazhai @codelipenghui @merlimat PTAL, thanks.

**Comment by wolfstudy** [comment]
> make sure you build the website locally and no broken links.

Yes, `yarn build` successful.

> I would recommend remove 2.4.2 release from releases.json so we can publish the documentation of 2.4.2 release but not promote it as the default release. wait until algolia indexes 2.4.2 release and then add 2.4.2 release to the releases.json. This would ensure the search box work as expected. @tuteng dealt with Algolia index issue before.

@tuteng verified done.

**Comment by tuteng** [comment]
Our goal is that the pages of the new version of the website can be generated correctly and included correctly by the search engine a few days later. In order to prevent the search from being unavailable before the pages are included, we continue to use version 2.4.1 as the default document for a period of time. When the new version search is available, we will set version 2.4.2 as the default document again.

After testing, we need to change the https://github.com/apache/pulsar/blob/fbdfc6d3ea93a4fe994323be26e6bfa97d5c7aab/site2/website/versions.json file to generate the page correctly, and the default version is 2.4.1. @sijie @wolfstudy

**Comment by Anonymitaet** [comment]
@wolfstudy 

- I have double checked with @congbobo184, the contents of [this PR](https://github.com/apache/pulsar/pull/5762) are only for  2.5.0, but they are shown in 2.4.2

- For schema guide, I see only the schema-understand.md is in this PR, do we need to include other schema chapters (.md files) in 2.4.2?

**Pull request closed without merging**
