### PR TITLE
fix partitionsAutoUpdateFuture never complete

### LINKED ISSUE #14624: partitionsAutoUpdateFuture never completes, when the connection is disconnect and reconnect again
**Describe the bug**
related to this issue: #14598 

We have thousands of production machines. We want clients to have higher fault tolerance in the event of network problems, otherwise restarting a large number of client services will be very inconvenient. When a network problem or cluster failure occurs, and then the network is restored or the cluster is restored, and the connection is re-established, the `partitionsAutoUpdateTimerTask` will still not be able to get partitions information normally, this causes `partitionsAutoUpdateFuture` to neither `completeExceptionally` nor `complete`. Then, `partitionsAutoUpdateTimerTask` because the previous `partitionsAutoUpdateFuture` did not `complete`. The `topicsPartitionChangedListener.onTopicsExtended` method will no longer be executed. This will affect our subsequent dynamic expansion of partitions.

https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/PartitionedProducerImpl.java#L104
```
                // if last auto update not completed yet, do nothing.
                if (partitionsAutoUpdateFuture == null || partitionsAutoUpdateFuture.isDone()) {
                    partitionsAutoUpdateFuture =
                            topicsPartitionChangedListener.onTopicsExtended(ImmutableList.of(topic));
                }
```

image

image

### LINKED ISSUE #14642: [Feature] Support reader interceptor
**Is your feature request related to a problem? Please describe.**
In [PIP 23](https://github.com/apache/pulsar/wiki/PIP-23%3A-Message-Tracing-By-Interceptors), pulsar has supported producer interceptor and consumer interceptor, but we don't have reader interceptor for now.

To support reader interceptor will allow users to do integration with Pulsar client.

**Describe the solution you'd like**
Introduce a new ReaderInterceptor interface to intercept message before read operation

### PR DESCRIPTION
**Pull request by wenbingshen**
Fixes #14624 

Master Issue: #14624 

### Modifications 
`partitionsAutoUpdateFuture` should `completeExceptionally` when get partition information due to network connection failure.

Need to update docs? 
- [x] `no-need-doc`

### CODE REVIEW

**Comment by wenbingshen** [comment]
@lhotari @eolivelli @michaeljmarshall Could you help take a look? Thanks very much.

**Comment by lhotari** [comment]
Good catch! 

I know it's hard, but would you like to try to find a way to add a test case? I shared some details about Pulsar tests in https://github.com/apache/pulsar/pull/14602#discussion_r822363841 .

**Review by lhotari — APPROVED** [review]

**Review by Shoothzj — APPROVED** [review]

**Review by RobertIndie — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Comment by wenbingshen** [comment]
> Good catch!
> 
> I know it's hard, but would you like to try to find a way to add a test case? I shared some details about Pulsar tests in [#14602 (comment)](https://github.com/apache/pulsar/pull/14602#discussion_r822363841) .

Thanks for your review. Of course. I could try to add a test.

**Review by michaeljmarshall — APPROVED** [review]
LGTM.

@wenbingshen - it looks like the same issue is present in this method: `MultiTopicsConsumerImpl#subscribeIncreasedTopicPartitions`. Would you like to fix that one too?

**Review by Technoboy- — APPROVED** [review]

**Comment by wenbingshen** [comment]
> LGTM.
> 
> @wenbingshen - it looks like the same issue is present in this method: `MultiTopicsConsumerImpl#subscribeIncreasedTopicPartitions`. Would you like to fix that one too?

@michaeljmarshall Thanks for your review :).  I looked at `MultiTopicsConsumerImpl#subscribeIncreasedTopicPartitions` implementation. I think it doesn't have this problem.

**Comment by wenbingshen** [comment]
@lhotari @michaeljmarshall @codelipenghui  I have added a test to check producer and consumer's partitionsAutoUpdateFuture's result. PTAL. Thanks.

**Comment by michaeljmarshall** [comment]
@wenbingshen - sorry, I had an old branch checked out locally and it didn't have the fix. I see now that master (and all active Pulsar branches) are good. Thanks for looking at `MultiTopicsConsumerImpl`.

**Comment by wenbingshen** [comment]
> @wenbingshen - sorry, I had an old branch checked out locally and it didn't have the fix. I see now that master (and all active Pulsar branches) are good. Thanks for looking at `MultiTopicsConsumerImpl`.

@michaeljmarshall Yes, the current active Pulsar branches are good. :)

**Comment by wenbingshen** [comment]
@codelipenghui The consumer test is always failing, so I removed the test that checks the results of the consumer automatic detection partition, since this PR has not fixed any consumer-related code, if we want to verify the status of the consumer, we can submit another PR to verify, PTAL.

**Comment by wenbingshen** [comment]
I think CPP、Python Tests failed not related to this PR: https://github.com/apache/pulsar/runs/5581897555?check_suite_focus=true

**Pull request merged**
