### PR TITLE
always remove message data size

### PR DESCRIPTION
**Pull request by MaiCw4J**
Signed-off-by: mak <610546069@qq.com>

### Motivation

always remove message data size when message get out of the queue

may cause the `batchReceive()` method to call `hasEnoughMessagesForBatchReceive()` to determine that the conditions are met, but there is not actually enough data in the queue!
### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by zymap — COMMENTED** [review]
Is there has any possibility to add a test for that? So that we can make that case is protected.

**Comment by MaiCw4J** [comment]
of course, I would love to do this, but I don't know how to simulate this kind of case, can you give me some help or advise?

**Review by sijie — APPROVED** [review]

**Comment by sijie** [comment]
@MaiCw4J You mentioned the following in the description of this pull request.

```
may cause the batchReceive() method to call hasEnoughMessagesForBatchReceive() to determine that the conditions are met, but there is not actually enough data in the queue!
```

Can you write a unit test to reproduce the issue you described in using batchReceive? Then you can confirm if this change fixes the issue or not.

**Comment by MaiCw4J** [comment]
this is not my actual problem, I found out when I was reading the source code :(

**Comment by zymap** [comment]
@MaiCw4J Could you please rebase the code? I want to merge it and make it release in the 2.7.1

**Review by zymap — APPROVED** [review]

**Pull request merged**
