### PR TITLE
[Doc] Update "load distribution" as "load balance"

### PR DESCRIPTION
**Pull request by Jennifer88huang**
### Motivation
The orignal text is "load distribution". Load balance is more accurate than load distribution, and while correcting the english term, it also makes translation into Chinese easier.

### Modifications
Refine the term "load distribution" as "load balance".

### CODE REVIEW

**Comment by sijie** [comment]
run cpp tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Pull request merged**
