### PR TITLE
Bump snappy zstd version to fix CompressorCodecBackwardCompatTest on Apple M1

### PR DESCRIPTION
**Pull request by Shoothzj**
### Motivation
Make `CompressorCodecBackwardCompatTest` paas on Apple M1

### Modifications
- Bump snappy from 1.1.7 to 1.1.8.4
- Bump zstd version from 1.3.7-3 to 1.1.8.4

### CODE REVIEW

**Review by Demogorgon314 — APPROVED** [review]

**Review by Technoboy- — CHANGES_REQUESTED** [review]
Does the new added dependency jar license under the Apache License?

**Comment by Shoothzj** [comment]
@Technoboy-  This PR not adding any new dependency in project. And `zstd` dependency only using test scope.

**Comment by Shoothzj** [comment]
@merlimat @eolivelli @nicoloboschi @codelipenghui PTAL, the failing CI is not related to this.

**Review by merlimat — APPROVED** [review]

**Comment by Shoothzj** [comment]
@Technoboy- ping

**Review by Technoboy- — APPROVED** [review]

**Pull request merged**
