### PR TITLE
Remove global zookeeper option in code base

### PR DESCRIPTION
**Pull request by liketic**
### Motivation

The option ```--global-zookeeper``` is deprecated in previous version. This PR will remove it and related code or replace it with the new name ```configuration store``` in our code base. See #3307 and #3305 .

### Modifications

Describe the modifications you've done.

### Result

After your change, what will change.

### CODE REVIEW

**Comment by srkukarni** [comment]
rerun java8 tests

**Comment by liketic** [comment]
rerun java8 tests

**Comment by sijie** [comment]
@merlimat can you review this PR?

**Comment by sijie** [comment]
ping @merlimat ?

**Comment by sijie** [comment]
ping @merlimat ?

**Comment by sijie** [comment]
Move this to 2.4.0.

**Comment by liketic** [comment]
hi @merlimat , is that's possible to get this merged ? Thanks :)

**Comment by tisonkun** [comment]
Closed as long stale and too many conflicts.

I don't know whether we remove config keys in this way, but it seems to me a breaking change in one major release cycle.

**Pull request closed without merging**
