### PR TITLE
[improve][cli][PIP-280] Retrofit `pulsar-cli-utils` into `pulsar-broker` and `pulsar-client-tools`

### PR DESCRIPTION
**Pull request by JooHyukKim**
- Main Issue: #21056 
- PIP: #20691 

### Motivation

- Retrofit `pulsar-cli-utils` into `pulsar-broker` and `pulsar-client-tools`.
- This seems to cover last bits of refactor around time and byte-unit.

### Modifications

- Made `TokensCliUtils` in `pulsar-broker` module to delegate time parsing logic to `pulsar-cli-utils`.
- Same as above, but to `CmdPersistentTopics`

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/JooHyukKim/pulsar/pull/23/

### CODE REVIEW

**Comment by JooHyukKim** [comment]
> This seems to cover last bits of refactor around time and byte-unit.

/cc @tisonkun, WDYT?

**Review by tisonkun — APPROVED** [review]
LGTM.

Out thread - I found that `RelativeTimeUtil` is duplicated in `pulsar-common` and `pulsar-cli-utils`. What's the reason, and if we can eliminate the duplicate?

**Comment by JooHyukKim** [comment]
WRT failing tests, they are flakey since they all pass in my fork.

**Comment by JooHyukKim** [comment]
> Out of thread - I noticed that `RelativeTimeUtil` is duplicated in both `pulsar-common` and `pulsar-cli-utils`. Is there a specific reason for this? Can we eliminate the duplication?

Indeed, `RelativeTimeUtil` is duplicated. However, I suggest we retain it. 

The rationale is that the duplication serves as a small trade-off to avoid introducing a dependency between the two modules. 

Furthermore, the likelihood of changes to the `RelativeTimeUtil` implementation is quite low, making the cost of this duplication minimal.

**Comment by tisonkun** [comment]
> WRT failing tests, they are flakey since they all pass in my fork.

Lari fixes an amount of flaky tests these days, you can merge master and push this branch to retrigger the CI.

**Review by tisonkun — APPROVED** [review]
LGTM.

**Comment by tisonkun** [comment]
Merging..

**Pull request merged**
