### PR TITLE
fix: unsafe cast of schema to JSONSchema

### PR DESCRIPTION
**Pull request by jerrypeng**
### Motivation

Reference to issue #2767

### CODE REVIEW

**Comment by jerrypeng** [comment]
Cherry pick back to 2.1

**Comment by jerrypeng** [comment]
rerun tests please

**Comment by jerrypeng** [comment]
rerun cpp tests
rerun integrations tests
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by gmethvin** [comment]
Thanks for the quick turnaround on this!

**Comment by srkukarni** [comment]
run java8 tests

**Comment by srkukarni** [comment]
run java8 tests

**Pull request merged**
