### PR TITLE
CPP Client - Removing boost dependencies from interface.

### PR DESCRIPTION
**Pull request by jai1**
### Motivation

Want to remove boost dependencies from CPP Client interface.

### Modifications

Changed boost smart pointers and functions to std.

### Result

No change in the code logic.

@msb-at-yahoo - Thanks for the push on this.

### CODE REVIEW

**Comment by jiazhai** [comment]
@jai1 This error reported several times in cpp tests:
```
[0;32m[ RUN      ] [mReaderTest.testReaderAfterMessagesWerePublished
unknown file: Failure
C++ exception with description "tr1::bad_weak_ptr" thrown in the test body.
[0;31m[  FAILED  ] [mReaderTest.testReaderAfterMessagesWerePublished (1 ms)
```

**Comment by merlimat** [comment]
@jai1 I think we should probably convert every usage of `boost::*_pointer` in the codebase in one single commit, not just the ones exposed in the API.

**Comment by jai1** [comment]
rerun cpp tests

**Comment by jai1** [comment]
retest this please

**Comment by jai1** [comment]
rerun integration tests

**Comment by jai1** [comment]
rerun cpp tests

**Comment by jai1** [comment]
rerun integration tests

**Pull request merged**
