### PR TITLE
[website][pulsar-client/pulsar-perf] pulsar-client and pulsar-perf cli doc command flag duplicated

### PR DESCRIPTION
**Pull request by urfreespace**
### Motivation
Support auto generate HTML page for pulsar client cli tool, for example: https://github.com/apache/pulsar/tree/asf-site/content/tools/pulsar-admin

### Modifications
fix duplicated long and short command line parameter names for pulsar-client cli docs
fix duplicated long and short command line parameter names for pulsar-perf cli docs

(Please pick either of the following options)

This change is a trivial rework / code cleanup without any test coverage.

(or)

This change is already covered by existing tests, such as (please describe tests).

(or)

This change added tests and can be verified as follows:

(example:)

Added integration tests for end-to-end deployment with large payloads (10MB)
Extended integration test for recovery after broker failure

### Does this pull request potentially affect one of the following parts:
If yes was chosen, please highlight the changes

Dependencies (does it add or upgrade a dependency): (yes / no)
The public API: (yes / no)
The schema: (yes / no / don't know)
The default values of configurations: (yes / no)
The wire protocol: (yes / no)
The rest endpoints: (yes / no)
The admin cli options: (yes / no)
Anything that affects deployment: (yes / no / don't know)

### Documentation
Does this pull request introduce a new feature? (yes / no)
If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
If a feature is not applicable for documentation, explain why?
If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by urfreespace** [comment]
@Anonymitaet  @tuteng PTAL, thanks

**Review by tuteng — APPROVED** [review]
LGTM

**Comment by Anonymitaet** [comment]
@urfreespace thanks for your contribution!

**Comment by tuteng** [comment]
@315157973 PTAL

**Comment by tuteng** [comment]
Unrelated test failures
```
Error:  testTokenProducerAndConsumer(org.apache.pulsar.client.api.TokenAuthenticatedProducerConsumerTest)  Time elapsed: 0.144 s  <<< FAILURE!
org.apache.pulsar.client.admin.PulsarAdminException$NotAuthorizedException: HTTP 401 Unauthorized
	at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:228)
	at org.apache.pulsar.client.admin.internal.BaseResource$1.failed(BaseResource.java:130)
	at org.glassfish.jersey.client.JerseyInvocation$1.failed(JerseyInvocation.java:882)
	at org.glassfish.jersey.client.JerseyInvocation$1.completed(JerseyInvocation.java:863)
```

**Comment by urfreespace** [comment]
image
@tuteng Was automatically cancelled due to timeout?

**Comment by tuteng** [comment]
> image
> @tuteng Was automatically cancelled due to timeout?

Because the test run time exceeds 120 minutes

**Pull request merged**
