### PR TITLE
[C++] Link with protobuf-lite to reduce binary size

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Since we have always used `option optimize_for = LITE_RUNTIME` in `PulsarApi.proto`, we should also link with the `protobuf-lite.a` library when linking statically, as it will reduce the overall size of the `libpulsar.a` that includes all the dependencies.

Example of size diff: 

```
$ ll -h /opt/homebrew/Cellar/protobuf/3.19.4/lib/libprotobuf*.a
-r--r--r--  1 mmerli  admin   874K Jan 28 08:41 /opt/homebrew/Cellar/protobuf/3.19.4/lib/libprotobuf-lite.a
-r--r--r--  1 mmerli  admin   4.0M Jan 28 08:41 /opt/homebrew/Cellar/protobuf/3.19.4/lib/libprotobuf.a
```

### CODE REVIEW

**Comment by BewareMyPower** [comment]
I think we should still keep the regular protobuf version to support protobuf native schema. The lite version doesn't support serializing to or from `google::protobuf::Descriptor`.

**Comment by merlimat** [comment]
> I think we should still keep the regular protobuf version to support protobuf native schema. The lite version doesn't support serializing to or from `google::protobuf::Descriptor`.

Uhm, I think there's a problem with the way the descriptor is currently exposed. In the dynamic library, we're generally including all the dependencies, in order to create a dependency-less libpulsar.so. All the symbols of the dependencies are hidden inside, to avoid conflict with other versions of same libraries. 

I believe that in many cases, this would not be working: 

```cpp
PULSAR_PUBLIC SchemaInfo createProtobufNativeSchema(const google::protobuf::Descriptor* descriptor);
```

because the `Descriptor` symbol is hidden and not accessible from the application code.

**Comment by BewareMyPower** [comment]
> I believe that in many cases, this would not be working:
> 
> ```c++
> PULSAR_PUBLIC SchemaInfo createProtobufNativeSchema(const google::protobuf::Descriptor* descriptor);
> ```
> 
> because the `Descriptor` symbol is hidden and not accessible from the application code.

The protobuf dependency must be imported to use protobuf native schema, so the symbol could be imported from protobuf.

```c++
const auto schemaInfo = createProtobufNativeSchema(::proto::TestMessage::GetDescriptor());
```

What I concerned is if we imported the protobuf-lite dependency, is there any conflict with the user provided protobuf dependency?

**Comment by tisonkun** [comment]
Closed as the development of the C++ client has been permanently moved to https://github.com/apache/pulsar-client-cpp.

**Pull request closed without merging**
