### PR TITLE
[pulsar-broker] add support for connection expiry and renew-cnx

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

Right now, broker authenticates client only at the time of opening the connection and this connection become valid for it's lifetime and client can produce/consume messages on this connection even though auth-data provided on that connection is expired.  So, we want to close/renew such connections which are expired on the broker.
So, right now, broker doesn't close the expired connection and broker-client don't have capability to renew the connection without closing it.

### Modification
Add option in broker to renew connection by asking client to resend renewed auth-data without closing the connection. If client fails to send refreshed-valid auth-data then broker closes the connection. 

### Result
Broker will have capability to check connection expiry after the auth-data is expired and broker can close the expired connection. This feature will be disabled by default.

### CODE REVIEW

**Comment by merlimat** [comment]
@rdhabalia Since this is not a fix or a trivial change, I'd move this to 2.4.0 rather than 2.3.1

**Comment by rdhabalia** [comment]
rerun integration tests
rerun java8 tests

**Comment by rdhabalia** [comment]
rerun integration tests

**Comment by rdhabalia** [comment]
rerun java8 tests

**Comment by rdhabalia** [comment]
rerun java8 tests

**Comment by rdhabalia** [comment]
rerun java8 tests

**Comment by rdhabalia** [comment]
rerun java8 tests

**Comment by codelipenghui** [comment]
@rdhabalia do we need this for 2.4.0? or shall move it to 2.5.0?

**Comment by sijie** [comment]
@rdhabalia I moved this pull request to 2.5.0 since it is idle for a while. If it is needed in 2.4.0, please move it back.

**Comment by aahmed-se** [comment]
@rdhabalia can you rebase this.

**Comment by rdhabalia** [comment]
@aahmed-se I have rebased the PR and it took a while as lot of changes have been merged since this PR was created. this PR was created in version-2.3 as this was one of our security requirement so, I am changing milestone to 2.4

**Comment by rdhabalia** [comment]
retest this please

**Comment by rdhabalia** [comment]
rerun java8 tests

**Comment by rdhabalia** [comment]
rerun java8 tests

**Comment by rdhabalia** [comment]
rerun java8 tests

**Comment by rdhabalia** [comment]
rerun cpp tests

**Comment by rdhabalia** [comment]
@merlimat this is related to PIP-51.

**Comment by codelipenghui** [comment]
@rdhabalia I moved this pull request to 2.7.0 since it is idle for a while. If it is needed in 2.6.0, please move it back.

**Comment by codelipenghui** [comment]
@rdhabalia I moved this pull request to 2.9.0 since it is idle for a while. If it is needed in 2.8.0, please move it back

**Pull request closed without merging**
