### PR TITLE
Removed managed-ledger-shaded artifact

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Managed ledger shaded artifact was added to be used from Presto connector. Since #4045 this is not being used anymore.

### CODE REVIEW

**Comment by sijie** [comment]
@merlimat do you want to include this in 2.4.0 or shall we move to 2.5.0?

**Comment by jerrypeng** [comment]
@merlimat could renaming managed-ledger-original to managed-ledger be a BC breaking change? While I don't think many people are using managed-ledger-original, there are a few people using managed-ledger-original for their single process "integration" tests like we have in pulsar-broker.  However, if they just depend on pulsar-broker they should be fine.

**Comment by merlimat** [comment]
This is not critical, moving to 2.5

**Comment by merlimat** [comment]
@jerrypeng you're right, that's prob the reason why the test are failing, I'll take the renaming out.

**Comment by aahmed-se** [comment]
@merlimat can you rebase this.

**Comment by merlimat** [comment]
run integration tests

**Comment by merlimat** [comment]
run integration tests

**Pull request merged**
