### PR TITLE
[pulsar-io] upgrade debezium version

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation
Upgeade debezium version for io connector.

### CODE REVIEW

**Comment by eolivelli** [comment]
Don't we have to update license files as well?

**Comment by rdhabalia** [comment]
we don't have version defined into [license file](https://github.com/apache/pulsar/blob/master/pulsar-io/debezium/postgres/src/main/resources/META-INF/services/pulsar-io.yaml)

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by codelipenghui — APPROVED** [review]

**Review by sijie — APPROVED** [review]

**Comment by sijie** [comment]
@rdhabalia I think the debezium integration failed. Please take a look at those errors.

**Comment by sijie** [comment]
@rdhabalia it seems that debezium integration tests are still failing.

**Comment by lxcid** [comment]
Is there anyway we can help to land this? i check the failure and see a few unrelated issue like rabbitmq and presto.

**Comment by eolivelli** [comment]
@lxcid we have some issues on CI, if the failures are not related to the patch then we simply rerun the tests.

There is an ongoing effort to fix all flakes and also to reduce overall CI time for PR validation

**Comment by lxcid** [comment]
Thanks @eolivelli for the reply! our assessment is still very rough and not reliable but we wanted to integrate pulsar for a while, and have been tracking the debezium part which is our blocker. finger cross in seeing it get landed! thanks so much!

**Comment by sijie** [comment]
@rdhabalia Can you take a look at the integration failures? It might be still related to debezium.

**Comment by lxcid** [comment]
I hope I can help a bit, I'm diving the codes, and compiling. the process take a long time, meanwhile, I'm looking at the failing test and it seems really weird that the test case is validating Avro instead of Json when the code obviously uses Json.

https://github.com/apache/pulsar/blob/16a2240a5af8402cf655049292d669378e694fa3/tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java#L168-L171

Screen Shot 2021-02-23 at 12 08 10 AM

I'll continue to dig to see if I can figure it out.

**Comment by eolivelli** [comment]
@rdhabalia this PR is superseded by the more recent #11204

**Pull request closed without merging**
