### PR TITLE
Upgrade guava to 27.0.1

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

As reported in #3493 we're using Guava 21 which has some known vulnerabilities. Upgrade to latest version.

### CODE REVIEW

**Comment by merlimat** [comment]
There are some issues with the shading of jclouds and the new guava. @jiazhai Do we still need the `jcloud-shaded` module or that was a stop-gap solution?

**Comment by sijie** [comment]
@merlimat @jiazhai do we need this pull request for 2.4.0? or can it be moved to 2.5.0?

**Comment by ivankelly** [comment]
@merlimat @sijie I don't think we're hit by the vuln in guava. We should try to track the latest where possible though in any case.

**Comment by codelipenghui** [comment]
@merlimat Is this PR need to onboard the 2.6.0 release? or we can move it to 2.7.0?

**Comment by codelipenghui** [comment]
move to 2.7.0

**Pull request closed without merging**
