### PR TITLE
[Issue 6887][pulsar-broker] ttlDurationDefaultInSeconds not applying

### LINKED ISSUE #6887: ttlDurationDefaultInSeconds is not applied
Pulsar 2.5.0
broker.conf has ttlDurationDefaultInSeconds=3600
But when creating a new namespace it is still created with ttl 0.

### PR DESCRIPTION
**Pull request by Omega-Ariston**
Fixes #6887 

### Motivation
The ttl for namespaces should be retrieved from broker's configuration if it is not configured at namespace policies. However, the current code only returns the value stored in namespace policies directly without judging if it is configured or not.

### Modifications

Added a condition to test if ttl is configured at namespace policies. If not, retrieve value stored in broker's configuration and return it as output.

### CODE REVIEW

**Comment by trexinc** [comment]
I don't think this is a valid fix. It fixes only the cli, creating a namespace using API will still have the issue.

**Comment by trexinc** [comment]
In the broker in

**Comment by trexinc** [comment]
@codelipenghui  @Omega-Ariston - there is actually the following code in the broker. So it seems that it does take the default TTL into consideration at the actual expiry check. So the bug is kind of more cosmetic than anything else.
Do you think that maybe get-namespace-ttl API should return the effective TTL?

    @Override
    public void checkMessageExpiry() {
        TopicName name = TopicName.get(topic);
        Policies policies;
        try {
            policies = brokerService.pulsar().getConfigurationCache().policiesCache()
                    .get(AdminResource.path(POLICIES, name.getNamespace()))
                    .orElseThrow(() -> new KeeperException.NoNodeException());
            int defaultTTL = brokerService.pulsar().getConfiguration().getTtlDurationDefaultInSeconds();
            int message_ttl_in_seconds = (policies.message_ttl_in_seconds <= 0 && defaultTTL > 0) ? defaultTTL
                    : policies.message_ttl_in_seconds;
            if (message_ttl_in_seconds != 0) {
                subscriptions.forEach((subName, sub) -> sub.expireMessages(message_ttl_in_seconds));
                replicators.forEach((region, replicator) -> ((PersistentReplicator)replicator).expireMessages(message_ttl_in_seconds));
            }
        } catch (Exception e) {
            if (log.isDebugEnabled()) {
                log.debug("[{}] Error getting policies", topic);
            }
        }
    }

**Comment by trexinc** [comment]
As I see it - it is actually a nice feature. You can changes the global default TTL and it immediately applies to all namespaces with default 0 TTL.
So probably just best to document it, and not make any code changes.

**Comment by trexinc** [comment]
@Omega-Ariston, sorry, had a long day and didn't even notice that your fix is for the "cosmetic" issue.

One issue with the fix that I see is that after it you can't tell which namespaces have the default 0 TTL. So maybe the command should print both global default and the one set on the namespace.

**Comment by codelipenghui** [comment]
@Omega-Ariston I think you can fix the `mergeNamespaceWithDefaults` method in the AdminResource class, we merge all namespace policy with the broker configuration here.

**Comment by Omega-Ariston** [comment]
> @Omega-Ariston I think you can fix the `mergeNamespaceWithDefaults` method in the AdminResource class, we merge all namespace policy with the broker configuration here. And please add some unit tests for the change to avoid some other changes to break it.

Okay thx, working on it :)

**Comment by Omega-Ariston** [comment]
> As I see it - it is actually a nice feature. You can changes the global default TTL and it immediately applies to all namespaces with default 0 TTL.
> So probably just best to document it, and not make any code changes.

Maybe returning the actual working TTL value is what we want here, as you said it's more like a cosmetic fix :D

**Comment by jiazhai** [comment]
@Omega-Ariston as Penghui mentioned, would you please help add a unit tests for this?

**Comment by Omega-Ariston** [comment]
> @Omega-Ariston as Penghui mentioned, would you please help add a unit tests for this?

Sorry for the delay, got some business these days...I have added a few lines in `AdminApiTest.java` to cover this issue. Not sure if I got them in the right place tho.

**Pull request merged**
