### PR TITLE
Update website for 2.4.1 release

### PR DESCRIPTION
**Pull request by jiazhai**
Update website for 2.4.1 release

### CODE REVIEW

**Comment by jiazhai** [comment]
update with latest master

**Comment by jerrypeng** [comment]
Hey the website's search bar is broken now. Any ideas why?

**Comment by sijie** [comment]
Jerry, it happened last time when we released 2.4.0. It is most likely due to the index issue in Algolia doc search. We might need to wait for a few hours until the reindex completes. We can help double check if that is the case this time.

**Comment by wolfstudy** [comment]
Change the Milestone to 2.4.2, because of conflict.

**Pull request merged**
