### PR TITLE
[websocket] support pong in websocket

### LINKED ISSUE #10014: Add "pong" logic in websocket server
**Is your enhancement request related to a problem? Please describe.**
As described in the websocket protocol, the ping/pong would allow to have a control frame to detect network issue in the websocket layer.

**Describe the solution you'd like**
When message sent to server via websocket via a "ping", the server should send a "pong" back.

**Describe alternatives you've considered**
Message acknowledgment of the pulsar layer can be used currently, but a not received ack could be caused  by other reasons than network issue. Plus it's a bit weird to have to detect network issue in the application layer.

Here is a description of the "ping/pong" websocket control frame : 
https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers

### PR DESCRIPTION
**Pull request by linlinnn**
Fixes #10014 

### Motivation
Add "pong" logic in websocket server

### Modifications
add WebSocketPingPongServlet to apply "pong" when on ping

### Verifying this change
- [x] Make sure that the change passes the CI checks.

### CODE REVIEW

**Review by codelipenghui — COMMENTED** [review]
Looks good to me, could you please help add some test for this change?

**Comment by linlinnn** [comment]
@codelipenghui PTAL

**Review by 315157973 — APPROVED** [review]
LGTM

**Review by codelipenghui — APPROVED** [review]

**Review by sijie — APPROVED** [review]

**Comment by youzipi** [comment]
as websocket producer and websocket pingpong has different url,
how can i use this to make a heartbeat to keep connection alive?
@linlinnn

**Comment by michaeljmarshall** [comment]
> websocket producer and websocket pingpong has different url, how can i use this to make a heartbeat to keep connection alive? @linlinnn

Please see @lhotari's comment for more information https://github.com/apache/pulsar/issues/10014#issuecomment-1623064436

**Pull request merged**
