### PR TITLE
Make bundle REST calls to be async

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Several operations that work over bundle are triggering multiple calls, one per bundle, against the broker, to be redirected to other brokers. 

Since these HTTP calls are handled synchronously, if there are many bundles in a namespace, it can cause a deadlock in Jetty threads, since 1 call will fan out to make multiple calls to itself.

To avoid that,  we need to make sure all the operations regarding bundles are handled asynchronously.

### CODE REVIEW

**Comment by wolfstudy** [comment]
ping @merlimat Can you merge master code and fix conflict?

**Comment by wolfstudy** [comment]
ping @merlimat again,  Can you merge master code and fix conflict?

**Comment by codelipenghui** [comment]
@merlimat Could you please rebase to the apache/master branch?

**Comment by codelipenghui** [comment]
move to milestone 2.8.0 first

**Comment by codelipenghui** [comment]
@merlimat Could you please rebase to the apache/master branch?

**Comment by mattisonchao** [comment]
Hi, @merlimat 

Looks like some PRs already fixed some parts of this code. If you don't have time to continue. 
I will try to continue working on it.

**Comment by tisonkun** [comment]
Closed as stale and conflict. Please rebase and resubmit the patch if it's still relevant.

**Pull request closed without merging**
