### PR TITLE
[fix] [branch-3.0] fix compile error in branch 3.0

### PR DESCRIPTION
**Pull request by thetumbled**
### Motivation
CI in branch-3.0 can't pass due to https://github.com/apache/pulsar/pull/22130#issuecomment-1968319314.

### Modifications
The solution is: first, cherry pick https://github.com/apache/pulsar/pull/20782 into branch-3.0, then we use this pr https://github.com/apache/pulsar/pull/22143 to fix the problem.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/thetumbled/pulsar/pull/44

### CODE REVIEW

**Comment by thetumbled** [comment]
PTAL, thanks. @lhotari @Technoboy-

**Comment by lhotari** [comment]
@thetumbled Thanks for the fix. For tracking purposes we will need to have a 1-to-1 mapping between the cherry-picked commit. This is something that we haven't properly documented in our release process. The cherry-picking process is currently mostly tribal knowledge without clear documentation. I have ranted about this in the past on the mailing list in this thread: https://lists.apache.org/thread/69mwjso51kzkrv5xgdmw04d9wngbg8br . 
Yesterday, I started looking into improving the documentation of the current process. One section has been added where some thoughts and a tool is shared to prevent the problems that are present in branch-3.0.
Doc is here:
https://pulsar.apache.org/contribute/release-process/#cherry-picking-changes-scheduled-for-the-release
However, that's not a description of the current process. 
A lot of the problems with cherry-picking occur since cherry-picks happen in the wrong order or dependent changes don't get picked. The added section will help in that, but it contains a lot of gaps.

**Comment by codelipenghui** [comment]
Hmmm, I think we can't cherry-pick https://github.com/apache/pulsar/pull/20782 because it's not a BUG fix, and it might be risky for LTS release.

**Comment by thetumbled** [comment]
> Hmmm, I think we can't cherry-pick #20782 because it's not a BUG fix, and it might be risky for LTS release.

Or we could revert https://github.com/apache/pulsar/pull/22101 in branch-3.0, which is also not a BUG fix.

**Comment by heesung-sn** [comment]
Let's revert https://github.com/apache/pulsar/pull/22101 .

**Comment by thetumbled** [comment]
> Let's revert #22101 in branch-3.0.
great, close this pr.

**Comment by thetumbled** [comment]
> Let's revert #22101 in branch-3.0.

great, close this pr.

**Pull request closed without merging**
