### PR TITLE
[improve] [pip] PIP-358: let resource weight work for OverloadShedder, LeastLongTermMessageRate, ModularLoadManagerImpl.

### PR DESCRIPTION
**Pull request by thetumbled**
PIP: https://github.com/apache/pulsar/pull/22889

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/thetumbled/pulsar/pull/57

### CODE REVIEW

**Comment by thetumbled** [comment]
As the proposal PR has been merged, we can move forward with this implementation PR. 
PTAL, thanks. @heesung-sn @Demogorgon314 @BewareMyPower @poorbarcode @Technoboy-

**Review by Technoboy- — APPROVED** [review]

**Review by Demogorgon314 — COMMENTED** [review]
Do we have a test to cover this change?

**Comment by BewareMyPower** [comment]
+1 to have a test for it

**Comment by thetumbled** [comment]
> Do we have a test to cover this change?

I add some tests to cover this change, PTAL, thanks.

**Review by BewareMyPower — APPROVED** [review]

**Review by Demogorgon314 — APPROVED** [review]

**Pull request merged**
