### PR TITLE
[feature][doc] Add badges for README

### LINKED ISSUE #15958: [feat][website] add badges to README
Can we add some badges to `README`？

- https://docs.jupyter.org/en/latest/contributing/docs-contributions/doc-new-repos.html#badges-in-readme

image

- https://github.com/apache/pulsar/issues/15538#issuecomment-1126064195

### PR DESCRIPTION
**Pull request by SignorMercurio**
Fixes #15958

### Motivation

Please see https://github.com/apache/pulsar/issues/15538#issuecomment-1126064195 for more info.

### Modifications

Add badges for README. Also formatted README.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no
  - The rest endpoints: no
  - The admin cli options: no
  - Anything that affects deployment: no

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [ ] `doc-not-needed` 
(Please explain why)
  
- [x] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by Anonymitaet — APPROVED** [review]

**Comment by Anonymitaet** [comment]
@SignorMercurio 

1. Should users be navigated to the following websites after clicking the badges?

image

1️⃣ not sure 
2️⃣ https://hub.docker.com/r/apachepulsar/pulsar?
3️⃣ https://github.com/apache/pulsar/graphs/contributors?
4️⃣ https://github.com/apache/pulsar/commits/master
5️⃣ https://pulsar.apache.org/download ?

2. Does it make sense the add the badges in red circles? Users can be navigated to https://pulsar.apache.org/docs/next/ after clicking `docs`

image

**Comment by SignorMercurio** [comment]
@Anonymitaet 

1. My bad, I forgot to add these links. I'll fix this soon.

2. I'll check the codecov status and add these badges.

**Comment by SignorMercurio** [comment]
@Anonymitaet 

The docs and codecov badges are generated by [shields.io](https://shields.io/) when [Read the Docs](https://readthedocs.org/) and [Codecov](https://docs.codecov.com/docs) are used. I think this project does not utilize these two and therefore it's not suitable to add these two badges.

**Comment by dave2wave** [comment]
Wrong URL for an ASF release

**Comment by Anonymitaet** [comment]
> Wrong URL for an ASF release

@dave2wave we use https://github.com/apache/pulsar/releases, is it incorrect?

**Pull request merged**
