### PR TITLE
Fix ensure single-topic consumer can be closed

### PR DESCRIPTION
**Pull request by HugeSkull**
It is found that there is a logic problem in creating a consumer, which may cause the consumer to be unable to close

### CODE REVIEW

**Review by codelipenghui — COMMENTED** [review]
Nice catch, could you please help add a unit test to cover this case to avoid regression?

**Comment by HugeSkull** [comment]
Of course, I have added the unit test, please take a look @codelipenghui

**Review by codelipenghui — APPROVED** [review]

**Review by 315157973 — APPROVED** [review]
Nice catch

**Comment by HugeSkull** [comment]
All checks have passed. Can this PR be merged?  @codelipenghui @315157973

**Pull request merged**
