### PR TITLE
Modify file system offload version to 2.5.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by congbobo184**
### Motivation
Modify file system version

### Verifying this change
Modify file system version

Does this pull request potentially affect one of the following parts:
If yes was chosen, please highlight the changes

Dependencies (does it add or upgrade a dependency): (no)
The public API: (no)
The schema: (no)
The default values of configurations: (no)
The wire protocol: (no)
The rest endpoints: (no)
The admin cli options: (no)
Anything that affects deployment: (no)

### Documentation
Does this pull request introduce a new feature? (yes / no)
If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
If a feature is not applicable for documentation, explain why?
If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by congbobo184** [comment]
run java8 tests

**Comment by ivankelly** [comment]
CI won't pass until #4667 is merged.

**Comment by congbobo184** [comment]
> run java8 tests

👍👍

**Pull request merged**
