### PR TITLE
[deployment] Update Kubernetes AWS (EKS) deployment

### PR DESCRIPTION
**Pull request by sde-melo**
### Motivation

We have encountered problems trying to use the current YAML files to deploy Pulsar to AWS EKS.
The cluster metadata initialization was missing, the monitoring tools were empty (Pulsar dashboard) or almost empty (Grafana).

### Modifications

We have updated the Grafana Docker image.  A newer version is now used (5.4.3 instead of 4.3.1), the configuration and dashboards have been modified accordingly, the topics dashboard has been fixed.
We have also modified the YAML files for the Kubernetes deployment to AWS, especially to make the monitoring work properly.  A newer version of Prometheus is now used (2.7.1 instead of 1.6.3).

### Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no
  - The rest endpoints: no
  - The admin cli options: no
  - Anything that affects deployment: **yes**
This pull request modifies the Grafana Docker image (upgrade) and the Kubernetes deployment to AWS EKS.

### Documentation

This pull request does not introduce any new feature but the existing documentation should be updated.

### CODE REVIEW

**Comment by sijie** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests
run integration tests

**Comment by sijie** [comment]
run cpp tests
run java8 tests

**Comment by sijie** [comment]
run cpp tests
run java8 tests

**Comment by tisonkun** [comment]
Closed as stale and conflicts. Also, The development of the Helm Chart has been permanently moved to https://github.com/apache/pulsar-helm-chart.

**Pull request closed without merging**
