### PR TITLE
[improve][broker] Add the MessageExpirer interface to make code clear

### PR DESCRIPTION
**Pull request by BewareMyPower**
### Motivation

When I reviewed https://github.com/apache/pulsar/pull/20597, the changes in `PersistentTopicsBase` are hard to read. The logic could be simplified to:

```java
PersistentSubscription sub = null;
PersistentReplicator repl = null;
if (metSomeCondition()) {
    repl = /* ... */;
    if (repl == null) {
        /* ... */
        return;
    }
} else {
    sub = /* ... */;
    if (repl == null) {
        /* ... */
        return;
    }
}
final PersistentSubscription finalSub = sub;
final PersistentReplicator finalRepl = repl;
future.thenAccept(__ -> {
    if (metSomeCondition()) {
        repl.expireMessages(/* ... */);
    } else {
        sub.expireMessages(/* ... */);
    }
});
```

The code above is bad. It adds two final variables because the lambda can only capture final variables. The `metSomeCondition` check is performed unnecessarily twice. The original code is more hard to read because the logic in `/* ... */` takes a few lines so that the two calls of `metSomeCondition()` are not near.

From the code search I see all these classes implement two `expireMessages` methods that accept an integer or a position.

- PersistentMessageExpiryMonitor
- PersistentSubscription
- PersistentReplicator
- NonPersistentSubscription

The code can be simplified to introduce a new interface.

### Modifications

Introduce a `MessageExpirer` interface and change the class hierarchy to:

```
// [I] is interface, [C] is class
[I] MessageExpirer
  [I] Subscription
    [C] PersistentSubscription
    [C] NonPersistentSubscription
  [C] PersistentReplicator
  [C] PersistentMessageExpiryMonitor
```

The method invocation can be simplified much as shown in this patch.

P.S. Inserting such an interface in the type hierarchy does not even break the ABI compatibility, see https://docs.oracle.com/javase/specs/jls/se7/html/jls-13.html

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [x] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by lifepuzzlefun** [comment]
@BewareMyPower 你好，我来澄清一下 你说到的代码问题，这个pr https://github.com/apache/pulsar/pull/20597 hard to read的原因是因为这里有一个bug，这个patch之前的代码是不允许用户调用admin api来重置offset的，不是一个『the unrelated changes』而且这里的代码风格是 从first init comment 提交的时候带过来的。
image
这个pr很棒，而且我觉得提高了代码的可读性，但是我觉得很容易对代码的reviewer产生对我本人后续patch的误会。maybe you can just tell people this is a refactoring pr but not with some insult words ok ?

**Comment by BewareMyPower** [comment]
Sorry I misunderstand the changes in your PR that they are not unrelated so I edited the PR description again.  https://github.com/apache/pulsar/pull/20597 not only fixes the NPE, **but also fixes the bug that `PersistentSubscription` will be queried from the `PersistentTopic` even if the subscription is a replicator subscription.** While the original PR description only mentioned:

> save PersistentTopic in PersistentMessageExpiryMonitor field.
>
> ensure when call expireMessages(Position messagePosition) only check topic LastPosition by topic. not null subscription.

It didn't mention why it needs to modify the `PersistentTopicsBase.java` in addition to the changes of the `PersistentMessageExpiryMonitor#topic` field and the `PersistentMessageExpiryMonitor#expireMessages` method.

P.S. I didn't blame the author (you) for that. I just pointed out the issue and why I misunderstood it. The reviewer should also be responsible to point out the missed description.

> but not with some insult words

@lifepuzzlefun I apologize if you thought my words insulted you. I only aimed at the code when I said "The code above is such a mess.", which I removed from the PR description now.

> 这里的代码风格是 从first init comment 提交的时候带过来的。

Yes you used a similar code style with the code in the first commit, but I think the original code is such a mess as well. Though I realized the words I used are not proper now.

**Comment by lifepuzzlefun** [comment]
@BewareMyPower OK, I think we are good now. I agree with your idea on the code style. As programmers, we all hate bad code. since the misunderstanding has been cleared up, I've hide my reply.

**Review by Technoboy- — APPROVED** [review]
LGTM

**Review by tisonkun — APPROVED** [review]
Thanks for your cleaning up.

**Review by lifepuzzlefun — APPROVED** [review]

**Pull request merged**
