### PR TITLE
[broker] add feature BrokerDeduplicationAcrossProducers

### PR DESCRIPTION
**Pull request by EugenDueck**
### Motivation

Deduplication of messages works per producer. But in the case of *redundant producers*, i.e. multiple producers that produce the same messages with the same sequence ids in an active/active setup, what is needed is deduplication across producers.

### Modifications

Added a configuration `brokerDeduplicationAcrossProducersEnabled` to `pulsar-broker-common/.../broker/ServiceConfiguration`, which, when set to true (default is false), will make deduplication work across producers, by ignoring which producers sent the messages. More specifically, instead of using the producerName as part of the key to store the last seen sequence id, a constant value `"__all"` gets used for all producers.

### Verifying this change

This change added unit tests and can be verified as follows:

- `testIsDuplicateAcrossProducers` (adapting the existing `testIsDuplicate`)
- `testIsDuplicateAcrossProducersWithFailure` (adapting the existing `testIsDuplicateWithFailure`)

### Documentation

This is a new feature that needs to be documented. I will do so as part of this PR after getting and if necessary incorporating feedback for this feature.

### CODE REVIEW

**Comment by EugenDueck** [comment]
@codelipenghui You are absolutely right, using this feature by itself will not make a lot of sense. It is part of a bigger feature, as discussed in [slack](https://apache-pulsar.slack.com/archives/C5ZSVEN4E/p1580084668018500).

When I asked whether to create a PIP for this, sijie said it may be best to just create PRs for the independent sub-features. Not sure if this is what he had in mind, as it will not be useful by itself.

(What would make this feature useful is if we required sequence ids to be increasing by one, i.e. without gaps, but details are out of scope for this sub-feature)

**Comment by sijie** [comment]
@codelipenghui @EugenDueck 

I think what @EugenDueck sent out can be used for seeding the idea for supporting deduplication across active-active producer setup. It is a good start.

I think one thing lacks here, we should still consider having the producer name available. The producer name can become a producer group name. If multiple producers are using same producer name, they are in the same group. Hence the de-duplication problem actually becomes de-duplication within the same producer group. It will preserve the meaning of "producer name" and be able to adopt use cases that @EugenDueck want to address.

**Comment by EugenDueck** [comment]
@sijie Yah, I did ponder that for a while, and I agree this looks useful. For that to work though, we would have to either
1) allow multiple producers with the same id to be connected at the same time (it seems that is what you are suggesting)
2) add a new "producerGroup" property as a per-producer configuration

Re 1) Can you confirm that this is not currently possible? If it is not, which is what was my assumption, then we may need to keep it that way for backwards compatibility (does a producer evict another producer with the same producer name? or will an existing producer prevent a second producer with the same name to connect?)

**Comment by sijie** [comment]
The current behavior for producers with the same producer name that only one producer is allowed to connect and the other producer will be rejected if there is already a producer with the same name connected to the broker. 

I was thinking of introducing a ProducerGroupType. By default, it is "exclusive". Only one producer connection is allowed for a producer name. That would be the current behavior.

Then we can introduce a "Shared" type. This allows multiple producer connections for a producer name. I am not sure it should be called "shared" or something else. But that's the type for allowing multiple producer connections. And you can implement the de-duplication logic across these producer connections. producer ids can be used for differentiating those producer connections. You can implement the de-duplication logic within a producer group.

**Comment by EugenDueck** [comment]
@sijie I think deduplication is currently configured at the namespace level (which I personally would have put at the topic level). Where would be put this *producer group type* setting?

**Comment by sijie** [comment]
> deduplication is currently configured at the namespace level

namespace policy is a way to configure topics. when it is configured at namesapce level, it applies to all the topics under that namespace.

@codelipenghui has been working on topic-level policy. After that is merged, you should be able to configure policies at topic level.

> Where would be put this producer group type setting?

Since all producers go to the owner broker, it can just be a setting at producer side. when a producer connects to the broker, it can carry the setting to broker. does it work?

**Comment by EugenDueck** [comment]
> Since all producers go to the owner broker, it can just be a setting at producer side. when a producer connects to the broker, it can carry the setting to broker. does it work?

In that case we need to consider what happens when 2 producers send different values for the group type.

Imagine there are multiple `active/active` producers with producer name _a_, and a producer with the `exclusive` setting and the same producer name _a_ comes in. Will it evict all the existing producers? Or will we prevent the late-coming `exclusive` producer?

**Comment by sijie** [comment]
IMO In that case, an "exclusive" producer should evict the active producers as the name indicates. once the “exclusive" producer occupies the ownership, the subsequent producers should be prevented.

**Comment by EugenDueck** [comment]
Sounds like a plan! I hope I'll be able to look into this in the next couple of days.

**Comment by merlimat** [comment]
I think there's more to be added to a producer group concept. eg: 

 * Having a failover-like scenario, where only 1 producer is active and the `client.createProducer()` hangs until a particular producer instance becomes active. 

This will allow for basic leader election support for applications.

**Comment by sijie** [comment]
+1 for fail-over

**Comment by EugenDueck** [comment]
>     * Having a failover-like scenario, where only 1 producer is active and the `client.createProducer()` hangs until a particular producer instance becomes active.

Makes sense. I guess you mean to say "until the currently active producer becomes inactive".

A waiting producer could continuously ring buffer the last couple of seconds worth of messages, and when it becomes active, it would flush that buffer, mostly leading to (deduplicatable) duplicates, but preventing a gap between where the failed producer left off and the new producer continues.

I'll continue working on active/active first though, which is useful in cases where a subset of the active producers may have occasional gaps, e.g. due to UDP packet loss, which would be filled by some other active producer.

**Comment by EugenDueck** [comment]
I've just committed a change that adds a _producer group mode_. I would like to know if that's along the lines of what @sijie and @merlimat where suggesting. If it is, I intend to 1) add more extensive unit tests  2) add documentation. I have not implemented the _failover mode_, but it is taken into account by means of the `GroupMode` enum, which currently has the values `Exclusive` and `Parallel` only, but which I created so it can be extended by a `FailOver` value in the future.

Btw I'm not totally happy by the use of the `IdentityHashSet`, but I haven't found any good discriminator so far that I can use in order to put multiple producers, which are currently considered identical (producerName + topic), into the same `Set`. I considered `cnx.clientAddress()`, but this does not work with tests at least - where the `clientAddress` would be the same for multiple producers - will look into that again. If you guys have any idea in the meantime, do let me know

**Comment by codelipenghui** [comment]
@EugenDueck 

Sorry, I missed the discussion in slack.  Agree with adding producer group, this looks more versatile. And we'd better consider adding a flag to enable deduplication based on the producer group name.  If the flag is false, producers in the same group also use name-based deduplication.

If the producer group added, I think the producer with the same name but the different group can connect to the broker. Hence, the group name also needs to consider adding to the unique identifier of the producer.

**Comment by EugenDueck** [comment]
@codelipenghui I've implemented it the way I believe @sijie suggested:

> The producer name can become a producer group name. If multiple producers are using same producer name, they are in the same group.

So I did not add a `producerGroupName` field. What I added is a producer group mode field. If the producer group mode is `Exclusive` (the default), everything stays as it was before: Only one producer with the same name can be connected at any one time. If however the group mode is `Parallel`, then multiple producers with the same `producerName` can connect at the same time.

So _group mode_ and _deduplication_ are orthogonal and we don't need another deduplication flag. In order to have deduplication across a producer group, all that needs to be done is

1. use the parallel producer group mode and
1. set the usual `brokerDeduplicationEnabled` to `true`.

**Comment by codelipenghui** [comment]
@EugenDueck I have understood the current implementation, just some minor suggestions. If we introduce a producer group, I think it needs a clear definition. If only use group type to indicate a producer group, it seems that a topic can only have a few groups at most(Equal to the number of types
of producer group). This is why I recommend adding producer group name here. I also think this is better understood by users.

If agree with the suggestion above, a topic may have multiple producer groups with different group types. So use a flag to indicate the duplication is based on producer name or producer group name is more flexible and understandable. 

Just some small suggestions, please point out any misunderstandings. If these are currently not necessary, we can ignore it first.

**Comment by EugenDueck** [comment]
@codelipenghui I think you are raising two points, which I'll address below. I'm pretty new to pulsar and its concepts, so maybe I'm not yet understanding the implications of all decisions. Let me just explain in detail how I currently see it, and I'll be happy for you or anyone to point out whatever it is that I'm missing.

1) how easy it is for users to understand

This is a valid point. Personally, I do not feel that the concept of a groupMode implies that you can only have one group per groupMode. However, there is potential for confusion around "producerName" meaning "name of the producer group". That is the disadvantage of repurposing the producerName as the producer group name. On the other hand, there is an advantage in terms of simplicity of implementation, which I think is one of the reasons sijie preferred to use the identity of the producerName, if I understand him correctly.

Adding a producer group name of course adds complexity in terms of implementation, but I think has also potential for confusion by users, because the possible/impossible combinations of producerName and producerGroupName would need to be documented (I guess it would be a hierarchy prodGroup/prod).

2) having multiple producer groups, each with their own deduplication settings

This is the way I currently see it: If we turn on deduplication for a topic, we have the same flexibility that we would get without producer group names:

1. If you want to deduplicate across a group of producers, give them the same producerName and set the groupMode to 'parallel'
1. for producers that don't want deduplication, use groupMode 'exclusive'
1. for failover producers use groupMode 'failover' ('failover' mode yet to be implemented)

And above groups can be freely mixed and matched within the same topic, which means you can have x parallel groups, y exclusive "groups", and z failover groups, all at the same time.

The only use case I can come up with that the current implementation cannot handle is this: One failover group that wants deduplication, while another group (failover or parallel) does not want deduplication on the same topic - or vice-a-versa.

But this should be orthogonal to the question of producerGroupName yes or no: It is a question of the granularity of the deduplication setting (currently at the namespace and broker level), which we could make more fine-grained up to the level of producer groups (although I wonder how many users would need that), regardless of whether we have a producerGroupName or if we use the producerName.

If there are any other use cases that I'm missing, I'd like to know.

So unless I'm missing a use case that is impossible with the current implementation and a finer graining of the dedupe setting in the future, I would prefer properly documenting the new groupMode feature (similar to the way subscription types aka subscription modes are documented), to adding complexity in terms of implementation, which I believe also needs documentation to avoid confusion.

**Comment by codelipenghui** [comment]
@EugenDueck I personally think that there are some disadvantages in using producer name to distinguish producers and producer groups. For users, if producers in a single group name are grouped producers, is this harder to understand than the grouped producer is a producer with the same name and producer type `Parallel`? I do not think so.

If a producer has a producer name, the workflow more like following steps:

1. Group some producers into a group(with same producer group name), but producer name is different
2. The client specifies the deduplication based on producer name or group name.
3. Broker side, if use producer name, this is the same as now. If we use the producer group name, we just need to use the `groupName/producerName` as the deduplication key. Of course, it needs to be turned on deduplication first at the broker side.

I don't know if this will cause other problems?

**Comment by EugenDueck** [comment]
@codelipenghui If we add producer group names, how do you envision creating and configuring these groups? On the fly when creating producers, or with a new API for producer groups?

**Comment by codelipenghui** [comment]
@EugenDueck Your understanding is correct. I think the two solutions are very similar. I am also inspired by the producer group that @sijie introduced. The difference is just how to make the producers a group(1. same producer name and group type 2. same producer group name).  

> 4. the failover group property would similarly be set on the producer group
> 5. we don't need the concept of "exclusive producer group"s, as exclusivity can be achieved through the producer name, just as has been done before this PR

I haven't fully figured out what the producer group type does, from the above description, it looks just indicate the producer groups.

**Comment by EugenDueck** [comment]
@codelipenghui Not sure I fully understand your question/statement, but the _producer group type_ would have the same function as with my current solution, with the exception that we don't need an `Exclusive` value.

So the _producer group type_ would have two possible values:

1. `Parallel`, which is the default mode where multiple producers with the same `producerGroupName` (but different `producerName`s) can be connected to a broker at the same time and produce concurrently
1. 'Failover', which is the mode merlimat suggested above.

One question is how we configure _producer groups_ - will we do it "on the fly" using the `ProducerBuilder`? In that case, what happens if two producers are created with the same `producerGroupName`, but different _producer group types_? As long as a producer group is alive, I would suggest rejecting attempts to connect with a different _producer group type_. Or were you thinking of adding a new API or configuration for creating and managing producer groups? (This sounds like more complexity)

**Comment by codelipenghui** [comment]
@EugenDueck 
> One question remains, which is how we configure producer groups - will we do it "on the fly" using the ProducerBuilder? In that case, what happens if two producers are created with the same producerGroupName, but different producer group types or deduplication flags?

The broker just needs to check the deduplication is based on producer name or producer group name. 
The deduplication flags are not for producer groups, it's for producers.  If use group name as the deduplication key, the key is group name. If use group name as the deduplication key, the key is groupName/producerName. 

For producer group type, I think if the type is Exclusive, only can have one producer in this group, others will be rejected. If the type is Failover, only have one active producer, others are standby. If the type is Shared or Parallel, all producers can connect to the broker. Seem very similar to the consumer side. I'm not sure am I understand correctly. @merlimat @sijie @jiazhai

**Comment by sijie** [comment]
@EugenDueck @codelipenghui 

I think you are on the same page. the only question here is - are we using "producer name" for identifying the group of producers (what I originally suggested and what @EugenDueck implemented) or introducing a new field "producer group name" in both producer builder and as well as in the wire protocol for identifying the group of producers (what @codelipenghui suggested).

I don't have any strong preferences about either approach. just from an operation perspective, if we re-use "producer name" for identifying the group,  does it affect stats returned by `topic stats` (question to @codelipenghui). If it is affecting stats, we might just consider adding another field "producer group name" for identifying the group.

for @EugenDueck, I don't think you need to re-do your current work if we need to add another field for identifying producer group.

**Comment by codelipenghui** [comment]
> if we re-use "producer name" for identifying the group, does it affect stats returned by topic stats

@sijie Yes, the producer name is returned in PublisherStats, if use `producer name` for identifying the group, we also need an extra attribute(IP? or others). If added `producer group name` for identifying the group, we can format the producer name as `group-name/producer-name`. If the producer group name is absent, keep up with the current.

**Comment by EugenDueck** [comment]
@sijie @codelipenghui So in order to combine the two approaches into one, I could

1. add a producerGroupName field to producers
1. add a flag to producers which controls whether producerName or producerGroupName should be used for deduplication
1. remove the possibility for multiple producers with the same producerName to connect at the same time

(3. is something I added but which I think we don't need any more if we have a producerGroupName)

Is that in line of what you guys are thinking?

**Comment by codelipenghui** [comment]
@EugenDueck

Thanks for sum up, 
for 3 if I understand correctly we just added group name for the producer, the producer name still keeps unique right? so that we don't need to do anything about the producer identifier, still the same as now. I think it is ok.

**Comment by EugenDueck** [comment]
@codelipenghui If by "now" you mean what is in master, then yes. I meant to say I need to remove it from my changes that I have made for this PR.

**Comment by codelipenghui** [comment]
@EugenDueck Yes, you are right

**Comment by sijie** [comment]
> add a flag to producers which controls whether producerName or producerGroupName should be used for deduplication

Do we need an extra flag? Can we just reply on whether `producerGroupName` is set or not? If `producerGroupName` is set, deduplicated using group name; otherwise using `producer name`.

**Comment by EugenDueck** [comment]
@sijie Imagine we have an exclusive (or failover) producer group. If we have a separate flag, we can support both of the follwing cases:
- sequence id of producers are shared
- producers use unrelated sequence ids

**Comment by sijie** [comment]
@EugenDueck 

> Producers use unrelated sequence ids

For this case, why not just have producers using different producer groups?

**Comment by EugenDueck** [comment]
@sijie That would be possible In the exclusive case, but in the failover case, they would lose the failover feature if they used different groups.

**Comment by sijie** [comment]
> but in the failover case, they would lose the failover feature if they used different groups.

In the failover feature, you can have the producers in the same group by different producer names, no?

`group name` is an extension to `producer name`. the `group name` can be used for grouping producers together. If `group name` is not set, the `producer name` can be used as a distinct name. Are we on the same page about this part?

**Comment by EugenDueck** [comment]
So this is how I currently understand it, after discussing with codelipenghui:
- the producer name must be unique, regardless of the producer group name
- if you want to have only one producer out of a set of producers connected at the same time (the failover case), you can use the same producer group name (but different producer names) with `failover` group mode, and all those producers may try to connect at the same time, but only one producer will get the "lease" at any one time, and all others will block

So there can be multiple producers with different names in the same producer group, however, they cannot be connected at the same time.

I'm not sure if you are thinking to use the producer group name in the same way.

**Comment by sijie** [comment]
@EugenDueck 

> So there can be multiple producers with different names in the same producer group, however, they cannot be connected at the same time. 

Yes that's what I am thinking for the "failover" mode.

**Comment by sijie** [comment]
I guess we are on the same page then.

**Comment by EugenDueck** [comment]
You still want to do without the `groupDeduplication` flag? If we do not have such a flag, then it would mean that failover producers that share a group would also share the deduplication key, i.e. the producer group name.

**Comment by sijie** [comment]
>  If we do not have such a flag, then it would mean that failover producers that share a group would also share the deduplication key,

They are supposed to share same de-duplication key, no?

**Comment by EugenDueck** [comment]
There is a use case where there are two producers that cannot deterministically produce the same sequence ids, although the messages are the same. So only one should be allowed to produce, and when it fails, failover to the other will occur. But after the failover, we don't want to continue deduplicating using the last sequence id of the previous producer.
Of course during failover we may have a message gap or duplicates, but there's nothing we can do about it. But as long as a producer is alive, there will be no duplicates, even in the face of broker / bookie failures. (I'm assuming here that one of the reasons for Pulsar offering deduplication is that in case of such failures duplicates may occur)

**Comment by EugenDueck** [comment]
@sijie @codelipenghui In terms of implementation, it would actually be simpler to allow multiple producers with the same name, if they have different producer groups.

Otherwise, if we have producerGroups and unique producerNames across all groups, we need to have two hash maps (producers, and producerGroups), and we would need to coordinate access to both (e.g. via locking), two prevent concurrent calls to e.g. Topic.add(producer) from getting them out of sync.

So unless there are objections, I'd like to change the uniqueness of producers from "producerName only" to "groupName and producerName".

**Comment by sijie** [comment]
SGTM

**Comment by EugenDueck** [comment]
I just realized that with a `producerGroup` field, we don't need the _exclusive_ group mode any more, so what remains are _parallel_ (the default) and _failover_. In _parallel_ mode, multiple producers can connect to the same group if their `producerName`s are different. This is the same behavior as before this PR.

As I'm not implementing failover mode with this PR, I'll remove the `groupMode` for now, as it can be introduced if and when failover mode gets implemented.

**Comment by EugenDueck** [comment]
@sijie @codelipenghui What is the use case for generated producer names? I'm just wondering if users should or should not be forced to specify a `producerName` when they specify a  `groupName` - your thoughts?

**Comment by codelipenghui** [comment]
@EugenDueck I think users should not be forced to specify a `producerName` when they specify a `groupName`.

**Comment by EugenDueck** [comment]
@codelipenghui Your https://github.com/apache/pulsar/pull/6326 makes sure that definite non-dupes are split from dupes/potential dupes in pulsar-client. Now when we have multiple producers, all messages need to be considered potential dupes, from the point of view of the pulsar clients that talk to broker. I'm still have to fully understand the broker side code, but do you as the dedupe expert have an opinion about what to do with message batching for this feature?

**Comment by codelipenghui** [comment]
@EugenDueck Sorry for the late response. Multiple producer deduplication looks a little complicated.  I think the highest sequence ID maintained in the broker is insufficient to meet such a demand. Maybe we can use the same mechanism of acknowledging the state of the message. The broker maintains a bitset in memory for the not continuous sequence and a mark sequence ID for the continuous sequence that producers sent to the topic. The producers may cause discontinuities(0, 2, 3, 1, 5) and no longer send 5. So that we can add a time window and if the time window passed, sequence ID 4 will no longer be stored. And this also needs this PR.

**Comment by tisonkun** [comment]
Closed as stale and conflict. Please rebase and resubmit the patch if it's still relevant.

**Pull request closed without merging**
