### PR TITLE
Added support for Snappy compression for Python/Go

### PR DESCRIPTION
**Pull request by murong00**
### Motivation

As discussed in #4259, this PR try to support Snappy compression (https://google.github.io/snappy/) for Python/Go.

### CODE REVIEW

**Comment by murong00** [comment]
run cpp tests

**Comment by sijie** [comment]
run cpp tests
run java8 tests

**Comment by murong00** [comment]
@merlimat @sijie The cpp test `test_producer_consumer_snappy` failed due to `Segmentation fault`, it seems that snappy lib was not found since `HAS_SNAPPY=0`. I'm not familiar with jenkins test, can you give me some clues? thanks!

**Comment by merlimat** [comment]
We should have a graceful fallback if C++ lib is not compiled with Snappy, returning an error when we try to create a producer.

**Comment by sijie** [comment]
@murong00 can you merge to latest master to include a pip fix in integration test?

**Comment by murong00** [comment]
run integration tests

**Pull request merged**
