### PR TITLE
[fix][flaky-test]CompactedTopicTest.testReadCompleteMessagesDuringTopicUnloading

### PR DESCRIPTION
**Pull request by poorbarcode**
### Motivation

截屏2022-08-30 18 29 31

Task "Clear the ledger that has been consumed" will be triggered by `mark delete event` and `retention policy`.

<strong>(High light)</strong>  Because there is no durable cursor(`__compaction` already acknowledged), the ledger will be removed by the asynchronous `clean-ledger-task`, even if the reader is still reading

https://github.com/apache/pulsar/blob/d4beae72d608bafaebe7ac1cff0a258238e84f10/pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactedTopicTest.java#L754-L778

----
The error execution flow is as follows: 

producer: 
- send 1000 messages ( ledger-1 )
-  unload the topic.
- send 1000 messages (ledger-2)

reader:
- read 500 messages
- auto acknowledgment
- calculate the next read position: 
  - `getNextValidPosition(position)` At this time the ledger-1 has been deleted, so `getNextValidPosition(position)` will return `(originalLedger+1:0)`
- read `(ledger-2:0)`, then error occur

### Modifications

- Create a consumer to generate a durable cursor, to avoid deleting the ledger before the reader receives.
- Make the reader creates before calling `triggerCompaction`

### Documentation

- [ ] `doc-required` 
  
- [x] `doc-not-needed` 

- [ ] `doc` 

- [ ] `doc-complete`

### CODE REVIEW

**Comment by poorbarcode** [comment]
rebase master

**Review by codelipenghui — APPROVED** [review]

**Review by lhotari — APPROVED** [review]

**Comment by lhotari** [comment]
Thank you @poorbarcode

**Pull request merged**
