### PR TITLE
doc: en to zh-cn

### PR DESCRIPTION
**Pull request by AdamTyn**
pageId: sql-getting-started
English to Chinese

### CODE REVIEW

**Review by Anonymitaet — CHANGES_REQUESTED** [review]
Pulsar localization work is processed in Crowdin rather than here. @tuhaihe can you give some instructions to @AdamTyn? Thanks!

**Comment by Anonymitaet** [comment]
cc @momo-jun @DaveDuggins @D-2-Ed

**Comment by tuhaihe** [comment]
@AdamTyn Hi, welcome to contribute your Chinese document translation in [Crowdin](https://crowdin.com/project/apache-pulsar/zh-CN). You can take [this document](https://github.com/apache/pulsar-translation) as a reference.

**Comment by tuhaihe** [comment]
This PR can be closed now.

**Pull request closed without merging**
