### PR TITLE
[fix][client] Make DeadLetterPolicy & KeySharedPolicy serializable

### LINKED ISSUE #23704: [Bug] deadLetterPolicy attribute in the ConsumerConfigurationData class marked as transient
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

All Java clients of version v2.8.0 and above

### Minimal reproduce step

Create an instance of `ConsumerConfigurationData` class and set a `deadLetterPolicy` on it. Serialize it and de-serialize it back to get a new instance of the same. The `deadLetterPolicy` previously set will not be present after deserialization.

### What did you expect to see?

Ideally the `deadLetterPolicy` should have been preserved through serialization-deserialization.

### What did you see instead?

null

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by AnuragReddy2000**
Fixes #23704 

### Motivation

We use the pulsar client to consume messages from a Pulsar broker in a Storm topology. Recently, we encountered an issue where the `deadLetterPolicy` that we set on the `PulsarSpout` seems to be lost when the topology is started. Upon investigation, we found that this is due to the `deadLetterPolicy` attribute in `ConsumerConfigurationData` being marked as transient. This prevents us from utilising the dead letter queue feature in our topology.

### Modifications

Made DeadLetterPolicy, KeySharedPolicy and Range classes implement the java.io.Serializable interface and removed the transient keyword from the corresponding fields in the ConsumerConfigurationData class. In addition, two tests were also modified / updated.

### Verifying this change

- [X] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:
- Extended existing unit test for the ConsumerConfigurationData class to validate the retention of deadLetterPolicy through serialization & deserialization. 

### Does this pull request potentially affect one of the following parts:

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [X] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/AnuragReddy2000/pulsar/pull/1

### CODE REVIEW

**Comment by dao-jun** [comment]
oh, that is a unconventional use case I've been never seen. @lhotari Do you think is this change makes sense?

**Review by lhotari — APPROVED** [review]
LGTM, good work @AnuragReddy2000

**Comment by AnuragReddy2000** [comment]
@lhotari A test is failing on this PR which did not fail on the PR that raised in my fork. I checked the test, I'm not sure how my changes may cause it to fail. What do you suggest I do here?

**Comment by lhotari** [comment]
> @lhotari A test is failing on this PR which did not fail on the PR that raised in my fork. I checked the test, I'm not sure how my changes may cause it to fail. What do you suggest I do here?

@AnuragReddy2000 there are quite a few flaky tests. Reporting ones that haven't already been reported and retrying is the way to handle it.

**Pull request merged**
