### PR TITLE
[python client] set protobuf version to be larger than 3.6.0

### LINKED ISSUE #3686: python bookkeeper client defective for python2 in mac
**Describe the bug**
Importing bookkeeper.admin module fails on a mac running python2
**To Reproduce**
Mac running Mojave and python2.
make sure to have python-client 2.3.0.post1 installed.
try doing
import bookkeeper.admin

it fails with 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sanjeevkulkarni/Library/Python/2.7/lib/python/site-packages/bookkeeper/admin/__init__.py", line 15, in <module>
    from bookkeeper.admin.client import Client
  File "/Users/sanjeevkulkarni/Library/Python/2.7/lib/python/site-packages/bookkeeper/admin/client.py", line 20, in <module>
    from bookkeeper import types
  File "/Users/sanjeevkulkarni/Library/Python/2.7/lib/python/site-packages/bookkeeper/types.py", line 22, in <module>
    from bookkeeper.proto import common_pb2
  File "/Users/sanjeevkulkarni/Library/Python/2.7/lib/python/site-packages/bookkeeper/proto/common_pb2.py", line 22, in <module>
    serialized_pb=_b('\n\x0c\x63ommon.proto\x12\x17\x62ookkeeper.proto.common\"*\n\x08\x45ndpoint\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x42-\n)org.apache.bookkeeper.stream.proto.commonP\x01\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'serialized_options'

**Expected behavior**
the import should work
**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by sijie**
*Motivation*

Fixes #3686

### CODE REVIEW

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by srkukarni** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by jerrypeng** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run cpp tests

**Comment by merlimat** [comment]
Merged in 2.3.1 at 
18aa430

**Pull request merged**
