### PR TITLE
[pulsar-broker] Fix some comment typos

### PR DESCRIPTION
**Pull request by zhenglaizhang**
Fix some comment typos in the pulsar-broker module, no real code changes.

### CODE REVIEW

**Comment by zhenglaizhang** [comment]
@sijie this pr hasn't been assigned and merged, are there any other actions i need to take? thx

**Comment by codelipenghui** [comment]
retest this please

**Comment by codelipenghui** [comment]
@zhenglaizhang No other actions you need take, after the required CI passed, this PR will be merged.

**Comment by tuteng** [comment]
run java8 tests
run cpp tests

**Comment by sijie** [comment]
run java8 tests

**Comment by zhenglaizhang** [comment]
It looks like some tests are not stable?

**Comment by sijie** [comment]
@zhenglaizhang there are some flaky tests and the jenkins environment is also having issues.

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Pull request merged**
