### PR TITLE
[improve][doc] Clarify the usage of `destination-topic-name` for Debezium connector and fix incorrect REST API links

### PR DESCRIPTION
**Pull request by momo-jun**
### Modifications

1. Add a note for `destination-topic-name` to clarify the usage and workaround. Note that the note needs to be removed as soon as #15667  is resolved.
image

2. Fix incorrect REST API links in 2.10.x. Related PR: #16267; Related issue: #14928 
3. Other minor fixes.

### Documentation
  
- [x] `doc`

### CODE REVIEW

**Comment by momo-jun** [comment]
Ping @freeznet and @Huanli-Meng to review item#1.

**Review by Huanli-Meng — APPROVED** [review]
LGTM

**Review by freeznet — APPROVED** [review]

**Comment by Huanli-Meng** [comment]
@momo-jun could you help resolve the conflicts? Then, we can merge the PR. Thanks.

**Comment by momo-jun** [comment]
@Anonymitaet this PR contains the fix to address the remaining anchoring issues of REST API links.

**Comment by momo-jun** [comment]
> @momo-jun could you help resolve the conflicts? Then, we can merge the PR. Thanks.

Resolved. Thank you.

**Pull request merged**
