### PR TITLE
[CLI] Add support for setting time based limit on backlog quota with CLI.

### LINKED ISSUE #9680: Backlog quota: allow time-based quota
Retention policies can be set based on size or time limit (or both), while backlog quotas can only be based on size. The recommendations I've gotten are to set backlog quota to be equal to or less than the retention policy, but if the retention policy is based solely on time, the backlog quota cannot be certain to be less than the retention policy.

### PR DESCRIPTION
**Pull request by MarvinCai**
Fixes #9680

This change added tests and can be verified as follows:

Added unit test.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): no
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no
  - The rest endpoints: no
  - The admin cli options: yes
  - Anything that affects deployment: no

### Documentation

  - Does this pull request introduce a new feature? yes
  - If yes, how is the feature documented? docs 
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by 315157973 — COMMENTED** [review]
Does this configuration also take effect at the broker level? I can't find configuration `backlogQuotaDefaultLimitSecond` in broker.conf

**Comment by MarvinCai** [comment]
> Does this configuration also take effect at the broker level? I can't find configuration `backlogQuotaDefaultLimitSecond` in broker.conf

Probably need to pull latest mainline, the broker size change should be merged via this pr: https://github.com/apache/pulsar/pull/10093

**Comment by 315157973** [comment]
> > Does this configuration also take effect at the broker level? I can't find configuration `backlogQuotaDefaultLimitSecond` in broker.conf
> 
> Probably need to pull latest mainline, the broker side change should be merged via this pr: #10093

In this PR, broker.conf does not include this option as well. Should we add it?

**Comment by MarvinCai** [comment]
@315157973 
Yes it's a broker config, added to broker.conf and standalone.conf
PTAL

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
