### PR TITLE
Specify the path of the *website* folder for clarity

### PR DESCRIPTION
**Pull request by Anonymitaet**

### CODE REVIEW

**Comment by Anonymitaet** [comment]
run cpp tests
run java8 tests
run integration tests

**Comment by Anonymitaet** [comment]
run java8 tests
run integration tests

**Comment by Anonymitaet** [comment]
@sijie @Jennifer88huang could you please help review?

**Comment by sijie** [comment]
run java8 tests

**Comment by Anonymitaet** [comment]
run java8 tests

**Comment by Anonymitaet** [comment]
run java8 tests

**Pull request merged**
