### PR TITLE
[fix][broker]Sync topicPublishRateLimiter update

### PR DESCRIPTION
**Pull request by AnonHxy**
### Motivation

* Synchronized `topicPublishRateLimiter` update action to prevent resource leakages:

  * Thread1:  `topicPublishRateLimiter ` is null,  and and it will not invoke `close` in line:1216. Then it stop before line:1219
  * Thread2:  set `topicPublishRateLimiter` a new value, for example, `limiter2`. Then thread2 stop.
  * Thread1:  set `topicPublishRateLimiter ` as `PublishRateLimiter.DISABLED_RATE_LIMITER` at line:1219
  * `limter2` will never be accessable, and may cause resource leakages.

https://github.com/apache/pulsar/blob/eee038870db95e009abde32e89b9d736a9e9cd1c/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java#L1213-L1222

### Modifications

Sync `updatePublishDispatcher()'

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

- [x] `no-need-doc` 
(Please explain why)

### CODE REVIEW

**Comment by Shawyeok** [comment]
> Thread1: topicPublishRateLimiter is null, and and it will not invoke close in line:1216. Then it stop before line:1219
Thread2: set topicPublishRateLimiter a new value, for example, limiter2. Then thread2 stop.
Thread1: set topicPublishRateLimiter as PublishRateLimiter.DISABLED_RATE_LIMITER at line:1219
limter2 will never be accessable, and may cause resource leakages.

In scenario above, `limiter2` could be garbage collected, correct me if I miss something.

**Comment by AnonHxy** [comment]
> 

I don't think so.  In `close` method, it will close the `RateLimiter`, and the `RalteLimter#close` may shutdown executorService or cancel tasks to release some resources. @Shawyeok

**Comment by Shawyeok** [comment]
Ah, you are right, I missed preciseTopicPublishRateLimitingEnable=true branch which will create a `PrecisPublishLimiter`.

After `org.apache.pulsar.common.util.RateLimiter#createTask` was called, it is reachable from GC Roots.

**Comment by AnonHxy** [comment]
https://github.com/apache/pulsar/pull/15599 solve the same problem , so  close this PR

**Pull request closed without merging**
