### PR TITLE
Fixing Debezium integration tests

### LINKED ISSUE #11099: PulsarDebeziumSourcesTest does not run on CI
**Describe the bug**

AFAICT PulsarDebeziumSourcesTest does not run on CI currently.

**To Reproduce**

Check CI logs.

**Expected behavior**

Test suite runs on CI

**Additional context**

There were refactorings of tests that created tests/integration/target/test-classes/pulsar-io-[suite|sinks|sources].xml (PulsarDebeziumSourcesTest moved to pulsar-io-sources.xml, included into pulsar-io-suite.xml) and refactoring/optimization of CI that created build/run_integration_group.sh and PulsarDebeziumSourcesTest fell through the cracks there (new xml files/suites not referred to in the run_integration_group.sh).

### PR DESCRIPTION
**Pull request by dlg99**
Fixes #11099 

### Motivation

Integration test for debezium connector to tun on CI

### Modifications

Debezium integration test for postgres:  added check for flush lsn updates

Added pulsar-io tests to the CI

### Verifying this change

Ran locally:
```
mvn package -DintegrationTests -f tests/docker-images/pom.xml

mvn test -f tests/pom.xml test -DintegrationTestSuiteFile=pulsar-io-sources.xml -DintegrationTests -Dtest=org.apache.pulsar.tests.integration.io.sources.debezium.PulsarDebeziumSourcesTest
```

- [ ] Make sure that the change passes the CI checks.

This change fixes existing tests.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

NO

### Documentation

  - Does this pull request introduce a new feature? NO

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
Very good.

@lhotari @codelipenghui @congbobo184 @sijie PTAL

**Review by lhotari — APPROVED** [review]
Good work @dlg99 ! 

I was wondering how the tests weren't run in CI. I tracked it back to #10140 when tests were refactored. We missed the CI part for Pulsar IO in that PR. Thanks for fixing it as part of this PR.

**Comment by dlg99** [comment]
Pulsar IO integration test failed after rebase, likely the same reason as https://github.com/apache/pulsar/pull/11204#issuecomment-875296663

**Comment by dlg99** [comment]
I confirmed that tests pass after revert of PIP-85; @nlu90 is looking at the options to fix this without revert.

**Comment by eolivelli** [comment]
Failed test
testDebeziumMongoDbSource(org.apache.pulsar.tests.integration.io.sources.debezium.PulsarDebeziumSourcesTest)  Time elapsed: 33.666 s  <<< FAILURE!
java.lang.AssertionError: expected [1] but found [0]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals

**Comment by dlg99** [comment]
@nlu90 @eolivelli situation with this PR so far:
I rebased it on latest master and "CI - Integration - Pulsar-IO Sinks and Sources" failed.
Running testDebeziumMySqlSourceJson locally I can repro failures, rootcause TBD but the only suspicious thing that I see in the function log is
```
[pulsar-client-io-1-2] ERROR org.apache.pulsar.io.kafka.connect.AbstractKafkaConnectSource - Timed out waiting to flush org.apache.pulsar.io.kafka.connect.KafkaConnectSource$KafkaSourceRecord@72495bb1 offsets to storage
```

I reverted both PRs https://github.com/apache/pulsar/pull/11251 and https://github.com/apache/pulsar/pull/11056 locally; rebuilt/re-run the test and the test passed, "Timed out waiting to flush" is not logged in the function log

**Comment by dlg99** [comment]
tests do pass if I create a new pulsar client in the PulsarOffsetBackingStore's ctor instead of the one passed there (I hardcoded the url in the test).

There is still something fishy with passing the client via source context and, ironically, I am missing on a context of what's going on there.  Feels like some kind of deadlock at the PulsarOffsetStore.set() where it does `producer.flushAsync()`.

I suggest we merge this PR, and @nlu90 continues work on the client in the SourceContext with the test enabled on the CI.

**Comment by nlu90** [comment]
@dlg99 Let me know when you merge this PR, I will continue look into the fix.

**Comment by dlg99** [comment]
@nlu90 I don't have permissions to merge; I hope @codelipenghui / @sijie / @merlimat / @eolivelli or other committer can merge.

**Comment by eolivelli** [comment]
@nlu90  are you "approving" this patch ?

**Comment by eolivelli** [comment]
I am fine to merge this patch as soon as CI is green

**Comment by dlg99** [comment]
@eolivelli 
> I am fine to merge this patch as soon as CI is green

I don't know what's going on with "CI - Unit - Brokers - Broker Group 1 / unit-tests" but it is not related.
"CI - Integration - Pulsar-IO Sinks and Sources" won't be green unless the problem with debezium/pulsar client in the source context is fixed. 
The point of merging this to enable integration tests on the PR and break the circular dependency where @nlu90 does the fixes but I detect the problems by rebasing this PR.

**Comment by sijie** [comment]
I think the agreement is to let Neng work on a proper fix based on Andrey's PR.

**Comment by nlu90** [comment]
I pushed a fix for the debezium connector in #11435 

And the integration test passed on my local laptop:
➜  sn-pulsar git:(neng/kafka-source-async-ack) ✗ mvn test -f tests/pom.xml test -DintegrationTestSuiteFile=pulsar-io-sources.xml -DintegrationTests -Dtest=org.apache.pulsar.tests.integration.io.sources.debezium.PulsarDebeziumSourcesTest

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache Pulsar :: Tests 2.9.0-SNAPSHOT:
[INFO]
[INFO] Apache Pulsar :: Tests ............................. SUCCESS [  1.147 s]
[INFO] Apache Pulsar :: Tests :: Integration .............. SUCCESS [06:12 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:13 min
[INFO] Finished at: 2021-07-23T11:05:54-07:00
[INFO] ------------------------------------------------------------------------
```

**Comment by dlg99** [comment]
@nlu90 I rebased the PR on top of recent master, the IO tests still failed. 
The error looks different:

```
2021-07-23 21:25:17,576 - INFO  - [docker-java-stream-1663661242:DockerUtils$2@211] - DOCKER.exec(PulsarDebeziumSourcesTest-abzgk-pulsar-functions-worker-process-chgkv-1:/pulsar/bin/pulsar-admin source delete --tenant public --namespace default --name test-source-debezium-mysqlavro-PROCESS-mlijfzbu): Executing...
2021-07-23 21:25:21,122 - INFO  - [docker-java-stream-2004020930:DockerUtils$4@347] - DOCKER.exec(PulsarDebeziumSourcesTest-abzgk-pulsar-broker-0:tail -f /var/log/pulsar/broker.log): STDOUT: 21:25:21.000 [pulsar-web-40-6] INFO  org.eclipse.jetty.server.RequestLog - 172.21.0.9 - - [23/Jul/2021:21:25:20 +0000] "GET /admin/v2/persistent/public/functions/coordinate/stats?getPreciseBacklog=false&subscriptionBacklogSize=false HTTP/1.1" 200 2476 "-" "Pulsar-Java-v2.9.0-SNAPSHOT" 8
21:25:21.034 [pulsar-web-40-1] INFO  org.eclipse.jetty.server.RequestLog - 172.21.0.9 - - [23/Jul/2021:21:25:21 +0000] "GET /admin/v2/persistent/public/functions/coordinate/stats?getPreciseBacklog=false&subscriptionBacklogSize=false HTTP/1.1" 200 2476 "-" "Pulsar-Java-v2.9.0-SNAPSHOT" 16
./build/retry.sh: line 26: 31272 Killed                  "$@"
The command has failed after 3 attempts.
```

**Comment by dlg99** [comment]
Excluded tests for sinks; something times out there, "Pulsar-IO Sinks and Sources" is limited to sources now (but passes)

**Review by sijie — APPROVED** [review]

**Pull request merged**
