### PR TITLE
Allow to automatically assign TCP ports when starting a broker

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Allow to configure the broker listen ports with 0 for (broker, broker+tls, http, https) in order to have ports automatically assigned by the OS. 

This will be primarily used in tests to avoid port conflicts.

### CODE REVIEW

**Comment by aahmed-se** [comment]
@merlimat can you rebase this.

**Comment by merlimat** [comment]
@sijie Binding on 0 is a common property of servers since it's supported by the OS. I don't think we need to have an extra flag to enable that since it's an explicit configuration setting that the user has to set.

**Comment by sijie** [comment]
@merlimat my point is to prevent mistakes like what we did in bookkeeper. 0 is only useful in tests, but it is actually harmful in production. we should provide a flag to prevent mistakes.

**Comment by merlimat** [comment]
> my point is to prevent mistakes like what we did in bookkeeper. 0 is only useful in tests, but it is actually harmful in production. we should provide a flag to prevent mistakes.

I think it's much more misleading to require a separate flag. Every server software out there will work if you put port 0 without any additional configuration.

>  0 is only useful in tests, but it is actually harmful in production. we should provide a flag to prevent mistakes.

You would have to put 0 directly in the config file. I don't see what can be unexpected or harmful.
Having port 0 to dynamically allocate a port is not our made up convention, it's the common behavior for unix.

**Comment by sijie** [comment]
@merlimat I understand port 0 is for dynamical port allocation, which is a common standard. What I am trying to point out is what is being used in bookkeeper to have a safe guard to prevent any unknowns in using port 0 in production. 

Anyway, I don't feel strong about this. please go ahead.

**Comment by merlimat** [comment]
> I understand port 0 is for dynamical port allocation, which is a common standard. What I am trying to point out is what is being used in bookkeeper to have a safe guard to prevent any unknowns in using port 0 in production.

I knew about the BK flag, though I'm trying to not add more flags unless necessary.

The other consideration is that currently it's already allows to bind on port 0 although things will not work correctly. 

This PR just adds: 
 * Advertise the effective port
 * Added method to retrieve the port used

**Pull request merged**
