### PR TITLE
Revert "[pulsar-client-java] retry when getPartitionedTopicMetadata failed

### PR DESCRIPTION
**Pull request by wolfstudy**
## Motivation

Revert the #5603 from `branch-2.4`. 

This pr does not seem to be merged to `branch-2.4`,  because `getDefaultBackoffIntervalNanos`, `useUserConfiguredIntervals` is not defined in `branch-2.4`.

### CODE REVIEW

**Comment by sijie** [comment]
@wolfstudy thank you for point this out.

Can you also send out a pull request to apply #5603 to master?

**Comment by wolfstudy** [comment]
> Can you also send out a pull request to apply #5603 to master?

Sure

**Comment by sijie** [comment]
run cpp tests
run integration tests

**Comment by wolfstudy** [comment]
run cpp tests

**Comment by wolfstudy** [comment]
run cpp tests

**Comment by sijie** [comment]
I don't think we are able to pass the c++ test because of the way how the tests setup. The tests don't run well on branches. If this is a revert change, we can just merge it. We should figure out a robust plan to test branches.

**Comment by wolfstudy** [comment]
> I don't think we are able to pass the c++ test because of the way how the tests setup. The tests don't run well on branches. If this is a revert change, we can just merge it. We should figure out a robust plan to test branches.

Thanks sijie, i will merge this pull request and open issue track the test in branch.

**Pull request merged**
