### PR TITLE
[refactor] Remove docs from the main repo

### PR DESCRIPTION
**Pull request by tisonkun**
This closes https://github.com/apache/pulsar/issues/19092.

Mailing list resolution: https://lists.apache.org/thread/89wl112cflvtoyfg3l7kglr1dozsljm9

All pending PRs updating `site2` content should be resubmitted. I'm trying to merge them if acceptable now.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by Anonymitaet** [comment]
Hi @tisonkun thanks for your work! 

I have several questions, can you take a look? Thank you!

After this PR gets merged,

1. Will the `documentation bot` (used to label PR with doc-related labels) be implemented in `pulsar-site` and removed in `pulsar`?

2. Will the sync workflow (sync docs from `pulsar` to `pulsar-site`) be removed?

3. Will the doc-related issues still be recorded in `pulsar`?

**Comment by tisonkun** [comment]
> Will the documentation bot (used to label PR with doc-related labels) be implemented in pulsar-site and removed in pulsar?

No. At least not yet. There are still PRs in `apache/pulsar` touch docs other than `site2`. Said other markdown files or inline comments. 

But yes, we can install the documentation bot in `apache/pulsar-site` if necessary. Although we may at first try to regard all changes in the site repo is about "doc".

> Will the sync workflow (sync docs from pulsar to pulsar-site) be removed?

See https://github.com/apache/pulsar-site/pull/348. We may still generate CLI references and swagger docs from main repo periodically. But since the docs content gets removed, we don't sync them (nothing to sync, actually).

> Will the doc-related issues still be recorded in pulsar?

Yes.

**Comment by Anonymitaet** [comment]
> Although we may at first try to regard all changes in the site repo is about "doc".
They also include website-related changes, e.g., changing the background color. So it's better to have the `doc bot` working in `pulsar-site` and label doc-related PRs with corresponding doc labels.

**Comment by tisonkun** [comment]
@Anonymitaet Make sense. File an issue https://github.com/apache/pulsar/issues/19103.

I'll do it as a follow-up.

**Review by BewareMyPower — APPROVED** [review]

**Review by nodece — APPROVED** [review]

**Review by Anonymitaet — APPROVED** [review]

**Comment by tisonkun** [comment]
Merging...

@momo-jun @Anonymitaet PRs touch `site2` files need to be resubmitted against [the site repo](https://github.com/apache/pulsar-site). Ping me if any issue.

**Pull request merged**
