### PR TITLE
[fix][test] Fix CI build error

### PR DESCRIPTION
**Pull request by gaozhangmin**
### Motivation

Now all CI failed with below error.
https://github.com/apache/pulsar/runs/7911509789?check_suite_focus=true

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by nodece — APPROVED** [review]

**Comment by codelipenghui** [comment]
I think it is related to https://github.com/apache/pulsar/pull/17142? If yes, we should cherry-pick it one to branch-2.11

**Review by codelipenghui — APPROVED** [review]

**Comment by gaozhangmin** [comment]
> Details

@codelipenghui  Yes.

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by Jason918 — APPROVED** [review]

**Review by AnonHxy — APPROVED** [review]

**Pull request merged**
