### PR TITLE
Issue 9279: Pulsar Admin: add command to list bookies

### LINKED ISSUE #9279: Pulsar Admin: add command to list bookies
In 2.7.x you can operate the bookies using `bin/bookkeeper shell` and `bin/pulsar-admin bookies`

With `pulsar-admin bookies racks-placement` command you can only see the bookies for which you have an explicit configuration.
With `bookkeeper shell listbookies -a` you can get a list of all of the registered bookies

It would be very good to have a `pulsar-admin bookies listbookies` command to inspect the list of bookies from the command line.

### PR DESCRIPTION
**Pull request by eolivelli**
Fixes #9279

### Motivation

It would be more user friendly to have a "list-bookies" command in pulsar-admin, as described in #9279  

### Modifications
- add bookies/all API
- add list-bookies command
- add relevant test cases

### Verifying this change

This change added tests 

### Does this pull request potentially affect one of the following parts:
  - The rest endpoints: yes  (a new REST API resource) 

### Documentation

  - Does this pull request introduce a new feature? yes
  - If yes, how is the feature documented? not documented - self explaining when using pulsar-admin help
  - If a feature is not applicable for documentation, explain why? it is explained in pulsar-admin help

### CODE REVIEW

**Comment by eolivelli** [comment]
I have resolved all of the conflicts.

**Comment by eolivelli** [comment]
@rdhabalia @Renkai can you please take a look ?

**Review by Renkai — APPROVED** [review]

**Review by rdhabalia — APPROVED** [review]
LGTM

**Pull request merged**
