### PR TITLE
[Doc] Add *Cassandra sink connector guide*

### PR DESCRIPTION
**Pull request by Anonymitaet**
Fix https://github.com/apache/pulsar/issues/5015

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@tuteng could you please help review? Thank you

**Comment by tuteng** [comment]
run java8 tests
run integrations tests
run cpp tests

**Comment by tuteng** [comment]
run integration tests

**Comment by Anonymitaet** [comment]
run cpp tests

**Comment by Anonymitaet** [comment]
run cpp tests

**Pull request merged**
