### PR TITLE
Apply make format into Python C++ wrapper client

### PR DESCRIPTION
**Pull request by Licht-T**
### Motivation

This is the continuation of https://github.com/apache/incubator-pulsar/pull/1080.
I totally missed Python-C++ client wrapper.

### Modifications

- Add the Python-C++ client wrapper codes into `make format` target
- Apply `make format` into that

### Result

C++ codes are now totally clean!

### CODE REVIEW

**Comment by Licht-T** [comment]
Thanks @merlimat, these are now in the target of `make format`!

**Comment by sijie** [comment]
@Licht-T @merlimat  are we targeting this for 2.0? If not, can we move it to 2.1?

**Comment by sijie** [comment]
moved to 2.1. if it is required for 2.0, feel free to move it back.

**Comment by pinkavaj** [comment]
This seems till relevant, would be possible revive it?

**Comment by dave2wave** [comment]
This PR is evidently stale or abandoned. Reopen if this is not so.

**Pull request closed without merging**
