### PR TITLE
propagate default resource values in Pulsar Functions

### PR DESCRIPTION
**Pull request by jerrypeng**
### Motivation

Currently when resources are not specified by users, the defaults do not get propagated throw which can result in "-Xmx" not set for java functions.  We should propagate through default resource values so that java heap is set appropriately

### CODE REVIEW

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by merlimat** [comment]
Merged in 2.3.1 at 
f46bed7

**Pull request merged**
