### PR TITLE
[WIP] Move Docker images to jdk11 and python3 as default

### PR DESCRIPTION
**Pull request by aahmed-se**

### CODE REVIEW

**Comment by aahmed-se** [comment]
jdk8 and python are EOL, so this pr is to start preparing for moving to lte versions for both.

**Comment by sijie** [comment]
@aahmed-se this will change the user behavior using pulsar docker images. this change will directly impact users. I would prefer having a PIP discussion and make sure the community is aligned on the direction about java versions. Ideally I would prefer still having java8 because most of the applications will be still in java8.

**Comment by aahmed-se** [comment]
ok will create a pip 
the runtime target will still java 8 , no plans to change that.

**Comment by aahmed-se** [comment]
@sijie I don't have access to add or edit on the pulsar wiki

**Comment by sijie** [comment]
@aahmed-se People who doesn't have committer permissions usually writes the PIP in a google doc or a gist and share it to dev@ mailing list. Committers can then help you move the gist to pulsar wiki.

**Pull request closed without merging**
