### PR TITLE
[fix][broker] Update cpu ResourceUsage before updating SystemResourceUsage usage

### PR DESCRIPTION
**Pull request by lordcheng10**
### Motivation
Update cpu ResourceUsage before updating SystemResourceUsage usage.

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by Technoboy- — APPROVED** [review]

**Review by 315157973 — APPROVED** [review]

**Comment by lordcheng10** [comment]
rerun failure checks

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
