### PR TITLE
[fix][sec] Bump commons-io version to 2.18.0

### PR DESCRIPTION
**Pull request by ZachChuba**
Fixes security risk

### Motivation

Dependency common-io, shaded in pulsar-client, is susceptable to a reDos attack prior to version 2.15.0 

### Modifications

Bump commons-io version to 2.18.0

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/ZachChuba/pulsar/pull/2

CI only failed at upload stages

### CODE REVIEW

**Comment by lhotari** [comment]
My guess would be https://github.com/apache/commons-io/commit/841b5fafe13683389d078ec7a7adf736c05e038e . @ZachChuba Just curious how you spotted this? I don't think that we use commons-io for XML parsing in Pulsar, so perhaps there's no impact at all for Pulsar, however, obviously it's worthwhile to keep dependencies up-to-date.

**Comment by ZachChuba** [comment]
> My guess would be [apache/commons-io@841b5fa](https://github.com/apache/commons-io/commit/841b5fafe13683389d078ec7a7adf736c05e038e) . @ZachChuba Just curious how you spotted this? I don't think that we use commons-io for XML parsing in Pulsar, so perhaps there's no impact at all for Pulsar, however, obviously it's worthwhile to keep dependencies up-to-date.

@lhotari  This vulnerability is indeed the one patched via https://github.com/apache/commons-io/commit/841b5fafe13683389d078ec7a7adf736c05e038e. It was identified through an internal analysis tool. It's unlikely that pulsar is susceptible to this, as you suggested, but it's always a good idea to in case an enhancement inadvertently opens an attack vector through that susceptible dependency. Will upgrade to 2.18.0.

**Comment by lhotari** [comment]
> @lhotari This vulnerability is indeed the one patched via [apache/commons-io@841b5fa](https://github.com/apache/commons-io/commit/841b5fafe13683389d078ec7a7adf736c05e038e). It was identified through an internal analysis tool. It's unlikely that pulsar is susceptible to this, as you suggested, but it's always a good idea to in case an enhancement inadvertently opens an attack vector through that susceptible dependency. Will upgrade to 2.18.0.

@ZachChuba What internal analysis tool do you use? It seems that GitHub CodeQL had also flagged this. Just curious to know what are your specific security requirements for Apache Pulsar?

**Review by lhotari — APPROVED** [review]
LGTM

**Comment by ZachChuba** [comment]
@lhotari Sonatype Lifecycle has flagged this as a high severity vulnerability. My organization's risk posture treats any vulnerabilities that can significantly hinder application performance as either high or severe.

Sonatype has cataloged this as sonatype-2023-4396 and rated it high severity with a score of 8.7 based on our risk policy.

**Comment by lhotari** [comment]
> @lhotari Sonatype Lifecycle has flagged this as a high severity vulnerability. My organization's risk posture treats any vulnerabilities that can significantly hinder application performance as either high or severe.
> 
> Sonatype has cataloged this as sonatype-2023-4396 and rated it high severity with a score of 8.7 based on our risk policy.

Thanks for sharing the context!

**Comment by lhotari** [comment]
Thanks for contributing @ZachChuba

**Pull request merged**
