### PR TITLE
Fix intermittent test: BrokerServiceLookupTest.testModularLoadManager…

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

Fix intermittent test:
```
FAILED: testModularLoadManagerSplitBundle
java.lang.AssertionError: expected [true] but found [false]
    at org.testng.Assert.fail(Assert.java:96)
    at org.testng.Assert.failNotEquals(Assert.java:776)
    at org.testng.Assert.assertTrue(Assert.java:44)
    at org.testng.Assert.assertTrue(Assert.java:54)
    at org.apache.pulsar.client.api.BrokerServiceLookupTest.testModularLoadManagerSplitBundle(BrokerServiceLookupTest.java:952)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
    at org.testng.TestRunner.privateRun(TestRunner.java:648)
    at org.testng.TestRunner.run(TestRunner.java:505)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
    at org.testng.SuiteRunner.run(SuiteRunner.java:364)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
    at org.testng.TestNG.runSuites(TestNG.java:1028)
    at org.testng.TestNG.run(TestNG.java:996)
    at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
```

### CODE REVIEW

**Comment by jiazhai** [comment]
run java8 tests

**Comment by rdhabalia** [comment]
rerun java8 tests

**Comment by jiazhai** [comment]
rerun java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by rdhabalia** [comment]
I am going to disable [org.apache.pulsar.functions.worker.PulsarWorkerAssignmentTest.shutdown()](https://builds.apache.org/job/pulsar_precommit_java8/7046/testReport/junit/org.apache.pulsar.functions.worker/PulsarWorkerAssignmentTest/shutdown/) test for now because it's blocking other PR. It's mainly happening due to deadlock in function-worker while stopping the function during shutdown. I will create separate issue to fix the deadlock and then we can enable this test again.

**Comment by rdhabalia** [comment]
created issue #3768

**Comment by merlimat** [comment]
run java8 tests
run integration tests

**Comment by rdhabalia** [comment]
rerun integration tests

**Comment by rdhabalia** [comment]
rerun java8 tests

**Comment by rdhabalia** [comment]
rerun java8 tests
rerun java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by rdhabalia** [comment]
rerun integration tests

**Comment by rdhabalia** [comment]
rerun integration tests

**Pull request merged**
