### PR TITLE
Fix Go Functions metrics

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <rxl@apache.org>

### Modifications

- Fix go functions metrics
- Format code style(#6105)

### CODE REVIEW

**Comment by wolfstudy** [comment]
@devinbost Can you help review these changes?

**Comment by devinbost** [comment]
@wolfstudy Thanks for picking up this task. These changes all look good to me.

**Comment by wolfstudy** [comment]
> @wolfstudy Thanks for picking up this task. These changes all look good to me.

Thanks your feedback

**Comment by wolfstudy** [comment]
```
[INFO] Running org.apache.pulsar.broker.service.TopicTerminationTest
[ERROR] Tests run: 20, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 44.428 s <<< FAILURE! - in org.apache.pulsar.broker.service.ReplicatorTest
[ERROR] testUpdateGlobalTopicPartition(org.apache.pulsar.broker.service.ReplicatorTest)  Time elapsed: 0.017 s  <<< FAILURE!
org.apache.pulsar.client.admin.PulsarAdminException$ConflictException: Namespace already exists
	at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:223)
	at org.apache.pulsar.client.admin.internal.BaseResource$1.failed(BaseResource.java:133)
	at org.glassfish.jersey.client.JerseyInvocation$4.failed(JerseyInvocation.java:1030)
	at org.glassfish.jersey.client.JerseyInvocation$4.completed(JerseyInvocation.java:1017)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:227)
	at org.glassfish.jersey.client.ClientRuntime.access$200(ClientRuntime.java:85)
	at org.glassfish.jersey.client.ClientRuntime$2.lambda$response$0(ClientRuntime.java:178)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
```

**Comment by wolfstudy** [comment]
```
[INFO] Running org.apache.pulsar.broker.admin.v1.V1_AdminApiTest
[ERROR] Tests run: 46, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 262.601 s <<< FAILURE! - in org.apache.pulsar.broker.admin.v1.V1_AdminApiTest
[ERROR] partitionedTopics(org.apache.pulsar.broker.admin.v1.V1_AdminApiTest)  Time elapsed: 60.737 s  <<< FAILURE!
org.apache.pulsar.client.admin.PulsarAdminException$TimeoutException: java.util.concurrent.TimeoutException
	at org.apache.pulsar.client.admin.internal.TopicsImpl.getPartitionedTopicMetadata(TopicsImpl.java:430)
	at org.apache.pulsar.broker.admin.v1.V1_AdminApiTest.partitionedTopics(V1_AdminApiTest.java:906)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```

**Pull request merged**
