### PR TITLE
feat(cli): support sql-worker in pulsar-daemon

### PR DESCRIPTION
**Pull request by ericsyh**
Signed-off-by: Eric Shen <ericshenyuhao@outlook.com>

### Motivation

Pulsar sql-worker only supports in pulsar shell cli and not support in pulsar-daemon. So, users have to open two terminals to use pulsar sql, one for sql-worker and one for sql-cli.

### Modifications

I changed the pulsar shell cli and pulsar-daemon shell cli to support sql-worker in pulsar-daemon.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 

- [x] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [ ] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@ericsyh need to add docs [here](https://pulsar.apache.org/docs/en/next/reference-cli-tools/#pulsar-daemon)?

**Comment by ericsyh** [comment]
@Anonymitaet If this PR merged, the command of start a Pulsar SQL worker should be updated. I changed the start command from `./bin/pulsar sql-worker run` to `./bin/pulsar sql-worker` and also support the daemon in `./bin/pulsar-daemon start sql-worker` https://pulsar.apache.org/docs/en/sql-getting-started/#query-data-in-pulsar

**Comment by Anonymitaet** [comment]
@ericsyh thanks for your explanations! Then can you update docs [here](https://pulsar.apache.org/docs/en/next/reference-cli-tools/#pulsar) and [here](https://pulsar.apache.org/docs/en/sql-getting-started/#query-data-in-pulsar)?

**Comment by ericsyh** [comment]
Sure, i will update the doc. But seems i need some help on the CI, my changes won't impact on broker UT.

**Comment by hangc0276** [comment]
It will break the current pulsar sql worker startup action, please take a look @codelipenghui

**Comment by codelipenghui** [comment]
@ericsyh You can try `bin/pulsar sql-worker start`

**Comment by ericsyh** [comment]
> @ericsyh You can try `bin/pulsar sql-worker start`

This works to run sql-worker in daemon. But it really confusing for sql-worker actually.... while other components are all use `pulsar-damon` to start in daemon.

**Pull request closed without merging**
