### PR TITLE
[fix][broker] Fix Broker was failing to create producer with broken schema ledger

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

When schema ledger is broken and producer tries to connect without schema then broker fails to add that producer with below error.

It fixes below errors
```
03:46:47.861 [pulsar-io-4-63] DEBUG org.apache.pulsar.broker.service.BrokerService - No autoTopicCreateOverride policy found for persistent://ncp/global/content.ncp/url_uuid_alias.prod
03:46:47.861 [pulsar-io-4-63] DEBUG org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://ncp/global/content.ncp/url_uuid_alias.prod] Storage size = [0], backlog quota limit
 [53687091200]
03:46:47.861 [pulsar-io-4-63] DEBUG org.apache.pulsar.broker.service.schema.BookkeeperSchemaStorage - [ncp/content.ncp/url_uuid_alias.prod] Fetching schema from store
03:46:47.862 [pulsar-io-4-63] DEBUG org.apache.pulsar.broker.service.schema.BookkeeperSchemaStorage - [ncp/content.ncp/url_uuid_alias.prod] Got schema locator Optional[org.apache.pulsar.broker.se
rvice.schema.BookkeeperSchemaStorage$LocatorEntry@2a675a45]
03:46:47.862 [pulsar-io-4-63] DEBUG org.apache.pulsar.broker.service.schema.BookkeeperSchemaStorage - Reading schema entry from ledgerId: 742584758
entryId: 0

03:46:47.862 [pulsar-io-4-63] DEBUG org.apache.pulsar.metadata.bookkeeper.PulsarLedgerManager - No such ledger: 742584758 at path /ledgers/07/4258/L4758
03:46:47.862 [pulsar-io-4-63] ERROR org.apache.bookkeeper.meta.CleanupLedgerManager - Failed on operating ledger metadata: -25
03:46:47.862 [pulsar-io-4-63] DEBUG org.apache.pulsar.broker.service.schema.BookkeeperSchemaStorage - [ncp/content.ncp/url_uuid_alias.prod] Get operation completed. res=null -- ex=java.util.concu
rrent.CompletionException: org.apache.pulsar.broker.service.schema.exceptions.SchemaException: No such ledger exists on Metadata Server -  ledger=742584758 - operation=Failed to open ledger

```

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by vineeth1995 — APPROVED** [review]

**Comment by rdhabalia** [comment]
I am also adding email thread reply here

>> I want to revert this PR. Background: When the schemas of a topic are lost, all of the messages in the topic can not be consumed successfully, and producers can not publish messages anymore.

We must not revert this PR and broker must not allow topic unavailability in any cases and we can't rely on manual operational efforts to fix any topic server side issue
There are already many issues created related to the lost schema ledgers so, it is a very well-known issue that the topic becomes unavailable and producers are not able to publish messages anymore just because of server issues which is extremely critical for mission-critical usecases and not acceptable as well. Because of that brokers must be fault tolerant to recover in case of missing ledgers. Broker already handles such issues during manged-ledger or managed-cursor legers but it should also handle in case of schema ledger as well and make sure that broker won't impact topic's unavailability. It is also very important to just not rely on operational effort to fix such unavailability issues manually but broker should have a mechanism to recover by itself,
Therefore, this PR is important to make sure tenants don't face topic unavailability due to well known issues of missing schema ledgers.

**Comment by poorbarcode** [comment]
@rdhabalia 

Answered in discussion channel, we should do this. User can delete the broken schemas manually if they wanted

- Discussion channel: https://lists.apache.org/list.html?dev@pulsar.apache.org

**Comment by rdhabalia** [comment]
> User can delete the broken schemas manually when they received such error if they wanted

First of all user can't delete ledgers from the metadata store as ledger concept has to be abstract to user. System admin may be able to delete such ledgers but that is not possible for the systems which is running millions of topics and this issue is happening with multiple ledgers at the same time and manual efforts are not possible to address this issue.

**Comment by rdhabalia** [comment]
created PR: https://github.com/apache/pulsar/pull/23428 it will switch back to previous behavior unless force-flag is configured and ledger error is non-recoverable.

**Pull request merged**
