### PR TITLE
[Doc] Add more rules for rack name validation

### PR DESCRIPTION
**Pull request by momo-jun**
### Modifications

To align with #14336, add two more rules for rack name validation to the doc page and pulsar-admin cli.

### Preview
image

### Documentation
  
- [x] `doc`

### CODE REVIEW

**Comment by momo-jun** [comment]
Hi @hangc0276 @urfreespace @Anonymitaet, can you please review this doc PR? Thanks.

**Review by urfreespace — APPROVED** [review]
LGTM

**Review by Anonymitaet — APPROVED** [review]
Approve from the tech writing pespective

**Review by hangc0276 — APPROVED** [review]

**Pull request merged**
