### PR TITLE
[pulsar-broker] Namespace-resource use namespace name to fetch policy resource

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation
Namespace-resources should be able to fetch policy with namespace and internal-path should be handled by the base-resources. It will make code clean and will be helpful for future abstraction.

### CODE REVIEW

**Review by sijie — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
Hi Rajan @rdhabalia, Could you please help resolve the conflicts? so that we can merge it before 2.8.0

**Comment by codelipenghui** [comment]
@rdhabalia I will move this one to 2.9.0, feel free to move it back if it's need to release in 2.8.0

**Comment by rdhabalia** [comment]
again it seems #11693 PR added with the same change and PR was merged.  Closing this old PR as new PR gets merged.

**Pull request closed without merging**
