### PR TITLE
Add first message's properties to batch message metadata.

### PR DESCRIPTION
**Pull request by zhanghaou**
### Motivation
When use java client to build batch message, properties in single message can not add to batch message’s metadata.

### Modifications
Add first message's properties to batch message's metadata.

### Verifying this change
 New unit test added.

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Comment by Jason918** [comment]
> When use java client to build batch message, properties in single message can not add to batch message’s metadata.

Sorry I don't get why we need to add the properties to batch meta? Can you clarify your use case? 
@zhanghaou

**Review by eolivelli — CHANGES_REQUESTED** [review]
I think that this may be really misleading.
The consumer cannot know if the message has been generated with this feature or not.

If you need this for server side filtering then your filter cannot rely on the fact that the client used this feature.

What about creating some customer BatchBuilder or use some kind of Client side Interceptor to manipulate the message before writing it on the wire?

**Comment by zhanghaou** [comment]
> > When use java client to build batch message, properties in single message can not add to batch message’s metadata.
> 
> Sorry I don't get why we need to add the properties to batch meta? Can you clarify your use case? @zhanghaou

@Jason918 We need to get the properties in pulsar broker side, but if use batch message in java client, we can not get batch message's properties if we don't decode the batch message. Some other metadata were copied to batch message's from first message's metadata, so I think properties can also added to batch message's metadata(Maybe make it configurable is better).

**Comment by zhanghaou** [comment]
> > When use java client to build batch message, properties in single message can not add to batch message’s metadata.
> 
> Sorry I don't get why we need to add the properties to batch meta? Can you clarify your use case? @zhanghaou

@Jason918 We need to get the properties in pulsar broker side, but if use batch message in java client, we can not get batch message's properties if we don't decode the batch message. Some other metadata were copied to batch message's from first message's metadata, so I think properties can also added to batch message's metadata(Maybe make it configurable is better).

**Comment by zhanghaou** [comment]
> 

@eolivelli Yes，make it configurable in pulsar client is better. When I make this PR, I checked Go client SDK, first message's properties was added in batch message's metadata. Should we keep the same behave on java and Go client SDK?

[https://github.com/apache/pulsar-client-go/blob/2d5f6fcfa22af4184793a22ca353731a02b54ca9/pulsar/internal/batch_builder.go#L214](url)

**Comment by zhanghaou** [comment]
> 

@eolivelli Yes，make it configurable in pulsar client is better. When I make this PR, I checked Go client SDK, first message's properties was added in batch message's metadata. Should we keep the same behave on java and Go client SDK?

[https://github.com/apache/pulsar-client-go/blob/2d5f6fcfa22af4184793a22ca353731a02b54ca9/pulsar/internal/batch_builder.go#L214](url)

**Comment by eolivelli** [comment]
I think that it is a bug in the GO client.
The metadata of each message can be different from the first message.

If you add these values on the main header, in any case, they cannot be used by anyone.
Because the broker cannot know about the behaviour of the client. In the broker you cannot know if the message was produced by a client who copies the metadata, so in any case you MUST unpack all the messages.

Why don't you implement this feature (that I guess is for some specific usecase) with a Interceptor ?

**Comment by zhanghaou** [comment]
@eolivelli I want to added this feature only for pulsar broker, and all client had enabled this feature. My case is to support flow dyeing, which messages from same environment should be delivered to consumers in same environment(Shared or Key_shared mode), so Interceptor on client side seems useless.

**Comment by congbobo184** [comment]
@zhanghaou  hi, I move this PR to release/2.9.5, if you have any questions, please ping me. thanks.

**Comment by tisonkun** [comment]
Closed as stale and no consensus. Please rebase and resubmit the patch if it's still relevant.

@zhanghaou I suggest you talk about more about your use case (like https://github.com/apache/pulsar/pull/16215#issuecomment-1231061699)  instead of details (https://github.com/apache/pulsar/pull/16215#issue-1284416728). We should first get your motivation and then determinate whether this change it good or not.

If it's for your use case specifically, Pulsar as an open-source project already allow you to modify and distribution as you like. If it's a common use case that you believe can benefit the community, you can start a discussion at [the forum](https://github.com/apache/pulsar/discussions/categories/general) or the dev@ mailing list to reach a consensus first.

This way, you may find better approaches to meet your requirements, or at least avoid [the XY problem](https://xyproblem.info/).

**Pull request closed without merging**
