### PR TITLE
[pulsar-storm] Fix: Authentication is failing with storm adapter

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation
In #4284, made [Authentication](https://github.com/apache/pulsar/blob/master/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Authentication.java#L33) a transient under ClientConfigurationData. `Authentication` is a serializable class because ClientConfig is used in Storm and Spark adapter to pass client configuration and Storm serializes and deserializes spout and bolt while executing them in topology. Now, after making `Authentication` transient variable storm always deserializes it as null and authentication fails. Also `Authentication` is a serializable class so, any auth-implementation must be serializable.

### Modification
Keep Authentication param serializable.

### Result
It fixes pulsar-storm with authentication enabled.

### CODE REVIEW

**Comment by sijie** [comment]
@rdhabalia this will break other usages. because not all authentication implementation are serializable. the change in #4284 is to use ClientConfigurationData to reconstruct the Authentication object. I think we should change the adapter to use the same approach.

**Comment by rdhabalia** [comment]
There are few issues here:
1. User can set `Authentication` with [3 different ways](https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientBuilderImpl.java#L102-L120):
a. set `pluginName` and `paramString`
b. set `pluginName` and `paramMap`
c. user creates `Authentication` object and set it.
Fix: #4284 only handles (a) and it can't handle (b) and (c).

PulsarSpout and PulsarBolt accepts `ClientBuilder` which directly sets `Authentication` in clientConfigData (so, clientConfigData will never have any params) and most of the users directly set `Authentication` and making it `transient` will totally break their existing code.

**Comment by sijie** [comment]
@rdhabalia I think Flink builder does the same approach before which takes the Authentication object. But I think there is one implementation of Authentication interface is not serializable. It leads to the fix in #4284. If we want to switch it back to non-transient, we have to fix that implementation to make it serializable.

**Comment by rdhabalia** [comment]
> If we want to switch it back to non-transient, we have to fix that implementation to make it serializable.

Can you point me that Auth which is not serializable?

**Comment by sijie** [comment]
@shiv4289 - did you remember which Authentication is not serializable in #4283?

**Comment by shiv4289** [comment]
> @shiv4289 - did you remember which Authentication is not serializable in #4283?

@rdhabalia @sijie  AuthenticationToken.java

**Comment by shiv4289** [comment]
@rdhabalia @sijie I would like to put on the table why transient was added in the first place. Flink job manager stores the state of job (including pulsar client connection) for recovery. If authentication is non-transient, the auth token would get stored which has 2 implications:

1. This is a red flag from security point of view.
2. If my token supplier rotated the token between last state update and recovery, flink job will not be able to connect to pulsar.

 **I see the current patch keeps Authentication transient . Is this the final decision then?**

**Comment by rdhabalia** [comment]
@shiv4289 
> If authentication is non-transient, the auth token would get stored which has 2 implications:

Umm.. If we serialize `AuthenticationToken` then it won't serialize token and store it instead it tries to serialize tokenSupplier and if supplier fetches token dynamically then there shouldn't be the issue. But in `AuthenticationToken` class it can be the issue as it keeps token in memory.

[AuthenticationToken.java](https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/auth/AuthenticationToken.java#L41) is not serializble because `supplierToken` is not serializble. To address security issue and serialiable issue, can't we just mark `supplierToken` as a transient field and #4284  is anyway builds `Authentication` from auth-plugin classname and param. So, we can still have `Authentication` serializable and if any Auth-impl class has non-serializable variable then it can be transient and auth can be build using params.

> I see the current patch keeps Authentication transient . Is this the final decision then?

No, I was waiting for the reply with auth-classname which is not serializable. #4284 completely broke storm-adapter because user sets auths using ClientBuilder which doesn't set authPlugin/param into `ClientConfigurationData` and storm internally passes `ClientConfigurationData` to PulsarClient so, it always sees authentication null. I have added another commit to fix that issue: https://github.com/apache/pulsar/pull/6782/commits/92510e166ecbc17e78dd89ccae46049910c87c0c

**Comment by rdhabalia** [comment]
can you please confirm the change if that will work for you.

**Comment by shiv4289** [comment]
> Umm.. If we serialize `AuthenticationToken` then it won't serialize token and store it instead it tries to serialize tokenSupplier and if supplier fetches token dynamically then there shouldn't be the issue. But in `AuthenticationToken` class it can be the issue as it keeps token in memory.

That should work. Thanks @rdhabalia

**Pull request merged**
