### PR TITLE
[CLI] Add a broker tool for operations of a specific broker

### PR DESCRIPTION
**Pull request by sijie**
*Motivation*

Add a tool to collect load report on a specific broker.
This is used for troubleshooting problems in a production cluster.

*Modifications*

Add a broker tool for operations of a specific broker.

```
broker-tool is used for operations on a specific broker

Usage:  broker-tool [flags] [commands]

Commands:

    load-report     Collect the load report of a specific broker

    help            Display help information about it

Flags:


    -h, --help
        Display help information

Use "broker-tool [command] --help" or "broker-tool help [command]" for more
information about a command
```

```
Collect the load report of a specific broker

Usage:  load-report [flags]

Flags:

    -i, --interval-ms
        Interval to collect load report, in milliseconds


    -h, --help
        Display help information
```

### CODE REVIEW

**Comment by tuteng** [comment]
I saw a `broker-stats` sub-command under the command `pulsar-admin` and a `load-report` sub-command under the command `broker-stats`. I also saw this sub-command here. is there any difference between the two, why not consider adding it under pulsar-admin? @sijie

**Comment by sijie** [comment]
This is the tool runs on broker. It is used for troubleshooting why broker can’t collect right load report. The command in Pulsar-admin is used for querying the data reported to zookeeper. That’s the difference.

**Comment by codelipenghui** [comment]
run integration tests

**Comment by codelipenghui** [comment]
run integration tests

**Pull request merged**
