### PR TITLE
[branch-2.9][Broker] Fix call sync method in onPoliciesUpdate method

### PR DESCRIPTION
**Pull request by nodece**
### Motivation

Cherry-pick #13885 to branch-2.9

### Documentation

- [x] `no-need-doc`

### CODE REVIEW

**Review by Technoboy- — APPROVED** [review]

**Review by liudezhi2098 — APPROVED** [review]

**Comment by RobertIndie** [comment]
> ### Motivation
> Cherry-pick #12944 to branch-2.9
> 

What is the relationship between this PR and #12944?

**Comment by nodece** [comment]
@RobertIndie Sorry, should be #13885.

**Review by RobertIndie — APPROVED** [review]

**Pull request merged**
