### PR TITLE
[Doc]Update document for developer and old version

### PR DESCRIPTION
**Pull request by tuteng**
### Motivation

At present, in official documents, due to changes in the document structure and the limitation of docusaurus framework, the old version of the document cannot be deleted, only the name of the document can be changed so that there are many duplicate contents. when contributors want to modify the content of the document, they do not know where to modify it or need to modify several places, which is very unfriendly to developers.

### Modifications

* Keep the title of the document of the old version, delete the duplicate content, ensure that the old version can find the matching content.

### Verifying this change

yarn build pass

### CODE REVIEW

**Comment by tuteng** [comment]
run integration tests

**Comment by tuteng** [comment]
run integration tests
run java8 tests

**Comment by tuteng** [comment]
rerun integration tests

**Comment by sijie** [comment]
run java8 tests

**Comment by Jennifer88huang** [comment]
@Anonymitaet could you please help check the IO parts?

**Pull request merged**
