### PR TITLE
Update release 2.6.1 blog

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <rxl@apache.org>

- Update release 2.6.1 blog

### CODE REVIEW

**Review by Jennifer88huang — APPROVED** [review]

**Comment by wolfstudy** [comment]
ping @CarolynSN. PTAL thanks

**Comment by Jennifer88huang** [comment]
@wolfstudy if the release time is 8/21, do you need to update the file name?

**Comment by wolfstudy** [comment]
> @wolfstudy if the release time is 8/21, do you need to update the file name?

Good idea, will fix it, thanks  @Jennifer88huang

**Comment by Jennifer88huang** [comment]
@wolfstudy you might also need to rename the file name from "2020-08-17-Apache-Pulsar-2-6-1.md" to "2020-08-21-Apache-Pulsar-2-6-1.md", if it matters.

**Pull request merged**
