### PR TITLE
[security] Remove sensitive msg from consumer/producer stats log

### PR DESCRIPTION
**Pull request by Shoothzj**
### Motivation
Currently, we are print password field to consumer/producer stats log

### Modification
- add missed `@JsonIgnore` on field and getMethod
- delete unused `withoutAttribute` call

### CODE REVIEW

**Review by RobertIndie — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Review by Technoboy- — APPROVED** [review]

**Review by michaeljmarshall — COMMENTED** [review]
The `@Secret` annotation was supposed to ensure these are serialized as `***` when present. Do we know why the `SecretsSerializer` wasn't working here?

**Comment by Shoothzj** [comment]
@michaeljmarshall The `@Secret` is not recognized by jackson writer.

**Comment by michaeljmarshall** [comment]
> @michaeljmarshall The `@Secret` is not recognized by jackson writer.

@Shoothzj - I don't believe that is correct. When I remove the `@JsonIgnore` annotations that you added, and run your test while logging the output, here is what I get:

```
{"serviceUrl":null,"authPluginClassName":null,"authParams":null,"authParamMap":null,"operationTimeoutMs":30000,"lookupTimeoutMs":30000,"statsIntervalSeconds":60,"numIoThreads":1,"numListenerThreads":1,"connectionsPerBroker":1,"useTcpNoDelay":true,"useTls":false,"tlsTrustCertsFilePath":"","tlsAllowInsecureConnection":false,"tlsHostnameVerificationEnable":true,"concurrentLookupRequest":5000,"maxLookupRequest":50000,"maxLookupRedirects":20,"maxNumberOfRejectedRequestPerConnection":50,"keepAliveIntervalSeconds":30,"connectionTimeoutMs":10000,"requestTimeoutMs":60000,"initialBackoffIntervalNanos":100000000,"maxBackoffIntervalNanos":60000000000,"enableBusyWait":false,"listenerName":null,"useKeyStoreTls":false,"sslProvider":null,"tlsTrustStoreType":"JKS","tlsTrustStorePath":null,"tlsTrustStorePassword":"*****","tlsCiphers":[],"tlsProtocols":[],"memoryLimitBytes":67108864,"proxyServiceUrl":null,"proxyProtocol":null,"enableTransaction":false,"dnsLookupBindAddress":null,"dnsLookupBindPort":0,"socks5ProxyAddress":null,"socks5ProxyUsername":null,"socks5ProxyPassword":"*****"}
```

Note that the `@Secret` fields correctly have `****` in the names.

The `@Secret` annotation was added here, https://github.com/apache/pulsar/pull/8910, and the annotation's interface definitely shows an integration with Jackson. That being said, perhaps you found a case where the Jackson serializer wasn't interpreting the annotation correctly? I'm not familiar enough with custom annotations to know, but it seems like the old behavior was working in unit tests.

**Comment by Shoothzj** [comment]
@michaeljmarshall 
There mightbe sometime the `@Secret` ability is broken. If you checkout to `8bf6785c0803d314465b2d9156df6ca5bbb3c644` commitId, the test will fail.

**Comment by michaeljmarshall** [comment]
@Shoothzj - The test fails because a configuration name including `Password` is printed in a key. The sensitive field's value is `****`, so there is no leak. When I remove `Assert.assertFalse(s.contains("Password"));`, the test passes.

**Comment by Shoothzj** [comment]
@michaeljmarshall I retest the code. You are right, shall we revert this PR? I can work on it.

**Comment by michaeljmarshall** [comment]
@Shoothzj - thanks for testing it out and confirming! I think it'd be good to revert it. I'm happy to help review and cherry-pick it, if that helps.

**Pull request merged**
