### PR TITLE
 [conf] Add annotations for documenting broker configuration settings

### PR DESCRIPTION
**Pull request by sijie**
*Motivation*

This change is adding annotations to broker configuration for generating broker configuration file.

### CODE REVIEW

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by jiazhai** [comment]
run java8 tests
run integration tests

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Pull request merged**
