### PR TITLE
Fix npe caused by enabling packagemanagement service in standalone se…

### PR DESCRIPTION
**Pull request by gaozhangmin**
### Motivation
NPE when enable packagemanagement service in standaloneService.
```
2022-02-25T16:23:41,253+0800 [main] ERROR org.apache.pulsar.broker.PulsarService - Failed to start Pulsar service: null
java.lang.NullPointerException: null
        at org.apache.distributedlog.impl.BKNamespaceDriver.getZKServersFromDLUri(BKNamespaceDriver.java:98) ~[org.apache.distributedlog-distributedlog-core-4.14.4.jar:4.14.4]
        at org.apache.distributedlog.ZooKeeperClientBuilder.uri(ZooKeeperClientBuilder.java:143) ~[org.apache.distributedlog-distributedlog-core-4.14.4.jar:4.14.4]
        at org.apache.distributedlog.metadata.DLMetadata.create(DLMetadata.java:146) ~[org.apache.distributedlog-distributedlog-core-4.14.4.jar:4.14.4]
        at org.apache.pulsar.packages.management.storage.bookkeeper.BookKeeperPackagesStorage.initializeDlogNamespace(BookKeeperPackagesStorage.java:105) ~[org.apache.pulsar-pulsar-package-bookkeeper-storage-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.apache.pulsar.packages.management.storage.bookkeeper.BookKeeperPackagesStorage.initialize(BookKeeperPackagesStorage.java:79) ~[org.apache.pulsar-pulsar-package-bookkeeper-storage-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.apache.pulsar.broker.PulsarService.startPackagesManagementService(PulsarService.java:1571) ~[org.apache.pulsar-pulsar-broker-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:782) [org.apache.pulsar-pulsar-broker-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.apache.pulsar.PulsarStandalone.start(PulsarStandalone.java:301) [org.apache.pulsar-pulsar-broker-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
        at org.apache.pulsar.PulsarStandaloneStarter.main(PulsarStandaloneStarter.java:142) [org.apache.pulsar-pulsar-broker-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
```

### Modifications

Fix npe

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Comment by gaozhangmin** [comment]
@codelipenghui  PTAL

**Review by codelipenghui — APPROVED** [review]
The change looks good to me, is it able to add a test?

**Comment by gaozhangmin** [comment]
> The change looks good to me, is it able to add a test?
@codelipenghui  test added

**Comment by gaozhangmin** [comment]
> The change looks good to me, is it able to add a test?
@codelipenghui  test added

**Review by nicoloboschi — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
LGTM

is branch-2.10 and branch-2.9 broken ?

**Comment by gaozhangmin** [comment]
> LGTM
> 
> is branch-2.10 and branch-2.9 broken ?
This feature rarely used, I think this bug has stayed for long time even before branch-2.9. @eolivelli

**Pull request merged**
