### PR TITLE
fix authorization not working when subscription permission is empty

### PR DESCRIPTION
**Pull request by wuzhanpeng**
### Motivation

This PR fixed the problem that `org.apache.pulsar.broker.authorization.AuthorizationProvider#canConsumeAsync` returned `true` when `org.apache.pulsar.common.policies.data.AuthPolicies#getSubscriptionAuthentication` was empty (i.e. the set of `subscription_auth_roles` in admin policies is empty). This is equivalent to allowing `subscription permissions` not to be checked during authorization.

### Modifications

- modifies `canConsumeAsync` of `PulsarAuthorizationProvider` and its relative test case.

### CODE REVIEW

**Comment by wuzhanpeng** [comment]
@rdhabalia @hangc0276 
Could you help review these changes ?

**Comment by eolivelli** [comment]
This looks like a behaviour change.
You we advertise this in the release notes ?
Will existing users be affected by this change ?

**Comment by wuzhanpeng** [comment]
> This looks like a behaviour change.
> You we advertise this in the release notes ?
> Will existing users be affected by this change ?

1) for regular users who enable authorization, they will grant topic and subscription permissions before actually consuming messages, thus these users would not be affected.
2) for those noncompliant users who never grant subscription permissions but still want authorization service, the subscriber would not be able to establish after this behavior takes effect.

**Comment by wuzhanpeng** [comment]
@hangc0276 @eolivelli @codelipenghui  Could you help review these changes?

**Comment by hangc0276** [comment]
> @hangc0276 @eolivelli @codelipenghui Could you help review these changes?

@wuzhanpeng  This PR will break the existing subscription behavior although the existing behavior not expected. It will cause the existing applications which doesn't grant role and subscription permission, subscribe failed after upgrading Pulsar to the version including this PR. We'd better start a discussion in dev@pulsar.apache.org first.

**Comment by hangc0276** [comment]
move to 2.8.2

**Comment by 315157973** [comment]
@wuzhanpeng Hello, is there an email address for discussion?

**Comment by Anonymitaet** [comment]
@wuzhanpeng is this a bug fix (no need to update docs?)

**Comment by michaeljmarshall** [comment]
I am going to remove the 2.8 label for now. @wuzhanpeng do you plan to continue with this work, or should we close this PR?

**Comment by michaeljmarshall** [comment]
@wuzhanpeng - if you're still interested in making this change, I think this feature might be viable if we put it behind a feature flag. The underlying question for this PR is how to interpret a lack of configuration for a subscription. Given that `null` has already been chosen to implicitly mean that the subscription permission feature is ignored, I think we need to maintain that functionality. However, a cluster focused on strict security where no permission is granted implicitly will interpret a lack of configuration for a subscription to mean the role doesn't have permission.

Additionally, I notice that there is currently no work around for admin roles that are not included in the subscription's allow list. Its worth discussing if admins get implicit permission to consume from a subscription.

**Comment by michaeljmarshall** [comment]
I've created #15597 to make this behavior configurable. Please feel free to add your feedback on the mailing list thread: https://lists.apache.org/thread/x6zg2l7hrtopd0yty93fhctsnm9n0wbt.

**Comment by tisonkun** [comment]
Closed as stale and conflict. Please rebase and resubmit the patch if it's still relevant.

**Pull request closed without merging**
