### PR TITLE
[issue 3839] [doc] Document default of schema-autoupdate-strategy : FULL

### LINKED ISSUE #3839: Document default of schema-autoupdate-strategy : FULL
**Describe the bug**
Doc bug. The document is missing default value for schema-autoupdate-strategy compatibilty

**To Reproduce**
1. Go to https://pulsar.apache.org/docs/en/pulsar-admin/#set-schema-autoupdate-strategy
2. In the options sections see the empty default box in front of compatibility.

**Expected behavior**
Document default value which is FULL

**Screenshots**
Screenshot 2019-03-16 at 9 09 30 PM

### PR DESCRIPTION
**Pull request by shiv4289**
Fixes #3839 
The documentation was missing default value for the cli property *schema-autoupdate-strategy compatibilty*

Added the missing documentation

### CODE REVIEW

**Comment by merlimat** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by jiazhai** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Pull request merged**
