### PR TITLE
[fix][broker] Modify authorization to update topic's properties

### PR DESCRIPTION
**Pull request by yuruguo**
### Motivation
Current users with production permission can change the properties of topic in PR-#17238, which will cause the properties of topic to become uncontrollable due to arbitrary changes. In fact, only tenant administrator and super user can change them.

### Modifications
- Modify `TopicOperation.PRODUCE` to `TopicOperation.UPDATE_METADATA` in internalUpdatePropertiesAsync method

### Documentation
- [x] `doc-not-needed` 

### Matching PR in forked repository
PR in forked repository: 
- https://github.com/yuruguo/pulsar/pull/3

### CODE REVIEW

**Review by nodece — APPROVED** [review]

**Comment by codelipenghui** [comment]
@yuruguo It's a behavior change. It's better to have a discussion under the dev mailing list to make sure everyone can know what will be changed.

**Comment by nodece** [comment]
> @yuruguo It's a behavior change. It's better to have a discussion under the dev mailing list to make sure everyone can know what will be changed.

First, add this feature in https://github.com/apache/pulsar/pull/17238, which will release in the 2.12 version, no breaking changes.

**Review by Technoboy- — APPROVED** [review]
LGTM

**Comment by yuruguo** [comment]
> > @yuruguo It's a behavior change. It's better to have a discussion under the dev mailing list to make sure everyone can know what will be changed.
> 
> First, add this feature in #17238, which will release in the 2.12 version, no breaking changes.

You are right @nodece, PTAL @codelipenghui

**Pull request merged**
