### PR TITLE
[improve][transaction] Add logs for REST API in transaction

### LINKED ISSUE #14851: Return code 500 when getting pending ack internal stats but without any error logs
**Describe the bug**

From the pulsar-admin:
```
root@normal-pulsar-broker-0:/pulsar# bin/pulsar-admin transactions pending-ack-internal-stats -t persistent://public/default/source-topic-partition-25 -s test -m
Warning: Nashorn engine is planned to be removed from a future JDK release
HTTP 500 Internal Server Error

Reason: HTTP 500 Internal Server Error
```

From the server side:
```
12:16:15.157 [pulsar-web-38-5] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [24/Mar/2022:12:16:15 +0000] "GET /admin/v3/transactions/pendingAckInternalStats/public/default/source-topic-partition-25/test?metadata=true HTTP/1.1" 500 54 "-" "Pulsar-Java-v2.9.2" 3
```

**Expected behavior**
The get pending ack internal stats command should work or give a meaningful error message

**Additional context**
latest branch-2.9

### PR DESCRIPTION
**Pull request by gaozhangmin**
### Motivation
Add logs when broker occur error.

### Documentation

Check the box below or label this PR directly.

Need to update docs? 
  
- [x] `no-need-doc` 

code optimize. no new feature added.

### CODE REVIEW

**Comment by mattisonchao** [comment]
Looks like you just add the error log here, a little bit confused about your PR title and description.

**Comment by gaozhangmin** [comment]
> Looks like you just add the error log here, a little bit confused about your PR title and description.

Without this, broker server side logged nothing as issue #14851.

**Review by RobertIndie — CHANGES_REQUESTED** [review]
This PR doesn't seem to fix the https://github.com/apache/pulsar/issues/14851 . I think we need to find the root cause of this issue.

**Review by Technoboy- — APPROVED** [review]
LGTM

**Comment by Technoboy-** [comment]
> This PR doesn't seem to fix the #14851 . I think we need to find the root cause of this issue.

Only add logs when error. It's not related to #14851.

**Review by RobertIndie — APPROVED** [review]
> > This PR doesn't seem to fix the #14851 . I think we need to find the root cause of this issue.
> 
> Only add logs when error. It's not related to #14851.

Get it. Thanks for your explanation. @Technoboy-

**Review by HQebupt — APPROVED** [review]

**Review by mattisonchao — COMMENTED** [review]
Looks like we will return 307, and this redirect exception may don't need to log error.

``@ApiResponse(code = 307, message = "Topic is not owned by this broker!"),``

**Comment by gaozhangmin** [comment]
> Looks like we will return 307, and this redirect exception may don't need to log error.
> 
> `@ApiResponse(code = 307, message = "Topic is not owned by this broker!"),`

@mattisonchao  redirection exception is thrown  in  method `validateTopicName`.  This error won't be caught by  CompletableFuture exceptionally

**Comment by mattisonchao** [comment]
@gaozhangmin 
Would you mind checking this code, looks this method will invoke ``validateTopicOwnershipAsync``?

https://github.com/apache/pulsar/blob/8757c3acf3456af64d3f4f8ffbb3202a6c18e02a/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TransactionsBase.java#L145-L149

**Comment by gaozhangmin** [comment]
@mattisonchao  PTAL again.

**Review by RobertIndie — APPROVED** [review]

**Review by mattisonchao — APPROVED** [review]

**Pull request merged**
