### PR TITLE
reduce unnecessary expansions for ConcurrentLong map and set 

### PR DESCRIPTION
**Pull request by lordcheng10**
### Motivation
Cleanup all the buckets that were in Deleted state, so that we can reduce unnecessary expansions.

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Comment by lordcheng10** [comment]
@eolivelli @merlimat PTAL,thanks!

**Review by Jason918 — COMMENTED** [review]
LGTM, But It's better to provide some unit test to cover this change.

**Review by Shoothzj — APPROVED** [review]

**Comment by lordcheng10** [comment]
> LGTM, But It's better to provide some unit test to cover this change.

I didn't expect a better test solution, unless I design a switch, such as: isCleanDeletedStatus=true, to compare the effect of opening and closing.
do you have a better idea？  @Jason918

**Comment by lordcheng10** [comment]
> LGTM, But It's better to provide some unit test to cover this change.

@Jason918 Fixed,PTAL,thanks!

**Review by Jason918 — APPROVED** [review]

**Comment by lordcheng10** [comment]
@eolivelli PTAL,thanks!

**Review by hangc0276 — APPROVED** [review]

**Comment by lordcheng10** [comment]
@eolivelli PTAL,thanks!

**Comment by lordcheng10** [comment]
@eolivelli PTAL,thanks!

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
