### PR TITLE
Trigger a build for branch-2.8 to see if the build passes

### PR DESCRIPTION
**Pull request by lhotari**
Trigger a build for branch-2.8 to see if the build passes

### CODE REVIEW

**Comment by lhotari** [comment]
@315157973 The build results from this empty PR will be helpful for checking branch-2.8 state.

**Comment by lhotari** [comment]
@315157973 The tests passed. It's possible to reopen this PR to get the tests to run for branch-2.8.

**Comment by michaeljmarshall** [comment]
Closing and re-opening to trigger tests.

**Comment by michaeljmarshall** [comment]
Triggering build for 2.8.3 rc 3

**Comment by michaeljmarshall** [comment]
Test `testRemoveClusterFromNamespace` failed with a timeout for the broker group 1 unit tests. Restarting now. Since it was a timeout, it might just be flaky.

**Comment by michaeljmarshall** [comment]
Tests passed, so it was just flaky.

**Comment by tisonkun** [comment]
Closed as stale. I think we're now using personal CI for casual testing :)

**Pull request closed without merging**
