### PR TITLE
Disallow parsing of token with none signature in authenticateToken

### PR DESCRIPTION
**Pull request by nodece**
Signed-off-by: Zixuan Liu <nodeces@gmail.com>

### Motivation

If Apache Pulsar is configured to authenticate clients using tokens based on JSON Web Tokens (JWT), the signature of the token is not validated if the algorithm of the presented token is set to "none". This allows an attacker to connect to Pulsar instances as any user (incl. admins).

### Modifications

- using `parseClaimsJws` instead of `parse`

`parseClaimsJws` can guarantees the correct security model for parsing signed JWTs.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

### CODE REVIEW

**Review by sijie — APPROVED** [review]

**Comment by sijie** [comment]
@315157973 Great catch!

@nodece Can you add a flag to turn this validation on/off?

**Review by hangc0276 — APPROVED** [review]

**Comment by nodece** [comment]
@hangc0276 `CI - Integration - Sql / sql` still failed.

**Comment by nodece** [comment]
@sijie `CI - Integration - Sql / sql (pull_request)` always failed. could you reset that?

**Comment by codelipenghui** [comment]
@nodece Please rebase the master branch

**Review by codelipenghui — APPROVED** [review]

**Review by tuteng — APPROVED** [review]

**Comment by nodece** [comment]
All tests has been passed.

**Comment by sijie** [comment]
@nodece Awesome contribution!

**Pull request merged**
