### PR TITLE
Upgrade to ZooKeeper 3.6.2

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Upgrade to latest stable ZK version 3.6.2. The new minor versions brings several advantages: 
 * Performance improvements (eg: tuning group commit on txn log)
 * Prometheus based metrics (so that we can get rid of AspectJ hacky way to instrument ZK)
 * New features like persistent recursive watches which would greatly simplify the logic to handle metadata cache invalidations.

The possibility of rollback to previous version has also been validated.

### CODE REVIEW

**Comment by rdhabalia** [comment]
it's compatible with old zk-server version.right?

**Review by rdhabalia — APPROVED** [review]

**Review by srkukarni — APPROVED** [review]

**Comment by merlimat** [comment]
> it's compatible with old zk-server version.right?

Yes, unless we start making use of new features in ZK client

**Review by codelipenghui — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
LGTM

FYI we have been using Pulsar broker 2.5.x with ZK 3.6.2 client and server in production without issues for a couple of months

**Comment by eolivelli** [comment]
@codelipenghui it would be interesting to have this patch in 2.7.0

@merlimat unfortunately there are test failure related to this patch, like this one:
```
java.lang.NullPointerException
	at org.apache.pulsar.io.flume.node.TestAbstractZooKeeperConfigurationProvider.tearDown(TestAbstractZooKeeperConfigurationProvider.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
```

**Comment by sijie** [comment]
@merlimat Can you rebase this pull request?

**Comment by eolivelli** [comment]
@merlimat if you do not have time I can pick this up

**Comment by codelipenghui** [comment]
@eolivelli I will start the 2.7.0 release process soon, I think it's better to onboard this change.  Seems @merlimat do not have time, I think you can pick up this fix.

**Comment by eolivelli** [comment]
@merlimat @codelipenghui I am trying to fix this patch now.
btw **it is not a blocker for a release**.

We are also supporting ZooKeeper server in pulsar distribution, and AFAIK adapting the server side can be painful the way we are launching it.
 
Stay tuned

**Comment by eolivelli** [comment]
closing in favour of #8590 

btw @codelipenghui we cannot make this upgrade, a release on BK is needed, see #8590

**Comment by eolivelli** [comment]
@merlimat I cannot close the issue, please do it for me

**Comment by sijie** [comment]
Closed this in favor of #8590

**Pull request closed without merging**
