### PR TITLE
[feat][client] Support configure MessageCrypto in ProducerBuilder

### PR DESCRIPTION
**Pull request by tisonkun**
This closes https://github.com/apache/pulsar/issues/19139.

### Motivation

It's a lightweight feature alignment. Since it somehow touches public API, I don't know if it requires a PIP. It may not be, just trivial.

### Modifications

Support configure MessageCrypto in ProducerBuilder.

We already test this field but never pass or expose the config:

https://github.com/apache/pulsar/blob/32ad90606062c1eda660037e6277253b35d4a1e6/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java#L207-L219

### Verifying this change

Trivial.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [x] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

Maybe I should update some doc, but I'm not sure where is related doc.

- [ ] `doc` 
- [x] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by Technoboy-** [comment]
LGTM

**Review by RobertIndie — COMMENTED** [review]
I think it was the lack of testing that caused the missing exposure of this field to the ProducerBuilder. Better to add a test to cover this case.

**Review by RobertIndie — APPROVED** [review]
Just found out that the consumer also lacks of function test of message crypto. I'm +1 for this PR.

**Comment by tisonkun** [comment]
> Just found out that the consumer also lacks of function test of message crypto. I'm +1 for this PR.

Yep. This is a standard builder pattern and a complement. We don't test builders but upper-layer logic, do we?

**Comment by tisonkun** [comment]
@eolivelli e73ad352252beab617cefbf4ff70b84e8206b71c add basic set-and-get tests to prevent API breaking. `ConsumerBuilderImplTest` already has similar API call to prevent API breaking. Please take another look :)

**Review by eolivelli — APPROVED** [review]

**Comment by tisonkun** [comment]
Thanks for your reviews!

Merging...

**Comment by Anonymitaet** [comment]
@tisonkun thanks for introducing this improvement!

I see this PR was labeled with `doc-required`, so from the doc perspective:

- Java Client API doc: it has been added.
- Java Client user doc: do we need to add some usage examples to [Java client - Work with producer](https://pulsar.apache.org/docs/next/client-libraries-producers/)?
- Pulsar Feature Matrix - Client: do we need to add details to [Java Client Producer - End-to-end Encryption](https://docs.google.com/spreadsheets/d/1YHYTkIXR8-Ql103u-IMI18TXLlGStK8uJjDsOOA0T20/edit#gid=1784579914&range=50:50)?

Thank you!

**Pull request merged**
