### PR TITLE
[improve][client][branch-2.11]PIP-189: No batching if only one message in batch

### PR DESCRIPTION
**Pull request by AnonHxy**
### Motivation

Cherry-pick https://github.com/apache/pulsar/pull/16605

### Modifications

Cherry-pick https://github.com/apache/pulsar/pull/16605

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by AnonHxy** [comment]
@Technoboy- @Jason918  PTAL

**Review by Technoboy- — APPROVED** [review]

**Review by Jason918 — APPROVED** [review]
LGTM

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by Jason918** [comment]
@eolivelli PTAL

**Comment by eolivelli** [comment]
thank you @Jason918

**Pull request merged**
