### PR TITLE
Make Pulsar-SQL module to be a child of Pulsar main project

### LINKED ISSUE #10727: Could not  find artifact org.apache.pulsar:pulsar-presto-distribution:tar.gz:newVersion
**Describe the bug**
change the version of pulsar using `mvn` command,  and it will get `Could not find artifact org.apache.pulsar:pulsar-presto-distribution:tar.gz:newVersion` exception when build.

**To Reproduce**
1. `mvn versions:set -DnewVersion=x.x.x.x`
2. `mvn clean install -DskipTests`
2. See error

**Expected behavior**
build successfully.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by dockerzhang**
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #10727

Master Issue: #<xyz>

### Motivation

we want to use a different version sometimes, it's laborious to change `pom.xml`, and it's better to support set any version for pulsar by maven command.

### Modifications

change the parent dependency for pulsar-presto-connector, and the version could be affected by 'mvn versions:set -DnewVersion=' command.

### CODE REVIEW

**Review by sijie — APPROVED** [review]

**Comment by dockerzhang** [comment]
I am confused there are some integration CI fails, which do not happen in the local environment.

```
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project pulsar-presto-distribution: Fatal error compiling: error: release version 1.8 not supported 
```

**Comment by dockerzhang** [comment]
After this PR, we could set any version for pulsar by maven command, and it will build successfully:
```
mvn versions:set -DnewVersion=x.x.x.x
```

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@dockerzhang Could you please help check the license check issue?

**Comment by dockerzhang** [comment]
@codelipenghui I tried to fix the license check issue, but I did not figure out why this PR could affect the License Check and SQL Integration test. And I checked the structure of pulsar-presto-distribution output files, there is no difference. Could you give me some clue about how to fix it?

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by eolivelli** [comment]
This implementation will probably change the  versions of the dependencies.
we should take care of explicitly setting dependency versions in the pulsar-sql pom files

**Comment by eolivelli** [comment]
it is because we have "dependencyManagement" and "pluginManagement" in main pulsar parent pom.xml

**Comment by eolivelli** [comment]
please also note the error:
`src/check-binary-license: line 111: echo: write error: Broken pipe`

this means that we have to rerun the job

**Comment by eolivelli** [comment]
the fact the the integration tests failed is bad news
probably some dependency changed and the Presto server does not work anymore

**Comment by eolivelli** [comment]
I would also change the title of the PR to "Make Pulsar-SQL module to be a child of Pulsar main project"
because the change is all about that

**Comment by dockerzhang** [comment]
@eolivelli I get what you said,  thanks. I will try to fix the LICENSE and the integration tests failed.

**Comment by dockerzhang** [comment]
I found the following exception after running the  `sql-worker`:
```
2021-06-01T17:51:27.931+0800    ERROR   main    io.prestosql.server.PrestoServer        javax/servlet/http/HttpFilter
java.lang.NoClassDefFoundError: javax/servlet/http/HttpFilter
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at io.airlift.http.server.HttpServer.createServletContext(HttpServer.java:400)
        at io.airlift.http.server.HttpServer.<init>(HttpServer.java:351)
        at io.airlift.http.server.HttpServerProvider.get(HttpServerProvider.java:134)
        at io.airlift.http.server.HttpServerProvider.get(HttpServerProvider.java:43)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85)
        at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:77)
        at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:66)
```

**Comment by dockerzhang** [comment]
the timeout of `Integration - Sql` may be caused by other dependency problems. 
but I test `sql-worker` and `pulsar sql` in the local environment, they work fine.

**Comment by dockerzhang** [comment]
the following exception is caused by `joda-time-2.10.1.jar`, we can update it to `joda-time-2.10.5.jar`.
```
Caused by: java.lang.IllegalArgumentException: The datetime zone id 'Asia/Qostanay' is not recognised
	at org.joda.time.DateTimeZone.forID(DateTimeZone.java:234)
	at io.prestosql.util.DateTimeZoneIndex.<clinit>(DateTimeZoneIndex.java:43)
	... 44 more
```

**Comment by dockerzhang** [comment]
@sijie @codelipenghui @eolivelli Please review this PR again, thanks. there are some flaky test fails for broker should not caused by this PR.

**Comment by dockerzhang** [comment]
rebase to solve the conflicts.

**Comment by lhotari** [comment]
@dockerzhang this change might have caused #10834 . Would you mind taking a look?

**Pull request merged**
