### PR TITLE
[fix][broker] fix ns total size stats

### LINKED ISSUE #15492: pulsar_storage_size used backlogsize?
**Describe the bug**

 pulsar_storage_size means 

```
The total storage size of the topics in this topic owned by this broker (bytes).
```

but in PersistentTopic

```
        nsStats.storageSize += ledger.getEstimatedBacklogSize();

```

maybe it should be 

```
        nsStats.storageSize += ledger.getTotalSize();

```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by leizhiyuan**
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #15492

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #<xyz>

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `no-need-doc` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-added`
(Docs have been already added)

### CODE REVIEW

**Comment by tjiuming** [comment]
LGTM

**Review by gaozhangmin — COMMENTED** [review]
LGTM

**Review by gaozhangmin — APPROVED** [review]

**Review by Shoothzj — APPROVED** [review]

**Review by michaeljmarshall — APPROVED** [review]
LGTM. @leizhiyuan - are there tests covering this metric generation? If so, is it possible to cover this change?

Also, note that earlier in the modified method, we use `ledger.getTotalSize()` to set the topic's `storageSize`: https://github.com/apache/pulsar/blob/f0b7efa3a16b31b19baa2613ad2e43b3c439bb60/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L1817-L1818

**Review by eolivelli — APPROVED** [review]
Lgtm

**Review by michaeljmarshall — CHANGES_REQUESTED** [review]
I don't think we can merge this solution just yet because it doesn't align with the `storageSize` captured in the `NamespaceStatsAggreagtor` class, which is used for the prometheus metrics endpoint. In that class, the ledger's storage size is multiplied by the number of replicas to report the total storage size.

https://github.com/apache/pulsar/blob/7a7b5faa102b196021fdaf2ba77763f16087ef7a/pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java#L337

https://github.com/apache/pulsar/blob/7a7b5faa102b196021fdaf2ba77763f16087ef7a/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerMBeanImpl.java#L288-L290

Note that earlier in the `PersitentTopic` class modified in this PR, we use the ledger's total size method already, which isn't consistent with the `/metrics` endpoint.

https://github.com/apache/pulsar/blob/f0b7efa3a16b31b19baa2613ad2e43b3c439bb60/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L1817-L1818

Ideally, the broker stat's endpoint should be consistent with the `/metrics` endpoint. We'll need to investigate the "right" solution though. My naive preference is to change the implementation of the namespace stats to match the `/metrics` endpoint's implementation.

Please let me know what you think.

**Comment by leizhiyuan** [comment]
> #15492

maybe we should confirm that  size should multiplied by the number of replicas or not?

**Comment by Jason918** [comment]
@michaeljmarshall Any further suggestions about this PR?

**Comment by eolivelli** [comment]
@Jason918 I think that @michaeljmarshall suggestion is correct Ndbwe should go that way

**Review by eolivelli — CHANGES_REQUESTED** [review]
We should follow @michaeljmarshall 's suggestion

**Comment by congbobo184** [comment]
@leizhiyuan   hi, I move this PR to release/2.9.5, if you have any questions, please ping me. thanks.

**Comment by poorbarcode** [comment]
Since we will start the RC version of `3.0.0` on `2023-04-11`, I will change the label/milestone of PR who have not been merged.
- The PR of type `feature` is deferred to `3.1.0`
- The PR of type `fix` is deferred to `3.0.1`

So drag this PR to `3.0.1`

**Comment by michaeljmarshall** [comment]
As discussed on the mailing list https://lists.apache.org/thread/w4jzk27qhtosgsz7l9bmhf1t7o9mxjhp, there is no plan to release 2.9.6, so I am going to remove the release/2.9.6 label

**Comment by leizhiyuan** [comment]
Since it takes a long time and the code differences are too large, I will close this PR.

**Pull request closed without merging**
