### PR TITLE
[ISSUE 10153]fix time unit ns -> ms

### LINKED ISSUE #10153: [Go functions] Very high (abnormal) average process latency
In Pulsar 2.6.2:

We ran a performance test of passthrough functions (meaning we just redirect the input to the output without any additional processing or logic) in Java, Python, and Go. Each function subscribed to the same input topic with an exclusive subscription. We delivered approximately 1000 msg/sec to the input topic. 

Here are the findings:
image

VSZ = Virtual Memory Size
RSS = Resident Set Size
(Both metrics are explained here: https://stackoverflow.com/questions/7880784/what-is-rss-and-vsz-in-linux-memory-management)

As you can see, the go functions reported an abnormally high latency. It's not clear yet if there's a bug in Go function metrics or if the actual latency was really that high. As we didn't notice any backlog accumulate, we suspect there's a miscalculation of the latency. However, it still should be investigated.

### PR DESCRIPTION
**Pull request by linlinnn**
Fixes #10153

### Motivation
fix the time unit of avg process latency in go

### CODE REVIEW

**Review by merlimat — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]
Nice catch.

**Review by sijie — APPROVED** [review]

**Pull request merged**
