### PR TITLE
[fix][broker] Fix RetentionPolicies types mismatch.

### LINKED ISSUE #18112: [Bug] RetentionPolicies types mismatch
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

`master` branch.

### Minimal reproduce step

The `retentionSizeInMB` field has `long` type here:

https://github.com/apache/pulsar/blob/7404e0d77d98c2ec4fab9a111b8ced38d33dcd5a/pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/RetentionPolicies.java#L32

But it is an `int` type in the constructor:

https://github.com/apache/pulsar/blob/7404e0d77d98c2ec4fab9a111b8ced38d33dcd5a/pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/RetentionPolicies.java#L38

### What did you expect to see?

I expect the same types for the private field and the constructor.

### What did you see instead?

It's not a user-faced bug.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Technoboy-**
Fixes #18112

### Documentation

- [x] `doc-not-needed`

### CODE REVIEW

**Comment by coderzc** [comment]
Also should modify `ManagedLedgerConfig.retentionSizeInMB` type.

https://github.com/apache/pulsar/blob/7b53bd90604e80ed5653dcb9f9d4324d3d533d68/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerConfig.java#L437-L440

**Review by coderzc — COMMENTED** [review]
Also should modify `ManagedLedgerConfig.retentionSizeInMB` type.

https://github.com/apache/pulsar/blob/7b53bd90604e80ed5653dcb9f9d4324d3d533d68/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerConfig.java#L437-L440

**Comment by Technoboy-** [comment]
> setRetentionSizeInMB



> Also should modify `ManagedLedgerConfig.retentionSizeInMB` type.
> 
> https://github.com/apache/pulsar/blob/7b53bd90604e80ed5653dcb9f9d4324d3d533d68/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerConfig.java#L437-L440

applyed

**Review by coderzc — APPROVED** [review]

**Review by lordcheng10 — APPROVED** [review]
LGTM

**Review by mattisonchao — APPROVED** [review]
Question: Why don't we choose `long`?

**Comment by Technoboy-** [comment]
> Question: Why don't we choose `long`?

`int` is enough.

**Comment by nodece** [comment]
Hi @Technoboy-, why not change the constructor of the `RetentionPolicies`?

So like:
```
    public RetentionPolicies(int retentionTimeInMinutes, long retentionSizeInMB) {
```

`long` can be compatible with `int`.

**Comment by nodece** [comment]
> > Question: Why don't we choose `long`?
> 
> `int` is enough.

I think we still should use the `long`, `long` can be compatible with `int`.

@Technoboy- @mattisonchao

**Pull request merged**
