### PR TITLE
Fix usage of PULSAR_EXTRA_OPTS/BOOKIE_EXTRA_OPTS in startup scripts

### PR DESCRIPTION
**Pull request by lhotari**
### Motivation

The changes in #11285 broke `pulsar-perf` and it fails with error 
```
root@3b36a0ea475b:/pulsar# ./bin/pulsar-perf produce 
[0.000s][error][logging] Error opening log file 'logs/pulsar_gc_14.log': No such file or directory
[0.000s][error][logging] Initialization of output 'file=logs/pulsar_gc_%p.log' using options 'filecount=10,filesize=20M' failed.
Invalid -Xlog option '-Xlog:gc*:logs/pulsar_gc_%p.log:time,uptime:filecount=10,filesize=20M', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

When analyzing the problem, it seems that the usage of `PULSAR_EXTRA_OPTS`/`BOOKIE_EXTRA_OPTS` environment variables isn't correctly used. It should be possible to use `PULSAR_EXTRA_OPTS`/`BOOKIE_EXTRA_OPTS` to add additional environment variables. This PR fixes that issue.

### Modifications

- don't combine `BOOKIE_MEM`, `BOOKIE_GC` and `BOOKIE_GC_LOG` in `BOOKIE_EXTRA_OPTS`
- don't add `PULSAR_GC_LOG` to `PULSAR_EXTRA_OPTS`
- make `BOOKIE_GC_LOG` default to `PULSAR_GC_LOG` for consistency
- apply `PULSAR_EXTRA_OPTS` and `BOOKIE_EXTRA_OPTS` after other settings so that it is possible to override
  settings defined by `PULSAR_MEM` / `PULSAR_GC` / `BOOKIE_MEM` / `BOOKIE_GC`.

### Documentation

- [x] `no-need-doc`

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by nicoloboschi — APPROVED** [review]
+1

**Review by MMirelli — COMMENTED** [review]
LGTM

**Review by 315157973 — APPROVED** [review]

**Comment by dave2wave** [comment]
Please make sure this change is referenced in the 2.10 release notes as it is a breaking change for OpenMessaging/Benchmarks (at least for me)

**Pull request merged**
