### PR TITLE
[Broker] Add spotbugs to pulsar-broker

### PR DESCRIPTION
**Pull request by nodece**
Signed-off-by: Zixuan Liu <nodeces@gmail.com>

### CODE REVIEW

**Review by sijie — CHANGES_REQUESTED** [review]
@nodece all the CI jobs failed due to license header isssue. Can you check and fix the issues?

**Comment by BewareMyPower** [comment]
The license format of `findbugsExclude.xml` is wrong, take https://github.com/apache/pulsar/blob/master/pulsar-client-api/src/main/resources/findbugsExclude.xml for example.

Also, you need to fix the spotbugs if existed.

**Review by sijie — APPROVED** [review]

**Comment by sijie** [comment]
@nodece Can you rebase the pull request?

**Comment by nodece** [comment]
@sijie done.

**Review by codelipenghui — APPROVED** [review]

**Comment by nodece** [comment]
Too long for no activity, so close.

**Pull request closed without merging**
