### PR TITLE
[Issue 11984] Fix zookeeper prometheus metrics doc

### LINKED ISSUE #11984: Zookeeper prometheus metrics inconsistent with Docs.
**Describe the bug**
The [documentation ](https://pulsar.apache.org/docs/en/reference-metrics/#zookeeper) and [zookeeper dashboard](https://github.com/streamnative/apache-pulsar-grafana-dashboard.git) use prometheus metrics prefixed with 'zookeeper_server_' which are no longer there.

For example `zookeeper_server_connections`

**To Reproduce**
1. `docker run --rm -d -p 2181:2181 --name zk apachepulsar/pulsar:2.8.0  bin/pulsar zookeeper`
2. `curl -s localhost:8000/metrics |grep ^zoo`
3. No zookeeper named metrics.
4. `curl -s localhost:8000/metrics`
5. Lots of output, so prometheus is working.
6. `docker rm -f zk`

**Expected behavior**
The documentation and grafana dasboards should use the correct metrics.

### PR DESCRIPTION
**Pull request by Shoothzj**
Fixes #11984

### Modifications

Fix the zookeeper prometheus metrics description

### CODE REVIEW

**Comment by Shoothzj** [comment]
@Anonymitaet

**Comment by Shoothzj** [comment]
@Anonymitaet PTAL this doc change, thanks

**Review by merlimat — APPROVED** [review]

**Comment by Anonymitaet** [comment]
@Shoothzj thanks for your contribution!

**Comment by Anonymitaet** [comment]
@Shoothzj Thanks for your contribution. Does this affect only master or other versioned docs? 
If latter, could you please help update all affected versions? Thanks

**Comment by Anonymitaet** [comment]
Hi @sijia-w can you help apply the same doc changes to 2.8.0, 2.8.1, 2.8.2? Thanks!
FYI: https://github.com/apache/pulsar/issues/11984#issuecomment-916591559

**Pull request merged**
