### PR TITLE
[Github Action] Fix flaky test

### PR DESCRIPTION
**Pull request by zymap**
---

*Motivation*

Some tests are failed by the file they used was changes.

*Modifications*

Fix flaky tests

### CODE REVIEW

**Comment by tuteng** [comment]
retest this please

**Comment by tuteng** [comment]
retest this please

**Comment by tuteng** [comment]
retest this please

**Comment by tuteng** [comment]
retest this please

**Comment by aahmed-se** [comment]
run cpp tests

**Comment by wolfstudy** [comment]
@sijie @tuteng @aahmed-se @jiazhai PTAL, thanks.

**Pull request merged**
