### PR TITLE
[docs] Fix typo in broker.conf and standalone.conf

### PR DESCRIPTION
**Pull request by rathipry**
Fixed typo in Resource usage ThresholdShedder in configuration comments.

### CODE REVIEW

**Comment by skyrocknroll** [comment]
@Jennifer88huang Can you please review this?

**Review by Huanli-Meng — APPROVED** [review]

**Review by Jennifer88huang — APPROVED** [review]
Nice catch @rathipry 
@skyrocknroll sure

**Review by wolfstudy — APPROVED** [review]

**Review by sijie — APPROVED** [review]

**Pull request merged**
