### PR TITLE
PIP-118: reconnect broker when ZooKeeper session expires

### LINKED ISSUE #13304: PIP-118: Do not restart brokers when ZooKeeper session expires
## Motivation

After all the work done for PIP-45 that was already included in 2.8 and 2.9
releases, it enabled the concept of re-acquirable resource locks and leader
election.

Another important change was to avoid doing any deferrable metadata operation
when we know that we are not currently connected to the metadata service.

Finally, that enabled to stabilize in 2.9 the configuration setting that allows
brokers to continue operating in a safe mode when the session with ZooKeeper
expires.

The way it works is that, when we lose a ZooKeeper session, the data plane will
continue to work undisturbed, relying on the BookKeeper fencing to avoid any
inconsistencies.

New topics are not able to get started, but existing topics will see no
impact.

The original intention for shutting down the brokers was to ensure that we
would automatically go back to a consistent state, with respect to which
resources are "owned" in ZooKeeper by a given broker.

With the re-acquirable resource locks, that problem was solved and thoroughly
tested to be robust.

## Proposed changes

In 2.10 release, for the setting:

```properties
# There are two policies to apply when broker metadata session expires: session expired happens, "shutdown" or "reconnect".
# With "shutdown", the broker will be restarted.
# With "reconnect", the broker will keep serving the topics, while attempting to recreate a new session.
zookeeperSessionExpiredPolicy=shutdown
```

Deprecate the old setting and rename it to `metadataSessionExpiredPolicy`, with default value set to `reconnect`.

### PR DESCRIPTION
**Pull request by HQebupt**
Fixes #13304 
### Motivation
See #13304 

### Modifications
Change `zookeeperSessionExpiredPolicy` default value from **shutdown** to **reconnect** instead of in the ` broker.conf `.

### Verifying this change

- [x]  Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:
If `yes` was chosen, please highlight the changes

- Dependencies (does it add or upgrade a dependency): (no)
- The public API: (no)
- The schema: (no)
- The default values of configurations: (no)
- The wire protocol: (no)
- The rest endpoints: (no)
- The admin cli options: (no)
- Anything that affects deployment: (no)

### Documentation
Check the box below and label this PR (if you have committer privilege).

Need to update docs? 

  
- [ ] `no-need-doc` 
  
  (There is description in the configuration modification)

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Review by merlimat — CHANGES_REQUESTED** [review]
Looks good though let's wait until the PIP is officially voted and accepted.

**Review by Shoothzj — APPROVED** [review]

**Comment by Anonymitaet** [comment]
Hi @HQebupt same comment: https://github.com/apache/pulsar/pull/13344#issuecomment-995544671

**Review by eolivelli — CHANGES_REQUESTED** [review]
thanks for your contribution

we should also change the default in ServiceConfiguration

**Comment by HQebupt** [comment]
> thanks for your contribution
> 
> we should also change the default in ServiceConfiguration

You are right, done.

**Review by codelipenghui — APPROVED** [review]

**Review by eolivelli — DISMISSED** [review]
LGTM

but the PIP VOTE thread is not finished
cc @merlimat

**Review by hangc0276 — APPROVED** [review]

**Review by Jason918 — APPROVED** [review]

**Review by merlimat — APPROVED** [review]

**Pull request merged**
