### PR TITLE
[Doc] [ISSUE 11291] Update Pulsar Dashboard relevant content

### LINKED ISSUE #11291: [Doc] Remove Pulsar Dashboard contents
Fix https://github.com/apache/pulsar/pull/11284

### PR DESCRIPTION
**Pull request by sijia-w**
Fixes #11291 

The links for `[Pulsar Java tutorial](https://github.com/streamlio/pulsar-java-tutorial)` and relevant content are broken. Is there any recommendations for what we should use instead? Thanks in advance.

### CODE REVIEW

**Comment by sijia-w** [comment]
@Anonymitaet @Jennifer88huang Please review the changes and I look forward to your recommendation for the links. Thanks.

**Comment by Anonymitaet** [comment]
@sijia-w @Jennifer88huang  how about https://opensourcelibs.com/lib/pulsar-java-tutorial?

**Comment by sijia-w** [comment]
@Anonymitaet I do not think it would work. It also uses the repo from streamlio 
image
I actually only found pulsar-java-tutorial in personal accounts, but I think we'd better find it somewhere official.

**Review by Huanli-Meng — CHANGES_REQUESTED** [review]
I think you need to go through the whole doc and replace `streamlio` related contents.

**Comment by sijia-w** [comment]
@Huanli-Meng Yes all relevant content should be updated, but I haven't found available sources for `pulsar-java-tutorial` yet. Do you have any suggestions?

**Comment by Huanli-Meng** [comment]
> I think you need to go through the whole doc and replace `streamlio` related contents.

Maybe you can double check with Penghui whether the Pulsar repo has such a tutorial folder. If not, you can check whether we can link back to the Pulsar website document.

**Comment by sijia-w** [comment]
@codelipenghui Any suggestions for a new link for `Pulsar-java-tutorial`? Many thanks.

**Comment by sijia-w** [comment]
@Huanli-Meng A new issue for `pulsar-java-tutorial` can be found #11699. Shall we close this pr if there is nothing else to modify for now?

**Review by Huanli-Meng — APPROVED** [review]
LGTM

**Pull request merged**
