### PR TITLE
[Doc]--add retry letter topic to messaging docs.

### PR DESCRIPTION
**Pull request by Huanli-Meng**
### Motivation
This doc update is for the PR: https://github.com/apache/pulsar/pull/6449. and it is target for Pulsar 2.6.0 release.

### Modifications
xxx

### CODE REVIEW

**Comment by Huanli-Meng** [comment]
@codelipenghui , could you please help review it? THX.

**Comment by Anonymitaet** [comment]
rerun tests

**Comment by Huanli-Meng** [comment]
close the PR as there are many conflicts that cannot be resolved. Will re-create a PR.

**Pull request closed without merging**
