### PR TITLE
[Transaction] Transaction coordinator metrics.

### PR DESCRIPTION
**Pull request by congbobo184**
## Motivation
Transaction coordinator metrics add.

## implement
```
    /** The transaction coordinatorId. */
    private long coordinatorId;

    /** The active transactions. */
    private int actives;

    /** The committed transaction count of this transaction coordinator. */
    public long committedCount;

    /** The aborted transaction count of this transaction coordinator. */
    public long abortedCount;

    /** The created transaction count of this transaction coordinator. */
    public long createdCount;

    /** The append transaction op log count of this transaction coordinator. */
    public long appendLogCount;

    /** The timeout out transaction count of this transaction coordinator. */
    public long timeoutCount;

    /** The transaction execution latency. */
    public StatsBuckets executionLatencyBuckets
```
This is transaction coordinator metrics, if have another useful metrics, we can add in other PR.
### Verifying this change
Add the tests for it

Does this pull request potentially affect one of the following parts:
If yes was chosen, please highlight the changes

Dependencies (does it add or upgrade a dependency): (no)
The public API: (no)
The schema: (no)
The default values of configurations: (no)
The wire protocol: (no)
The rest endpoints: (no)
The admin cli options: (no)
Anything that affects deployment: (no)

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@congbobo184 thanks for your work. Could you please help add docs accordingly? Thanks

**Comment by congbobo184** [comment]
> @congbobo184 thanks for your work. Could you please help add docs accordingly? Thanks

OK, when transaction completely, I will add the docs.

**Review by eolivelli — APPROVED** [review]
LGTM

very useful

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
