### PR TITLE
[fix][broker] Only validate superuser access if authz enabled

### PR DESCRIPTION
**Pull request by michaeljmarshall**
### Motivation

In #19455, I added a requirement that only the proxy role could supply an original principal. That check is only supposed to apply when the broker has authorization enabled. However, in one case, that was not the case. This PR does a check and returns early when authorization is not enabled in the broker.

See https://github.com/apache/pulsar/pull/19830#issuecomment-1492262201 for additional motivation.

### Modifications

* Update the `PulsarWebResource#validateSuperUserAccessAsync` to only validate when authentication and authorization are enabled in the configuration.

### Verifying this change

This is a trivial change. It'd be good to add tests, but I didn't include them here because this is a somewhat urgent fix. There was one test that broke because of this change, so there is at least some existing coverage.

### Documentation

- [x] `doc-not-needed`

### Matching PR in forked repository

PR in forked repository: https://github.com/michaeljmarshall/pulsar/pull/39

### CODE REVIEW

**Review by poorbarcode — APPROVED** [review]
Since there will not have a scenario like this `disabled authentication & enabled authorization`, so it will work.

LGTM

**Comment by michaeljmarshall** [comment]
> Since there will not have a scenario like this `disabled authentication & enabled authorization`, so it will work.

Correct. The broker actually fails on startup if that is the configuration:

https://github.com/apache/pulsar/blob/6621fd3451a52bb7447ebeb845c83ac2f310b718/pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java#L695-L698

**Review by codelipenghui — APPROVED** [review]

**Review by nicoloboschi — APPROVED** [review]

**Review by Technoboy- — APPROVED** [review]

**Comment by codelipenghui** [comment]
@michaeljmarshall Is it possible to add a test to make we will not be impacted in the future?

**Review by nodece — APPROVED** [review]

**Comment by michaeljmarshall** [comment]
Looks like there are some legitimate test failures. I fixed the first. The second is `activeBrokerParse` added by https://github.com/apache/pulsar/pull/9191. It looks like that test enables authorization, but it doesn't look configured. I think we can remove those config lines, but I'm not certain.

**Comment by michaeljmarshall** [comment]
> The second is `activeBrokerParse` added by #9191. It looks like that test enables authorization, but it doesn't look configured. I think we can remove those config lines, but I'm not certain.

I decided to remove the configuration to enable authorization. It was not actually used in the previous tests and it was forcing the failure here. If we want to test authorization in that test, we need to enable authentication as well.

**Comment by michaeljmarshall** [comment]
There are more, legitimate test failures. This one is next `testNamespacesApiRedirects`. Interestingly, it looks like that test might have a hint as to why the `activeBrokerParse` was enabling authorization:

https://github.com/apache/pulsar/blob/3a069ed07ea0e03405b72458a585f93bf95b2d77/pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java#L706-L707

When running the `activeBrokerParse` locally, it is flaky, and it appears that it passes on master when there are several 307 redirects, but fails on my branch without any of those redirects.

**Comment by michaeljmarshall** [comment]
This is the part of the code that has the "hack" described in the above comment:

https://github.com/apache/pulsar/blob/3b76dd435d1bb7f5f933dbc15307255c7c928ca4/pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java#L512-L519

https://github.com/apache/pulsar/blob/3b76dd435d1bb7f5f933dbc15307255c7c928ca4/pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java#L536-L547

**Comment by michaeljmarshall** [comment]
After discovering the hack, I noticed that the "easiest" solution is to add the check for authentication back in. I don't have time to dig into the (surprising) coupling of authorization and geo replication, so I created an issue https://github.com/apache/pulsar/issues/20023.

**Comment by michaeljmarshall** [comment]
> @michaeljmarshall Is it possible to add a test to make we will not be impacted in the future?

@codelipenghui - given that it made a test fail, I think we're "covered" because I updated the test. I think the more ideal solution will be to refactor this logic so that it is in the `AuthorizationService`.

**Comment by michaeljmarshall** [comment]
I'll take care of cherry picking this later tonight. There are some merge conflicts to resolve.

**Comment by michaeljmarshall** [comment]
Cherry picking complete.

**Pull request merged**
