### PR TITLE
[Issue 14013] RestAPI - Make ``getPartitionedTopicList`` to async.

### PR DESCRIPTION
**Pull request by mattisonchao**
Master Issue: #14013

### Motivation

Make Rest API ``getPartitionedTopicList`` to async and to refactor code style to make it more clear.

### Modifications

- Make the ``getPartitionedTopicList`` method from sync to async.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

none.

Need to update docs? 

- [x] `no-need-doc`

### CODE REVIEW

**Comment by mattisonchao** [comment]
@Anonymitaet  
Sorry, I got the wrong tag here.
please help me to remove the ``doc-required`` tag.

**Comment by mattisonchao** [comment]
@codelipenghui  @liudezhi2098  @Technoboy-  @Jason918  @nodece  PTAL :-)

**Review by Technoboy- — COMMENTED** [review]
No need the last `{}`

**Pull request closed without merging**
