### PR TITLE
[feat][broker][PIP-278] Support pluggable topic compaction service

### PR DESCRIPTION
**Pull request by coderzc**
PIP: #20624 

### Motivation

Support pluggable topic compaction service

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by mattisonchao** [comment]
Could you please split this PR into multiple?

**Comment by coderzc** [comment]
> Could you please split this PR into multiple?

This is a bit difficult. If only submit part modifications, the CI will not be able to pass.

In fact, most of them are modifications to test to be compatible with the new interface.

**Comment by mattisonchao** [comment]
Honestly, It's tough for other committers to review this whole bunch. Maybe we can add some interface or other new things first? :)

**Comment by coderzc** [comment]
> Honestly, It's tough for other committers to review this whole bunch. Maybe we can add some interface or other new things first? :)

Ok, I push a new PR only include the new topic compaction interface and pulsar implementation. PR: https://github.com/apache/pulsar/pull/20645

**Pull request closed without merging**
