### PR TITLE
 Fix Get Function Cluster in Master Docs

### PR DESCRIPTION
**Pull request by k2la**
### Motivation

About #2948 , fix path in master docs.

### Modifications
Change `curl -s http://localhost:8080/admin/v2/functions/cluster` to `curl -s http://localhost:8080/admin/v2/worker/cluster`

### CODE REVIEW

**Comment by k2la** [comment]
run integration tests

**Comment by k2la** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by k2la** [comment]
run integration tests

**Comment by merlimat** [comment]
Integration tests should be more stable in master now. If it doesn't pass it might be worth to just merge or rebase with master

**Pull request merged**
