### PR TITLE
[improve][build] Remove broker-shaded artifacts

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

The `pulsar-broker-shaded` is creating a huge jar with all broker deps. This was meant as a way to avoid dependencies conflicts when embedding Pulsar broker into an existing application. As far as I know, this is not currently used and it takes significant time and resources to assemble during the build.

I propose to remove for now, we can always bring it back when needed.

(cc/ @eolivelli just in case you happen to use this)

- [x] `doc-not-needed`

### CODE REVIEW

**Comment by sijie** [comment]
+1 to @rdhabalia 's comment. I think broker-shaded was introduced for addressing some requirements from slack users. it is not like the other shaded modules I removed in #3559

**Comment by merlimat** [comment]
I know where it was coming from, though I think it was not used in the end. I know this is different from the 2 other shaded modules, but still a big time/resource sink to build each time, if there's no need for ti. Let's move this for 2.4 to have more time for gathering feedback.

**Comment by eolivelli** [comment]
I suggest not to port this to 2.4 line but to ship it only woth a major version

**Comment by codelipenghui** [comment]
@merlimat Is this PR need to onboard the 2.6.0 release? or we can move it to 2.7.0?

**Comment by codelipenghui** [comment]
move to 2.7.0

**Comment by eolivelli** [comment]
can you please rebase ?
this patch was approved, it is good to commit it now for 2.9

**Review by tisonkun — APPROVED** [review]
Rebased. If it's good to go, we can keep an eye on this PR :)

**Comment by merlimat** [comment]
🎉🎉🎉 Thanks @tisonkun for merging this 3 years old PR! :)

**Review by michaeljmarshall — APPROVED** [review]

**Pull request merged**
