### PR TITLE
[DOCS] Restore format

### PR DESCRIPTION
**Pull request by sijia-w**
Restore the incorrectly changed format in https://github.com/apache/pulsar/pull/8920/files.

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by Jennifer88huang — COMMENTED** [review]
@sijia-w I'm afraid the restore is not totally correct. 
@RobertIndie fixed the token issues in https://github.com/apache/pulsar/pull/9313 for the upcoming 2.8.0 release. As discussed and confirmed in https://github.com/apache/pulsar/issues/9187, except token, others support JSON format before 2.7.0 release. So you do not need to restore other changes (except token) in this PR.  You can double confirm it with @RobertIndie on it.

**Comment by sijia-w** [comment]
@Jennifer88huang Does it work in the restored / updated version in this pr? If it does work in both ways, then we can keep it.

**Comment by RobertIndie** [comment]
> @sijia-w Thank you for your efforts. I'm afraid the restore is not totally correct.
> @RobertIndie fixed the token issues in #9313 for the upcoming 2.8.0 release. As discussed and confirmed in #9187, except token, others support JSON format before 2.7.0 release. So you do not need to restore other changes (except token) in this PR. You can double confirm it with @RobertIndie on it.

As discussed with @sijia-w , I think it is better to change other authentication parameters to `string` type. While other authentication supports the JSON format in more recent versions, they may not have been supported in the early version.

**Review by RobertIndie — APPROVED** [review]
LGTM

**Review by Jennifer88huang — APPROVED** [review]

**Pull request merged**
