### PR TITLE
[Pulsar IO] Develop Huawei Cloud DIS connector

### PR DESCRIPTION
**Pull request by Shoothzj**
### Motivation

We are trying to use **Pulsar IO** connector. The **DIS** is one of Sink my business must supported.

### Modifications

Add a new **Pulsar IO** module DIS.

### Verifying this change
- Fill the Junit test for config file.
- Test the E2E ability manually.

### Documentation

  - Does this pull request introduce a new feature? yes
  - If yes, how is the feature documented? docs

### CODE REVIEW

**Comment by Shoothzj** [comment]
For the merge policy, I close this PR, I will commit these codes to https://github.com/streamnative/pulsar-io-huawei-dis

**Comment by eolivelli** [comment]
Can you please explain better this problem with 'merge policy' ?

**Comment by Shoothzj** [comment]
> Can you please explain better this problem with 'merge policy' ?

@codelipenghui told me that the IO part is going to split with Pulsar main Repo, currently it's not recommend to merge to main repo. I think after the split, i will merge to PulsarIO repo.

**Comment by eolivelli** [comment]
Personally I believe that we can accept this code here and when we will split the repo the code will go into the new repo for connectors.

That said, it is your decision.
As ASF project we are happy to see more integrations

**Comment by Shoothzj** [comment]
> Personally I believe that we can accept this code here and when we will split the repo the code will go into the new repo for connectors.
> 
> That said, it is your decision.
> As ASF project we are happy to see more integrations

I want to merge code to **Pulsar IO** module too.  @sijie says growing connectors brings difficulty for pulsar project build、tests、release. He recommends for two way to share project. The other way is waiting for him to split the code. Should we discuss with sijie?

**Comment by eolivelli** [comment]
Can you please open a discussion on dev@pulsar.apache.org?

That's the place where we discuss about these topics.

BTW thanks for this awesome work and for the will to share it with the community

**Comment by sijie** [comment]
@Shoothzj thank you for the great work! 

My take on the connectors - I would recommend avoiding adding more connectors to the Pulsar repo. It becomes really hard to maintain the quality of the connectors. It is a similar situation in other projects like Flink.

I’d recommend the author of the connector maintaining the connector themselves. In this way, we can scale out the Pulsar ecosystem. 

Where to host the connector code is totally up to the author. It can be under his personal GitHub account. If you want to share the connector with the  broader ecosystem, you are welcome to add your connector to https://hub.streamnative.io

**Comment by Shoothzj** [comment]
> @Shoothzj thank you for the great work!
> 
> My take on the connectors - I would recommend avoiding adding more connectors to the Pulsar repo. It becomes really hard to maintain the quality of the connectors. It is a similar situation in other projects like Flink.
> 
> I’d recommend the author of the connector maintaining the connector themselves. In this way, we can scale out the Pulsar ecosystem.
> 
> Where to host the connector code is totally up to the author. It can be under his personal GitHub account. If you want to share the connector with the broader ecosystem, you are welcome to add your connector to https://hub.streamnative.io

@sijie 
I think you make sense, connectors are hard to maintain the quality. Let me open a discussion, let the connector merge policy come to a conclusion.

By the way, if we decide not to merge to Pulsar repo. I want to maintain this connector in StreamNative repo, I think it's better than maintain on personal repos.

Thanks.

**Pull request closed without merging**
