### PR TITLE
[improve][test] Upgrade awaitility to 4.2.0

### PR DESCRIPTION
**Pull request by Demogorgon314**
### Motivation

The awaitility version 4.0.3 is outdated. Upgrade to the latest stable 4.2.0 version.

### Modifications

Upgrade awaitility to 4.2.0

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Review by nicoloboschi — APPROVED** [review]

**Review by Jason918 — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
Lgtm

**Review by RobertIndie — APPROVED** [review]

**Review by Shoothzj — APPROVED** [review]

**Comment by lhotari** [comment]
> /pulsarbot rerun-failure-checks

There's no need to re-run. Please read this information about failed PR checks: https://lists.apache.org/thread/60x7sqg2p4mlssj5jtow6zwq3jksf6w3
It might appear that "/pulsarbot rerun-failure-checks" is broken. That's not the case. The email thread explains it.

**Review by lhotari — APPROVED** [review]

**Pull request merged**
