### PR TITLE
support shrink in ConcurrentLongHashMap

### PR DESCRIPTION
**Pull request by lordcheng10**
### Motivation
support shrink in ConcurrentLongHashMap.

This feature was introduced in bookkeeper's PR：https://github.com/apache/bookkeeper/pull/3061

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Comment by lordcheng10** [comment]
@eolivelli @merlimat PTAL,thanks!

**Review by codelipenghui — APPROVED** [review]

**Review by nicoloboschi — APPROVED** [review]
LGTM

**Review by Jason918 — APPROVED** [review]

**Pull request merged**
