### PR TITLE
Revert "[improve][ci] Add workflow for python local install (#17232)"

### LINKED ISSUE #17430: ci-python-build-3.9-client.yaml failed to run
This section is incorrect and produces:

```
a step cannot have both the `uses` and `run` keys
```

See https://github.com/apache/pulsar/actions/runs/2978090895.

I guess it will cause all PRs to fail. Please take a look @nodece @RobertIndie.

Weird why it's not failed on PR CI workflows.

_Originally posted by @tisonkun in https://github.com/apache/pulsar/pull/17232#discussion_r961497433_

### PR DESCRIPTION
**Pull request by tisonkun**
This closes #17430.

- [x] `doc-not-needed`

### CODE REVIEW

**Review by MarvinCai — APPROVED** [review]

**Review by nodece — APPROVED** [review]

**Review by RobertIndie — APPROVED** [review]

**Comment by tisonkun** [comment]
@nodece still fail. We may first revert these new steps and re dev again.

**Comment by tisonkun** [comment]
All tests passed. Finally ><

ping @nodece @MarvinCai @RobertIndie

**Pull request merged**
