### PR TITLE
Minor typo

### PR DESCRIPTION
**Pull request by prabhatjha**
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes : N/A

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue:  N/A 

### Motivation

*Minor grammar fix

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts: No

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by Anonymitaet — CHANGES_REQUESTED** [review]
Many thanks for your contribution. Would you like to fix the same issue in other doc versions? Thanks.

image

**Comment by prabhatjha** [comment]
Let me include more doc fixes in another PR. Do the fixes have to go in previous branches or can it be on the latest only? I feel like it's not worth the effort going back so many versions.

**Comment by Anonymitaet** [comment]
@prabhatjha thanks for your contribution. It is not a big effort, just needs a batch search and replacement. 😀

**Comment by Anonymitaet** [comment]
@prabhatjha Thanks for your contribution. Could you please update versioned docs [here](https://github.com/apache/pulsar/tree/master/site2/website/versioned_docs) in this PR, thanks.

**Comment by prabhatjha** [comment]
Unfortunately I don't have bandwidth. Please feel free to take over this PR or close this. Thank you.

**Comment by Anonymitaet** [comment]
@prabhatjha thanks for your reply. I've fixed this issue in https://github.com/apache/pulsar/pull/11744, so I close this PR.

**Pull request closed without merging**
