### PR TITLE
[fix] prevent offload non-persistent or system topics

### PR DESCRIPTION
**Pull request by chunxiaozheng**
When ledger is closed, do not offload when this ledger is non-persistent or system topics.

### Motivation

When ledger is closed, do not offload when this ledger is non-persistent or system topics.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by dao-jun** [comment]
NonPersistentTopic has no ledgers to persist messages, so we don't need to care about it.
About SystemTopic, I remember there is a PR to fix it

**Comment by dao-jun** [comment]
Got it, https://github.com/apache/pulsar/pull/22497

**Comment by chunxiaozheng** [comment]
> Got it, #22497

Thanks! But I see the #22497 did not merge. In our scenario, due to system topic triggered offload, many exceptions were printed in the log, so I submitted the above modifications

**Comment by dao-jun** [comment]
> > Got it, #22497
> 
> Thanks! But I see the #22497 did not merge. In our scenario, due to system topic triggered offload, many exceptions were printed in the log, so I submitted the above modifications

let me ask him, if there is no other problems, I'll reopen and merge it

**Comment by chunxiaozheng** [comment]
> > > Got it, #22497
> > 
> > 
> > Thanks! But I see the #22497 did not merge. In our scenario, due to system topic triggered offload, many exceptions were printed in the log, so I submitted the above modifications
> 
> let me ask him, if there is no other problems, I'll reopen and merge it

Thanks！

**Comment by dao-jun** [comment]
@chunxiaozheng https://github.com/apache/pulsar/pull/22497 merged, let's close this PR

**Comment by chunxiaozheng** [comment]
> @chunxiaozheng #22497 merged, let's close this PR

okay，thanks！

**Pull request closed without merging**
