### PR TITLE
[fix][broker] In the trimDeletedEntries method, release the removed entry

### PR DESCRIPTION
**Pull request by lordcheng10**
### Motivation
In the trimDeletedEntries method, the removed entry is not released：
https://github.com/apache/pulsar/blob/2e878e8aac869bc4500e9d32e5c78bfc5c86614b/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L3307-L3310

https://github.com/apache/pulsar/blob/2e878e8aac869bc4500e9d32e5c78bfc5c86614b/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java#L582-L585

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/lordcheng10/pulsar/pull/38

### CODE REVIEW

**Comment by lordcheng10** [comment]
@codelipenghui @Jason918 PTAL,thanks!

**Review by codelipenghui — APPROVED** [review]
Nice catch!

**Comment by lordcheng10** [comment]
@AnonHxy @Jason918 @HQebupt PTAL,thanks!

**Review by coderzc — APPROVED** [review]

**Comment by lordcheng10** [comment]
@Technoboy- PTAL,thanks!

**Comment by coderzc** [comment]
> /pulsarbot run-failure-checks

`Pulsar CI Flaky` is not necessary.

**Pull request merged**
