### PR TITLE
 [bookie] enable bookie http server

### PR DESCRIPTION
**Pull request by sijie**
*Motivation*

Currently bookie http server is disabled by default. Setting the http server port
to 8000 and include a vertx http server implementation to prepare enabling http server
on bookie.

*NOTES*

Currently bookkeeper only provides two http server bindings, one is vertx, the other one
is finagle server binding. both are netty based http server. so technically it doesn't
introduce additional dependencies. However if people prefers a jetty implementation,
I can add a jetty binding in bookkeeper.

### CODE REVIEW

**Comment by sijie** [comment]
This change is based on #3061 .

**Comment by sijie** [comment]
currently the setting is still disabled in the config. we will turn it on when 4.7.3 is released (due to apache/bookkeeper#1546)

**Comment by jiazhai** [comment]
retest this please

**Comment by sijie** [comment]
run cpp tests 
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run cpp tests
run integration tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Pull request merged**
