### PR TITLE
[fix][test] Replace usage of org.testcontainers.shaded.* classes in tests

### PR DESCRIPTION
**Pull request by lhotari**
### Motivation

`org.testcontainers.shaded.*` classes shouldn't be used. 

### Modifications

- replace usage of org.testcontainers.shaded.* classes in tests with the correct imports.
- organize imports

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by poorbarcode — APPROVED** [review]

**Review by Demogorgon314 — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]
Thanks!

**Review by nicoloboschi — COMMENTED** [review]
What about adding a new checkstyle rule to avoid the import of

org.testcontainers.shaded ?

**Comment by lhotari** [comment]
> What about adding a new checkstyle rule to avoid the import of
> 
> org.testcontainers.shaded ?

@nicoloboschi We have already #18113 and I also tried https://github.com/lhotari/pulsar/commit/03624d2a since there was a comment somewhere that IllegalImport check doesn't apply to class imports.
It appears that we don't run checkstyle for tests so that's why it doesn't work.

**Comment by lhotari** [comment]
Found it. Most checks are disabled for tests: https://github.com/apache/pulsar/blob/82237d3684fe506bcb6426b3b23f413422e6e4fb/buildtools/src/main/resources/pulsar/suppressions.xml#L41

**Comment by lhotari** [comment]
@nicoloboschi The checkstyle rule is now active and will prevent importing org.testcontainers.shaded.* classes in the future.

**Comment by tisonkun** [comment]
thought - I'd actually prefer to use some technologies that can automatically format code like spotless (see [FLINK-20651](https://issues.apache.org/jira/browse/FLINK-20651)), but it can introduce a big diff and the maven plugin cannot cover "forbid import pattern" pattern (while the Gralde one can, I suppose it's technically possible upstream to support for maven plugin also).

**Pull request merged**
