### PR TITLE
[fix][python]Fix generated Python protobuf code not compatible with latest protobuf package

### PR DESCRIPTION
**Pull request by cbornet**
### Motivation
Protobuf latest 4.21 version broke compatibility with files generated with protoc < 3.19
As a result all current CI tests fail.
See https://developers.google.com/protocol-buffers/docs/news/2022-05-06

### Modifications
This fix downgrades protobuf python package to 3.20.1.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

no

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
fix
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by BewareMyPower — APPROVED** [review]

**Review by Demogorgon314 — APPROVED** [review]

**Review by hangc0276 — APPROVED** [review]
Great job!

**Review by zymap — CHANGES_REQUESTED** [review]
Shouldn't we regenerate the code to support the latest protobuf?

**Comment by lhotari** [comment]
> Shouldn't we regenerate the code to support the latest protobuf?

@zymap I suppose you are referring to #15827. That makes sense. However, this PR doesn't conflict with that and there's no reason to block this PR with requesting changes. Let's keep the PRs separate.

**Review by lhotari — APPROVED** [review]

**Review by zymap — APPROVED** [review]

**Comment by zymap** [comment]
Make sense to me

**Comment by lhotari** [comment]
I added another commit to this PR to limit the version to 3.20.* in setup.py for the Pulsar Python client's dependencies. This would be a useful fix also for maintenance branches.

**Review by eolivelli — APPROVED** [review]
Great catch!

**Comment by lhotari** [comment]
@zymap Why did you restart all tests and not just the failed ones?

**Review by codelipenghui — APPROVED** [review]
Nice fix!

**Pull request merged**
