### PR TITLE
[pulsar-sql]deserialize the avro schema data by correct reader

### PR DESCRIPTION
**Pull request by congbobo184**
#4607
Implement the correct avro schema reader to deserialize the message

### Motivation
Implement the correct avro schema reader to deserialize the message

### Verifying this change
Add the test for this

Does this pull request potentially affect one of the following parts:
If yes was chosen, please highlight the changes

Dependencies (does it add or upgrade a dependency): (no)
The public API: (no)
The schema: (no)
The default values of configurations: (no)
The wire protocol: (no)
The rest endpoints: (no)
The admin cli options: (no)
Anything that affects deployment: (no)

### Documentation
Does this pull request introduce a new feature? (yes / no)
If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
If a feature is not applicable for documentation, explain why?
If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by congbobo184** [comment]
run cpp tests

**Comment by congbobo184** [comment]
run cpp tests

**Comment by congbobo184** [comment]
run java8 tests

**Comment by congbobo184** [comment]
run java8 tests

**Comment by congbobo184** [comment]
> @ congbobo184我的感觉是我们应该改为直接使用Pulsar的架构。因为那里的多模式版本控制得到了很好的处理。从长远来看，维护重复代码将变得非常困难。
> 
> 在[＃4151中，](https://github.com/apache/pulsar/pull/4151)我添加了对原始模式的支持。所以我认为我们应该在presto集成中使用schema。您可以查看此文件https://github.com/apache/pulsar/pull/4151/files#diff-94529d7fb95125ffc87591a5fa87ad80
> 
> 如果你有时间并愿意为pulsar sql做出贡献，也许你可以选择[＃4151](https://github.com/apache/pulsar/pull/4151)，我们可以先合并。之后，我们可以在此拉取请求中更改为使用AvroSchema。

@sijie I have read #4151, I understand what you mean. This PR can be merged first. After that I am making a big change

**Comment by congbobo184** [comment]
> @congbobo184 my feeling is that we should just change to use Pulsar's schema directly. because the multi schema versioning has been well handled there. It will become really hard to maintain duplicated code in the long term.
> 
> In #4151 I am adding supports for primitive schemas. so I think we should move to use schema in presto integration. You can check this file https://github.com/apache/pulsar/pull/4151/files#diff-94529d7fb95125ffc87591a5fa87ad80
> 
> If you have time and are willing to contribute to pulsar sql, maybe you can pick up #4151 and we can merge that first. After that, we can change to use AvroSchema in this pull request.

@sijie I have read #4151, I understand what you mean. This PR can be merged first. After that I am making a big change

**Comment by sijie** [comment]
@congbobo184 okay I will review this PR.

**Comment by congbobo184** [comment]
> @congbobo184 okay I will review this PR.

I will close this PR and then come up with a new PR similar to #4151

**Comment by sijie** [comment]
@congbobo184 okay. thanks

**Pull request closed without merging**
