### PR TITLE
[fix][test] : PulsarStandaloneTest.testMetadataInitialization

### LINKED ISSUE #19838: Flaky-test: PulsarStandaloneTest.testMetadataInitialization
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

<No failure observed running with Pulsar CI Github action>

### Exception stacktrace

**Issue:**
 
- Running test-case locally failed with below stack-trace.

```
org.apache.pulsar.broker.PulsarServerException: java.lang.IllegalStateException: Unable to read VM NIC speed. You must set [loadBalancerOverrideBrokerNicSpeedGbps] to override it when load balancer is enabled.

	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:919)
	at org.apache.pulsar.PulsarStandalone.start(PulsarStandalone.java:349)
	at org.apache.pulsar.PulsarStandaloneTest.testMetadataInitialization(PulsarStandaloneTest.java:94)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:829)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.IllegalStateException: Unable to read VM NIC speed. You must set [loadBalancerOverrideBrokerNicSpeedGbps] to override it when load balancer is enabled.
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:724)
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by niharrathod**
Fixes #19838

### Motivation

- flaky test : PulsarStandaloneTest.testMetadataInitialization. Test failure can only be observed if test-suit is running on machine/VM where nic speed is not set and PulsarService starts with broker conf where 'loadBalancerOverrideBrokerNicSpeedGbps' value is not set. 
- Pulsar CI Github action is running on VM where nic speed is set and test run is able to read nic speed of a VM where test-suite is running.

### Modifications

1. set 'loadBalancerOverrideBrokerNicSpeedGbps' config for PulsarStandAloneTest Broker.

### Verifying this change

This change is already covered by existing tests.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [X] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by niharrathod** [comment]
I have raise same PR on my personal fork([Link](https://github.com/niharrathod/pulsar/pull/1)), but it didn't start CI process. And as per PR template, this PR CI is waiting on personal forked PR CI to be completed. 

Am I missing something?

**Comment by niharrathod** [comment]
- Pulsar CI Flaky/Flaky tests suite failed : 
    Reason : Codecov failed to upload report, all three attempt failed. Can we rerun failed jobs?
 
- Pulsar CI / Unit - Brokers - Broker Group 1 failed :  
   Reason : `org.apache.pulsar.broker.stats.MetadataStoreStatsTest.testMetadataStoreStats` Test failed. Issue already exist : 
   [#19456](https://github.com/apache/pulsar/issues/19456)

**Comment by niharrathod** [comment]
Found a PR(#19828) to unblock. Thanks @Technoboy-.

@Technoboy-  : CI workflow is blocked for approval. Could you please approve?

**Review by tisonkun — APPROVED** [review]

**Comment by tisonkun** [comment]
Thanks for your contribution @niharrathod!

**Comment by niharrathod** [comment]
@tisonkun : Thanks

**Pull request merged**
