### PR TITLE
PIP-45: Allow to start bookie with Pulsar metadata store backend

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

We need to add system properties (`bookkeeper.metadata.{bookie,client}.drivers`)for the Bookie and BookieShell commands to discover the BK bridge to the Pulsar metadata provider. 

This is what will allow to configure bk metadataUri such as `metadata-store:zk:my-zk1:2181` or `metadata-store:etcd:http://my-etcd:2379`.

### CODE REVIEW

**Comment by Shoothzj** [comment]
@merlimat Could you pull the master code, in case there are any check-style violations

**Comment by Anonymitaet** [comment]
@merlimat since this is a new feature, so we need to update docs？

**Review by liangyuanpeng — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
Lgtm

**Comment by Anonymitaet** [comment]
Hi @momo-jun has doc been updated for this PR? Thanks

**Comment by momo-jun** [comment]
> Hi @momo-jun has doc been updated for this PR? Thanks

Yes, @RobertIndie added docs for this PR through #13921.

**Pull request merged**
