### PR TITLE
Replace newInstance() with getDeclaredConstructor().newInstance()

### PR DESCRIPTION
**Pull request by yuruguo**
### Motivation
The method `newInstance()` is deprecated in Class since java9, and it is recommended to use `getDeclaredConstructor().newInstance()` instead. As follow:
```java
    /**
     * Creates a new instance of the class represented by this {@code Class}
     * object.  The class is instantiated as if by a {@code new}
     * expression with an empty argument list.  The class is initialized if it
     * has not already been initialized.
     *
     * @deprecated This method propagates any exception thrown by the
     * nullary constructor, including a checked exception.  Use of
     * this method effectively bypasses the compile-time exception
     * checking that would otherwise be performed by the compiler.
     * The {@link
     * java.lang.reflect.Constructor#newInstance(java.lang.Object...)
     * Constructor.newInstance} method avoids this problem by wrapping
     * any exception thrown by the constructor in a (checked) {@link
     * java.lang.reflect.InvocationTargetException}.
     *
     * <p>The call
     *
     * <pre>{@code
     * clazz.newInstance()
     * }</pre>
     *
     * can be replaced by
     *
     * <pre>{@code
     * clazz.getDeclaredConstructor().newInstance()
     * }</pre>
     *
     * The latter sequence of calls is inferred to be able to throw
     * the additional exception types {@link
     * InvocationTargetException} and {@link
     * NoSuchMethodException}. Both of these exception types are
     * subclasses of {@link ReflectiveOperationException}.
     *
     * @return  a newly allocated instance of the class represented by this
     *          object.
     * @throws  IllegalAccessException  if the class or its nullary
     *          constructor is not accessible.
     * @throws  InstantiationException
     *          if this {@code Class} represents an abstract class,
     *          an interface, an array class, a primitive type, or void;
     *          or if the class has no nullary constructor;
     *          or if the instantiation fails for some other reason.
     * @throws  ExceptionInInitializerError if the initialization
     *          provoked by this method fails.
     * @throws  SecurityException
     *          If a security manager, <i>s</i>, is present and
     *          the caller's class loader is not the same as or an
     *          ancestor of the class loader for the current class and
     *          invocation of {@link SecurityManager#checkPackageAccess
     *          s.checkPackageAccess()} denies access to the package
     *          of this class.
     */
    @CallerSensitive
    @Deprecated(since="9")
    public T newInstance()
        throws InstantiationException, IllegalAccessException
```

### Modifications
- Use `getDeclaredConstructor().newInstance()` instead of new a Clazz.
- I updated all uses of `clazz.newInstance()`.

### Documentation
- no-need-doc

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
Lgtm 

Thanks

**Comment by eolivelli** [comment]
Please check ci

**Comment by yuruguo** [comment]
> Please check ci

ok, i will  format code.

**Comment by yuruguo** [comment]
/pulsarbot run-failure
-checks

**Comment by yuruguo** [comment]
@merlimat @lhotari @sijie @codelipenghui @hangc0276 PTAL

**Review by merlimat — APPROVED** [review]

**Pull request merged**
