### PR TITLE
Fix Javadoc comments in the pulsar-io-core module

### PR DESCRIPTION
**Pull request by vzhikserg**
### Modifications

The modifications were done only in the pulsar-io-core module:

- Add missing Javadoc comments
- Remove outdated parameters in Javadoc
- Format some of the comments according to the defined guidelines

### CODE REVIEW

**Comment by sijie** [comment]
run integration tests

**Comment by vzhikserg** [comment]
run integration tests

**Comment by vzhikserg** [comment]
run integration tests

**Comment by vzhikserg** [comment]
run integration tests

**Comment by codelipenghui** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by vzhikserg** [comment]
run integration tests

**Comment by Jennifer88huang** [comment]
run integration tests

**Pull request merged**
