### PR TITLE
[Issue 11440]. Add complete metadata for admin.topics().examineMessages

### LINKED ISSUE #11440: Incomplete metadata in MessageImpl return by admin.topics().examineMessage()
**Is your enhancement request related to a problem? Please describe.**
We can get MessageImpl object using `org.apache.pulsar.client.admin.Topics#examineMessage`,
but it has Incomplete metadata , e.g. keys.
Same things happens to `getMessageByID` and `peekNthMessage`, since they use the same `generateResponseWithEntry` to serialize the message, And only a few metadata entries are added to the response headers.

**Describe the solution you'd like**
Add all the metadata to the response headers. 

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Jason918**
Fixes #11440

### Motivation

see issue 11440

### Modifications

Add all the other non-empty meta data fields in http response headers in `org.apache.pulsar.broker.admin.impl.PersistentTopicsBase#generateResponseWithEntry`. For fields with byte[] type, base64 is used for serialization and deserialization.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change added tests and can be verified as follows:

`org.apache.pulsar.broker.admin.PersistentTopicsTest#testExamineMessageMetadata`

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by sijie — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@Jason918 Please check the checkstyle issue 

```
Error:  src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java:[111,44] (whitespace) WhitespaceAround: '=' is not preceded with whitespace.
Error:  src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java:[118,37] (whitespace) WhitespaceAround: '=' is not preceded with whitespace.
```

**Comment by Jason918** [comment]
> @Jason918 Please check the checkstyle issue
> 
> ```
> Error:  src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java:[111,44] (whitespace) WhitespaceAround: '=' is not preceded with whitespace.
> Error:  src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java:[118,37] (whitespace) WhitespaceAround: '=' is not preceded with whitespace.
> ```
Fixed it. 
Sorry for that .
There seems a lot flaky tests lately. @_@

**Comment by Anonymitaet** [comment]
@Jason918 thanks for your great work. Would you like to add docs accordingly? Then you can ping me to review, thanks

**Comment by Jason918** [comment]
> @Jason918 thanks for your great work. Would you like to add docs accordingly? Then you can ping me to review, thanks

@Anonymitaet It seems there're no user docs for examine-message cmd. So I added new section for it. Please check it out in my last commit.

**Pull request merged**
