### PR TITLE
[Java Client] Remove unnecessary synchronization; Simplify initialization

### PR DESCRIPTION
**Pull request by michaeljmarshall**
### Motivation

In https://github.com/apache/pulsar/pull/8051, the `producers` and `consumers` sets in the `PulsarClientImpl` were updated to be backed by a concurrent hash map. Therefore, there is no need to synchronize updates to the map or the counting of the size of the map.

This update will help improve shutdown times when there are many producers/consumers.

### Modifications

* Update `cleanupProducer` and `cleanupConsumer` to remove the unnecessary `synchronize` on each set update
* Update `producersCount` and `consumersCount` to remove the unnecessary `synchronize` on each set count
* Update the initialization of each set to make it clear that these sets are intentionally thread safe data structures

### Verifying this change

This is a trivial change. Since we switched to a concurrent data structure in this PR, https://github.com/apache/pulsar/pull/8051, it is safe to remove the `synchronize` blocks around the set updates. It is also safe to assume that getting the count of elements in the set will be the "latest" number of elements.

### Does this pull request potentially affect one of the following parts:

This change does not affect any public behavior. It should improve shutdown time of the Java client in cases where there are many producers or consumers.

### Documentation

This is a change to an implementation detail within the client. There is no need to update documentation.

### CODE REVIEW

**Comment by michaeljmarshall** [comment]
@Technoboy- - PTAL

**Review by Technoboy- — APPROVED** [review]
LGTM

**Review by merlimat — APPROVED** [review]

**Pull request merged**
