### PR TITLE
PIP-62: Delete pulsar adapters

### PR DESCRIPTION
**Pull request by sijie**
Delete the pulsar adapter modules because they are already moved to https://github.com/apache/pulsar-adapters

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by jiazhai — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Comment by lhotari** [comment]
I created #8511 to remove some remaining bits of pulsar-adapters.

**Pull request merged**
