### PR TITLE
[issue 3939] [pulsar-flink]: Allow client authentication from pulsar-flink package

### LINKED ISSUE #3939: Allow client authentication from pulsar-flink package
**Is your feature request related to a problem? Please describe.**
We recently enabled JWT based authentication on our brokers. Though the native pulsar client allows setting tokens in the client builder, the pulsar-flink connector does not provide a way to provide authentication token to the pulsar client used internally.

**Describe the solution you'd like**
Pulsar-flink module should accept auth token / provider. Further when building the pulsar client:
1. Pulsar-flink should check if auth is enabled.
2. If yes. set the same when building pulsar-client instance.

**Describe alternatives you've considered**
There is no alternative. It is not possible to provide auth info to pulsar-flink.

**Additional context**
Here is how the the pulsar-flink module builds pulsar-client:
`PulsarClient client = PulsarClient.builder().serviceUrl(serviceUrl).build();`

### PR DESCRIPTION
**Pull request by shiv4289**
### Problem:
pulsar-flink module (aka flink connector) internally uses pulsar-client. Though the pulsar client allows setting tokens in the client builder, the flink connector does not provide a way to pass authentication token to the pulsar client it uses internally.

### Solution:
Accept authentication information as an input in pulsar-flink module. Pass this authentication information to pulsar-client.

<--
### Contribution Checklist

Fixes #3939 

### Motivation

We recently enabled JWT based authentication on our brokers. Though the native pulsar client allows setting tokens in the client builder, the pulsar-flink connector does not provide a way to pass authentication token to the pulsar client initialised internally.

### Modifications

pulsar-flink takes auth argument and passes it to pulsar client, set new AuthenticationDisabled() to disable.

### Verifying this change

This change is already covered by existing tests, such as *(PulsarAvroTableSinkTest.java
PulsarJsonTableSinkTest.java)*.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes) : changed constructor signatures in pulsar-flink module
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (JavaDocs)

### CODE REVIEW

**Comment by sijie** [comment]
run cpp tests
run integration tests

**Comment by jiazhai** [comment]
retest this please

**Comment by sijie** [comment]
run cpp tests
run integration tests

**Comment by shiv4289** [comment]
> retest this please

Thanks @jiazhai . There were examples in the base pulsar directory which i hadn't caught in the first version because I was running all the tests from pulsar-flink directory 

All checks have passed now 👍

**Comment by shiv4289** [comment]
run java8 tests

**Comment by shiv4289** [comment]
@sijie @jiazhai It seems the master branch is unstable? pulsar-broker module fails and then the following pulsar-flink tests are skipped..

**Comment by sijie** [comment]
@shiv4289 yeah there are a few flaky tests which tends to fail randomly at Apache Jenkins. :(

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
@shiv4289 can you rebase to latest master? :)

**Comment by shiv4289** [comment]
> @shiv4289 can you rebase to latest master? :)

Done :-)

**Pull request merged**
