### PR TITLE
move exclamation.zip location

### PR DESCRIPTION
**Pull request by jerrypeng**
### Motivation

Current location of test python function zip package is inappropriate. 

Also removed requirements.txt file from exclamation.zip

### CODE REVIEW

**Comment by sijie** [comment]
run integration tests

**Comment by merlimat** [comment]
@jerrypeng We should also remove the zip file from sources before 2.3 release. The zip should be constructed at build time

**Comment by merlimat** [comment]
Also, please make sure the zip doesn't include the `requirements.txt` per my other comment: https://github.com/apache/pulsar/pull/2965#issuecomment-437273936

**Comment by jerrypeng** [comment]
@merlimat as I mentioned under the "Motivation" section for this PR, I already removed the requirements.txt from the zip file

**Comment by merlimat** [comment]
> @merlimat as I mentioned under the "Motivation" section for this PR, I already removed the requirements.txt from the zip file

 OK :) missed that

**Comment by jerrypeng** [comment]
@merlimat I will submit another PR to construct the zip programmatically

**Pull request merged**
