### PR TITLE
[Doc] Add notes for S3 offloading configuration

### PR DESCRIPTION
**Pull request by Anonymitaet**
This PR adds a workaround for https://github.com/apache/pulsar/issues/9084

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@Renkai @addisonj could you please help review? Many thanks

**Comment by jiazhai** [comment]
also ping @gaoran10 to help review.

**Comment by Renkai** [comment]
Maybe we should guide users on how to set permission, too. https://docs.aws.amazon.com/AmazonS3/latest/dev/using-with-s3-actions.html

**Comment by Anonymitaet** [comment]
@Renkai thanks for your suggestion, I've added the reference link to the doc, PTAL.

**Review by Renkai — APPROVED** [review]

**Review by Huanli-Meng — APPROVED** [review]

**Review by Jennifer88huang — APPROVED** [review]

**Review by sijie — APPROVED** [review]

**Pull request merged**
