### PR TITLE
[Broker] Fixed the incorrectly used logger.

### PR DESCRIPTION
**Pull request by mattisonchao**
### Motivation

I found some incorrectly used logger.

### Modifications

- Fixed the incorrectly used logger in the broker module.

### CODE REVIEW

**Comment by mattisonchao** [comment]
@martint @lhotari If you have time, can you help me review the code? : )

**Comment by lhotari** [comment]
@mattisonchao very useful. 

If you'd like to check all logger usages, there's an error prone plugin https://github.com/KengoTODA/errorprone-slf4j which has been configured in Pulsar's pom.xml . It was added in #8879 . The PR describes how it can be run.

**Comment by mattisonchao** [comment]
@lhotari I will do that, thanks to you ~

**Review by merlimat — APPROVED** [review]

**Review by sijie — APPROVED** [review]

**Pull request merged**
