### PR TITLE
[Doc] Add producer configuration description for Java client

### PR DESCRIPTION
**Pull request by Anonymitaet**

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@yjshen could you please help review? Thank you

Double-check:
The default value of `messageRoutingMode` is `null` or `pulsar.RoundRobinDistribution`?

**Comment by sijie** [comment]
@Anonymitaet pulsar.RoundRobinDistribution

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by Anonymitaet** [comment]
@sijie thank you

**Comment by Anonymitaet** [comment]
run java8 tests

**Comment by yjshen** [comment]
run java8 tests

**Comment by Anonymitaet** [comment]
Fix https://github.com/apache/pulsar/pull/5154

**Pull request merged**
