### PR TITLE
fix retryLetterProducer usr auto_chema

### PR DESCRIPTION
**Pull request by Johnnyhooyo**
link to #11474

### CODE REVIEW

**Comment by Anonymitaet** [comment]
Thanks for your contribution. For this PR, do we need to update docs?

(The [PR template contains info about doc](https://github.com/apache/pulsar/blob/master/.github/PULL_REQUEST_TEMPLATE.md#documentation), which helps others know more about the changes. Can you provide doc-related info in this and future PR descriptions? Thanks)

**Comment by Johnnyhooyo** [comment]
> Thanks for your contribution. For this PR, do we need to update docs?
> 
> (The [PR template contains info about doc](https://github.com/apache/pulsar/blob/master/.github/PULL_REQUEST_TEMPLATE.md#documentation), which helps others know more about the changes. Can you provide doc-related info in this and future PR descriptions? Thanks)

maybe this PR do not need update Docs, because the modified logic is normal logic and does not need to be repeated

**Review by congbobo184 — COMMENTED** [review]
good catch! could you please add some test for it? like: https://github.com/apache/pulsar/pull/9970

**Comment by codelipenghui** [comment]
The pr had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale. I make a follow-up at #19051. Please take a look.

This original author is marked as co-author.

**Pull request closed without merging**
