### PR TITLE
[refactor][broker] Move loadbalancer used data classes package position

### PR DESCRIPTION
**Pull request by Demogorgon314**
### Motivation

I'm working on improving the loadbalancer, but I find they are four classes used in loadbalancer and the package position is under the `org.apache.pulsar.broker`. This is strange because another class named `LocalBrokerData` is in `org.apache.pulsar.policies.data.loadbalancer`.

We should move it to pulsar-common and put them together with `LocalBrokerData` for future extensions.

### Modifications

Move loadbalancer used data classes package position to `org.apache.pulsar.policies.data.loadbalancer`

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Review by mattisonchao — APPROVED** [review]

**Review by Jason918 — APPROVED** [review]
LGTM

**Review by RobertIndie — APPROVED** [review]

**Comment by Demogorgon314** [comment]
@codelipenghui @RobertIndie The CI is passed. Please take a look if you have time, thanks : )

**Pull request merged**
