### PR TITLE
Revert "Upgraded ElasticSearch to get rid of CVEs. (#13747)"

### PR DESCRIPTION
**Pull request by dlg99**
This reverts commit 1af8d3fc6bca31c1ca059a2dda80e6d8eb7ae24b.

Elastic client switched license from Apache 2 to Elastic License. Reverting / to try to move to another client implementation.
### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): *YES*, reverts dependency changes
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Comment by dlg99** [comment]
duplicates https://github.com/apache/pulsar/pull/13861

**Comment by lhotari** [comment]
Some notes:
- Elastic license changed since 7.11.0
- [Elastic High Level REST Client](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high.html) is deprecated in favor of the Java API Client. The Elastic High Level REST Client isn't ASL 2.0 licensed.
- The migration from HLRC to Java Client should happen before upgrading, https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/migrate-hlrc.html
- Elastic Java Client is ASL 2.0 licensed

**Review by lhotari — APPROVED** [review]

**Review by nicoloboschi — APPROVED** [review]
+1

**Review by michaeljmarshall — APPROVED** [review]
LGTM

**Pull request merged**
