### PR TITLE
[fix][broker]fix multi invocation for ledger createComplete

### PR DESCRIPTION
**Pull request by aloyszhang**
### Motivation

fix multi invocation for ledger `createComplete`

### Modifications

Only call `createComplete` at the point of creating ledger timeout if the ledger is not created normally

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework without any test coverage.

### Documentation

- [x] `doc-not-needed` 

### Matching PR in forked repository

PR in forked repository: [https://github.com/aloyszhang/pulsar/pull/8]

### CODE REVIEW

**Review by poorbarcode — COMMENTED** [review]
Method `checkAndCompleteLedgerOpTask` has already prevented this.

https://github.com/apache/pulsar/blob/002fa49692ff4b8b038bf2edeeb3b32ed218e64f/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L520

**Comment by aloyszhang** [comment]
> Method checkAndCompleteLedgerOpTask has already prevented this.

Of course, `checkAndCompleteLedgerOpTask` can prevent this.
But we do not need to go into the `createComplete` at all if the ledger creation is complete normally.

Actually, this is introduced by https://github.com/apache/pulsar/pull/7401, before this PR, the processing logic is 
```java
 if (!ledgerCreated.get()) {
                cb.createComplete(BKException.Code.TimeoutException, null, ledgerCreated);
            }
```
and PR#7401 change it to 
```java
           if (!ledgerCreated.get()) {
                if (log.isDebugEnabled()) {
                    log.debug("[{}] Timeout creating ledger", name);
                }
            } else {
                if (log.isDebugEnabled()) {
                    log.debug("[{}] Ledger already created when timeout task is triggered", name);
                }
            }
            cb.createComplete(BKException.Code.TimeoutException, null, ledgerCreated);
```

**Review by poorbarcode — APPROVED** [review]

**Review by nodece — APPROVED** [review]

**Review by RobertIndie — COMMENTED** [review]
This seems to be intentional; see here: https://github.com/apache/pulsar/pull/7401/files#r447839861

Looks like this PR is more like a cleanup instead of a bug fix. Or does it fix any issues?

**Review by mattisonchao — APPROVED** [review]
LGTM

**Review by congbobo184 — APPROVED** [review]

**Comment by aloyszhang** [comment]
> This seems to be intentional; see here: https://github.com/apache/pulsar/pull/7401/files#r447839861

As poorbarcode mentioned above, `checkAndCompleteLedgerOpTask ` in `createComplete` has the ability to prevent the following logic of callback triggered twice. 
But we have to invoke `createComplete` twice for every ledger creation. I think it's confusing.


> Looks like this PR is more like a cleanup instead of a bug fix. Or does it fix any issues?

It just fixes the twice trigger of `createComplete`.

**Comment by RobertIndie** [comment]
> It just fixes the twice trigger of createComplete.

Thanks, make sense to me.

**Pull request merged**
