### PR TITLE
[fix][misc] Add proper nslookup (included in bind-tools) to docker image

### PR DESCRIPTION
**Pull request by lhotari**
Fixes: #22877 

### Motivation

The default `nslookup` in Alpine is based on busybox and it isn't compatible with Kubernetes. See #22877 for more details.

### Modifications

Install `bind-tools` package to get proper `nslookup`

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by merlimat — APPROVED** [review]

**Comment by lhotari** [comment]
> I assume `bind-utils` is light-weight.

It is. The downside is that it could contain vulnerabilities which show up in scanning. However there doesn't seem to be an alternative for backwards compatibility with Pulsar helm charts that use nslookup to check when another component is available.

**Comment by lhotari** [comment]
The correct package name in Alpine is `bind-tools`. Testing it soon with Apache Pulsar Helm chart.

**Comment by merlimat** [comment]
> > I assume `bind-utils` is light-weight.
> 
> It is. The downside is that it could contain vulnerabilities which show up in scanning. However there doesn't seem to be an alternative for backwards compatibility with Pulsar helm charts that use nslookup to check when another component is available.

After we do the `RUN apk upgrade --no-cache` step, it's picking up the latest version, with no vulnerabilities

**Comment by lhotari** [comment]
Pulsar cluster gets initialized properly with Apache Pulsar Helm chart when using nslookup from bind-tools package. Here's the way I tested: https://github.com/lhotari/pulsar-helm-chart/pull/10/files#diff-f34da55ca08f1a30591d8b0b3e885bcc678537b2a9a4aadea4f190806b374ddcR3 . Pushed the image to https://hub.docker.com/r/lhotari/pulsar-all/tags (`docker pull lhotari/pulsar-all:3.3.0-nslookup`)

**Pull request merged**
