### PR TITLE
[docs] Add description for max topics per namespace

### PR DESCRIPTION
**Pull request by sijia-w**
Add description for https://github.com/apache/pulsar/pull/8942.

### CODE REVIEW

**Comment by sijia-w** [comment]
@Anonymitaet I am not sure about where to add this parameter, so I added it at the end of each section. Please let me know if I should remove it to the middle. Thank you.

**Review by Anonymitaet — APPROVED** [review]

**Comment by Anonymitaet** [comment]
@sijia-w thanks for your contribution, you can ask help from the author as well. @hangc0276 could you please help review? Thanks

**Comment by Anonymitaet** [comment]
@sijia-w some checks were not successful, you can comment `/pulsarbot run-failure-checks` to rerun the tests.

**Review by sijie — APPROVED** [review]

**Pull request merged**
