### PR TITLE
[improve][doc] Highlight important tips

### PR DESCRIPTION
**Pull request by Anonymitaet**
Preview looks good

image

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@momo-jun review? Thanks!

**Review by momo-jun — APPROVED** [review]
LGTM.

BTW, there are several more occurrences in the docs, FYI:
image

**Comment by Anonymitaet** [comment]
@momo-jun yes, thanks for reminding me, explain it in https://github.com/apache/pulsar/issues/15892

**Comment by Anonymitaet** [comment]
@momo-jun thanks for adding the `deprecate note` to [site2/docs/develop-binary-protocol.md](https://github.com/apache/pulsar/pull/15890/files#diff-676d561a2e48838e3578efb4f9a9d5b3a49b73c20e87a4f18031eeeca2a19501). 

After thinking twice, I remove it in this PR since some contributors modify the wrong file accidentally https://github.com/apache/pulsar/pull/15878#pullrequestreview-993147936

`develop-binary-protocol.md` is duplicated with `developing-binary-protocol.md`. I've checked all occurrences and ensure no versioned docs has referenced `develop-binary-protocol.md` on master. Every versioned doc has its own `develop-binary-protocol.md` or `developing-binary-protocol.md`.

**Review by Huanli-Meng — APPROVED** [review]

**Pull request merged**
