### PR TITLE
Upgrade Apache BookKeeper Client to 4.11.1

### PR DESCRIPTION
**Pull request by eolivelli**
### Motivation

Upgrade Apache BookKeeper client to version 4.11.1 and RocksDB to 6.10.2 (needed by Bookie)

### Modifications

Upgrade Apache BookKeeper client, fix a few build errors, due to the introduction of BookieServiceInfo structure (see BP-38).

### Verifying this change

This change is already covered by existing tests

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes)
  - The public API: ( no)
  - The schema: (no )
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)
  - If a feature is not applicable for documentation, explain why? it is only a dependency upgrade, no new BK features enabled with this change
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by eolivelli** [comment]
This is only a Draft, because BK 4.11.1 still is not released, but the API is the same as BK 4.11.0, it will be better to merge this patch after BK 4.11.1 is released

**Comment by eolivelli** [comment]
some CI jobs failed with this error, it looks like a temporary error

> Error:  Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.3.0:add-source (default) on project flink: Execution default of goal net.alchim31.maven:scala-maven-plugin:4.3.0:add-source failed: Plugin net.alchim31.maven:scala-maven-plugin:4.3.0 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.apache.maven:maven-builder-support:jar:3.3.9, org.apache.maven:maven-artifact:jar:3.3.9: Could not transfer artifact org.apache.maven:maven-builder-support:jar:3.3.9 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/maven-builder-support/3.3.9/maven-builder-support-3.3.9.jar: Connection timed out (Read failed) -> [Help 1]

**Review by sijie — APPROVED** [review]

**Comment by eolivelli** [comment]
I have to fix LICENSE stuff.

**Review by jiazhai — APPROVED** [review]

**Comment by jiazhai** [comment]
@eolivelli Thanks for the fix. there a license check failed. and would you please also help update this pr with latest master code?

https://github.com/apache/pulsar/pull/8270/checks?check_run_id=1285693542
```
Run src/check-binary-license ./distribution/server/target/apache-pulsar-*-bin.tar.gz
src/check-binary-license: line 61: echo: write error: Broken pipe
jakarta.activation-jakarta.activation-api-1.2.1.jar unaccounted for in LICENSE
jakarta.xml.bind-jakarta.xml.bind-api-2.3.2.jar unaccounted for in LICENSE
jakarta.activation-jakarta.activation-api-1.2.2.jar mentioned in LICENSE, but not bundled
com.sun.activation-jakarta.activation-1.2.2.jar mentioned in LICENSE, but not bundled
jakarta.xml.bind-jakarta.xml.bind-api-2.3.3.jar mentioned in LICENSE, but not bundled
jetty-alpn-java-client-9.4.27.v20200227.jar mentioned in lib/presto/LICENSE, but not bundled
jakarta.activation-1.2.2.jar mentioned in lib/presto/LICENSE, but not bundled
jakarta.activation-api-1.2.2.jar mentioned in lib/presto/LICENSE, but not bundled
jakarta.xml.bind-api-2.3.3.jar mentioned in lib/presto/LICENSE, but not bundled

It looks like there are issues with the LICENSE/NOTICE.
Error: Process completed with exit code 2.
```

**Comment by eolivelli** [comment]
thank you @jiazhai 
my plan is to commit https://github.com/apache/pulsar/pull/8360 before this one.

Also in that PR I have a problem with license check,
locally the script is passing on my machine, but it fails on CI

this is very weird

**Comment by eolivelli** [comment]
@jiazhai I have fixed the conflict on Presto Distribution license

**Review by rdhabalia — APPROVED** [review]

**Comment by eolivelli** [comment]
This error is very nasty, investigating now.
It is probably due to some dependency imported from the new BK client

```
Error:  Tests run: 11, Failures: 1, Errors: 0, Skipped: 10, Time elapsed: 4.263 s <<< FAILURE! - in org.apache.pulsar.client.TlsProducerConsumerTest
Error:  setup(org.apache.pulsar.client.TlsProducerConsumerTest)  Time elapsed: 4.166 s  <<< FAILURE!
java.lang.NoSuchFieldError: xmss_with_SHA256
	at java.security.AccessController.doPrivileged(Native Method)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.pulsar.common.util.SecurityUtility.getBCProviderFromClassPath(SecurityUtility.java:125)
	at org.apache.pulsar.common.util.SecurityUtility.getProvider(SecurityUtility.java:102)
	at org.apache.pulsar.common.util.SecurityUtility.<clinit>(SecurityUtility.java:69)
	at org.apache.pulsar.broker.web.WebService.<init>(WebService.java:114)
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:479)
	at org.apache.pulsar.broker.auth.MockedPulsarServiceBaseTest.startBroker(MockedPulsarServiceBaseTest.java:269)
	at org.apache.pulsar.broker.auth.MockedPulsarServiceBaseTest.startBroker(MockedPulsarServiceBaseTest.java:251)
```

**Comment by eolivelli** [comment]
The problem was about the fact that now BookKeeper imports a dependency from BouncyCastle and this pollutes the complex handling of BC in Pulsar

**Pull request merged**
