### PR TITLE
[Docs] Add functions-worker commands for pulsar admin CLI

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <ranxiaolong716@gmail.com>

### Motivation

`functions-worker` document missing

### Modifications

Add functions-worker commands for pulsar admin CLI:

- function-stats
- get-cluster
- get-cluster-leader
- get-function-assignments
- monitoring-metrics

### CODE REVIEW

**Comment by wolfstudy** [comment]
run cpp tests
run integration tests
run java8 tests

**Comment by jiazhai** [comment]
run integration tests

**Comment by codelipenghui** [comment]
run integration tests

**Comment by wolfstudy** [comment]
run integration tests

**Comment by wolfstudy** [comment]
run integration tests

**Comment by wolfstudy** [comment]
> org.apache.pulsar.tests.integration.functions.PulsarStateTest.pulsar-standalone-suite

run integration tests

**Comment by wolfstudy** [comment]
run integration tests

**Comment by wolfstudy** [comment]
run cpp tests

**Pull request merged**
