### PR TITLE
[PIP-139] Support Broker send command to close producer/consumer.

### LINKED ISSUE #13989: [PIP-139] Support Broker send command to close producer/consumer.
Relation pull request:  #13337
Authors: @Technoboy-  @mattisonchao 

## Motivation

- When there are no user-created topics under a namespace, Namespace should be deleted. But currently, the system topic existed and the reader/producer could auto-create the system which may cause the namespace deletion to fail.
- When enabling geo-replication under a namespace, inactive topics could not be deleted by GC, and if the broker enables `auto-create` topic, the topic will be created(replicator) even deleted with `force=true`.

For the above reasons, we need to close the topics readers/producers first, then delete the relative topics.

Following this way, we need to close consumers/producers(not disconnect, which means do not allow them to reconnect). So we write this PIP to discuss to resolve this problem.

Related email : https://lists.apache.org/thread/p4tmgk23l8j554bjr4h4ofk97bll5gp4

## Goal

We can add a new field(`reconnect`) in command  ``CommandCloseProducer``/ ``CommandCloseConsumer`` to achieve this goal.

## API Changes

- Add ``reconnect`` to ``CommandCloseProducer``;

```java
**Before**

message CommandCloseProducer {
    required uint64 producer_id = 1;
    required uint64 request_id = 2;
}

**After**
message CommandCloseProducer {
    required uint64 producer_id = 1;
    required uint64 request_id = 2;
    optional bool reconnect = 3 [default = true];
}
```

- Add ``reconnect`` to ``CommandCloseConsumer``
```java
**Before**

message CommandCloseConsumer {
    required uint64 consumer_id = 1;
    required uint64 request_id = 2;
}

**After**
message CommandCloseConsumer {
    required uint64 consumer_id = 1;
    required uint64 request_id = 2;
    optional bool reconnect = 3 [default = true];
}
```

### ClientCnx - Producer:

**Before**
 ```java
@Override
protected void handleCloseProducer(CommandCloseProducer closeProducer) {
    log.info("[{}] Broker notification of Closed producer: {}", remoteAddress, closeProducer.getProducerId());
    final long producerId = closeProducer.getProducerId();
    ProducerImpl<?> producer = producers.get(producerId);
    if (producer != null) {
        producer.connectionClosed(this);
    } else {
        log.warn("Producer with id {} not found while closing producer ", producerId);
    }
}  
 ```
After:
 ```java
@Override
protected void handleCloseProducer(CommandCloseProducer closeProducer) {
    log.info("[{}] Broker notification of Closed producer: {}", remoteAddress, closeProducer.getProducerId());
    final long producerId = closeProducer.getProducerId();
    ProducerImpl<?> producer = producers.get(producerId);
    if (producer != null) {
        if (closeProducer.isReconnect()) {
            producer.connectionClosed(this);
        } else {
            producer.closeAsync();
        }
    } else {
        log.warn("Producer with id {} not found while closing producer ", producerId);
    }
}
 ```
### ClientCnx - Consumer:

**Before**
 ```java
@Override
protected void handleCloseConsumer(CommandCloseConsumer closeConsumer) {
    log.info("[{}] Broker notification of Closed consumer: {}", remoteAddress, closeConsumer.getConsumerId());
    final long consumerId = closeConsumer.getConsumerId();
    ConsumerImpl<?> consumer = consumers.get(consumerId);
    if (consumer != null) {
        consumer.connectionClosed(this);
    } else {
        log.warn("Consumer with id {} not found while closing consumer ", consumerId);
    }
}    
 ```
**After**
 ```java
 @Override
protected void handleCloseConsumer(CommandCloseConsumer closeConsumer) {
    log.info("[{}] Broker notification of Closed consumer: {}", remoteAddress, closeConsumer.getConsumerId());
    final long consumerId = closeConsumer.getConsumerId();
    ConsumerImpl<?> consumer = consumers.get(consumerId);
    if (consumer != null) {
        if (closeConsumer.isReconnect()) {
            consumer.connectionClosed(this);
        } else {
            consumer.closeAsync();
        }
    } else {
        log.warn("Consumer with id {} not found while closing consumer ", consumerId);
    }
}   
 ```

## Reject Alternatives

none.

### PR DESCRIPTION
**Pull request by mattisonchao**
### Motivation
  
 Original PIP  #13989

- When there are no user-created topics under a namespace, Namespace should be deleted. But currently, the system topic existed and the reader/producer could auto-create the system which may cause the namespace deletion to fail.
- When enabling geo-replication under a namespace, inactive topics could not be deleted by GC, and if the broker enables `auto-create` topic, the topic will be created(replicator) even deleted with `force=true`.

For the above reasons, we need to close the topics readers/producers first, then delete the relative topics.

Following this way, we need to close consumers/producers(not disconnect, which means do not allow them to reconnect). So we write this PIP to discuss to resolve this problem.

### Modifications

- Add ``optional bool reconnect = 3 [default = true];`` at ``CommandCloseConsumer``
- Add ``optional bool reconnect = 3 [default = true];`` at ``CommandCloseProducer``
- If broker send ``CommandCloseConsumer/CommandCloseProducer`` with ``isReconnect=false`` the Producer/Consumer will close immediately.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:

  - The wire protocol: (yes)

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [x] `no-need-doc`

### CODE REVIEW

**Review by Technoboy- — COMMENTED** [review]
LTGM

**Review by Jason918 — DISMISSED** [review]
LGTM

**Pull request closed without merging**
