### PR TITLE
[Doc] Correct Python versions

### PR DESCRIPTION
**Pull request by Anonymitaet**
Resolve https://github.com/apache/pulsar/issues/5345

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@tuteng @candlerb could you please help review? Thank you

**Comment by candlerb** [comment]
I presume that's correct, as long as CI tests all of those versions?

**Comment by tuteng** [comment]
run java8 tests
run integration tests

**Comment by tuteng** [comment]
run cpp tests
run java8 tests

**Comment by Anonymitaet** [comment]
Thank you @tuteng @candlerb @aahmed-se

**Pull request merged**
