### PR TITLE
[functions][metrics] Update function metrics

### PR DESCRIPTION
**Pull request by sijie**
some prometheus agent are picky at the prometheus output format. this change to make metric type is by the metric. The resulting output is showed as below

```
# TYPE pulsar_function__total_processed__sum gauge
pulsar_function__total_processed__sum{cluster="standalone",namespace="test/test-namespace",name="example",instanceId="0"} 0.0 1538351566227
# TYPE pulsar_function__total_successfully_processed__count gauge
pulsar_function__total_successfully_processed__count{cluster="standalone",namespace="test/test-namespace",name="example",instanceId="0"} 0.0 1538351566227
# TYPE pulsar_function__total_successfully_processed__max gauge
pulsar_function__total_successfully_processed__max{cluster="standalone",namespace="test/test-namespace",name="example",instanceId="0"} 0.0 1538351566227
# TYPE pulsar_function__total_successfully_processed__min gauge
pulsar_function__total_successfully_processed__min{cluster="standalone",namespace="test/test-namespace",name="example",instanceId="0"} 0.0 1538351566227
# TYPE pulsar_function__total_successfully_processed__sum gauge
pulsar_function__total_successfully_processed__sum{cluster="standalone",namespace="test/test-namespace",name="example",instanceId="0"} 0.0 1538351566227
# TYPE pulsar_function__total_system_exceptions__count gauge
pulsar_function__total_system_exceptions__count{cluster="standalone",namespace="test/test-namespace",name="example",instanceId="0"} 0.0 1538351566227
# TYPE pulsar_function__total_system_exceptions__max gauge
pulsar_function__total_system_exceptions__max{cluster="standalone",namespace="test/test-namespace",name="example",instanceId="0"} 0.0 1538351566227
# TYPE pulsar_function__total_system_exceptions__min gauge
pulsar_function__total_system_exceptions__min{cluster="standalone",namespace="test/test-namespace",name="example",instanceId="0"} 0.0 1538351566227
# TYPE pulsar_function__total_system_exceptions__sum gauge
pulsar_function__total_system_exceptions__sum{cluster="standalone",namespace="test/test-namespace",name="example",instanceId="0"} 0.0 1538351566227
# TYPE pulsar_function__total_user_exceptions__count gauge
pulsar_function__total_user_exceptions__count{cluster="standalone",namespace="test/test-namespace",name="example",instanceId="0"} 0.0 1538351566227
# TYPE pulsar_function__total_user_exceptions__max gauge
```

### CODE REVIEW

**Comment by sijie** [comment]
@merlimat can you review this change?

**Comment by merlimat** [comment]
@sijie Can you rebase/merge with master -- That should have fixed several of the flaky tests

**Comment by sijie** [comment]
rebased to latest master

**Comment by sijie** [comment]
retest this please

**Pull request merged**
