### PR TITLE
[feature][website] feat: website docs migrate with new syntax and preview script `start.sh`

### PR DESCRIPTION
**Pull request by urfreespace**
## Website Preview
```
cd site2/website
sh start.sh
```

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `no-need-doc` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-added`
(Docs have been already added)

### CODE REVIEW

**Review by Anonymitaet — APPROVED** [review]

**Comment by michaeljmarshall** [comment]
@urfreespace - are you able to explain the motivation for this PR a bit more? It looks like it added new doc files to old versioned docs directories. For example, I see that `site2/website/versioned_docs/version-2.1.0-incubating/pulsar-admin.md` was added in this PR, but I'm not sure why. I ask because I am working on understanding some of the broken links in Pulsar. Thanks for any help you can give!

**Comment by urfreespace** [comment]
> 

image

it seems that `pulsar-admin` is part of version-2.1.0, In fact, as we upgrade the framework of docusaurus, this pr is fixing the  md syntax to adapt the docusaurus v2.x, and as the different between v1.x an v2.x, the v2.x need full copy docs for every version independence, but in v1.x, the missing docs will auto links to the latest version docs, so in v1.x, for example, maybe a.md is not exist in version a, but it will auto links to a.md that in latest version, but in v2.x that will not happened, you must make sure a.md exist in version a

**Comment by urfreespace** [comment]
> @urfreespace - are you able to explain the motivation for this PR a bit more? It looks like it added new doc files to old versioned docs directories. For example, I see that `site2/website/versioned_docs/version-2.1.0-incubating/pulsar-admin.md` was added in this PR, but I'm not sure why. I ask because I am working on understanding some of the broken links in Pulsar. Thanks for any help you can give!

image

it seems that `pulsar-admin` is part of version-2.1.0, In fact, as we upgrade the framework of docusaurus, this pr is fixing the  md syntax to adapt the docusaurus v2.x, and as the different between v1.x an v2.x, the v2.x need full copy docs for every version independence, but in v1.x, the missing docs will auto links to the latest version docs, so in v1.x, for example, maybe a.md is not exist in version a, but it will auto links to a.md that in latest version, but in v2.x that will not happened, you must make sure a.md exist in version a

**Comment by michaeljmarshall** [comment]
Thank you for the explanation. That helps explain what I saw in the git history. My one concern is that this change makes new features get documented in the old versioned docs. Would it make sense to "archive" these docs? I don't really see a reason to host docs for anything older the 2.6 right now since those versions are no longer supported. This would need discussion on the mailing list, but it seems like we could get rid of those dos and it'd make your job easier since you would have fewer docs to worry about managing. Also, I have noticed that some of the incubating docs are returned in search engine searches, and that seems like it'd create confusion for new users.

**Pull request merged**
