### PR TITLE
[Issue 5941][Pulsar IO]Upgrade debezium from v0.10.0-Final to v1.0.0-Final

### PR DESCRIPTION
**Pull request by tuteng**
Fixes https://github.com/apache/pulsar/issues/5941

### Motivation

Debezium has released the major version v1.0.0.Final.

### Modifications

* Upgrade version of debezium from 0.10.0 to 1.0.0.Final

### Verifying this change

Local integration test

### CODE REVIEW

**Comment by tuteng** [comment]
retest this please

**Comment by tuteng** [comment]
run java8 tests

**Comment by tuteng** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by tuteng** [comment]
run java8 tests

**Pull request merged**
