### PR TITLE
Update bin/bookkeeper script.

### PR DESCRIPTION
**Pull request by MarvinCai**
Fixes https://github.com/apache/pulsar/issues/16904

### Motivation
Allowing user to override default `-Djava.net.preferIPv4Stack=true` config to run bookie init command in ipv6 environment.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (yes)
  Should be able to init bookkeeper cluster in ipv6 env using `bin/bookkeeper shell initnewcluster`

### Documentation

Need to update docs? 
- [x] `doc-not-needed`

### CODE REVIEW

**Review by zymap — APPROVED** [review]

**Review by hangc0276 — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]

**Comment by tisonkun** [comment]
@MarvinCai to pass required CI tasks, you should merge the latest master branch. I think this patch is ready to merge already :)

**Review by Shoothzj — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
Can you please send the same patch to BookKeeper project?

**Comment by tisonkun** [comment]
Rebased onto master. Pending to merge...

> Can you please send the same patch to BookKeeper project?

I think it's another topic that should not block this patch :)

**Comment by tisonkun** [comment]
Thanks for your contribution @MarvinCai!

Merging...

**Pull request merged**
