### PR TITLE
[DOCS] Refine reader interface for Pulsar client

### PR DESCRIPTION
**Pull request by sijia-w**
Modification:
Update the reader interface for Pulsar client in master branch and 2.7.0. 
At present, the version 2.7.0 supports partitioned topics. While the docs are not up-to-date.

### CODE REVIEW

**Comment by sijia-w** [comment]
@Jennifer88huang Please help review the changes. Thank you.

**Comment by Jennifer88huang** [comment]
@sijia-w could you please also adopt the changes to 2.7.1 docs? Thank you.

**Comment by sijia-w** [comment]
@Jennifer88huang  Do we have 2.7.1 docs? I didn't see it on Pulsar website.

**Comment by Jennifer88huang** [comment]
Yes,  https://github.com/apache/pulsar/tree/master/site2/website/versioned_docs/version-2.7.1

**Comment by sijia-w** [comment]
@Jennifer88huang The changes to 271 version is in a separate pr https://github.com/apache/pulsar/pull/9065 since this branch was not rebased. Thank you.

**Review by Jennifer88huang — APPROVED** [review]

**Pull request merged**
