### PR TITLE
[improve][test] remove powermock-reflect dependency

### LINKED ISSUE #16912: Get rid of powermock
In this comment https://github.com/apache/pulsar/pull/16884#issuecomment-1201512995 I wrote:

> I don't like powermock as it lacks maintenance. It seems all usage of powermock is `Whitebox`. We can get rid of it with simple reflections. This can be a separate issue, though.

Thus I file this issue to investigate whether we can remove powermock from our testing framework.

WDTY @merlimat @lhotari @codelipenghui @nicoloboschi?

### PR DESCRIPTION
**Pull request by tisonkun**
This closes #16912.

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [x] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Comment by tisonkun** [comment]
cc @Shoothzj @merlimat @nicoloboschi

**Review by nicoloboschi — APPROVED** [review]
LGTM but tbh it's a very long pull 👀

**Review by Shoothzj — APPROVED** [review]

**Comment by tisonkun** [comment]
Thanks for your reviews! Could You help with merging this patch? @Shoothzj @nicoloboschi

> LGTM but tbh it's a very long pull 👀

As long as we use squash and merge😉

We should try to prevent reintroduce the library in further development randomly. And perhaps it's time to convert the "community" page to a contributor guide, like https://inlong.apache.org/community/how-to-contribute.

**Pull request merged**
