### PR TITLE
Enable CheckStyle Plugin in managed-ledger module

### PR DESCRIPTION
**Pull request by liudezhi2098**
Motivation
Enable CheckStyle Plugin in managed-ledger module.

Documentation
- [x] `no-need-doc`

### CODE REVIEW

**Comment by Shoothzj** [comment]
@liudezhi2098 The comma style doesn't protected by checkstyle ?

**Review by Shoothzj — CHANGES_REQUESTED** [review]
block this PR for checkstyle discussion

**Comment by liudezhi2098** [comment]
> @liudezhi2098 The comma style doesn't protected by checkstyle ?
Some comments are not protected, and some modules do not include checkstyle, we  can discuss.

**Comment by Shoothzj** [comment]
After discuss with @liudezhi2098, We need to apply `checkstyle-plugins` to `managed-ledger` module to protect these changes.

**Review by Shoothzj — APPROVED** [review]

**Comment by Shoothzj** [comment]
@codelipenghui can we change managed-ledger/src/main/java/org/apache/bookkeeper/mledger/LedgerOffloader.java's `default CompletableFuture<Boolean> AsyncClose()`  to `default CompletableFuture<Boolean> asyncClose()` ?

**Comment by liudezhi2098** [comment]
> @codelipenghui can we change managed-ledger/src/main/java/org/apache/bookkeeper/mledger/LedgerOffloader.java's `default CompletableFuture<Boolean> AsyncClose()` to `default CompletableFuture<Boolean> asyncClose()` ?

I found no place to use this method

**Comment by liudezhi2098** [comment]
@codelipenghui PTAL

**Comment by codelipenghui** [comment]
@Shoothzj It's ok, the `OffloadHandle` introduced by streaming offloading, and it only is used in streaming offload, and its internal component, so we can change the method name.

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
