### PR TITLE
Remove deprecated Mockito api use

### PR DESCRIPTION
**Pull request by Shoothzj**
### Modifications
Remove deprecated Mockito api use

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 
  
- [x] `no-need-doc` 
  
  trival changes, no need doc

### CODE REVIEW

**Review by Technoboy- — APPROVED** [review]

**Comment by Shoothzj** [comment]
@codelipenghui @lhotari @michaeljmarshall @merlimat @eolivelli @315157973 PTAL, thanks

**Review by merlimat — APPROVED** [review]

**Pull request merged**
