### PR TITLE
[fix][flaky-test]DispatcherBlockConsumerTest.testBrokerSubscriptionRecovery

### PR DESCRIPTION
**Pull request by poorbarcode**
### Motivation

test example: https://github.com/apache/pulsar/runs/8128077384?check_suite_focus=true

#### Why flaky

This test, uses the index to compare the messages, but the order of received messages is not guaranteed: 

- Subscription type is `Shared`
- Enabled streaming dispatch (There may be bugs in this scenario. I am confirming it)

截屏2022-09-02 12 15 36

### Modifications

- This PR is only concerned with fixing flaky Test 
  - Compare using the content of the unack messages
- There may be bugs when enabled streaming dispatch. 
  - There should be another PR solution

### Documentation

- [ ] `doc-required` 

  
- [x] `doc-not-needed` 

  
- [ ] `doc` 

- [ ] `doc-complete`

### CODE REVIEW

**Comment by poorbarcode** [comment]
the problem still exists: https://github.com/apache/pulsar/runs/8149264299?check_suite_focus=true

**Comment by poorbarcode** [comment]
try expand wait time of receive message

**Comment by poorbarcode** [comment]
@mattisonchao will fix the problem of `streaming dispatch`

**Comment by tisonkun** [comment]
> Try to expand the wait time to receive messages

Since we have a great number of tests, this approach can hardly work. Because if every test tries to wait for a long time, the resource is consumed more eagerly and more tests become unstable due to they don't get enough time to run.

**Pull request closed without merging**
