### PR TITLE
Issue #3773:  update partition doc for auto update

### LINKED ISSUE #3773: Update documentation for topic partitions auto update
Update documentation for topic partitions auto update

### PR DESCRIPTION
**Pull request by jiazhai**
fix #3773 
update partition doc for auto update

### CODE REVIEW

**Comment by jiazhai** [comment]
run integration tests

**Comment by jiazhai** [comment]
run java8 tests
run integration tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run integration tests

**Pull request merged**
