### PR TITLE
Move settings.xml back for the Pulsar release.

### PR DESCRIPTION
**Pull request by codelipenghui**
The settings.xml been remove by https://github.com/apache/pulsar/pull/10111. Move it back since we need the setting.xml for the maven package upload.

### CODE REVIEW

**Review by jiazhai — APPROVED** [review]

**Comment by hangc0276** [comment]
do we need `.travis.yml`?

**Comment by codelipenghui** [comment]
@hangc0276 Seems the `.travis.yml` generated locally? I can't find it in both branch-2.7 and branch-2.6

**Comment by merlimat** [comment]
@codelipenghui maybe we could move this file under `src` directory, since it's not related to travis

**Comment by codelipenghui** [comment]
@merlimat moved to the src directory

**Comment by hangc0276** [comment]
> @hangc0276 Seems the `.travis.yml` generated locally? I can't find it in both branch-2.7 and branch-2.6

@codelipenghui  it was import by #528 and located in `src/.travis.yml`

**Pull request merged**
