### PR TITLE
[Issue 5215,4601,5215][pulsar-io] Add jdbc sinks: postgres, mariadb, clickhouse

### LINKED ISSUE #5215: Support Postgres as a JDBC source/sink
Having ran a custom build of Pulsar 2.4 with the PostgreSQL client built in for a number of days now, I have not come across any problems using the PSQL driver as a JDBC sink at load.

I note the JDBC tests are all performed against an embedded SQL instance, are there any other tests that should be ran before I create a PR to support Postgres?

### PR DESCRIPTION
**Pull request by vzhikserg**
Fixes #5215  #4601 #5215

### Motivation

Right now, the number of supported JDBC connectors is rather limited. There are a couple of open issues related to the missing connectors. 

### Modifications

As a base for this pull request, I took the [changes](https://github.com/apache/pulsar/pull/5624) from @huangdx0726 Unfortunately,  I was not able to reach him to merge my changes to his branch, so I created a new one.

The main modification is a split of one JDBC module into a bunch of them. One module serves as a core and provides the main logic of the connector. Other modules are real connectors and add only an appropriate JDBC driver.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes)
  - The default values of configurations: (yes)
  - Anything that affects deployment: (yes / don't know)

### Documentation

  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (docs / JavaDocs)

I would like to confirm that this is the right way and after that, I can change existing documentation for the MySQL and SQLite connectors, and add docs for the newly added connectors.

One more question is related to the MySQL connector and the #6656 Does it mean that we need to remove the MySQL connector?

### CODE REVIEW

**Comment by vzhikserg** [comment]
@sijie could you please comment on this pull request? Do you think that it is a right approach? Shall I continue working on it and change/add docs? Did I miss something?

**Comment by sijie** [comment]
@vzhikserg I like the approach. This works out very well. 

Just one minor comment - I don't think we can bundle MySQL in the release anymore because of the license issue. It might be worth removing that one from this pull request.

**Comment by vzhikserg** [comment]
@sijie the pull request is ready for the final review.
The MySQL connector was removed from the distribution. Documentation on how to use the MySQL connector was substituted with the Postgres connector. The integration tests were also updated to use Postgres.

**Pull request merged**
