### PR TITLE
[fix][doc] Add JDK 11 as recommended version

### PR DESCRIPTION
**Pull request by nodece**
Signed-off-by: Zixuan Liu <nodeces@gmail.com>

### Motivation

Improve the  `Requirements` section, add recommended version for JDK.

### Modifications

- Add JDK recommended version in getting started and deploy doc of Pulsar 2.8-latest versions

### Documentation

- [x] `doc`

### CODE REVIEW

**Review by momo-jun — APPROVED** [review]
Thanks for contributing to Pulsar docs!
It looks good to me. As it is the requirement to run Pulsar 2.9.1 and later versions, will you apply this change to the versioned docs as well?

**Comment by nodece** [comment]
> As it is the requirement to run Pulsar 2.9.1 and later versions, will you apply this change to the versioned docs as well?

This just applies to Pulsar 2.9.1 and later versions.

**Comment by Anonymitaet** [comment]
@nodece this PR only updates master docs, will you update 2.9.1 docs? https://github.com/apache/pulsar/tree/master/site2/website/versioned_docs/version-2.9.1

**Comment by Anonymitaet** [comment]
@nodece 2.9.2 is on the way. Will this change apply to the 2.9.2 doc set as well? (currently, we do not have the 2.9.2 doc set yet. I can generate if needed）

**Comment by nodece** [comment]
@momo-jun @Anonymitaet Thanks for your point! I double-check that the Pulsar Docker image, the Pulsar 2.8-lastest requires JDK 11, not JDK 8. 

This PR has been updated, please take a look if you have time.

**Review by codelipenghui — CHANGES_REQUESTED** [review]
Pulsar support JDK8 or later, not required JDK11, do you see any problem when running on JDK8?

We have compiler configurations in pom.xml

```xml
    <maven.compiler.source>8</maven.compiler.source>
    <maven.compiler.target>8</maven.compiler.target>
```

**Comment by nodece** [comment]
@codelipenghui I suggest that the version here should be consistent with the version in the Docker image, avoid don't support some features like some TLS configuration.

**Comment by codelipenghui** [comment]
> @codelipenghui I suggest that the version here should be consistent with the version in the Docker image.

But the Requirments section is updated.

**Comment by nodece** [comment]
Can we add a suggestion version of JDK?

**Comment by codelipenghui** [comment]
> Can we add a suggestion version of JDK?

Yes, look good to me.

**Review by lhotari — APPROVED** [review]

**Pull request merged**
