### PR TITLE
[fix][doc] Reflect archived and halted repositories

### PR DESCRIPTION
**Pull request by tisonkun**
cc @dave2wave @merlimat 

### Documentation

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by dave2wave — CHANGES_REQUESTED** [review]
Rather than delete references to the no longer maintained repositories each should be listed in an "Archived/Unsupported" section after the other repositories.

**Comment by tisonkun** [comment]
@dave2wave thanks for your review. Resolved at 1ba2e760443d97717d573842b0ce85ae569a8a93.

**Comment by tisonkun** [comment]
ping @merlimat @dave2wave

**Review by dave2wave — APPROVED** [review]
Thanks for those changes

**Pull request merged**
