### PR TITLE
[Issue 7873][chore]: remove unused field

### LINKED ISSUE #7873: Unused Field
https://github.com/apache/pulsar/blob/f53c9d33176a06a9a283beea9269d802c467f71e/pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/ConsumerConfiguration.java#L49

This field is never used.

### PR DESCRIPTION
**Pull request by kezhenxu94**
Closes #7873

- Motivation
Remove unused field

- Modifications
Remove field `initializeSubscriptionOnLatest` in class ConsumerConfiguration

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Comment by kezhenxu94** [comment]
closing as no update

**Pull request merged**
