### PR TITLE
[pulsar-functions][python-examples] Fixing python function example custom_object_function.py

### PR DESCRIPTION
**Pull request by marcusalmeida**
### Motivation

Fixing Python examples for pulsar-functions custom_object_function.py

### Modifications

Adding conversion of "str" to "bytes" using the methods "encode" and "decode" from string.

To perform the tests run:
```sh
$ bin/pulsar-admin functions create \
 --py $PULSAR_HOME/examples/python-examples/custom_object_function.py \
 --tenant public \
 --namespace default \
 --name custom_object \
 --inputs input-topic \
 --custom-serde-inputs '{"input-topic": "custom_object_function.CustomSerDe"}' \
 --output output-topic \
 --output-serde-classname custom_object_function.CustomSerDe \
 --classname custom_object_function.CustomObjectFunction 
 ```

And trigger the function using the CLI "functions trigger" :
```sh
$ pulsar-admin functions trigger \
  --name custom \
  --tenant public \ 
  --namespace default \
  --trigger-value "1,2"
```
And should return:
 
12, 26

 
### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): no
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no
  - The rest endpoints: no
  - The admin cli options: no
  - Anything that affects deployment: no

### Documentation

  - Does this pull request introduce a new feature? no
 
Hi, @srkukarni, can you please take a look?

### CODE REVIEW

**Comment by marcusalmeida** [comment]
@sijie I tested using different Python versions (2.7.15+ and 3.6.8).

I created two virtualenvs one for each version and ran the Pulsar in standalone mode in each virtualenv. And this code works.

**Comment by sijie** [comment]
@marcusalmeida cool

**Comment by sijie** [comment]
run cpp tests
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by gh777777** [comment]
@sijie thank you for making this example works! I'm learning pulsar functions dev in python. About this example (custom_object_function.py), how can I build and send a custom object in producer, so that I can get it back like that from the input in CustomObjectFunction.process(self, input, context)? Do I have to use schema?

**Pull request merged**
