### PR TITLE
clear old function failure exception from stats

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

Right now, if function fails first time and then starts and runs successfully then still function-stats shows old exception in stats which confuses user regarding function current state.

### Modifications

Hide old exception if function started successfully.

### CODE REVIEW

**Comment by sijie** [comment]
retest this please

**Comment by rdhabalia** [comment]
rerun java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
rerun java8 tests

**Comment by sijie** [comment]
run cpp tests

**Comment by sijie** [comment]
run cpp tests

**Pull request merged**
