### PR TITLE
[ISSUE 10176] fix npe in CmdTopics

### LINKED ISSUE #10176: NPE in pulsar-admin topics partitioned-stats
**To Reproduce**

```
$ bin/pulsar-admin topics create-partitioned-topic  partitioned-topic  --partitions 4
```
succeeds

```
$ bin/pulsar-admin topics partitioned-stats persistent-topic --per-partition

java.lang.NullPointerException
	at org.apache.pulsar.admin.cli.CmdTopics$GetPartitionedStats.run(CmdTopics.java:612)
	at org.apache.pulsar.admin.cli.CmdBase.run(CmdBase.java:86)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.run(PulsarAdminTool.java:281)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:328)
	
$ bin/pulsar-admin topics partitioned-stats persistent://public/default/persistent-topic --per-partition 

java.lang.NullPointerException
	at org.apache.pulsar.admin.cli.CmdTopics$GetPartitionedStats.run(CmdTopics.java:612)
	at org.apache.pulsar.admin.cli.CmdBase.run(CmdBase.java:86)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.run(PulsarAdminTool.java:281)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:328)	
```

**Expected behavior**

Stats or human-friendly error

**Additional context**
tried with pulsar standalone

### PR DESCRIPTION
**Pull request by linlinnn**
Fixes #10176

### Motivation
fix npe in CmdTopics

### Modifications
remove the member topics which causes npe easily. always use getAdmin().topics()

### CODE REVIEW

**Review by codelipenghui — CHANGES_REQUESTED** [review]
@linlinnn The change looks good to me, could you please help add a test to avoid the regression?

**Comment by codelipenghui** [comment]
This bug is only occurs on the master branch, no need to cherry-pick to branch-2.7

**Review by codelipenghui — APPROVED** [review]

**Review by 315157973 — APPROVED** [review]
How about
```
private Topics getTopics() {
        if (topics == null) {
            topics = getAdmin().topics();
        }
        return topics;
    }
```
change to
```
private Topics getTopics() {
        return getAdmin().topics();
    }
```

**Pull request merged**
