### PR TITLE
[improve][build] Upgrade Testcontainers to 1.18.3 & docker-java to 3.3.0

### PR DESCRIPTION
**Pull request by lhotari**
### Motivation

- keep the dependency up-to-date

### Modifications

Upgrade Testcontainers to 1.18.3 and docker-java to 3.3.0 .
docker-java version has to be kept in sync with Testcontainers version.

The correct version can be found in the testcontainers pom. For example for 1.18.3, one can find the docker-java version here: https://repo1.maven.org/maven2/org/testcontainers/testcontainers/1.18.3/testcontainers-1.18.3.pom

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Comment by lhotari** [comment]
this replaced previous PR #20519

**Review by michaeljmarshall — APPROVED** [review]

**Comment by tisonkun** [comment]
IIRC once we picked to a specific branch we remove the `release/xxx` label. But that can be argued to still mark which version is fixed.

cc @Technoboy- @RobertIndie

**Comment by michaeljmarshall** [comment]
I think the release label is supposed to stay on the PR.

**Comment by michaeljmarshall** [comment]
That's how I've been doing it for a year and a half.

**Comment by lhotari** [comment]
> IIRC once we picked to a specific branch we remove the `release/xxx` label. But that can be argued to still mark which version is fixed.
> 
> cc @Technoboy- @RobertIndie 

@tisonkun That's not how we have been using labels. 
We can always change the way. One of the problems is that the process isn't documented. I wrote 2 long emails on the dev list, but I guess nobody has been able to read those yet. 
This is the thread: https://lists.apache.org/thread/69mwjso51kzkrv5xgdmw04d9wngbg8br

**Review by nicoloboschi — COMMENTED** [review]
LGTM

**Pull request merged**
