### PR TITLE
[fix] [broker] Fix totalEntries calculation problem in AbstractBaseDispatcher#filterEntriesForConsumere

### PR DESCRIPTION
**Pull request by horizonzy**
fixes-#15297

### Motivation
Fix totalEntries calculation problem in AbstractBaseDispatcher#filterEntriesForConsumere

Need to update docs?

- [x] `no-need-doc` 
(Please explain why)

### CODE REVIEW

**Review by gaozhangmin — APPROVED** [review]

**Review by RobertIndie — APPROVED** [review]

**Review by codelipenghui — COMMENTED** [review]
Please help add a test to avoid regression.

**Comment by horizonzy** [comment]
Fine



发自我的iPhone


------------------ Original ------------------
From: lipenghui ***@***.***&gt;
Date: Mon,Apr 25,2022 10:08 PM
To: apache/pulsar ***@***.***&gt;
Cc: Yan Zhao ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [apache/pulsar] [fix] [broker] Fix totalEntries calculation problem in AbstractBaseDispatcher#filterEntriesForConsumere (PR #15298)





 
@codelipenghui commented on this pull request.
 
Please help add a test to avoid regression.

**Review by codelipenghui — APPROVED** [review]

**Review by hangc0276 — APPROVED** [review]

**Pull request merged**
