### PR TITLE
Closing FunctionAssignmentTailer should handle ConsumerAlreadyClosedException

### PR DESCRIPTION
**Pull request by sijie**
*Motivation*

Currently when FunctionAssignmentTailer throws RuntimeException when received
exception when tailing the assignment topic. Exception can be thrown when closing
the reader.

The runtime exception is the root cause why PulsarWorkerAssignmentTest timeouts
during shutting down.

*Modifications*

Handle AlreadyClosedException differently

### CODE REVIEW

**Comment by merlimat** [comment]
@sijie I think the shutdown timeout is still happening in this PR. should be fixed in https://github.com/apache/pulsar/pull/3749

**Comment by merlimat** [comment]
run java8 tests

**Comment by jerrypeng** [comment]
run java8 tests

**Comment by jerrypeng** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by jerrypeng** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by srkukarni** [comment]
run java8 tests

**Comment by merlimat** [comment]
rerun tests please

**Comment by merlimat** [comment]
retest this please

**Comment by merlimat** [comment]
retest this please

**Comment by merlimat** [comment]
retest this please

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Pull request merged**
