### PR TITLE
[improve][authentication] Adapt basic authentication configuration with prefix

### PR DESCRIPTION
**Pull request by nodece**
Signed-off-by: Zixuan Liu <nodeces@gmail.com>

### Motivation

Fix https://github.com/apache/pulsar/pull/16526#discussion_r920269032, which supports the following config:
```
basicAuthConf=data:;base64,YOUR-BASE64
basicAuthConf=file:///my/basic.conf
basicAuthConf=YOUR-BASE64
basicAuthConf=/my/basic.conf
```

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [ ] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [x] `doc-complete` - https://github.com/apache/pulsar/pull/16941

### CODE REVIEW

**Review by Technoboy- — APPROVED** [review]
LGTM

**Comment by mattisonchao** [comment]
Hi, @nodece 
Could you help to cherry-pick this PR for branch-2.9?

**Comment by nodece** [comment]
Move `release/2.9.4` to #16944.

**Comment by nodece** [comment]
Move `release/2.7.5` to #16947.

**Pull request merged**
