### PR TITLE
Upgrade BookKeeper to 4.12.0

### PR DESCRIPTION
**Pull request by eolivelli**
Upgrade Apache BookKeeper to 4.12.0

Most notable changes that impact this patch are:
- BP-41 -> "BookieSocketAddress" becomes "BookieId"
- BP-42 -> LedgerMetadata now carries "ledgerId" (as a transient non serialized value)

### CODE REVIEW

**Comment by eolivelli** [comment]
@jiazhai now that you released BK 4.12.0 this patch should be good to go as soon as CI passes

**Comment by eolivelli** [comment]
@jiazhai @codelipenghui @sijie @merlimat @rdhabalia 
the patch is ready for review.
The failures on CI are not caused by the upgrade, some day ago with BK 4.12.0-SNAPSHOT all of the tests passed
they look like flaky tests

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
