### PR TITLE
Convert latency to millisecond in producer stats

### LINKED ISSUE #5025: ProducerStats invalid stat values
Producer latency stat values are actually in microseconds, but ProducerStats method names state that it should be milliseconds.

### PR DESCRIPTION
**Pull request by liketic**
Closes #5025

### CODE REVIEW

**Comment by codelipenghui** [comment]
@liketic There is some problems with the license header, you can use `mvn license:format` to format the license header.

**Comment by liketic** [comment]
Thank you @codelipenghui . It's really useful for me.

**Comment by liketic** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Pull request merged**
