### PR TITLE
[sql] Upgrade PrestoSQL to the first Trino version

### PR DESCRIPTION
**Pull request by tisonkun**
### Motivation

See also previous discussion at https://lists.apache.org/thread/mflm0pb5235jjk80vol0vs7v0hvowkq8.

Instead of firstly create a pulsar-sql repository and highly possibly leave it uncompleted, the original pain points of maintaining Pulsar SQL (a.k.a. Pulsar Presto Connector) are:

1. Pulsar (All) docker image is too large.
2. PrestoSQL version is too old and pollutes old dependencies.

Thus, I'd suggest we continuously kaizen the situation by upgrading version and decouple modules. When moving out the codebase to another repository a trivial step, we consider to do it.

This patch is a small step to upgrade PrestoSQL to the first Trino version which supports Apple M1, and it contains most of the renaming work.

After this change, if users running sql worker with pulsar provided scripts, the experience should be as usual. But people directly depend on pulsar-presto-connector will find the dependency is switched to Trino. I'm unsure whether or not I should write a PIP of this kaizen way.

I'll treat this change at the earliest in 2.12 release train and don't rush things.

### Modifications

1. Update dependencies in `pom.xml` from `io.prestosql` to `io.trino`.
2. Update `prestosql` in code to `trino`.

~~Fortunately, the breaking changes mentioned in #16494 aren't included in this version bump.~~

3. Fix timestamp breaking changes in https://github.com/trinodb/trino/commit/21e3ddf55a641e1c17b7e4a17689223ff1120b42 and https://github.com/trinodb/trino/commit/19811d3d58e908d145639b1975ec111a0002e138. This exists in the first Trino version (351).
4. Update joda-time to 2.10.10 to catch up Trino 363's requirement, see https://github.com/apache/pulsar/pull/16683/commits/848e66fefa42d020ea61a566f063e8743b531cbf in details.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is already covered by existing tests. We should keep all existing test passed.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes)

### Documentation

- [x] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [ ] `doc-not-needed` 

It should be required. But leave it as is to verify CI first.

### CODE REVIEW

**Comment by tisonkun** [comment]
This patch should be technically completed.

cc @merlimat @lhotari @MarvinCai if you have spare time, please read the description above and see what direction is good to go.

**Comment by tisonkun** [comment]
If we can upgrade prestosql to trino, we may have an opportunity to rename the folder, and thus move `conf/presto` to `trino/conf` and `lib/presto/*` to `trino/*`, so that we can later smoothly move out the Pulsar SQL components.

**Review by merlimat — APPROVED** [review]
👍 Great work!

**Comment by tisonkun** [comment]
Thank @merlimat for review! I push a new commit to fix license issues. Our CI doesn't check binary licenses of Pulsar SQL, though. It can be a separated issue to resolve and here is https://github.com/apache/pulsar/issues/16783.

cc @MarvinCai @lhotari @codelipenghui perhaps you can also give a review on this patch and decide how to move forward?

**Comment by tisonkun** [comment]
I think all required tasks have passed.

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
