### PR TITLE
[Issue 5098] [doc] Fix wrong reference in kubernetes deployment README.md

### LINKED ISSUE #5098: [Doc] Wrong reference in kubernetes deployment README.md
image
The reference of Kubernetes.md seems linked to the wrong path.

### PR DESCRIPTION
**Pull request by lsy180829**
### Motivation

Fixes #5098

### Modifications

Modify the relative path in README.md (pulsar/deployment/kubernetes/README.md)

### CODE REVIEW

**Comment by sijie** [comment]
run java8 tests

**Comment by murong00** [comment]
run java8 tests

**Comment by lsy180829** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Pull request merged**
