### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shiv4289**
Intellij needs the lombok plugin to generate the code (getter, setter, data etc) used in this project.

### CODE REVIEW

**Comment by merlimat** [comment]
run integration tests

**Comment by jiazhai** [comment]
run integration tests

**Comment by sijie** [comment]
run java8 tests

**Comment by skyrocknroll** [comment]
run integration tests

**Comment by skyrocknroll** [comment]
run java8 tests

**Comment by skyrocknroll** [comment]
run cpp tests

**Comment by shiv4289** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Pull request merged**
