### PR TITLE
Get schema info with topic partition

### LINKED ISSUE #4730: Can't get schema info with topic partition
**Describe the bug**

If topic is a partitioned topic, use topic name can get schema info correct. But if use topic partition (e.g. persistent://my-tenant/my-namespace/my-topic-partitiion-0), can't get a schema info.

**To Reproduce**
1.create a new partitioned topic
2.create producer with schema
3.use pulsar admin to get schema info with topic partition

**Expected behavior**

If use topic partition to get schema info should return the partitioned topic schema info.

### PR DESCRIPTION
**Pull request by congbobo184**
### Motivation
to fix #4730
Get schema info with topic partition
### Verifying this change
Add the tests for it

Does this pull request potentially affect one of the following parts:
If yes was chosen, please highlight the changes

Dependencies (does it add or upgrade a dependency): (no)
The public API: (no)
The schema: (yes)
The default values of configurations: (no)
The wire protocol: (no)
The rest endpoints: (no)
The admin cli options: (no)
Anything that affects deployment: (no)

### Documentation
Does this pull request introduce a new feature? (yes / no)
If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
If a feature is not applicable for documentation, explain why?
If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by jiazhai** [comment]
run cpp tests
run integration tests

**Comment by codelipenghui** [comment]
run cpp tests
run integration tests

**Comment by codelipenghui** [comment]
run cpp tests

**Comment by congbobo184** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
Change the Milestone to 2.4.2, because of conflict.

**Pull request merged**
