### PR TITLE
[pulsar-common] Support Snappy compression for Java

### PR DESCRIPTION
**Pull request by murong00**
### Motivation

Support Snappy compression (https://google.github.io/snappy/) for Java/C++.

### CODE REVIEW

**Comment by jiazhai** [comment]
retest this please

**Comment by merlimat** [comment]
retest this please

**Comment by sijie** [comment]
@murong00 

the cpp format check failed.

```
-- Build files have been written to: /pulsar/pulsar-client-cpp
Scanning dependencies of target check-format
clang-format checks failed, run 'make format' to fix
CMakeFiles/check-format.dir/build.make:57: recipe for target 'CMakeFiles/check-format' failed
make[3]: *** [CMakeFiles/check-format] Error 255
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/check-format.dir/all' failed
make[2]: *** [CMakeFiles/check-format.dir/all] Error 2
CMakeFiles/Makefile2:106: recipe for target 'CMakeFiles/check-format.dir/rule' failed
make[1]: *** [CMakeFiles/check-format.dir/rule] Error 2
Makefile:175: recipe for target 'check-format' failed
make: *** [check-format] Error 2
Build step 'Execute shell' marked build as failure
```

You can run `pulsar-client-cpp/docker-format.sh` to format the cpp code.

**Comment by murong00** [comment]
@sijie Thanks a lot, done.

**Comment by murong00** [comment]
@sijie Oops..It seems to have to support c++ client as the same time to pass the unit tests. I will fix it later.

**Comment by murong00** [comment]
run cpp tests

**Comment by merlimat** [comment]
@murong00 Do you plan to also enable Snappy on Python & Go wrappers?

**Comment by murong00** [comment]
@merlimat done in #4319, please take a look, thanks.

**Comment by liangyuanpeng** [comment]
i try to make,but i got the some error

```
lanrendeMBP:pulsar-client-cpp lanren$ sudo make
[  0%] Building CXX object lib/CMakeFiles/pulsarShared.dir/CompressionCodecSnappy.cc.o
/Users/lanren/Documents/repositorys/git/pulsar/pulsar-client-cpp/lib/CompressionCodecSnappy.cc:38:59: error: use of undeclared identifier 'res'
        LOG_ERROR("Failed to compress to snappy. res=" << res);
                                                          ^
/Users/lanren/Documents/repositorys/git/pulsar/pulsar-client-cpp/lib/CompressionCodecSnappy.cc:51:28: error: no matching function for call to 'snappy_uncompress'
    snappy_status status = snappy_uncompress(encoded.data(), encoded.readableBytes(),
                           ^~~~~~~~~~~~~~~~~
/usr/local/include/snappy-c.h:103:15: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'size_t *' (aka 'unsigned long *') for 4th argument
snappy_status snappy_uncompress(const char* compressed,
              ^
2 errors generated.
make[2]: *** [lib/CMakeFiles/pulsarShared.dir/CompressionCodecSnappy.cc.o] Error 1
make[1]: *** [lib/CMakeFiles/pulsarShared.dir/all] Error 2
make: *** [all] Error 2
```

@murong00

**Pull request merged**
