### PR TITLE
Fix TopicsImpl compile failure.

### PR DESCRIPTION
**Pull request by Technoboy-**
### Motivation
Fix TopicsImpl compile failure issue.

### Documentation

- [x] `no-need-doc`

### CODE REVIEW

**Comment by yuruguo** [comment]
The compile failure is releted to this [PR](https://github.com/apache/pulsar/pull/13388), the better resolution is as below:
image
@Technoboy-

**Comment by Shoothzj** [comment]
> The compile failure is releted to this [PR](https://github.com/apache/pulsar/pull/13388), the better resolution is as below: image @Technoboy-

+1

**Review by lhotari — APPROVED** [review]

**Comment by Technoboy-** [comment]
> 

Oh, yes.

**Comment by lhotari** [comment]
I merged this to fix the broken master branch and created #13436 to make the code match the refactorings.

**Pull request merged**
