### PR TITLE
[metadata] add MetadataCache#deleteRecursive

### PR DESCRIPTION
**Pull request by Jason918**
### Motivation

`MetadataStore#deleteRecursive` is useful to clean up metadata, when user deletes a tenant or a namespace or a topic.

And old implementation like `org.apache.pulsar.broker.resources.BaseResources#deleteRecursiveAsync` can be replaced with this method.
### Modifications

Add a new interface `MetadataCache#deleteRecursive`, and use `MetadataStore#deleteRecursive` to do the actual deletion.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:
  - Add org.apache.pulsar.metadata.MetadataCacheTest#deleteRecursiveTest

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 
  
  
- [x] `doc` 
  
Added java doc of `MetadataCache#deleteRecursive`

### CODE REVIEW

**Comment by merlimat** [comment]
@Jason918 In `BaseReosources` there's already access to `MetadataStore`, couldn't we just use that instead of exposing it also through the `MetadataCache` interface?

**Comment by Jason918** [comment]
> @Jason918 In `BaseReosources` there's already access to `MetadataStore`, couldn't we just use that instead of exposing it also through the `MetadataCache` interface?

Aha, yees, we can use `MetadataStore#deleteRecursive` solve the problem of `BaseResources#deleteRecursiveAsync`.

Actually I am a little confusing about why do we have `MetadataCache#delete` interface, as we can just use MetadataStore interface and all cache instance comes from store instance. 
And IMHO, delete a key in the underlying store from a cache interface is a little strange?

**Comment by merlimat** [comment]
Yes, the behavior for delete() is exactly the same because the cache is guaranteed to be invalidated in both cases, when the operation is done.

**Comment by Jason918** [comment]
> Yes, the behavior for delete() is exactly the same because the cache is guaranteed to be invalidated in both cases, when the operation is done.

That make sense. So this can also be applied to `MetadataCache#deleteRecursive()`, right? 

And I am not sure if we have other `MetadataStore#deleteRecursive` case in Pulsar. But I am working on a protocol handler, and this metadata module provides great abstraction, So I plan to widely use this in our implementation.

**Comment by Anonymitaet** [comment]
@Jason918 you always provide clear doc-related info in PR descriptions, thanks 👍

**Pull request closed without merging**
