### PR TITLE
[fix][Flaky-test] Fix bug in method testConsumerImpl of AutoScaledReceiverQueueSizeTest

### LINKED ISSUE #15323: Flaky-test: AutoScaledReceiverQueueSizeTest.testConsumerImpl
AutoScaledReceiverQueueSizeTest.testConsumerImpl is flaky. It fails sporadically.

[example failure](https://github.com/apache/pulsar/runs/6168493028?check_suite_focus=true#step:11:645)

```
  Error:  testConsumerImpl(org.apache.pulsar.client.impl.AutoScaledReceiverQueueSizeTest)  Time elapsed: 10.215 s  <<< FAILURE!
  org.awaitility.core.ConditionTimeoutException: Condition with org.apache.pulsar.client.impl.AutoScaledReceiverQueueSizeTest was not fulfilled within 10 seconds.
  	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
  	at org.apache.pulsar.client.impl.AutoScaledReceiverQueueSizeTest.testConsumerImpl(AutoScaledReceiverQueueSizeTest.java:70)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

<!-- optionally provide the full stacktrace ->
<details>
<summary>Full exception stacktrace</summary>
<code><pre>
full exception stacktrace here
</pre></code>
</details>

### PR DESCRIPTION
**Pull request by codertmy**
Fixes #15323

### Motivation
Method testConsumerImpl of AutoScaledReceiverQueueSizeTest throw error when running.

### Modifications
Modify the order of the two lines of code as follow:
   Awaitility.await().until(consumer.scaleReceiverQueueHint::get);
   Assert.assertNotNull(consumer.receive());

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below or label this PR directly.

Need to update docs? 
- [x] `no-need-doc`

### CODE REVIEW

**Review by Jason918 — APPROVED** [review]

**Review by Technoboy- — APPROVED** [review]

**Review by RobertIndie — APPROVED** [review]

**Review by HQebupt — APPROVED** [review]

**Review by Technoboy- — COMMENTED** [review]
The test fails again of this method.
Need more fixes for this method.

**Comment by codertmy** [comment]
I will fix it

**Comment by Jason918** [comment]
> The test fails again of this method.
> Need more fixes for this method.

Seems the same reason.

**Review by Jason918 — APPROVED** [review]

**Review by mattisonchao — COMMENTED** [review]
Could you add more information to explain why this change can fix the flaky test?

**Review by mattisonchao — APPROVED** [review]

**Comment by codertmy** [comment]
It's a concurrent issue.
Thread A : (IO thread)
1. Receive msg from broker
2. incomingMessages.offer(message)
3. scaleReceiverQueueHint.set(getAvailablePermits() + incomingMessages.size() >= getCurrentReceiverQueueSize());

Thread B: (main test thread)
1. producer.send message
2. consumer.receive message 
If ThreadB.2 happen between ThreadA.2 and ThreadA.3, `scaleReceiverQueueHint` won't be set to true.

**Review by lhotari — APPROVED** [review]

**Pull request merged**
