### PR TITLE
Upgrade bk version to 4.10.0

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <ranxiaolong716@gmail.com>

### Motivation

Bump Apache Bookkeeper version to `4.10.0` to bring bug fixes from bookkeeper for Pulsar.

### Modifications

Upgrade Apache Bookkeeper version to `4.10.0`.

### CODE REVIEW

**Comment by wolfstudy** [comment]
@sijie @jiazhai @merlimat PTAL

**Comment by sijie** [comment]
@eolivelli Can you help review this pull request?

**Comment by wolfstudy** [comment]
run java8 tests
run integration tests

**Comment by wolfstudy** [comment]
run java8 tests
run integration tests

**Comment by eolivelli** [comment]
Sure

**Comment by eolivelli** [comment]
I see changes that are not needed due to the bk upgrade.
Can you please add a more detailed description of the change? You are talking about some bug fix.

There is also no new test added, please motivate

**Comment by sijie** [comment]
@eolivelli I think there are some changes made by Matteo in bookkeeper 4.10. we would like those changes to land in Pulsar. I think @wolfstudy can rephrase the motivation to "bump bookkeeper version to 4.10 to bring bug fixes from bookkeeper for Pulsar".

> I see changes that are not needed due to the bk upgrade.

I think all these changes are required due to interface changes in bookkeeper. 

> I will upgrade bk in my project that it is already using Pulsar.

wow. didn't know you are already using Pulsar. a blog post? :)

**Comment by wolfstudy** [comment]
> I hope that Pulsar 2.4.x is able to run with bk 4.10 without changes

Yes, this is what I hope, but in fact, we can't do it. When i upgrade the bk version to 4.20.0, `mvn clean install -DskipTests` execution failed. 

Because the interface `LedgerMetadata` and `RackChangeNotifier` had been changed, as follows:

https://github.com/apache/bookkeeper/pull/2092
https://github.com/apache/bookkeeper/pull/2006

**Comment by merlimat** [comment]
The main fix I was concerned about is the read-ahead fix. Without that the read performance is very poor: https://github.com/apache/bookkeeper/pull/2172

**Comment by wolfstudy** [comment]
run java8 tests
run cpp tests
run integration tests

**Comment by wolfstudy** [comment]
> org.apache.pulsar.broker.service.BrokerBkEnsemblesTests.testSkipCorruptDataLedger

run java8 tests

**Comment by wolfstudy** [comment]
run integration tests

**Comment by wolfstudy** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by wolfstudy** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
> org.apache.pulsar.broker.admin.AdminApiTest.setup
> org.apache.pulsar.broker.admin.v1.V1_AdminApiTest.setup

run java8 tests

**Comment by wolfstudy** [comment]
> org.apache.pulsar.tests.integration.functions.PulsarStateTest.pulsar-standalone-suite

run integration tests

**Comment by wolfstudy** [comment]
> org.apache.pulsar.proxy.server.ProxyLookupThrottlingTest.testLookup

test java8 tests

**Comment by wolfstudy** [comment]
> org.apache.pulsar.proxy.server.ProxyLookupThrottlingTest.testLookup

run java8 tests

**Comment by eolivelli** [comment]
@sijie in the release noted of 4.10.0 I did not mention this new Exception, it is kind of breaking change in the API.

Shall we add a warning in the breaking changed section if the release notes?

Can you send a PR with your findings about breaking changes?

**Comment by sijie** [comment]
> in the release noted of 4.10.0 I did not mention this new Exception, it is kind of breaking change in the API.

@eolivelli yes we should update the release notes of bookkeeper 4.10.0.

**Comment by wolfstudy** [comment]
> org.apache.pulsar.broker.stats.PrometheusMetricsTest.testPerNamespaceStats
org.apache.pulsar.broker.stats.PrometheusMetricsTest.testPerTopicStats

run java8 tests

**Comment by wolfstudy** [comment]
run java8 tests
run integration tests

**Comment by wolfstudy** [comment]
run cpp tests

**Comment by wolfstudy** [comment]
run java8 tests
run integration tests

**Comment by wolfstudy** [comment]
> org.apache.pulsar.broker.service.SubscriptionSeekTest.testSeekTimeOnPartitionedTopic

run java8 tests

**Comment by wolfstudy** [comment]
> org.apache.pulsar.io.PulsarFunctionE2ETest.testPulsarFunctionStats
org.apache.pulsar.io.PulsarFunctionE2ETest.testPulsarSinkStatsWithFile
org.apache.pulsar.io.PulsarFunctionE2ETest.testPulsarSinkStatsWithUrl
org.apache.pulsar.io.PulsarFunctionE2ETest.testPulsarSourceStatsWithFile
org.apache.pulsar.io.PulsarFunctionE2ETest.testPulsarSourceStatsWithUrl

run java8 tests

**Comment by wolfstudy** [comment]
> org.apache.pulsar.client.impl.schema.KeyValueSchemaInfoTest.encodeDecodeNestedKeyValueSchemaInfo
org.apache.pulsar.client.impl.schema.KeyValueSchemaInfoTest.encodeDecodeNestedKeyValueSchemaInfo
org.apache.pulsar.client.impl.schema.KeyValueSchemaInfoTest.encodeDecodeNestedKeyValueSchemaInfo
org.apache.pulsar.client.impl.schema.KeyValueSchemaInfoTest.testKeyValueSchemaInfoToString
org.apache.pulsar.client.impl.schema.PrimitiveSchemaTest.allSchemasShouldRoundtripInput
org.apache.pulsar.client.impl.schema.PrimitiveSchemaTest.allSchemasShouldSupportNull

run java8 tests

**Pull request merged**
