### PR TITLE
[functions] Default functionAuthProvider when running in k8s

### PR DESCRIPTION
**Pull request by addisonj**
### Motivation

In 2.4.x, when running with the KubernetesRuntime, it default to always
using the KubernetesSecretAuthProvider class. With the change in 2.5 to
making this behavior pluggable, there is currently a bug in that it
doesn't keep this behavior and requires a new configuration option to be
passed.

### Modifications

This commit changes the config so that it defaults to the correct class
when we are running with a kubernetes runtime. This restores the
behavior match that of earlier versions

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:

- Added a test that ensures that we get the correct default based on other config values

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): n
  - The public API: n
  - The schema: n
  - The default values of configurations: y
  - The wire protocol:n
  - The rest endpoints: n
  - The admin cli options: n
  - Anything that affects deployment: n

### Documentation

  - Does this pull request introduce a new feature? n
  - If yes, how is the feature documented? n/a
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by sijie** [comment]
@addisonj can you rebase this pull request to include some improvements in the github action files?

**Comment by addisonj** [comment]
@sijie I did the rebase, looks to have still failed some

**Comment by sijie** [comment]
@addisonj can you try to rebase again? I just merge a pull request with bunch of improvements in integration tests.

**Comment by tuteng** [comment]
Please take a look at this test: https://github.com/apache/pulsar/pull/6203/checks?check_run_id=446244014   @addisonj 

```
The exception was thrown with the wrong message: expected "Function language runtime is either not set or cannot be determined" but got "null"
	at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:71)
	at org.testng.internal.Invoker.considerExceptions(Invoker.java:1130)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:615)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
```

**Comment by tuteng** [comment]
ping @addisonj

**Comment by addisonj** [comment]
@tuteng rebased and ran the tests locally and they appear to pass

**Comment by addisonj** [comment]
whoops, ignore the last comment, am able to repro now, will fix

**Comment by addisonj** [comment]
@tuteng @sijie  It looks like all the tests passed at least once, notice the CPP tests are on the list twice, one passed? I think this is ready for merge

**Comment by addisonj** [comment]
@sijie you still want this for 2.5.1? All tests passed on this, it just looks like github is showing the checks twice

**Comment by addisonj** [comment]
this looks good to merge @sijie, not sure if you want for 2.5.1?

**Comment by sijie** [comment]
@addisonj thank you for your contribution!

**Pull request merged**
