### PR TITLE
[Doc] Add a note about sink-type and source-type value of the built-in connector.

### PR DESCRIPTION
**Pull request by Huanli-Meng**
### Motivation
In #7699, i update doc for the master only. The contents are approved and merged.

This PR is for updating docs for releases 2.6.1 --2.1.0

### Modifications

Update the following docs:

Pulsar IO > get started
Connector Admin CLI

### CODE REVIEW

**Comment by Huanli-Meng** [comment]
@jiazhai @Jennifer88huang , these updates are same as the ones for the master branch, which is approved and merged. Therefore, please help approve the PR.

**Comment by jiazhai** [comment]
seems there is new md files added, but side bar not included, @Huanli-Meng Would you please build and run the site locally to have a check?

**Comment by sijie** [comment]
@Huanli-Meng Can you take a look at @jiazhai 's comment?

**Comment by Huanli-Meng** [comment]
There is no need to update the sidebar. please feel free to approve the doc if there is no more comment.

**Pull request merged**
