### PR TITLE
[bookkeeper] bump bookkeeper version to 4.7.3

### PR DESCRIPTION
**Pull request by sijie**
*Motivation*

There are bunch of fixes in 4.7.3 regarding dns cache, ledger storage flushes.
4.7.3 is a minor release of 4.7.2, so it is safe to upgrade and included in 2.2.1 release

### CODE REVIEW

**Comment by merlimat** [comment]
retest this please

**Comment by merlimat** [comment]
retest this please

**Comment by sijie** [comment]
retest this please

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run cpp tests
run java8 tests

**Comment by sijie** [comment]
run cpp tests
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Pull request merged**
