### PR TITLE
Configure BK memory sizes automatically from JVM parameters

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

In BK 4.9, the DbLedgerStorage is already auto-tuning the mem sizes from the available memory in the JVM. Removing the fixed size default.

### CODE REVIEW

**Comment by merlimat** [comment]
run integration tests
run java8 tests

**Comment by jiazhai** [comment]
run integration tests

**Comment by merlimat** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by ivankelly** [comment]
rerun integration tests

**Comment by ivankelly** [comment]
We should enable -XX:+UseCGroupMemoryLimitForHeap  for the docker images to ensure that if this is running on a large machine in k8s, that it doesn't try to pull a huge amount of memory.

**Comment by ivankelly** [comment]
In fact, I'm going to hazard a guess that this is why integration tests are failing.

**Comment by ivankelly** [comment]
Not quite, but the failure is related to this change.

**Comment by merlimat** [comment]
The problem is that DbLedgerStorage is failing when the config key is present but empty: 

```
14:50:13.375 [main] ERROR org.apache.bookkeeper.server.Main - Failed to build bookie server
org.apache.commons.configuration.ConversionException: 'dbStorage_writeCacheMaxSizeMb' doesn't map to a Long object
	at org.apache.commons.configuration.AbstractConfiguration.getLong(AbstractConfiguration.java:884) ~[commons-configuration-commons-configuration-1.6.jar:1.6]
	at org.apache.commons.configuration.AbstractConfiguration.getLong(AbstractConfiguration.java:865) ~[commons-configuration-commons-configuration-1.6.jar:1.6]
	at org.apache.bookkeeper.bookie.storage.ldb.DbLedgerStorage.initialize(DbLedgerStorage.java:97) ~[org.apache.bookkeeper-bookkeeper-server-4.9.0.jar:4.9.0]
	at org.apache.bookkeeper.bookie.Bookie.<init>(Bookie.java:790) ~[org.apache.bookkeeper-bookkeeper-server-4.9.0.jar:4.9.0]
	at org.apache.bookkeeper.proto.BookieServer.newBookie(BookieServer.java:137) ~[org.apache.bookkeeper-bookkeeper-server-4.9.0.jar:4.9.0]
	at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:106) ~[org.apache.bookkeeper-bookkeeper-server-4.9.0.jar:4.9.0]
	at org.apache.bookkeeper.server.service.BookieService.<init>(BookieService.java:43) ~[org.apache.bookkeeper-bookkeeper-server-4.9.0.jar:4.9.0]
	at org.apache.bookkeeper.server.Main.buildBookieServer(Main.java:301) ~[org.apache.bookkeeper-bookkeeper-server-4.9.0.jar:4.9.0]
	at org.apache.bookkeeper.server.Main.doMain(Main.java:221) [org.apache.bookkeeper-bookkeeper-server-4.9.0.jar:4.9.0]
	at org.apache.bookkeeper.server.Main.main(Main.java:203) [org.apache.bookkeeper-bookkeeper-server-4.9.0.jar:4.9.0]
	at org.apache.bookkeeper.proto.BookieServer.main(BookieServer.java:314) [org.apache.bookkeeper-bookkeeper-server-4.9.0.jar:4.9.0]
Caused by: org.apache.commons.configuration.ConversionException: Could not convert  to java.lang.Long
	at org.apache.commons.configuration.PropertyConverter.toNumber(PropertyConverter.java:413) ~[commons-configuration-commons-configuration-1.6.jar:1.6]
	at org.apache.commons.configuration.PropertyConverter.toLong(PropertyConverter.java:280) ~[commons-configuration-commons-configuration-1.6.jar:1.6]
	at org.apache.commons.configuration.AbstractConfiguration.getLong(AbstractConfiguration.java:880) ~[commons-configuration-commons-configuration-1.6.jar:1.6]
	... 10 more
```

We want the key to be present (and empty) in the config file so that we can easily override in Docker environment.

Moving this to 2.3.1 since it will require a small change in BK side

**Comment by ivankelly** [comment]
:+1: we should take the Cgroup stuff into account in our images also though

**Comment by merlimat** [comment]
Sure, but that can be a bit tricky to enable in a general way because: 
 * CGroup mem limit might not have been set on the container, so we end up using all mem
 * `UseCGroupMemoryLimitForHeap` is basically setting the Xmx automatically based on the mem quota, but we also need to leave room for direct memory :/

**Comment by merlimat** [comment]
This was already done in #4297

**Pull request closed without merging**
