### PR TITLE
[Functions]Support protobuf schema for pulsar function

### PR DESCRIPTION
**Pull request by tuteng**
Fixes #<xyz>

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #<xyz>

### Motivation

Some users have encountered the following exception when using the protobuf schema, so add the relevant dependencies to the instance:

```
ERROR org.apache.pulsar.functions.instance.JavaInstanceRunnable - Sink open produced uncaught exception:
java.lang.IllegalArgumentException: com.google.protobuf.GeneratedMessageV3 is not assignable from bold.proto.PersonOuterClass$Person
	at org.apache.pulsar.client.impl.schema.ProtobufSchema.of(ProtobufSchema.java:110) ~
```

### Modifications

* Add the relevant dependencies to the instance

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

#### For contributor

For this PR, do we need to update docs?

- If yes, please update docs or create a follow-up issue if you need help.
  
- If no, please explain why.

#### For committer

For this PR, do we need to update docs?

- If yes,
  
  - if you update docs in this PR, label this PR with the `doc` label.
  
  - if you plan to update docs later, label this PR with the `doc-required` label.

  - if you need help on updating docs, create a follow-up issue with the `doc-required` label.
  
- If no, label this PR with the `no-need-doc` label and explain why.

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Review by gaoran10 — APPROVED** [review]
LGTM

**Review by eolivelli — APPROVED** [review]
Lgtm

It would be better to follow up and include an integration test.
Because we are actively working on the classpath for functions and I wouldn't like to see this broken

**Comment by tuteng** [comment]
> Lgtm
> 
> It would be better to follow up and include an integration test.
> Because we are actively working on the classpath for functions and I wouldn't like to see this broken

Thanks, I created an issue https://github.com/apache/pulsar/issues/11711  to track it and I will consider adding integration tests in the next pr.

**Comment by Anonymitaet** [comment]
@tuteng Thanks for your contribution. For this PR, do we need to update docs?

(The [PR template contains info about doc](https://github.com/apache/pulsar/blob/master/.github/PULL_REQUEST_TEMPLATE.md#documentation), which helps others know more about the changes. Can you provide doc-related info in this and future PR descriptions? Thanks)

**Comment by tuteng** [comment]
> @tuteng Thanks for your contribution. For this PR, do we need to update docs?
> 
> 
> 
> (The [PR template contains info about doc](https://github.com/apache/pulsar/blob/master/.github/PULL_REQUEST_TEMPLATE.md#documentation), which helps others know more about the changes. Can you provide doc-related info in this and future PR descriptions? Thanks) 

I think don't need to update the document, the document already exists.

**Pull request merged**
