### PR TITLE
[Doc] Add HBase sink connector guide

### PR DESCRIPTION
**Pull request by Anonymitaet**
Fix https://github.com/apache/pulsar/issues/5667

Get configurations from [HbaseSinkConfig.java](https://github.com/apache/pulsar/blob/master/pulsar-io/hbase/src/main/java/org/apache/pulsar/io/hbase/sink/HbaseSinkConfig.java) and [HbaseAbstractConfig.java](https://github.com/apache/pulsar/blob/master/pulsar-io/hbase/src/main/java/org/apache/pulsar/io/hbase/HbaseAbstractConfig.java)

Get configuration examples from [sinkConfig.yaml](https://github.com/apache/pulsar/blob/master/pulsar-io/hbase/src/test/resources/sinkConfig.yaml)

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@tuteng could you please help review? Thank you

**Comment by sijie** [comment]
run java8 tests

**Comment by tuteng** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Pull request merged**
