### PR TITLE
fix: add anonymous role to proxy configuration

### PR DESCRIPTION
**Pull request by jerrypeng**
### Motivation

Currently there is not configuration in proxy for anonymousUserRole.  We need to have it in order for anonymous roles to be able to be used when running a proxy

### CODE REVIEW

**Comment by jerrypeng** [comment]
rerun integration tests

**Comment by jerrypeng** [comment]
rerun java8 tests
rerun integration tests

**Comment by jerrypeng** [comment]
rerun java8 tests
rerun integration tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by jerrypeng** [comment]
rerun cpp tests

**Comment by sijie** [comment]
run cpp tests

**Pull request merged**
