### PR TITLE
[Issue 12672][test] Reduce unnecessary message send in testPeekWithSubscriptionNameNotExist

### LINKED ISSUE #12672: Flaky-test: PersistentTopicsTest.testPeekWithSubscriptionNameNotExist
PersistentTopicsTest is flaky. The testPeekWithSubscriptionNameNotExist test method fails sporadically.

[example failure](https://github.com/apache/pulsar/runs/4139503686?check_suite_focus=true#step:9:483)

```
Error:  Tests run: 50, Failures: 10, Errors: 0, Skipped: 21, Time elapsed: 211.054 s <<< FAILURE! - in org.apache.pulsar.broker.admin.PersistentTopicsTest
Error:  testPeekWithSubscriptionNameNotExist(org.apache.pulsar.broker.admin.PersistentTopicsTest)  Time elapsed: 60.065 s  <<< FAILURE!
org.apache.pulsar.client.api.PulsarClientException$TimeoutException: request timeout {'durationMs': '30000', 'reqId':'1030153108732970473', 'remote':'localhost/127.0.0.1:37151', 'local':'/127.0.0.1:45602'}
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:1008)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:91)
	at org.apache.pulsar.broker.admin.PersistentTopicsTest.testPeekWithSubscriptionNameNotExist(PersistentTopicsTest.java:682)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by Jason918**
Fixes #12672 

### Motivation

See  #12672 

### Modifications

Reduced the message send in this test.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is already covered by existing tests, such as testPeekWithSubscriptionNameNotExist itself.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 
  
- [x] `no-need-doc` 

Fix flaky test case.

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Review by 315157973 — COMMENTED** [review]
It does not seem to be a problem of message sending. The exception has already appeared when the Producer was created.

I can run this single unit test successfully, but it will fail to run the entire test class. It seems that other unit tests modify global variables and affect it.

**Comment by Jason918** [comment]
> It does not seem to be a problem of message sending. The exception has already appeared when the Producer was created.
> 
> I can run this single unit test successfully, but it will fail to run the entire test class. It seems that other unit tests modify global variables and affect it.

Yes, you are right, I will look into it.

**Comment by Jason918** [comment]
> It does not seem to be a problem of message sending. The exception has already appeared when the Producer was created.
> 
> I can run this single unit test successfully, but it will fail to run the entire test class. It seems that other unit tests modify global variables and affect it.

Something messed up with replicator.
Changed this topic to another tenant and namespace, this entire test class can pass now.

**Review by 315157973 — APPROVED** [review]
Great! Please fix the conflicts

**Comment by 315157973** [comment]
Has it been repaired? https://github.com/apache/pulsar/pull/12703

**Comment by Jason918** [comment]
> Has it been repaired? #12703

I don't think so. 
The test case blocked during the producer creation.

**Pull request merged**
