### PR TITLE
Fix topic name logic for partitioned topics

### PR DESCRIPTION
**Pull request by srkukarni**
### Motivation
When python functions do explicit acking using context.ack method, the topic name that they pass could be a partitioned topic. Partitioned Topics have a -partition-<partitionid> suffix attached to them. This means that when finding the right consumer to ack this message, we need to take into account the actual topic name without the suffix. This pr handles this case.
### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by jerrypeng** [comment]
@srkukarni PR looks good.  Can we add a unit test for this?

**Comment by srkukarni** [comment]
@jerrypeng added unittest

**Comment by srkukarni** [comment]
run java8 tests

**Comment by srkukarni** [comment]
run java8 tests

**Comment by srkukarni** [comment]
run java8 tests

**Comment by srkukarni** [comment]
run java8 tests

**Comment by srkukarni** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by cckellogg** [comment]
rerun java8 tests

**Comment by merlimat** [comment]
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by merlimat** [comment]
Merged in 2.3.1 at 1c6563eb81fdff69b8f6507881497a95659165d7

**Pull request merged**
