### PR TITLE
Allow to config Sasl configs in Kafka sink.

### PR DESCRIPTION
**Pull request by Shoothzj**
### Motivation
Allow pulsar io to push messages to sasl kafka cluster.

### Modifications

Add several kafka sasl configs, make them configable.

### Documentation
I think the pulsar-io can automatically generate the doc for added fields. So we don't need add any docs.

### CODE REVIEW

**Review by BewareMyPower — CHANGES_REQUESTED** [review]
Please add tests for these configs. You can modify the existed kafkaSinkConfig.yaml under resource directory.

**Comment by eolivelli** [comment]
for the tests simple unit tests around `KafkaAbstractSink#open()` is enough.
We do not need integration tests (they will be very heavyweight)

**Review by eolivelli — COMMENTED** [review]
The patch overall looks good to me
please add the tests as @BewareMyPower commented

**Review by BewareMyPower — APPROVED** [review]

**Review by murong00 — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
LGTM

**Pull request merged**
