### PR TITLE
[integration-tests]Enable messaging tests to integration tests.

### PR DESCRIPTION
**Pull request by codelipenghui**
Master Issue: #5452

### Motivation

Enable messaging tests to integration tests.

### CODE REVIEW

**Comment by sijie** [comment]
run cpp tests
run integration tests

**Comment by codelipenghui** [comment]
run java8 tests
run integration tests

**Comment by tuteng** [comment]
run integration tests

**Comment by jerrypeng** [comment]
@codelipenghui some of the PersistentTopicMessagingTest are failing

**Comment by codelipenghui** [comment]
run java8 tests

**Pull request merged**
