### PR TITLE
[fix] [broker] In Key_Shared mode: remove unnecessary mechanisms of message skip to avoid unnecessary consumption stuck

### PR DESCRIPTION
**Pull request by poorbarcode**
### Motivation
- https://github.com/apache/pulsar/pull/7105 provide a mechanism to avoid a stuck consumer affecting the consumption of other consumers: 
  - if all consumers can not accept more messages, stop delivering messages to the client.
  - if one consumer can not accept more messages, just read new messages and deliver them to other consumers.
- https://github.com/apache/pulsar/pull/7553 provide a mechanism to fix the issue of lost order of consumption: If the consumer cannot accept any more messages, skip the consumer for the next round of message delivery because there may be messages with the same key in the replay queue.
- https://github.com/apache/pulsar/pull/10762 provide a mechanism to fix the issue of lost order of consumption: If there have any messages with the same key in the replay queue, do not deliver the new messages to this consumer.

https://github.com/apache/pulsar/pull/10762 and https://github.com/apache/pulsar/pull/7553 do the same thing and https://github.com/apache/pulsar/pull/10762 is better than https://github.com/apache/pulsar/pull/7553 , so https://github.com/apache/pulsar/pull/7553 is unnecessary. 

### Modifications
remove the mechanism provided by https://github.com/apache/pulsar/pull/7553 to avoid unnecessary consumption stuck.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: 
- x

### CODE REVIEW

**Review by equanz — APPROVED** [review]
LGTM

I'll remove duplicated changes from https://github.com/apache/pulsar/pull/20179 when this PR is merged. (By the way, if you could, please check the new comments https://github.com/apache/pulsar/pull/20179#issuecomment-1543445903 ?)

**Comment by poorbarcode** [comment]
@equanz 

> By the way, if you could, please check the new comments https://github.com/apache/pulsar/pull/20179#issuecomment-1543445903 ?

Sorry, I've been so busy lately. I left a comment to you https://github.com/apache/pulsar/pull/20179#discussion_r1198087967

**Review by mattisonchao — APPROVED** [review]

**Comment by lhotari** [comment]
@poorbarcode just curious to know if the logic that was removed in this PR was causing problems. Is this PR an optimization or a bug fix?

**Comment by poorbarcode** [comment]
@lhotari 

> Is this PR an optimization or a bug fix?

I think it should be called a fix.

> just curious to know if the logic that was removed in this PR was causing problems. 

If there have two consumers `[c1, c2]` on the same subscription, and there have some messages in the `Replay Queue`, and the `c1` was stuck by the client and its `permits` came to `0`, the consumer `c2` will not receive any messages in the `Replay Queue`, it caused by the `nextStuckConsumers` is not empty(`c1`), then Dispatcher will try to read new messages, but there are no new messages now.

**Comment by lhotari** [comment]
@codelipenghui @massakam do you have a chance to do a post-merge review since you have worked a lot on Key_Shared?

**Comment by codelipenghui** [comment]
@lhotari It looks good to me https://github.com/apache/pulsar/pull/10762 covered the fix that https://github.com/apache/pulsar/pull/7553 do and this PR doesn't revert the tests introduced by https://github.com/apache/pulsar/pull/7553.

**Comment by lhotari** [comment]
> @lhotari It looks good to me #10762 covered the fix that #7553 do and this PR doesn't revert the tests introduced by #7553.

@codelipenghui @poorbarcode the part I'm wondering is the lack of tests for reproducing the problem that this PR intends to fix. Is there a way to add a test for this PR? /cc @Technoboy-

**Comment by poorbarcode** [comment]
@lhotari 

>  the part I'm wondering is the lack of tests for reproducing the problem that this PR intends to fix. Is there a way to add a test for this PR?

I will do this

**Pull request merged**
