### PR TITLE
[fix][broker][branch-3.2]  PersistentSubscription duplicate implementation interface Subscri…

### LINKED ISSUE #22354: [Cleanup] PersistentSubscription duplicate implementation interface Subscription
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

branch-3.2

### Minimal reproduce step

Code design issues

### What did you expect to see?

image

### What did you see instead?

image

PersistentSubscription implemented Subscription , in this 07c46fe9ef42a72de18be3267e70a51bbc883678 commit added to extends the AbstractSubscription class, and the AbstractSubscription class implements Subscription resulting in duplicate implementation of the Subscription
image

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by sherlock-lin**
…ption

Fixes #22354 

Main Issue: #xyz 

PIP: #xyz 

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [x] Dependencies (add or upgrade a dependency)
- [x] The public API
- [x] The schema
- [x] The default values of configurations
- [x] The threading model
- [x] The binary protocol
- [x] The REST endpoints
- [x] The admin CLI options
- [x] The metrics
- [x] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by Technoboy-** [comment]
I see the master branch also have the same issue, could you also push a fix for the master branch?

**Comment by sherlock-lin** [comment]
> I see the master branch also have the same issue, could you also push a fix for the master branch?

of course，I'll create a new pr for that.

**Comment by sherlock-lin** [comment]
> > I see the master branch also have the same issue, could you also push a fix for the master branch?
> 
> of course，I'll create a new pr for that.

new pr：https://github.com/apache/pulsar/pull/22359

**Comment by dao-jun** [comment]
since https://github.com/apache/pulsar/pull/22359 created, do we still need this PR? Just cherry-pick https://github.com/apache/pulsar/pull/22359 to 3.2 after it get merged.

**Comment by lhotari** [comment]
I don't think that we should make such changes to branch-3.2 . This "duplication" isn't a problem at all.

**Pull request closed without merging**
