### PR TITLE
[improve][doc] Add casdoor document for administration-pulsar-manager

### PR DESCRIPTION
**Pull request by jakiuncle**
Fixes https://github.com/apache/pulsar-manager/pull/446
**Modifications:**
Add document for casdoor.
1. How to install casdoor
2. How to use casdoor
3. What we need do in pulsar-manager code

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [ ] `doc-not-needed` 
(Please explain why)
  
- [x] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Comment by jakiuncle** [comment]
* [x] `doc`

**Comment by jakiuncle** [comment]
- [x ] `doc` 
(Your PR contains doc changes)

**Comment by hsluoyz** [comment]
@tuteng plz review

**Review by Anonymitaet — COMMENTED** [review]
Thanks for your contribution! 

Suggest using SVG rather than PNG because:

- Adaptive. 

  SVG images are adapted to the different sizes of the Chrome window automatically.

- Sharper and smaller. 

  Compared with png images, SVG images are more crisp and clean, and they are in smaller sizes.

- Quality

  SVG is vector-based and can expand to any size without losing resolution

- Accessibility

  SVG is XML-based and can be read by both human readers and machines like search engines (for SEO purposes).

Details see https://docs.google.com/document/d/16Hp7Sc86MQtL0m8fc2w_TrcKXAuglwRwHmdmwfk00mI/edit#bookmark=id.q8ccsj2e27xm

**Comment by jakiuncle** [comment]
@Anonymitaet  plz review,thank you

**Comment by Anonymitaet** [comment]
@jakiuncle please request a technical review first.
If it is technically correct, then technical writers can review it from the technical writing perspective.
Thank you! 😊

**Comment by jakiuncle** [comment]
@Anonymitaet who can i request?

**Comment by Anonymitaet** [comment]
> @tuteng plz review

Already asked a right reviewer.

**Comment by jakiuncle** [comment]
@Anonymitaet  Thank you

**Comment by hsluoyz** [comment]
gentle ping @tuteng

**Comment by jakiuncle** [comment]
@Anonymitaet

**Comment by hsluoyz** [comment]
@tuteng

**Comment by Anonymitaet** [comment]
@tuteng 
Could you please review this PR from a technical perspective? 
If it is technically correct, then technical writers can review it from the technical writing perspective.
Thank you! 😊

**Comment by tuteng** [comment]
casdoor is an optional authentication plugin for pulsar-manager, should this documentation be more appropriately placed in the [pulsar-manager repository](https://github.com/apache/pulsar-manager/pull/484/files)? @hsluoyz

**Comment by jakiuncle** [comment]
Hi ,place here? [#49](https://github.com/apache/pulsar-manager/pull/499)

**Comment by tisonkun** [comment]
Closed as superseded by https://github.com/apache/pulsar/pull/17324#issuecomment-1323047379.

**Comment by hsluoyz** [comment]
It looks good to me, thanks!

**Pull request closed without merging**
