### PR TITLE
[fix][broker] log update in class:LeastResourceUsageWithWeight

### PR DESCRIPTION
**Pull request by StevenLuMT**
### Motivation
base PR: #18964 ,log update in class(org.apache.pulsar.broker.loadbalance.extensions.strategy.LeastResourceUsageWithWeight)

### Modifications

when log's level is debug,call log.debug to print log

### Verifying this change
- [x] Make sure that the change passes the CI checks.
This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation
Check the box below or label this PR directly.

Need to update docs?

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository
PR in forked repository: https://github.com/StevenLuMT/pulsar/pull/9

### CODE REVIEW

**Review by AnonHxy — APPROVED** [review]

**Review by Technoboy- — CHANGES_REQUESTED** [review]
New loadbalancer has always been print `info` log with this flag.

**Comment by StevenLuMT** [comment]
@heesung-sn help me review it ,thanks

**Comment by heesung-sn** [comment]
We print info logs under the debugMode flag. Whats the intention?

**Comment by StevenLuMT** [comment]
> We print info logs under the debugMode flag. Whats the intention?

image

@heesung-sn In your PR #18964 ,you print info log in debugMode flag, 
but I think when debugMode is true,we should print debug log in PR #20168

**Comment by heesung-sn** [comment]
The intention under this debugMode flag is to dynamically print the useful operational logs when there are issues and monitor the decision logics. One can turn off this debug more, when done. With this dynamic flag, one does not need to change the log level as it currently outputs logs at the info level. I understand some other projects strictly follow printing such logs at the debug level. However, it appears that Pulsar does not have such strict practice as we have other code that print info level logs under such debug flag.

I would let Pulsar PMC members deice on such practice, and we follow their decision.

**Comment by tisonkun** [comment]
Closed as no consensus. There is no relation between `debugMode` and `debug` log level.

**Pull request closed without merging**
