### PR TITLE
Add Maven Source Plugin.

### PR DESCRIPTION
**Pull request by codelipenghui**
### Motivation

Allow maven or gradle to download pulsar client source.

### Modifications

Add maven source plugin in pulsar.pom

### CODE REVIEW

**Comment by merlimat** [comment]
@codelipenghui I think the sources should be already attached and published on maven repo: http://central.maven.org/maven2/org/apache/pulsar/pulsar-client/2.1.1-incubating/ 

Is it failing to find them?

**Comment by merlimat** [comment]
I think I see the problem: `pulsar-client` is the shaded module. It includes `pulsar-client-original` and its dependencies. 

For `pulsar-client-original` the sources and javadoc jars appear to be correct (http://central.maven.org/maven2/org/apache/pulsar/pulsar-client-original/2.1.1-incubating/), but for `pulsar-client` the sources jar is empty, because the module itself has no Java sources. 

I don't think this PR will solve the problem either. We need a way to attach the orginal sources (and javadoc) to the shaded artifact.

**Comment by sijie** [comment]
@merlimat I think the sources jar is missing at snapshot

https://repository.apache.org/content/repositories/snapshots/org/apache/pulsar/pulsar-client-original/2.2.0-incubating-SNAPSHOT/

if we can configure the snapshot job to publish source jar, that's probably enough for @codelipenghui

**Comment by sijie** [comment]
> I still worry that the source jar for pulsar-client will be empty, given that module is just for shading purpose and has no sources.

yeah, I agreed. we should fix that as well.

**Comment by jiazhai** [comment]
retest this please

**Comment by sijie** [comment]
run cpp tests

**Pull request closed without merging**
