### PR TITLE
[cleanup][doc] Remove dangling pages develop-binary-protocol

### PR DESCRIPTION
**Pull request by tisonkun**
This closes https://github.com/apache/pulsar-site/issues/172.

Although we can redirect `develop-` to the proper `developing-` as:

```mdx
---
id: develop-binary-protocol
---

import {Redirect} from '@docusaurus/router';

<Redirect to="developing-binary-protocol" />
```

I notice that we don't always have a `develop-` page even in the incubating versions. So I regard all those `develop-` pages as dangling pages. We can just remove them.

<details>
<summary>develop- total 27:</summary>
<pre>
./site2/website/versioned_docs/version-2.2.0/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.2.1/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.3.0/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.3.1/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.3.2/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.4.0/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.4.1/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.4.2/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.5.0/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.5.1/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.5.2/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.6.0/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.6.1/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.6.2/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.6.3/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.6.4/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.7.0/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.7.1/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.7.3/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.7.4/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.8.0-deprecated/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.8.1-deprecated/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.8.2-deprecated/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.8.x/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.9.0-deprecated/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.9.1-deprecated/develop-binary-protocol.md
./site2/website/versioned_docs/version-2.9.x/develop-binary-protocol.md
</pre>
</details>

<details>
<summary>developing- total 37:</summary>
<pre>
./site2/docs/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.1.0-incubating/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.1.1-incubating/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.10.0-deprecated/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.10.1-deprecated/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.10.x/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.2.0/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.2.1/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.3.0/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.3.1/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.3.2/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.4.0/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.4.1/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.4.2/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.5.0/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.5.1/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.5.2/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.6.0/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.6.1/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.6.2/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.6.3/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.6.4/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.7.0/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.7.1/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.7.2/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.7.3/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.7.4/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.8.0-deprecated/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.8.1-deprecated/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.8.2-deprecated/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.8.3-deprecated/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.8.x/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.9.0-deprecated/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.9.1-deprecated/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.9.2-deprecated/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.9.3-deprecated/developing-binary-protocol.md
./site2/website/versioned_docs/version-2.9.x/developing-binary-protocol.md
</pre>
</details>

cc @urfreespace @Anonymitaet As we delete content files, https://github.com/apache/pulsar-site/issues/175 this issue can be significant to resolve later.

- [x] `doc`

### CODE REVIEW

**Comment by tisonkun** [comment]
cc @eolivelli @michaeljmarshall

**Review by michaeljmarshall — COMMENTED** [review]
Where is the source for these pages?

**Comment by tisonkun** [comment]
@michaeljmarshall what do you mean about "source"? I will say all `develop-binary-protocol` is duplicate of `developing-binary-protocol` under the same folder.

**Review by Anonymitaet — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Review by urfreespace — APPROVED** [review]

**Comment by michaeljmarshall** [comment]
@tisonkun - thanks for the explanation. I missed those duplicates.

**Review by michaeljmarshall — APPROVED** [review]

**Pull request merged**
