### PR TITLE
[fix][flaky-test]PulsarFunctionTlsTest.testFunctionsCreation

### PR DESCRIPTION
**Pull request by poorbarcode**
Fixes: #17112

### Motivation

Add more context

### Modifications

Add more context

### Documentation

- [ ] `doc-required` 
  
- [x] `doc-not-needed` 
  
- [ ] `doc` 

- [ ] `doc-complete`

### CODE REVIEW

**Review by lhotari — APPROVED** [review]

**Comment by lhotari** [comment]
@poorbarcode is this ready for merging?

**Review by nicoloboschi — APPROVED** [review]
good catch!

**Comment by poorbarcode** [comment]
Hi @lhotari 

> is this ready for merging?

Yes. I am writing `Motivation` to explain why this change, so labeled `[do not merge]`

**Comment by lhotari** [comment]
@poorbarcode I merged this. Thanks for making this change. you can write the motivation later.

**Comment by poorbarcode** [comment]
Hi @lhotari 

> I merged this. Thanks for making this change. you can write the motivation later.

Thanks, I have added the motivation, and I will continue to look up the root problems

**Comment by lhotari** [comment]
PulsarFunctionTlsTest still gets stuck in tearDown, here's a recent stacktrace:
```
"main" #1 prio=5 os_prio=0 cpu=43749.23ms elapsed=3506.78s tid=0x00007f965c026e90 nid=0xac2 waiting on condition  [0x00007f9660e26000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.4.1/Native Method)
	- parking to wait for  <0x0000100032218608> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.4.1/LockSupport.java:211)
	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.4.1/CompletableFuture.java:1864)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.4.1/ForkJoinPool.java:3463)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.4.1/ForkJoinPool.java:3434)
	at java.util.concurrent.CompletableFuture.waitingGet(java.base@17.0.4.1/CompletableFuture.java:1898)
	at java.util.concurrent.CompletableFuture.join(java.base@17.0.4.1/CompletableFuture.java:2117)
	at org.apache.pulsar.metadata.coordination.impl.LockManagerImpl.close(LockManagerImpl.java:163)
	at org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl.stop(ModularLoadManagerImpl.java:983)
	at org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerWrapper.stop(ModularLoadManagerWrapper.java:118)
	at org.apache.pulsar.functions.worker.PulsarFunctionTlsTest.tearDown(PulsarFunctionTlsTest.java:193)
```
in https://github.com/apache/pulsar/actions/runs/3044816917/jobs/4905919291#step:11:528

**Comment by poorbarcode** [comment]
Hi @lhotari 

> PulsarFunctionTlsTest still gets stuck in tearDown, here's a recent stacktrace:

Thank you. This information is very useful. I will try to find the root cause

**Pull request merged**
