### PR TITLE
[improve][doc] Update swagger for 2.10.2

### PR DESCRIPTION
**Pull request by Jason918**
### Motivation

Update swagger for 2.10.2

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] Anything that affects deployment

### Documentation

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by codelipenghui** [comment]
@Anonymitaet Will the swagger files move the `pulsar-site` repo?

**Comment by Anonymitaet** [comment]
> @Anonymitaet Will the swagger files move the `pulsar-site` repo?

@urfreespace @tisonkun can you take a look at the following questions? Thank you!

### Q1. 

Now the swagger files in [pulsar](https://github.com/apache/pulsar/tree/master/site2/website/static/swagger) are synced to [pulsar-site](https://github.com/apache/pulsar-site/tree/main/site2/website-next/static/swagger), can we remove swagger files in pulsar and only keep them in pulsar-site? (Does the REST API doc build process rely on the files in pulsar and must be completed in pulsar?)

### Q2. 

We use swagger for generating [REST API docs](https://pulsar.apache.org/admin-rest-api/?version=master) only.

Since we use one doc set now (2.10.x for 2.10.0, 2.10.1, 2.10.2, ...), does this mean we just need to generate REST API doc for 2.10.x only instead of generating for 2.10.0, 2.10.1, 210.2, ...?

If yes, the [release process](https://github.com/apache/pulsar/blob/master/wiki/release/release-process.md#update-swagger-file) needs to be updated (now release managers generate swagger files for each release), that is, swagger files should be only generated for major releases (2.10.x, 2.11.x, 2.12.x, ...) instead of minor releases (2.10.1, 2.10.2, ...).

cc @momo-jun @labuladong

**Comment by michaeljmarshall** [comment]
@Anonymitaet - We need to generate the swagger docs for each released version of Apache Pulsar. In my opinion, it is not sufficient to generate them frequently based on the current state of `branch-2.x` because the swagger docs are used to generate clients, and we want to provide stable versions of these docs.

We should move the swagger files to the pulsar-site repo because they are generated. Note that we already do this in this part of the website's generated doc files here: https://pulsar.apache.org/api/.

**Review by michaeljmarshall — APPROVED** [review]
LGTM. I don't think we should hold up @Jason918's work as release manager, so I am going to merge this PR.

**Comment by tisonkun** [comment]
@michaeljmarshall agree. You may notice #18014 for a similar proposal. I don't read through the logic about swagger files yet. I'll appreciate it if you can share your knowledge about this sync and build process, especially for the API/generated files.

**Pull request merged**
