### PR TITLE
[feat][io] [WIP] Creating Apache Ignite Connector

### LINKED ISSUE #6358: [pulsar-io] Create Apache Ignite connector for Pulsar
Apache Ignite is a rising distributed caching technology that is extremely fast and very stable. 
It has some similarities to Redis but is much more robust (since it's a distributed technology) and also supports the persistence of data. (It's smart about how data can be persisted.) It's also much faster than Redis. It might be the fastest distributed cache technology currently on the market. 
We really need to create a connector to write to Ignite to support data enrichment use cases and other use cases that require a cache layer that needs to be faster than Cassandra.

### PR DESCRIPTION
**Pull request by devinbost**
Fixes #6358

### Motivation
Apache Ignite is a very promising technology. We at least need to create a Pulsar sink that will allow us to write data from Pulsar into Ignite. This will encourage community integration between the two technologies. Ignite is a very useful technology for fast caching and is faster and more useful than Redis for most purposes. 

* [x] `doc-required`

### CODE REVIEW

**Comment by devinbost** [comment]
Note that development on this task is just starting, so it's not ready for review.

**Comment by sijie** [comment]
@devinbost maybe send it in a draft or make the title "[WIP]"

**Comment by tisonkun** [comment]
> Note that development on this task is just starting, so it's not ready for review.

I just noticed this comment. Then close as stale...

Feel free to resubmit the patch based on the current master branch if you'd still work for it.

**Pull request closed without merging**
