### PR TITLE
[2nd Storage]Extract common method in tiered storage to managed-ledger module

### PR DESCRIPTION
**Pull request by yjshen**
Move common ledger metadata SerDe methods to managed-ledger.

### CODE REVIEW

**Comment by yjshen** [comment]
@sijie PTAL, thanks!

**Comment by jiazhai** [comment]
Thanks for the help. lgtm

**Comment by jiazhai** [comment]
conflict with #6717, marked with 2.5.2

**Comment by jiazhai** [comment]
merged into branch-2.5

**Pull request merged**
