### PR TITLE
[fix][broker] Fix wrong double-checked locking for readOnActiveConsumerTask in dispatcher

### PR DESCRIPTION
**Pull request by BewareMyPower**
### Motivation

The access on `readOnActiveConsumerTask` is not thread safe.

```java
if (readOnActiveConsumerTask != null) {
    return;
}
readOnActiveConsumerTask = topic.getBrokerService().executor().schedule(() -> {/* ... */});
```

There is a case that:

| Steps | Thread 1 | Thread 2 |
| :- | :- | :- |
| 1 | Read `readOnActiveConsumerTask`: null | |
| 2 | call `schedule` | |
| 3 | | Read `readOnActiveConsumerTask`: null |
| 4 | | call `schedule` |
| 5 | Write `readOnActiveConsumerTask` to the result of `schedule` | |
| 6 | | Write `readOnActiveConsumerTask` to the result of `schedule` |

Then `schedule()` will be called twice and only one result (it could be either step 5 or 6) will be assigned to `readOnActiveConsumerTask`.

### Modifications

Follow the double-checked locking when `readOnActiveConsumerTask` is null to ensure `readOnActiveConsumerTask` cannot be called concurrently.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by lhotari — DISMISSED** [review]
LGTM. Good catch @BewareMyPower . I wonder if the same bug pattern is in other locations in the Pulsar code base?

**Review by lhotari — COMMENTED** [review]
@BewareMyPower Please also check that possible concurrent calls on scheduleReadOnActiveConsumer method aren't causing issues.

**Comment by BewareMyPower** [comment]
@lhotari `scheduleReadOnActiveConsumer` is thread safe. The steps of `scheduleReadOnActiveConsumer` are:
1. Call `cancelPendingRead()`, which might set `havePendingRead` with false. (The concurrent call of `cancelPendingRead()` does not matter because it does not set `havePendingRead` with true so that following logic will be skipped.)
2. Skip the following logic if `havePendingRead` is true, which could only be caused by `readMoreEntries`.
3. Call `readMoreEntries()` immediately or lazily according to the subscription type and the config.

Yes, there is a chance that `readMoreEntries` is called concurrently.

| Steps | Thread 1 | Thread 2 |
| :- | :- | :- |
| 1 | Read `havePendingRead`: false | |
| 2 | | Write `havePendingRead`: true |
| 3 | Call `readMoreEntries` | |

However, it's still safe because in `readMoreEntries`, before reading messages through `cursor`, it checks `havePendingRead` again in the synchronized block. https://github.com/apache/pulsar/blob/442595ea26c8c0699807a0fef2b7e2e27c677c08/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java#L343-L349

> if the same bug pattern is in other locations in the Pulsar code base?

BTW, yes, the same bug pattern is use in many places.

**Review by lhotari — APPROVED** [review]
Good job and awesome explanations @BewareMyPower

**Comment by BewareMyPower** [comment]
@lhotari This PR is merged too quickly without a 2nd review. After revisiting the code, I found the double-checked locking is unnecessary. 

`scheduleReadOnActiveConsumer()` is always called in `pickAndScheduleActiveConsumer()`, which is always called in `addConsumer()` and `removeConsumer()`. However, both of them are synchronized methods. So `scheduleReadOnActiveConsumer` could never be called concurrently.

The original motivation is the IDE warning:

image

It's true that it's a non-atomic operation on volatile field 'readOnActiveConsumerTask'. It's a commonly seen error to access a volatile field so IDE gives such warnings. However, we don't need to make `scheduleReadOnActiveConsumer()` thread safe. Unfortunately, there is no comment that notes this point. The lack of such comments makes code hard to maintain. Generally, developers assume all methods must be thread safe so the code might become unnecessarily complicated.

I opened another PR (https://github.com/apache/pulsar/pull/22285) that improves the code quality and reduces the unnecessary atomicity. That PR also reverts the changes of this PR. PTAL again.

**Comment by lhotari** [comment]
> @lhotari This PR is merged too quickly without a 2nd review. After revisiting the code, I found the double-checked locking is unnecessary.

@BewareMyPower We don't have a policy that there should be a 2nd review. This PR didn't contain any risky changes and wasn't harmful at all and that's why I merged. It's better to keep on moving instead of optimizing for perfect PRs. The resolution that you have done is a good one: opening another PR with follow-up changes.

**Comment by lhotari** [comment]
> Generally, developers assume all methods must be thread safe so the code might become unnecessarily complicated.

@BewareMyPower I agree that generalizing thread safety to a certain style in the Pulsar code base won't be very useful. However there are real problems where thread safety has been ignored and fixing the issues isn't prioritized. For example the topic level policies contain real problems, #21303.

**Pull request merged**
