### PR TITLE
After #3228, removed usages of deprecated client API

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

 * Refactored tests and other parts to only use the non deprecated methods.  
 * Removed the interfaces that were already copied in `pulsar-client-1x` module

### CODE REVIEW

**Comment by jai1** [comment]
rerun java8 tests

**Comment by jai1** [comment]
run integration tests

**Comment by merlimat** [comment]
run integration tests

**Comment by merlimat** [comment]
run integration tests

**Pull request merged**
