### PR TITLE
Add proxy plugin interface to support user defined additional servlet

### PR DESCRIPTION
**Pull request by wolfstudy**
### Motivation

In order to facilitate users' flexible access in the broker, we provide plug-ins similar to broker protocol and broker interceptor. Similarly, in the proxy, sometimes users also need similar plug-in functions to facilitate customizing some data requests.

### Modifications

- Add protocol plugin for proxy

### CODE REVIEW

**Comment by jiazhai** [comment]
@gaoran10 to help on this issue

**Comment by wolfstudy** [comment]
@jiazhai @codelipenghui PTAL thanks

**Comment by jiazhai** [comment]
@gaoran10 to help review it

**Comment by wolfstudy** [comment]
After discussing with @jiazhai  and @codelipenghui, we removed it from `release/2.6.2`.

**Review by jiazhai — APPROVED** [review]

**Comment by jiazhai** [comment]
not in high priority, remove 2.6.2

**Pull request merged**
