### PR TITLE
[Doc] Add guides for Transactions

### PR DESCRIPTION
**Pull request by Anonymitaet**
Pulsar 2.8 has been released and one of the highlights is transaction API, which supports atomic writes and acknowledgments across multiple topics. It completes our vision of making Pulsar a complete unified messaging and streaming platform.

While the previous transaction docs are incomplete and need to be improved, so I've re-architectured it and added missing contents.

This PR fixes https://github.com/apache/pulsar/issues/10971 and it is based on the [google doc](https://docs.google.com/document/d/1rChR2ZScYxCDKUmkQTg6inbuhyfrz_jJfdQOFtwO8P0/edit#) I collaborated with @congbobo184 and @D-2-Ed, so it should be pretty good already.

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@congbobo184 @Jennifer88huang @Huanli-Meng could you please help review? Many thanks

**Review by congbobo184 — APPROVED** [review]
LGTM.

**Review by lhotari — APPROVED** [review]
LGTM. 

I wonder if the Pulsar binary protocol specification https://pulsar.apache.org/docs/en/develop-binary-protocol/ / https://github.com/apache/pulsar/blob/master/site2/docs/developing-binary-protocol.md needs updating to make it consistent with transactions? Any ideas how to cover that?

**Review by codelipenghui — APPROVED** [review]

**Comment by Anonymitaet** [comment]
Hi @lhotari thanks for your feedback.

I've discussed w/ @congbobo184, we are considering making the following changes to doc:

1.  Add `transaction` section under the `interactions` chapter
image

2. Add descriptions for transaction command in the [source code file](https://github.com/apache/pulsar/blob/master/pulsar-common/src/main/proto/PulsarApi.proto) (rather than in user guide) and add links of the [source code file](https://github.com/apache/pulsar/blob/master/pulsar-common/src/main/proto/PulsarApi.proto) to the user guide.

Reason: 
- The descriptions are simple.
- Developers make code changes at any time or frequently (for example,  add a transaction command), it is not easy to capture all code changes and sync doc with code. But we provide the source code file link, so that users can be navigated to the source code file to get the latest and complete info.

3. Add a diagram (something like below) of transaction to the user guide.

image

Any thoughts?

**Comment by Anonymitaet** [comment]
Hi @lhotari any feedback?

**Pull request merged**
