### PR TITLE
Update grpc to 1.31.0

### PR DESCRIPTION
**Pull request by aahmed-se**

### CODE REVIEW

**Review by pkumar-singh — APPROVED** [review]

**Review by srkukarni — APPROVED** [review]

**Comment by lhotari** [comment]
@aahmed-se @pkumar-singh @srkukarni @dlg99 It seems that this PR was never merged. Was that intentional? 

We are also facing the grpc deadlock issue described in PR #8351 (that PR had to be reverted at that time because of multiple issues described in the comment history) and it would be important to get the problem fixed asap. 

@aahmed-se Were there some obstacles in upgrading grpc to 1.31.0 ?

**Comment by aahmed-se** [comment]
THis requires some changes in bookkeeper first and the reference version in pulsar be upgraded.

**Comment by lhotari** [comment]
@aahmed-se Thanks for explaining. Would you mind adding a reference to the changes that are required? What is the status of those changes?

**Comment by aahmed-se** [comment]
The changes have been made internally in our bookkeeper they are quite substantial. 
I don't know the current plans on when they can pushed upstream. It depends on when there is downtime in work.

**Comment by eolivelli** [comment]
@diegosalvi @aluccaroni which GRPC version do you have in EmailSuccess stack ? IIRC we had upgraded to latest version recently

**Comment by diegosalvi** [comment]
@eolivelli Thank you. No, actually it needs to be upgraded. Next release cycle

**Comment by dlg99** [comment]
@aahmed-se @lhotari can you take a look at https://github.com/apache/bookkeeper/pull/2582  - I tried to upgrade grpc for bookkeeper

**Pull request closed without merging**
