### PR TITLE
[function] fix update user config

### LINKED ISSUE #10720: pulsar-admin functions update drops user-configs
**Describe the bug**
When using the /pulsar-admin functions update command to update an existing function instance. If you only provide the `--parallelism` flag, then the previously provided user-configs settings get deleted.

**To Reproduce**
1. Create a Pulsar Function from the CLI providing a value for the `--user-config` switch, e.g. `bin/pulsar-admin functions create   --jar /streamlio/connectors/test-functions-1.0.0.nar   --classname com.manning.pulsar.loadgen.SumOfFibonacciFunction   --inputs persistent://public/default/input-1   --output persistent://public/default/output-1   --log-topic persistent://public/default/log-1   --user-config "{\"max\" : \"60\"}"   --parallelism 10'
2.  Verify that the Function was created and the user configs were accepted, e.g. `bin/pulsar-admin functions get --name SumOfFibonacciFunction`
3. Update the parallelism setting using the /pulsar-admin functions update command, e.g. `bin/pulsar-admin functions update --name SumOfFibonacciFunction --parallelism 60` 
4. Get the function details again, and notice that the user-configs are now blank, e.g. `bin/pulsar-admin functions get --name SumOfFibonacciFunction`

{
  "tenant": "public",
  "namespace": "default",
  "name": "SumOfFibonacciFunction",
  "className": "com.manning.pulsar.loadgen.SumOfFibonacciFunction",
  "inputSpecs": {
    "persistent://public/default/input-1": {
      "isRegexPattern": false,
      "schemaProperties": {},
      "consumerProperties": {}
    }
  },
  "output": "persistent://public/default/output-1",
  "producerConfig": {
    "useThreadLocalProducers": false,
    "batchBuilder": ""
  },
  "logTopic": "persistent://public/default/log-1",
  "processingGuarantees": "ATLEAST_ONCE",
  "retainOrdering": false,
  "retainKeyOrdering": false,
  "forwardSourceMessageProperty": true,
  **"userConfig": {},**
  "runtime": "JAVA",
  "autoAck": true,
  "parallelism": 60,
  "resources": {
    "cpu": 1.0,
    "ram": 1073741824,
    "disk": 10737418240
  },
  "cleanupSubscription": true
}

**Expected behavior**
Updating the parallelism of a function should not clear out the user provided configuration settings.

**Desktop (please complete the following information):**
 - OS: Mac

### PR DESCRIPTION
**Pull request by linlinnn**
Fixes #10720

### Motivation
fix update user config

### CODE REVIEW

**Comment by wangjialing218** [comment]
In this way, `userConfigMap ` will be null if user does not set user config. We need to confirm if this will cause Conext.getUserConfigMap() return null. In that condition, user may get NPE if they do not handle null in there function code.

**Comment by linlinnn** [comment]
> In this way, `userConfigMap ` will be null if user does not set user config. We need to confirm if this will cause Conext.getUserConfigMap() return null. In that condition, user may get NPE if they do not handle null in there function code.

@wangjialing218 
I think it's a normal case.
Because user always need to judge not null when access a member of object, it's programing specification.

**Comment by sijie** [comment]
@nlu90 @freeznet Can you review this?

**Review by freeznet — APPROVED** [review]

**Comment by nlu90** [comment]
@linlinnn could you describe what's the difference between your change and the original one?

Based on my understanding, they are kind of equivalent. Your change set the empty hashmap inside the `userConfigString` while the previous one set it after the `if` clause

**Review by freeznet — COMMENTED** [review]
LGTM, `userConfig` can be null if no `userConfigString` provided. but could you please add some tests that show the issue has been correctly fixed?

**Comment by linlinnn** [comment]
@nlu90 The previous one clear `userConfig` if no `userConfigString` provided, and this change keep the `userConfig` same as before.

**Comment by linlinnn** [comment]
@freeznet done, please help review.

**Review by freeznet — APPROVED** [review]
LGTM

**Review by sijie — APPROVED** [review]

**Pull request merged**
