### PR TITLE
check null point before setting auto read

### PR DESCRIPTION
**Pull request by yuanboliu**
Pulsar enable throttler to controll the speed of consuming data. But sometimes ctx will be closed while throttler is running in a independent thread. We should check ctx null point before setting auto read.

### CODE REVIEW

**Comment by yuanboliu** [comment]
@sijie 
sorry to interrupt. 
NPE will be thrown if throttler is enabled and ctx is closed. It would be more graceful if we check null before enabling auto read. Any thoughts about this issue?

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@yuanboliu You can `checkout -b` a new branch when you work on a bug fix or feature. For more details, you can refer to http://pulsar.apache.org/en/contributing/#create-a-branch-in-your-fork, could you help rebase to the apache/master since there are some CI fixes.

**Comment by yuanboliu** [comment]
thanks for review, I'll rebase it soon

**Pull request closed without merging**
