### PR TITLE
[fix][broker] Revert "[fix][load-balancer] skip mis-configured resource usage(>100%) in load balancer

### PR DESCRIPTION
**Pull request by Technoboy-**
### Motivation

Discuss is https://github.com/apache/pulsar/issues/18598

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Review by mattisonchao — APPROVED** [review]

**Comment by mattisonchao** [comment]
```
Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /home/runner/work/pulsar/pulsar/pulsar-common/src/test/java/org/apache/pulsar/policies/data/loadbalancer/LocalBrokerDataTest.java:[61,21] cannot find symbol
  symbol:   method getMaxResourceUsageWithWeightWithinLimit(double,double,double,double,double)
  location: variable data of type org.apache.pulsar.policies.data.loadbalancer.LocalBrokerData
```
Please take a look at this problem.

**Comment by Technoboy-** [comment]
> ```
> Error:  COMPILATION ERROR : 
> [INFO] -------------------------------------------------------------
> Error:  /home/runner/work/pulsar/pulsar/pulsar-common/src/test/java/org/apache/pulsar/policies/data/loadbalancer/LocalBrokerDataTest.java:[61,21] cannot find symbol
>   symbol:   method getMaxResourceUsageWithWeightWithinLimit(double,double,double,double,double)
>   location: variable data of type org.apache.pulsar.policies.data.loadbalancer.LocalBrokerData
> ```
> 
> Please take a look at this problem.

Fixed.

**Comment by Technoboy-** [comment]
@heesung-sn Could you please help review this ?

**Review by heesung-sn — APPROVED** [review]

**Comment by hangc0276** [comment]
LGTM

**Pull request merged**
