### PR TITLE
Set the dedup cursor as "inactive" after recovery

### LINKED ISSUE #3535: Deduplication causes a lot of Full GCs
**Describe the bug**

**2019/02/14 Added**

In our experiments, we found that enabling deduplication causes a lot of Full GCs in Brokers, which 
 seems to cause session expiration from ZooKeepers and finally shutdown.

**2019/02/07 Original report of unexpected Broker shutdown**

We have seen unexpected Broker shutdown.

1. There were LedgerFencedExceptions for a lot of ledgers:
```
01:47:09.430 [BookKeeperClientWorker-OrderedExecutor-43-0] WARN  o.a.bookkeeper.client.PendingAddOp   - Fencing exception on write: L9104171 E28233 on xxx.xx.xx.xx:3181
01:47:09.430 [BookKeeperClientWorker-OrderedExecutor-43-0] ERROR o.a.bookkeeper.client.LedgerHandle   - Closing ledger 9104171 due to LedgerFencedException: Ledger has been fenced off. Some other client must have opened it to read
01:47:09.430 [BookKeeperClientWorker-OrderedExecutor-43-0] WARN  o.a.bookkeeper.client.PendingAddOp   - Fencing exception on write: L9104171 E28234 on xxx.xx.xx.xx:3181
01:47:09.430 [BookKeeperClientWorker-OrderedExecutor-43-0] ERROR o.a.bookkeeper.client.LedgerHandle   - Closing ledger 9104171 due to LedgerFencedException: Ledger has been fenced off. Some other client must have opened it to read
01:47:09.430 [BookKeeperClientWorker-OrderedExecutor-43-0] WARN  o.a.bookkeeper.client.PendingAddOp   - Fencing exception on write: L9104171 E28235 on xxx.xx.xx.xx:3181
01:47:09.430 [BookKeeperClientWorker-OrderedExecutor-43-0] ERROR o.a.bookkeeper.client.LedgerHandle   - Closing ledger 9104171 due to LedgerFencedException: Ledger has been fenced off. Some other client must have opened it to read
...
```

2. There were a lot of "Failed to create producer: Producer with name geo-replicator".
```
01:47:09.907 [pulsar-io-21-31] ERROR o.a.pulsar.client.impl.ProducerImpl  - [persistent://<topicname>] [pulsar.repl.<localcluster>] Failed to create producer: Producer with name 'pulsar.repl.<localcluster>' is already connected to topic
```

3. Finally, Broker suddenly stopped with
```
01:47:09.963 [pulsar-ordered-OrderedExecutor-4-0-EventThread] ERROR o.a.p.z.ZooKeeperSessionWatcher      - ZooKeeper session already expired, invoking shutdown
```

**Additional context**
Broker OS: CentOS Linux release 7.6.1810
Broker version: 2.1.1

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

The cursor used for message deduplication is currently set as "inactive" only when it gets first created, but not when it gets recovered the subsequent times.

Having the cursor active, means the managed-ledger keeps caching messages that are not being evicted from the cache until it gets full, since the dedup cursor never reads from the cursor (outside the topic recovery phase). 

This leads to a high number of objects in the cache, kept for an extended amount of time (until the cache is full and eviction kicks in) and it's hitting the GC very badly.

This should fix #3535

### CODE REVIEW

**Comment by rdhabalia** [comment]
I think I need to recollect dedup code little bit but from where exactly `initialize()` method is being called.? I think cursor is being set-inactive as soon as it's [recovered](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageDeduplication.java#L241). I don't see any code-path that actually calls `initialize()` method?

**Comment by merlimat** [comment]
Currently it's only set inactive on 
https://github.com/apache/pulsar/blob/8b2929b3e5403fb44653976dc74be287666f7b96/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageDeduplication.java#L239-L242 which is called the first time the dedup is enabled (or if there is any discrepancy enabled/disabled) but it's not being set on the cursor when the topic (and the dedup) cursor is being recovered.

**Comment by hrsakai** [comment]
run java8 tests

**Comment by hrsakai** [comment]
@merlimat 
Please tell me where `initialize ()` is called from.

**Comment by merlimat** [comment]
@hrsakai You're correct.. I don't see where it's being called... it looks like all initialization are done through the `checkStatus()`.. Let me go back and repeat my testing then

**Comment by merlimat** [comment]
@hrsakai @massakam Did more experimentation and fixed it by making sure the dedup cursor is never considered "active" in order to never trigger caching behavior.

**Comment by massakam** [comment]
rerun java8 tests

**Comment by massakam** [comment]
rerun java8 tests

**Comment by merlimat** [comment]
run java8 tests
run integration tests

**Comment by merlimat** [comment]
run cpp tests

**Comment by massakam** [comment]
rerun integration tests

**Comment by merlimat** [comment]
Merged in 2.3.1 at 
2d924ab

**Pull request merged**
