### PR TITLE
Integration smoke test for pulsar

### PR DESCRIPTION
**Pull request by ivankelly**
Boots a cluster, sends and receives some messages, shuts down the
cluster.

If anything fails, then something is very broken.

### CODE REVIEW

**Comment by ivankelly** [comment]
Will fail now, as it depends on a fix in bookkeeper
https://github.com/apache/bookkeeper/pull/1269

**Comment by ivankelly** [comment]
retest this please

**Comment by ivankelly** [comment]
retest this please

**Comment by ivankelly** [comment]
Depends on https://github.com/apache/incubator-pulsar/pull/1496

**Comment by ivankelly** [comment]
Also depends on https://github.com/apache/incubator-pulsar/pull/1492

**Comment by ivankelly** [comment]
retest this please // ManagedCursorTest.testOutOfOrderDeletePersistenceIntoLedgerWithClose

**Comment by ivankelly** [comment]
retest this please // ManagedCursorTest.testOutOfOrderDeletePersistenceIntoLedgerWithClose again

**Comment by ivankelly** [comment]
retest this please // ManagedCursorTest.testOutOfOrderDeletePersistenceIntoLedgerWithClose again. Starting to think master is broken

**Comment by merlimat** [comment]
retest this please

**Comment by merlimat** [comment]
retest this please

**Comment by ivankelly** [comment]
retest this please 

// flake on PersistentFailoverE2ETest.testSimpleConsumerEventsWithoutPartition (java8)
// flake on ConsumerStatsTest.testCachingMechanism (c++/python)

**Comment by ivankelly** [comment]
finally

**Pull request merged**
