### PR TITLE
 renaming sinks and sources api to be consistent with the rest of Pulsar

### PR DESCRIPTION
**Pull request by jerrypeng**
### Motivation

Users have complained that the sinks and sources REST and admin API is not consistent with the rest of Pulsar's REST and admin API.  Which causes lost of productivity to developers. The primary reason of user's complaint is that other Pulsar REST/admin APIs is always plural (e.g. Topics, Namespaces, etc.) while the APIs for sinks and sources are singular (i.e. Sink and Source).  

###Modification 

Change the sinks and sources API to be more consistent with the rest of Pulsar and yet still remain BC.

Things changed:
1. Sinks and Sources CLI
2. Sinks and Sources Admin API
3. Sinks and Sources REST endpoints

### CODE REVIEW

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by jerrypeng** [comment]
@sijie can I fix the documentation in subsequent PR?  This PR is already quite large.

**Comment by sijie** [comment]
> @sijie can I fix the documentation in subsequent PR? This PR is already quite large.

@jerrypeng do you mind creating an issue for that? so it is not dropped.

**Comment by jerrypeng** [comment]
@sijie I have created an issue to track this:
https://github.com/apache/pulsar/issues/4383

**Pull request merged**
