### PR TITLE
[pulsar-functions-go] support set subscription position

### PR DESCRIPTION
**Pull request by freeznet**
### Motivation

Support pass subscription position to pulsar-functions-go

### Modifications

- add subscription position in go instance conf
- process subscription position in go function

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 

- [x] doc-required 
  
will add related doc in separate PR
  
- [ ] no-need-doc 
  
  (Please explain why)
  
- [ ] doc 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@freeznet Thanks for your contribution. Please do not forget to update docs later. And you can ping me to review the docs, thanks.

**Review by sijie — APPROVED** [review]

**Comment by sijie** [comment]
@nlu90 please review it.

**Review by nlu90 — APPROVED** [review]
LGTM

**Comment by Anonymitaet** [comment]
Doc has been added
image

**Pull request merged**
