### PR TITLE
Update deps, allow to run tests with forkCount=1

### PR DESCRIPTION
**Pull request by eolivelli**
# Motivation
In current master you cannot run the tests with "forkCount=1", this is very annoying as by default we are running all of the tests in parallel.
This change upgrades a few testing dependencies and fixes a problem with PowerMock + Testng + Log4j2 + forkCount=1

### Modifications
- Upgrade TestNG
- Upgrade PowerMock
- Upgrade Mockito

### Verifying this change

All tests should pass

This change is a trivial rework / code cleanup without any test coverage.

### CODE REVIEW

**Comment by eolivelli** [comment]
It looks like I have to update testing xml files according to
https://github.com/cbeust/testng/pull/2023/files

**Comment by eolivelli** [comment]
@lhotari this is a small clean up but it will help in understanding the dynamics of the test suite.
I suspect we have a few leaks that slow down CI,
I am running the test suite locally with forlCount=1 in order to seek for the causes

cc @jiazhai @sijie @codelipenghui

**Comment by lhotari** [comment]
> this is a small clean up but it will help in understanding the dynamics of the test suite.
> I suspect we have a few leaks that slow down CI,
> I am running the test suite locally with forlCount=1 in order to seek for the causes

@eolivelli the changes LGTM. 

btw. One way to get more visibility into the Maven build would be to use [Gradle Build Scans for Maven](https://scans.gradle.com/#maven) ([more details](https://docs.gradle.com/enterprise/maven-extension/#using_build_scans)) to get detailed reports of the build execution. Gradle has tools for Maven as well. It's part of Gradle Enterprise, but the Builds Scans can be used for free when using the public server. It's well suitable for opensource projects.

**Review by aahmed-se — APPROVED** [review]

**Review by jiazhai — APPROVED** [review]

**Comment by eolivelli** [comment]
thank you @jiazhai  !

**Pull request merged**
