### PR TITLE
Fix: init of subcription rateLimiter to avoid race-condition and NPE

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

Initialize final `dispatchRateLimiter` to avoid multiple init for `dispatchRateLimiter ` and avoid possible [NPE](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L1202) due to uninitialized `dispatchRateLimiter`

### CODE REVIEW

**Comment by lovelle** [comment]
Excellent solution! just a question/proposal, has anyone ever considered of using annotations to document better thread safety like `@ThreadSafe` at a class level? A lot of people use [jcip-annotations](https://mvnrepository.com/artifact/net.jcip/jcip-annotations) for this purpose and gives a clearer visibility about thread safety.

**Comment by rdhabalia** [comment]
@lovelle I think it makes more sense to use jcip-annotations for the public api for better documentation. for internally, I am not sure because most of the entities at broker and clients are thread-safe and but it might be helpful for developers if we come across with such apis that requires explicit documentation.

**Comment by lovelle** [comment]
Great! I agree :+1:

**Comment by jiazhai** [comment]
@rdhabalia  Thanks for the change. lgtm. but from the code, this looks like a lazy creation,  which could avoid creating a `dispatchRateLimiter` if possible.  @merlimat @sijie Would you please help confirm this?

**Comment by sijie** [comment]
I shared the same concern with @jiazhai  - this change is forcing every consumer to have one instance of dispatcher limiter. this can be potentially expensive for users who have a lot of consumers. @rdhabalia can we find some other approaches to fix the problem?

**Comment by rdhabalia** [comment]
> this change is forcing every consumer to have one instance of dispatcher limiter.

umm..that's not correct. Rate-Limiter is per dispatcher-level so, not every consumer will create a rate-limiter but it will be limited at subscription level. Also, this PR is not creating additional object but it just creates RateLimiter object in a thread-safe way.

> But from the code, this looks like a lazy creation, which could avoid creating a dispatchRateLimiter if possible.


Actually existing code is also initializing rate-limiter as soon as subscription reads the message. It's lazy, non-thread-safe and unnecessary if throttling is not configured for the subscription: https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java#L373

However, we can avoid creating rateLimiter object if throttling is not configured and it can save us some heap. I will make the fix.

**Comment by jiazhai** [comment]
@rdhabalia Thanks for the fix in #3479. Does this mean we could close this pr?

**Comment by rdhabalia** [comment]
@jiazhai yes, we can close this one now.

**Pull request closed without merging**
