### PR TITLE
Fix: Netty threads may still linger after client close

### PR DESCRIPTION
**Pull request by jerrypeng**
### Motivation

Even after the synchronous close() method is called on a PulsarClient, netty thread(s) from the EventLoopGroup used in the ConnectionPool may still linger around for another 2 seconds afterwards due to not wait for the the graceful shutdown to complete.

While this usually doesn't cause any problems for a normal use case, it does cause problems in the Pulsar Flink sources and sinks.  Exceptions like the following can happen when the Flink job with a Pulsar source or sink gets closed:

```
Exception in thread "pulsar-client-io-1-1" java.lang.NoClassDefFoundError: org/apache/pulsar/shade/io/netty/buffer/PoolArena$1
	at org.apache.pulsar.shade.io.netty.buffer.PoolArena.freeChunk(PoolArena.java:293)
	at org.apache.pulsar.shade.io.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:460)
	at org.apache.pulsar.shade.io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:430)
	at org.apache.pulsar.shade.io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:422)
	at org.apache.pulsar.shade.io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:279)
	at org.apache.pulsar.shade.io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:270)
	at org.apache.pulsar.shade.io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:241)
	at org.apache.pulsar.shade.io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:450)
	at org.apache.pulsar.shade.io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:426)
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocal.remove(FastThreadLocal.java:271)
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocal.removeAll(FastThreadLocal.java:67)
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:32)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.pulsar.shade.io.netty.buffer.PoolArena$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$ChildFirstClassLoader.loadClass(FlinkUserCodeClassLoaders.java:129)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
```

This is because threads from the EventLoopGroup lingers after the pulsar client is closed and the Flink job is unloaded.

### Modifications

Shorten the graceful shutdown period and wait for it to complete

### CODE REVIEW

**Comment by jerrypeng** [comment]
rerun integration tests

**Comment by jerrypeng** [comment]
rerun integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by codelipenghui** [comment]
retest this please

**Comment by jerrypeng** [comment]
rerun integration tests

**Comment by sijie** [comment]
retest this please

**Comment by wolfstudy** [comment]
run integration tests

**Comment by wolfstudy** [comment]
> org.apache.pulsar.broker.service.ReplicatorTest.testResumptionAfterBacklogRelaxed
org.apache.pulsar.broker.service.ReplicatorTest.testCloseReplicatorStartProducer
org.apache.pulsar.broker.service.ReplicatorTest.testConfigChange
org.apache.pulsar.broker.service.ReplicatorTest.testDeleteReplicatorFailure
org.apache.pulsar.broker.service.ReplicatorTest.testReplicatePeekAndSkip
org.apache.pulsar.broker.service.ReplicatorTest.testReplication
org.apache.pulsar.broker.service.ReplicatorTest.testReplication
org.apache.pulsar.broker.service.ReplicatorTest.testReplication
org.apache.pulsar.broker.service.ReplicatorTest.testReplicationForBatchMessages
org.apache.pulsar.broker.service.ReplicatorTest.testReplicationOverrides
org.apache.pulsar.broker.service.ReplicatorTest.testReplicatorClearBacklog
org.apache.pulsar.broker.service.ReplicatorTest.testResetCursorNotFail
org.apache.pulsar.broker.service.ReplicatorTest.testReplicatorProducerClosing
org.apache.pulsar.broker.service.schema.PartitionedTopicsSchemaTest.partitionedTopicWithSchema

run java8 tests

**Comment by jerrypeng** [comment]
rerun integration tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun integration tests

**Comment by jerrypeng** [comment]
rerun integration tests

**Comment by wolfstudy** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
> org.apache.pulsar.tests.integration.cli.CLITest.pulsar-test-suite

run integration tests

**Comment by wolfstudy** [comment]
> org.apache.pulsar.tests.integration.cli.CLITest.pulsar-test-suite
org.apache.pulsar.tests.integration.cli.CLITest.pulsar-test-suite
org.apache.pulsar.tests.integration.schema.SchemaTest.pulsar-test-suite
org.apache.pulsar.tests.integration.functions.PulsarFunctionsProcessTest.pulsar-test-suite
org.apache.pulsar.tests.integration.functions.PulsarFunctionsProcessTest.pulsar-test-suite
org.apache.pulsar.tests.integration.functions.PulsarFunctionsProcessTest.pulsar-test-suite
org.apache.pulsar.tests.integration.functions.PulsarFunctionsProcessTest.pulsar-test-suite
org.apache.pulsar.tests.integration.functions.PulsarFunctionsThreadTest.pulsar-test-suite
org.apache.pulsar.tests.integration.functions.PulsarFunctionsThreadTest.pulsar-test-suite
org.apache.pulsar.tests.integration.functions.PulsarFunctionsThreadTest.pulsar-test-suite

run integration tests

**Comment by jerrypeng** [comment]
rerun java8 tests
rerun integration tests

**Comment by jerrypeng** [comment]
rerun integration tests

**Comment by wolfstudy** [comment]
run integration tests
run java8 tests

**Comment by jerrypeng** [comment]
run integration tests
run java8 tests

**Comment by jerrypeng** [comment]
rerun java8 tests
rerun integration tests

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by wolfstudy** [comment]
@jerrypeng Please fix the test case, will change the milestone to `2.4.3`.

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun integration tests
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun integration tests

**Comment by jerrypeng** [comment]
rerun integration tests

**Pull request merged**
