### PR TITLE
[cleanup][dependency] Remove JUnit

### PR DESCRIPTION
**Pull request by nodece**
Signed-off-by: Zixuan Liu <nodeces@gmail.com>

### Motivation

We no longer use JUnit, so remove this.

### Modifications

- Remove Junit dependency

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `no-need-doc` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-added`
(Docs have been already added)
- [x] `doc-not-needed`

### CODE REVIEW

**Review by Shoothzj — APPROVED** [review]

**Review by RobertIndie — APPROVED** [review]

**Review by nicoloboschi — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Comment by nodece** [comment]
@codelipenghui I noticed this CI always failed, could you help me check this CI? Why does removing Junit break integration testing?

**Comment by Shoothzj** [comment]
pom file is changed, trigger the CVE check. One of the failure of CVE check needs to bump the grpc version. But `grpc` haven't release a version yet.

**Comment by nodece** [comment]
Thanks @codelipenghui and @Shoothzj, the CI has been passed.

**Review by Demogorgon314 — APPROVED** [review]

**Review by HQebupt — APPROVED** [review]

**Comment by nodece** [comment]
Hi @codelipenghui, this PR looks can be merged into the master branch.

**Review by liangyuanpeng — APPROVED** [review]

**Pull request merged**
