### PR TITLE
[pulsar-flink] add streaming connectors as a Pulsar stream that serializes data in Avro format

### PR DESCRIPTION
**Pull request by ambition119**
### Motivation

add Avro data format flink streaming connectors 

### Modifications

add class PulsarAvroTableSink 

### Result

add append-only table sink for serializes data in Avro format.

### CODE REVIEW

**Comment by ambition119** [comment]
ok, I can supplement PulsarJsonTableSink and PulsarAvroTableSink  simple example.

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
@ambition119 just try to check here - are you going to provide the example here? or are you planning to do it in a separate PR?

**Comment by ambition119** [comment]
@sijie sorry, I  was in the exam these two days and didn't have time to write the code,I will continue to improve it during the working day. I can continue to add example in this PR

**Comment by ambition119** [comment]
@sijie  Add JsonTableSink and AvroTableSink test, example. thanks

**Comment by sijie** [comment]
@ambition119 there are some issues related shading, can you take a look?

```
/home/jenkins/jenkins-slave/workspace/pulsar_precommit_cpp/pulsar-flink/src/test/java/org/apache/flink/streaming/connectors/pulsar/PulsarConsumerSourceTests.java:[528,62] incompatible types: io.netty.buffer.ByteBuf cannot be converted to org.apache.pulsar.shade.io.netty.buffer.ByteBuf
```

**Comment by ambition119** [comment]
> @ambition119 there are some issues related shading, can you take a look?
> 
> ```
> /home/jenkins/jenkins-slave/workspace/pulsar_precommit_cpp/pulsar-flink/src/test/java/org/apache/flink/streaming/connectors/pulsar/PulsarConsumerSourceTests.java:[528,62] incompatible types: io.netty.buffer.ByteBuf cannot be converted to org.apache.pulsar.shade.io.netty.buffer.ByteBuf
> ```

ok

**Pull request merged**
