### PR TITLE
[improve][docs] Add chroot path related informations

### PR DESCRIPTION
**Pull request by yoda-mon**
### Motivation

On this PR https://github.com/apache/pulsar/pull/13985, `/my-chroot-path` was added to the URLs.
If users follow the document, `bookkeeper.conf` and `broker.conf` lacks the informations about the path and fail to set up the cluster.

### Modifications

Add chroot path related informations to the documents and add `zk://` prefix to metadata URLs.

### Documentation

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 
Screen Shot 2022-10-13 at 19 49 19
Screen Shot 2022-10-13 at 19 49 59

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@mattisonchao 
could you please review this PR from a technical perspective? Thank you!

**Comment by Anonymitaet** [comment]
ping @mattisonchao

**Review by tisonkun — COMMENTED** [review]
I'd prefer we don't use `chroot` at all since it's an advanced topic and should not be the default information delivered to users.

cc @RobertIndie it's related to your previous patch https://github.com/apache/pulsar/pull/13985. Please take a look.

**Comment by yoda-mon** [comment]
Thank you for your comment.
@RobertIndie  `chroot` is the point that I struggled at first as a Pulsar beginner. If it is advanced topic I would emit the usage of `chroot` from the doc.

**Comment by tisonkun** [comment]
@RobertIndie Then let's remove it first. I think we cannot cover every ZK advanced topics in the Pulsar doc site. But if chroot a significant topic, we may find a place to discuss it. You may contact with @momo-jun @Anonymitaet for where in the information architecture is proper to handle such content.

@yoda-mon for this PR, let's revert the chroot command from #13985. You may check the corresponding files under [site2/website/versioned_docs/version-2.10.x](https://github.com/apache/pulsar/tree/master/site2/website/versioned_docs/version-2.10.x) where we're actively maintaining and you should update it simultaneously.

**Comment by yoda-mon** [comment]
@tisonkun Thank you for your advice, I followed. 
And let me confirm one thing, I added `zk://` prefix to the example because the `broker.conf`'s comment shows this style first and `initialize-cluster-metadata`'s example shows.
I recognized that both styles, the prefix exists or not, work fine. If it is preferable to remove the prefix, I will revert the commit.

**Comment by tisonkun** [comment]
@yoda-mon Thanks for your contribution!

**Pull request merged**
