### PR TITLE
[fix] Revert "[fix][cli] Fix the shell script parameter passthrough syntax (#22867)"

### PR DESCRIPTION
**Pull request by coderzc**
This reverts commit c81c0f684f8c55c2e39739c6e1de935dff2085d6.

Fixes #xyz

Main Issue: #xyz

PIP: #xyz 

### Motivation

#22867 introduced some break changes, such as `bin/pulsar zookeeper-shell --run-one "ls /ledgers"` can't work after introduced 22867.

### Modifications

Revert #22867

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by RobertIndie — APPROVED** [review]

**Review by merlimat — APPROVED** [review]

**Comment by lhotari** [comment]
> #22867 introduced some break changes, such as `bin/pulsar zookeeper-shell --run-one "ls /ledgers"` can't work after introduced 22867.

@coderzc @RobertIndie @merlimat I don't agree with reverting this change. The syntax of `bin/pulsar zookeeper-shell --run-one "ls /ledgers"` is simply wrong. It just happened to work before when the shell script didn't correctly handle parameters.

**Comment by lhotari** [comment]
There are several problems with `bin/pulsar zookeeper-shell --run-one "ls /ledgers"`

1. `zookeeper-shell` has never supported an option called `--run-one`
2. The parameter for zookeeper-shell shouldn't be quoted.

**Comment by lhotari** [comment]
The `--run-once "ls /path"` syntax is supported for the Python based zk-shell, https://pypi.org/project/zk-shell/ . That's not used when `pulsar zookeeper-shell` is called.

**Comment by lhotari** [comment]
@coderzc Please review #22923. Reverting the shell script was not the correct solution to address this problem. I've explained in #22923 and also comments above. I'd like to finally fix the shell script syntax for Pulsar 4.0.0 so that it's not forever invalid. There's no need to cherry-pick to older versions if that's a concern.

**Pull request merged**
