### PR TITLE
[improve][build] Capture local build scans on ge.apache.org to benefit from deep build insights

### PR DESCRIPTION
**Pull request by clayburn**
### Motivation

This PR publishes a build scan for every CI build on GitHub Actions and for every local build from an authenticated Apache committer. The build will not fail if publishing fails.

The build scans of the Apache Pulsar project are published to the Gradle Enterprise instance at [ge.apache.org](https://ge.apache.org/), hosted by the Apache Software Foundation and run in partnership between the ASF and Gradle. This Gradle Enterprise instance has all features and extensions enabled and is freely available for use by the Apache Pulsar project and all other Apache projects.

Currently, the Apache Pulsar build is configured to publish build scans to [ge.apache.org](https://ge.apache.org/) for CI only. This pull request enhances that functionality by also publishing build scans to [ge.apache.org](https://ge.apache.org/) for authenticated Apache committers. On this Gradle Enterprise instance, Apache Pulsar will have access not only to all of the published build scans but other aggregate data features such as:

- Dashboards to view all historical build scans, along with performance trends over time
- Build failure analytics for enhanced investigation and diagnosis of build failures
- Test failure analytics to better understand trends and causes around slow, failing, and flaky tests

### Modifications

- Update the Gradle Enterprise Maven Extension to 1.17
- Remove the logic that copies `ge-extensions.xml` in favor of the more conventional `extensions.xml` file. Updates to the `publishIfAuthenticated` property in Gradle Enterprise Maven Extension 1.17 will cause the build to print no output if the user is not authenticated to [ge.apache.org](https://ge.apache.org/).

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.
### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by lhotari — APPROVED** [review]
LGTM

**Review by tisonkun — APPROVED** [review]
Although I'm thinking of further cleanup for setting:

```yml
env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ...
```

and drop the handmade action, it should not be a blocker to us for merging this patch.

**Comment by tisonkun** [comment]
Merging...

**Pull request merged**
