### PR TITLE
Upgrade athenz version and remove yahoo.bintray.com repository

### PR DESCRIPTION
**Pull request by lhotari**
-  backport #10079 to branch-2.7

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by codelipenghui — APPROVED** [review]

**Review by congbobo184 — APPROVED** [review]

**Comment by eolivelli** [comment]
CI is stuck. I am merging this patch anyway.
The build passes in other CI jobs and the patch is the same as in master branch

**Pull request merged**
