### PR TITLE
[cleanup][managed-ledger]fix typo error in ManagedCursorContainer

### PR DESCRIPTION
**Pull request by HQebupt**
### Motivation
fix typo error in ManagedCursorContainer

### Verifying this change

- [x]  Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:
If `yes` was chosen, please highlight the changes

- Dependencies (does it add or upgrade a dependency): (no)
- The public API: (no)
- The schema: (no)
- The default values of configurations: (no)
- The wire protocol: (no)
- The rest endpoints: (no)
- The admin cli options: (no)
- Anything that affects deployment: (no)

### Documentation
Check the box below and label this PR (if you have committer privilege).

Need to update docs?
- [x] `doc`
- [ ] `doc-required`
- [ ] `doc-not-needed`
- [ ] `doc-complete`

### CODE REVIEW

**Review by poorbarcode — APPROVED** [review]

**Comment by lhotari** [comment]
> /pulsarbot run-failure-checks

@HQebupt This won't help. please read https://lists.apache.org/thread/lv358906mnroq7tkk72xtsxfyjpbyvor . This PR won't be eligible for merging unless you rebase.

**Comment by HQebupt** [comment]
> > /pulsarbot run-failure-checks
> 
> @HQebupt This won't help. please read https://lists.apache.org/thread/lv358906mnroq7tkk72xtsxfyjpbyvor . This PR won't be eligible for merging unless you rebase.

I see, thanks

**Review by AnonHxy — APPROVED** [review]

**Review by momo-jun — APPROVED** [review]

**Pull request merged**
