### PR TITLE
[improve][io] Upgrade Alluxio to 2.8.1

### PR DESCRIPTION
**Pull request by sekikn**
### Motivation

Currently, the Alluxio sink depends on Alluxio 2.7.3, which was released around a year ago.

### Modifications

This PR upgrades Alluxio to 2.8.1 so that we can ensure the sink works with more recent version of Alluxio.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is already covered by existing tests, such as AlluxioSinkConfigTest and AlluxioSinkTest.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [x] Dependencies (add or upgrade a dependency)
  - Upgrade Alluxio 2.7.3 to 2.8.1. Its API changed a bit, so the PR addressed it too.
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/sekikn/incubator-pulsar/pull/10

The CI above failed on the BROKER_CLIENT_IMPL and BROKER_GROUP_1 tests, but they seem to be unrelated with this change.

### CODE REVIEW

**Comment by sekikn** [comment]
Originally I tried to upgrade Alluxio to 2.9.0, which is the latest version at this writing, but [Alluxio's metrics refers to the `sun.management` package since that version](https://github.com/Alluxio/alluxio/blob/v2.9.0/core/common/src/main/java/alluxio/metrics/MetricsSystem.java#L165) and I came across the following error during using it.

```
2023-01-19T09:47:18,396+0900 [public/default/alluxio-sink-0] ERROR org.apache.pulsar.functions.instance.JavaInstanceRunnable - [public/default/alluxio-sink:0] Uncaught exception in Java Instance
java.lang.IllegalAccessError: class alluxio.metrics.MetricsSystem (in unnamed module @0x8c05339) cannot access class sun.management.ManagementFactoryHelper (in module java.management) because module java.management does not export sun.management to unnamed module @0x8c05339
        at alluxio.metrics.MetricsSystem.getDirectBufferPool(MetricsSystem.java:165) ~[?:?]
        at alluxio.metrics.MetricsSystem.<clinit>(MetricsSystem.java:157) ~[?:?]
        at alluxio.client.file.FileSystemContext.initContext(FileSystemContext.java:316) ~[?:?]
        at alluxio.client.file.FileSystemContext.init(FileSystemContext.java:305) ~[?:?]
        at alluxio.client.file.FileSystemContext.create(FileSystemContext.java:256) ~[?:?]
        at alluxio.client.file.FileSystemContext.create(FileSystemContext.java:225) ~[?:?]
        at alluxio.client.file.FileSystemContext.create(FileSystemContext.java:207) ~[?:?]
        at alluxio.client.file.FileSystem$Factory.create(FileSystem.java:138) ~[?:?]
        at org.apache.pulsar.io.alluxio.sink.AlluxioSink.open(AlluxioSink.java:101) ~[?:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setupOutput(JavaInstanceRunnable.java:857) ~[org.apache.pulsar-pulsar-functions-instance-2.11.0.jar:2.11.0]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setup(JavaInstanceRunnable.java:224) ~[org.apache.pulsar-pulsar-functions-instance-2.11.0.jar:2.11.0]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:259) ~[org.apache.pulsar-pulsar-functions-instance-2.11.0.jar:2.11.0]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Probably I have to add the `--add-opens java.management/sun.management=ALL-UNNAMED` runtime option somewhere, but I'm not sure where it is yet. So let me upgrade it to 2.9.0+ in another PR.

**Review by Jason918 — APPROVED** [review]
LGTM

**Review by tisonkun — APPROVED** [review]
@sekikn I'd like to know whether, after this version bump, the sink can still work with Alluxio server in previous versions.

**Comment by tisonkun** [comment]
@sekikn Thanks for your investigation!

I'm not quite sure what our policy is to handle such b/w compatibility issues. Generally, client libs will keep it so version bumps are always b/w compatible. But if it's not the case, at least we should add a release note to describe the breaking changes. I ever did it at https://github.com/apache/pulsar/pull/18774 while that version bump doesn't break fundamental functions.

**Pull request closed without merging**
