### PR TITLE
[build] Configure Google Error Prone static code analysis tool for Pulsar maven build

### PR DESCRIPTION
**Pull request by lhotari**
### Motivation

Google's [Error Prone static code analysis tool](https://errorprone.info/) can detect typical programming mistakes (for more info see https://errorprone.info/). This PR adds configuration to Pulsar maven build so that Error Prone static code analysis
can be run for the Pulsar code base. This additional configuration is not active by default and requires activating `errorprone` and `errorprone-jdk8` or `errorprone-jdk11` maven profiles in addition to `main` or `core-modules` profile for running the analysis.

### Modifications

- add a separate maven profile for running errorprone analysis
  it is not active by default

- Add top-level `lombok.config file` for configuring Lombok.
  This file doesn't contain any other settings that
  marks it as the top most config file with `config.stopBubbling = true`
  (see https://projectlombok.org/features/configuration for reference)

- Before running the Error Prone analysis, it's necessary to
  manually configure Lombok to add `@javax.annotation.Generated("lombok")`
  annotation on all fields, methods, and types that are generated.
  This makes Error Prone skip the analysis for Lombok generated code.
  - this setting cannot be enabled by default since JDK9+ doesn't include
    the `javax.annotation.Generated` annotation by default and adding the
    required dependency will change the classpath dependency resolution results.
  - There is an open issue to support lombok.Generated annotion in
    ErrorProne, https://github.com/google/error-prone/issues/1863

- example usage:
  Configure Lombok to add Generated annotations
  `echo "lombok.addJavaxGeneratedAnnotation = true" >> lombok.config`
  then,
  on JDK8
  `mvn -Perrorprone,errorprone-jdk8,core-modules compile`
  on JDK11+
  `mvn -Perrorprone,errorprone-jdk11,core-modules compile`

  - usability is better when used together with IntelliJ
    since one can click on the error message to navigate
    to the code location

- also add configuration for Error Prone SLF4J plugin
  https://github.com/KengoTODA/errorprone-slf4j
  which helps detect misusage of SLF4J API

### CODE REVIEW

**Review by sijie — APPROVED** [review]

**Comment by lhotari** [comment]
I'll revisit the changes since adding the annotations jar to provided scope will change the dependency resolution. I'll try to find another solution for JDK9+.

**Comment by asafm** [comment]
Interesting. I gave it a go after updating to the latest version as the above-mentioned annotation bug was fixed, and it failed compilation without any statement as to why. Weird.

**Pull request merged**
