### PR TITLE
Expose local run config metrics-port-start to CLI

### PR DESCRIPTION
**Pull request by jerrypeng**
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #<xyz>

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #<xyz>

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by srkukarni — APPROVED** [review]

**Review by eolivelli — COMMENTED** [review]
It looks to me that you are only adding the parameters but they are not used.
How does it work?

**Comment by jerrypeng** [comment]
@eolivelli please take a look at these lines:

https://github.com/apache/pulsar/pull/10185/files#diff-431b0dbdd81271794f0365209668a267d2d7a2c08dc695062892364a1741a173R196

**Review by eolivelli — APPROVED** [review]
LGTM

sorry for the delay, now I understand how we are applying the parameters with reflection
https://github.com/apache/pulsar/blob/0469dfe2c7804bd9ca9ea34e95d83b2196216cf9/pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java#L685

**Comment by eolivelli** [comment]
@jerrypeng can you please clean up the "description" of this PR ? it still contains the template

**Pull request merged**
