### PR TITLE
Modify authz tests of GET_TOPICS and PACKAGES op

### PR DESCRIPTION
**Pull request by yuruguo**
### Motivation
Integration authz test of [GetTopicsOfNamespaceWithAuthTest.java](https://github.com/apache/pulsar/blob/master/tests/integration/src/test/java/org/apache/pulsar/tests/integration/auth/admin/GetTopicsOfNamespaceWithAuthTest.java) and [PackagesOpsWithAuthTest.java](https://github.com/apache/pulsar/blob/master/tests/integration/src/test/java/org/apache/pulsar/tests/integration/auth/admin/PackagesOpsWithAuthTest.java) is too much heavyweight for check GET_TOPICS and PACKAGES namespace op.

In fact, we can add a small amount of code in [AuthorizationProducerConsumerTest.java](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/test/java/org/apache/pulsar/client/api/AuthorizationProducerConsumerTest.java) to replace with above integration test.

### Documentation 
- [x] `no-need-doc`

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by yuruguo** [comment]
**Important Note**: The test failure is related to this PR, I need to deal with it

**Comment by yuruguo** [comment]
**Important Note**
The test failure is related to this PR, I will deal with it.

**Review by RocMarshal — APPROVED** [review]
Good job. @yuruguo Thanks for the contribution. From my perspective this looks good. I also like to get concise in coding.

**Review by RobertIndie — APPROVED** [review]

**Review by RobertIndie — COMMENTED** [review]
I think we should remove the test class here:
https://github.com/apache/pulsar/blob/c3da1452a444c9599cb85562a3faa82ddfdecec8/tests/integration/src/test/resources/pulsar-auth.xml?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L25

**Comment by yuruguo** [comment]
> I think we should remove the test class here: https://github.com/apache/pulsar/blob/c3da1452a444c9599cb85562a3faa82ddfdecec8/tests/integration/src/test/resources/pulsar-auth.xml?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L25

I am sorry, what you suggested is exactly what we need to modify, 
It is still a integration test that need create docker to verify namespace operation, actually we can run only a simple unit tests which can save CI resources.

**Comment by yuruguo** [comment]
> I think we should remove the test class here: https://github.com/apache/pulsar/blob/c3da1452a444c9599cb85562a3faa82ddfdecec8/tests/integration/src/test/resources/pulsar-auth.xml?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L25

I agree :)

**Comment by yuruguo** [comment]
@merlimat @codelipenghui @hangc0276 PTAL, thx!

**Review by codelipenghui — APPROVED** [review]

**Comment by michaeljmarshall** [comment]
Just want to mention that this test re-write removed test coverage for admin client to proxy to broker with different kinds of authentication. I fixed it here #19557.

**Pull request merged**
