### PR TITLE
add RuntimeUtils test

### PR DESCRIPTION
**Pull request by jerrypeng**
### Motivation

Forgot to include a test that I added for https://github.com/apache/pulsar/pull/4572

### CODE REVIEW

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Pull request merged**
