### PR TITLE
Avoid double encoding for subscription name in pulsar-admin

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

Right now, Pulsar-admin encodes sub name multiple times [WebTargets](https://github.com/apache/pulsar/blob/master/pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/WebTargets.java#L35)

So, avoid multiple encoding.

### CODE REVIEW

**Comment by rdhabalia** [comment]
rerun java8 tests

**Comment by rdhabalia** [comment]
rerun integration tests

**Comment by rdhabalia** [comment]
rerun java8 tests

**Comment by rdhabalia** [comment]
rerun integration tests

**Comment by rdhabalia** [comment]
rerun java8 tests

**Comment by rdhabalia** [comment]
rerun integration tests

**Comment by merlimat** [comment]
@rdhabalia It looks there is a test failure at `AdminApiTest.persistentTopics`

```
20:07:37.433 [pulsar-web-3570:org.eclipse.jetty.server.HttpChannel@585] WARN  org.eclipse.jetty.server.HttpChannel - /admin/v2/persistent/prop-xyz/ns1/topic_%2B%26*%25%7B%7D%28%29+%5C%24%40%23%5E%25/subscription/topic_%2B%26*%25%7B%7D%28%29+%5C%24%40%23%5E%25/position/1
javax.servlet.ServletException: javax.servlet.ServletException: java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "{}"

```

**Comment by tisonkun** [comment]
Long stale and conflict. I'm trying to pick it up at #18435.

The test failure reported at https://github.com/apache/pulsar/pull/2910#issuecomment-442637019 cannot reproduce locally.

**Comment by tisonkun** [comment]
Closed as invalid. See also https://github.com/apache/pulsar/pull/18435#issuecomment-1311718467:

> Closed. It seems that other client module code depend on this double encoding behaviour - what a tech debt, lol.

**Pull request closed without merging**
