### PR TITLE
[fix] [broker] fix unload bundle count metric.

### PR DESCRIPTION
**Pull request by thetumbled**
### Motivation

Those bundles that are filtered when try to unload them should not be included in the indicator.

### Modifications

Increment the metric only when the bundle are unloaded.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/thetumbled/pulsar/pull/58

### CODE REVIEW

**Comment by thetumbled** [comment]
PTAL, thanks. @heesung-sn @Demogorgon314

**Comment by heesung-sn** [comment]
Good catch! can you also add a unit test too? thanks.

**Comment by thetumbled** [comment]
> Good catch! can you also add a unit test too? thanks.

I add an unit test, PTAL, thanks.

**Review by heesung-sn — APPROVED** [review]

**Review by Demogorgon314 — APPROVED** [review]

**Pull request merged**
