### PR TITLE
[improve][connector] Add getSinkConfig method to SinkContext

### PR DESCRIPTION
**Pull request by shibd**
### Motivation

The configuration of SinkConfig is rich, and the user can flexibly specify it when registry the sink. But some sinks do not support these configurations, for example we want to disable autoAck.

So, add SinkConfig to SinkContext, enables the sink to validate the configuration when executing the `sink.open` method.

### Modifications
- Add getSinkConfig method to SinkContext

### Documentation

- [x] `no-need-doc`

### CODE REVIEW

**Comment by shibd** [comment]
> It's better to add some tests.

Thanks, added.

**Review by freeznet — APPROVED** [review]
lgtm, any plan to add the same interface to source and function to allow user get `SourceConfig` and `FunctionConfig` from `Context`?

**Review by Technoboy- — APPROVED** [review]

**Comment by freeznet** [comment]
@shibd I think it is good if we could keep the consistency for both functions and connectors context, so please help to create an issue first, so the community can engage if you do not have much time, thanks.

**Comment by shibd** [comment]
> @shibd I think it is good if we could keep the consistency for both functions and connectors context, so please help to create an issue first, so the community can engage if you do not have much time, thanks.

@freeznet  I open pr to fix it. https://github.com/apache/pulsar/pull/16305, PTAL.

**Comment by zymap** [comment]
@shibd A suggestion about changing the existing interface. We'd better use `default` to add a new API. Otherwise, it will impact all the users who implemented that interface.

**Pull request merged**
