### PR TITLE
[clean up] remove unused filed authenticationData in ServerCnx

### PR DESCRIPTION
**Pull request by lordcheng10**
In the class ServerCnx, the variable authenticationData is not used.

### CODE REVIEW

**Comment by eolivelli** [comment]
@lordcheng10:Thanks for your contribution. For this PR, do we need to update docs?
(The [PR template contains info about doc](https://github.com/apache/pulsar/blob/master/.github/PULL_REQUEST_TEMPLATE.md#documentation), which helps others know more about the changes. Can you provide doc-related info in this and future PR descriptions? Thanks)

**Review by RobertIndie — DISMISSED** [review]

**Comment by lordcheng10** [comment]
@merlimat PTAL,thanks!

**Review by Jason918 — DISMISSED** [review]
LGTM

**Comment by lordcheng10** [comment]
@eolivelli PTAL ,thanks!

**Comment by Anonymitaet** [comment]
@lordcheng10 thanks. Please provide doc-related info in the [PR template](https://github.com/apache/pulsar/blob/master/.github/PULL_REQUEST_TEMPLATE.md#documentation) when you submit a PR, then the Bot can identify it, thanks.

> > @lordcheng10:Thanks for your contribution. For this PR, do we need to update docs? (The [PR template contains info about doc](https://github.com/apache/pulsar/blob/master/.github/PULL_REQUEST_TEMPLATE.md#documentation), which helps others know more about the changes. Can you provide doc-related info in this and future PR descriptions? Thanks)
> 
> No need to modify the document

**Review by Shoothzj — APPROVED** [review]

**Comment by Shoothzj** [comment]
@eolivelli Please take a look again

**Comment by lordcheng10** [comment]
ping

**Pull request closed without merging**
