### PR TITLE
[Issue #8204][pulsar-broker] Fixes first automatic compaction issue

### LINKED ISSUE #8204: Automatic topic compaction never triggered if no durable subscriptions are found
**Describe the bug**
If we create a topic, publish to it but we never create a durable subscription automatic compaction will never be triggered on such topic. 

This is the case when we use `SubscriptionMode.NonDurable` or we use `Reader` to read from topic.

**To Reproduce**
1. Create a namespace with a "compactionThreshold" equal to `1`
```
  $  ./pulsar-admin topics create my-topic
```
2. Produce a pair of messages with same key to topic
```
  $ ./pulsar-client produce my-topic -k 1 -m msg1
  $ ./pulsar-client produce my-topic -k 1 -m msg2
```
3. Let one or two minutes to pass (default compaction monitor timeout is 1 minute)
4. Consume messages in compacted mode from the beginning using `Reader` interface:
```
     Reader<String> reader= getClient().newReader(Schema.STRING).topic("my-topic").readCompacted(true).startMessageIdInclusive()	.startMessageId(MessageId.earliest).create();
     Message<String> msg = reader.readNext(timeoutMillis, TimeUnit.MILLISECONDS);
     System.out.println("First message value: " + msg.getValue()); // ---> This should be "msg2" but it will always be "msg1"
```

**Expected behavior**
Automatic topic compaction should work with non-durable subscriptions as well or without any subscription at all (only published data).

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by fmiguelez**
Fixes #8204

### Motivation

Details are described in the issue and also on previous pull request #8205

### Modifications

If we have no durable subscriptions yet (e.g. when using `Reader` instead of `Consumer`) use ledger total size instead of estimated backlog size that will always be equal to 0 in this case.

### Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (comments)
  - If a feature is not applicable for documentation, explain why? It is an internal change (no equivalent doc is available)

### CODE REVIEW

**Review by jiazhai — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@fmiguelez Could you please help take a look the checkstyle failure?

**Comment by fmiguelez** [comment]
> @fmiguelez Could you please help take a look the checkstyle failure?

Is it now ok?

**Comment by wolfstudy** [comment]
@fmiguelez Please fix ci error. It seems to be a check-style problem, as follows:

```
Error:  src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:[1273] (regexp) RegexpSingleline: Trailing whitespace
Error:  Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:check (check-style) on project pulsar-broker: You have 1 Checkstyle violation. -> [Help 1]
```

**Comment by codelipenghui** [comment]
Don't merge this PR, CI with name Broker Group 2 is missed in the CI tests list.

**Comment by fmiguelez** [comment]
@codelipenghui is there anything left I should do?

**Comment by codelipenghui** [comment]
@fmiguelez no, we are fixing the CI issues. After the CI fixed, I will try to rerun the test.

**Review by sijie — APPROVED** [review]

**Comment by codelipenghui** [comment]
@fmiguelez Please take a look at the failed test, seems related to this change. I copied the log here:

```
Error:  Tests run: 36, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 9.187 s <<< FAILURE! - in org.apache.pulsar.broker.service.PersistentTopicTest
Error:  testCompactionTriggeredAfterThresholdFirstInvocation(org.apache.pulsar.broker.service.PersistentTopicTest)  Time elapsed: 0.021 s  <<< FAILURE!
Wanted but not invoked:
compactor.compact(<any string>);
-> at org.apache.pulsar.broker.service.PersistentTopicTest.testCompactionTriggeredAfterThresholdFirstInvocation(PersistentTopicTest.java:1612)
Actually, there were zero interactions with this mock.

	at org.apache.pulsar.broker.service.PersistentTopicTest.testCompactionTriggeredAfterThresholdFirstInvocation(PersistentTopicTest.java:1612)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Pull request merged**
