### PR TITLE
[ci] move back PersistentStreamingDispatcherBlockConsumerTest to the flaky suite

### PR DESCRIPTION
**Pull request by nicoloboschi**
### Motivation
In https://github.com/apache/pulsar/pull/17161 we moved that class out of the flaky suite because we fixed that single test. But the class is still flaky for this test `testBrokerSubscriptionRecovery ` https://github.com/apache/pulsar/issues/17011

### Modifications

* Move the class to the flaky suite to unblock CI for other pulls  

- [x] `doc-not-needed`

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]

**Comment by mattisonchao** [comment]
@nicoloboschi   I will fix this flaky test in 24 hours, could we wait for the fix?

**Comment by nicoloboschi** [comment]
@mattisonchao we can revert this one once we merge your fix

**Comment by lhotari** [comment]
@nicoloboschi This doesn't seem to have an impact. 
example failure: https://github.com/apache/pulsar/runs/8222280666?check_suite_focus=true#step:10:1347
The test was executed as part of the broker group.

**Comment by nicoloboschi** [comment]
> @nicoloboschi This doesn't seem to have an impact. example failure: https://github.com/apache/pulsar/runs/8222280666?check_suite_focus=true#step:10:1347 The test was executed as part of the broker group. It might be a TestNG limitation.

see https://github.com/apache/pulsar/pull/17510 @lhotari

**Pull request merged**
