### PR TITLE
Fix message not dispatch for key_shared sub type in non-persistent su…

### LINKED ISSUE #9703: non-persistent topics don't seem to work with Key_Shared
**Describe the bug**
With a non-persistent topic, I see messages published in the topic stats, but consumers do not consume them if they use Key_Shared. Other consumer modes work fine.

**To Reproduce**
1. In one window, start consumer: bin/pulsar-client consume --hex -n 0 -s cli -p Earliest -t Key_Shared non-persistent://public/default/test
2. In another window, start producer: bin/pulsar-client produce -m hi,bye -k a_key non-persistent://public/default/test

**Expected behavior**
The consumer should receive the 2 messages, however nothing happens on the consumer side.

Checking the "topic stats" in the admin client shows the consumer is present, and messages are published, but the consumer stays at 0 messages received.

Changing the consumer to Shared works fine, but of course the key doesn't apply.

**Desktop (please complete the following information):**
 - OS: Pulsar docker image, deployed with Helm chart ("pulsar-mini") on Minikube

**Additional context**
I used the latest Helm chart (with Docker images 2.7.0) and deployed it on Minikube following the instructions here: https://pulsar.apache.org/docs/en/kubernetes-helm/

### PR DESCRIPTION
**Pull request by MarvinCai**
Fixes #9703

### Motivation

With a non-persistent topic, I see messages published in the topic stats, but consumers do not consume them if they use Key_Shared. Other consumer modes work fine.

### Verifying this change

Covered by existing test case, verified manually.

### CODE REVIEW

**Review by codelipenghui — COMMENTED** [review]
@MarvinCai Could you please add some tests?

**Comment by MarvinCai** [comment]
@codelipenghui added unit test, PTAL

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@MarvinCai Could you please also take a look at the `KeySharedSubscriptionTest`? I think we are providing a data provider to cover the non-persistent topic tests, but seems the test does not check the total receive messages, so for the non-persistent topic test, the test will get passed, but did not actually receive any messages.

**Comment by MarvinCai** [comment]
@codelipenghui updated the test.

**Review by codelipenghui — APPROVED** [review]

**Review by 315157973 — APPROVED** [review]
LGTM

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by sijie — APPROVED** [review]

**Pull request merged**
