### PR TITLE
[improve][test] force initialize field to avoid polluted by mocks

### PR DESCRIPTION
**Pull request by tisonkun**
Master Issue: #16912

- [x] `doc-not-needed` 

cc @Shoothzj @eolivelli @nicoloboschi @Technoboy-

### CODE REVIEW

**Comment by tisonkun** [comment]
It seems CI failed only on known flaky test https://github.com/apache/pulsar/issues/17011.

**Comment by lhotari** [comment]
@tisonkun Have you checked with a debugger or logging that the tests actually do what they are claiming to do? (for example recover after OOME)

I'm not a great fan of these tests and I'm fine with removing them. However my concern is that after the changes, they won't be really testing anything and no OOME is thrown ever.

**Comment by tisonkun** [comment]
@lhotari 

For `PulsarByteBufAllocatorDefaultTest` and `PulsarByteBufAllocatorOomThrowExceptionTest`, they assert the config and it's well verified.

For `BatchMessageContainerImplTest`, you're right that OOME isn't tested anymore. I'll try to investigate a bit.

**Comment by tisonkun** [comment]
Fixed in cbda29f5d370f592c77512abfe384efa220f4a6d.

Perhaps we can consider something like [failpoint](https://github.com/pingcap/failpoint) for Golang to noninvasive inject failure. I don't know whether the JVM ecosystem already has such library, though.

**Comment by tisonkun** [comment]
ping @Shoothzj @lhotari

**Comment by tisonkun** [comment]
ping @lhotari @codelipenghui @Shoothzj

**Review by Shoothzj — APPROVED** [review]

**Review by nicoloboschi — APPROVED** [review]

**Comment by tisonkun** [comment]
@Shoothzj @nicoloboschi could you help with merging this patch?

**Pull request merged**
