### PR TITLE
Vagrantfile update for build dependency

### LINKED ISSUE #5967: Vagrantfile problem
**Describe the bug**
When I try to setup the vm environment, and build the project. I failed because zip/unzip tools are not installed.

**To Reproduce**
1. Clear your pulsar environment
2. cd dev/ 
3. vargrant up; vagrant ssh
4. cd /pulsar
5. mvn test

**Expected behavior**
Build failure because of Pulsar Shaded Broker depends on zip/unzip tool.

**Desktop (please complete the following information):**
 - OS: macos

### PR DESCRIPTION
**Pull request by zuquan-song**
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #5967

### Motivation
Cannot build the project successfully.

### Modifications
Add install commands to install the unzip zip tools when vm sets up

### Verifying this change

- [x] Make sure that the change passes the CI checks.
This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (don't know)
  - The default values of configurations: ( no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: ( no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by zuquan-song** [comment]
It's weird that my update affects the Jenkins Unit Tests because I just modify the Vagrantfile. Anyone could help? Thanks!

**Comment by zuquan-song** [comment]
run java8 tests

**Comment by tuteng** [comment]
run cpp tests
run java8 tests
run integration tests

**Comment by tuteng** [comment]
run cpp tests
run java8 tests

**Comment by zuquan-song** [comment]
run cpp tests

**Pull request merged**
