### PR TITLE
Fix time field use error

### PR DESCRIPTION
**Pull request by casuallc**
Should check the field eventTime but not publishTime.

### CODE REVIEW

**Comment by Anonymitaet** [comment]
Thanks for your contribution. For this PR, do we need to update docs?

(The [PR template contains info about doc](https://github.com/apache/pulsar/blob/master/.github/PULL_REQUEST_TEMPLATE.md#documentation), which helps others know more about the changes. Can you provide doc-related info in this and future PR descriptions? Thanks)

**Comment by casuallc** [comment]
> Thanks for your contribution. For this PR, do we need to update docs?
> 
> (The [PR template contains info about doc](https://github.com/apache/pulsar/blob/master/.github/PULL_REQUEST_TEMPLATE.md#documentation), which helps others know more about the changes. Can you provide doc-related info in this and future PR descriptions? Thanks)

No need.

**Comment by casuallc** [comment]
I am confused with the failed tests.

There is some reason for use the field publishTime?

**Comment by casuallc** [comment]
> LGTM. Please push an empty commit to trigger the build.

What to do next ?

**Comment by tomscut** [comment]
Hi @hangc0276 @codelipenghui, could you please help review this PR? Since ```First-time contributors need a maintainer to approve running workflows.```

**Review by hangc0276 — APPROVED** [review]

**Review by Shoothzj — APPROVED** [review]

**Pull request merged**
