### PR TITLE
Update presto to 0.226

### PR DESCRIPTION
**Pull request by aahmed-se**

### CODE REVIEW

**Comment by aahmed-se** [comment]
run integration tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run integration tests

**Comment by jerrypeng** [comment]
rerun integration tests
rerun java8 tests

**Comment by PierreZ** [comment]
+1 for this PR, I was stuck during Presto startup because of `Presto requires an Oracle or OpenJDK JVM (found AdoptOpenJDK)` which has been fixed in [this commit](https://github.com/prestodb/presto/commit/988f0f2e7bd0a33b2d0d2585cb70eab078fb226c#diff-7744bcf6ae8b3ba4d34755c26beafaa1) :smile:

**Comment by skyrocknroll** [comment]
rerun integration tests
rerun java8 tests

**Comment by skyrocknroll** [comment]
rerun cpp tests

**Comment by candlerb** [comment]
Integration test failures:

```
2019-10-30\T\10:08:12.926 [INFO] -------------------------------------------------------
2019-10-30\T\10:08:12.926 [INFO]  T E S T S
2019-10-30\T\10:08:12.926 [INFO] -------------------------------------------------------
2019-10-30\T\10:08:13.423 [INFO] Running TestSuite
2019-10-30\T\11:17:27.498 [ERROR] Tests run: 87, Failures: 2, Errors: 0, Skipped: 3, Time elapsed: 4,154.023 s <<< FAILURE! - in TestSuite
2019-10-30\T\11:17:27.499 [ERROR] pulsar-test-suite(org.apache.pulsar.tests.integration.presto.TestBasicPresto)  Time elapsed: 2.261 s  <<< FAILURE!
org.apache.pulsar.tests.integration.docker.ContainerExecException: /bin/bash -c /pulsar/bin/pulsar sql --execute 'show catalogs;' failed on 50bdfb36060ff10e83189f10195798c073c6de929f3aad743223a0cf366f5487 with error code 1
	at org.apache.pulsar.tests.integration.utils.DockerUtils$2.onComplete(DockerUtils.java:259)
	at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec$1.onComplete(AbstrAsyncDockerCmdExec.java:51)
	at org.testcontainers.dockerclient.transport.okhttp.OkHttpInvocationBuilder.lambda$executeAndStream$1(OkHttpInvocationBuilder.java:297)
	at java.lang.Thread.run(Thread.java:748)

2019-10-30\T\11:17:27.501 [ERROR] pulsar-test-suite(org.apache.pulsar.tests.integration.presto.TestBasicPresto)  Time elapsed: 2.273 s  <<< FAILURE!
org.apache.pulsar.tests.integration.docker.ContainerExecException: /bin/bash -c /pulsar/bin/pulsar sql --execute 'show catalogs;' failed on 50bdfb36060ff10e83189f10195798c073c6de929f3aad743223a0cf366f5487 with error code 1
	at org.apache.pulsar.tests.integration.utils.DockerUtils$2.onComplete(DockerUtils.java:259)
	at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec$1.onComplete(AbstrAsyncDockerCmdExec.java:51)
	at org.testcontainers.dockerclient.transport.okhttp.OkHttpInvocationBuilder.lambda$executeAndStream$1(OkHttpInvocationBuilder.java:297)
	at java.lang.Thread.run(Thread.java:748)
```

I think it would be helpful to see `cee.getResult().getStderr()` here - maybe class ContainerExecException should include some stderr in its default string output.

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by sijie** [comment]
```
java.lang.RuntimeException: java.lang.UnsupportedOperationException: com.facebook.presto.spi.block.LongArrayBlock
	at org.apache.pulsar.sql.presto.PulsarSplitManager.getSplits(PulsarSplitManager.java:135)
	at org.apache.pulsar.sql.presto.TestPulsarSplitManager.testPublishTimePredicatePushdown(TestPulsarSplitManager.java:206)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedOperationException: com.facebook.presto.spi.block.LongArrayBlock
	at com.facebook.presto.spi.block.Block.getLong(Block.java:72)
	at org.apache.pulsar.sql.presto.PulsarSplitManager$PredicatePushdownInfo.getPredicatePushdownInfo(PulsarSplitManager.java:356)
	at org.apache.pulsar.sql.presto.PulsarSplitManager.getSplitsForTopic(PulsarSplitManager.java:257)
	at org.apache.pulsar.sql.presto.PulsarSplitManager.getSplitsNonPartitionedTopic(PulsarSplitManager.java:228)
	at org.apache.pulsar.sql.presto.TestPulsarSplitManager$ResultCaptor.answer(TestPulsarSplitManager.java:70)
	at org.apache.pulsar.sql.presto.PulsarSplitManager.getSplits(PulsarSplitManager.java:127)
```

@aahmed-se you need to fix the code when upgrading to a newer version.

**Pull request closed without merging**
