### PR TITLE
[schema] check if exists default constructor for avro/json schema

### LINKED ISSUE #10377: Schema prevents usage of Dead Letter Queue DLQ
**Describe the bug**
When using a Schema pushing a negativeAcknowledged Message to a DeadletterQueue will fail.
There is no obvious Errors/Exceptions. The Message, just stay in the current Topic and is never published to the DLQ-Topic.
When using no Schema oder Schema.STRING it will work.

This happende when using pulsar 2.7.1 and the Java-Client.

Pulsar was started as standalone docker container.
```
$ docker run -it \
  -p 6650:6650 \
  -p 8080:8080 \
  --mount source=pulsardata,target=/pulsar/data \
  --mount source=pulsarconf,target=/pulsar/conf \
  apachepulsar/pulsar:2.7.1 \
  bin/pulsar standalone
```

**To Reproduce**
I created an repo with some code for this issue: https://github.com/jvoigt/pulsar-schema-dlq-issue

1. Create Producer to topic with Schema `pulsarClient.newProducer(JSONSchema.of(Payload.class)).create()`
2. Send Message to Producer `producer.send( new Payload("My Json message"))`
3. Consume Topic with Schema AND DLQ `pulsarClient.newConsumer(schema).topic(topic)                .deadLetterPolicy(DeadLetterPolicy.builder().maxRedeliverCount(3).build()).subscribe()`
4. receive the Message, but use a nack. `consumer.negativeAcknowledge(msg);` 
5. The Message will be redeliverd  3 Times, then the DLQ-Topic ist automatically create.
6. But the Message is never sent.

**Logs**
See the attached Repo for detailed Logs:
But Mainly you can see that the client is creating a new Producer for the DLQ-Topic and then nothing more happens.

```
Apr 26, 2021 8:19:13 AM com.jvoigt.issue.MyListener received
INFO:  persistent://public/default/jsonTopic => Message received: {"message":"My Json message"}
Apr 26, 2021 8:19:13 AM com.jvoigt.issue.MyListener received
SEVERE: persistent://public/default/jsonTopic => I WILL NACK IT with Counter: 3
Apr 26, 2021 8:19:16 AM org.apache.pulsar.client.impl.UnAckedMessageTracker$2 run
WARNING: [ConsumerBase{subscription='subscription', consumerName='5416a', topic='jsonTopic'}] 1 messages have timed-out
Apr 26, 2021 8:19:16 AM org.apache.pulsar.client.impl.ProducerStatsRecorderImpl init
INFO: Starting Pulsar producer perf with config: {
  "topicName" : "jsonTopic-subscription-DLQ",
.....
}
Apr 26, 2021 8:19:16 AM org.apache.pulsar.client.impl.ProducerStatsRecorderImpl init
INFO: Pulsar client config: {
  "serviceUrl" : "pulsar://localhost:6650",
.....
}
Apr 26, 2021 8:19:16 AM org.apache.pulsar.client.impl.ProducerImpl connectionOpened
INFO: [jsonTopic-subscription-DLQ] [null] Creating producer on cnx [id: 0x7861b6d7, L:/127.0.0.1:43226 - R:localhost/127.0.0.1:6650]
Apr 26, 2021 8:19:16 AM org.apache.pulsar.client.impl.ProducerImpl lambda$connectionOpened$16
INFO: [jsonTopic-subscription-DLQ] [standalone-6-1] Created producer on cnx [id: 0x7861b6d7, L:/127.0.0.1:43226 - R:localhost/127.0.0.1:6650]
Apr 26, 2021 8:20:04 AM org.apache.pulsar.client.impl.ConsumerStatsRecorderImpl lambda$init$0
INFO: [jsonTopic] [subscription] [5416a] Prefetched messages: 0 --- Consume throughput received: 0.07 msgs/s --- 0.00 Mbit/s --- Ack sent rate: 0.00 ack/s --- Failed messages: 0 --- batch messages: 0 ---Failed acks: 0
Apr 26, 2021 8:20:24 AM org.apache.pulsar.client.impl.ProducerStatsRecorderImpl init
INFO: Starting Pulsar producer perf with config: {
  "topicName" : "jsonTopic-subscription-DLQ",
.....
}
Apr 26, 2021 8:20:24 AM org.apache.pulsar.client.impl.ProducerStatsRecorderImpl init
INFO: Pulsar client config: {
  "serviceUrl" : "pulsar://localhost:6650",
.....
}
Apr 26, 2021 8:20:24 AM org.apache.pulsar.client.impl.ProducerImpl connectionOpened
INFO: [jsonTopic-subscription-DLQ] [null] Creating producer on cnx [id: 0x7861b6d7, L:/127.0.0.1:43226 - R:localhost/127.0.0.1:6650]
Apr 26, 2021 8:20:24 AM org.apache.pulsar.client.impl.ProducerImpl lambda$connectionOpened$16
INFO: [jsonTopic-subscription-DLQ] [standalone-6-2] Created producer on cnx [id: 0x7861b6d7, L:/127.0.0.1:43226 - R:localhost/127.0.0.1:6650]`
```

### LINKED ISSUE #10393: Struct schema(AvroSchema/JSONSchema) cannot decode without default constructor.
Related #10377

**Is your enhancement request related to a problem? Please describe.**
Struct schema(AvroSchema/JSONSchema) cannot decode without default constructor.

**Reproduce code**
```
@Data
@AllArgsConstructor
public static class Payload {
    String message;
}

public static void main(String[] args) {
    AvroSchema<Payload> schema = AvroSchema.of(Payload.class);
    Payload payload = new Payload("test");
    byte[] encode = schema.encode(payload);
    schema.decode(encode);
}
```

**AvroSchema Exception stack**
```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoSuchMethodException: org.apache.pulsar.client.impl.schema.JSONSchema$Payload.<init>()
	at org.apache.avro.specific.SpecificData.newInstance(SpecificData.java:466)
	at org.apache.avro.specific.SpecificData.newRecord(SpecificData.java:484)
	at org.apache.avro.reflect.ReflectData.newRecord(ReflectData.java:1038)
	at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:236)
	at org.apache.avro.specific.SpecificDatumReader.readRecord(SpecificDatumReader.java:123)
	at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:179)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:160)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:153)
	at org.apache.pulsar.client.impl.schema.reader.AvroReader.read(AvroReader.java:75)
	at org.apache.pulsar.client.api.schema.SchemaReader.read(SchemaReader.java:39)
	at org.apache.pulsar.client.impl.schema.reader.AbstractMultiVersionReader.read(AbstractMultiVersionReader.java:62)
	at org.apache.pulsar.client.api.schema.SchemaReader.read(SchemaReader.java:39)
	at org.apache.pulsar.client.impl.schema.AbstractStructSchema.decode(AbstractStructSchema.java:55)
	at org.apache.pulsar.client.impl.schema.JSONSchema.main(JSONSchema.java:75)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: org.apache.pulsar.client.impl.schema.JSONSchema$Payload.<init>()
	at org.apache.avro.specific.SpecificData$1.computeValue(SpecificData.java:67)
	at org.apache.avro.specific.SpecificData$1.computeValue(SpecificData.java:58)
	at java.lang.ClassValue.getFromHashMap(ClassValue.java:227)
	at java.lang.ClassValue.getFromBackup(ClassValue.java:209)
	at java.lang.ClassValue.get(ClassValue.java:115)
	at org.apache.avro.specific.SpecificData.newInstance(SpecificData.java:463)
	... 13 more
Caused by: java.lang.NoSuchMethodException: org.apache.pulsar.client.impl.schema.JSONSchema$Payload.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.apache.avro.specific.SpecificData$1.computeValue(SpecificData.java:63)
	... 18 more
```

**JSONSchema Exception stack**
```
Exception in thread "main" org.apache.pulsar.client.api.SchemaSerializationException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `org.apache.pulsar.client.impl.schema.JSONSchema$Payload` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (byte[])"{"message":"test"}"; line: 1, column: 2]
	at org.apache.pulsar.client.impl.schema.reader.JacksonJsonReader.read(JacksonJsonReader.java:49)
	at org.apache.pulsar.client.api.schema.SchemaReader.read(SchemaReader.java:39)
	at org.apache.pulsar.client.impl.schema.AbstractStructSchema.decode(AbstractStructSchema.java:55)
	at org.apache.pulsar.client.impl.schema.JSONSchema.main(JSONSchema.java:75)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `org.apache.pulsar.client.impl.schema.JSONSchema$Payload` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (byte[])"{"message":"test"}"; line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1455)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1081)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1332)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3504)
	at org.apache.pulsar.client.impl.schema.reader.JacksonJsonReader.read(JacksonJsonReader.java:47)
	... 3 more
```

### PR DESCRIPTION
**Pull request by linlinnn**
Fixes #10393
Fixes #10377

**Motivation**
Check if exists default constructor for avro/json schema
Simplify code

**Verify**
Add unit test

### CODE REVIEW

**Comment by david-streamlio** [comment]
LGTM

**Review by codelipenghui — APPROVED** [review]

**Review by gaoran10 — APPROVED** [review]
LGTM

**Review by congbobo184 — CHANGES_REQUESTED** [review]
I don't think it is a good change, avro api has checked this. we don't need to check this, give it to avro api is better.

**Comment by linlinnn** [comment]
> I don't think it is a good change, avro api has checked this. we don't need to check this, give it to avro api is better.

@congbobo184 
Could you point it out please?
I want to check this during init schema, otherwise will cause the issue that send message successfully but consume message failed.
```java
@Data
@AllArgsConstructor
public static class Payload {
    String message;
}

public static void main(String[] args) {
    AvroSchema<Payload> schema = AvroSchema.of(Payload.class);
    Payload payload = new Payload("test");
    ...
    producer.send(payload); // successfully
    Message<Payload> message = consumer.receive();
    message.getValue();        // exception
}
```

**Comment by congbobo184** [comment]
@linlinnn Do we need to track every question about avro in advance? consume failed has given you an error about this, why we need to check in pulsar `AvroSchema`?

**Comment by linlinnn** [comment]
@congbobo184 
From the side of design, I totally agree with your consideration.
My purpose is to help user being aware of this problem as far as possible, because it's common that there are no default constructor, even in pulsar test case.
I will try to fix this issue in arvo/json library side.

**Pull request closed without merging**
