### PR TITLE
[pulsar-perf] Support version command

### PR DESCRIPTION
**Pull request by yuruguo**
### Motivation
Support `version` command to get the current version of pulsar in `pulsar-perf`

### Modifications
- Modify script `pulsar-perf`. Call `org.apache.pulsar.PulsarVersionStarter` when the command is `version`
- Modify document `reference-cli-tools.md`. Show usage of `version` command

### Documentation
- need to update docs

### CODE REVIEW

**Comment by yuruguo** [comment]
@merlimat @aahmed-se @eolivelli @k2la @codelipenghui @315157973 @hangc0276 @gaoran10 PTAL, thx!

**Comment by hangc0276** [comment]
`version` just represents the version of the current pulsar server, we'd better added it into `bin/pulsar` command instead of `bin/pulsar-perf` ?

**Comment by yuruguo** [comment]
> Why should this feature be added to perf?

`bin/pulsar-perf` can run a producer/consumer to produce/consume data. If user want to know the version of the pulsar server quickly and conveniently, they can get it directly through `bin/pulsar-perf version`.
ps: Currently,  `bin/pulsar` / `bin/pulsar-admin` / `bin/pulsar-client` all support the `version` command.

**Comment by yuruguo** [comment]
> @yuruguo should we add the `version` flag to the code files in `https://github.com/apache/pulsar/tree/master/pulsar-testclient/src`? Example: https://github.com/apache/pulsar/pull/11933/files

No need, the two are implemented in different ways.

**Comment by yuruguo** [comment]
@merlimat @aahmed-se @eolivelli @k2la @codelipenghui @gaoran10 PTAL, thx!

**Pull request closed without merging**
