### PR TITLE
[Proxy] Use shared internal and external executor for broker clients

### PR DESCRIPTION
**Pull request by lhotari**
### Motivation

Pulsar Proxy will create a new Pulsar Client instance for each and every proxied connection. 

Currently 2 threads will be created for every Pulsar Client instance for the internal/IO and external/listener  executors. This causes a lot of overhead and inefficiency in the Pulsar Proxy. 

In the current solution, it's already possible to share the EventLoopGroup and HashedWheelTimer instances. Support for sharing the timer was added by #9802.

A recently merged PR, #12037, added support for sharing the the internal/IO and external/listener  executors in PulsarClientImpl instances. This feature has been used in this PR to share the executors across all PulsarClientImpl instances created in the Pulsar Proxy.

### Modifications

- add new configuration key `brokerClientNumIOThreads` which can be used to configure the number of threads for the internal/IO executor. It defaults to 2 * number of available processors.
- create shared executors in ProxyService
- add method for creating PulsarClientImpl to ProxyService that uses the shared executors
- refactor ProxyConnection to use this method for PulsarClientImpl instantiation

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
the change makes sense to me.

nice work!

do you have numbers to share in order to demonstrate the effects ?

**Comment by lhotari** [comment]
> do you have numbers to share in order to demonstrate the effects ?

@eolivelli I don't. The main impact is the fact that more threads won't be created when the number of proxy connections increase.

btw. I noticed a surprising detail of the client usage in the proxy: the client isn't used at all. I'll revisit this PR.

**Comment by lhotari** [comment]
This PR has been replaced with an improved solution in #13836.

**Comment by lhotari** [comment]
#13839 is for using shared executors for broker client / geo-replication clients

**Pull request closed without merging**
