### PR TITLE
[fix][test] Try fix PulsarSinkE2ETest.testPulsarSinkDLQ

### PR DESCRIPTION
**Pull request by tisonkun**
This refers to #16578.

`setNegativeAckRedeliveryDelayMs` to 1 ms so that messages are sent to DLQ quickly.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/tisonkun/pulsar/pull/18

### CODE REVIEW

**Comment by tisonkun** [comment]
Forked CI didn't fail on Broker Group 2. Trigger here to another verification.

**Comment by tisonkun** [comment]
cc @codelipenghui @mattisonchao

**Review by nodece — APPROVED** [review]

**Comment by tisonkun** [comment]
Merging...

I'm unsure whether there's bug but it seems the original config/condition is too strict on time that can be easily failed under heavy load.

**Pull request merged**
