### PR TITLE
Update the issuer url in the doc

### PR DESCRIPTION
**Pull request by zymap**
---

*Motivation*

Fix the issuer url is using the token endpoint.

### CODE REVIEW

**Review by jiazhai — APPROVED** [review]

**Comment by jiazhai** [comment]
@wolfstudy, just opened an issue for the ci failure: https://github.com/apache/pulsar/issues/7978
it is related to PulsarFunctionE2ETest
would you please help take a look?

**Review by Huanli-Meng — APPROVED** [review]

**Comment by zymap** [comment]
@Huanli-Meng @Jennifer88huang @jiazhai Because this is a doc change, could we merge it without ci check?

**Comment by Jennifer88huang** [comment]
@zymap we have no permission to merge it before the CI checks pass. The rule is set by admin.

**Review by sijie — APPROVED** [review]

**Pull request merged**
