### PR TITLE
[improve][io] Upgrade Hadoop and HBase versions

### PR DESCRIPTION
**Pull request by sekikn**
### Motivation

Recently, the latest version of Hadoop and HBase were released, 3.3.5 and 2.4.16 respectively. This PR upgrades them to ensure that the current Pulsar IOs work with them.

### Modifications

Updated the version number of those dependencies in pom.xml.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is already covered by existing tests, such as the tests under pulsar-io/hdfs3/src/test/java and pulsar-io/hbase/src/test/java.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [x] Dependencies (add or upgrade a dependency)
  - Hadoop and HBase were upgraded to 3.3.5 and 2.4.16 respectively.
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/sekikn/incubator-pulsar/pull/12 (failed on BROKER_GROUP_1 but seems to be unrelated to this fix)

### CODE REVIEW

**Review by nicoloboschi — APPROVED** [review]
Technically the other changes were unrelated since these versions are only related to pulsar-io/hdfs3
However I agree it's better to get them aligned

**Review by tisonkun — APPROVED** [review]
Bumping patches version should be safe.

Thanks for your contribution!

**Comment by tisonkun** [comment]
Merging...

**Pull request merged**
