### PR TITLE
Gracefully shutdown function worker service

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

Right now, if broker is down when function service starts, it fails to start worker and keeps the process hanging in a failure state. Also, function-worker doesn't close resource on sigterm or while shutting down.
```

	19:26:56.037 [main] ERROR org.apache.pulsar.functions.worker.Worker - Failed to start worker
java.lang.RuntimeException: java.lang.RuntimeException: org.apache.pulsar.client.api.PulsarClientException$TimeoutException: 0 lookup request timedout after ms 1
	at org.apache.pulsar.functions.worker.WorkerService.start(WorkerService.java:184) ~[classes/:?]
	at org.apache.pulsar.functions.worker.Worker.doStartImpl(Worker.java:64) ~[classes/:?]
	at org.apache.pulsar.functions.worker.Worker.doStart(Worker.java:52) [classes/:?]
	at com.google.common.util.concurrent.AbstractService.startAsync(AbstractService.java:211) [guava-21.0.jar:?]
	at org.apache.pulsar.functions.worker.FunctionWorkerStarter.main(FunctionWorkerStarter.java:64) [classes/:?]
```
### Modifications

- shutdown worker if it fails to start
- gracefully shutdown worker service.

### CODE REVIEW

**Comment by sijie** [comment]
retest this please

**Comment by rdhabalia** [comment]
rerun tests please

**Comment by rdhabalia** [comment]
retest this please

**Comment by sijie** [comment]
run cpp tests

**Pull request merged**
