### PR TITLE
Inactive topic policies support cross multiple clusters

### PR DESCRIPTION
**Pull request by mattisonchao**
Master Issue: #13444

Motivation
Inactive topic policies support cross multiple clusters

Documentation
- [x] no-need-doc

### CODE REVIEW

**Comment by mattisonchao** [comment]
@315157973 @codelipenghui PTAL

**Review by 315157973 — APPROVED** [review]

**Review by Jason918 — APPROVED** [review]

**Comment by mattisonchao** [comment]
@315157973 

I have resolved the conflict.

**Pull request merged**
