### PR TITLE
Merge module pulsar-client-tools-test into pulsar-client-tools

### PR DESCRIPTION
**Pull request by liketic**
The module ```pulsar-client-tools-test``` only contains some test cases for module ```pulsar-client-tools```. We can merge it into ```pulsar-client-tools```.

### CODE REVIEW

**Comment by merlimat** [comment]
I think there was some dependency issue in having these tests in the `pulsar-client-tools` module.

**Comment by liketic** [comment]
run java8 tests
run integration tests

**Comment by liketic** [comment]
run java8 tests
run integration tests
run cpp tests

**Comment by liketic** [comment]
@sijie The purpose is move the test and source code into one module. However, seems I missed the dependency problem which make us separate them. I'll close this one.

**Pull request closed without merging**
