### PR TITLE
[cleanup][broker] remove unused method getTotalServiceUnitsLoaded

### PR DESCRIPTION
**Pull request by lordcheng10**
### Motivation
remove unused method getTotalServiceUnitsLoaded.

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [x] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### Matching PR in forked repository

PR in forked repository: 

[[run-tests][clean][broker] remove unused method getTotalServiceUnitsLoaded ](https://github.com/lordcheng10/pulsar/pull/21)

### CODE REVIEW

**Comment by lordcheng10** [comment]
@aloyszhang PTAL,thanks!

**Review by aloyszhang — APPROVED** [review]

**Comment by lordcheng10** [comment]
@AnonHxy PTAL,thanks!

**Review by AnonHxy — APPROVED** [review]

**Pull request merged**
