### PR TITLE
[Docs] Add delete-dynamic-config command for brokers

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <ranxiaolong716@gmail.com>

### Motivation

`delete-dynamic-config` document missing

### Modifications

Add `delete-dynamic-config` command for **pulsar-admin brokers**.

### CODE REVIEW

**Comment by wolfstudy** [comment]
@sijie @jiazhai @codelipenghui PTAL

**Comment by wolfstudy** [comment]
run cpp tests
run java8 tests
run integration tests

**Comment by wolfstudy** [comment]
run cpp tests
run java8 tests
run integration tests

**Comment by codelipenghui** [comment]
run cpp tests
run java8 tests

**Comment by codelipenghui** [comment]
run Integration tests

**Comment by wolfstudy** [comment]
run integration tests
run cpp tests

**Comment by wolfstudy** [comment]
run integration tests
run cpp tests

**Comment by wolfstudy** [comment]
run integration tests

**Comment by wolfstudy** [comment]
run integration tests

**Comment by wolfstudy** [comment]
> java.lang.IllegalArgumentException: No pulsar-functions-worker is alive
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at org.apache.pulsar.tests.integration.topologies.PulsarCluster.getAnyContainer(PulsarCluster.java:461)
	at org.apache.pulsar.tests.integration.topologies.PulsarCluster.getAnyWorker(PulsarCluster.java:446)
	at org.apache.pulsar.tests.integration.functions.FunctionsCLITest.checkUpload(FunctionsCLITest.java:55)
	at org.apache.pulsar.tests.integration.functions.FunctionsCLITest.checkDownload(FunctionsCLITest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

run integration tests

**Comment by wolfstudy** [comment]
run integration tests

**Comment by wolfstudy** [comment]
run cpp tests

**Comment by wolfstudy** [comment]
run cpp tests

**Comment by wolfstudy** [comment]
run integration tests

**Pull request merged**
