### PR TITLE
Add package management REST API show in doc

### PR DESCRIPTION
**Pull request by zymap**
---

Master Issue: #8676

*Motivation*

Show REST API examples in the website.

*Modifications*

Add website related changes for package management REST APIs.

*ScreenShot*

Screen Shot 2020-12-10 at 5 25 18 PM

### CODE REVIEW

**Comment by zymap** [comment]
test failed:
```
------- Starting test [TestClass name=class org.apache.pulsar.tests.integration.SmokeTest].checkMessages([])-------
Error: ~~ SKIPPED -- [TestClass name=class org.apache.pulsar.tests.integration.SmokeTest].checkMessages([])-------[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 305.039 s <<< FAILURE! - in TestSuite
Error:  setup(org.apache.pulsar.tests.integration.SmokeTest)  Time elapsed: 305.038 s  <<< FAILURE!
org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:330)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
	at org.apache.pulsar.tests.integration.SmokeTest.setup(SmokeTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.testng.TestRunner.privateRun(TestRunner.java:764)
	at org.testng.TestRunner.run(TestRunner.java:585)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
	... 32 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:498)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 33 more
Caused by: java.lang.IllegalStateException: Container exited with code 255
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:470)
	... 35 more

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    SmokeTest.setup:43 » ContainerLaunch Container startup failed
[INFO] 
Error:  Tests run: 3, Failures: 1, Errors: 0, Skipped: 2
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache Pulsar :: Tests 2.8.0-SNAPSHOT:
[INFO] 
[INFO] Apache Pulsar :: Tests ............................. SUCCESS [  1.503 s]
[INFO] Apache Pulsar :: Tests :: Docker Images ............ SUCCESS [  0.337 s]
[INFO] Apache Pulsar :: Tests :: Docker Images :: Java Test Functions SUCCESS [  0.858 s]
[INFO] Apache Pulsar :: Tests :: Docker Images :: Latest Version Testing SUCCESS [  0.272 s]
[INFO] Apache Pulsar :: Tests :: Integration .............. SUCCESS [05:57 min]
[INFO] Apache Pulsar :: Tests :: Backwards Client Compatibility 2.0.0-rc1-incubating FAILURE [05:05 min]
[INFO] Apache Pulsar :: Tests :: Backwards Client Compatibility 2.0.1-incubating SKIPPED
[INFO] Apache Pulsar :: Tests :: Pulsar-Client-All-Shade Test SKIPPED
[INFO] Apache Pulsar :: Tests :: Pulsar-Client-Shade Test . SKIPPED
[INFO] Apache Pulsar :: Tests :: Pulsar-Client-Admin-Shade Test SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11:06 min
[INFO] Finished at: 2020-12-10T13:08:12Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project bc_2_0_0: There are test failures.
```

**Review by tuteng — APPROVED** [review]
LGTM

**Review by sijie — APPROVED** [review]

**Pull request merged**
