### PR TITLE
Enable CheckStyle Plugin in Pulsar client api

### PR DESCRIPTION
**Pull request by goflutterjava**
### Motivation
currently, the `pulsar-client-api` module is not protected by the `checkstyle-plugin`.
### Modifications
- Enable CheckStyle Plugin
- Fix checkstyle violations
### Documentation
Check the box below and label this PR (if you have committer privilege).
Need to update docs?
- [x] `no-need-doc`
java checkstyle changes, no need doc.

### CODE REVIEW

**Comment by goflutterjava** [comment]
@codelipenghui @hangc0276 PTAL, thanks

**Review by hangc0276 — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
