### PR TITLE
[Doc][Improve] Add images to /assets

### PR DESCRIPTION
**Pull request by DaveDuggins**
This PR fixes issue #17960.

### Motivation

Builds automatically failed because images used in concepts-messaging.md were not found.

### Modifications

Add images to /assets for concepts-messaging.md

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

### Documentation

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by tisonkun — COMMENTED** [review]
Thank you!

You may update the file `site2/docs/concepts-messaging.md` to reduce reference to `https://user-images.githubusercontent.com/xxx.xvg`.

In this patch, the following image is unused in the whole docsite. Please check.

* message-delay.svg
* pulsar-exclusive-subscription.svg
* pulsar-failover-subscriptions.svg
* pulsar-key-shared-subscriptions.svg
* pulsar-shared-subscriptions.svg

**Comment by Huanli-Meng** [comment]
@DaveDuggins do you want to reference these images in the Messaging doc? If yes, you need to update the related image links in the Messaging MD file.

**Comment by momo-jun** [comment]
@DaveDuggins I have the same comment with Tison. Can you pls respond and clarify the intention further before we can move it forward?

**Comment by Anonymitaet** [comment]
@DaveDuggins before submitting images, make sure:
- Test your changes locally, make sure all images are shown correctly, and attach the screenshots of local previews in the PR description
- Verify all the images are used in docs 

Thank you!

**Comment by tisonkun** [comment]
@DaveDuggins Since the SVG files is present, I'm going to take over this PR to fix the site build issue - this patch still have some name mismatches issue. I'll add you as the coauthor for the superseding patch. See also #17991.

**Pull request closed without merging**
