### PR TITLE
[improve][doc] Use Text Blocks to improve JSON text

### PR DESCRIPTION
**Pull request by coderzc**
### Motivation

The JSON text has a lot of escape characters, we can use [Text Blocks](https://docs.oracle.com/en/java/javase/15/text-blocks/index.html) to improve it.

### Modifications

Use Text Blocks to improve JSON text

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [ ] `doc-not-needed` 
(Please explain why)
  
- [x] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by poorbarcode — APPROVED** [review]

**Comment by nodece** [comment]
Could you use `"` instead of `'`?

**Comment by coderzc** [comment]
> Could you use `"` instead of `'`?

OK.

**Comment by coderzc** [comment]
@nodece PTAL

**Review by nodece — APPROVED** [review]
LGTM

**Comment by nodece** [comment]
Overall job is optional, so you don't need to rerun the failure job.

**Review by tisonkun — APPROVED** [review]
Cool! Glad to see we gradually use new features beyond JDK11.

Out of the topic, we may be careful about using some new features like `var` - they will cause significant style inconsistency.

**Comment by nodece** [comment]
This is a good start, but we may need to note that this change does not benefit the cherry-pick operations, the old version doesn't support this syntax.

**Comment by coderzc** [comment]
> Overall job is optional, so you don't need to rerun the failure job.

It seems "Pulsar CI / Pulsar CI checks completed" be dependent on other tasks.

**Comment by coderzc** [comment]
@momo-jun PTAL

**Comment by tisonkun** [comment]
> @momo-jun PTAL

I just notice this is for example shown on the doc. It can be a concern that leading whitespace may cause margin error. But fortunately Java text block detect margin by the close `"""` and these changes should be fine. See also https://docs.oracle.com/en/java/javase/15/text-blocks/index.html.

**Comment by coderzc** [comment]
> Cool! Glad to see we gradually use new features beyond JDK11.
> 
> Out of the topic, we may be careful about using some new features like `var` - they will cause significant style inconsistency.

@tisonkun Another PR(#17296) also uses Text Blocks to improve doc annotation, please take a look, thanks!

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
