### PR TITLE
[cleanup][broker] Cleanup ManagedLedgerImpl's nouse method: isLedgersReadonly

### PR DESCRIPTION
**Pull request by StevenLuMT**
### Motivation

Cleanup ManagedLedgerImpl's nouse method: isLedgersReadonly

### Modifications
Cleanup ManagedLedgerImpl.isLedgersReadonly.

### Verifying this change
- [x] Make sure that the change passes the CI checks.
This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation
Check the box below or label this PR directly.

Need to update docs?

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository
PR in forked repository: https://github.com/StevenLuMT/pulsar/pull/5

### CODE REVIEW

**Review by HQebupt — APPROVED** [review]

**Review by AnonHxy — APPROVED** [review]

**Comment by michaeljmarshall** [comment]
@StevenLuMT - what is the justification for removing this method? We added it as part of PIP 180. I think we should consult with @Jason918 before we do this kind of cleanup up, as this feature was only just added in November with #18265 and might not be something we should remove.

**Comment by Jason918** [comment]
> @StevenLuMT - what is the justification for removing this method? We added it as part of PIP 180. I think we should consult with @Jason918 before we do this kind of cleanup up, as this feature was only just added in November with #18265 and might not be something we should remove.

@michaeljmarshall  Thank you for the reminding. It's OK to delete this. I add this method during locally updates. It's not used any more.

**Comment by StevenLuMT** [comment]
> > @StevenLuMT - what is the justification for removing this method? We added it as part of PIP 180. I think we should consult with @Jason918 before we do this kind of cleanup up, as this feature was only just added in November with #18265 and might not be something we should remove.
> 
> @michaeljmarshall Thank you for the reminding. It's OK to delete this. I add this method during locally updates. It's not used any more.

@michaeljmarshall  I have communicated with @Jason918 , it's not use any more, 
thank you very much

**Comment by michaeljmarshall** [comment]
Great! Thanks for verifying.

**Review by michaeljmarshall — APPROVED** [review]

**Pull request merged**
