### PR TITLE
[improve][misc] Upgrade Netty to 4.1.104 and io_uring to 0.0.24

### PR DESCRIPTION
**Pull request by lhotari**
### Motivation

Keep Netty and Netty's io_uring libraries up-to-date. 

Release notes since last upgrades:
- https://netty.io/news/2023/12/15/4-1-104-Final.html
- https://netty.io/news/2023/12/13/4-1-103-Final.html
- https://netty.io/news/2023/11/09/4-1-101-Final.html
- https://netty.io/news/2023/11/17/io_uring_0-0-24-Final.html
- https://netty.io/news/2023/10/02/multiple_releases_incubator.html

### Modifications

- Upgrade Netty to 4.1.104.Final (from 4.1.100.Final)
- Upgrade Netty io_uring to 0.0.24.Final (from 0.0.21.Final)

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by Technoboy- — APPROVED** [review]

**Review by coderzc — APPROVED** [review]

**Comment by lhotari** [comment]
@Technoboy- Alluxio isn't compatible with Netty 4.1.103 for some reason which doesn't produce a proper error message. AlluxioSinkTest fails.  Do you have ideas how to fix this problem?

**Comment by lhotari** [comment]
I'm trying to pin the versions in Alluxio connector using dependencyManagement . That should be effective. Picking versions listed in https://repo1.maven.org/maven2/org/alluxio/alluxio-parent/2.9.3/alluxio-parent-2.9.3.pom

**Comment by lhotari** [comment]
I moved the pulsar-io/alluxio Netty version pinning solution to #21728 . That is needed before this PR can be merged.

**Comment by lhotari** [comment]
4.1.103 is broken on MacOS on Intel. Let's wait for a fix to this issue in Netty: https://github.com/netty/netty/issues/13728

**Comment by merlimat** [comment]
> 4.1.103 is broken on MacOS on Intel. Let's wait for a fix to this issue in Netty: [netty/netty#13728](https://github.com/netty/netty/issues/13728)

4.1.104 seems to be already out: https://netty.io/news/2023/12/15/4-1-104-Final.html

**Comment by lhotari** [comment]
> 4.1.104 seems to be already out: https://netty.io/news/2023/12/15/4-1-104-Final.html

@merlimat Thanks, Now upgraded to 4.1.104 which fixes the issue in 4.1.103.

**Pull request merged**
