### PR TITLE
[refactor][broker] Remove EntryWrapper usages and use MessageMetadata instead

### PR DESCRIPTION
**Pull request by BewareMyPower**
### Motivation

https://github.com/apache/pulsar/pull/7266 introduced the `EntryWrapper`
to store the `Entry` object and the associated `MessageMetadata` if it
exists. However, the `getEntry` field of `EntryWrapper` is never used.
There is no need to allocate memory for `EntryWrapper`, even if it's
allocated from the recycler pool.

### Modifications

- Calculate the remaining messages without creating `EntryWrapper`
  object, just iterate over the parsed message metadata list.
- Pass an optional `MessageMetadata` array to `filterEntriesForConsumer`
  and add the JavaDocs for these two parameters.

After that, Remove unused `EntryWrapper` and `updateEntryWrapperWithMetadata`.
This PR uses functional programming style to make code more simple and clear.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is already covered by existing tests, such as
`testBatchMessageDispatchingAccordingToPermits`.

### Documentation

Check the box below or label this PR directly.

Need to update docs?

- [ ] `doc-required`
(Your PR needs to update docs and you will update later)

- [x] `doc-not-needed`
(Please explain why)

- [ ] `doc`
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Comment by eolivelli** [comment]
@BewareMyPower @codelipenghui please give time for other reviewers to see such important patches.
This patch is touching critical parts of the Broker.

I believe that for non trivial patches we must at least give 1 day for people to see what's going on.

cc @merlimat @rdhabalia @codelipenghui @lhotari

**Comment by codelipenghui** [comment]
@eolivelli Yes, agree.

**Comment by BewareMyPower** [comment]
Sorry for the quick merge since this is a part of my development that I want to split it into multiple PRs. @eolivelli 

And unfortunately, just now I found this PR introduced a bug that I will fix it soon.

**Comment by BewareMyPower** [comment]
After digging for a while, this PR didn't introduce a bug but it changed the original behavior a little and could bring unexpected behavior. I'll open a new PR and explain it in details.

**Pull request merged**
