### PR TITLE
[Issue 5626][pulsar-function-go] Fix a memory leak of pulsar-function-go library regarding time.NewTimer()

### PR DESCRIPTION
**Pull request by Sunkwan-Kwon**
### Motivation
There is a memory leak in the pulsar-function-go library.

It is related to KillAfterIdleMs configuration value. If I set the value to 0, time.NewTimer() function has occupied more memory indefinitely.

Refer to the issue for more detail. (#5626)

### Modifications
If `killAfterIdleMs` is 0, time.After() function call makes memory leak. Refer to https://golang.org/pkg/time/#After. According to the document, the underlying Timer object is not recovered by the garbage collector if the timer is not fired. And It seems that if the duration is 0, it will not be released. Therefore, use one Timer object for idle time checking explicitly instead of the time.After() function.

### Verifying this change
Verified it by reproducing step described in the issue #5626.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by jiazhai** [comment]
run integration tests
run java8 tests

**Comment by Sunkwan-Kwon** [comment]
Is there any update for merging?

**Comment by sijie** [comment]
run integration tests

**Comment by Sunkwan-Kwon** [comment]
Hello. @wolfstudy.
Could you review this PR?

**Comment by sijie** [comment]
@wolfstudy please review this pull request.

**Comment by wolfstudy** [comment]
run integration tests

**Comment by wolfstudy** [comment]
run java8 tests
run cpp tests
run integration tests

**Comment by wolfstudy** [comment]
run java8 tests

**Pull request merged**
