### PR TITLE
[Issue 5775][Doc] Description of broker-tool added

### PR DESCRIPTION
**Pull request by BGRichi**
Fixes https://github.com/apache/pulsar/issues/5775

### Motivation
Add the description for broker-tool accordingly.
Refer to: https://github.com/apache/pulsar/pull/5768

### Modifications
broker-tool section added.

### Verifying this change
This change needs to be reviewed.

### Does this pull request potentially affect one of the following parts:
Dependencies (does it add or upgrade a dependency): (no)
The public API: (no)
The schema: (no)
The default values of configurations: (no)
The wire protocol: (no)
The rest endpoints: (no)
The admin cli options: (no)
Anything that affects deployment: (no)

### Documentation
Does this pull request introduce a new feature? (yes)
If yes, how is the feature documented? ( docs )
If a feature is not applicable for documentation, explain why?
If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by tuteng** [comment]
retest this please

**Comment by sijie** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by Jennifer88huang** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by Jennifer88huang** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Pull request merged**
