### PR TITLE
Fix Log4cxx support

### PR DESCRIPTION
**Pull request by lbenc135**
### Motivation

Currently the log4cxx support is broken because of a recent refactor.

### Modifications

Fixed the Log4Cxx logger refactor.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This is a trivial change.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): no
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no
  - The rest endpoints: no
  - The admin cli options: no
  - Anything that affects deployment: no

### Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by merlimat** [comment]
@lbenc135 the CMake flag was meant so that you can decide to use Log4Cxx. It's not a good idea to have it enabled by default, since on many platforms Log4Cxx can be very complicated to install (because of its dependencies).

**Comment by merlimat** [comment]
just do `cmake . -DUSE_LOG4CXX=ON`

**Comment by lbenc135** [comment]
@merlimat I see, thanks for the explanation. Does that mean that I can't use the default distribution (from PyPI for Python) and I have to build my own from source?

Should I maybe investigate other approaches to control logging? Maybe we can do something similar to what the Kafka client does - create a logger PyObject (to fix #4234). Or we can add a method/argument on the client for controlling the log level.

**Comment by merlimat** [comment]
@lbenc135 There was an attempt to expose the logger in Python, so that you could be able to plug a Python function there. It was in #6113, though it was later reverted because of some other issues in #6174. I think that change should be revived

**Comment by lbenc135** [comment]
@merlimat I revived the change here https://github.com/apache/pulsar/pull/7713 so please take a look if you can.

I reverted the CMake flag here and left only the refactoring fixes. Not sure why the CI failed though.

**Comment by Giaco9** [comment]
Hi everyone, any news on this issue? We would like to configure the python logger in version prior to 2.8. Would this pull request make it possible? Also, this pull request https://github.com/apache/pulsar/issues/7838 seems to be helpful, which one will be merged? Is any help needed?

Thank you

Giacomo

**Comment by tisonkun** [comment]
Closed as stale. The development of the C++ client has been permanently moved to https://github.com/apache/pulsar-client-cpp. If this is still relevant, please open an issue there.

**Pull request closed without merging**
