### PR TITLE
[cpp-build] Do not install libsnappy at each build

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

The docker image containing libsnappy was already pushed to docker hub so there's no need to install the package in the container at each build.

### CODE REVIEW

**Comment by merlimat** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests.

**Pull request merged**
