### PR TITLE
[fix][broker] Fix incorrect unack msk count when dup ack a message (#20990)

### PR DESCRIPTION
**Pull request by nodece**
### Motivation

Cherry-pick #20990 to branch-2.10

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by nodece** [comment]
This image works fine locally:
```
❯ docker pull quay.io/maksymbilenko/oracle-12c:master                         
master: Pulling from maksymbilenko/oracle-12c
8ba884070f61: Downloading [===========================>                       ]  40.77MB/75.4MB
ef9513b81046: Pulling fs layer 
6f1de349e202: Download complete 
5376ebfa0fa3: Waiting 
5f632c3633d2: Waiting 
3e74293031d2: Waiting
```

**Comment by nodece** [comment]
@lhotari Do you have any suggestions about `com.github.dockerjava.api.exception.DockerClientException: Could not pull image: failed to register layer: write /u01/app/oracle-product/12.2.0/SE/suptools/orachk/collections.dat: no space left on device`?

**Comment by lhotari** [comment]
> @lhotari Do you have any suggestions about `com.github.dockerjava.api.exception.DockerClientException: Could not pull image: failed to register layer: write /u01/app/oracle-product/12.2.0/SE/suptools/orachk/collections.dat: no space left on device`?

@nodece where did that happen?

**Review by Technoboy- — APPROVED** [review]

**Pull request merged**
