### PR TITLE
[Broker] Apply PolicyHierarchyValue to inactiveTopicPolicies

### PR DESCRIPTION
**Pull request by Jason918**
### Motivation

#12658 introduced `PolicyHierarchyValue` to cache broker/namespace/topic level policy value.

This pull request applied `PolicyHierarchyValue` to inactiveTopicPolicies, which can avoid some complex checking on updates and make it easier to understand.

### Modifications

Changed type of inactiveTopicPolicies to PolicyHierarchyValue.
- Init  with broker value.
- update namespace level value in onPoliciesUpdate(Policies)
- update topic level value in  onUpdate(TopicPolicies)

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is already covered by existing tests, such as pulsar-broker/src/test/java/org/apache/pulsar/broker/service/InactiveTopicDeleteTest.java

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 
  
- [x] `no-need-doc` 
Polish code, no documents needed.

### CODE REVIEW

**Comment by Shoothzj** [comment]
#12675 If that's your test failure reason, you should have a rebase or merge

**Comment by Jason918** [comment]
@codelipenghui @hangc0276 @linlinnn  PTAL.

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
