### PR TITLE
[improve][misc] Allow custom Netty DnsServerAddressStreamProviders

### PR DESCRIPTION
**Pull request by onobc**
### Motivation

ℹ️ _**NOTE:** Taken from the "Motivation" section of the reported issue https://github.com/apache/pulsar/issues/18644._

When running on a Java client on Mac M1 we receive the annoying `WARN` log statement:

> 22:07:00.494 [Test worker] WARN  org.apache.pulsar.shade.io.netty.resolver.dns.DnsServerAddressStreamProviders - Can not find org.apache.pulsar.shade.io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider in the classpath, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS.

This can lead to actual issues - but in most cases is just an annoyance. The suggested workaround is to add the M1-specific dependency [netty-resolver-dns-native-macos](
https://mvnrepository.com/artifact/io.netty/netty-resolver-dns-native-macos/4.1.85.Final) when running on M1 ([example](https://github.com/netty/netty/issues/11020#issuecomment-1193280582)). However, this does **NOT** work for Pulsar when using the `pulsar-client-all` shared jar because it attempts to load the M1 version w/ the shaded prefix (`org.apache.pulsar.shade.io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider` rather than `io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider`). 

### Modifications

Let's define a couple of terms (as used in this proposal) before explaining the modifications:

* **Shading** - the process of running the maven-shade-plugin to generate an uber jar w/ zero or more of its classes relocated from one package to another
* **Relocating** - the process of renaming a class from one package to another (aka relocating) in order to effectively "hide" it from any of the same classes already on the user's classpath.

The Netty DNS components w/ the following package name patterns:
- `io.netty.resolver.dns.macos.*`
- `io.netty.resolver.dns.*`
  
are excluded from _relocation_ during _shading_ in the following modules:
- `pulsar-client-shaded`
- `pulsar-admin-client-shaded`
- `pulsar-client-all`

They are **still included in the uber jar** but are **not relocated** to a "shaded" prefix package name. 

The result is that the suggested workaround mentioned above is now possible - the M1 specific dependency can be added and proper DNS resolution can take place. 

ℹ️ _**NOTE:** I attempted to only shade the `io.netty.resolver.dns.macos.*` package but that ultimately failed at runtime because the `DnsServerAddressStreamProviders` casts the impl to a `DnsServerAddressStreamProvider` (the shaded one if it too has been shaded). Therefore I had to also exclude `io.netty.resolver.dns.*` to make it work._ 

### Caveat
A negative aspect of this solution is that the `io.netty.resolver.dns**` packages are not relocated (shaded) in the resulting jar. If the user has a conflicting version of the Netty DNS lib(s) then they will need to exclude the non-shaded Netty DNS lib from the "shaded" Pulsar jar. IOW - one of the primary purposes of relocation/shading is no longer in play for the Netty DNS libs.  That being said, some other libs are already being excluded during the shading process - this is not a first. 

### Verifying this change
- [ ] Make sure that the change passes the CI checks.

This change added no tests.

### Documentation

ℹ️  _**NOTE:** I think we should document this exclusion somewhere. Maybe something like what is stated for the [Bouncycastle jars](https://github.com/apache/pulsar/blob/b579bb845b28c1404b75a76c44cc8beb74b2fcc3/site2/website/versioned_docs/version-2.10.x/security-bouncy-castle.md?plain=1#L105) could be added to the [client-libraries-java.md](https://github.com/apache/pulsar/blob/master/site2/website/versioned_docs/version-2.10.x/client-libraries-java.md#installation). Wdyt? Otherwise, the checklist below is accurate._

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository
PR in forked repository: https://github.com/onobc/pulsar/pull/2

### CODE REVIEW

**Comment by onobc** [comment]
I am not sure if `misc` is the proper `scope` for this one. It does have `build` work and can be roughly related to `ci` but not 100% where it should go.

**Comment by onobc** [comment]
Based on my note in the "**Documentation**" section above, I played around w/ the client libraries doc to see how it looked / fit in. The new content is everything in the "NOTE" section underneath the already existing "TIP" section. 

Screen Shot 2022-11-27 at 20 32 49

**Review by codelipenghui — COMMENTED** [review]
@onobc Have you tried if the change works?

I don't have a M1 Mac. IMO, we should add [netty-resolver-dns-native-macos](https://mvnrepository.com/artifact/io.netty/netty-resolver-dns-native-macos/4.1.85.Final) to the Pulsar Client dependencies(not your project dependencies) due to Pulsar will shade all the netty libs when building the client shaded jar.

**Comment by onobc** [comment]
Hi @codelipenghui 

> @onobc Have you tried if the change works

Yes, I have verified that when I use the `2.11.0-SNAPSHOT` shaded lib (built locally) and include the `netty-resolver-dns-native-macos` in my app the WARN goes away. When I remove the `netty-resolver-dns-native-macos` lib the WARN comes back. 

> IMO, we should add [netty-resolver-dns-native-macos](https://mvnrepository.com/artifact/io.netty/netty-resolver-dns-native-macos/4.1.85.Final) to the Pulsar Client dependencies(not your project dependencies) due to Pulsar will shade all the netty libs when building the client shaded jar. 

This is a good point and a good thing for me to try. I did not pursue this path originally as I did not think that would work as the Mac DNS provider would always be on the classpath. However, I believe that Netty uses the os and arch to figure out which provider to actually load. IOW - only when you are running on M1 would this DNS provider actually be used. I will verify that is in fact true and then try to include it in client deps and shade it. That would get rid of the partial shading as well as prevent users from having to add this manually themselves. I should be able to take a look w/in the next 24hrs.

**Comment by lhotari** [comment]
> However, this does NOT work for Pulsar when using the pulsar-client-all shared jar because it attempts to load the M1 version w/ the shaded prefix (org.apache.pulsar.shade.io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider rather than io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider).

In Pulsar, there's a custom solution to deal with relocating native Netty library files. There are scripts https://github.com/apache/pulsar/blob/master/src/rename-netty-native-libs.sh (bash) and https://github.com/apache/pulsar/blob/master/src/rename-netty-native-libs.cmd (powershell, when building on windows). 

These scripts are used in pulsar-client-all/pom.xml and pulsar-client-shaded/pom.xml .
https://github.com/apache/pulsar/blob/8b404d4ce14a1a10bd7569826754800f2cab5b0b/pulsar-client-all/pom.xml#L378-L399

Perhaps we could modify rename-netty-native-libs.sh and rename-netty-native-libs.cmd to also handle netty-resolver-dns-native-macos ?

**Comment by onobc** [comment]
> > However, this does NOT work for Pulsar when using the pulsar-client-all shared jar because it attempts to load the M1 version w/ the shaded prefix (org.apache.pulsar.shade.io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider rather than io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider).
> 
> In Pulsar, there's a custom solution to deal with relocating native Netty library files. There are scripts https://github.com/apache/pulsar/blob/master/src/rename-netty-native-libs.sh (bash) and https://github.com/apache/pulsar/blob/master/src/rename-netty-native-libs.cmd (powershell, when building on windows).
> 
> These scripts are used in pulsar-client-all/pom.xml and pulsar-client-shaded/pom.xml .
> 
> https://github.com/apache/pulsar/blob/8b404d4ce14a1a10bd7569826754800f2cab5b0b/pulsar-client-all/pom.xml#L378-L399
> 
> Perhaps we could modify rename-netty-native-libs.sh and rename-netty-native-libs.cmd to also handle netty-resolver-dns-native-macos ?

Thanks for that info @lhotari - I definitely missed that detail. I will take a look at this. It will also blend well w/ @codelipenghui suggestion of shading the native mac os lib rather than unshading the whole dns package.

**Comment by onobc** [comment]
The latest commit does the following: 
- includes the native Mac DNS resolver libs in client deps
- these included libs get automatically shaded 
- updates the "rename.." script to include the newly added libs

This works on my sample app as well. The WARN is gone and I do **not** have the Mac DNS deps on my sample app any longer. 

@codelipenghui @lhotari PTAL

**Review by lhotari — APPROVED** [review]
LGTM. Thanks for the contribution!

**Review by michaeljmarshall — APPROVED** [review]
LGTM, thanks for your contribution @onobc!

@lhotari - I didn't know we packaged these native libraries this way, so I looked into an existing jar to see what was in it. It looks like there are native files that are not being relocated. For example, in `pulsar-client-all-2.10.2.jar`, I see that some of the files are missing the `org_apache_pulsar_shade_` string. Below is a list of the files under `META-INF/native/`. Should we relocate those files as well?

```
META-INF/native/liborg_apache_pulsar_shade_netty_tcnative_linux_x86_64.so
META-INF/native/libnetty_tcnative_osx_aarch_64.jnilib
META-INF/native/liborg_apache_pulsar_shade_netty_transport_native_epoll_x86_64.so
META-INF/native/include/
META-INF/native/include/netty_unix_jni.h
META-INF/native/include/netty_jni_util.h
META-INF/native/include/netty_unix_limits.h
META-INF/native/include/netty_unix_util.h
META-INF/native/include/netty_unix_filedescriptor.h
META-INF/native/include/netty_unix_errors.h
META-INF/native/include/netty_unix_buffer.h
META-INF/native/include/netty_unix.h
META-INF/native/include/netty_unix_socket.h
META-INF/native/netty_tcnative_windows_x86_64.dll
META-INF/native/lib/
META-INF/native/lib/libnetty-unix-common.a
META-INF/native/libnetty_tcnative_linux_aarch_64.so
META-INF/native/libnetty_tcnative_osx_x86_64.jnilib
```

**Comment by merlimat** [comment]
>  Should we relocate those files as well?

@michaeljmarshall Yes, otherwise the native libs are not loaded by Netty when using it in shaded mode

**Comment by tisonkun** [comment]
CI failed at:

```
  /home/runner/work/_temp/_github_home/.local/bin/gh-actions-artifact-client.js:9924
        throw new Error(`Unable to find an artifact with the name: ${name}`)
              ^
  
  Error: Unable to find an artifact with the name: pulsar-maven-repository-binaries.tar.zst
      at ExtendedDownloadHttpClient.downloadStream (/home/runner/work/_temp/_github_home/.local/bin/gh-actions-artifact-client.js:9924:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
  0.00 B 0:00:00 [0.00 B/s]
  zstd: /*stdin*\: unexpected end of file 
  tar: Child returned status 1
  tar: Error is not recoverable: exiting now
```

I don't know whether it's relevant to this new packing change, and it seems simply rerun hold the failure. I'm going to merge the latest commits and push for this PR.

**Comment by tisonkun** [comment]
CI failed on:

```
netty-resolver-dns-classes-macos-4.1.77.Final.jar unaccounted for in trino/LICENSE
netty-resolver-dns-native-macos-4.1.77.Final-osx-aarch_64.jar unaccounted for in trino/LICENSE
netty-resolver-dns-native-macos-4.1.77.Final-osx-x86_64.jar unaccounted for in trino/LICENSE
```

LICENSE need to be updated.

**Comment by tisonkun** [comment]
Merging...

Thanks for your contribution!

**Comment by onobc** [comment]
Yw @tisonkun . Sorry for the inconvenience on the distro license. I updated it in the other file https://github.com/apache/pulsar/pull/18646/commits/699674f9912845883d91bc75ee34a11f33fb9574 but missed this one. TIL.

**Comment by tisonkun** [comment]
@onobc never mind. It's not quite obvious when you first meet it :)

**Comment by onobc** [comment]
I don't see this one in the [3.0.0 Release notes](https://github.com/apache/pulsar/releases/tag/v3.0.0) but I do see the changes in the [branch-3.0](https://github.com/apache/pulsar/blob/7636e8989f4d3fc24fce69a356d54e1c550945ed/pulsar-client/pom.xml#L83). Really I just want to make sure the fix is in 3.0.0 and there is not something else I am missing. 

Thanks

**Comment by tisonkun** [comment]
ditto @RobertIndie https://github.com/apache/pulsar/pull/20106#issuecomment-1532419289

**Comment by onobc** [comment]
I have verified that the original message is not reported when running on Mac M1 w/ Pulsar 3.0.0.

**Pull request merged**
