### PR TITLE
Use StandardCharsets.UTF_8 for converting String to bytes

### PR DESCRIPTION
**Pull request by liketic**
Use StandardCharsets.UTF_8 for converting String to bytes to avoid potential encoding error.

### CODE REVIEW

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by liketic** [comment]
run java8 tests
run integration tests

**Comment by liketic** [comment]
run java8 tests
run integration tests

**Comment by liketic** [comment]
run java8 tests
run integration tests

**Comment by liketic** [comment]
run java8 tests
run integration tests

**Comment by sijie** [comment]
run java8 tests

**Pull request merged**
