### PR TITLE
[Improvement] Apply maven modernizer to remaining modules.

### PR DESCRIPTION
**Pull request by MarvinCai**
Master Issue: https://github.com/apache/pulsar/issues/12271

### Modifications
Applied to following modeules:
pulsar-config-validation
pulsar-functions
pulsar-metadata
pulsar-package-management

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Comment by MarvinCai** [comment]
@tisonkun please help take a look, these are remaining modules except pulsar-broker

**Review by tisonkun — APPROVED** [review]
LGTM. Thanks!

**Comment by tisonkun** [comment]
Out of curiosity, does modernizer plugin provides a goal to auto fix like spotless can `apply` format changes?

**Comment by MarvinCai** [comment]
from the readme it doesn't seems modernizer has such ability

**Review by hangc0276 — APPROVED** [review]

**Pull request merged**
