### PR TITLE
[improve][client] Make seek wait for reconnect

### PR DESCRIPTION
**Pull request by nodece**
### Motivation

When doing seek operation, the client needs to seed a seek command to the broker. When one seeks is successful, the broker disconnects the client, and then the client reconnects and resubscribes to the broker based on the seek position.

Right now, the consumer responds to the caller after sending a seek command succeeds, this should be incorrect behavior. 
The right behavior should be to wait for reconnect and resubscribe, then respond to the caller.

### Modifications

Based on the global `CompletableFuture` and `seekMessageId` check the seek operation to wait for reconnect and resubscribe.

When reconnecting is done, make the `CompletableFuture` to complete, when resubscribing is done, cleanup the `seekMessageId`.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/nodece/pulsar/pull/9

### CODE REVIEW

**Comment by lhotari** [comment]
@nodece Do you think that this PR addresses #10671 ?

**Comment by nodece** [comment]
> @nodece Do you think that this PR addresses #10671 ?

I think this PR can fix race condition of seeking.

**Comment by lhotari** [comment]
is there any relationship to #16757?

**Comment by nodece** [comment]
> is there any relationship to #16757?

Right, but this PR fixes some issues on the client side.

**Review by congbobo184 — COMMENTED** [review]
I think we should reconsider seek. This PR only solves some problems, but it does not solve all seek and reconnect concurrency problems.

**Comment by nodece** [comment]
> I think we should reconsider seek. This PR only solves some problems, but it does not solve all seek and reconnect concurrency problems.

Do you have any suggestions?

**Comment by congbobo184** [comment]
I have no idea about that. [PIP-194] https://lists.apache.org/thread/97o9t4ltkds5pfq41l9xbbd31t41qm8w discuss how to solve this problem.

**Comment by nodece** [comment]
> I have no idea about that. [PIP-194] https://lists.apache.org/thread/97o9t4ltkds5pfq41l9xbbd31t41qm8w discuss how to solve this problem.

I think this is a different issue, I just fix the concurrency problems of seeking on the client side.

**Comment by nodece** [comment]
No reviewer, so close this PR.

**Pull request closed without merging**
