### PR TITLE
[improve][test] Improve AdminApiTest to reduce the execution time

### PR DESCRIPTION
**Pull request by coderzc**
Fixes: 
* https://github.com/apache/pulsar/issues/17640

### Modifications

Only execution once `setup`/`clean` and clean `tenants`/`namespaces`/`producer`/`consumer` after the end of each test execution.

Execution time after improve test:
```
Tests run: 83, Failures: 0, Errors: 0, Skipped: 4, Time elapsed: 404.325 s - in org.apache.pulsar.broker.admin.AdminApiTest
```

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [x] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### Matching PR in forked repository

PR in forked repository: https://github.com/coderzc/pulsar/pull/10

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@coderzc Please help check the failed test of Broker Group 3, it looks like related to this chnage

**Comment by coderzc** [comment]
> @coderzc Please help check the failed test of Broker Group 3, it looks like related to this change

`Admin2Test` have two timeout test, this pr change is `AdminTest`, I try again once.

**Review by poorbarcode — APPROVED** [review]

**Pull request merged**
