### PR TITLE
[Branch-2.7] On multi-topic consumer, we shouldn't keep checking the partitioned metadata 

### PR DESCRIPTION
**Pull request by Technoboy-**
Pick #10708  to branch 2.7.

### CODE REVIEW

**Comment by Technoboy-** [comment]
ping @codelipenghui .

**Comment by codelipenghui** [comment]
@Technoboy- Please check the compile issue

**Review by codelipenghui — APPROVED** [review]

**Comment by Anonymitaet** [comment]
@Technoboy- seems that it does not affect docs?

**Comment by Technoboy-** [comment]
> @Technoboy- seems that it does not affect docs?

Yes, no need to update docs.

**Pull request merged**
