### PR TITLE
Update full-width typo in schema-understand.md

### PR DESCRIPTION
**Pull request by vruc**
fix full-width “” to half-width "

### Motivation

Some typo exists in schema-understand.md

### Modifications

fix full-width “” to half-width "

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:
no

### Documentation
just fix typo in schema-understand.md

### CODE REVIEW

**Comment by merlimat** [comment]
run java8 tests
run integration tests

**Comment by codelipenghui** [comment]
run java8 tests
run integration tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Pull request merged**
