### PR TITLE
[Tests] Enable Schema Integration Tests

### PR DESCRIPTION
**Pull request by sijie**
*Motivation*

Some of the schema integration tests are not running in CI.

*Modifications*

- Provide suite xml files to enable schema tests in CI
- Fix some errors in existing schema integration tests

### CODE REVIEW

**Comment by sijie** [comment]
@shiv4289 FYI. There is some minor issues in existing schema autoupdate policy test. But I still can't reproduce the issue you mentioned in the slack channel :(

**Comment by shiv4289** [comment]
> @shiv4289 FYI. There is some minor issues in existing schema autoupdate policy test. But I still can't reproduce the issue you mentioned in the slack channel :(

@sijie  I am using 2.3.1 java client. And I can reproduce simply with this:

    public static void main(String[] args) throws PulsarClientException {
        try {
            client = PulsarClient.builder()
                    .serviceUrl(PULSAR_BROKER_URL)
                    .build();
            
            producer = client.newProducer(AvroSchema.of(SampleCreated.class))
                    .topic(PULSAR_TOPIC)
                    .create();
        } catch (PulsarClientException e) {
            e.printStackTrace();
        } finally {
            producer.close();
            client.close();
        }
    }

The schema is AVRO and  is part of the POJO SampleCreated.class

1. Run the code above with an avro schema.
2. Delete a field in the avro schema and use new POJO to create producer.

The producer create will crash with 

> org.apache.pulsar.client.api.PulsarClientException$IncompatibleSchemaException: org.apache.pulsar.broker.service.schema.IncompatibleSchemaException: Incompatible schema used

Please let me know if you need any help in reproducing the issue with the java client.

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run integration tests

**Comment by codelipenghui** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by codelipenghui** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by jiazhai** [comment]
run integration tests

**Comment by shiv4289** [comment]
@sijie  It seems the integration tests failures are related to changes here, Please check

> 2019-05-20\T\03:15:18.163 [ERROR] pulsar-test-suite(org.apache.pulsar.tests.integration.cli.SchemaUpdateStrategyTest)  Time elapsed: 4.514 s  <<< FAILURE!
> org.apache.pulsar.tests.integration.docker.ContainerExecException: /pulsar/bin/pulsar-admin namespaces create -c SchemaUpdateStrategyTest-vzosr public/none-p-v2 failed on 230cf2b737d28c7a1150106729316506f08fb671eac3e443075f7386b8c78673 with error code 1
> 	at org.apache.pulsar.tests.integration.utils.DockerUtils.runCommand(DockerUtils.java:250)
> 	at org.apache.pulsar.tests.integration.containers.ChaosContainer.execCmd(ChaosContainer.java:116)
> 	at org.apache.pulsar.tests.integration.topologies.PulsarCluster.runCommandOnAnyBrokerWithScript(PulsarCluster.java:497)
> 	at org.apache.pulsar.tests.integration.topologies.PulsarCluster.runAdminCommandOnAnyBroker(PulsarCluster.java:485)
> 	at org.apache.pulsar.tests.integration.cli.SchemaUpdateStrategyTest.testNoneV2(SchemaUpdateStrategyTest.java:344)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
> 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
> 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)


> 2019-05-20\T\03:15:18.163 [ERROR] pulsar-test-suite(org.apache.pulsar.tests.integration.schema.SchemaTest)  Time elapsed: 0.212 s  <<< FAILURE!
> org.apache.pulsar.client.api.PulsarClientException$InvalidConfigurationException: Subscription name must be set on the consumer builder
> 	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribeAsync(ConsumerBuilderImpl.java:111)
> 	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribe(ConsumerBuilderImpl.java:89)
> 	at org.apache.pulsar.tests.integration.schema.SchemaTest.testAvroLogicalType(SchemaTest.java:207)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
> 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
> 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by codelipenghui** [comment]
@sijie Can we close this PR now? we already enable schema integration tests in the master branch

**Pull request closed without merging**
