### PR TITLE
[cleanup] [broker] Remove useless code to avoid confusion in OpReadEntry#checkReadCompletion

### LINKED ISSUE #15103: Remove useless code to reduce confusion
**Describe the bug**
https://github.com/apache/pulsar/blob/a242f03f69791fcfa1934b6cab20689393228381/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpReadEntry.java#L136-L162

line_141 - line_143.
The code is useless, it looks like half completed code which forget to be remove. 

line_147 will recalculate readPosition.

### PR DESCRIPTION
**Pull request by horizonzy**
Fixes #15103

### Motivation

Remove useless code.

- [x] `no-need-doc` 
(Please explain why)

### CODE REVIEW

**Review by Jason918 — APPROVED** [review]
LGTM

**Comment by HQebupt** [comment]
LGTM

**Review by HQebupt — APPROVED** [review]

**Review by mattisonchao — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Comment by mattisonchao** [comment]
This PR need to cherry-pick to another branch, because when invoke `cursor.ledger.startReadOperationOnLedger(nextReadPosition, OpReadEntry.this);` twice may cause NPE when ledger id equals `null` and then failed this `OpAddEntry` and recycle it.

@codelipenghui  @horizonzy Could you help to confirm it?

**Comment by horizonzy** [comment]
Sure



发自我的iPhone


------------------ Original ------------------
From: Qiang Zhao ***@***.***&gt;
Date: Sat,May 28,2022 8:46 AM
To: apache/pulsar ***@***.***&gt;
Cc: Yan Zhao ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [apache/pulsar] [cleanup] [broker] Remove useless code to avoidconfusion in OpReadEntry#checkReadCompletion (PR #15104)





 
This PR need to cherry-pick to another branch, because when invoke cursor.ledger.startReadOperationOnLedger(nextReadPosition, OpReadEntry.this); twice may cause NPE when ledger id equals null and then failed this OpAddEntry and recycle it.
 
@codelipenghui  @horizonzy Could you help to confirm it?

**Pull request merged**
