### PR TITLE
[Documentation] Fix reference configuration table formatting

### PR DESCRIPTION
**Pull request by michaeljmarshall**
This PR includes basic improvements to table formatting in the `reference-configuration.md` file. There were several issues:

1. Some rows were missing a pipe (`|`). This didn't affect rendering on the website.
2. Some rows had new line characters in them, which led to a single row rendering as two on the website.
3. Some rows were combined.

Only formatting is changed. No configuration content is changed.

Each of these errors are visible on the live docs right now: https://pulsar.apache.org/docs/en/reference-configuration/.

### CODE REVIEW

**Review by Anonymitaet — APPROVED** [review]

**Review by Jennifer88huang — APPROVED** [review]
@michaeljmarshall  thank you for fixing them

**Comment by Jennifer88huang** [comment]
@michaeljmarshall @eolivelli those configuration info comes from different conf files. I was wondering whether we could generate the configuration reference from those conf files automatically by using scripts, just as we generate the CLI and REST API on the pulsar website. Do you have any idea on it?

**Comment by michaeljmarshall** [comment]
@Jennifer88huang - I am not familiar with any methods to generate a reference from the `.conf` files. I'll keep this in mind though and try to look for options some time soon. It's a great idea to have this type of documentation generated to prevent manual errors.

**Comment by Jennifer88huang** [comment]
@michaeljmarshall thank you, hope we could find a good option soon.

**Pull request merged**
