### PR TITLE
[fix][client] Fix update response body text

### PR DESCRIPTION
**Pull request by tuteng**
Fixes #xyz

Master Issue: #xyz

### Motivation

When using pulsar-admin and encountering an exception, first check the body, then check the http text

### Modifications

* Update http response body check

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/AmateurEvents/pulsar/pull/31

### CODE REVIEW

**Review by mattisonchao — APPROVED** [review]
LGTM, We need to see if we break unit test.

**Comment by Jason918** [comment]
> When using pulsar-admin and encountering an exception, first check the body, then check the http text

Can you give an actual case this PR is solving?

**Comment by tuteng** [comment]
> > When using pulsar-admin and encountering an exception, first check the body, then check the http text
> 
> Can you give an actual case this PR is solving?

https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/web/ExceptionHandler.java#L46 

This needs an interceptor and then throws an exception with a custom message, using pulsar-admin to execute the corresponding command, which never gets the custom message @Jason918

**Comment by mattisonchao** [comment]
Oops. Could you help to take a look? I am not sure if it is a sensitive breaking change for users.

@codelipenghui @eolivelli  @Technoboy-  @Jason918

**Pull request merged**
