### PR TITLE
Add sample docker-compose file with pulsar standalone

### PR DESCRIPTION
**Pull request by aahmed-se**
Add sample compose file for experimentation purposes.

### CODE REVIEW

**Comment by sijie** [comment]
please fix license header

**Comment by aahmed-se** [comment]
Add license and packaging

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
Can you add a README at `docker-compose/standalone-dashboard`? so when people use this file, they have instructions and how to see dashboard as well.

**Comment by aahmed-se** [comment]
added readme

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Pull request merged**
