### PR TITLE
Allow to build Pulsar on JDK14+

### PR DESCRIPTION
**Pull request by eolivelli**
### Motivation
Currently Pulsar does not build on JDK14

### Modifications

- update Maven Assembly plugin
- use explicit import for Record class (prevent clash with java.lang.Record)
- move maven-git-commit-id plugin execution only inside Pulsar Common (in order to speed up the build)

### Verifying this change

This change is already covered by existing tests

### CODE REVIEW

**Comment by eolivelli** [comment]
This change is not intended to make tests pass, only to allow a full clean build.
Fixing tests will be a follow up work

**Comment by eolivelli** [comment]
rerun failure tests

**Comment by eolivelli** [comment]
thank you @rdhabalia

**Review by codelipenghui — APPROVED** [review]

**Review by merlimat — APPROVED** [review]

**Review by jiazhai — APPROVED** [review]

**Comment by eolivelli** [comment]
Is it normal this series of failures ?

**Comment by eolivelli** [comment]
The upgrade of plugins determined changes in the final output of the binaries.
I see license errors and probably also integration tests are related

**Comment by eolivelli** [comment]
I cannot reproduce CI errors locally, opening a new PR #8360

**Pull request closed without merging**
