### PR TITLE
Allow user to configure proxy as reverse HTTP proxy

### PR DESCRIPTION
**Pull request by ivankelly**
Users normally want to expose as few endpoints as possible. This patch
enables configuring the pulsar proxy as a review HTTP proxy, so that
it can be used as a single endpoint for all pulsar and even non-pulsar
HTTP services.

The reverse proxy uses jetty's built-in implementation.

It is configured in proxy.conf, in the form

```
httpReverseProxy.NAME.path = '/path-on-pulsar-proxy-endpoint'
httpReverseProxy.NAME.proxyTo = 'http://internal-server/some-app'
```

where NAME is any user-defined string. Multiple paths can be
configured this way.

### CODE REVIEW

**Comment by ivankelly** [comment]
cc @cckellogg

**Comment by merlimat** [comment]
run java8 tests
run integration tests

**Comment by merlimat** [comment]
@ivankelly There was a failure in one of the new tests: 

```
java.lang.AssertionError: expected [200] but found [504]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:652)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at org.apache.pulsar.proxy.server.ProxyIsAHttpProxyTest.testMultipleRedirect(ProxyIsAHttpProxyTest.java:167)
```

**Comment by ivankelly** [comment]
rerun integration tests

**Comment by merlimat** [comment]
@ivankelly One more failure here: https://builds.apache.org/job/pulsar_precommit_java8/4349/testReport/junit/org.apache.pulsar.proxy.server/ProxyIsAHttpProxyTest/

**Comment by ivankelly** [comment]
looking into it

**Comment by ivankelly** [comment]
@merlimat Looks like a legit issue. Seems to only repro if you have 24 cores though. There's a race somewhere, and I suspect it's in jetty itself

**Comment by merlimat** [comment]
Ouch, maybe we can try to upgrade Jetty to latest stable too.

**Comment by ivankelly** [comment]
I have a reliable repro, so will try the upgrade. I suspect it could be related to 
https://github.com/eclipse/jetty.project/pull/2023

**Comment by ivankelly** [comment]
Created https://github.com/eclipse/jetty.project/issues/3005. Moving to 9.4 series, which seems to fix it.

**Pull request merged**
