### PR TITLE
Pulsar Adapters: add download section (only source tarball)

### PR DESCRIPTION
**Pull request by eolivelli**
This patch adds to the Download page the link to the Apache Pulsar Adapter 2.8.0 source distribution.
There is not "binary" distribution for Adapters, the artifacts (jar files) are only on Maven Central.

### CODE REVIEW

**Comment by eolivelli** [comment]
This is how the page will look like

Screenshot 2021-07-07 at 11 58 05

**Comment by eolivelli** [comment]
In my opinion we should add to the website the documentation about how to use the various Pulsar Adapters, or at least the most important ones.
But this is a separate work

**Review by tuteng — APPROVED** [review]

**Review by merlimat — APPROVED** [review]

**Comment by Anonymitaet** [comment]
@eolivelli thanks for your contribution.
We have docs for adapters: https://pulsar.apache.org/docs/en/adaptors-kafka/

For the updates on the `adapter` chapter:

1. I plan to add [Pulsar SQL doc](https://docs.google.com/document/d/1jczvzh-eVL7wczpIKNPxY2oXK9JH9kr022stkkblUbI/edit) to the `adapter` chapter after the Pulsar connector is contributed to Trino (WIP, code: https://github.com/trinodb/trino/pull/8020, doc: https://github.com/trinodb/trino/pull/8469)
image

2. Are there other improvements that we need to make on adapter docs?

**Comment by eolivelli** [comment]
@Anonymitaet very good

I believe that the other "adapters" module that is worth to add some docs is the Log4J2 appender
https://github.com/apache/pulsar-adapters/tree/master/pulsar-log4j2-appender

Maybe we could add a page with a minimal doc about how to start using it

**Comment by Anonymitaet** [comment]
@eolivelli thanks. 
Seems that we do not have any tech inputs for `Log4J2 appended`, could you please provide them? Then I would like to help review, thanks.

**Pull request merged**
