### PR TITLE
Replace orElse with orElseGet to avoid calling too many times.

### PR DESCRIPTION
**Pull request by Technoboy-**
### Motivation
Use orElseGet when `orElse(xxx)` is not a raw value, otherwise it will calling the value every time.

### Documentation
This is an enhancement, no need to update doc.

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
Lgtm

**Comment by eolivelli** [comment]
The patch looks good.

I am not sure we achieve some visible improvement because in anyway you are allocating an instance of the lambda expression. Probably the overhead of instantiating such instance will be lower.

I am +1

**Comment by merlimat** [comment]
> I am not sure we achieve some visible improvement because in anyway you are allocating an instance of the lambda expression. Probably the overhead of instantiating such instance will be lower.

If the lambda is not capturing any reference, like `TopicPolicies::new` it will not need an allocation.

**Comment by eolivelli** [comment]
I am not sure if it really happens.
I would be curious to verify if it really the JVM does it.
But I not time to dig into it

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
