### PR TITLE
fix bug: https://github.com/apache/pulsar/issues/7706

### PR DESCRIPTION
**Pull request by xuesong172500**
Fixes https://github.com/apache/pulsar/issues/7706

### Motivation

Pulsar-Proxy/Pulsar-Discovery-Service No active broker is available

### Modifications

Change zookeeper getValue interface

### CODE REVIEW

**Comment by massakam** [comment]
Changes in https://github.com/apache/pulsar/pull/7690 seem to be reverted. Is this intentional?

**Comment by xuesong172500** [comment]
Yes, I submitted the code one day later than the latest code in the master branch. I passed the test on the old code, but did not merge and retest the latest code of the master branch.




daxia_xue@126.com
 
From: Masahiro Sakamoto
Date: 2020-08-12 10:57
To: apache/pulsar
CC: xuesong172500; Assign
Subject: Re: [apache/pulsar] fix bug: https://github.com/apache/pulsar/issues/7706 (#7774)
Changes in #7690 seem to be reverted. Is this intentional?

**Comment by massakam** [comment]
If we revert #7690 changes, the deadlock issue will reappear, so we should not it. Can the issue of #7706 be reproduced on the master branch? If so, could you fix the code in the master branch?

**Comment by xuesong172500** [comment]
Yes, I will fork the master branch again and submit a new pull request.



daxia_xue@126.com
 
From: Masahiro Sakamoto
Date: 2020-08-12 13:12
To: apache/pulsar
CC: xuesong172500; Assign
Subject: Re: [apache/pulsar] fix bug: https://github.com/apache/pulsar/issues/7706 (#7774)
If we revert #7690 changes, the deadlock issue will reappear, so we should not it. Can the issue of #7706 be reproduced on the master branch? If so, could you fix the code in the master branch?

**Comment by xuesong172500** [comment]
I tested the code of PR #7690 and solved the issues #7706. The PR #7774 submitted by me can also solve the problems of pulsar proxy and pulsar discovery service modules, so please decide which PR to use.

**Comment by massakam** [comment]
If #7690 has already solved the issue, I will close this PR.

**Pull request closed without merging**
