### PR TITLE
[improve][broker] add limitStatsLogging configuration when enable bookkeeperClientExposeStatsToPrometheus

### PR DESCRIPTION
**Pull request by TakaHiR07**
### Motivation

This closes https://github.com/apache/pulsar/issues/16732.

### Modifications

Add bookkeeperClientLimitStatsLogging configuration for broker.conf

After enable bookkeeperClientExposeStatsToPrometheus and bookkeeperClientLimitStatsLogging, there are no more per_channel_bookie_client metrics in bookie client stats.

wecom-temp-6ba3feaee4543aeb5bbcba3c26f51956
wecom-temp-9ba30e4d92209f2120c2850ac1b6d120

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): no
  - The public API: no
  - The schema: no
  - The default values of configurations: **yes**
  - The wire protocol: no
  - The rest endpoints: no
  - The admin cli options: no
  - Anything that affects deployment: no

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [x] `doc`

### CODE REVIEW

**Review by codelipenghui — COMMENTED** [review]
Could you please add an unit test to cover the new configuration? Make sure the default value is false and change the value is work property.

**Comment by TakaHiR07** [comment]
> Could you please add an unit test to cover the new configuration? Make sure the default value is false and change the value is work property.

@codelipenghui I add an unit test and doc of this configuration. Please take a look

**Review by tisonkun — APPROVED** [review]
LGTM.

The config document will be updated automatically since we're now generating from the code.

**Review by zymap — APPROVED** [review]
LGTM

**Comment by tisonkun** [comment]
Merging...

**Pull request merged**
