### PR TITLE
[Authenticate] fix debug log authenticate role error

### PR DESCRIPTION
**Pull request by liudezhi2098**
### Motivation

authState.getAuthRole() will throws exception.
```
DEBUG org.apache.pulsar.broker.authentication.PulsarSaslServer - serviceHostname is 'chinaunion-2.internal.cloudapp.net', servicePrincipalName is 'broker', SASL mechanism(mech) is 'GSSAPI'.
 [pulsar-io-4-2] ERROR org.apache.pulsar.broker.service.ServerCnx - [/*.*.*.*:48378] Error trying to authenticate: operation=connect, principal=null
java.lang.IllegalStateException: Authentication incomplete
        at com.sun.security.sasl.gsskerb.GssKrb5Server.getAuthorizationID(GssKrb5Server.java:343) ~[?:1.8.0_322]
        at org.apache.pulsar.broker.authentication.PulsarSaslServer.getAuthorizationID(PulsarSaslServer.java:139) ~[org.apache.pulsar-pulsar-broker-auth-sasl-2.9.1.jar:2.9.2-SNAPSHOT]
        at org.apache.pulsar.broker.authentication.SaslAuthenticationDataSource.getAuthorizationID(SaslAuthenticationDataSource.java:54) ~[org.apache.pulsar-pulsar-broker-auth-sasl-2.9.1.jar:2.9.2-SNAPSHOT]
        at org.apache.pulsar.broker.authentication.SaslAuthenticationState.getAuthRole(SaslAuthenticationState.java:51) ~[org.apache.pulsar-pulsar-broker-auth-sasl-2.9.1.jar:2.9.2-SNAPSHOT]
        at org.apache.pulsar.broker.authentication.AuthenticationProviderList$AuthenticationListState.getAuthRole(AuthenticationProviderList.java:88) ~[pulsar-broker-common.jar:2.9.2-SNAPSHOT]
        at org.apache.pulsar.broker.service.ServerCnx.handleConnect(ServerCnx.java:814) [pulsar-broker.jar:2.9.2-SNAPSHOT]
        at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:167) [pulsar-common.jar:2.9.2-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Final]
```

### Documentation

  
- [x] `no-need-doc`

### CODE REVIEW

**Review by nodece — APPROVED** [review]

**Comment by liudezhi2098** [comment]
> @liudezhi2098 This CI is passed, you don't need to rerun this CI.

OK

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
