### PR TITLE
docs: add developers-landing page to sidebars

### PR DESCRIPTION
**Pull request by tisonkun**
This is a followup to #17284.

cc @DaveDuggins @Anonymitaet @momo-jun @urfreespace 

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [ ] `doc-not-needed` 
(Please explain why)

- [x] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### Matching PR in forked repository

docs only change

### CODE REVIEW

**Comment by tisonkun** [comment]
Currently, this page is dangling:

image

**Comment by DaveDuggins** [comment]
Hi tison! This page does not require sidebar links. The landing pages I'll be creating PRs for over the next few days will not require a sidebar link. These pages serve only as a connection point between the content blocks on the main documentation page and the topics. No additional navigation is needed.

**Comment by tisonkun** [comment]
@DaveDuggins this patch doesn't add a new entry but reuse the "development" entry.

If we don't add it to the sidebars, how can users find the page? Only by entering the exact url? It seems unreasonable.

**Comment by tisonkun** [comment]
@DaveDuggins OK. I see the link from the original patch. Let me show you the result of this patch in preview later today.

**Comment by tisonkun** [comment]
cc @DaveDuggins 

Current:

https://user-images.githubusercontent.com/18818196/191638058-655aec16-0d91-4ef6-abaa-06a65ec50c91.mov

Preview with this patch:


https://user-images.githubusercontent.com/18818196/191638238-9e18bc4d-1995-4598-9fd7-4fbe70a69060.mov

**Comment by tisonkun** [comment]
ping @DaveDuggins @Anonymitaet @momo-jun @urfreespace for another turn.

**Review by momo-jun — APPROVED** [review]

**Comment by DaveDuggins** [comment]
> @DaveDuggins this patch doesn't add a new entry but reuse the "development" entry.
> 
> If we don't add it to the sidebars, how can users find the page? Only by entering the exact url? It seems unreasonable.

No, by clicking the appropriate topic box on the main documentation page. These landing pages only serve as a bridge to the related articles linked from the content blocks on the main doc page.

**Comment by tisonkun** [comment]
@DaveDuggins Yep. Please read the following comment. This change won't break existing things and as an improvement.

**Review by urfreespace — APPROVED** [review]

**Comment by tisonkun** [comment]
@DaveDuggins @momo-jun @urfreespace @Anonymitaet shall we merge this patch now?

**Pull request merged**
