### PR TITLE
[Minor] Fix method comment for class Topics

### PR DESCRIPTION
**Pull request by liketic**
Fix typo and incorrect description for class ```Topics```.

### CODE REVIEW

**Comment by liketic** [comment]
run java8 tests

**Comment by liketic** [comment]
run java8 tests

**Comment by sijie** [comment]
@liketic since you are touching this area, it might be good to fix all the javadoc warnings.

**Comment by liketic** [comment]
@sijie OK, I'll take a look.

**Comment by liketic** [comment]
run java8 tests

**Pull request merged**
