### PR TITLE
[chore][test] Check LineLength only for Java files

### PR DESCRIPTION
**Pull request by tisonkun**
When I prototyping #17062 I met the issue that a text file can contain properties very long and that's proper.

Instead of suppressing them file by file, I think the original purpose we turn on LineLength is for checking Java files. So I propose this change.

- [x] `doc-not-needed` 

cc @eolivelli @lhotari @Shoothzj @RobertIndie

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Review by RobertIndie — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
Lgtm

**Comment by tisonkun** [comment]
cc @eolivelli @codelipenghui @RobertIndie I hope this patch is ready for merge now.

**Pull request merged**
