### PR TITLE
[C++] Show bytes throughput for performance tests

### PR DESCRIPTION
**Pull request by BewareMyPower**
### Motivation

The send callback changed after #4811 but message size cannot be retrieved from `MessageId`, so the statistics of message bytes were lost.

### Modifications

- Format code in `examples` and `perf` directories;
- Add a parameter to send callback to record each message's bytes count;
- Enable round robin routing for partitioned topics.

### CODE REVIEW

**Comment by BewareMyPower** [comment]
@jiazhai It looks like a bug of CI tests? They both failed after 1m at `clean disk` step:

```
Run sudo swapoff /swapfile
swapoff: /swapfile: swapoff failed: No such file or directory
##[error]Process completed with exit code 255.
```

**Comment by merlimat** [comment]
@BewareMyPower it’s already fixed in master, rebase today pick it up

**Pull request merged**
