### PR TITLE
[FEATURE] support for resetting logger level in runtime

### PR DESCRIPTION
**Pull request by wuzhanpeng**
### Motivation
This PR supplements a useful feature that enable users to reset logger level in runtime. It is very meaningful for developers to dynamically adjust the log level in the production environment, especially in the case of tracing online problems and unable to restart the broker process.

### Modifications

- add an REST endpoint for resetting (/brokers/configuration/log4j/{logger}/{level})
- add a companion admin cmd under `broker` (bin/pulsar-admin brokers reset-logger-level)

### Verifying this change
This change added tests and can be verified as follows:

*(example:)*
  - *Run`bin/pulsar-admin brokers reset-logger-level --level debug --logger root` after broker start to check log level*
  - *Run`bin/pulsar-admin brokers reset-logger-level --level info --logger root` to restore*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): no
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no
  - `The rest endpoints: yes`
  - `The admin cli options: yes`
  - Anything that affects deployment: no

### Documentation

- [x] doc-required

### CODE REVIEW

**Comment by wuzhanpeng** [comment]
@eolivelli @codelipenghui @hangc0276 Can you help review ?

**Review by merlimat — CHANGES_REQUESTED** [review]
This will only work for log4j, although it might not be the used logger. 

I think we should rely on the logger library to do this kind of operations. Log4j2 has already the option to monitor the log configuration file and update the settings.

**Comment by wuzhanpeng** [comment]
> This will only work for log4j, although it might not be the used logger.
> 
> I think we should rely on the logger library to do this kind of operations. Log4j2 has already the option to monitor the log configuration file and update the settings.

Thanks for your suggestions! As far as I know, `slf4j-1.X` currently does not support dynamically modify the log level, but this feature is hopefully implemented in `2.X`(see [this issue](https://jira.qos.ch/browse/SLF4J-124)). In addition, log4j natively supports jmx so that we can use mbeans to remotely monitor and control loggers, but it only supports the loggers predefined in the configuration file. With that in mind, this PR is dedicated to allow all loggers to log at a dynamic level avoiding the operation of modifying the configuration file and then restarting.

**Comment by tisonkun** [comment]
Closed as stale, conflict, and no consensus. Please rebase and resubmit the patch if it's still relevant.

**Pull request closed without merging**
