### PR TITLE
[fix][client] add support to TableView to read encrypted messages

### LINKED ISSUE #19007: [Bug] TableView does not support reading from encrypted topics
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Pulsar 2.10.2

### Minimal reproduce step

- write messages into a compacted topic using a `Producer` that has a `CryptoKeyReader` configured
- try reading messages from the topic using a `TableView`

### What did you expect to see?

When constructing the `TableView` using a `TableViewBuilder` I would expect to have methods that allow me to specify a `CryptoKeyReader` and a `ConsumerCryptoFailureAction` much like on `ReaderBuilder`.

### What did you see instead?

No such methods and reading from the compacted topic using a `TableView` failed.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by rbarbey**
Fixes #19007

### Motivation

This PR adds support for a `TableView` to read encrypted messages from a topic.

### Modifications

Analogous to `ReaderBuilder`, I've added methods to `TableViewBuilder` that allow to specify a `CryptoKeyReader` and a `ConsumerCryptoFailureAction`. The respective values are stored in `TableViewConfigurationData` and forwarded to the `ReaderBuilder` instance inside `TableViewImpl` when the `Reader` is constructed.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:
  - Added unit tests for `TableViewImpl` and `TableViewBuilderImpl`
  - Extended integration test verifying that encrypted messages can be read inside a `TableView`

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [x] The public API

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

[PR in forked repository](https://github.com/rbarbey/pulsar/pull/1)

### CODE REVIEW

**Review by eolivelli — CHANGES_REQUESTED** [review]
Please add a test case

**Comment by rbarbey** [comment]
If you’re talking about unit tests I was planning to write some. Am 20.12.2022 um 15:08 schrieb Enrico Olivelli ***@***.***>:﻿
@eolivelli requested changes on this pull request.

Please add a test case

**Comment by labuladong** [comment]
> If you’re talking about unit tests

Yes, please add some tests to cover the new feature to make it easy to verify.

**Comment by rbarbey** [comment]
@eolivelli I've added unit tests for `TableViewImpl` and `TableViewBuilderImpl` (there weren't any before and I took heavy inspiration on similar tests relating to `Producer`s and `Consumer`s.

Then I found `TableViewImplTest` in the `pulsar-broker` module which is an integration and there I've added a test that actually shows that encrypted messages can be read inside `TableViewImpl`.

I've run the tests locally (using the Maven commands I found in the workflow YAML) and they were passing so they should pass here as well.

**Comment by BewareMyPower** [comment]
You should create a PR in your fork, the link you pasted is not a PR in your repo. See my PRs in my fork as example: https://github.com/BewareMyPower/pulsar/pulls

**Comment by rbarbey** [comment]
@BewareMyPower Thank you! I've created a [PR](https://github.com/rbarbey/pulsar/pull/1) in my fork and linked it in the original comment of this PR as well.

**Comment by BewareMyPower** [comment]
image

image

Please synchronize your master (there should be a sync button in your account). Otherwise the file changed might be different in the PR of your fork repo.

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by BewareMyPower** [comment]
Creating a matching PR is to trigger the CI in your own account to avoid unnecessary CI resource usages in the Apache repo. But I see no CI has run in your PR.

image


Here is an example of a correct matching PR that ran the CI.

image

**Comment by rbarbey** [comment]
Synced my fork. Will look into the missing CI runs later. As I mentioned, I ran tests etc locally on my machine before I pushed my commits so I don't expect any tests to fail.

**Comment by rbarbey** [comment]
@BewareMyPower I've activated the CI checks in my fork and they ran successfully now. Please let me know if there's anything else left to do from my side. Thank you!

**Review by BewareMyPower — APPROVED** [review]

**Pull request merged**
