### PR TITLE
[pulsar-io] pass client builder if no service url provided to debezium connector 

### PR DESCRIPTION
**Pull request by freeznet**
### Motivation

#11293 allows to passing client builder to debezium database history, but it still requires passing `database.history.pulsar.service.url` as well. With client builder, the `database.history.pulsar.service.url` is not been used anymore. 
This PR fixes the logic and only pass client builder with no `database.history.pulsar.service.url` provided. 

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 

- [ ] doc-required 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] no-need-doc 
  
 internal bug fix
  
- [ ] doc 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Comment by eolivelli** [comment]
@dlg99 please take a look

**Review by eolivelli — COMMENTED** [review]
should we update the integration tests ?

**Review by dlg99 — APPROVED** [review]

**Comment by freeznet** [comment]
@eolivelli sorry for the late reply, I have modified the integration tests, PTAL when you have time, thanks.

**Comment by freeznet** [comment]
@nlu90 please help to review this when you have time, thanks.

**Review by eolivelli — CHANGES_REQUESTED** [review]
We are doubling the number of Debezium tests. They are very heavyweight, we should not go this way.
I believe that we can simply add only one additional test case to test this change and leave the other tests unchanged

**Comment by eolivelli** [comment]
@nicoloboschi PTAL

**Review by nlu90 — COMMENTED** [review]
+1 for avoid doubling the test workload.

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by nlu90 — APPROVED** [review]
LGTM

**Comment by codelipenghui** [comment]
@freeznet Could you please create a PR for 2.8 and 2.9 directly? There is some conflict when cherry-picking into 2.8 and 2.9 branches.

**Comment by freeznet** [comment]
@codelipenghui added #14040 and #14041 to add this into 2.8 and 2.9.

**Comment by Anonymitaet** [comment]
This PR needs to update docs. And I've update docs in https://github.com/apache/pulsar-site/pull/605

**Pull request merged**
