### PR TITLE
Added more blog posts in the resources page

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

The articles list in the resources page was not updated in while. Added blog posts centered on Pulsar.

### CODE REVIEW

**Comment by jiazhai** [comment]
@merlimat 
How about also including these ones:
https://flink.apache.org/2019/05/03/pulsar-flink.html
https://debezium.io/blog/2019/05/23/tutorial-using-debezium-connectors-with-apache-pulsar/

**Comment by merlimat** [comment]
> How about also including these ones:

Yes, forgot about these. Adding now

**Comment by sijie** [comment]
run java8 tests
run cpp tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests
run cpp tests

**Pull request merged**
