### PR TITLE
[feature][connectors][PIP-193] Support Transform Function with LocalRunner

### PR DESCRIPTION
**Pull request by cbornet**
Master Issue: https://github.com/apache/pulsar/issues/16739

### Motivation

This adds support for Transform Function in LocalRunner

### Modifications

see below

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:
* Run testPulsarSinkWithFunction

### Does this pull request potentially affect one of the following parts:

no

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [x] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [ ] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by nicoloboschi — APPROVED** [review]
LGTM

**Comment by momo-jun** [comment]
@cbornet It will help users a lot if you can add the docs for this feature. Do you have any plans on that?

**Comment by momo-jun** [comment]
Hi @cbornet, Feel free to share your plans on adding the docs to the next version of docs and let me know anything I can help with.

**Pull request merged**
