### PR TITLE
[fix][fn] Make pulsar-admin support update py/go with package url

### LINKED ISSUE #18966: [Bug] Cannot update functions with Package URL
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Pulsar v2.10.2

### Minimal reproduce step
1) Enable package service
2) build a go function (maybe works with python or java too, don't know)
```
pulsar-admin packages upload function://public/default/myfunction@1.0 --path /full/path/to/function_binary --description "my function"
The package 'function://public/default/myfunction@1.0' uploaded from path '/full/path/to/function_binary' successfully

pulsar-admin functions create --tenant public --namespace default --name myfunc --go "function://public/default/myfunction@1.0" --inputs persistent://public/default/test
Created successfully

pulsar-admin packages upload function://public/default/myfunction@2.0 --path /full/path/to/function_binary_v2 --description "my function, but newer"
The package 'function://public/default/myfunction@2.0' uploaded from path '/full/path/to/function_binary_v2' successfully

pulsar-admin functions update --go "function://public/default/myfunction@2.0" --tenant public --namespace default --name myfunc
null

Reason: java.lang.IllegalArgumentException: File is not a normal file /Users/me/pulsar/function:/public/default/myfunction@2.0
```

### What did you expect to see?

```
Updated successfully
```

### What did you see instead?

```
Reason: java.lang.IllegalArgumentException: File is not a normal file /Users/me/pulsar/function:/public/default/myfunction@2.0
```

### Anything else?

Unlike `functions create`, `functions update` does not seem to understand package URLs, and attempts to access a local file. Since packages have built in versioning, it only makes sense that you would be able to create a new package version and update the function to use it. This would be emanently useful for testing and/or staging upgrades to running functions, so it feels like it should work, however documentation on the subject is kind of hazy.  In any case, it should be supported if it's not.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by jiangpengcheng**
Fixes #18966

Master Issue: #xyz

PIP: #xyz 

### Motivation

pulsar-admin functions update doesn't support package URL for python and golang

### Modifications

Fix

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

- [x] This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/jiangpengcheng/pulsar/pull/9

### CODE REVIEW

**Review by freeznet — APPROVED** [review]

**Comment by flowchartsman** [comment]
If we could backport this to at least 2.10 when it lands, you would make my year.

**Review by nlu90 — APPROVED** [review]

**Comment by nlu90** [comment]
@codelipenghui Can we backport this fix to 2.10?

**Comment by michaeljmarshall** [comment]
This is a pretty clear bug, so I cherry picked it to several release branches.

**Pull request merged**
