### PR TITLE
[fix][ml] Fix topic retention by size

### PR DESCRIPTION
**Pull request by dao-jun**
Fixes: https://github.com/apache/pulsar/issues/22473

### Motivation

For retention policies, it should be retain/delete the ledgers which were consumed.

But currently, we determine whether to delete a ledger by ledger total size(includes un-cosumed ledgers), it is not reasonable, and leads to deleting all the consumed ledger.

And also, the threshold of backlog quota might be related to this: backlog quota limitation have to less than retention. It doesn't make sense, too. 

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by lhotari — CHANGES_REQUESTED** [review]
> But currently, we determine whether to delete a ledger by ledger total size(includes un-cosumed ledgers), it is not reasonable, and leads to deleting all the consumed ledger.

@dao-jun  Please report a separate issue with more details since this seems like a significant change. This might even justify a dev mailing list discussion.

**Comment by lhotari** [comment]
It seems like there's a mailing list thread: https://lists.apache.org/thread/sv0wdyhn16r67hobmymfoor4bnd4d0fp.
In addition to this, please first create an issue with clear details in the issue description.

**Comment by dao-jun** [comment]
> It seems like there's a mailing list thread: https://lists.apache.org/thread/sv0wdyhn16r67hobmymfoor4bnd4d0fp. In addition to this, please first create an issue with clear details in the issue description.

OK

**Comment by dao-jun** [comment]
Close the PR since it is a doc issue.

**Pull request closed without merging**
