### PR TITLE
[docs] Add functions-debug file for Pulsar Functions(new)

### LINKED ISSUE #4554: [docs] Improve the structure of Pulsar Functions
**Is your feature request related to a problem? Please describe.**
I'm a little confused when searching information on Pulsar Functions. The content is scattered in different sections and does not integrate as a whole. Meanwhile, some information duplicates in *Overview* and other sections. It's a little bit frustrating to read the docs as a new user.

**Describe the solution you'd like**
I want to re-structure the architecture of Pulsar Functions as follows, so it will be easier to read and find information.
image

If you have any suggestion on the new architecture, feel free to contact me.
If there is no issue with it, I'll update the content throughout.

### PR DESCRIPTION
**Pull request by Jennifer88huang**
Fixes #4554 

### Motivation
Add debug tutorial for new Pulsar Functions structure.

### Modifications
1. To avoid conflicts with the original "functions-debugging" file, duplicate this file, rename it as "functions-debug".
2. Refine the content based on the duplicated file.

When you review this file, review it throughout, including tech, language, links and so on.

### CODE REVIEW

**Comment by Jennifer88huang** [comment]
@wolfstudy Could you please help review? Thank you.

**Comment by jiazhai** [comment]
run integration tests
run java8 tests

**Comment by Jennifer88huang** [comment]
run integration tests
run java8 tests

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by Jennifer88huang** [comment]
run integration tests

**Comment by Jennifer88huang** [comment]
run integration tests

**Comment by sijie** [comment]
retest this please

**Comment by Jennifer88huang** [comment]
run java8 tests

**Pull request merged**
