### PR TITLE
[improve][branch-2.10]upgrade the bookkeeper version to 4.14.7

### PR DESCRIPTION
**Pull request by horizonzy**
Fixes #xyz

Master Issue: #xyz

PIP: #xyz 

### Motivation
BookKeeper 4.14.7 has been released and it contains a lot of notable bug fixes. We need to upgrade the BookKeeper dependency from 4.14.5 to 4.14.7.

BookKeeper release notes can be found:
https://github.com/apache/bookkeeper/releases

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by nicoloboschi — COMMENTED** [review]
you should update the license file as well

**Comment by hangc0276** [comment]
BookKeeper 4.14.7 has been released, we can use BookKeeper 4.14.7 directly.

**Review by hangc0276 — APPROVED** [review]

**Comment by liangyepianzhou** [comment]
@horizonzy The OWASP check was failed. Could you please merge branch-2.10 to fix it?

**Comment by hangc0276** [comment]
> @horizonzy The OWASP check was failed. Could you please merge branch-2.10 to fix it?

@liangyepianzhou If the master has resolved the OWASP check, I think we can merge this PR directly. Because the CI need to rerun a few times before getting passed.

**Review by codelipenghui — APPROVED** [review]

**Review by Technoboy- — APPROVED** [review]

**Pull request merged**
