### PR TITLE
Make unit tests to only use dynamically allocated ports

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Use dynamically allocated ports in unit tests execution to ensure no port conflicts between multiple threads/processes.

### CODE REVIEW

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests
run integration tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests.

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by tuteng** [comment]
run java8 tests

**Comment by tuteng** [comment]
run java8 tests

**Comment by tuteng** [comment]
run java8 tests

**Comment by tuteng** [comment]
run java8 tests

**Comment by tuteng** [comment]
Unit testing seems to have some problems:

```
2020-01-05\T\06:21:26.542 [ERROR] testAuthentication(org.apache.pulsar.broker.authentication.ProxySaslAuthenticationTest)  Time elapsed: 33.912 s  <<< FAILURE!
org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: Connection already closed
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:717)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:93)
	at org.apache.pulsar.broker.authentication.ProxySaslAuthenticationTest.testAuthentication(ProxySaslAuthenticationTest.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Pull request merged**
