### PR TITLE
[fix][broker] Fix NPE when updating topic properties

### PR DESCRIPTION
**Pull request by Flowermin**
### Motivation
 The NPE occurs if `p.properties` is `null` when updating topic's properties in #17238 .

### Documentation
- [x] `doc-not-needed`

### CODE REVIEW

**Comment by HQebupt** [comment]
Please follow Pulsar Pull Request Naming Convention Guide: https://docs.google.com/document/d/1d8Pw6ZbWk-_pCKdOmdvx9rnhPiyuxwq60_TrD68d7BA/edit#heading=h.wu6ygjne8e35

**Comment by Flowermin** [comment]
> Please follow Pulsar Pull Request Naming Convention Guide: https://docs.google.com/document/d/1d8Pw6ZbWk-_pCKdOmdvx9rnhPiyuxwq60_TrD68d7BA/edit#heading=h.wu6ygjne8e35

Done

**Review by merlimat — APPROVED** [review]

**Review by yuruguo — APPROVED** [review]
LGTM

**Review by AnonHxy — APPROVED** [review]

**Review by nodece — APPROVED** [review]

**Review by Jason918 — APPROVED** [review]

**Comment by Jason918** [comment]
Can you help open a new PR to branch-2.10? There are a lot conflict when cherry-pick directly. @Flowermin

**Comment by AnonHxy** [comment]
It' fix for this PR https://github.com/apache/pulsar/pull/17238#issuecomment-1236343562,  we should also remove the label @Jason918

**Pull request merged**
