### PR TITLE
remove unused config managedLedgerNumWorkerThreads and related metrics

### PR DESCRIPTION
**Pull request by wenbingshen**
### Motivation
Related to this PR: #10647, since version 2.8.0, the `managedLedgerNumWorkerThreads` config is not referenced anywhere.

Need to update docs?  
  
- [x] `doc`

### CODE REVIEW

**Comment by wenbingshen** [comment]
@hangc0276 @codelipenghui PTAL. Thanks.

**Review by Shoothzj — APPROVED** [review]

**Comment by wenbingshen** [comment]
@codelipenghui @urfreespace @tuteng Could you help take a look at this pr? If this PR is accepted, I'll go ahead and submit a related PR to https://github.com/apache/pulsar-site

**Comment by codelipenghui** [comment]
@wenbingshen The `PulsarConnectorConfig` class also has `managedLedgerNumWorkerThreads`, could you please help remove it?

**Comment by wenbingshen** [comment]
> @wenbingshen The `PulsarConnectorConfig` class also has `managedLedgerNumWorkerThreads`, could you please help remove it?

Thanks for review. I have removed `managedLedgerNumWorkerThreads` from `PulsarConnectorConfig`. PTAL.

**Review by tuteng — COMMENTED** [review]
Do we just remove it, or do we set it to a deprecated state?

**Comment by wenbingshen** [comment]
> Do we just remove it, or do we set it to a deprecated state?

This configuration has not been `referenced` by any code since `2.8.0`,because starting from version 2.8.0, whether the user configures this parameter or not, the code will no longer take effect. So we still need to mark it as deprecated? 

I think in deprecated state, this parameter needs to take effect at least in code. It is not recommended for users to use it after version 2.8.0, but we have reached version 2.11 now, and this parameter will not take effect even if it is configured.

**Review by codelipenghui — APPROVED** [review]

**Review by Jason918 — APPROVED** [review]

**Pull request merged**
