### PR TITLE
[impr][broker] Reduce string allocations for stats generation

### PR DESCRIPTION
**Pull request by michaeljmarshall**
### Motivation

We are try to minimize the number of strings allocated when generating stats. This PR changes the logic to reduce allocations by storing string references that are generated. Here is some of the code that we're calling:

```java
    public String getClientVersion() {
        return clientVersionOffset == -1 ? null
                : stringBuffer.substring(clientVersionOffset, clientVersionOffset + clientVersionLength);
    }
```

Since each invocation of `getClientVersion` generates a new string, it is better to get the string once and store it in a reference.

### Modifications

* Update certain string comparisons so that we do not regenerate the same string multiple times.

### Verifying this change

This is a trivial rework that is covered by tests.

### Does this pull request potentially affect one of the following parts:

This is an internal optimization.

### Documentation

- [x] `doc-not-needed`

### Matching PR in forked repository

PR in forked repository: Skipping forked PR

### CODE REVIEW

**Comment by michaeljmarshall** [comment]
@lhotari - PTAL

**Review by lhotari — CHANGES_REQUESTED** [review]
Let's instead revert #1480 changes and use ordinary fields instead of the StringBuilder hack. There's no justification that the solution would be useful.

**Comment by poorbarcode** [comment]
Since we will start the RC version of `3.0.0` on `2023-04-11`, I will change the label/milestone of PR who have not been merged.
- The PR of type `feature` is deferred to `3.1.0`
- The PR of type `fix` is deferred to `3.0.1`

So drag this PR to `3.1.0`

**Comment by lhotari** [comment]
handled by #20428

**Comment by michaeljmarshall** [comment]
Thanks @lhotari

**Pull request closed without merging**
