### PR TITLE
fix: RuntimeInfo doesn't get set when transferring ownership of function from another worker to this worker

### PR DESCRIPTION
**Pull request by jerrypeng**
### Motivation

For externally managed runtimes in functions, when the assignment of a function gets transferred from another worker to this worker, the runtime info of the function doesn't get set causing the function to not be able to be deleted afterwards

### Modifications

Fix the issue as well as add unit tests to test for this situation.

Also add some print statements to make sure runtime infos and assignments for a worker is in sync

### CODE REVIEW

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by merlimat** [comment]
rerun integration tests

**Comment by jerrypeng** [comment]
rerun integration tests

**Comment by jerrypeng** [comment]
rerun integrations tests

**Comment by jerrypeng** [comment]
rerun integration tests
rerun cpp tests

**Comment by jerrypeng** [comment]
rerun integrations tests

**Comment by merlimat** [comment]
run integrations tests

**Comment by merlimat** [comment]
run integration tests

**Pull request merged**
