### PR TITLE
Support key based batch builder for Go Functions

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <rxl@apache.org>

### Motivation

The changing base on #8523

### Modifications

Support key_based batch builder for Go Functions

### CODE REVIEW

**Review by codelipenghui — COMMENTED** [review]
Could you please a unit test for this change?

**Comment by wolfstudy** [comment]
> Could you please a unit test for this change?

In fact, in the integration test, we already test this case.

In `generateCreateFunctionCommand()`, we add the command as follows:

```
        if (batchBuilder != null) {
            commandBuilder.append("--batch-builder" + batchBuilder);
        }
```

And in create different language functions, we will use `generateCreateFunctionCommand` res to test different case.

```
        switch (runtime){
            case JAVA:
                command = generator.generateCreateFunctionCommand();
                break;
            case PYTHON:
            case GO:
                generator.setRuntime(runtime);
                command = generator.generateCreateFunctionCommand(functionFile);
                break;
            default:
                throw new IllegalArgumentException("Unsupported runtime : " + runtime);
        }
```

**Review by codelipenghui — APPROVED** [review]

**Comment by wolfstudy** [comment]
```
stderr: 
Error:  Tests run: 20, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 889.319 s <<< FAILURE! - in TestSuite
Error:  testBookKeeperDown(org.apache.pulsar.tests.integration.cli.HealthCheckTest)  Time elapsed: 0.176 s  <<< FAILURE!
org.apache.pulsar.tests.integration.docker.ContainerExecException: pkill -STOP -f BookieServer failed on a7586c3276f50e9b34e60153710166022c4886da5f5b3f984e804cb8ee9cc99c with error code 1
	at org.apache.pulsar.tests.integration.utils.DockerUtils$2.onComplete(DockerUtils.java:259)
	at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec$1.onComplete(AbstrAsyncDockerCmdExec.java:51)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.lambda$executeAndStream$4(OkHttpInvocationBuilder.java:331)
	at java.lang.Thread.run(Thread.java:748)
```

**Pull request merged**
