### PR TITLE
[Doc] Support DLQ in key_shared subscription mode

### PR DESCRIPTION
**Pull request by Huanli-Meng**
### Motivation

According to this [PR](https://github.com/apache/pulsar/pull/9678), the DLQ is supported in the key_shared sub. Therefore, update the docs accordingly.

### Modifications

Update the **Dead Letter topic** section in **Messaging** doc.

### Affected release:
2.8.0

### CODE REVIEW

**Review by Jennifer88huang — APPROVED** [review]

**Comment by Anonymitaet** [comment]
Hi @codelipenghui based on your comment [here](https://github.com/apache/pulsar/pull/9583#issuecomment-783424273), should we update the docs as below?

1. Update the usage for DLT.

- Original text

>Currently, dead letter topic is enabled only in the shared subscription mode.`

- Updated text

>Currently, the dead letter topic can be enabled for all subscription types (`Exclusive`, `Failover`, `Key_Shared`, and `Shared`).

2. Add the consequence of using DQL for ordered subscription type.

    Since we have [documented ](https://pulsar.apache.org/docs/en/next/concepts-messaging/#negative-acknowledgement) the consequence of using nack for ordered subscription types, should we add the consequence of using DQL for ordered subscription types as well?

- Added text

```
> **Note**
>
>  Using the dead letter topic on **ordered** subscription types (`Exclusive`, `Failover`, and `Key_Shared`) can cause messages to arrive consumers out of the original order.

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@Anonymitaet Currently, we can only enable DLQ on Shared and Key_Shared subscriptions.

**Comment by Anonymitaet** [comment]
@codelipenghui thanks! How about adding the consequence of using DQL for ordered subscription type (as below)?

> **Note**
>
>  Using the dead letter topic on **ordered** subscription types (`Key_Shared`) can cause messages to arrive consumers out of the original order.

**Review by eolivelli — APPROVED** [review]

**Comment by Jennifer88huang** [comment]
@Huanli-Meng when you submit a PR, could you please add the labels accordingly? Thank you.

**Comment by Anonymitaet** [comment]
> @codelipenghui thanks! How about adding the consequence of using DQL for ordered subscription type (as below)?
> 
> > **Note**
> > Using the dead letter topic on the **ordered** subscription type (`Key_Shared`) can cause messages to arrive consumers out of the original order.

Hi @codelipenghui could you please help answer this question? Thanks

**Comment by codelipenghui** [comment]
@Anonymitaet Yes, we can add a notice in the DLQ concept, if enable DLQ on the Key_Shared subscription, this will break the message process order.

**Comment by Huanli-Meng** [comment]
we have described what is Dead letter topic is used for in our doc. Therefore, I think we do not need to add a notice to indicate it will break the message process order.
image

**Pull request merged**
