### PR TITLE
[fix][broker]fix arithmetic exception for LeastResourceUsageWithWeight strategy

### PR DESCRIPTION
**Pull request by HQebupt**
### Motivation
For a candidate broker, the addition expression maybe results in out of bounds and causes unexpected result when executing the following code.
https://github.com/apache/pulsar/blob/3ecf34abf99afd7c53a681ab82d5bcec2bc499a1/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LeastResourceUsageWithWeight.java#L146-L151

### Modifications
Make the max resource usage as 100% instead of `Double.MAX_VALUE`.

### Verifying this change

- [x]  Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.
### Does this pull request potentially affect one of the following parts:

If `yes` was chosen, please highlight the changes

- Dependencies (does it add or upgrade a dependency): (no)
- The public API: (no)
- The schema: (no)
- The default values of configurations: (no)
- The wire protocol: (no)
- The rest endpoints: (no)
- The admin cli options: (no)
- Anything that affects deployment: (no)

### Documentation
Check the box below and label this PR (if you have committer privilege).

Need to update docs? 
- [x] `doc-not-needed`

### CODE REVIEW

**Review by MarvinCai — APPROVED** [review]
lgtm

**Review by codelipenghui — COMMENTED** [review]
Please help add a test to avoid the regression

**Review by codelipenghui — APPROVED** [review]

**Comment by mattisonchao** [comment]
HI @HQebupt 
Would you like to cherry-pick this PR for branch 2.9 to fix this problem?

**Comment by Jason918** [comment]
LeastResourceUsageWithWeight is introduced in 2.11, so it's better remove the old release labels.
@mattisonchao FYI

**Pull request merged**
