### PR TITLE
make AsyncHttpConnector.delayer thread daemon

### LINKED ISSUE #7437: Pulsar Admin Java Client leaves hanging thread after close called
**Describe the bug**
After closing a Java pulsar admin instance, a delayer thread is left hanging in the background in a TIMED_WAITING state that can prevent the parent program from ending.

**To Reproduce**
1. Create a pulsar admin instance.
2. Add a new topic using the pulsar admin.
3. Close the pulsar admin.
4. Do a java thread dump to see the hanging delayer thread.

**Expected behavior**
Calling close should free and end all threads created by the PulsarAdmin. This includes all AsyncHttp related threads.

**Desktop (please complete the following information):**
- Linux

### PR DESCRIPTION
**Pull request by rushsky518**
Fixes #7437

### CODE REVIEW

**Comment by codelipenghui** [comment]
@rushsky518 Thanks for the contribution, would you please take a look the comment?

**Comment by wolfstudy** [comment]
```
org.apache.pulsar.functions.worker.PulsarFunctionE2ESecurityTest
[ERROR] testAuthorization(org.apache.pulsar.functions.worker.PulsarFunctionE2ESecurityTest)  Time elapsed: 1.779 s  <<< FAILURE!
java.lang.AssertionError: expected [null] but found [value]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:132)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:453)
	at org.testng.Assert.assertEquals(Assert.java:463)
	at org.apache.pulsar.functions.worker.PulsarFunctionE2ESecurityTest.testAuthorization(PulsarFunctionE2ESecurityTest.java:630)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by wolfstudy** [comment]
@rushsky518 Sorry, Due to my reasons, I closed the pull request incorrectly. Can you help reopen it and merge master code, thanks.

**Comment by codelipenghui** [comment]
@rushsky518 There are some tests fixes in the master branch, I think you need to merge the master branch, Otherwise, the CI can't be passed. And you'd better to `checkout -b` a new branch and use the new branch to send out a pull request.

**Comment by rushsky518** [comment]
> 
> 
> @rushsky518 There are some tests fixes in the master branch, I think you need to merge the master branch, Otherwise, the CI can't be passed. And you'd better to `checkout -b` a new branch and use the new branch to send out a pull request.

hi, i opend a new pr #7687

**Pull request closed without merging**
