### PR TITLE
[improve][build] Set correct project.build.outputTimestamp

### PR DESCRIPTION
**Pull request by tisonkun**
This closes #17754.

### Motivation

See https://github.com/apache/pulsar/pull/17754#issue-1380037910.

Also, this corrects the generated NOTICE year range.

### Modifications

* Set `project.build.outputTimestamp` to `maven.build.timestamp`
* Upgrade plugin for reproducible builds, spotted by `mvn artifact:check-buildplan`

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/tisonkun/pulsar/pull/21

### CODE REVIEW

**Comment by tisonkun** [comment]
After a discussion with @michaeljmarshall, we agree on continuing #17754 :)

**Comment by michaeljmarshall** [comment]
@tisonkun - I'm sorry, I misread your initial PR. Your solution is better than mine. I think we should reopen this and use it.

**Review by michaeljmarshall — APPROVED** [review]

**Comment by tisonkun** [comment]
@michaeljmarshall Thanks for your review!

Merging...

**Pull request merged**
