### PR TITLE
[doc][puslar-io]Fix document of debezium

### PR DESCRIPTION
**Pull request by tuteng**
### Motivation

There are some typos in the document content of about debezium, which affect users' use, so fix it.

### Modifications

Fix typos in document of debezium. And format content

### CODE REVIEW

**Comment by tuteng** [comment]
run Integration tests
run Cpp tests

**Comment by jiazhai** [comment]
run integration tests
run cpp tests

**Comment by sijie** [comment]
retest this please

**Comment by sijie** [comment]
run cpp tests

**Comment by sijie** [comment]
run cpp tests

**Comment by sijie** [comment]
run cpp tests

**Pull request merged**
