### PR TITLE
Windows CMake corrections

### PR DESCRIPTION
**Pull request by heronr**
### Motivation

This change is to fix building with CMake on Windows platforms.

### Modifications

The primary change is to provide more library names for zlib, protobuf, and curl that will match the windows versions of these libraries. It also includes small changes to find clang-format and clang-tidy, and also to install the dll in the bin folder instead of the lib folder.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): no
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no
  - The rest endpoints: no
  - The admin cli options: no
  - Anything that affects deployment: no

### Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by aahmed-se** [comment]
@heronr Add a gitlab workflow to check compilation on windows.

**Comment by sijie** [comment]
@heronr can you add a github action to verify it can build on windows?

**Comment by heronr** [comment]
Apologies, how do I do that?

**Comment by aahmed-se** [comment]
@heronr 
check the workflows  under 
`.github/workflows/`
add a new one and target the windows os , you can use vcpkg to install dependencies and cache them. After that just make sure that it can be compiled under windows using cmake.

**Comment by merlimat** [comment]
I think it the windows github action would be good to go in a different PR anyway.

**Comment by tuteng** [comment]
Add label release-2.5.1, due to #6458 dependency

**Pull request merged**
