### PR TITLE
support limit max topics per namespace

### LINKED ISSUE #8225: Support limits the max topics per namespace
**Is your feature request related to a problem? Please describe.**
Support limits the max topics per namespace of the Pulsar cluster. When the topics reach the max topics of the namespace, the broker should reject the new topic request(include topic auto-created by the producer or consumer). 

**Describe the solution you'd like**
Add `maxTopicsPerNamespace=0` in the broker.conf and don't limit by default.

### PR DESCRIPTION
**Pull request by hangc0276**
Fix #8225 

### Changes
1. Add topic partition number limit, which only take persistent topic into account, for each namespace
2. The  max topic number of each namespace can only be configured by broker.conf, i will make it configurable dynamic soon
3. Add the tests for this feature.

### CODE REVIEW

**Comment by aahmed-se** [comment]
The limit should be per namespace.

**Comment by hangc0276** [comment]
> The limit should be per namespace.

@aahmed-se Yes, the limit is per namespace.

**Comment by sijie** [comment]
@aahmed-se :

> The limit should be per namespace.

We usually add a default setting to broker/cluster-level first. Then add the setting to the namespace policy. We should make it consistent.

**Review by sijie — APPROVED** [review]

**Comment by sijia-w** [comment]
@hangc0276 @Anonymitaet Shall we add description to this section https://pulsar.apache.org/docs/en/concepts-messaging/#namespaces? I appreciate your confirmation.

**Comment by Anonymitaet** [comment]
@sijia-w I think the doc for this newly added configuration `maxTopicsPerNamespace` should be added to the configuration section:

- [broker](https://pulsar.apache.org/docs/en/next/reference-configuration/#broker)
- [standalone](https://pulsar.apache.org/docs/en/next/reference-configuration/#standalone)

Need to add configuration name, descriptions, and the default value (0).

@hangc0276 Please correct me if I'm wrong, thanks.

**Pull request merged**
