### PR TITLE
[feat][proxy] PIP-250: Add proxyVersion to CommandConnect

### PR DESCRIPTION
**Pull request by michaeljmarshall**
PIP #19623 
Relates to https://github.com/apache/pulsar/pull/19540

### Motivation

In order to get more information about connections, it is helpful for the proxy to supply its version to the broker.

### Modifications

* Add `proxy_version` field to the `CommandConnect` protobuf message 
* Update proxy and broker to handle this new field

### Verifying this change

New tests are added with this PR.

### Does this pull request potentially affect one of the following parts:

- [x] The binary protocol

This will be submitted as part of a PIP.

### Documentation

- [x] `doc-not-needed`

### Matching PR in forked repository

PR in forked repository: Skipping since this is only a draft.

### CODE REVIEW

**Comment by michaeljmarshall** [comment]
I plan to submit a PIP for this PR. I'll leave it in draft mode until we have a PIP.

**Comment by poorbarcode** [comment]
Since we will start the RC version of `3.0.0` on `2023-04-11`, I will change the label/milestone of PR who have not been merged.
- The PR of type `feature` is deferred to `3.1.0`
- The PR of type `fix` is deferred to `3.0.1`
So drag this PR to `3.1.0`

**Review by lhotari — APPROVED** [review]
LGTM

**Review by nicoloboschi — APPROVED** [review]

**Comment by michaeljmarshall** [comment]
Docs added here: https://github.com/apache/pulsar-site/pull/531

**Pull request merged**
