### PR TITLE
[Build] Update management module version

### PR DESCRIPTION
**Pull request by gaoran10**
### Modifications

Update package `org.apache.pulsar:pulsar-package-management` from `2.7.0-SNAPSHOT` version to `2.8.0-SNAPSHOT`.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by eolivelli** [comment]
The MACOs test is failing with:
```
Run apache/pulsar-test-infra/diff-only@master
Error: Container action is only supported on Linux
```

IMHO we can ignore it and merge the patch

**Comment by codelipenghui** [comment]
@eolivelli Yes, we are still trying to find a solution to verify the build process on different os. So it's not a required CI test. I have merged this PR, and I will close https://github.com/apache/pulsar/pull/8698 first.

**Pull request merged**
