### PR TITLE
[improve] Update Oxia client to 0.1.6

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Update Oxia client 0.1.2, using regular non-shaded library.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by lhotari — APPROVED** [review]
LGTM

**Review by dao-jun — APPROVED** [review]

**Review by nodece — APPROVED** [review]

**Comment by merlimat** [comment]
There is a problem with the unshaded pom, I'm still waiting for 0.1.3 to be available on Maven Central

**Comment by nodece** [comment]
@merlimat Please check `java.lang.NoClassDefFoundError: io/streamnative/oxia/client/metrics/api/Metrics`.

**Comment by merlimat** [comment]
> @merlimat Please check `java.lang.NoClassDefFoundError: io/streamnative/oxia/client/metrics/api/Metrics`.

Yes, it's because the pom is still shaded and the dependencies are removed by maven. Waiting for 0.1.3

**Review by mattisonchao — APPROVED** [review]

**Review by dao-jun — APPROVED** [review]

**Comment by nodece** [comment]
```
LockManagerTest.acquireLocks:66 » NoClassDefFound Could not initialize class io.streamnative.oxia.proto.ListResponse
```

**Comment by merlimat** [comment]
> ```
> LockManagerTest.acquireLocks:66 » NoClassDefFound Could not initialize class io.streamnative.oxia.proto.ListResponse
> ```

This was due to protobuf version conflicts. Solved by merging with master

**Pull request merged**
