### PR TITLE
issue #6698, Add instantiation interface in Pulsar function

### LINKED ISSUE #6698: Pulsar function to instantiate
**Is your feature request related to a problem? Please describe.**
When instantiating the function implementation class, the function implementation class's constructor is instantiated by using the functions-worker runtime classloader. In the function implementation class's constructor, getting the configuration file in the classpath only reads the configuration file in Java-instance.jar, and then the function that executes the process function has been switched to the function instance's classloader, so in process function, you can read the configuration file under classpath in the project jar of function application.
But I want to initialize the members of the function implementation class before executing the process function, such as creating a database connection and other operations, which cannot be operated.

**Describe the solution you'd like**
Modify the source code of Function.java and JavaInstanceRunnable.java, add a prepare interface in function.java, switch classloader after instantiating function at runtime, call the prepare interface first, pass the parameters of the command submitted during create function into the prepare interface with context, perform initialization operation in the prepare interface, and then call the process interface to consume messages.

public interface Function<I, O> {

    void prepare(Context context) throws Exception;

    /**
     * Process the input.
     *
     * @return the output
     */
    O process(I input, Context context) throws Exception;
}

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by xuesongxs**
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #6698 
*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #6698 

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications
1.add prepare interface in Function.java

2.swith classloader after setupJavaInstance，before process in JavaInstanceRunnable.java.

3.List of modified files:
JavaInstance.java
JavaInstanceRunnable.java
Function.java
WindowFunctionExecutor.java
JavaInstanceRunnableTest.java
JavaInstanceRunnableTest.java
JavaInstanceTest.java
AutoSchemaFunction.java
ConfigBasedAppendFunction.java
ConsistentlyFailingFunction.java
ContextFunction.java
CustomBaseToBaseFunction.java
CustomBaseToDerivedFunction.java
CustomDerivedToBaseFunction.java
CustomDerivedToDerivedFunction.java
CustomObjectFunction.java
ExclamationFunction.java
HostAppenderFunction.java
InstanceIdAppenderFunction.java
IntegerAdditionFunction.java
LoggingFunction.java
PublishFunction.java
TypedMessageBuilderPublish.java
UserConfigFunction.java
UserExceptionFunction.java
UserMetricFunction.java
UserPublishFunction.java
VoidFunction.java
WordCountFunction.java
FunctionsImplTest.java
FunctionApiV2ResourceTest.java
FunctionApiV3ResourceTest.java

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by xuesong172500** [comment]
issue #6698

**Comment by sijie** [comment]
@xuesong172500 

this change couples a lot of different changes (i.e. skywalking related changes). Can we move it out?

**Comment by xuesong172500** [comment]
yes！

**Comment by codelipenghui** [comment]
@xuesong172500 Could you rebase with the master branch?

**Comment by codelipenghui** [comment]
move to 2.7.0 first.

**Comment by tisonkun** [comment]
Closed as stale and no consensus.

**Pull request closed without merging**
