### PR TITLE
[Issue 5362][website]Update logo path for Pulsar users

### LINKED ISSUE #5362: [website] Some company logos are not displayed well on poweredby website
**Describe the bug**
Some company logos are not displayed well on website http://pulsar.apache.org/powered-by/

image
image
image

### PR DESCRIPTION
**Pull request by Jennifer88huang**
Fixes #5362 

### Motivation
Some logo pathes are not correct, and could not display well at http://pulsar.apache.org/powered-by/

### Modifications
Update the logo pathes.

### CODE REVIEW

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by Jennifer88huang** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by Jennifer88huang** [comment]
run java8 tests

**Comment by tuteng** [comment]
run java8 tests

**Comment by Jennifer88huang** [comment]
run java8 tests

**Comment by Jennifer88huang** [comment]
2019-10-18\T\04:11:04.551 [ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 61.287 s <<< FAILURE! - in org.apache.pulsar.functions.worker.PulsarFunctionE2ESecurityTest
2019-10-18\T\04:11:04.552 [ERROR] testAuthorization(org.apache.pulsar.functions.worker.PulsarFunctionE2ESecurityTest)  Time elapsed: 4.783 s  <<< FAILURE!
java.lang.AssertionError: expected [0] but found [1]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:652)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at org.apache.pulsar.functions.worker.PulsarFunctionE2ESecurityTest.testAuthorization(PulsarFunctionE2ESecurityTest.java:792)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Jennifer88huang** [comment]
run java8 tests

**Comment by Jennifer88huang** [comment]
run java8 tests

**Pull request merged**
