### PR TITLE
[improve][cli] Allow pulser-client consume create a replicated subscription

### PR DESCRIPTION
**Pull request by JooHyukKim**
Master Issue: #11371
Issue: #11371

### Motivation

`pulsar-client consume` doesn't currently support creating replicated subscriptions.

### Modifications

- Added option in `CmdConsume` for specifying the replicated parameter for subscription creation.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:

- We need to add integration test between the client and broker regarding the replication.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [x] Anything that affects deployment 👉🏼 new client CLI option.

### Documentation

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/JooHyukKim/pulsar/pull/4

### CODE REVIEW

**Review by nicoloboschi — APPROVED** [review]
Thanks for your contribution! 
I renamed the pull request with "cli" since this only affects the CLI component

**Comment by tisonkun** [comment]
> The doc could be generated automatically

Yes, specifically, in [this script](https://github.com/apache/pulsar-site/blob/cc349c2a440cd5da3ccbd7ecb771e93f57ec745d/tools/pytools/lib/execute/pulsar_client_clidoc_generator.py).

**Review by tisonkun — APPROVED** [review]
Thank you!

**Comment by tisonkun** [comment]
image

Already updated.

**Comment by tisonkun** [comment]
Ref - https://github.com/apache/pulsar-site/commit/2536a6e4938b0dac06d88f5b611a018afa1d7572

**Pull request merged**
