### PR TITLE
[broker][fix]Fix update topic remove properties

### PR DESCRIPTION
**Pull request by AnonHxy**
### Motivation

* There is a bug that the properties of topic will be removed if we update topic partition number using pulsar admin

### Modifications

* Keep the properties in `PartitionedTopicMetadata` when updating it.

### Verifying this change

- [x] Make sure that the change passes the CI checks.
- Add UT `org.apache.pulsar.broker.admin.PersistentTopicsTest#testUpdatePartitionedTopicHavingProperties`

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by yuruguo — COMMENTED** [review]
Same problem below, please pay attention :)
https://github.com/apache/pulsar/blob/8286e8ccb2e1433814c306607c6f218ca548752a/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L483-L484

**Comment by AnonHxy** [comment]
> Same problem below, please pay attention :)
> 
> https://github.com/apache/pulsar/blob/8286e8ccb2e1433814c306607c6f218ca548752a/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L483-L484

Nice catch. Thanks @yuruguo

**Review by yuruguo — APPROVED** [review]
LGTM

**Comment by HQebupt** [comment]
> [broker][fix]Fix update topic remove properties
Does the PR title naming change ?

**Review by Technoboy- — APPROVED** [review]

**Comment by Jason918** [comment]
Can you help open a new PR to branch-2.10? There are a lot conflict when cherry-pick directly. @AnonHxy

**Comment by AnonHxy** [comment]
The conflict cause is that this patch is based on https://github.com/apache/pulsar/pull/14141, which is release in 2.11.0. I will remove the 2.10.2 label and and 2.11.1

**Pull request merged**
