### PR TITLE
[docs] Add support for websocket produce/consume command

### PR DESCRIPTION
**Pull request by Jennifer88huang**
### Motivation
Support for websocket produce/consume command is added in https://github.com/apache/pulsar/pull/3835. The info is not updated in doc content.

### Modifications
Sync doc content with code update.

### CODE REVIEW

**Comment by tuteng** [comment]
run java8 tests

**Comment by Jennifer88huang** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by Jennifer88huang** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Pull request merged**
