### PR TITLE
[issue 10750][pulsar-broker]Fix the bug that consumers with the same name cannot consume when key_shared mode

### LINKED ISSUE #10750: Consumer cannot consume messages when key_shared mode  and subscriptionKeySharedUseConsistentHashing
**Describe the bug**
Key_shared mode is configured as ConsistentHashingStickyKeyConsumerSelector, When I use three consumers with the same consumerName, if one consumer is closed, the other two consumers will no longer be able to consume messages.

**To Reproduce**
1. config the 'conf/standalone.conf'
   ```
    subscriptionKeySharedUseConsistentHashing=true
   ```
2. ./bin/pulsar standalone
3. Start 3 consumers with the same cosumerName.
```
        PulsarClient client = PulsarClient.builder()
                .serviceUrl("pulsar://localhost:6650")
                .build();

        org.apache.pulsar.client.api.Consumer consumer = client.newConsumer()
                .topic("my-topic")
                .subscriptionName("my-subscription")
                .consumerName("one")
                .subscriptionType(SubscriptionType.Key_Shared)
                .subscribe();
```
4. Start a producer send messages.
5. All 3 consumers can consume messages.
6. Close one consumer, and the producer send messages again.
7. **The other two consumers cannot consume new messages**

**Expected behavior**
The other two consumers can continue to consume new messages(Refer to step 7 above).

**Additional context**
https://github.com/apache/pulsar/blob/e19f6472183ac93dc058a96f7ac0537c22d90e18/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ConsistentHashingStickyKeyConsumerSelector.java#L93

I think the problem is due to the above code, which removes all consumers with the same name.

### PR DESCRIPTION
**Pull request by sourcelliu**
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #10750 

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no) no
  - The public API: (yes / no) no
  - The schema: (yes / no / don't know) no
  - The default values of configurations: (yes / no) no
  - The wire protocol: (yes / no) no
  - The rest endpoints: (yes / no) no
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know) no

### Documentation

  - Does this pull request introduce a new feature? (yes / no) no
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by mantuliu** [comment]
@massakam @merlimat @codelipenghui @MarvinCai PTAL, thanks.

**Comment by mantuliu** [comment]
Hi, @massakam @merlimat @codelipenghui @MarvinCai , can you please take a look?

**Review by k2la — APPROVED** [review]

**Comment by eolivelli** [comment]
@mantuliu thanks for your fix.
Can you please clean up the PR description and fill in the fields (Motivation, Modifications...) ?

**Review by eolivelli — CHANGES_REQUESTED** [review]
it looks like the implementation of ConsistentHashingStickyKeyConsumerSelector is based on  
consumer.consumerName() in many other places.

Probably this is not the best approach to fix the problem.

**Comment by codelipenghui** [comment]
The pr had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale and conflict. Feel free to rebase and resubmit the patch.

**Pull request closed without merging**
