### PR TITLE
Upgrade Lombok version

### PR DESCRIPTION
**Pull request by lhotari**
### Motivation

- 1.18.18 includes fixes for IDE compatibility (IntelliJ, Eclipse, Netbeans).
  This is relevant while developing Pulsar.
  - see https://projectlombok.org/changelog for more details

### Modifications

- upgrade Lombok version from 1.18.16 to 1.18.18

### CODE REVIEW

**Review by sijie — APPROVED** [review]

**Review by aahmed-se — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by 315157973 — APPROVED** [review]

**Review by Jennifer88huang — APPROVED** [review]

**Comment by zymap** [comment]
Hi @lhotari , Looks like the CI `process` is in a weird status. Rebase your code or reopen this PR may make it normal.

**Comment by lhotari** [comment]
This PR is finally ready to be merged. /Cc @sijie @merlimat

**Pull request merged**
