### PR TITLE
[pulsar-io-elastic-search] NumberOfReplicas can be 0

### PR DESCRIPTION
**Pull request by geraudster**
### Motivation

Replicating shards in Elasticsearch is not mandatory, so we should have a way to set numberOfReplicas to 0 in sink configuration.

### Modifications

 - Change condition on `indexNumberOfReplicas` to accept 0 value
 - Update error message

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no
  - The rest endpoints: no
  - The admin cli options: no
  - Anything that affects deployment: no

### Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by merlimat** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Pull request merged**
