### PR TITLE
[Functions] Create per instance pulsar clients. #8575

### LINKED ISSUE #8575: When a task is stopped or deleted, it will cause all other tasks to stop consuming data
**Describe the bug**
Runtime ： Thread Runtime
broker number ：3
bookie number ：6 
functionWorker number ： 6
task number: 423

**When I call the following api, all other tasks will stop consuming data.**
https://pulsar.apache.org/admin/v3/sinks/{tenant}/{namespace}/{sinkName}/stop
**When all tasks stop consuming data, we can see the following stack information.**
image
image
**And the topic stats:**
image

The reason for this problem is that there is only one PulsarClient in a functionWorker instance, and the number of externalExecutorProvider thread pools in PulsarClient is 1, so all consumers share the same listener executor. Therefore, when one or more tasks stoped, the listener executor will be blocked, and finally other tasks will stop consuming data.

I think there should be at least two solutions:
1. Add "numListenerThreads" configuration in WorkerConfig.
2. Remove the message listener in PulsarSource, and add a thread in PulsarSource to execute the consumer's receive method to take message. 

There is a problem with scheme 1: when you stop or delete a task, you will see the following in the stack
image

How do you like it? Or are there any other, more graceful, solutions to this problem?

### PR DESCRIPTION
**Pull request by xche**
Fixes #8575

### Motivation

Move create PulsarClient from ThreadRuntimeFactory to JavaInstanceRunnable

The reason for this problem is that there is only one PulsarClient in a functionWorker instance, and the number of externalExecutorProvider thread pools in PulsarClient is 1, so all consumers share the same listener executor. Therefore, when one or more tasks stoped, the listener executor will be blocked, and finally other tasks will stop consuming data.

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by xche** [comment]
@jerrypeng This pr is for "The correct solution would be to change the number listener threads for the pulsar client used in the TheadRuntime or create per instance pulsar clients."

**Comment by jiazhai** [comment]
@xche Thanks a lot for the help.  Is it possible to add a test to cover the original error: `when one or more tasks stoped, the listener executor will be blocked, and finally other tasks will stop consuming data`. This will protect this part of the fix, and also help a lot to verify this fix. 

@freeznet Would you please also take a look at this PR?

**Comment by freeznet** [comment]
@jiazhai sorry for the late response. 

This PR is LGTM, and solved #8575 by adding per instance pulsar client for each thread function. But we should dig a little bit deeper to find out why the queue is blocked under shared pulsar client in thread runtime mode. Ideally, when one or more functions stop, the client should keep consuming data for the rest functions, and one or more functions' change should not affect other functions' condition.

**Review by jerrypeng — CHANGES_REQUESTED** [review]
I don't think this is the right solution.  There is a reason for having one client for all threads.  It is in place to conserve resources for running in thread mode and creating a Pulsar client per thread is redundant.

**Comment by xche** [comment]
Each task instance has one client, which leads to CPU consumption

**Pull request closed without merging**
