### PR TITLE
[feat][sql] Support metadata store url

### PR DESCRIPTION
**Pull request by tisonkun**
This refers to #18209 and part of the commits is included in #18207.

Although it seems hard to integrate with the RocksDB metadata store backend which is the original purpose for this patch as described in #18209, this patch migrates Pulsar SQL dependency of metadata store to the PIP-45 proposed model. And now we can use etcd metadata store backend at least and reduce dependencies to legacy logics.

cc @merlimat @gaoran10 @nicoloboschi @Jason918 @lhotari 

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/tisonkun/pulsar/pull/12

### CODE REVIEW

**Review by Jason918 — APPROVED** [review]
LGTM

**Review by codelipenghui — APPROVED** [review]

**Comment by tisonkun** [comment]
cc @Jason918 @codelipenghui I think this patch is ready for merge now :)

**Pull request merged**
