### PR TITLE
[fix][doc] Correcting spelling mistakes

### PR DESCRIPTION
**Pull request by daziz**
### Motivation
Correcting spelling mistakes

### Documentation

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Comment by daziz** [comment]
- [ ] `doc` 
- [ ] `doc-required` 
- [√ ] `doc-not-needed` 
- [ ] `doc-complete`

**Comment by daziz** [comment]
- [ ] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete`

**Review by tisonkun — APPROVED** [review]
Thank you!

**Comment by tisonkun** [comment]
@Technoboy- I suppose API docs are also docs.

**Comment by tisonkun** [comment]
Trivial changes.

Merging...

Thanks for your contribution @daziz!

**Pull request merged**
