### PR TITLE
[feat][pulsar-io] ElasticSearch sink: support token based auth

### PR DESCRIPTION
**Pull request by nicoloboschi**
### Motivation
Support token based authentication in the ElasticSearch sink connector.

https://www.elastic.co/guide/en/elasticsearch/reference/current/token-authentication-services.html

### Modifications
* New `token` and `apiKey` config fields.
You have to use only one between username/password, token and apiKey.

Both are used with the `Authorization` header.
```
Authorization: Bearer <token>
...
Authorization: ApiKey <apiKey>
```

Note that OpenSearch doesn't support Api Key authentication at the moment.

- [x] `doc`

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
Lgtm

**Comment by nicoloboschi** [comment]
@michaeljmarshall @lhotari PTAL

**Review by michaeljmarshall — APPROVED** [review]

**Pull request merged**
