### PR TITLE
Refactored PulsarRecordCursor to avoid intermediate thread

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Refactor the `PulsarRecordCursor` to avoid intermediate thread to deserialize the batch into messages. Instead, trigger that directly from the Presto split thread.

This has few advantages: 
 * Less context switches in the data path
 * Less number of objects active: just break down 1 single batch at a time.
 * Object for individual messages are requested and released to pool from a single thread, leading to more efficient pooling.

### CODE REVIEW

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by jiazhai** [comment]
@merlimat Here is the error in the report:
```

org.apache.pulsar.sql.presto.TestPulsarRecordCursor.setup

java.lang.NullPointerException
	at java.util.concurrent.ConcurrentLinkedQueue.checkNotNull(ConcurrentLinkedQueue.java:920)
	at java.util.concurrent.ConcurrentLinkedQueue.offer(ConcurrentLinkedQueue.java:327)
	at java.util.concurrent.ConcurrentLinkedQueue.add(ConcurrentLinkedQueue.java:297)
	at org.mockito.internal.stubbing.StubbedInvocationMatcher.addAnswer(StubbedInvocationMatcher.java:38)
	at org.mockito.internal.stubbing.InvocationContainerImpl.addAnswer(InvocationContainerImpl.java:65)
	at org.mockito.internal.stubbing.InvocationContainerImpl.setMethodForStubbing(InvocationContainerImpl.java:110)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:54)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:38)
	at org.powermock.api.mockito.repackaged.MethodInterceptorFilter.intercept(MethodInterceptorFilter.java:60)
	at org.apache.pulsar.client.admin.PulsarAdmin$$EnhancerByMockitoWithCGLIB$$b47fd21.namespaces(<generated>)
	at org.apache.pulsar.sql.presto.TestPulsarConnector.setup(TestPulsarConnector.java:765)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by codelipenghui** [comment]
@merlimat 
Could you please rebase this PR?
Is this PR need to onboard the 2.6.0 release?

**Comment by codelipenghui** [comment]
move to 2.7.0

**Pull request closed without merging**
