### PR TITLE
[CheckStyle]Enable pulsar-functions-worker checkstyle

### PR DESCRIPTION
**Pull request by gaozhangmin**
### Motivation

Enable CheckStyle plugin in 
pulsar-functions-worker

### Modifications

Fix the wrong code style in pulsar-functions-worker module.

### Verifying this change
The maven-checkstyle-plugin is added to pom.xml so
that the code style will be checked in mvn clean install.

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Review by BewareMyPower — COMMENTED** [review]
Please avoid the unnecessary indent changes, especially in `pom.xml`.

**Comment by gaozhangmin** [comment]
> ### Motivation
> Enable CheckStyle plugin in pulsar-functions-worker pulsar-functions-api-example pulsar-functions-local-runner-origin pulsar-functions-local-runner pulsar-functions-proto pulsar-functions-runtime pulsar-functions-runtime-all pulsar-functions-utils pulsar-functions-secrets
> 
> ### Modifications
> Fix the wrong code style in pulsar-functions-worker module.
> 
> ### Verifying this change
> The maven-checkstyle-plugin is added to pom.xml so that the code style will be checked in mvn clean install.
> 
> ### Documentation
> Check the box below or label this PR directly (if you have committer privilege).
> 
> Need to update docs?
> 
> * [ ]  `doc-required`
>   (If you need help on updating docs, create a doc issue)
> * [x]  `no-need-doc`
>   (Please explain why)
> * [ ]  `doc`
>   (If this PR contains doc changes)

**Comment by gaozhangmin** [comment]
ping @lhotari @Shoothzj @BewareMyPower

**Review by BewareMyPower — APPROVED** [review]

**Pull request merged**
