### PR TITLE
[Java Client] Use common request timeout handling for lookup requests and a fix a possible memory leak

### PR DESCRIPTION
**Pull request by lhotari**
### Motivation

In the existing solution there's a memory leak that occurs when a lookup request doesn't receive a reply.
The timeout handling doesn't remove the lookup request's future from pending requests.

https://github.com/apache/pulsar/blob/9db880eddb4bcd4478e24d5161ec022991cd5da7/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java#L615-L621

### Modifications

There's a common way to handle request timeouts in ClientCnx class . However, this method wasn't used for lookup requests.
This PR makes changes in lookup request timeout handling to use the common way which uses the `requestTimeoutQueue` based solution.
Another modification is to use `System.nanoTime()` for calculating elapsed time since `System.currentTimeMillis()` is not a stable way to calculate elapsed time.

### CODE REVIEW

**Review by merlimat — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
LGTM
great work

**Pull request merged**
