### PR TITLE
[improve][pip] PIP-301: Introduce LoadBalanceResources to unify the load-date CRUD

### PR DESCRIPTION
**Pull request by AnonHxy**
[DISCUSS thread](https://lists.apache.org/thread/7ngw9dc62tj2c4c5484dgsnlwgtstpbj)
[VOTE thread](https://lists.apache.org/thread/26dc8r6hnp7owdsq1hpzb48g8vlfrtxt)

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Comment by AnonHxy** [comment]
> LGTM.
> 
> But we also have broker-level load data too. Don't we want to add it here?

The broeker-level data(`/loadbalance/brokers/xxx`) is handled by `LockManager`.  Broker needs acquire a lock when starts. It's not a simple CRUD, so I think it's not suitable to put it here @heesung-sn

**Comment by AnonHxy** [comment]
@codelipenghui @merlimat @asafm @Technoboy-  PTAL

**Comment by Technoboy-** [comment]
Need to update the vote thread

**Comment by AnonHxy** [comment]
> Need to update the vote thread

OK. I will start the VOTE later.

**Review by congbobo184 — APPROVED** [review]

**Pull request merged**
