### PR TITLE
ENH: Add code formatter for Java

### PR DESCRIPTION
**Pull request by Licht-T**
### Motivation

Same as https://github.com/apache/incubator-pulsar/pull/1038.

### Modifications

Added Java code formatter.

### Result

- Codes is formatted when `mvn clean`.
- Codes format is validated when `mvn install`.

### CODE REVIEW

**Comment by maskit** [comment]
I'm basically +1 on this, but I'm not sure `clean` is an appropriate phase. People might be confused if code was modified when they run `mvn clean`. Also, if we are going to check code format on CI, we shouldn't format code during the build. Otherwise the check wouldn't work. Maybe we should use git hook (pre-commit) instead.

**Comment by sijie** [comment]
@Licht-T @merlimat - are we targeting this for 2.0? If not, can we move it to 2.1?

**Comment by sijie** [comment]
moved to 2.1. if it is required for 2.0, feel free to move it back.

**Comment by codelipenghui** [comment]
Close the PR since inactive for a long time, and it's not a critical issue fix or a new feature.

**Pull request closed without merging**
