### PR TITLE
[test] remove PowerMockito from the classpath and replace the usages with Mockito

### PR DESCRIPTION
**Pull request by nicoloboschi**
### Motivation
PowerMockito (mockito extension built on PowerMock) can be totally replaced with Mockito.
In this way we can remove the dependency `powermock-api-mockito2`.

We can also remove `powermock-module-testng` artifact (and in turn `powermock-core`) since it's not used anymore.
The only artifact that [doesn't have a simple replace path](https://stackoverflow.com/questions/40280918/what-do-i-use-instead-of-whitebox-in-mockito-2-2-to-set-fields) is `powermock-reflect` which will remain in the classpath.

The main reason behind the PowerMock usage reduction is that the project is semi-abandoned and it can easily break with newer jdk versions.

### Modifications

* Replaced PowerMockito with Mockito classes (just changing the packages)
* Replaced PowerMockito constructor mock with Mockito `MockedConstruction ` feature.
* Removed the module `powermock-module-testng` in favor of `powermock-reflect`

### Documentation

- [x] `no-need-doc`

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
Lgtm as far as CI passes.

Please note that this patch will make it harder to cherry pick patches.

Please take into consideration a port to at least branch 2.9 and 2.8

**Review by eolivelli — CHANGES_REQUESTED** [review]
Putting state into 'requested change' until CI passes

**Comment by nicoloboschi** [comment]
@eolivelli CI is green

**Comment by nicoloboschi** [comment]
@lhotari @Shoothzj @michaeljmarshall @codelipenghui PTAL

**Review by lhotari — APPROVED** [review]
Awesome!

**Review by Shoothzj — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]

**Pull request merged**
