### PR TITLE
[fix][auto-recovery] [branch-2.11] Fix metadata store deadlock due to BookkeeperInternalCallbacks.Processor 

### PR DESCRIPTION
**Pull request by horizonzy**
### Motivation
cherry-pick #21159 

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by poorbarcode — APPROVED** [review]

**Comment by horizonzy** [comment]
@hangc0276

**Pull request merged**
