### PR TITLE
fix potential NPE and repeated conditional test

### PR DESCRIPTION
**Pull request by ntysdd**
### Motivation

fix potential NPE and repeated conditional test

### Modifications

local changes

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### CODE REVIEW

**Comment by jiazhai** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Pull request merged**
