### PR TITLE
[Doc]--Update docs for how to delete data from namespace + reorg the admin API namespace doc

### PR DESCRIPTION
**Pull request by Huanli-Meng**
Fixes https://github.com/streamnative/pulsar/issues/1639

### Motivation
To specify how soon after message acknowledgement can we expect the message to be deleted - is it immediate or is there some asynchronous cleanup process.

### Modifications

1: Add "delete data from namespaces" for master release. Once the PR is approved, will sync update to previous releases.
2: Reorg the Admin API for namespace doc as some section titles are missed.

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@Huanli-Meng Please resolve the conflicts. Thanks.

**Review by sijie — APPROVED** [review]

**Comment by Huanli-Meng** [comment]
@codelipenghui I re-run the tests many times but the CI tests always fail. Could you please help fix it? Thanks

**Pull request merged**
