### PR TITLE
Fix unit test issue in BrokerServiceTest.java

### PR DESCRIPTION
**Pull request by codelipenghui**
### Motivation

Since #5599 merged, it introduce some conflict code with master branch, maybe the reason is #5599 not rebase with master

### Verifying this change

This is a test change

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
rerun java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by tuteng** [comment]
Add label release/2.5.1, due error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:testCompile (default-testCompile) on project pulsar-broker: Compilation failure: Compilation failure:
[ERROR] /pulsar/pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java:[949,86] cannot find symbol
[ERROR]   symbol:   method get(int)
[ERROR]   location: interface java.util.Collection<org.apache.pulsar.broker.service.Producer>
[ERROR] /pulsar/pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java:[951,24] cannot find symbol
[ERROR]   symbol:   method add(org.apache.pulsar.broker.service.Producer)
[ERROR]   location: variable producers of type java.util.concurrent.ConcurrentHashMap<java.lang.String,org.apache.pulsar.broker.service.Producer>
[ERROR] -> [Help 1]
```

**Pull request merged**
