### PR TITLE
[cleanup][test] Delete useless test

### PR DESCRIPTION
**Pull request by Technoboy-**
### Modifications
Delete these useless intergration tests

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by tisonkun — COMMENTED** [review]
How do you identify these tests as "useless"?

**Comment by Technoboy-** [comment]
> How do you identify these tests as "useless"?

Ah, it's pulsar-2.2~-2.5, we already not support these versions.

**Comment by tisonkun** [comment]
> we already not support these versions

@Technoboy- here we have one question: do we still keep compatible with those versions? These tests do sanity checks that new version clients can talk to old version servers, this is part of our compatibility promise.

We also have `pulsar-client-1x-base`. If we don't need to ensure compatibility use <= 2.8, we may not need to maintain those modules also.

What do you think?

**Comment by Technoboy-** [comment]
> > we already not support these versions
> 
> @Technoboy- here we have one question: do we still keep compatible with those versions? These tests do sanity checks that new version clients can talk to old version servers, this is part of our compatibility promise.
> 
> We also have `pulsar-client-1x-base`. If we don't need to ensure compatibility use <= 2.8, we may not need to maintain those modules also.
> 
> What do you think?

The reason for this PR is that when I was working on #21221, I found that some scripts in the test were no longer universal. I wanted to change them, but found that they had little practical significance. Therefore, I want to delete all the related tests in this PR. If it goes according to your opinion, indeed, they should all be deleted. However, we may need to discuss in the mail.

**Pull request closed without merging**
