### PR TITLE
[improve][branch-2.8]Upgrade the bk version to 4.14.7

### PR DESCRIPTION
**Pull request by horizonzy**
Fixes #xyz

Master Issue: #xyz

PIP: #xyz 

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by hangc0276 — CHANGES_REQUESTED** [review]
Please hold on to the upgrade due to the RocksDB issue.  https://github.com/apache/bookkeeper/issues/3734

**Comment by horizonzy** [comment]
> Please hold on to the upgrade due to the RocksDB issue. [apache/bookkeeper#3734](https://github.com/apache/bookkeeper/issues/3734)

The issue concerns the bookie server; upgrading the bookkeeper version is compatible with the old bookie server.

**Comment by hangc0276** [comment]
BookKeeper 4.14.7 has been released, we can use BookKeeper 4.14.7 directly.

**Review by hangc0276 — APPROVED** [review]

**Comment by hangc0276** [comment]
@horizonzy Would you please rebase branch-2.8?

**Comment by horizonzy** [comment]
> @horizonzy Would you please rebase branch-2.8?

Done

**Comment by dave2wave** [comment]
Branch 2.8 is EOL.

**Pull request closed without merging**
