### PR TITLE
[Issue #3726] Modify the usage of Connector CLI for better guidance

### LINKED ISSUE #3726: functions cli received HTTP 404 when trying to inspect a build-in I/O connector
**Describe the bug**

When trying to use `pulsar-admin functions` CLI (e.g. `getstatus`) for inspecting a submitted build-in I/O sink connector by following the tutorial for Pulsar IO, someone will receive HTTP 404 like follows:
```
$ bin/pulsar-admin functions getstatus \
>     --tenant public \
>     --namespace default \
>     --name test-sink
HTTP 404 Not Found

Reason: Function test-sink doesn't exist
```
However, use `pulsar-admin sink` CLI can get the correct result.

### PR DESCRIPTION
**Pull request by murong00**
### Motivation

Fixes #3726

### Modifications

Replace `functions` by `sink`.

### CODE REVIEW

**Comment by srkukarni** [comment]
run java8 tests
run cpp tests

**Comment by murong00** [comment]
@sijie Not found in version 2.3.0, just copy from the master and modify original_id, PTAL!

**Comment by murong00** [comment]
run cpp tests

**Comment by murong00** [comment]
@sijie Can this pull request being merged soon?

**Comment by sijie** [comment]
@murong00 done

**Pull request merged**
