### PR TITLE
[fix][broker]fix bug: fail to expose managed ledger client stats to prometheus if bookkeeperClientExposeStatsToPrometheus is true

### PR DESCRIPTION
**Pull request by HQebupt**
### Motivation
It failed to expose bookkeeper client managed ledger stats to prometheus if setting `bookkeeperClientExposeStatsToPrometheus=true` in `ServiceConfiguration`. Because creating BkClient ignore the `StatsLogger` and use the `NullStatsLogger.INSTANCE` as default.

```java
//class: org.apache.pulsar.broker.BookKeeperClientFactoryImpl
    @Override
    public BookKeeper create(ServiceConfiguration conf, ZooKeeper zkClient, EventLoopGroup eventLoopGroup,
                             Optional<Class<? extends EnsemblePlacementPolicy>> ensemblePlacementPolicyClass,
                             Map<String, Object> properties) throws IOException {
        return create(conf, zkClient, eventLoopGroup, ensemblePlacementPolicyClass, properties,
                NullStatsLogger.INSTANCE);
    }
```

### Modifications
Add `StatsLogger` into BookKeeperClientFactory when creating BkClient.

The screenshot below is the result of my verification.
image

### Verifying this change

- [x]  Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.
### Does this pull request potentially affect one of the following parts:

If `yes` was chosen, please highlight the changes

- Dependencies (does it add or upgrade a dependency): (no)
- The public API: (no)
- The schema: (no)
- The default values of configurations: (no)
- The wire protocol: (no)
- The rest endpoints: (no)
- The admin cli options: (no)
- Anything that affects deployment: (no)

### Documentation
Check the box below and label this PR (if you have committer privilege).

Need to update docs? 
- [x] `doc-not-needed`

### CODE REVIEW

**Review by gaozhangmin — APPROVED** [review]
Nice catch

**Review by horizonzy — APPROVED** [review]
lgtm.

**Review by codelipenghui — COMMENTED** [review]
@HQebupt Please help add a test to make sure the issue will not comeback. Thanks.

**Comment by HQebupt** [comment]
> @HQebupt Please help add a test to make sure the issue will not comeback. Thanks.

It is hard to add a unit test due to there is two kinds of new BookKeeper client instance.

**Review by Jason918 — APPROVED** [review]

**Comment by mattisonchao** [comment]
Hi, @HQebupt 

It looks like we have some conflict on branch-2.9. Could you please help to cherry-pick or push a new PR for it?

**Comment by BewareMyPower** [comment]
cherry-pick https://github.com/apache/pulsar/pull/16343 to branch-2.8 instead.

**Pull request merged**
