### PR TITLE
[Issue 7736][broker]Fix broker lookup return wrong url when specify advertised listener

### LINKED ISSUE #7736: Broker did not return correct url when client specify advertisedListenerName
**Describe the bug**
When client lookup the broker url for a new created topics (no one owns the bundle of the topic) with advertisedListenerName, the searchForCandidateBroker() function return the default advertiesed url instead of the url specified by advertisedListenerName if the candidateBroker is not self.

**To Reproduce**
1. Start broker with advertisedListeners setting, make sure the client can only connect to broker through the url specified by the advertisedListener.
2. Create a topic with 50 partitions and  use client to produce messages with correct advertisedListenerName.
3. For some partition topics, client got the default advertiesed url and failed to connect to broker.

**Expected behavior**
Client should get the correct url by the specified advertisedListenerName.

### PR DESCRIPTION
**Pull request by wangjialing218**
### Motivation

Fixes #7736

### Modifications

In function searchForCandidateBroker(), return the url according to advertisedListenerName when the candidateBroker is not self.

### CODE REVIEW

**Comment by sijie** [comment]
@wangjialing218 Can you write a simple test case?

**Comment by murong00** [comment]
@sijie @wolfstudy  Can this pr be cherry-picked to upcoming release 2.6.1, we also need this fix in our product env.

**Comment by wolfstudy** [comment]
> @sijie @wolfstudy Can this pr be cherry-picked to upcoming release 2.6.1, we also need this fix in our product env.

Sure, please make sure the Action CI pass, will cherry-pick this change to branch-2.6

**Comment by wolfstudy** [comment]
@sijie @jiazhai @codelipenghui PTAL thanks

**Comment by wolfstudy** [comment]
@wangjialing218 Can you merge the master code to fix CI error?

**Pull request merged**
