### PR TITLE
[feat][doc] Add native PHP client to third-party client matrix

### PR DESCRIPTION
**Pull request by ikilobyte**
### Motivation

*I have developed a php client.*

### Modifications

*Add Third-party Native PHP Client to the Doc.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [x] `doc` 
(Your PR contains doc changes)

### CODE REVIEW

**Comment by tuhaihe** [comment]
@ikilobyte Thanks for your contribution.

**Review by Anonymitaet — APPROVED** [review]

**Comment by Anonymitaet** [comment]
Thanks for your contribution! 

I've renamed your PR title to make it more descriptive.

The PR title will be the content of the release note and the commit message when it gets merged. 

Please follow the rules stated in the [Pulsar Pull Request Naming Guideline](https://docs.google.com/document/d/1d8Pw6ZbWk-_pCKdOmdvx9rnhPiyuxwq60_TrD68d7BA/edit#heading=h.wu6ygjne8e35). Thanks! 😊

**Comment by ikilobyte** [comment]
Thanks! 😊

**Comment by Anonymitaet** [comment]
@dave2wave does this client need to be renamed? (context: https://lists.apache.org/thread/c54wmgq9o7q5wg85wxxbgqb8rwk1v8nh)

**Comment by dave2wave** [comment]
> @dave2wave does this client need to be renamed? (context: https://lists.apache.org/thread/c54wmgq9o7q5wg85wxxbgqb8rwk1v8nh)

I think that this can proceed. I feel that the PMC will allow these links. Further cleanup should be done. We can discuss on the dev@ list which of these 3rd party client projects are defunct.

**Review by dave2wave — APPROVED** [review]

**Pull request merged**
