### PR TITLE
[Spotbugs] Enable spotbugs for pulsar functions

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <rxl@apache.org>

### Motivation

Enable spotbugs for pulsar functions

### Modifications

Enable spotbugs for pulsar functions

- [x] Instance
- [x] API
- [x] Java Examples
- [x] Localrun
- [x] Runtime All
- [x] Secrets

### CODE REVIEW

**Comment by wolfstudy** [comment]
@sijie @jiazhai @codelipenghui PTAL thanks

**Comment by codelipenghui** [comment]
@wolfstudy Please rebase to the master branch

**Comment by wolfstudy** [comment]
> @wolfstudy Please rebase to the master branch

ok, will process it

**Review by sijie — APPROVED** [review]

**Pull request merged**
