### PR TITLE
[clean code] clean unused method: getRangeConsumer

### PR DESCRIPTION
**Pull request by lordcheng10**
### Motivation
clean unused method: getRangeConsumer in class HashRangeAutoSplitStickyKeyConsumerSelector and ConsistentHashingStickyKeyConsumerSelector

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Comment by mattisonchao** [comment]
@lordcheng10 
This PR needs to wait for #13772 to be merged, then close and reopen it.

**Review by mattisonchao — APPROVED** [review]
LGTM +1

**Review by Jason918 — APPROVED** [review]

**Comment by lordcheng10** [comment]
ping

**Review by Shoothzj — APPROVED** [review]
need to remove the import

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@lordcheng10 Please rebase to the master branch

**Pull request merged**
