### PR TITLE
Update RESTFUL API for 2.4.2 release

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <rxl@apache.org>

### Modifications

- Update RESTFUL API for 2.4.2 release

docs are generated by the following command:

```
mvn -am -pl pulsar-broker install -DskipTests -Pswagger
mkdir -p site2/website/static/swagger/2.4.2/
cp pulsar-broker/target/docs/*.json site2/website/static/swagger/2.4.2/
```

### CODE REVIEW

**Comment by wolfstudy** [comment]
@tuteng @sijie PTAL, thanks.

**Comment by tuteng** [comment]
run integration tests

**Comment by wolfstudy** [comment]
run cpp tests

**Comment by wolfstudy** [comment]
run cpp tests

**Pull request merged**
