### PR TITLE
Match exception if connection just connected #15764

### LINKED ISSUE #15764: Flaky-test: ConnectionTimeoutTest.testLowTimeout
ConnectionTimeoutTest.testLowTimeout is flaky. It fails sporadically.

https://github.com/apache/pulsar/runs/6582172714

```
  Error:  testLowTimeout(org.apache.pulsar.client.impl.ConnectionTimeoutTest)  Time elapsed: 3.042 s  <<< FAILURE!
  java.lang.AssertionError: expected [class io.netty.channel.ConnectTimeoutException] but found [class io.netty.channel.StacklessClosedChannelException]
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.failNotEquals(Assert.java:1037)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
  	at org.testng.Assert.assertEquals(Assert.java:122)
  	at org.testng.Assert.assertEquals(Assert.java:617)
  	at org.apache.pulsar.client.impl.ConnectionTimeoutTest.testLowTimeout(ConnectionTimeoutTest.java:44)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by WJL3333**
Fixes #15764

see https://github.com/netty/netty/pull/10523

Documentation
- [X] doc-not-needed

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@WJL3333 
Please follow the rules below:
1. Doc label instructions: https://docs.google.com/document/d/1Qw7LHQdXWBW9t2-r-A7QdFDBwmZh6ytB4guwMoXHqc0/edit#
image
2. Pulsar Pull Request Naming Convention Guide: https://docs.google.com/document/d/1d8Pw6ZbWk-_pCKdOmdvx9rnhPiyuxwq60_TrD68d7BA/edit#heading=h.wu6ygjne8e35

**Review by lhotari — CHANGES_REQUESTED** [review]
This fix doesn't make sense. It makes the test pass, but the test itself is invalid and doesn't test the connection timeout in all cases. The original test is not correct.
I have addressed this in a change, which I'll push once the CI is unblocked (after #15846 has been merged).

**Comment by lhotari** [comment]
The problem with the original test is that it assumes that IP `192.0.2.1` is a "black hole". This is an assumption which doesn't hold when a firewall blocks such connections.

**Comment by WJL3333** [comment]
@lhotari so we need add more connection timeout condition in the origin test ?

**Pull request closed without merging**
