### PR TITLE
[Issue 6957][pulsar-io-debezium] Support CDC Connector for SqlServer

### LINKED ISSUE #6957: PulsarIO [Debezium] - Support MS SqlServer
This feature request will track work on creating a connector for SqlServer through the Debezium module.

### PR DESCRIPTION
**Pull request by huangdx0726**
Fixes #6957 

### Motivation

Add debezium Sqlserver source

### Modifications

Add debezium Sqlserver source

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by codelipenghui** [comment]
@huangdx0726 Would you please help take a look at the failed CI tests? Looks related to this PR.

**Comment by codelipenghui** [comment]
move to 2.7.0 first.

**Comment by codelipenghui** [comment]
@huangdx0726 Could you please take a look at the failed CI tests? looks related to the maven poms.

**Comment by sijie** [comment]
@huangdx0726 Can you rebase it to the latest master?

**Review by codelipenghui — APPROVED** [review]

**Comment by sijie** [comment]
@huangdx0726 I think the integration test you added failed. Can you check the following error?

```
05:52:23.218 [tc-okhttp-stream-869783420:org.apache.pulsar.tests.integration.utils.DockerUtils$2@257] ERROR org.apache.pulsar.tests.integration.utils.DockerUtils - DOCKER.exec(PulsarFunctionsProcessTest-xzzxp:cat debezium-sqlserver-init/inventory.sql | docker exec -i debezium-sqlserver-example bash -c '/opt/mssql-tools/bin/sqlcmd -U sa -P $SA_PASSWORD'): completed with non zero return code: 126
stdout: OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "cat debezium-sqlserver-init/inventory.sql | docker exec -i debezium-sqlserver-example bash -c '/opt/mssql-tools/bin/sqlcmd -U sa -P $SA_PASSWORD'": stat cat debezium-sqlserver-init/inventory.sql | docker exec -i debezium-sqlserver-example bash -c '/opt/mssql-tools/bin/sqlcmd -U sa -P $SA_PASSWORD': no such file or directory: unknown
```

**Comment by sijie** [comment]
Remove this from 2.7.0 release first. If you can fix the integration test before the release, we can include it. Otherwise, let's include it for 2.8.0 release.

**Review by tuteng — DISMISSED** [review]

**Comment by codelipenghui** [comment]
@huangdx0726 Could you please resolve the conflicts?

**Comment by jdunhamvrtx** [comment]
Hey Everyone, 
   Anything I can do to help this along? Seems it's *really* close.
-J

**Comment by huangdx0726** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by tisonkun** [comment]
I think this is resolved by https://github.com/apache/pulsar/pull/12256. Please open a new issue if it's not the case.

**Comment by tisonkun** [comment]
Sorry that we don't give a review in time :/

**Pull request closed without merging**
