### PR TITLE
[Doc] Add pulsar-admin command and fix inconsistencies

### PR DESCRIPTION
**Pull request by Anonymitaet**
Fix https://github.com/apache/pulsar/issues/5345

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@Jennifer88huang could you please help review? Thank you

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by Anonymitaet** [comment]
@codelipenghui thank you

**Comment by Anonymitaet** [comment]
run cpp tests

**Comment by Anonymitaet** [comment]
@aahmed-se thank you

**Pull request merged**
