### PR TITLE
[Issue 5387] Update Netty version for improving memory usage

### PR DESCRIPTION
**Pull request by equanz**
### Motivation

Want to improve memory usage to be able to create many PulsarClients and Consumers.
(Fix https://github.com/apache/pulsar/issues/5387)

### Modifications

Update Netty version to `4.1.34.Final` and netty-tcnative-boringssl-static version to `2.0.22.Final`.

In Netty community, memory increase issue(https://github.com/netty/netty/issues/8814) was reported (at `4.1.32.Final`). It was fixed by https://github.com/netty/netty/pull/8825 (at `4.1.34.Final`). 

When I apply `4.1.34.Final` then memory usage was decreased correctly.

### CODE REVIEW

**Comment by aahmed-se** [comment]
https://mvnrepository.com/artifact/io.netty/netty-all/4.1.42.Final is the latest release why not just update to that.

**Comment by equanz** [comment]
@aahmed-se 
Thank you for your review.
In https://github.com/netty/netty/issues/8814 issue, problem was occurred patch version update. So, update version chose just fixed one. Not for critical reason such as build failure.

As follow suggestion, I'll try to update to https://mvnrepository.com/artifact/io.netty/netty-all/4.1.42.Final.

**Comment by equanz** [comment]
Please take another look.

**Comment by merlimat** [comment]
@equanz Great catch on correlating #5387 with the netty memory usage issue. 

The netty upgrade is already part of #3613 which is also breaking down netty-all into individual modules.

**Comment by sijie** [comment]
The netty version is already upgraded as part of #3613

**Pull request closed without merging**
