### PR TITLE
[improve][broker] Reduce unnecessary persistence of markdelete

### PR DESCRIPTION
**Pull request by lordcheng10**
### Motivation
Reduce unnecessary persistence of markdelete：
1. When mdEntry.newPosition is equal to persistentMarkDeletePosition, this persistence should be skipped：
https://github.com/apache/pulsar/blob/36806853b5a445299d8f9a6ba89905c1915345a3/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L1971-L1980

It should be modified to:
```
if (persistentMarkDeletePosition != null
          && mdEntry.newPosition.compareTo(persistentMarkDeletePosition) <= 0)
```

2. When mdEntry.newPosition is equal to INPROGRESS_MARKDELETE_PERSIST_POSITION_UPDATER, this persistence should also be skipped：
https://github.com/apache/pulsar/blob/36806853b5a445299d8f9a6ba89905c1915345a3/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L1982-L1999

It should be modified to:
```
if (current != null && current.compareTo(mdEntry.newPosition) >= 0) 
```

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/lordcheng10/pulsar/pull/26

### CODE REVIEW

**Comment by lordcheng10** [comment]
@lhotari PTAL,thanks!

**Review by codelipenghui — COMMENTED** [review]
The change looks good me.

It's better to add a test since this looks like a boundary problem. We should have a test to enforce correct behavior

**Comment by lordcheng10** [comment]
> The change looks good me.
> 
> It's better to add a test since this looks like a boundary problem. We should have a test to enforce correct behavior

OK , I will fixed

**Review by lhotari — COMMENTED** [review]
This might impact persisting individual acks? Tests might be missing for this.

**Comment by lordcheng10** [comment]
> 1. persistentMarkDeletePosition

I will add test

**Comment by lordcheng10** [comment]
Close this PR.
I submitted this change to https://github.com/apache/pulsar/pull/18042 because they are the same issue.

**Pull request closed without merging**
