### PR TITLE
Support defining and validating schema on Python client

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Allow applications to declare the schema for messages in python client library.

The schema is used to perform validation against the topic schema and also
for serialization/deserialization

Added support for Bytes, String, JSON and Avro definitions.

The schema of a message can be easily defined as: 

```python
import pulsar.schema

class Example(pulsar.schema.Record):
    a = Integer()
    b = String()
    c = Long(default=5)
```

With that, one can create a producer/consumer. Eg: 

```python
producer = client.create_producer(
                    topic='my-topic',
                    schema=pulsar.schema.AvroSchema(Example)

producer.send(Example(a=1, b='hello'))
```

Type is also validated to ensure a producer will only send data of the same type.

TODOs (in separate PRs):
 * Add tests for schema compatibility across Python and Java
 * Documentation and examples
 * AUTO_CONSUME schema type

### CODE REVIEW

**Comment by merlimat** [comment]
run integration tests

**Comment by merlimat** [comment]
run integration tests

**Comment by merlimat** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by merlimat** [comment]
run integration tests

**Comment by merlimat** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by merlimat** [comment]
run java8 tests

**Pull request merged**
