### PR TITLE
[Issue 10546] fix sink/source exception stats

### LINKED ISSUE #10546: Sink status reports incorrect number of Exceptions
**Describe the bug**
If I have few exceptions in my Sink, while fetching the status from CLI command 
```./pulsar-admin sinks status --name my-pulsar-sink --namespace default --tenant public```

I can see exceptions in `latestSinkExceptions` but the counter `numSinkExceptions` remains 0. I am not sure whether I am misunderstood here or there is some genuine error. Sharing the sample output below.

**To Reproduce**
1. Put some record in Sink which it cannot process and throws Exception from the Sink Implementation.

**Expected behavior**
`numSinkExceptions` should be non-zero.

**Sample output**
```
{
  "numInstances" : 1,
  "numRunning" : 1,
  "instances" : [ {
    "instanceId" : 0,
    "status" : {
      "running" : true,
      "error" : "",
      "numRestarts" : 0,
      "numReadFromPulsar" : 100000,
      "numSystemExceptions" : 0,
      "latestSystemExceptions" : [ ],
      "numSinkExceptions" : 0,
      "latestSinkExceptions" : [ {
        "exceptionString" : "Failed to process message: 11:0:-1:3542",
        "timestampMs" : 1620797430555
      }, {
        "exceptionString" : "Failed to process message: 11:1:-1:19608",
        "timestampMs" : 1620797437509
      }, {
        "exceptionString" : "Failed to process message: 11:2:-1:2763",
        "timestampMs" : 1620797438087
      }, {
        "exceptionString" : "Failed to process message: 11:3:-1:480",
        "timestampMs" : 1620797438173
      }, {
        "exceptionString" : "Failed to process message: 11:4:-1:1985",
        "timestampMs" : 1620797438542
      }, {
        "exceptionString" : "Failed to process message: 11:5:-1:26902",
        "timestampMs" : 1620797443469
      }, {
        "exceptionString" : "Failed to process message: 11:6:-1:2201",
        "timestampMs" : 1620797443829
      }, {
        "exceptionString" : "Failed to process message: 11:7:-1:7575",
        "timestampMs" : 1620797445133
      }, {
        "exceptionString" : "Failed to process message: 11:8:-1:27939",
        "timestampMs" : 1620797449756
      }, {
        "exceptionString" : "Failed to process message: 11:9:-1:6830",
        "timestampMs" : 1620797450912
      } ],
      "numWrittenToSink" : 99990,
      "lastReceivedTime" : 1620797450938,
      "workerId" : "c-pulsar-cluster-1-fw-a4e8ce63c331-8080"
    }
  } ]
}
```

As we can see, exceptions are there but the counter is 0.

### PR DESCRIPTION
**Pull request by linlinnn**
Fixes #10546

### Motivation
fix sink/source exception stats

### CODE REVIEW

**Review by abhilashmandaliya — COMMENTED** [review]
Awesome @linlinnn . That was a super quick fix :-)

**Comment by abhilashmandaliya** [comment]
@eolivelli @lhotari PTAL

**Review by sijie — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
