### PR TITLE
[package management service] check service status before run commands

### PR DESCRIPTION
**Pull request by freeznet**
### Motivation

`pulsar-admin` runs packages management services commands, but if the broker is not enabled the service, it will throw NPE. 

The root cause is https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PackagesBase.java#L45-L47, the `PackagesManagement` might be null if the service is not enabled.

### Modifications

Check `isEnablePackagesManagement` before each internal request.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Comment by freeznet** [comment]
@nlu90 please help to review when you have time, thanks.

**Review by nlu90 — APPROVED** [review]
I think the change serves its purpose to fix the current NPE issue.

But as a general way to improve the code quality, is there any way to let broker admin reject any requests if the component is not turned on? Like some dynamic loading of rest endpoint? This can also be applied to endpoints such as functions, sources, and sinks.

**Comment by freeznet** [comment]
@nlu90 good idea, IIRC the functions API will return `UnsupportedOperationException` if no functions worker enabled, this reminds me that it might be helpful to improve the code quality with this PR.
I have changed this PR and removed some duplicating code, PTAL, thanks.

**Review by nlu90 — APPROVED** [review]
LGTM now

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
Depends by https://github.com/apache/pulsar/pull/16365

**Pull request merged**
