### PR TITLE
[improve][ci] Add pulsar-client test group

### PR DESCRIPTION
**Pull request by yaalsn**
### Motivation

`pulsar-client` test group is not in CI, but this module is important and we need to make sure of its quality.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/yaalsn/pulsar/pull/15

### CODE REVIEW

**Review by mattisonchao — APPROVED** [review]

**Review by poorbarcode — APPROVED** [review]

**Comment by mattisonchao** [comment]
@lhotari  Could you please take a look at this PR?

**Review by codelipenghui — APPROVED** [review]

**Comment by lhotari** [comment]
> @lhotari Could you please take a look at this PR?

@mattisonchao I didn't have time to review before this was merged.  /cc @codelipenghui 

> pulsar-client test group is not in CI, but this module is important and we need to make sure of its quality.

@yaalsn The pulsar-client module tests were run as part of the OTHER test group and continue to run as part of that group. I created PR #18339 to address that.

**Comment by lhotari** [comment]
I hope Pulsar CI changes like this could be reviewed carefully before merging so that we don't needlessly make changes. If gaps are detected, it's worth bringing up to discussion on dev mailing list or on [Pulsar slack on the #testing channel](https://apache-pulsar.slack.com/channels/testing).

**Pull request merged**
