### PR TITLE
Update cursor last active timestamp when reseting cursor 

### LINKED ISSUE #13165: refine cursor last active
**Is your enhancement request related to a problem? Please describe.**
We found that after turning on the automatic cleanup for inactive subscriptions, if only resetting a sub without continuous consumption, the sub will also be cleaned up. Among them, using pulsar-flink-connector for consumption is a typical scenario due to its strategy of committing offset when checkpoint is triggered regularly.

**Describe the solution you'd like**
I submit a pr as an attachment to supplement this situation so that `resetCursor` will also trigger the update of `updateLastActive`.

**Describe alternatives you've considered**
If the `resetCursor` can update the lasr active time is not recognized, we may need to add a flag to record the time of the last reset, but I think this may be a bit redundant.

### PR DESCRIPTION
**Pull request by wuzhanpeng**
Resolves #13165 

### Modifications
1. trigger last active time update after resetting cursor
2. add related test case

### Documentation

Need to update docs? 
  
- [x] `no-need-doc` 
  
Just a little function supplement, no need to update the document

### CODE REVIEW

**Review by hangc0276 — APPROVED** [review]

**Review by zymap — APPROVED** [review]

**Review by RobertIndie — APPROVED** [review]

**Review by Jason918 — APPROVED** [review]

**Comment by hangc0276** [comment]
@wuzhanpeng  Please rebase the master to fix the flaky test.

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
