### PR TITLE
[Functions] Completed work for PR #7555 to allow customizable function logging

### LINKED ISSUE #10205: [Functions] Need a way to enable debug log level in functions running in production
As mentioned in this issue: https://github.com/apache/pulsar/issues/3259
there is currently no way to change the log level of a function to debug level. 
For solving the issue here: https://github.com/apache/pulsar/issues/6054
I need to be able to enable debug logging in Pulsar functions to observe the permits behavior of `ConsumerImpl`. 
Only being able to see the permit behavior on the broker tells half of the story and is insufficient for finding the problem.

### PR DESCRIPTION
**Pull request by devinbost**
This PR completes the work started by @g0715158 in PR #7555 to allow customization of the Pulsar function log level. 
I created a new PR because it looked like the branch for that repo (`g0715158:master`) involved a change for a different issue, and Github indicated the repo had been deleted. (I was unable to find the original commits on that repo in a branch.) 

@g0715158 Please let me know if you'd like to create a branch with your changes so you can get credit for your work. (In that case, I'll delete this PR and add my commits to your branch.)

Fixes #10205

### CODE REVIEW

**Comment by devinbost** [comment]
Please verify these changes @jerrypeng @cdbartholomew @vaihtovirta @eolivelli

**Review by eolivelli — APPROVED** [review]
Very useful!

+1

**Comment by devinbost** [comment]
@eolivelli I made some additional changes to make this feature more robust. Please review the new changes.

**Review by eolivelli — APPROVED** [review]
Still great

**Comment by devinbost** [comment]
I tested this in production, and it works great. 
@merlimat @sijie ?

**Review by jerrypeng — APPROVED** [review]

**Comment by eolivelli** [comment]
@devinbost will this patch apply to branch-2.7?

Or does it need some dependencies?

**Comment by devinbost** [comment]
@eolivelli Yes, this applies to branch-2.7 and doesn't have any other dependencies.

**Comment by eolivelli** [comment]
cherry picked to branch-2.7

**Comment by Anonymitaet** [comment]
Hi @devinbost thanks for your great work. I'm adding docs for this PR but have some questions documented [here](https://docs.google.com/document/d/1FgeagvB7Nqefe5zxu--wKlEYzr3OoiOp3dWvEGGSRjM/edit), could you please take a look? Many thanks!

**Comment by devinbost** [comment]
@Anonymitaet Thanks for your help with the docs. I'll get this taken care of today.

**Comment by devinbost** [comment]
@Anonymitaet Please see #10617

**Comment by Anonymitaet** [comment]
@devinbost many thanks for your contribution. I've reviewed your doc PR, PTAL.

**Pull request merged**
