### PR TITLE
[Pulsar sql] Support keyValue Schema add integration test.

### PR DESCRIPTION
**Pull request by congbobo184**
## Motivation
Add the test for pulsar-sql support keyValue schema
## implement
Add the test
### Verifying this change
Add the test for it

Does this pull request potentially affect one of the following parts:
If yes was chosen, please highlight the changes

Dependencies (does it add or upgrade a dependency): (no)
The public API: (no)
The schema: (no)
The default values of configurations: (no)
The wire protocol: (no)
The rest endpoints: (no)
The admin cli options: (no)
Anything that affects deployment: (no)

### CODE REVIEW

**Review by sijie — APPROVED** [review]

**Review by sijie — CHANGES_REQUESTED** [review]
@congbobo184 Can you add an integration test to test KeyValue schema with both separate and inline modes?

**Comment by congbobo184** [comment]
> @congbobo184 Can you add an integration test to test KeyValue schema with both separate and inline modes?

OK

**Review by jiazhai — APPROVED** [review]

**Comment by congbobo184** [comment]
https://github.com/apache/pulsar/pull/8422 has solve this problem, so this PR only add the test

**Comment by hnail** [comment]
> #8422 has solve this problem, so this PR only add the test

I added `TestPulsarRecordCursor#TestKeyValueStructSchema` and `TestPulsarRecordCursor#TestKeyValuePrimitiveSchema ` in #8422 , which contains `KeyValueEncodingType.INLINE` and `KeyValueEncodingType.SEPARATED` modes unit test , but lack of integration test ?

**Comment by congbobo184** [comment]
> > #8422 has solve this problem, so this PR only add the test
> 
> I added `TestPulsarRecordCursor#TestKeyValueStructSchema` and `TestPulsarRecordCursor#TestKeyValuePrimitiveSchema ` in #8422 , which contains `KeyValueEncodingType.INLINE` and `KeyValueEncodingType.SEPARATED` modes unit test , but lack of integration test ?

Yes, it lack integration test. If you want to add the test, i will close this PR.

**Comment by hnail** [comment]
> > > #8422 has solve this problem, so this PR only add the test
> > 
> > 
> > I added `TestPulsarRecordCursor#TestKeyValueStructSchema` and `TestPulsarRecordCursor#TestKeyValuePrimitiveSchema ` in #8422 , which contains `KeyValueEncodingType.INLINE` and `KeyValueEncodingType.SEPARATED` modes unit test , but lack of integration test ?
> 
> Yes, it lack integration test. If you want to add the test, i will close this PR.

> > > #8422 has solve this problem, so this PR only add the test
> > 
> > 
> > I added `TestPulsarRecordCursor#TestKeyValueStructSchema` and `TestPulsarRecordCursor#TestKeyValuePrimitiveSchema ` in #8422 , which contains `KeyValueEncodingType.INLINE` and `KeyValueEncodingType.SEPARATED` modes unit test , but lack of integration test ?
> 
> Yes, it lack integration test. If you want to add the test, i will close this PR.

thanks replay , I'm not working the integration tests.

**Comment by congbobo184** [comment]
@hnail OK, i will work in this pr. thanks reply.

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@sijie Please help take a look at this PR again. @congbobo184 Could you please check the branch-2.7? I think branch-2.7 does not work. Since we can't cherry-pick #8422, could you please create a PR to fix the branch-2.7?

**Review by sijie — APPROVED** [review]

**Comment by codelipenghui** [comment]
https://github.com/apache/pulsar/pull/9685 is fixing the branch-2.7

**Pull request merged**
