### PR TITLE
Add support in cpp client for 1 partitioned topic

### PR DESCRIPTION
**Pull request by jiazhai**
### Motivation

IN PR #4883, we support 1 partitioned topic producer/consumer in java client. this is for Cpp client support.

### Modifications
- change cpp client 
- add unit test

### Verifying this change
New added Ut Passed

### CODE REVIEW

**Comment by sijie** [comment]
run cpp tests

**Comment by sijie** [comment]
retest this please

**Comment by jiazhai** [comment]
run cpp tests

**Comment by jiazhai** [comment]
run cpp tests
run java8 tests

**Comment by sijie** [comment]
run cpp tests

**Pull request merged**
