### PR TITLE
[Test] Migrate deprecated Matchers to ArgumentMatchers

### PR DESCRIPTION
**Pull request by liketic**
Migrate deprecated Matchers to ArgumentMatchers.

### CODE REVIEW

**Comment by liketic** [comment]
run java8 tests
run integration tests

**Comment by liketic** [comment]
run cpp tests

**Comment by liketic** [comment]
run java8 tests
run integration tests
run cpp tests

**Comment by liketic** [comment]
run java8 tests
run integration tests
run cpp tests

**Comment by liketic** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Pull request merged**
