### PR TITLE
Update missing import libs in function-develop.md

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <rxl@apache.org>

### Modifications

- Add import libs for `WordCountFunction`
- Add import libs for `JavaNativeExclamationFunction `
- Add import libs for `ExclamationFunction `

### CODE REVIEW

**Comment by wolfstudy** [comment]
@Jennifer88huang PTAL

**Comment by wolfstudy** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
run  java8 tests

**Comment by wolfstudy** [comment]
run java8 tests

**Pull request merged**
