### PR TITLE
[Issue 5541] cpp and python API: consumer and reader seek

### LINKED ISSUE #5541: Python API: seek(eventtime)
**Is your feature request related to a problem? Please describe.**
Feature-parity between APIs: Java Consumer and Reader have [`seek(messageId)`](https://github.com/apache/pulsar/blob/master/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java#L319) and [`seek(timestamp)`](https://github.com/apache/pulsar/blob/master/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java#L327), but Python has only [`seek(messageId)`](https://pulsar.apache.org/api/python/#pulsar.Consumer.seek) in Consumer, and nothing in Reader.

**Describe the solution you'd like**
Add a new method to Consumer and Reader to seek by timestamp.  Or it could test the type of the value passed, or have different named arguments.

**Describe alternatives you've considered**
N/A

**Additional context**
Use cases are given in #5537 - e.g. rewind a reader to start at a given time.

### PR DESCRIPTION
**Pull request by candlerb**
Updates the cpp and Python APIs:

* Consumer seek(): overload to accept timestamp as well as MessageID
* Reader gains seek()

Fixes #5541

### Motivation

Feature parity between cpp and Python APIs and Java API.  The Java API already has overloaded seek() on both Consumer and Reader.

Some use cases for Reader.seek(timestamp) described in #5537

### Modifications

* cpp Consumer: overload seek() and seekAsync() to accept uint64_t timestamp
* cpp Reader: add overloaded seek() and seekAsync()
* expose these to Python API in the same way

### Verifying this change

- [X] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:

  - Added basic tests in Python which exercise Consumer seek(timestamp), Reader seek(messageId), Reader seek(timestamp)

~~Note to reviewer: test just uses seek(0) to seek to the first message. It would be better if the messages had distinct publish timestamps so that it would seek to a particular message.  Is there a way to mock these out? Otherwise I'd need a sleep(2) between messages to ensure the timestamps were spaced apart~~ Since publish timestamps have millisecond resolution, I've updated the test to seek to actual times.  Waiting on CI to see if this works as expected, without buffering issues.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - The public API: yes: adds overloaded variant of seek() to Consumer, adds new seek() to Reader.  Should be backwards compatible.

Note to reviewer: in python, the single parameter of the seek() function is called "messageid", but this change means it can also be an integer timestamp - that is, it's overloaded on the type of the value provided (just like Java and cpp).  As long as it's used as a positional arg it works, but it might be considered confusing.

An alternative would be to have a separate methods, e.g. `seek()` and `seek_time()`

### Documentation

  - Does this pull request introduce a new feature? yes
  - If yes, how is the feature documented? JavaDocs

### CODE REVIEW

**Comment by candlerb** [comment]
I can't see why the Java 8 unit tests failed, as I didn't change anything in Java.  Fragile test?

```
<<< FAILURE! - in org.apache.pulsar.functions.worker.PulsarFunctionE2ESecurityTest
<<< FAILURE! - in org.apache.pulsar.broker.stats.PrometheusMetricsTest
```

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
@candlerb yes the tests are fragile we are working to improve them

**Comment by candlerb** [comment]
More unrelated test failures:

```
[140/160] ConsumerStatBuild timed out (after 300 minutes). Marking the build as aborted.
```

```
2019-11-02\T\23:20:03.133 [ERROR] testAuthorizationWithAnonymousUser(org.apache.pulsar.functions.worker.PulsarFunctionE2ESecurityTest)  Time elapsed: 300.188 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.functions.worker.PulsarFunctionE2ESecurityTest.testAuthorizationWithAnonymousUser() didn't finish within the time-out 300000
```

**Comment by aahmed-se** [comment]
run cpp tests
run java8 tests

**Comment by candlerb** [comment]
I think this is now ready for code review please.

There are a several commits which I can squash if you like, or you can do it.

**Comment by candlerb** [comment]
Regarding the main documentation site: I can't see the ability to seek described anywhere at the moment.

1. Should the [clients](https://pulsar.apache.org/docs/en/next/concepts-clients/) page mention that consumers and readers can `seek()`?
2. It's not immediately obvious to me what happens when a consumer does a seek on a long-lived topic, especially if there are multiple consumers sharing the subscription.  Are all messages prior to the seek point marked as "acknowledged", and all messages from the seek point onwards marked as "unacknowledged"?  This relates to [message retention and expiry](https://pulsar.apache.org/docs/en/next/concepts-messaging/#message-retention-and-expiry).

**Comment by candlerb** [comment]
Again appears to be unrelated failure.

```
...
[100%] Built target main
---- Testing Pulsar C++ client using image apachepulsar/pulsar-build:ubuntu-16.04 (type --help for more options)
ubuntu-16.04: Pulling from apachepulsar/pulsar-build
Digest: sha256:d03f66e312923a5e84936d92cfa0af6c95977e5cd4ecd4edb42aa808d543eeab
Status: Image is up to date for apachepulsar/pulsar-build:ubuntu-16.04
docker.io/apachepulsar/pulsar-build:ubuntu-16.04
doing start standalone ...
starting standalone, logging to /tmp/pulsar-test-dist/logs/pulsar-standalone-0ba43a2a86b4.log
-- Wait for Pulsar service to be ready
-- Pulsar service is ready -- Configure permissions
-- Ready to start tests
/pulsar/pulsar-client-cpp/tests /pulsar/pulsar-client-cpp
---- Run unit tests in parallel
[0/160] Running tests...
...
[138/160] BasicEndToEndTest.testRSAEncryption (35336 ms)
[139/160] BlockingQueueTest.testReserveBuild timed out (after 300 minutes). Marking the build as aborted.
Build was aborted
Archiving artifacts
Recording test results
None of the test reports contained any result
Setting status of 6504a5113442c8a868840ca7361703f418f4e9bd to FAILURE with url https://builds.apache.org/job/pulsar_precommit_cpp/10418/ and message: 'FAILURE
 '
Using context: Jenkins: C++ / Python Tests
Finished: ABORTED
```

**Comment by candlerb** [comment]
run cpp tests

**Comment by candlerb** [comment]
I have the power :-)

**Comment by candlerb** [comment]
I've managed to setup local dev environment, and the python test_seek passes locally.

**Comment by candlerb** [comment]
run java8 tests

This time the C++ / Python tests succeeded (yay!) but Java failed.

**Comment by candlerb** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by skyrocknroll** [comment]
run integration tests

**Pull request merged**
