### PR TITLE
[fix][doc] SVG files and references

### LINKED ISSUE #17960: [BUG] Site build consistently fails
@merlimat @Anonymitaet @urfreespace @momo-jun 

Since @DaveDuggins doesn't upload these SVG files, the site build is currently broken: https://github.com/apache/pulsar-site/actions/runs/3204572728/jobs/5236018179.

If @DaveDuggins can provide the files, I'm glad to help with submitting a patch. Otherwise, we may firstly revert this commit.

_Originally posted by @tisonkun in https://github.com/apache/pulsar/pull/17863#discussion_r990174850_

### PR DESCRIPTION
**Pull request by tisonkun**
* This closes #17963.
* This closes #17960.

### Documentation

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: docs only.

### CODE REVIEW

**Comment by tisonkun** [comment]
@Anonymitaet @SignorMercurio currently the doc site suffers issues beyond the SVG files...See https://github.com/apache/pulsar/pull/17991/commits/6e9be94d38ad363679be556ce53198e3f2c4199c that may be caused by careless review.

And please help with fixing:

image

It seems something related to recent changes on release notes.

**Comment by tisonkun** [comment]
Those files removed by https://github.com/apache/pulsar-site/commit/5ca72cce0d039e3bf95099fa5fb8249e00f2a3de.

**Comment by tisonkun** [comment]
Fixed. That's another automatic issue.

**Comment by tisonkun** [comment]
image

Confirm site properly build and preview.

**Comment by tisonkun** [comment]
cc @urfreespace @Anonymitaet @momo-jun @DaveDuggins

**Review by Anonymitaet — APPROVED** [review]

**Review by momo-jun — APPROVED** [review]

**Review by urfreespace — APPROVED** [review]

**Pull request merged**
