### PR TITLE
[fix][proxy] Fix connection read timeout handling in Pulsar Proxy

### PR DESCRIPTION
**Pull request by lhotari**
### Motivation

- The behavior of the custom ProxyReadTimeoutHandler is not defined in any way and based on the code will result in bad behavior and proxy connections being closed

### Modifications

- Remove ProxyReadTimeoutHandler that was added as part of Zero copy support (#15678)
  - replace with a solution where readTimeoutHandler is remove from the pipeline

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by michaeljmarshall — APPROVED** [review]
LGTM

**Review by eolivelli — APPROVED** [review]
I agree

+1

**Review by nodece — APPROVED** [review]

**Review by coderzc — APPROVED** [review]

**Comment by michaeljmarshall** [comment]
Test failure looks potentially related to the PR:

```
  Error:  Tests run: 17, Failures: 1, Errors: 0, Skipped: 5, Time elapsed: 124.408 s <<< FAILURE! - in org.apache.pulsar.broker.service.TopicTerminationTest
  Error:  testTerminateWhilePublishing(org.apache.pulsar.broker.service.TopicTerminationTest)  Time elapsed: 20.039 s  <<< FAILURE!
  org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.broker.service.TopicTerminationTest.testTerminateWhilePublishing() didn't finish within the time-out 20000
  	at java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method)
  	at java.base@17.0.6/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
  	at java.base@17.0.6/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
  	at java.base@17.0.6/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
  	at java.base@17.0.6/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
  	at java.base@17.0.6/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
  	at java.base@17.0.6/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2072)
  	at app//org.apache.pulsar.broker.service.TopicTerminationTest.testTerminateWhilePublishing(TopicTerminationTest.java:172)
  	at java.base@17.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base@17.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base@17.0.6/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:568)
  	at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base@17.0.6/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base@17.0.6/java.lang.Thread.run(Thread.java:833)
```

**Comment by lhotari** [comment]
> Test failure looks potentially related to the PR:
> 
> ```
>   Error:  Tests run: 17, Failures: 1, Errors: 0, Skipped: 5, Time elapsed: 124.408 s <<< FAILURE! - in org.apache.pulsar.broker.service.TopicTerminationTest

@michaeljmarshall It's most likely yet another flaky one since this PR contains only proxy changes. Broker tests don't use the proxy.

**Pull request merged**
