### PR TITLE
[fix] [broker] add timeout for health check read.

### LINKED ISSUE #21989: [Bug] Resource Leak when do health check.
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

master

### Minimal reproduce step

We will do the health check for the cluster by rest api `org.apache.pulsar.broker.admin.impl.BrokersBase#healthCheck` every 1 min.  But recently we meet a case that the health check fail.
```
bin/pulsar-admin --admin-url http://XXX brokers healthcheck
```
image

There is no any error log in the broker log, the random message has been produced to the health-check topic, but the reader fail to read it out, so the logic stuck at  
```
org.apache.pulsar.broker.admin.impl.BrokersBase#healthCheckRecursiveReadNext
```
, which result into the created producers and readers can't be closed, and the scheduled async tasks can't be completed as well, and the number of these objects increase as time goes by.
For example:
`bin/pulsar-admin topics stats persistent://pulsar/XXX/healthcheck`
image

### What did you expect to see?

1

### What did you see instead?

1

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by thetumbled**
Fixes #21989

### Motivation
There could be cases that the health-check message is lost or the reader just can't read the expected message for any reason, which will result into the producers and readers can't be closed and therefore the resource leak problem occur.

### Modifications
Add timeout for health check read operation.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/thetumbled/pulsar/pull/39

### CODE REVIEW

**Comment by thetumbled** [comment]
PTAL, thanks. @mattisonchao @lhotari

**Review by lhotari — APPROVED** [review]
LGTM. Good work @thetumbled

**Review by poorbarcode — APPROVED** [review]
LGTM. @thetumbled could you add a test for this case?

**Comment by thetumbled** [comment]
> LGTM. @thetumbled could you add a test for this case?

Done.

**Pull request merged**
