### PR TITLE
[fix][test] Flakey-test : Remove `null` assignment to Pulsar insntance in `MockedPulsarServiceBaseTest`

### PR DESCRIPTION
**Pull request by JooHyukKim**
Fixes : apache/pulsar#20553

### Motivation

Fixes a flakey test scenario.

### Modifications

- Fix flakey test by have `null`-check on Pulsar instance before invocation inside `SimpleProducerConsumerTest.rest()`

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/JooHyukKim/pulsar/pull/8

### CODE REVIEW

**Review by Technoboy- — APPROVED** [review]

**Comment by JooHyukKim** [comment]
Failures

- ClusterMigrationTest.testClusterMigrationWithReplicationBacklog:459 expected [false] but found [true]
-  MetadataStoreTest.testExistsDistributed:712 expected [true] but found [false]

**Comment by JooHyukKim** [comment]
## NOTE

I will temporarily turn this into draft, because debugging a test failure in it is taking longer than expected to fix message 
 `ClusterMigrationTest.testClusterMigrationWithReplicationBacklog` with paramter `[true, SuscriptionType.Shared]`.

**Pull request closed without merging**
