### PR TITLE
In ZK 3.4.13 the elapsed time is not anymore based on System.currentTimeMillis()

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

In ZK dashboard, the latency metrics are showing wrong values (eg: 48 years). 

The problem is that we rely on AspectJ to get access to ZK internals and add instrumentation. The "request start" timestamp in ZK 3.4.13 has been changed from using `System.currentTimeMillis()` to `System.nanoTime() / 100000`. 

We need to change the timestamp we use for end operation as well.

### CODE REVIEW

**Comment by merlimat** [comment]
run cpp tests

**Comment by merlimat** [comment]
run cpp tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run cpp tests

**Comment by sijie** [comment]
run cpp tests

**Pull request merged**
