### PR TITLE
[Doc] Add contents for *Get Started (Schema)*

### PR DESCRIPTION
**Pull request by Anonymitaet**
Structure of Schema Chapter: https://github.com/apache/pulsar/issues/4789

@sijie could you please help review?

### CODE REVIEW

**Comment by sijie** [comment]
run java8 tests
run cpp tests

**Comment by Anonymitaet** [comment]
run java8 tests
run cpp tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by Anonymitaet** [comment]
run java8 tests

**Pull request merged**
