### PR TITLE
resolve a null pointer ex

### PR DESCRIPTION
**Pull request by qqdsx**
### Motivation

When i want to get a specific property, it give a null pointer error.I know that i should use "getProperties()" firstly, but i think it would be better if I used this function directly.

### Modifications

Only changed this one function.

### CODE REVIEW

**Comment by lovelle** [comment]
Hi! What about adding a new method which returns a Optional?

**Comment by qqdsx** [comment]
> Hi! What about adding a new method which returns a Optional?

Maybe it doesn't seem to fit the programming style of this module.

**Comment by qqdsx** [comment]
> ### Motivation
> When i want to get a specific property, it give a null pointer error.I know that i should use "getProperties()" firstly, but i think it would be better if I used this function directly.
> 
> ### Modifications
> Only changed this one function.

run integration Tests

**Comment by qqdsx** [comment]
run java8 tests

**Comment by qqdsx** [comment]
run Integration Tests

**Comment by sijie** [comment]
run integration tests

**Comment by qqdsx** [comment]
run integration tests

**Comment by sijie** [comment]
@qqdsx please rebase your branch to latest master to include the fix in #4387

**Comment by qqdsx** [comment]
> @qqdsx please rebase your branch to latest master to include the fix in #4387

ok

**Pull request merged**
