### PR TITLE
Fixed hasMessageAvailable() with empty topic

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

When the topic is empty, the `Reader.hasMessageAvailable()` can return incorrect results if the reader is started on latest. The main issue is that we are not associating the last message in topic with the "real" position of the reader.

### CODE REVIEW

**Review by jerrypeng — APPROVED** [review]

**Review by sijie — APPROVED** [review]

**Review by wolfstudy — APPROVED** [review]

**Comment by merlimat** [comment]
Fixed in #9652

**Pull request closed without merging**
