### PR TITLE
replace deprecated function of TopicPoliciesTest

### PR DESCRIPTION
**Pull request by suiyuzeng**
### Motivation

*replace deprecated function of TopicPoliciesTest.*

### Modifications

*replace deprecated function of org.apache.pulsar.client.admin.Topics whit org.apache.pulsar.client.admin.TopicPolicies in TopicPoliciesTest.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.
  - *olny change unit test*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
   olny change unit test
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Review by Jason918 — APPROVED** [review]

**Comment by Anonymitaet** [comment]
Hi  @suiyuzeng 
when submitting a PR, can you help provide a doc label (tick the box) in the [PR template which contains info about doc](https://github.com/apache/pulsar/blob/master/.github/PULL_REQUEST_TEMPLATE.md#documentation)? This helps others know more about the changes. Thanks
Documentation

**Comment by suiyuzeng** [comment]
> Hi @suiyuzeng when submitting a PR, can you help provide a doc label (tick the box) in the [PR template which contains info about doc](https://github.com/apache/pulsar/blob/master/.github/PULL_REQUEST_TEMPLATE.md#documentation)? This helps others know more about the changes. Thanks Documentation

ok, i will add the doc lable. Thanks~

**Review by codelipenghui — APPROVED** [review]

**Comment by Anonymitaet** [comment]
@suiyuzeng 
image

**Comment by codelipenghui** [comment]
@suiyuzeng Could you please help resolve the conflicts?

**Comment by suiyuzeng** [comment]
> @suiyuzeng Could you please help resolve the conflicts?

done

**Pull request merged**
