### PR TITLE
[Issue 6170][functions] add custom property option to functions

### LINKED ISSUE #6170: Support system env var as functions parameters
**Is your feature request related to a problem? Please describe.**
Hi, I'd like to use YAML functions configurations files to pass creds to functions, but I still want use versioned YAML configurations file without have creds in repo.

**Describe the solution you'd like**
Something in the YAML description that uses `runtimeFlags: -Denv1=${SYSTEM_ENV1}...`

### PR DESCRIPTION
**Pull request by nlu90**
Fixes #6170

### Motivation
Allow users set custom system properties while submitting functions. This can be used to pass credentials via system property.

### Modifications

- pulsar-admin client tool to accept multiple `--custom-property` options while creating the function
- function's java runtime to append these provided properties.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): no
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no
  - The rest endpoints: no
  - **The admin cli options: yes**
  - Anything that affects deployment: no

### Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by nlu90** [comment]
Now we can submit a function with multiple custom properties as follows:

```
./bin/pulsar-admin functions create \
--custom-property prop1="hello_world" --custom-property success=1 \
--jar ./pulsar-functions/java-examples/target/pulsar-functions-api-examples.jar \
--classname org.apache.pulsar.functions.api.examples.ExclamationFunction \
--tenant public --namespace default --name exclamation \
--inputs persistent://public/default/my-topic \
--output persistent://public/default/exclamation
```

**Comment by nlu90** [comment]
After a discussion with @sijie , the way this options works is as follows now:

```
./bin/pulsar-admin functions create \
--custom-property prop1=PROP1_VALUE --custom-property prop2=PROP2_VALUE \
--jar ./pulsar-functions/java-examples/target/pulsar-functions-api-examples.jar \
--classname org.apache.pulsar.functions.api.examples.ExclamationFunction \
--tenant public --namespace default --name exclamation \
--inputs persistent://public/default/my-topic \
--output persistent://public/default/exclamation
```

both `PROP1_VALUE` and `PROP2_VALUE` would be replaced with the actual system property value when the function process is being started.

**Comment by KannarFr** [comment]
@nlu90 Hi, thanks for the work you did here :).

* So PROP2_VALUE must be a system env var? What if it's undefined? Does the system throws an exception on boot?

* All these options are defined using `pulsar-admin` with arguments. Does the creation via YAML function configuration supports these features?

**Comment by nlu90** [comment]
@KannarFr Thanks for your feedback

- I added check for whether the property is set in broker/worker. If it's not set, an `IllegalArgumentException` will be thrown and the function submission will be failed.

- Yes, this change also works with YAML configuration. For my previously example submission command, you can also use the following YAML file as a configuration file to submit:
```yaml
jar: ./pulsar-functions/java-examples/target/pulsar-functions-api-examples.jar
className: org.apache.pulsar.functions.api.examples.ExclamationFunction
tenant: public
namespace: default
name: exclamation
customProperties: 
  - prop=HELLO
inputs: 
  - persistent://public/default/my-topic
output: persistent://public/default/exclamation
```
and the submission command is:
```bash
./bin/pulsar-admin functions create --function-config-file ~/func-conf.yaml
```

**Comment by sijie** [comment]
@nlu90 the change looks very good. although I think it might be worth thinking of the extensibility of this approach. We might be looking into some more generic variable binding approach that allows user dynamically generating the properties or values through variable bindings. [Serverless](https://serverless.com/framework/docs/providers/aws/guide/variables/#referencing-environment-variables) provides a good example of how to load variable bindings through different formats (e.g. environment variables,  cli options, and etc).

**Comment by nlu90** [comment]
@sijie We can create a new issue for the yaml file variable extension feature and add it in a separate PR.

**Comment by sijie** [comment]
@nlu90 sounds good. do you want to create an issue for that?

**Comment by sijie** [comment]
@nlu90 actually looked into the description of #6170, I think what @KannarFr is looking for might be similar to a variable binding approach. Maybe let's ask @KannarFr for some clarifications.

**Comment by KannarFr** [comment]
The goal is to use system env var defined and pass them to functions via
the yaml configuration file. Like myProp: $MY_PROP.

Le mar. 18 févr. 2020 à 20:40, Sijie Guo <notifications@github.com> a
écrit :

**Comment by nlu90** [comment]
Hi @KannarFr, Just want to confirm if the following solution meet your needs (Notice the last line of `customRuntimeOptions`):

```yaml
tenant: "test"
namespace: "test-namespace"
name: "example"
className: "org.apache.pulsar.functions.api.examples.ExclamationFunction"
inputs: ["test_src"]
userConfig:
  "PublishTopic": "test_result"
output: "test_result"
autoAck: true
parallelism: 1
customRuntimeOptions: "-DmyProp=${MY_PROP}"
```

and when you create function with this yaml file, the variable `${MY_PROP}` will be automatically replaced with the actual system property value.

Let me know your thoughts.

**Comment by KannarFr** [comment]
That's it! All seems perfect then.

**Comment by nlu90** [comment]
@sijie  @KannarFr Now you can submit a function with the following yaml file:

```yaml
jar: ./pulsar-functions/java-examples/target/pulsar-functions-api-examples.jar
className: org.apache.pulsar.functions.api.examples.ExclamationFunction
tenant: public
namespace: default
name: exclamation
inputs:
  - persistent://public/default/my-topic
output: persistent://public/default/exclamation
customRuntimeOptions: "-Dprop1=${MY_PROP1} -Dprop2=${MY_PROP2}"
```

One more question is currently if fetch function info with the cli, it will show the actual value of `${MY_PROP1}` and `${MY_PROP2}`, is this expected? Or should we hide the actual value in the cli result?

**Comment by KannarFr** [comment]
@nlu90 Well considering logs are often exported to external services, I think we must hide them from logs. Thats being said, we can log the env var name like: ```injecting $PROP as prop``` foreach prop. WDYT?

**Comment by nlu90** [comment]
@KannarFr Now no actual variable value will be logged into files.

**Comment by KannarFr** [comment]
@nlu90 Perfect! Thanks for all the work you did here :).

**Comment by KannarFr** [comment]
@sijie can we merge this?

**Comment by KannarFr** [comment]
@nlu90 oh, there few tests issues, can you check them?

**Comment by KannarFr** [comment]
@sijie Can you merge it? :)

**Comment by KannarFr** [comment]
What is the status of this PR?

**Comment by nlu90** [comment]
@KannarFr Sorry for the late reply, I was busy with some other projects.

After a discussion with @sijie , now the changes enable you put the env variable in `userConfig` and get the actual value via `context.getUserConfigValue`

an example yaml would be:
```yaml
jar: ./pulsar-functions/java-examples/target/pulsar-functions-api-examples.jar
className: org.apache.pulsar.functions.api.examples.ExclamationFunction
tenant: public
namespace: default
name: exclamation
inputs:
  - persistent://public/default/my-topic
output: persistent://public/default/exclamation
userConfig:
  "prop1": "$MY_PROP"
```

and you can access the actual value for `prop1` in your function code like this:
`context.getUserConfigValue("prop1")`

**Comment by KannarFr** [comment]
@nlu90 Thanks for your answer.

So 

```
  "prop1": "$MY_PROP"
```

reads `$MY_PROP` from system env vars? Right?

**Comment by nlu90** [comment]
> @nlu90 Thanks for your answer.
> 
> So
> 
> ```
>   "prop1": "$MY_PROP"
> ```
> 
> reads `$MY_PROP` from system env vars? Right?

Yes.

**Comment by KannarFr** [comment]
Awesome!

**Comment by Anonymitaet** [comment]
Docs have been added [here](https://streamnative.io/docs/latest/process/pulsar-functions/develop/feature#user-config).
Will copy to Pulsar later.

**Pull request merged**
