### PR TITLE
[branch-2.6] update to stable version of bk 4.11.1

### PR DESCRIPTION
**Pull request by jiazhai**
It would be great to update branch-2.6 to a stable version of bk. so some issues could be fixed.
e.g. https://github.com/apache/bookkeeper/pull/2333

### CODE REVIEW

**Review by sijie — APPROVED** [review]

**Review by sijie — CHANGES_REQUESTED** [review]
Let's make sure the branch-2.6 is able to build

**Comment by jiazhai** [comment]
doing the cherry-pick for #8270

**Review by codelipenghui — APPROVED** [review]

**Comment by vishnuvardhanp4** [comment]
how to upgrade apache pulsar 2.6.1 version to 2.7.0 without losing any data

**Comment by codelipenghui** [comment]
@vishnuvardhanp4 If you just upgrade the broker, I think this will not lose any data. If you want to upgrade the bookkeeper too, you can do like followings:

1. Disable the auto-recovery to prevent the not necessary data replication during the bookkeeper upgrade.(`bin/bookkeeper shell autorecovery -disable`)
2. Upgrade the bookies one by one(after one upgraded, check the bookies works as expected, can write data and read data)
3. After all bookies upgraded, enabled the auto-recovery(`bin/bookkeeper shell autorecovery -enable`)

**Comment by vishnuvardhanp4** [comment]
I am new to Apache pulsar .I am using apache pulsar standalone 2.6.1
version so iwant to upgrade it to 2.7.0 how to do it can u tell in detail
along with commands

**Comment by codelipenghui** [comment]
For the standalone mode, you just need to replace the lib directory with the new lib directory of 2.7.0 and then restart the server. You can use a separate environment to verify. Before replacing, you can backup the old lib directory.

**Comment by vishnuvardhanp4** [comment]
Then is my old  data will be safe ? And also need to upgrade bookkeper ?

Thanks in advance

**Comment by codelipenghui** [comment]
Yes, the data will be safe. The standalone contains the broker and bookkeeper, so the bookkeeper will also upgrade when you upgrade the standalone.

**Comment by vishnuvardhanp4** [comment]
Awesome, thanks!
can u tell me how can i get to know that pulsar standalone is upgraded to
2.7.0 ?

**Comment by vishnuvardhanp4** [comment]
after replacing lib and started facing below error
 ERROR org.apache.bookkeeper.bookie.Bookie - Cookie for this bookie is not
stored in metadata store. Bookie failing to come up
INSTANCEID not exists in zookeeper. Not considering it for data verification
ERROR org.apache.pulsar.PulsarStandaloneStarter - Failed to start pulsar
service.

**Comment by eolivelli** [comment]
If you are using pulsar standalone for development and you can lose your data you can erase the `data` directory and start from scratch

**Comment by vishnuvardhanp4** [comment]
Using it in production.data should not be loose  .is there any other
scenario to solve this issue .please help me out of this
Why the error is showing

**Comment by eolivelli** [comment]
@vishnuvardhanp4 can you please paste more logs ?
"Failed to start pulsar" is not enough.

Side note:
Usually people use "standalone" for development, because with a single node you do not have fault tolerance.

**Comment by eolivelli** [comment]
can you please also create a dedicated ticket "issue", this way we can follow up the discussion about your case

**Comment by vishnuvardhanp4** [comment]
Sure, will do that.

**Pull request merged**
