### PR TITLE
JSONSchema fails to serialise fields on objects that are nested in a collection

### PR DESCRIPTION
**Pull request by chrismiller**
### Motivation

The fix for #2577 (https://github.com/apache/pulsar/commit/701f3ea7e3541f61f064167043de04e8a2db5c0f#diff-576ea6c408d757d9f4a0de5ae27a88fc) introduced a new bug when serialising classes that contain collections of other classes. In this situation, objects in the collection do not have any of their fields serialised because they fail the shouldSkipField() test in JSONSchema.java

### Modifications

Added new unit tests that highlight the problem. I haven't fixed the bug as it is not so clear to me what the correct solution should be.

### Result

The new JSONSchemaTest.testNestedClasses() test will fail, showing the bug in JSONSchema.

### CODE REVIEW

**Comment by jerrypeng** [comment]
Let me take a look

**Comment by jerrypeng** [comment]
@chrismiller thanks for reporting this.

I have removed the code in the JSONSchema that was causing the problem.  The original reason we added that code was so that fields from child classes don't get serialized if the schema is set to the base class.  However, after some thinking, I don't think this is necessary and likely impossible to accomplish given the problem @chrismiller described.  I think its ok to still serialize the field of child classes and write them to a topic given that you can read them out on the consumer end as the base class which currently you can.  So I don't see a point to going down the rabbit hole of how not to serialize child class fields.  We might even want this behavior given that users can evolve their schema over time

**Comment by jerrypeng** [comment]
rerun integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Pull request merged**
