### PR TITLE
removing metrics module from functions

### PR DESCRIPTION
**Pull request by jerrypeng**
### Motivation

Do to recent addition of exposing metrics directly from function instances, metrics module is no longer needed

### CODE REVIEW

**Comment by merlimat** [comment]
Also need to remove from `distribution/server/src/assemble/bin.xml`

**Comment by jerrypeng** [comment]
@merlimat thanks for pointing that out.  I have removed that as well

**Comment by jerrypeng** [comment]
rerun java 8 tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun integration tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Pull request closed without merging**
