### PR TITLE
Make pulsar-brokers gradually conform project checkstyle

### PR DESCRIPTION
**Pull request by Renkai**

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Review by sijie — CHANGES_REQUESTED** [review]
@Renkai I don't think we should remove the ImportOrder rule just because we can't make IDE work. The rule makes the imports sorted by alphabet order. We should document it in our contributor guide (http://pulsar.apache.org/en/coding-guide/)

**Comment by Renkai** [comment]
> @Renkai I don't think we should remove the ImportOrder rule just because we can't make IDE work. The rule makes the imports sorted by alphabet order. We should document it in our contributor guide (http://pulsar.apache.org/en/coding-guide/)

Actually I tried to sort import order in alphabet manually, but the plugin just tells one import command is not in the right order, maybe some bugs exist in checkstyle plugin about this rule

**Comment by Renkai** [comment]
@sijie This draft PR(https://github.com/apache/pulsar/pull/8522/files#diff-26056e00d43a29a9ff02a53654d692aef03e971fcec6c4f57b546afcfff2250dR49)  shows how imports are in order but stylecheck still get wrong

**Comment by eolivelli** [comment]
Please upgrade checkstyle to the latest version (Maven Plugin and Checkstyle dependency)
I started to do it and it is a big pain, because the "ImportOrder" rule changed.
It is better to do it now that we are changing lots of files

**Comment by Renkai** [comment]
> Please upgrade checkstyle to the latest version (Maven Plugin and Checkstyle dependency)
> I started to do it and it is a big pain, because the "ImportOrder" rule changed.
> It is better to do it now that we are changing lots of files

I tried to upgrade checkstyle plugin to `3.1.1` but I got errors

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:check (check-style) on project pulsar-client-api: Execution check-style of goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:check failed: A required class was missing while executing org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:check: com/puppycrawl/tools/checkstyle/api/AutomaticBean$OutputStreamOptions
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/renkai/.m2/repository/org/apache/maven/plugins/maven-checkstyle-plugin/3.1.1/maven-checkstyle-plugin-3.1.1.jar
[ERROR] urls[1] = file:/Users/renkai/renkai-lab/pulsar/buildtools/target/buildtools-2.7.0-SNAPSHOT.jar
[ERROR] urls[2] = file:/Users/renkai/.m2/repository/org/testng/testng/6.14.3/testng-6.14.3.jar
[ERROR] urls[3] = file:/Users/renkai/.m2/repository/com/beust/jcommander/1.72/jcommander-1.72.jar
[ERROR] urls[4] = file:/Users/renkai/.m2/repository/org/apache-extras/beanshell/bsh/2.0b6/bsh-2.0b6.jar
[ERROR] urls[5] = file:/Users/renkai/.m2/repository/org/apache/logging/log4j/log4j-api/2.10.0/log4j-api-2.10.0.jar
[ERROR] urls[6] = file:/Users/renkai/.m2/repository/org/apache/logging/log4j/log4j-core/2.10.0/log4j-core-2.10.0.jar
[ERROR] urls[7] = file:/Users/renkai/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.10.0/log4j-slf4j-impl-2.10.0.jar
[ERROR] urls[8] = file:/Users/renkai/.m2/repository/com/puppycrawl/tools/checkstyle/6.19/checkstyle-6.19.jar
[ERROR] urls[9] = file:/Users/renkai/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.jar
[ERROR] urls[10] = file:/Users/renkai/.m2/repository/org/antlr/antlr4-runtime/4.5.3/antlr4-runtime-4.5.3.jar
[ERROR] urls[11] = file:/Users/renkai/.m2/repository/commons-beanutils/commons-beanutils/1.9.2/commons-beanutils-1.9.2.jar
[ERROR] urls[12] = file:/Users/renkai/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
[ERROR] urls[13] = file:/Users/renkai/.m2/repository/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.jar
[ERROR] urls[14] = file:/Users/renkai/.m2/repository/com/google/guava/guava/19.0/guava-19.0.jar
[ERROR] urls[15] = file:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/../lib/tools.jar
[ERROR] urls[16] = file:/Users/renkai/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
[ERROR] urls[17] = file:/Users/renkai/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
[ERROR] urls[18] = file:/Users/renkai/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
[ERROR] urls[19] = file:/Users/renkai/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[20] = file:/Users/renkai/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[21] = file:/Users/renkai/.m2/repository/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar
[ERROR] urls[22] = file:/Users/renkai/.m2/repository/org/apache/maven/reporting/maven-reporting-impl/2.3/maven-reporting-impl-2.3.jar
[ERROR] urls[23] = file:/Users/renkai/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.6/maven-shared-utils-0.6.jar
[ERROR] urls[24] = file:/Users/renkai/.m2/repository/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar
[ERROR] urls[25] = file:/Users/renkai/.m2/repository/org/apache/maven/doxia/doxia-core/1.2/doxia-core-1.2.jar
[ERROR] urls[26] = file:/Users/renkai/.m2/repository/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar
[ERROR] urls[27] = file:/Users/renkai/.m2/repository/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.jar
[ERROR] urls[28] = file:/Users/renkai/.m2/repository/org/apache/httpcomponents/httpclient/4.0.2/httpclient-4.0.2.jar
[ERROR] urls[29] = file:/Users/renkai/.m2/repository/org/apache/httpcomponents/httpcore/4.0.1/httpcore-4.0.1.jar
[ERROR] urls[30] = file:/Users/renkai/.m2/repository/commons-codec/commons-codec/1.3/commons-codec-1.3.jar
[ERROR] urls[31] = file:/Users/renkai/.m2/repository/commons-validator/commons-validator/1.3.1/commons-validator-1.3.1.jar
[ERROR] urls[32] = file:/Users/renkai/.m2/repository/commons-digester/commons-digester/1.6/commons-digester-1.6.jar
[ERROR] urls[33] = file:/Users/renkai/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.4/doxia-sink-api-1.4.jar
[ERROR] urls[34] = file:/Users/renkai/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.4/doxia-logging-api-1.4.jar
[ERROR] urls[35] = file:/Users/renkai/.m2/repository/org/apache/maven/doxia/doxia-decoration-model/1.4/doxia-decoration-model-1.4.jar
[ERROR] urls[36] = file:/Users/renkai/.m2/repository/org/apache/maven/doxia/doxia-site-renderer/1.4/doxia-site-renderer-1.4.jar
[ERROR] urls[37] = file:/Users/renkai/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.4/doxia-module-xhtml-1.4.jar
[ERROR] urls[38] = file:/Users/renkai/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.4/doxia-module-fml-1.4.jar
[ERROR] urls[39] = file:/Users/renkai/.m2/repository/org/codehaus/plexus/plexus-i18n/1.0-beta-7/plexus-i18n-1.0-beta-7.jar
[ERROR] urls[40] = file:/Users/renkai/.m2/repository/org/apache/velocity/velocity-tools/2.0/velocity-tools-2.0.jar
[ERROR] urls[41] = file:/Users/renkai/.m2/repository/commons-chain/commons-chain/1.1/commons-chain-1.1.jar
[ERROR] urls[42] = file:/Users/renkai/.m2/repository/dom4j/dom4j/1.1/dom4j-1.1.jar
[ERROR] urls[43] = file:/Users/renkai/.m2/repository/oro/oro/2.0.8/oro-2.0.8.jar
[ERROR] urls[44] = file:/Users/renkai/.m2/repository/sslext/sslext/1.2-0/sslext-1.2-0.jar
[ERROR] urls[45] = file:/Users/renkai/.m2/repository/org/apache/struts/struts-core/1.3.8/struts-core-1.3.8.jar
[ERROR] urls[46] = file:/Users/renkai/.m2/repository/org/apache/struts/struts-taglib/1.3.8/struts-taglib-1.3.8.jar
[ERROR] urls[47] = file:/Users/renkai/.m2/repository/org/apache/struts/struts-tiles/1.3.8/struts-tiles-1.3.8.jar
[ERROR] urls[48] = file:/Users/renkai/.m2/repository/org/apache/maven/doxia/doxia-integration-tools/1.6/doxia-integration-tools-1.6.jar
[ERROR] urls[49] = file:/Users/renkai/.m2/repository/commons-io/commons-io/1.4/commons-io-1.4.jar
[ERROR] urls[50] = file:/Users/renkai/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[51] = file:/Users/renkai/.m2/repository/org/codehaus/plexus/plexus-component-annotations/2.0.0/plexus-component-annotations-2.0.0.jar
[ERROR] urls[52] = file:/Users/renkai/.m2/repository/org/codehaus/plexus/plexus-resources/1.1.0/plexus-resources-1.1.0.jar
[ERROR] urls[53] = file:/Users/renkai/.m2/repository/org/codehaus/plexus/plexus-utils/3.3.0/plexus-utils-3.3.0.jar
[ERROR] urls[54] = file:/Users/renkai/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.26/plexus-interpolation-1.26.jar
[ERROR] urls[55] = file:/Users/renkai/.m2/repository/org/codehaus/plexus/plexus-velocity/1.2/plexus-velocity-1.2.jar
[ERROR] urls[56] = file:/Users/renkai/.m2/repository/org/apache/velocity/velocity/1.7/velocity-1.7.jar
[ERROR] urls[57] = file:/Users/renkai/.m2/repository/commons-lang/commons-lang/2.4/commons-lang-2.4.jar
[ERROR] urls[58] = file:/Users/renkai/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>org.apache.pulsar:pulsar:2.7.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] : com.puppycrawl.tools.checkstyle.api.AutomaticBean$OutputStreamOptions
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pulsar-client-api
```

**Comment by eolivelli** [comment]
You have to upgrade puppycrawl checkstyle as well

**Comment by Renkai** [comment]
> You have to upgrade puppycrawl checkstyle as well

@eolivelli  checkstyle configuration in the newest version seems quite different from old ones, maybe we need to change the XML a lot to make it a valid configuration.

**Comment by eolivelli** [comment]
yes, I also did it in my branch, the changes are pretty simple, just google for the errors that you find and you will get a solution, if you want we can chat on slack

**Comment by Renkai** [comment]
> yes, I also did it in my branch, the changes are pretty simple, just google for the errors that you find and you will get a solution, if you want we can chat on slack

Hi @eolivelli , I sent message to you on slack

**Comment by Renkai** [comment]
After some compatibility work, checkstyles are now passed, I will try to add import order check back if the bugs are fixed in the newest version of checkstyle plugin. @eolivelli @sijie

**Comment by Renkai** [comment]
> @sijie This draft PR(https://github.com/apache/pulsar/pull/8522/files#diff-26056e00d43a29a9ff02a53654d692aef03e971fcec6c4f57b546afcfff2250dR18-R52) shows how imports are in order but stylecheck still get wrong.
> Static import at top conforms `<property name="option" value="top"/>`

Sadly newest version of checkstyle still have the same problem.

**Comment by eolivelli** [comment]
@Renkai @sijie I observed the same problem.
The only thing to do is to adapt to the rule and fix our code.

@Renkai do you mind creating an issue on checkstyle repository (not maven checkstyle plugin, but puppycrawl checkstyle) ?

**Comment by Renkai** [comment]
@eolivelli Looks like they already have lots of ImportOrder issues in progress, and the issues covers our condition. So no need to create a new issue, up vote for existing issues is enough.

https://github.com/checkstyle/checkstyle/issues?q=is%3Aissue+is%3Aopen+ImportOrder

**Comment by Renkai** [comment]
Set ImportOrder back but exclude several packages for not effect too many files at once.

**Review by eolivelli — COMMENTED** [review]
awesome work

**Review by sijie — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by eolivelli** [comment]
@codelipenghui @sijie 
after merging this patch we should encourage every contributor to merge any pending patch with master branch,
otherwise at every merge we will break the build, because old patches are very likely to be not compatible with these new rules.
it will be annoying, but we have to do it only once
Probably it is better to send a HEADS UP  message to dev@pulsar (and also on Slack)

**Review by sijie — APPROVED** [review]

**Pull request merged**
