### PR TITLE
Provide a mechanism to disable uploading distribution packages

### PR DESCRIPTION
**Pull request by sijie**
*Motivation*

Currently all the distribution packages are very large. We should provide a way to skip uploading distribution packages.

### CODE REVIEW

**Comment by sijie** [comment]
run java8 tests

**Comment by merlimat** [comment]
@sijie I think the only reason the dist files are "attached" is for the maven docker task to pick them up. If we can disable the deploy/upload, we should probably do that by default

**Comment by sijie** [comment]
@merlimat I didn't change the default behavior because I am not sure if it can break anything. I would prefer adding the flag first (starting with a safer approach) and disabling it by default later.

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run cpp tests
run integration tests

**Comment by sijie** [comment]
run java8 tests

**Pull request merged**
