### PR TITLE
move general schema hash to common module

### PR DESCRIPTION
**Pull request by yittg**
Master Issue: #5141 

Move same hash functions for client and broker to common module.

### CODE REVIEW

**Comment by sijie** [comment]
run java8 tests
run cpp tests

**Comment by yittg** [comment]
run java8 tests
run cpp tests

**Comment by jiazhai** [comment]
run java8 tests
run cpp tests

**Comment by yittg** [comment]
run cpp tests

**Comment by yittg** [comment]
run cpp tests

**Comment by jiazhai** [comment]
run cpp tests

**Pull request merged**
