### PR TITLE
[WebSocket] Add spotbugs plugin for websocket module

### PR DESCRIPTION
**Pull request by BewareMyPower**
### Motivation

Add spotbugs plugin for WebSocket module.

### Modifications

There're 20 potential bugs after adding the plugin to check. Here're the modifications to fix:
- MS_MUTABLE_ARRAY: Change the public static array `ENTRY_LATENCY_BUCKETS_USEC` to an unmodifiableList.
- SE_BAD_FIELD: Make the `service` field of Servlet classes `transient` to avoid being serialized.
- URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD: Ignore these errors because it's just an encapsulation issue and some fields are used in other modules or existed clients.
- IS2_INCONSISTENT_SYNC: Add `synchronized` keyword to the setter of `localCluster` to make all access synchronized.
- EI_EXPOSE_REP: Return a clone of array as a snapshot.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

### CODE REVIEW

**Comment by zymap** [comment]
We have a fix of the integration tests. Please rebase your code. Thanks.

**Review by zymap — COMMENTED** [review]
Does this PR need to wait for PR #8784 merged?

**Comment by BewareMyPower** [comment]
@zymap It's better to wait for #8784 merged because this PR doesn't specify the spotbugs' version.

**Review by sijie — APPROVED** [review]

**Pull request merged**
