### PR TITLE
[improve][fn] Support configure compression type

### LINKED ISSUE #19462: Support configure compression type for pulsar functions
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

currently, pulsar functions are using LZ4 as the hardcoded compression type, it would be better to make it configurable

### Solution

Add a `compressionType` field to the `FunctionConfig`, so it can be passed to function instances

### Alternatives

_No response_

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by jiangpengcheng**
Fixes #19462 

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [x] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/jiangpengcheng/pulsar/pull/6

### CODE REVIEW

**Review by nlu90 — APPROVED** [review]

**Comment by nlu90** [comment]
@jiangpengcheng 
Since this PR involves protobuf change, let's send an email in the mailing list to let folks in the community know about it.

**Review by tisonkun — COMMENTED** [review]
Thanks for your contribution @jiangpengcheng! Generally looks good.

Comments below:

1. I don't find changes to Go Functions, do you update it later or it's unrelevant?
2. @momo-jun maybe we should update the document for this new feature. Although it can be a light one, the author marks it as `doc-required`. But I'm unsure what page is suitable for such chanegs.

**Comment by momo-jun** [comment]
@tisonkun thanks for considering the doc development.
@jiangpengcheng To scope the incremental doc updates, I think at least we have a new config that needs to be added to [this topic](https://pulsar.apache.org/docs/next/functions-cli/#yaml-configurations-for-pulsar-functions). Can you please confirm and advise? It would be great if you could analyze the user impact of this improvement and involve the doc updates within this PR.

**Comment by jiangpengcheng** [comment]
> Details

added go support and suggestions to docs update

**Comment by momo-jun** [comment]
> the type is `String` and available values are: `None`, `LZ4`, `ZLIB`, `ZSTD` and `SNAPPY`, and default to `LZ4`

@jiangpengcheng thanks for the input. I've drafted https://github.com/apache/pulsar-site/pull/461 to add the docs.
Only one concern - the default config of compression type on client side, e.g., Java producers, is `None` (no compression), which is not aligned with functions. Is there any risk here?

**Comment by jiangpengcheng** [comment]
> > the type is `String` and available values are: `None`, `LZ4`, `ZLIB`, `ZSTD` and `SNAPPY`, and default to `LZ4`
> 
> @jiangpengcheng thanks for the input. I've drafted [apache/pulsar-site#461](https://github.com/apache/pulsar-site/pull/461) to add the docs. Only one concern - the default config of compression type on client side, e.g., Java producers, is `None` (no compression), which is not aligned with functions. Is there any risk here?


There is no risk, just for back compatibility since current pulsar functions are using `LZ4` as compression type.

One thing I did wrong is that the `None` should be `NONE` instead

**Comment by michaeljmarshall** [comment]
This updates the function proto. Shouldn't we have had a PIP?

**Comment by nlu90** [comment]
Hi @michaeljmarshall, a mail thread sent on February 28 discussed the change. 
PTAL: https://lists.apache.org/thread/8z849bhp79ob23kf1p21f6kq7rd6bljq

**Comment by michaeljmarshall** [comment]
Thanks for that link @nlu90! Looks good to me.

**Comment by lhotari** [comment]
This PR broke the master branch. Please review and merge #19904 asap to fix master. 
The reason why this PR was mergeable is due to a CI bug #19905 .

**Comment by lhotari** [comment]
> > > the type is `String` and available values are: `None`, `LZ4`, `ZLIB`, `ZSTD` and `SNAPPY`, and default to `LZ4`
> > 
> > 
> > @jiangpengcheng thanks for the input. I've drafted [apache/pulsar-site#461](https://github.com/apache/pulsar-site/pull/461) to add the docs. Only one concern - the default config of compression type on client side, e.g., Java producers, is `None` (no compression), which is not aligned with functions. Is there any risk here?
> 
> There is no risk, just for back compatibility since current pulsar functions are using `LZ4` as compression type.
> 
> One thing I did wrong is that the `None` should be `NONE` instead

@jiangpengcheng @nlu90  This PR introduced a change to the compression type default. Only when the producer config is provided, it will use the LZ4 compression default. The producer config is optional and that's why compression will now be NONE by default when the producer config isn't provided.
Producers are created in 2 locations in the Pulsar Functions code. The other location still has LZ4 compression by default.
There's another issue #22948 which I'm currently working on. I'm not changing the behavior of the compression default in that change, but unifying the configuration so that compression type can be configured also for the producers created in ContextImpl.

**Pull request merged**
