### PR TITLE
[Docs]Fix website io connector link 404

### PR DESCRIPTION
**Pull request by tuteng**
### Motivation

Currently, the old version of the connector document is incorrect. The new version of the connector document is not compatible with the old version, resulting in an HTTP 404 response.

### Modifications

* Documentation for older versions http link of connectors remains unchanged.
* Add document of old versions.

### Verifying this change

Local Test Pass

### CODE REVIEW

**Comment by aahmed-se** [comment]
rerun cpp tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
@tuteng rebase this
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests
run cpp tests

**Comment by tuteng** [comment]
run java8 tests

**Comment by tuteng** [comment]
run java8 tests

**Comment by tuteng** [comment]
run java8 tests

**Comment by tuteng** [comment]
run java8 tests

**Comment by tuteng** [comment]
run java8 tests

**Comment by tuteng** [comment]
run cpp tests

**Comment by tuteng** [comment]
retest this please

**Comment by tuteng** [comment]
run java8 tests

**Pull request merged**
