### PR TITLE
Add messaging integration tests for different subscriptions.

### PR DESCRIPTION
**Pull request by codelipenghui**
### Motivation

Add integration tests for message send and receive.

Cover different subscriptions:
- Exclusive
- Failover
- Shared
- Key_Shared

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by codelipenghui** [comment]
run Java8 Tests

**Comment by merlimat** [comment]
@codelipenghui It's failing on KeySharedSubscriptionTest.testConsumerCrashSendAndReceiveWithHashRangeStickyKeyConsumerSelector which seems to be flaky #4353

**Comment by lovelle** [comment]
`KeySharedSubscriptionTest.testConsumerCrashSendAndReceiveWithHashRangeStickyKeyConsumerSelector` fails on master branch for me.

**Comment by codelipenghui** [comment]
Seems this is related to changes here https://github.com/apache/pulsar/pull/4329/files#diff-12d605952d013b598fd881f86c7cdefcL193.
 I did some testing and found that this problem occurs when I close two consumers too quickly and if not included #4329 , UT can passed every time. I am trying to find out what the problem is.

**Comment by merlimat** [comment]
Thanks for fixing this. It was indeed a regression in my change.

**Comment by codelipenghui** [comment]
run Integration Tests

**Comment by codelipenghui** [comment]
run Java8 Tests

**Comment by codelipenghui** [comment]
relate to #4077

**Pull request merged**
