### PR TITLE
Cherry-pick functions admin api docs to 2.4.1

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <ranxiaolong716@gmail.com>

### Motivation

The docs of functions admin api missing in `v2.4.1`

### Modifications

`Cherry-pick` the docs of functions admin api to `v2.4.1`

### CODE REVIEW

**Comment by wolfstudy** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
> [ERROR] testSeekTimeOnPartitionedTopic(org.apache.pulsar.broker.service.SubscriptionSeekTest)

run java8 tests

**Pull request merged**
