### PR TITLE
[feature][pulsar-broker-common]Move additional servlet module to pulsar broker common module

### PR DESCRIPTION
**Pull request by tuteng**
### Motivation

* Currently, after merging this or https://github.com/apache/pulsar/pull/8067, the pulsar-proxy module already supports loading custom web routes, which is also needed in the `pulsar-broker` and `pulsar-function` modules, so consider moving this functionality to the `pulsar-broker-common` module as a generic module.

### Modifications

* Update the class name to remove the proxy prefix
* Move to the a module

How to use this generic module

1. add configuration `additionalServletDirectory` and `additionalServlets` to the configuration file
2. Call the following code

```
          Collection<AdditionalServletWithClassLoader> additionalServletCollection =
                    service.getProxyAdditionalServlets().getServlets().values();
            for (AdditionalServletWithClassLoader servletWithClassLoader : additionalServletCollection) {
                servletWithClassLoader.loadConfig(config);
                server.addServlet(servletWithClassLoader.getBasePath(), servletWithClassLoader.getServletHolder(),
                        Collections.emptyList(), config.isAuthenticationEnabled());
                log.info("proxy add additional servlet basePath {} ", servletWithClassLoader.getBasePath());
            }
```

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by sijie — APPROVED** [review]
@tuteng The overall change looks good to me.

**Comment by Anonymitaet** [comment]
Confirmed w/ @tuteng, no need to add docs for this PR.

**Pull request merged**
