### PR TITLE
[improve][CI] Replace test reporting with less verbose solution

### LINKED ISSUE #16736: CI: Replace current GitHub Actions test reporting solution with less verbose solution
**Is your enhancement request related to a problem? Please describe.**

We are currently using a test reporting solution based on https://github.com/dorny/test-reporter and there's a copy of this action in https://github.com/apache/pulsar-test-infra/tree/master/test-reporter .

The problem with this solution is that the test reporting is very verbose since it creates new check runs for the PR. 
When there are failed tests, the PR will be marked failing even in cases where the tests pass in a later retry.

**Describe the solution you'd like**

There's an alternative solution in https://github.com/mikepenz/action-junit-report which is actively maintained. 
It's possible to use this action with `annotate_only: 'true'` so that check runs aren't created at all. This is to mitigate the gap in GitHub Actions solution that check results cannot target a specific workflow when there are multiple active ones (more details in https://github.com/mikepenz/action-junit-report/issues/40#issuecomment-1192309267). 
The action will create a report for each build job using [a new method available in GitHub Actions](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/). example: https://github.com/mikepenz/action-junit-report/actions/runs/2717236074#summary-7464569272

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #16736

### Motivation

See #16736

This PR reduces noise in test reporting and removes the misleading check runs from PR checks.

### Modifications

- remove separate workflow that added GitHub Actions check runs
- replaces test reporting with https://github.com/mikepenz/action-junit-report which has been
  copied to https://github.com/apache/pulsar-test-infra/tree/master/action-junit-report
- [x] `doc-not-needed`

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]

**Comment by lhotari** [comment]
@tisonkun @maxsxu please join the review too

**Review by nicoloboschi — APPROVED** [review]

**Review by tisonkun — COMMENTED** [review]
Generally looks good. Thanks!

Two comments:

1. `./.github/actions/merge-test-reports` seems no more references, we may remove it.
2. I don't find a report on the new progress in the demo https://github.com/lhotari/pulsar/pull/78, can you show me a direct link for the test report page? (IIUC it should be something like this one: https://github.com/apache/pulsar/pull/17062/checks?check_run_id=8027361638)

**Comment by lhotari** [comment]
> Generally looks good. Thanks!
> 
> Two comments:
> 
> 1. `./.github/actions/merge-test-reports` seems no more references, we may remove it.

Yes makes sense.


> 2. I don't find a report on the new progress in the demo https://github.com/lhotari/pulsar/pull/78, can you show me a direct link for the test report page? (IIUC it should be something like this one: https://github.com/apache/pulsar/pull/17062/checks?check_run_id=8027361638)

The goal of the PR is to not add the report as a check run. The report is displayed on the workflow run summary page: https://github.com/lhotari/pulsar/actions/runs/2943996610
Besides the markdown report, annotations are added with the relevant code location and stack trace.

**Review by tisonkun — APPROVED** [review]
Thanks for your explanation! I get the point. +1 to merge,

**Comment by tisonkun** [comment]
One thing to remind here is that we may want to cherry-pick this change to previous release branch. I suppose we can possibly remove the test-reporter action from pulsar-test-infra.

**Comment by lhotari** [comment]
> One thing to remind here is that we may want to cherry-pick this change to previous release branch. I suppose we can possibly remove the test-reporter action from pulsar-test-infra.
> 
> Or we can tag pulsar-test-infra and use a stable version :)

The forks of apache/pulsar still depend on test-reporter action and it might be a good idea to keep it for some time, also after our maintenance branches no more use it.

btw. There would be a way in GitHub Actions to make maintenance branches use workflows defined in the master branch. This is possible with the new reuseable workflows, https://github.blog/changelog/2022-08-22-github-actions-improvements-to-reusable-workflows-2/ . There's a tradeoff in doing this, but that could make things easier if we have a single pipeline to maintain.

**Review by maxsxu — COMMENTED** [review]
Thanks for this clean PR!

Just wondering how we added the action-junit-report against the pulsar-test-infra repo?

**Comment by tisonkun** [comment]
@maxsxu I think @lhotari pushed a commit https://github.com/apache/pulsar-test-infra/commit/eeb9107170ddeb24f76b41bc0582e340c688113f directly.

**Comment by lhotari** [comment]
> @maxsxu I think @lhotari pushed a commit [apache/pulsar-test-infra@eeb9107](https://github.com/apache/pulsar-test-infra/commit/eeb9107170ddeb24f76b41bc0582e340c688113f) directly.

yes

**Pull request merged**
