### PR TITLE
[Issue 8079] Use if to avoid throwing NPE

### LINKED ISSUE #8079: Use if to avoid throwing NPE
image
For above marked place, we should use if to check NPE to avoid throwing NPE.
```
if (sub == null) {
   asyncResponse.resume(new RestException(Status.NOT_FOUND, "Subscription not found"));
   return;
}
```

### PR DESCRIPTION
**Pull request by Technoboy-**
Fix #8079 .

### CODE REVIEW

**Comment by sijie** [comment]
What is the motivation of this change?

**Comment by Technoboy-** [comment]
> What is the motivation of this change?

Refer to #8078 .

**Review by sijie — APPROVED** [review]

**Comment by codelipenghui** [comment]
@Technoboy- Could you please help resolve the conflicts?

**Pull request merged**
