### PR TITLE
Fix potential npe bug of #14384

### PR DESCRIPTION
**Pull request by gaozhangmin**
### Motivation
Fix potential npe bug

### Modifications

Fix potential npe bug

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Comment by lhotari** [comment]
@gaozhangmin Please add some tests to cover this change.

**Review by nodece — APPROVED** [review]
Good catch!

**Comment by gaozhangmin** [comment]
> @gaozhangmin Please add some tests to cover this change.

The tests were already covered by `BookKeeperPackagesStorageTest.java`. But need to change `zookeeperServers` to `metadataStoreUrl` @lhotari

**Comment by lhotari** [comment]
> > @gaozhangmin Please add some tests to cover this change.
> 
> The tests were already covered by `BookKeeperPackagesStorageTest.java`. But need to change `zookeeperServers` to `metadataStoreUrl` @lhotari

ok, that explains. At the time I checked the PR there was a fix, but no test changes and that's why I made the comment.

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
