### PR TITLE
fix bug:https://github.com/apache/pulsar/issues/7815

### LINKED ISSUE #7815: functions-worker jvm metrics error
**Describe the bug**
functions-worker process model：
1.After the functions worker is started, if you do not create function, you cannot get any JVM metrics information.
2.The indicators of functions worker shown in the JVM metrics dashboard are not correct. It should be the indicators collected by functions worker. The in heap memory is set to 4G. However, the maximum in heap memory of functions worker shown in the dashboard is always 1g.

functions-worker thread model：
1.After the functions worker is started, if you don't create function, you can't get any metrics information.
2.After create function, only the functions runtime processed metrics information, but no functions worker JVM metrics information.

pulsar 2.5.2
image

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by xuesongxs**
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #7815 

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #7815 

### Motivation
Functions worker adds a type field to distinguish between functions and functions worker metrics.

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by xuesong172500** [comment]
> I think you should expose the JVM metrics to the same `/metrics` endpoint instead of creating a new endpoint.

At present, the /metrics endpoint collects the function indicators, including the function's JVM indicators. If the functions worker's JVM indicators are added to the /metrics endpoint, the functions and functions worker's JVM indicators will have duplicate names, and filter conditions should be added. I will consider how to modify /metrics uniformly。

**Comment by xuesong172500** [comment]
@sijie please reivew again，I have modified.

**Comment by wolfstudy** [comment]
@sijie PTAL again, thanks

**Pull request closed without merging**
