### PR TITLE
[Issue 8294][docs]Some errors on the official website document of Pulsar Java client #8294

### LINKED ISSUE #8294: Some errors on the official website document of Pulsar Java client
#### official website document of Pulsar Java client

**No such grammar exists in Java，This is the syntax of python**

**No such method：consumerBuilder.topics(String... topicNames)**

**compile error**

**conf not used，it's redundant**

#### System configuration
**Pulsar version**: 2.6.1

### PR DESCRIPTION
**Pull request by yixing1337**
Fixes #8294

### CODE REVIEW

**Comment by Jennifer88huang** [comment]
@yixing1337 thank you very much for fixing the issue. 
Is this exclusive to release 2.6.1 only, or does it also apply to other versions?

**Comment by tuteng** [comment]
LGTM, These files also have errors, please help update them, thank you. @yixing1337 

site2/docs/client-libraries-java.md
site2/website/versioned_docs/version-2.6.2/client-libraries-java.md
site2/website/versioned_docs/version-2.6.0/client-libraries-java.md
site2/website/versioned_docs/version-2.5.2/client-libraries-java.md
site2/website/versioned_docs/version-2.5.1/client-libraries-java.md
site2/website/versioned_docs/version-2.5.0/client-libraries-java.md

**Comment by yixing1337** [comment]
> @yixing1337 thank you very much for fixing the issue.
> Is this exclusive to release 2.6.1 only, or does it also apply to other versions?

yes, other versions also have these errors, I'll commit again to fix those versions.

**Comment by yixing1337** [comment]
> LGTM, These files also have errors, please help update them, thank you. @yixing1337
> 
> site2/docs/client-libraries-java.md
> site2/website/versioned_docs/version-2.6.2/client-libraries-java.md
> site2/website/versioned_docs/version-2.6.0/client-libraries-java.md
> site2/website/versioned_docs/version-2.5.2/client-libraries-java.md
> site2/website/versioned_docs/version-2.5.1/client-libraries-java.md
> site2/website/versioned_docs/version-2.5.0/client-libraries-java.md

The above mentioned have been fixed, please review code , thank you!

**Review by Jennifer88huang — APPROVED** [review]
@yixing1337 Thank you very much for your contribution~

**Review by wolfstudy — APPROVED** [review]

**Pull request merged**
