### PR TITLE
[tests] create consumers before producing for DeadLetterTopicTest

### PR DESCRIPTION
**Pull request by sijie**
### Motivation

Create consumers before producing will make sure consumers received all the messages that they expect to receive.

### CODE REVIEW

**Comment by sijie** [comment]
retest this please

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Pull request merged**
