### PR TITLE
[pulsar-admin] add option to get precise backlog on v1 topic

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation
Add option to get precise backlog for v1 topic as well.

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Review by sijie — APPROVED** [review]

**Comment by codelipenghui** [comment]
@rdhabalia Seems the failed tests related to this PR, I will move this one to the next milestone, If you can fix the test please move it back to 2.8.0.

**Pull request merged**
