### PR TITLE
Inject system-env variables to pulsar configuration

### PR DESCRIPTION
**Pull request by rdhabalia**
### Motivation

It's always convenient to set system-env variables and pulsar service is able to parse it while reading configuration file.

### Modifications

Add support to parse system-env variables in pulsar configuration files.

### Result

Now, user can set config value as system-env variable
eg:
```
// set system-env variable
export brokerServicePort=6650
export webServicePort=8080

// set system-env prop name into config file
brokerServicePort=$brokerServicePort
webServicePort=${webServicePort}
```

### CODE REVIEW

**Comment by jai1** [comment]
retest this please

**Comment by merlimat** [comment]
I think it becomes a bit tricky, because if you want to configure some options through env variables, you might as well need to configure them all. 

For example, what happens if the variable is not defined in 

```shell
webServicePort=${webServicePort}
```

I think that falling back to default should be the best option. 

For updating the config file through environment variables, there is already a tool in  [docker/scripts/apply-config-from-env.py](https://github.com/apache/incubator-pulsar/blob/master/docker/scripts/apply-config-from-env.py), that updates the config files replacing the variables that are being overwritten through the enviroment.

**Comment by rdhabalia** [comment]
> I think that falling back to default should be the best option.

Sure.

>For updating the config file through environment variables, there is already a tool in docker/scripts/apply-config-from-env.py,

Yes, but here only difference is that it helps without modifying files. So, it will also help in testing while starting multiple instance using the same file.

**Comment by merlimat** [comment]
> Yes, but here only difference is that it helps without modifying files. So, it will also help in testing while starting multiple instance using the same file.

For this last case, I'd prefer to allow CLI parameter overrides, in that it's more explicit of where the setting is coming from

**Comment by sijie** [comment]
@jai1 @rdhabalia what is the take here?  are we targeting this for 2.0? If not, can we move it to 2.1?

**Comment by sijie** [comment]
moved to 2.1

**Comment by dave2wave** [comment]
This PR is evidently stale or abandoned. Reopen if this is not so.

**Pull request closed without merging**
