### PR TITLE
[fix][broker] Enable message deduplication. Occasionally, it may occu…

### PR DESCRIPTION
**Pull request by zhuhai1221**
### Motivation

- message deduplication is enabled
- Create new cursor ledger failed
- PENDING_MARK_DELETED_SUBMITTED_COUNT_UPDATER not decrement
-  It is impossible to create a new cursor ledger again.
- The mark delete position of the snapshot cannot be moved.  
- The consumed ledger cannot be deleted.  
- The bookie is unable to clean the disk.  

### Modifications

The logic for handling PENDING_MARK_DELETED_SUBMITTED_COUNT_UPDATER is omitted in the code. Add it at the omitted place.  

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is just a minor tweak and there is no test coverage.  
### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by zhuhai1221** [comment]
@BewareMyPower @poorbarcode @liangyepianzhou Please help me review the code

**Review by liangyepianzhou — COMMENTED** [review]
Good catch!  Do you mind adding a unit test to avoid the case happened again?

**Comment by zhuhai1221** [comment]
Please Ignore this PR, as I have just noticed it has been resolved, and now the callback function is being called.@liangyepianzhou

**Comment by zhuhai1221** [comment]
> Good catch! Do you mind adding a unit test to avoid the case happened again?

Please Ignore this PR, as I have just noticed it has been resolved, and now the callback function is being called.@liangyepianzhou

**Pull request closed without merging**
