### PR TITLE
[cleanup][broker] Remove authenticateOriginalAuthData in ServerCnx

### PR DESCRIPTION
**Pull request by lordcheng10**
### Modifications

Remove unused authenticateOriginalAuthData in ServerCnx.

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `no-need-doc` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-added`
(Docs have been already added)

### CODE REVIEW

**Review by Jason918 — APPROVED** [review]

**Review by HQebupt — APPROVED** [review]

**Review by Technoboy- — APPROVED** [review]

**Review by Demogorgon314 — APPROVED** [review]

**Comment by gaozhangmin** [comment]
pr #15147 remove all the unused filed in method and class, this parameters included.

**Review by michaeljmarshall — APPROVED** [review]

**Pull request merged**
