### PR TITLE
[branch-2.9][fix][load-balancer] skip mis-configured resource usage(>100%) in loa…

### PR DESCRIPTION
**Pull request by heesung-sn**
### Motivation

cherry-pick this commit to branch-2.9 requested by : https://github.com/apache/pulsar/pull/16937#issuecomment-1227036563

### CODE REVIEW

**Review by Demogorgon314 — APPROVED** [review]

**Comment by codelipenghui** [comment]
@Demogorgon314 We don't need to remove the `release/*` label after cherry-picking the PR. Because we are using the `release/*` label to check how many changes will introduce to that version.

**Comment by Demogorgon314** [comment]
@codelipenghui Thanks for reminding!

**Pull request merged**
