### PR TITLE
[improve][test] Optimize TransactionEndToEndTest

### PR DESCRIPTION
**Pull request by liangyepianzhou**
## Motivation
1. fix flaky test https://github.com/apache/pulsar/issues/18466 caused by txn async send method
2. decrease run time by optimizing receive method 
## Modification
1. fix flaky test
   * modify `producer.newMessage(txn1).value(("Hello Txn - " + i).getBytes(UTF_8)).sendAsync();` to `producer.newMessage(txn1).value(("Hello Txn - " + i).getBytes(UTF_8)).send();` 
This also can be resolved by https://github.com/apache/pulsar/pull/17836 and https://github.com/apache/pulsar/pull/18486 later.
2. decrease run time by optimizing receive method 
    * modify
 `    Message<byte[]> message = consumer.receive(5, TimeUnit.SECONDS);
                   Assert.assertNull(message);` to
                   `  Message<byte[]> message = consumer.receive(300, TimeUnit.MILLISECONDS);
                            Assert.assertNull(message);`
   * modify `message = consumer.receive();` to `message = consumer.receive(5, TimeUnit.SECONDS);`
   * keep other `consumer.receive(x, y)` no change.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/liangyepianzhou/pulsar/pull/12

### CODE REVIEW

**Review by Technoboy- — APPROVED** [review]

**Review by labuladong — COMMENTED** [review]
I'm wondering what's the root cause of the `TransactionEndToEndTest` flaky test? 

This test failed because of out of time limit (300 seconds), so I guess it was caused by the `receive` with infinite timeout:

https://github.com/apache/pulsar/blob/79d1e5210ea3e30b203f7241180eea1628e9296e/pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java#L163-L167

Could you please explain why changing `sendAsync` to `send` can fix this flaky test?

**Comment by liangyepianzhou** [comment]
> I'm wondering what's the root cause of the `TransactionEndToEndTest` flaky test?
> 
> This test failed because of out of time limit (300 seconds), so I guess it was caused by the `receive` with infinite timeout:
> 
> https://github.com/apache/pulsar/blob/79d1e5210ea3e30b203f7241180eea1628e9296e/pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java#L163-L167
> 
> Could you please explain why changing `sendAsync` to `send` can fix this flaky test?

@labuladong The root cause is the logic of sequence ID and serializeAndSendMessage command not being contained in the same synchronized block. And then make the message drop due to deduplication.
Https://github.com/apache/pulsar/pull/17836 has already fixed this.

**Comment by nodece** [comment]
I suggest keeping the same timeout.

**Comment by liangyepianzhou** [comment]
> I suggest keeping the same timeout.

@nodece I have already tried to unify the timeout time. But this will cause some test instability. Some tests may have special considerations and need to increase the timeout time, while some tests require a very short timeout time. So for those stable tests with a timeout, we should not modify it.

**Review by nodece — APPROVED** [review]

**Comment by nodece** [comment]
@liangyepianzhou Please check the CI failed.

**Pull request merged**
