### PR TITLE
The consumption performance index cannot be obtained, and the obtaine…

### PR DESCRIPTION
**Pull request by g0715158**
Fixes:#8023

Motivation
The consumption performance index cannot be obtained, and the obtained value is all 0

Modifications
Add code to collect the indicators of stats.rateOut and stats.throughputOut in the getTopicStats method of the NamespaceStatsAggregator class

Verifying this change
Make sure that the change passes the CI checks.

This change added tests

Does this pull request potentially affect one of the following parts:

If yes was chosen, please highlight the changes
•Dependencies (does it add or upgrade a dependency): (no)
•The public API: (no)
•The schema: (no)
•The default values of configurations: (no)
•The wire protocol: (no)
•The rest endpoints: (no)
•The admin cli options: (no)
•Anything that affects deployment: (don't know)

Documentation
•Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Review by g0715158 — COMMENTED** [review]
topic.getSubscriptions().values().forEach(sub->{
            sub.getConsumers().forEach(consumer -> {
                stats.rateOut+=consumer.getStats().msgRateOut;
                stats.throughputOut += consumer.getStats().msgThroughputOut;
            });
        });

**Review by codelipenghui — COMMENTED** [review]
@g0715158 Could you please clarify the root cause? I noticed the rateOut and throughputOut already aggregated at https://github.com/apache/pulsar/pull/8025/files#diff-b3f64ff76fdabb9e471435147298c3c707cbecae09023f0d86cf06f6ad78cbdaR157-R158.

BTW, it's better to create a new branch for pushing a fix or a new feature. For more detailed contribution guide, you can see http://pulsar.apache.org/en/contributing/

**Comment by codelipenghui** [comment]
move to milestone 2.8.0

**Comment by tisonkun** [comment]
Closed as stale and conflict. Please rebase and resubmit the patch if it's still relevant.

**Pull request closed without merging**
