### PR TITLE
Intercept beforeSendMessage calls

### PR DESCRIPTION
**Pull request by sijie**
*Motivation*

Currently the message metadata headers are deserialized for filtering
out the entries to dispatch. Add a `beforeSendMessage` method to
intercept entries before sending them to consumers

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by jiazhai** [comment]
@sijie CI failed for checkstyles:

```
Error:  src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java:[237] (javadoc) JavadocStyle: First sentence should end with a period.
Error:  src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java:[242] (sizes) LineLength: Line is longer than 120 characters (found 129).
Error:  src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java:[270] (sizes) LineLength: Line is longer than 120 characters (found 132).
```

**Comment by jiazhai** [comment]
seems already  have PR #8933 to fix this checkstyle issue

**Review by jiazhai — APPROVED** [review]

**Pull request merged**
