### PR TITLE
[Broker] Improve test code readability and maintainability by refactoring repeated values 

### PR DESCRIPTION
**Pull request by kellyfj**
### Motivation
Make the test code a little more readable and maintainable and clarify intent of `Thread.sleep(3000)` 

### Modifications
Refactored Thread.sleep() to common function and hard-coded Http values to constants

### Verifying this change
This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): no
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no
  - The rest endpoints: no
  - The admin cli options: no
  - Anything that affects deployment: no

### Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by zymap** [comment]
Please rebase to the latest master. There have some fixes about the CI.

**Review by sijie — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
