### PR TITLE
[test] add getters and setters to PulsarService & BrokerService

### PR DESCRIPTION
**Pull request by sijie**
*Motivation*

When using PulsarService or BrokerService for testing, it might require accessing
the components in PulsarService and BrokerService. This change is adding setters
and getters to access the components in PulsarService & BrokerService

### CODE REVIEW

**Comment by sijie** [comment]
run cpp tests

**Comment by sijie** [comment]
run cpp tests

**Comment by sijie** [comment]
run cpp tests

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by sijie** [comment]
run cpp tests
run java tests

**Comment by sijie** [comment]
run cpp tests

**Comment by jiazhai** [comment]
run cpp tests

**Comment by jiazhai** [comment]
run cpp tests

**Comment by sijie** [comment]
run cpp tests

**Pull request merged**
