### PR TITLE
[Transaction] Fix recover of TransactionBuffer

### PR DESCRIPTION
**Pull request by liangyepianzhou**
### Motivation
Fix the concurrency issue caused by TransactionBuffer when recovering.
### Modification
1. use TransactionReplayExecutor when thenAcceptAsync in recover::run was called.
2. delete repeated changeToInitializingState
3. if cursor.hasMoreEntries() == false && entryQueue.size() == 0, return false and stop recovering.
    -  If the cursor is cleared when transaction is recovering , there will no entries  can be read, but currentLoadPosition < lastConfirmedEntry.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Review by congbobo184 — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Review by gaoran10 — COMMENTED** [review]
Great work, a little suggestion, maybe we could use this format, it's easier to view and it will not increase code indent.

```
if (!this.topicTransactionBuffer.changeToInitializingState()) {
  // doing something
  return;
}
```

**Comment by liangyepianzhou** [comment]
> Great work, a little suggestion, maybe we could use this format, it's easier to view and it will not increase code indent.
> 
> ```
> if (!this.topicTransactionBuffer.changeToInitializingState()) {
>   // doing something
>   return;
> }
> ```

Good idea !

**Comment by gaoran10** [comment]
Strange, it seems that there is a check-style problem, but it does not belong to this PR.

```
Error:  src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java:[21] (regexp) RegexpSinglelineJava: Line matches the illegal pattern 'com\.google\.api\.client\.util\.(ByteStreams|Charsets|Collections2|Joiner|Lists|Maps|Objects|Preconditions|Sets|Strings|Throwables)'.
Error:  Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:check (checkstyle) on project pulsar-broker-common: You have 1 Checkstyle violation. -> [Help 1]
```

**Review by gaoran10 — APPROVED** [review]
Lgtm

**Pull request merged**
