### PR TITLE
[feat][website] add local debugging tools shell for website

### PR DESCRIPTION
**Pull request by urfreespace**
Currently, website construction test is not very convenient, you need to merge branches to see the effect, in order to facilitate local testing, I added this tool script, after building the website, you can execute `sh debug-site.sh` locally, you can access the latest build locally Website

### Does this pull request potentially affect one of the following parts:
If yes was chosen, please highlight the changes

Dependencies (does it add or upgrade a dependency): (no)
The public API: (no)
The schema: (no)
The default values of configurations: (no)
The wire protocol: (no)
The rest endpoints: (no)
The admin cli options: (no)
Anything that affects deployment: (no)

### Documentation
Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Review by tuteng — COMMENTED** [review]
LGTM, please add introduction in readme file

**Comment by urfreespace** [comment]
> LGTM, please add introduction in readme file

@tuteng done, PTAL, thanks

**Comment by Anonymitaet** [comment]
As we discussed just now, we do not add the instructions to READ.ME now since there might be a better and simpler way to handle this. I'll preview the local changes and need help from @urfreespace later, and then write down the instructions.

**Comment by Anonymitaet** [comment]
@tuteng could you please help review this PR? Thanks

**Review by tuteng — APPROVED** [review]

**Pull request merged**
