### PR TITLE
[Client] Consumer for a single partition of a PartitionedTopic should be set with correct partitionIndex

### LINKED ISSUE #4586: [Consumer] Subscribe and read from a single partition of a PartitionedTopic will get MessageId's partitionIdx as -1
When we subscribe to a single partition from a partitioned topic, received messages will have all their `MessageId`'s `partitionIndex` as -1, instead, they should have `partitionIdx` set correctly.

### PR DESCRIPTION
**Pull request by yjshen**
This PR fixes #4586 by getting `partitionIndex` from topic name.

### CODE REVIEW

**Comment by yjshen** [comment]
@codelipenghui Test added, PTAL, thanks!

**Comment by yjshen** [comment]
run java8 tests

**Comment by yjshen** [comment]
run cpp tests

**Comment by yjshen** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Pull request merged**
