### PR TITLE
[admin-client] 'rebalance' command for functions worker

### PR DESCRIPTION
**Pull request by nicoloboschi**
### Motivation

The `rebalance` feature is currently exposed only to the REST api. 
It can be useful to have this command in the Admin CLI because the rebalance work is performed only by leader of Functions workers so the client needs to eventually follow redirects and the user may not be aware.
The Admin CLI follow the redirect under the hood  

### Modifications

* Added a new command `bin/pulsar-admin functions-worker rebalance` (no parameters needed)
* Added a unit test to verify the REST api is triggered

Notes:
* the user doesn't need to specify the functions worker leader
* it works with and without enabling authentication

### Does this pull request potentially affect one of the following parts:

 - The admin cli options: (yes) -> new command

### Documentation

- [x] `no-need-doc`

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
LGTM

I left one small nit, please fix

**Comment by nicoloboschi** [comment]
@lhotari @michaeljmarshall @codelipenghui PTAL

**Review by lhotari — APPROVED** [review]
LGTM

**Review by congbobo184 — APPROVED** [review]

**Pull request merged**
