### PR TITLE
[improve][ci]Add "pip" into the scope of the pull request title check rule

### PR DESCRIPTION
**Pull request by poorbarcode**
### Motivation

Per the PIP process (new) as you see [here](https://github.com/apache/pulsar/blob/master/pip/README.md) title should start with "|[pip][design] PIP- -"  But the check rule of PR title is not supported

### Modifications

Add new a scope `pip` for the check pull request title

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: x

### CODE REVIEW

**Review by coderzc — APPROVED** [review]

**Review by codelipenghui — COMMENTED** [review]
Should we add pip under the scope section? You might also need to fix typos in the pip, and improve the pip to make it easy to read.

Now the `type` looks like `actions`. Maybe we can consider adding `create` under the type section, it will work for any documentation changes. E.g. create a document, improve a document, fix a bug, refactor the document or code, create a pip, fix the pip.

cc @Anonymitaet @tisonkun WDYT?

**Comment by tisonkun** [comment]
> Should we add pip under the scope section? You might also need to fix typos in the pip, and improve the pip to make it easy to read.
> 
> Now the `type` looks like `actions`. Maybe we can consider adding `create` under the type section, it will work for any documentation changes. E.g. create a document, improve a document, fix a bug, refactor the document or code, create a pip, fix the pip.
> 
> cc @Anonymitaet @tisonkun WDYT?

Originally I suggest a conventional commit like spec so that we don't reinvent all these concepts. In conventional commit spec PIPs can be regarded as `docs` since they are design docs.

Scopes, IMO, need not to be required but at the author preference. Unless we make use of that field, it won't be valuable.

**Comment by Anonymitaet** [comment]
To make rules as simple and easy to use as possible, how about just adding a scope `pip`? 

Use cases:
- If creating a PR regarding the PIP docs, we can name it as "[feat][pip] add a **PIP design doc** for xxx".
- If creating code PRs to implement this PIP, we can name it as, e.g., "[feat][broker] **PIP-xxx** add xxx" or "[improve][broker] **PIP-xxx** improve xxx". Since the PIP NO. is added in the title, others can know they are code PRs related to this PIP.

**Comment by asafm** [comment]
I tried hard to develop a search string that would capture all Pull Requests, which are PIPs, so I decided on `[pip][design]` since it was unique enough.
If we can automatically add a label "pip" to our agreed-upon prefix, whatever it may be (only the create ones, not the update ones), then I can alter the readme to say that you search by type PRs with the label PIP.

If this is the case, then I'm ok with calling it `[docs][pip] PIP-xyz: {short description}` and `[docs][pip] Update PIP-xyz: {short description of update}`

**Comment by poorbarcode** [comment]
@asafm 

> If we can automatically add a label "pip" to our agreed-upon prefix, whatever it may be (only the create ones, not the update ones), then I can alter the readme to say that you search by type PRs with the label PIP.

In most cases, it is OK. If the author of the proposal is not a committer, this will require the help of others.

Why add the label only to the creation, not the modification? Maybe need two labels just like `pip/create` and `pip/update`?

> If this is the case, then I'm ok with calling it [docs][pip] PIP-xyz: {short description} and [docs][pip] Update PIP-xyz: {short description of update}

It's frustrating that the first identifier means what action you want to do, but `docs` is not an action. The action contains these enums: `cleanup, feat, fix, improve, refactor, revert`

**Comment by asafm** [comment]
> In most cases, it is OK. If the author of the proposal is not a committer, this will require the help of others.
It's not.
If one person a PR and nobody were fast enough to add a label, then the 2nd person would get the number wrong because that new pip will not appear in the search results under the label. We must add a label automatically or stick to the prefix I chose, which is unique. I prefer to go with the automated way.

@tisonkun Can we add a GitHub action based on the PR name, or even better - based on the addition to the pip directory, we add the relevant pip label?

**Comment by tisonkun** [comment]
> based on the addition to the pip directory, we add the relevant pip label?

This is of course possible. You can file an issue and ping me.

**Comment by asafm** [comment]
Given what @tisonkun and assuming we will have https://github.com/apache/pulsar/issues/20712 then I'm ok with PIPs starting with "[improve][pip]".

WDYT?

**Comment by tisonkun** [comment]
> I'm ok with PIPs starting with "[improve][pip]".

I'm OK with this one also.

**Comment by poorbarcode** [comment]
@asafm  @tisonkun 

> I'm ok with PIPs starting with "[improve][pip]".

fixed. thanks

**Comment by asafm** [comment]
> Given what @tisonkun and assuming we will have #20712 then I'm ok with PIPs starting with "[improve][pip]".
> 
> WDYT?

@tisonkun ?

**Review by tisonkun — APPROVED** [review]

**Pull request merged**
