### PR TITLE
[fix][broker]Fast return if ack cumulative illegal

### PR DESCRIPTION
**Pull request by AnonHxy**
### Motivation

* It should fast return if ack type is Cumulative  with illegal `CommandAck`

### Modifications

* Return if `ack.getMessageIdsCount() != 1` or `Subscription.isIndividualAckMode(subType)`

### Verifying this change

- [x] Make sure that the change passes the CI checks.
- Add UT for this case `org.apache.pulsar.broker.service.MessageCumulativeAckTest`

### Documentation

- [x] `no-need-doc`

### CODE REVIEW

**Review by codelipenghui — COMMENTED** [review]
The change looks good. Could you please help add a test?

For the changes of line:382, it should be a bug fix and the behavior changed?
Before this change, if cumulative ack happened on a Shared subscription, the ack will take effect, but after this change, the ack will not take effect if the request with only one ack.

https://github.com/apache/pulsar/blob/e2fa1898f7e9a38b1743b2abf21c87eafe126ee2/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java#L373-L383

**Comment by AnonHxy** [comment]
Add UT,  PTAL @codelipenghui

**Review by codelipenghui — APPROVED** [review]

**Review by hangc0276 — APPROVED** [review]

**Review by coderzc — APPROVED** [review]

**Review by shibd — APPROVED** [review]

**Review by mattisonchao — APPROVED** [review]

**Pull request merged**
