### PR TITLE
improve issue templates wordings

### PR DESCRIPTION
**Pull request by tisonkun**
This is a follow-up to #16902. See https://github.com/apache/pulsar/pull/16902#discussion_r977204882.

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [x] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### Matching PR in forked repository

N/A

### CODE REVIEW

**Comment by tisonkun** [comment]
ping @lhotari @nicoloboschi @dave2wave

**Review by lhotari — APPROVED** [review]

**Comment by lhotari** [comment]
@tisonkun 
Please add these 2 lines in `.github/changes-filter.yaml` under `docs:`
```
  - '.github/changes-filter.yaml'
  - '.github/ISSUE_TEMPLATE/**'
```
that would allow skipping the tests when issue templates or changes-filter.yaml are edited.

**Comment by tisonkun** [comment]
@lhotari Yes. I'm thinking of it. Adding them now.

**Comment by lhotari** [comment]
> @lhotari Yes. I'm thinking of it. Adding them now.

@tisonkun oh sorry, I pushed already since I wanted to merge this now. :)

**Comment by tisonkun** [comment]
@lhotari never mind. It does no harm :)

**Pull request merged**
