### PR TITLE
use originalAuthMethod on originalAuthChecker

### LINKED ISSUE #6873: Wrong auth provider check on broker's originalRole auth check
**Describe the bug**
If a proxy has a auth provider A, and the proxy to broker has a B auth provider usage. The broker originalAuth check uses B instead of A.

### PR DESCRIPTION
**Pull request by KannarFr**
Fixes #6873

Use originalAuthMethod on originalAuthProvider check.

### CODE REVIEW

**Comment by KannarFr** [comment]
@sijie can you review it? Do it cover all cases?

**Comment by jiazhai** [comment]
@KannarFr Thanks for the fix. Seems there is no test cover this case, Would you please also help provide a test for this case?

**Comment by jiazhai** [comment]
> @sijie can you review it? Do it cover all cases?

This is the only place that I can see.

**Comment by KannarFr** [comment]
@jiazhai @sijie We have an interesting issue, the original auth method & auth data are empty. Only the original principal is filled.

**Comment by KannarFr** [comment]
Nvm, missed: `forwardAuthorizationCredentials=true`.

**Pull request merged**
