### PR TITLE
[docs] [ISSUE 8262] [ISSUE 7625] Update request body description of sinks REST APIs

### LINKED ISSUE #7625: [docs] request body description of sinks REST APIs is wrong
See: https://pulsar.apache.org/sink-rest-api/?version=2.6.0#operation/registerSink

The doc of request body is 

> A JSON value presenting config payload of a Pulsar Sink. All available configuration options are:

And the request sample is:

```json
{  
	"classname": "org.example.MySinkTest",
	"inputs": ["persistent://public/default/sink-input"],
	"processingGuarantees": "EFFECTIVELY_ONCE",
	"parallelism": 10
}
```

But if I changed the header to `Content-Type: application/json` and passed a JSON body, then a 415 response would be received.

From the [source code](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SinksBase.java#L71):

```java
    @Path("/{tenant}/{namespace}/{sinkName}")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    public void registerSink
```

the media type is `multipart/form-data`, and the body contains two parts. The JSON presentation of a `SinkConfig` object is just one part, the other part should be the octet stream of a NAR file or an url of package.

The same goes for `updateSink` REST API.

### LINKED ISSUE #8262: The REST API  to create source is not correct
I found params it need is "sourceConfig" and "url" ,but the REST API documents is not true,

[https://pulsar.apache.org/source-rest-api/?version=2.6.1&apiversion=v3#operation/registerSource](https://pulsar.apache.org/source-rest-api/?version=2.6.1&apiversion=v3#operation/registerSource)

### PR DESCRIPTION
**Pull request by sijia-w**
Fixes #8262 
Fixes #7625

Thanks @BewareMyPower for providing the code.

### CODE REVIEW

**Comment by sijia-w** [comment]
@tuteng Can you please help review the changes and check the preview page? Many thanks.

**Comment by BewareMyPower** [comment]
LGTM, but I think it's better to upload the preview image.

**Comment by sijia-w** [comment]
I'll upload the preview soon.

**Comment by sijia-w** [comment]
@BewareMyPower In the preview page, only the first value in the screenshot is displayed. Further modification is needed. 
image
image

Many thanks to @tuteng @urfreespace for their help in previewing the changes.

**Comment by codelipenghui** [comment]
The pr had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale. It seems a framework issue that all form data param's name are 'body'.

**Pull request closed without merging**
