### PR TITLE
[improve][client] Move acknowledge APIs to another interface and improve docs

### PR DESCRIPTION
**Pull request by BewareMyPower**
### Motivation

Currently there are many acknowledge methods in `Consumer` interface, including:
- 7 overloads of `acknowledgeAsync`
- 4 overloads of `acknowledge`
- 3 overloads of `acknowledgeCumulativeAsync`
- 2 overloads of `acknowledgeCumulative`

The JavaDocs of these APIs are also massive and duplicated. For example, some terms are not for application users like "pending ack", which should not appear in API Docs.

### Modifications

- Add a new interface `MessageAcknowledger` and move the acknowledge APIs into this new interface.
- Improve the API docs. For some overload methods, change them to default methods so that duplicated description can be avoided.

The new API docs should be much more clear than before. Though this PR adds a new API, the API compatibility is guaranteed.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [x] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] Anything that affects deployment

### Documentation

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/BewareMyPower/pulsar/pull/9

### CODE REVIEW

**Comment by BewareMyPower** [comment]
@eolivelli I wrote a function just now with the 2.10.2 dependency.

```java
package org.example;

import org.apache.pulsar.functions.api.Context;
import org.apache.pulsar.functions.api.Function;

public class StringLengthExample implements Function<String, Integer> {

    @Override
    public Integer process(String input, Context context) throws Exception {
        return input.length();
    }
}
```

```xml
    <dependency>
      <groupId>org.apache.pulsar</groupId>
      <artifactId>pulsar-functions-api</artifactId>
      <version>2.10.2</version>
    </dependency>
```

Then I created the function in the branch of this PR and it works well.

```bash
./bin/pulsar-admin functions create \
 --jar ./PulsarFunctionDemo-1.0-SNAPSHOT.jar \
 --classname org.example.StringLengthExample \
 --tenant public \
 --namespace default \
 --name word-count \
 --inputs persistent://public/default/sentences \
 --output persistent://public/default/count
```

```bash
./bin/pulsar-client produce sentences -m "hello world java"
```

```bash
$ ./bin/pulsar-client consume -s sub count -n 0
...
----- got message -----
key:[null], properties:[__pfn_input_msg_id__=CAsQADAA, __pfn_input_topic__=persistent://public/default/sentences], content:16
```

Could it verify the API and binary compatibility?

**Comment by BewareMyPower** [comment]
@eolivelli Is there any more concern? If you concerned about the binary compatibility, from https://docs.oracle.com/javase/specs/jls/se7/html/jls-13.html, we can see 

> here is a list of some important binary compatible changes that the Java programming language supports:
> ...
> Moving a method upward in the class hierarchy.

We can also have a simple verification like:

```
.
├── AImpl.java
├── v0
│   └── A.java
└── v1
    ├── A.java
    └── F.java
```

where `AImpl` implements the interface `A`.

```
$ cat v0/A.java
public interface A {
    void f();
    void f(int x);
    void g();
}
$ cat v1/A.java
public interface A extends F {
    void g();
}
$ cat v1/F.java
public interface F {
    void f(int x);
    default void f() {
        f(100);
    }
}
$ javac AImpl.java v0/A.java
$ java -classpath $PWD/v0:$PWD AImpl
f()
f(1)
g()
$ javac v1/*.java
$ java -classpath $PWD/v1:$PWD AImpl
f()
f(1)
g()
```

**Review by tisonkun — APPROVED** [review]
This can be a good refactor to go. To see the value of separating interfaces, we can actually mock (write test class) against the narrow interface in testing code.

**Review by eolivelli — APPROVED** [review]
Lgtm

Thanks for double checking

**Review by codelipenghui — APPROVED** [review]

**Review by Technoboy- — APPROVED** [review]

**Pull request merged**
