### PR TITLE
#7628 - change to jetty bom in root pom

### LINKED ISSUE #7628: Use the jetty bom instead of listing all of the dependencies in the root pom
**Describe the bug**
 Use the [jetty-9.4.29.v20200521](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-bom/9.4.29.v20200521/jetty-bom-9.4.29.v20200521.pom) bom instead of listing all of the dependencies in the root pom

Will create similar issues for netty, jersey, jackson dependencies so that the changes are reviewed and goes thru CI independently.

### PR DESCRIPTION
**Pull request by vcottagiri**
Fixes #7628

Also see #7638 & #7630

### CODE REVIEW

**Comment by vcottagiri** [comment]
I will look into the failures

**Comment by vcottagiri** [comment]
Ran the failing test using the pulsar-build docker image. 
`mvn -B -ntp test -pl pulsar-broker -Dinclude='org/apache/pulsar/client/impl/**/*.java`
Tried a few times - It is not consistent - passes/fails intermittently.

**Comment by vcottagiri** [comment]
@merlimat , @sijie - could you please review this PR

**Comment by tisonkun** [comment]
Closed by https://github.com/apache/pulsar/pull/13716.

**Pull request closed without merging**
