### PR TITLE
[fix][broker] Disable EntryFilters for system topics

### PR DESCRIPTION
**Pull request by lhotari**
### Motivation

Applying EntryFilters for system topics is not very useful and could cause problems.
I noticed this while investigating the flaky AdminApi2Test. 

### Modifications

Skip applying entry filters for system topics.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by michaeljmarshall — APPROVED** [review]

**Review by mattisonchao — APPROVED** [review]

**Comment by mattisonchao** [comment]
IMO, We should consider a new way to handle the system topic because we do a lot of similar logic to filter system topics. :(

**Review by Technoboy- — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
+1

**Comment by michaeljmarshall** [comment]
> IMO, We should consider a new way to handle the system topic because we do a lot of similar logic to filter system topics. :( 
> 
> 
> 
> Not only the entry filter but also some policies etc.

I was mentioning the same thing to @lhotari earlier today. This is one reason I have pushed for a more formal definition of system topics on the ML over the past two years.

At the moment, their design feels very accidental instead of intentional. System topics continue to get more exceptions, and we continue to add dependencies upon the system topic concept.

Maybe we should restart a discussion on this topic.

**Comment by lhotari** [comment]
> > IMO, We should consider a new way to handle the system topic because we do a lot of similar logic to filter system topics. :(
> > Not only the entry filter but also some policies etc.
> 
> I was mentioning the same thing to @lhotari earlier today. This is one reason I have pushed for a more formal definition of system topics on the ML over the past two years.
> 
> At the moment, their design feels very accidental instead of intentional. System topics continue to get more exceptions, and we continue to add dependencies upon the system topic concept.
> 
> Maybe we should restart a discussion on this topic.

@mattisonchao @michaeljmarshall +1. Yes, it would be good to restart it.

In KOP there are topics like `__transaction_state` and `__consumer_offsets`. These don't seem to be system topics from Pulsar's perspective at the moment. That's another example of more exceptions.

**Review by RobertIndie — APPROVED** [review]

**Comment by lhotari** [comment]
For some reason this PR isn't picking up the recent changes I pushed to the branch. That happened in another PR a while ago. Let's see if I'll need to create a new PR to pick up the changes.

**Comment by lhotari** [comment]
oh, GitHub Status page shows that there are on-going issues: https://www.githubstatus.com/

**Pull request merged**
