### PR TITLE
[Doc] add metrics for the total non contiguous deleted messages range

### PR DESCRIPTION
**Pull request by Sunny-Island**
### Motivation
Add docs of #10638

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@Sunny-Island thanks for your contribution. 
Do we need to update the docs in the [Metrics](https://pulsar.apache.org/docs/en/next/reference-metrics/#broker) Chapter?

**Comment by Anonymitaet** [comment]
@Sunny-Island need to add it to 2.7.3 docs as well?

**Comment by Sunny-Island** [comment]
I think we should update all metrics not shown here, including #9618

**Comment by Sunny-Island** [comment]
I think so. Could you show me the folder path of 2.7.3 docs? I can't find it.

**Comment by Anonymitaet** [comment]
> I think so. Could you show me the folder path of 2.7.3 docs? I can't find it.

2.7.3 doc is not generated yet https://github.com/apache/pulsar/issues/10665. Will keep you updated once it makes progress.

**Review by Anonymitaet — APPROVED** [review]

**Pull request merged**
