### PR TITLE
fix github pull request template comment typo

### PR DESCRIPTION
**Pull request by yittg**
just fix this particular template comment mark, :)

cc @sijie

### CODE REVIEW

**Comment by yittg** [comment]
@sijie thanks, i'm new here, how would i do to trigger this PR to be merged, or nothing need, :)

**Comment by sijie** [comment]
you can use " retest this please " to trigger all the three jenkins jobs.

**Comment by yittg** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by yittg** [comment]
@sijie seems the UT is a bit unstable :), and many sleep-wait that waste much time. run java8 tests again.

**Comment by sijie** [comment]
@yittg yes tests are flaky especial the ASF jenkins server is in a shared environment where there are many variants.

**Comment by sijie** [comment]
// "Couldn?t find any executable in /home/jenkins/tools/maven/apache-maven-3.5.0"

run java8 tests

**Pull request merged**
