### PR TITLE
[broker] Optimize deduplicationSnapshotIntervalSeconds with HierarchyTopicPolicies

### PR DESCRIPTION
**Pull request by Jason918**
Master Issue: #13756

### Motivation

See #13756

### Modifications

Add `deduplicationSnapshotIntervalSeconds` in HierarchyTopicPolicies.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is already covered by existing tests, such as TopicDuplicationTest.java 

Some checklist for updating topic policy with `HierarchyTopicPolicies`.
- [x] Broker level value set. And if it's dynamic (no).
- [x] Namespace level value updated. 
- [x] Topic level value updated.
- [x] Pre-existing unit test covers this change and updated to verify this change.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 
  
- [x] `no-need-doc` 

Code optimization.

### CODE REVIEW

**Review by mattisonchao — APPROVED** [review]

**Comment by mattisonchao** [comment]
This PR needs to wait for #13772 to be merged, then close and reopen it.

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@Jason918 Please check the checkstyle violations

**Pull request merged**
