### PR TITLE
Check if metadata write size is right

### PR DESCRIPTION
**Pull request by casuallc**
### Motivation

Should we check metadata real write size in `Command` to avoid some error like #13699 ?

### Modifications

Add write size check.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 
  
- [x] `no-need-doc`

### CODE REVIEW

**Review by Jason918 — COMMENTED** [review]
This change make sense to me.
But it's not obvious to me what side affect it brings if we throws Exception from here. Please help verify this.

**Comment by casuallc** [comment]
>

**Comment by casuallc** [comment]
> This change make sense to me. But it's not obvious to me what side affect it brings if we throws Exception from here. Please help verify this.

There is no affect to current version. 
It would avoid these mistake on new feature.

**Comment by tisonkun** [comment]
Closed. Since this is a third-party dependency, I tend to either trust it or loop until flush all content, instead of throwing a runtime exception on failure.

**Pull request closed without merging**
