### PR TITLE
[Security] Add configuration for running OWASP Dependency Check for all modules

### PR DESCRIPTION
**Pull request by lhotari**
### Motivation

[OWASP Dependency-Check](https://owasp.org/www-project-dependency-check/) is a Software Composition Analysis (SCA) tool that attempts to detect publicly disclosed vulnerabilities contained within a project’s dependencies.

This PR adds basic configuration for `org.owasp:dependency-check-maven` maven plugin and makes it operational in the apache/pulsar project. This a starting point. Later on,  it's possible to improve this further and introduce a scheduled job to automate the checking and fail the job if a new critical or high vulnerability is detected.

### Modifications

Add necessary maven profiles and configuration so that it's possible to run the dependency-check independently for all projects.

This is the way to run the dependency check for manual inspection:
```
# run dependency check for all projects
./build/pulsar_ci_tool.sh dependency_check
# open the html report for all modules in a browser
open target/dependency-check-report.html
# open the html report for Pulsar server distribution (excluding Presto/Pulsar SQL) in a browser
open distribution/server/target/dependency-check-report.html
```

### CODE REVIEW

**Comment by lhotari** [comment]
@aahmed-se please review

**Review by merlimat — APPROVED** [review]

**Pull request merged**
