### PR TITLE
[hotfix] fix problem caused by concurrent merge

### PR DESCRIPTION
**Pull request by aloyszhang**
### Motivation
Currently, the master branch is broken due to PR #9444 and #9302 merged concurrently. 
This PR fixes this problem.

### CODE REVIEW

**Comment by lhotari** [comment]
@sijie please prioritize merging this PR since the master branch is currently broken and this PR fixes it.

**Review by merlimat — APPROVED** [review]

**Comment by merlimat** [comment]
There appear to still be a test that's failing all the time: https://github.com/apache/pulsar/pull/9546/checks?check_run_id=1864571680

**Review by sijie — APPROVED** [review]

**Pull request merged**
