### PR TITLE
[cleanup][broker]Cleanup DispatchRateLimiter isDispatchRateNeeded()

### PR DESCRIPTION
**Pull request by AnonHxy**
### Motivation

* Remove `isDispatchRateNeeded()` and `getTopicPolicyDispatchRate()` and `isDispatchRateNeeded()` in `DispatchRateLimiter`, because it is only invoked by UT to mock. 

### Modifications

* Remove `isDispatchRateNeeded()` and `getTopicPolicyDispatchRate()` and `isDispatchRateNeeded()`  in  `DispatchRateLimiter`

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

  
- [x] `doc-not-needed`

### CODE REVIEW

**Review by Jason918 — APPROVED** [review]

**Comment by Jason918** [comment]
@Technoboy- PTAL

**Review by Technoboy- — APPROVED** [review]

**Review by gaoran10 — APPROVED** [review]
LGTM

**Pull request merged**
