### PR TITLE
WIP: Upgrade Mockito to 4.6.1

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

We have been seeing several weird test errors involving mock objects failure to construct. Updating to latest Mockito version to pick up all the new fixes and improvements.
- [x] `doc-not-needed`

### CODE REVIEW

**Review by Shoothzj — APPROVED** [review]

**Review by Demogorgon314 — APPROVED** [review]

**Comment by Technoboy-** [comment]
Need to update buildtools -> pom.xml

**Review by hangc0276 — COMMENTED** [review]
We also need to upgrade the version here.
https://github.com/apache/pulsar/blob/d61b06ab558c5a5e8586bdd345931d3c32bd75d3/buildtools/pom.xml#L53

**Comment by lhotari** [comment]
> We have been seeing several weird test errors involving mock objects failure to construct. Updating to latest Mockito version to pick up all the new fixes and improvements.

This is indeed an annoying problem. [Mockito's FAQ about thread safety](https://github.com/mockito/mockito/wiki/FAQ#is-mockito-thread-safe):

> 
> For healthy scenarios Mockito plays nicely with threads. For instance, you can run tests in parallel to speed up the build. 
> Also, you can let multiple threads call methods on a shared mock to test in concurrent conditions. Check out a 
> [`timeout()`](http://www.javadoc.io/page/org.mockito/mockito-core/latest/org/mockito/Mockito.html#22) feature for testing concurrency.
> 
> However Mockito is only thread-safe in healthy tests, that is tests without multiple threads stubbing/verifying a shared mock.
> Stubbing or verification of a shared mock from different threads is NOT the proper way of testing because it will always lead 
> to intermittent behavior. In general, mutable state + assertions in multi-threaded environment lead to random results. If you 
> do stub/verify a shared mock across threads you will face occasional exceptions like: `WrongTypeOfReturnValue`, etc.

@merlimat  What are the problems that we are seeing?

**Comment by leizhiyuan** [comment]
```
Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /Users/runner/work/pulsar/pulsar/pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/InMemoryDeliveryTrackerTest.java:[27,1] cannot find symbol
  symbol:   static verifyZeroInteractions
  location: class org.mockito.Mockito
Error:  /Users/runner/work/pulsar/pulsar/pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java:[23,1] cannot find symbol
  symbol:   static anyObject
```

some methods were deleted in new version.

**Comment by tisonkun** [comment]
Closed as stale and conflict. Please rebase and resubmit the patch if it's still relevant.

**Pull request closed without merging**
