### PR TITLE
[Issue-11270] Change ContextClassLoader to NarClassLoader in ProtocolHandler

### LINKED ISSUE #11270: Use NarClassLoader in protocol hander callbacks.
**Is your enhancement request related to a problem? Please describe.**
I am working on a new protocol handler for an existing mq implementation.
ClassNotFoundException occurs when I am calling methods like `com.fastjson.JSON.parseObject("some json str", MyConfig.class)`. This happens because the  MyConfig.class is dynamically loaded by a NarClassLoader in protocol hander mechanism, but current thread calling `ProtocolHandler::initialize` uses the default class load in pulsar.

**Describe the solution you'd like**
IMHO, Maybe it's not very elegant for protocol handler to handle class loader issue in its own project?

As there is an ProtocolHandlerWithClassLoader object in each protocol handlers, I am suggesting change the thread default class loader to the NarClassLoader before we call interfaces in ProtocolHandler.

**Describe alternatives you've considered**
Currently, I am getting the NarClassLoader through `MyProtocolHandler.class.getClassLoader()`.
I think it's a bit of tricky.

**Additional context**

### PR DESCRIPTION
**Pull request by Jason918**
Fixes #11270

### Motivation

See #11270 

### Modifications

Change context class loader through `Thread.currentThread().setContextClassLoader(classLoader)` before every protocol handler callback, and change it back to original class loader afterwards.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:

see new test case in org.apache.pulsar.broker.protocol.ProtocolHandlerWithClassLoaderTest#testClassLoaderSwitcher.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@Jason918 
thanks for your contribution. For this PR, do we need to update docs?

**Comment by Jason918** [comment]
> thanks for your contribution. For this PR, do we need to update docs?

@Anonymitaet Nop, I think it's transparent to the user and developer. Just fixing some conner issue.

**Review by codelipenghui — APPROVED** [review]

**Review by sijie — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
LGTM


tagging @merlimat @jerrypeng as we are working on the "classpath" problem for Pulsar IO

**Pull request merged**
