### PR TITLE
[ci] bot commands may have leading whitespace

### PR DESCRIPTION
**Pull request by tisonkun**
### Motivation

Bot commands may have leading whitespace, and we trim whitespaces in https://github.com/apache/pulsar-test-infra/pull/54.

### Modifications

Replace strict `startsWith` with `contains`.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

- [x] `doc-not-needed`

### CODE REVIEW

**Comment by Shoothzj** [comment]
what would happended, if I suggest some one to use command, like this comment?
```
/pulsarbot
```

**Comment by tisonkun** [comment]
@Shoothzj in the pulsarbot actions, we already validate input as:

```shell
if [[ ${COMMENT_BODY} != "${BOT_COMMAND_PREFIX}"* ]]; then
    echo "Not a pulsarbot command, skipping it ..."
    exit
fi

read -r -a commands <<< "${COMMENT_BODY}"
BOT_COMMAND=${commands[1]}
CHECK_NAME=""
if [ "${BOT_COMMAND}" == "rerun-failure-checks" ]; then
    CHECK_NAME="_all"
elif [ "${BOT_COMMAND}" == "run-failure-checks" ]; then
    CHECK_NAME="_all"
elif [ "${BOT_COMMAND}" == "run" ]; then
    CHECK_NAME=${commands[2]}
elif [ "${BOT_COMMAND}" == "rerun" ]; then
    CHECK_NAME=${commands[2]}
else
    echo "Invalid bot command '${BOT_COMMAND}', skip ..."
    exit
fi

if [[ "${CHECK_NAME}" == "" ]]; then
    echo "Invalid check name '${CHECK_NAME}', skip ..."
    exit
fi
```

Previously, we add an early filter in workflow file as `startsWith(..., '/pulsarbot')`. However, contributor's comments are likely to contain extra whitespace, such as:

```

/pulsarbot run-failure-checks

```

In https://github.com/apache/pulsar-test-infra/pull/54 I create patch to trim all whitespace but the script will still validate commands. If we keep the filter as `startsWith`, commands with leading whitespace will be skipped.

**Comment by tisonkun** [comment]
cc @michaeljmarshall

**Review by codelipenghui — APPROVED** [review]

**Comment by Technoboy-** [comment]
@tisonkun Please rebase

**Comment by tisonkun** [comment]
@Technoboy- updated.

**Review by Technoboy- — APPROVED** [review]

**Pull request merged**
