### PR TITLE
Remove query parameter authoritative for partitions API

### PR DESCRIPTION
**Pull request by liketic**
The parameter ```authoritative``` for list partitions API was never been used. We can remove it now.

### CODE REVIEW

**Comment by merlimat** [comment]
@liketic There's a compilation error for tests 

```
2019-05-13\T\15:45:34.827 [ERROR] /home/jenkins/jenkins-slave/workspace/pulsar_precommit_cpp/pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java:[106,25] method createPartitionedTopic in class org.apache.pulsar.broker.admin.v2.PersistentTopics cannot be applied to given types;
  required: java.lang.String,java.lang.String,java.lang.String,int
  found: java.lang.String,java.lang.String,java.lang.String,int,boolean
  reason: actual and formal argument lists differ in length
2019-05-13\T\15:45:34.827 [ERROR] /home/jenkins/jenkins-slave/workspace/pulsar_precommit_cpp/pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTest.java:[638,25] method createPartitionedTopic in class org.apache.pulsar.broker.admin.v1.PersistentTopics cannot be applied to given types;
  required: java.lang.String,java.lang.String,java.lang.String,java.lang.String,int
  found: java.lang.String,java.lang.String,java.lang.String,java.lang.String,int,boolean
  reason: actual and formal argument lists differ in length
```

**Comment by liketic** [comment]
Thanks @merlimat , no worries, I'll fix them.

**Comment by merlimat** [comment]
retest this please

**Comment by merlimat** [comment]
retest this please

**Comment by jiazhai** [comment]
retest this please

**Comment by liketic** [comment]
retest this please

**Comment by liketic** [comment]
retest this please

**Comment by jiazhai** [comment]
@liketic Seems the failed [tests](https://builds.apache.org/job/pulsar_precommit_java8/8990/) is related to this change:
```
[[FATAL] A resource model has ambiguous (sub-)resource method for HTTP method PUT and input mime-types as defined by"@Consumes" and "@Produces" annotations at Java methods public void org.apache.pulsar.broker.admin.v1.NonPersistentTopics.createPartitionedTopic(java.lang.String,java.lang.String,java.lang.String,java.lang.String,int,boolean) and public void org.apache.pulsar.broker.admin.v1.PersistentTopics.createPartitionedTopic(java.lang.String,java.lang.String,java.lang.String,java.lang.String,int) at matching regular expression /([^/]+)/([^/]+)/([^/]+)/([^/]+)/partitions. These two methods produces and consumes exactly the same mime-types and therefore their invocation as a resource methods will always fail.; source='org.glassfish.jersey.server.model.RuntimeResource@6690b9fa']
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:394)
	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:315)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:282)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:335)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:178)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:370)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:670)
```

**Comment by liketic** [comment]
Thank you @jiazhai , I even didn't find it. I'll take a look at this failure.

**Comment by liketic** [comment]
run Integration Tests

**Comment by liketic** [comment]
run Integration Tests

**Comment by liketic** [comment]
run Integration Tests

**Pull request merged**
