### PR TITLE
fix misspelling

### PR DESCRIPTION
**Pull request by yangl**
Signed-off-by: YANGLiiN <ielin@qq.com>

### Motivation

zookeeper.conf  Enable Quorum TLS step:  sqlQuorum --> `sslQuorum`
ZKMetadataStore.java  lcaolZkPolicyPath  --> `localZkPolicyPath`

### CODE REVIEW

**Review by michaeljmarshall — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Review by sijie — APPROVED** [review]

**Review by Jennifer88huang — APPROVED** [review]
nice catch

**Review by merlimat — APPROVED** [review]

**Pull request merged**
