### PR TITLE
[fix][broker] Fix incorrect bundle split count metric

### PR DESCRIPTION
**Pull request by Shawyeok**
### Motivation

Suppose there is a non-partitioned topic has more than 1000 producers (1000 is `loadBalancerNamespaceBundleMaxSessions` default value), `pulsar_lb_bundles_split_count` metric will increase constantly due to corresponding bundle reached maxBundleSessions, even the bundle range is 1 (upper - lower) that actually will skip this bundle.

### Modifications

Only increase `pulsar_lb_bundles_split_count` metric if bundle splits succeed.

### Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] Anything that affects deployment

### Documentation

- [x] `doc`

### Matching PR in forked repository

PR in forked repository: https://github.com/Shawyeok/pulsar/pull/2

### CODE REVIEW

**Comment by Shawyeok** [comment]
@hangc0276 Please take a review, thanks.

**Review by codelipenghui — APPROVED** [review]
The change looks good to me.

**Review by hangc0276 — APPROVED** [review]

**Review by Technoboy- — APPROVED** [review]

**Pull request merged**
