### PR TITLE
[pulsar-admin] Add --update-mode to optimize namespace rate policy

### PR DESCRIPTION
**Pull request by yuruguo**
### Motivation
This PR is similar to [12242](https://github.com/apache/pulsar/pull/12242) and mainly adds `--update-mode` option for rate-related commands, including:
- [set-dispatch-rate](https://pulsar.apache.org/tools/pulsar-admin/2.9.0-SNAPSHOT/#-em-set-dispatch-rate-em-)
- [set-subscription-dispatch-rate](https://pulsar.apache.org/tools/pulsar-admin/2.9.0-SNAPSHOT/#-em-set-subscription-dispatch-rate-em-)
- [set-replicator-dispatch-rate](https://pulsar.apache.org/tools/pulsar-admin/2.9.0-SNAPSHOT/#-em-set-replicator-dispatch-rate-em-)
- [set-publish-rate](https://pulsar.apache.org/tools/pulsar-admin/2.9.0-SNAPSHOT/#-em-set-publish-rate-em-)
- [set-subscribe-rate](https://pulsar.apache.org/tools/pulsar-admin/2.9.0-SNAPSHOT/#-em-set-subscribe-rate-em-)

### Documentation  
Automatically generate doc through code
- [x] `doc`

### CODE REVIEW

**Review by eolivelli — DISMISSED** [review]
Lgtm

**Comment by yuruguo** [comment]
@merlimat @lhotari @aahmed-se @k2la @congbobo184 @BewareMyPower @hangc0276 @gaoran10 PTAL

**Comment by yuruguo** [comment]
@merlimat @lhotari @aahmed-se @k2la @congbobo184 @BewareMyPower @hangc0276 @gaoran10 PTAL

**Pull request closed without merging**
