### PR TITLE
[cleanup][broker] Delete unuse metrics of zk_write_latency and zk_read_latency

### PR DESCRIPTION
**Pull request by liangyuanpeng**
### Motivation

clean up unuse metrics of `zk_write_latency` and `zk_read_latency`.

passed CI on self repo CI.
https://github.com/pulsar-sigs/pulsar/pull/2

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup 

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

Need to update docs? 

- [ ] `doc-required` 
  
- [x] `doc-not-needed` 
  
- [ ] `doc` 

- [ ] `doc-complete`

### CODE REVIEW

**Review by Shoothzj — APPROVED** [review]

**Review by tisonkun — COMMENTED** [review]
May I ask how can these metrics become unused? Is there any background for this change?

**Comment by liangyuanpeng** [comment]
> May I ask how can these metrics become unused? Is there any background for this change?


These are legacy code that should be removed after [PIP45](https://github.com/apache/pulsar/wiki/PIP-45%3A-Pluggable-metadata-interface) is complete. The new metrics is  `pulsar_storage_ledger_write_latency`

**Review by merlimat — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]
@liangyuanpeng thanks for your explanation! LGTM.

**Comment by tisonkun** [comment]
@Shoothzj @merlimat shall we merge this PR now?

**Comment by tisonkun** [comment]
@liangyuanpeng I think you may merge the latest master to pass CI.

**Comment by liangyuanpeng** [comment]
@tisonkun Thanks for your update and merged master.


This is just a minor code cleanup that can be merged easily and safely. Please someone review and merge,Thanks.

**Comment by liangyuanpeng** [comment]
Just random ping someone. Thanks.

@lhotari @hangc0276 @michaeljmarshall

**Pull request merged**
