### PR TITLE
Add skip-all command for topic

### LINKED ISSUE #5060: pulsar-admin topics skip-all is missing
**Describe the bug**
According to the pulsar-admin doc, skip-all should work. But it throws unknown command.

**To Reproduce**
pulsar-admin topics skip-all some-topic -s some-sub

**Expected behavior**
Succeeds

**Additional context**
It's available under the persistent command. It appears that the topics command unification commit forgot to add skip-all: https://github.com/apache/pulsar/pull/1634

### PR DESCRIPTION
**Pull request by liketic**
Add ```skip-all``` command for topics. 

Closes #5060

### CODE REVIEW

**Comment by merlimat** [comment]
Skip all is the action already performed by the `clear-backlog` subcommand

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by liketic** [comment]
Thanks @merlimat , maybe we can add an alias for command ```clear-backlog``` ?

**Comment by sijie** [comment]
@liketic #5194 has fixed the documentation.

**Pull request closed without merging**
