### PR TITLE
[branch-2.9][enh][monitor]: add metrics for pulsar web service thread pool

### PR DESCRIPTION
**Pull request by mattisonchao**
### Motivation

Cherry-pick #14742

### CODE REVIEW

**Comment by mattisonchao** [comment]
@tjiuming PTAL :-)

**Comment by dao-jun** [comment]
LGTM

**Comment by tjiuming** [comment]
@mattisonchao LGTM

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@mattisonchao Please check the license issue.

**Comment by mattisonchao** [comment]
@codelipenghui 
It looks like the cherry-pick issue, I need to confirm with @nicoloboschi .

**Pull request merged**
