### PR TITLE
[fix][ci]duplicate `modernizer-maven-plugin` config in pulsar-metadata

### PR DESCRIPTION
**Pull request by youzipi**
duplicate `modernizer-maven-plugin` config in pulsar-metadata

https://github.com/apache/pulsar/pull/17330/files#diff-21a3dc744e69febf161fec4aeb57553f39564ee756cd5a175ac2f8647faf9465R105-R122

maven warn:
```bash
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.apache.pulsar:pulsar-metadata:jar:2.11.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.gaul:modernizer-maven-plugin @ line 166, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
```

### Documentation

- [x] `doc-not-needed`

### CODE REVIEW

**Comment by youzipi** [comment]
@MarvinCai

**Review by tisonkun — APPROVED** [review]
Thanks!

**Review by MarvinCai — APPROVED** [review]

**Review by liangyuanpeng — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Comment by tisonkun** [comment]
@youzipi you can try to merge the nightly master by click the "Update Branch" button and rerun the test.

**Comment by tisonkun** [comment]
"OWASP Dependency Check" is unrelated to this patch.

**Comment by youzipi** [comment]
@hangc0276 @codelipenghui

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
