### PR TITLE
[PIP-82] [pulsar-broker] Add missing permission check, fail update on non-existent ResourceGroup

### PR DESCRIPTION
**Pull request by ravi-vaidyanathan**
### Motivation

Fix a few small issues found during testing and code inspection.

### Modifications

*Added missing check for permissions for certain ResourceGroup operations.
*Check if ResourceGroup exists before proceeding to update in pulsar-admin.

### Verifying this change

- [x] Make sure that the change passes the CI checks.
- [x] tested manually

### Documentation
    
- [x] no-need-doc

### CODE REVIEW

**Comment by ravi-vaidyanathan** [comment]
@jerrypeng @cckellogg

**Review by michaeljmarshall — CHANGES_REQUESTED** [review]
We should add a test to ensure that there are not future regressions.

**Comment by ravi-vaidyanathan** [comment]
> We should add a test to ensure that there are not future regressions.

@michaeljmarshall you are right, so added unit tests.

**Comment by bharanic-dev** [comment]
LGTM

**Review by aahmed-se — APPROVED** [review]

**Pull request merged**
