### PR TITLE
Fix the persistent in topics file

### PR DESCRIPTION
**Pull request by sijia-w**
Modification:
Update the `persistent` in pulsar-admin commands and REST API commands in versioned docs.

### CODE REVIEW

**Comment by Jennifer88huang** [comment]
@tuteng could you please help review this PR? Thank you.

**Review by Huanli-Meng — APPROVED** [review]
LGTM

**Review by zymap — APPROVED** [review]

**Comment by sijia-w** [comment]
This pr is fixed in 10607.

**Pull request closed without merging**
