### PR TITLE
PIP-41 (part-1): Introduce Protocol Handler API

### PR DESCRIPTION
**Pull request by sijie**
*Motivation*

This is the first pull request for implementing PIP-41.

PIP-41: https://github.com/apache/pulsar/wiki/PIP-41%3A-Pluggable-Protocol-Handler

*Modification*

- Introduce the protocol handler API
- Introduce a new field `protocols` in LoadReport
- Add util classes to search and load protocol handlers
- Include the protocol handlers in broker's lifecycle
- Add settings to configure what protocol handlers to load

### CODE REVIEW

**Comment by sijie** [comment]
Tests are coming in  the next commit.

**Comment by sijie** [comment]
I have added the unit tests for newly introduced classes.

**Comment by jiazhai** [comment]
run integration tests

**Comment by aahmed-se** [comment]
@merlimat can you take a look at this

**Pull request merged**
