### PR TITLE
[Issue 14080] Clean up Cleanup NPEs in ``ServerCnxTest ``

### LINKED ISSUE #14080: Cleanup NPEs in ServerCnxTest
**Describe the bug**
The test logs for the `ServerCnxTest` class are filled with NPEs making it hard to read through the logs. The cause of the NPE is the following method:

https://github.com/apache/pulsar/blob/f78fdacdfbf99c80e0dc61c396b70187c631aabf/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BacklogQuotaManager.java#L68-L78

The `namespaceResources` are set to `null` in the following constructor, presumably because we don't have any other values to use for the test.

https://github.com/apache/pulsar/blob/f78fdacdfbf99c80e0dc61c396b70187c631aabf/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/PulsarResources.java#L59-L72

**To Reproduce**
1. Run the tests for `ServerCnxTest` class.

**Expected behavior**
It'd be nice to avoid NPEs in the tests so that our logs are more meaningful.

**Screenshots**
```
2021-11-16T22:37:43,412-0600 [TestNG-method=testCreateProducerTimeoutThenCreateSameNamedProducerShouldFail-1] WARN  org.apache.pulsar.broker.service.BacklogQuotaManager - Failed to read policies data, will apply the default backlog quota: namespace=prop/use/ns-abc
java.lang.NullPointerException: null
	at org.apache.pulsar.broker.service.BacklogQuotaManager.getBacklogQuota(BacklogQuotaManager.java:70) ~[classes/:?]
	at org.apache.pulsar.broker.service.BacklogQuotaManager.getBacklogQuota(BacklogQuotaManager.java:82) ~[classes/:?]
	at org.apache.pulsar.broker.service.persistent.PersistentTopic.getBacklogQuota(PersistentTopic.java:2468) ~[classes/:?]
	at org.apache.pulsar.broker.service.persistent.PersistentTopic.isBacklogQuotaExceeded(PersistentTopic.java:2477) ~[classes/:?]
	at org.apache.pulsar.broker.service.ServerCnx.lambda$handleProducer$21(ServerCnx.java:1193) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108) ~[?:?]
	at org.apache.pulsar.broker.service.ServerCnx.lambda$handleProducer$23(ServerCnx.java:1188) ~[classes/:?]
	at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680) [?:?]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658) [?:?]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094) [?:?]
	at org.apache.pulsar.broker.service.ServerCnx.handleProducer(ServerCnx.java:1145) [classes/:?]
	at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:194) [pulsar-common-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:343) [netty-transport-4.1.68.Final.jar:4.1.68.Final]
	at org.apache.pulsar.broker.service.ServerCnxTest.testCreateProducerTimeoutThenCreateSameNamedProducerShouldFail(ServerCnxTest.java:897) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132) [testng-7.3.0.jar:?]
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45) [testng-7.3.0.jar:?]
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73) [testng-7.3.0.jar:?]
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11) [testng-7.3.0.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

### PR DESCRIPTION
**Pull request by mattisonchao**
Fixes #14080

Master Issue: #14080

### Motivation

see #14080

### Modifications

- Add null check to avoid NPE.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

- [x] `no-need-doc`

### CODE REVIEW

**Comment by mattisonchao** [comment]
@michaeljmarshall  PTAL :)

**Review by Jason918 — APPROVED** [review]

**Review by Shoothzj — APPROVED** [review]

**Review by michaeljmarshall — APPROVED** [review]
LGTM

**Comment by michaeljmarshall** [comment]
> @michaeljmarshall PTAL :)
> 
> I have another idea. We can create some brand new classes that name is `XXXDefaultResources` to return the default value. this way can avoid useless null checks. Let me know what you think. Thanks ~

@mattisonchao - I agree that it feels unfortunate to have to put these extra null checks in classes like this, especially since the `namespaceResources` object is only used in the whole class. Given that the `namespaceResources` class is never going to be `null` in a non-test scenario, we could probably improve the design by implementing a zero valued `NamespaceResources` class. For now, I think this is a good addition.

**Pull request merged**
