### PR TITLE
[improve][metadata] Add tls config for etcd client

### LINKED ISSUE #15205: Pulsar should support cluster metadata store with etcd backend with SSL(https://...)
I hope Pulsar‘s components configuration support etcd with ssl access (metadataStoreUrl can use metadataServiceUri=metadata-store:etcd:**https:**//my-etcd:2379)

In some secure or existing environments, there has been existing a etcd cluster with SSL  authentication。When I use the etcd service for Pulsar cluster medata store, I meet the problem that I can't configure Pulsar cluster for SSL authenticated etcd cluster like https://.....

### PR DESCRIPTION
**Pull request by nodece**
Signed-off-by: Zixuan Liu <nodeces@gmail.com>

Fixes #15205

### Motivation

The etcd metadata doesn't support tls config.

### Modifications

- Add tls config for etcd metadata store
- Add `metadataStoreConfigPath ` to `broker.conf` and `standalone.conf`
- Add `README.md` for etcd test directory

### Verifying this change

- [x] Make sure that the change passes the CI checks.
- Added tls config test

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [x] `doc-required` - Update `metadataStoreConfigPath` description

### CODE REVIEW

**Review by Technoboy- — COMMENTED** [review]
I think the test should use the config file, it can test the whole logic and also demonstrate how to config.

**Comment by nodece** [comment]
> I think the test should use the config file, it can test the whole logic and also demonstrate how to config.

This test includes this, you can check [this](https://github.com/apache/pulsar/pull/15270/files#diff-a0e5839b037c6eafba3bd343c5de940112d46a3c82cfc51e4fd0db44755247f3R44).

**Review by liangyuanpeng — APPROVED** [review]
LGTM

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@nodece Please open a separate PR to add a document for the new configurations, and it's better to provide a config template under the `conf` directory.

**Comment by nodece** [comment]
> @nodece Please open a separate PR to add a document for the new configurations, and it's better to provide a config template under the `conf` directory.

Thanks for your point, I'll open a new PR to do this.

**Review by Jason918 — APPROVED** [review]
LGTM

**Comment by liangyuanpeng** [comment]
@Technoboy-    PTAL,Thanks.

**Review by Technoboy- — APPROVED** [review]

**Comment by momo-jun** [comment]
### Doc status update
Besides PR#16463 mentioning the configs, @nodece will submit a follow-up PR to add docs.

**Pull request merged**
