### PR TITLE
Move Pulsar release related docs to codebase

### PR DESCRIPTION
**Pull request by codelipenghui**
### Motivation

After moving to the pulsar codebase
- Everyone can contribute to the validation doc
- The release process doc update can get reviewers to review

The mailing list discussion: https://lists.apache.org/thread/mv1to079cznkxdldrpoq5518l2ozl5kr
- [x] `doc`

### CODE REVIEW

**Review by tisonkun — COMMENTED** [review]
We may later redirect to these docs from the original wiki pages, instead of holding the content in both places.

**Comment by codelipenghui** [comment]
> We may later redirect to these docs from the original wiki pages, instead of holding the content in both places.

Yes, I have replied to the mailing list.

**Review by tisonkun — APPROVED** [review]
LGTM.

FYI I may try to bring these docs to our site for easy access and better display later.

**Review by Jason918 — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
+1

**Review by mattisonchao — APPROVED** [review]

**Review by Demogorgon314 — APPROVED** [review]

**Review by Shoothzj — APPROVED** [review]

**Pull request merged**
