### PR TITLE
[Doc]Fix document link error

### PR DESCRIPTION
**Pull request by tuteng**
### Motivation

There are currently 404 links to some documents. Fix these problems.

### Modifications

Use the correct file name

### CODE REVIEW

**Comment by tuteng** [comment]
run java8 tests

**Comment by sijie** [comment]
@tuteng there are conflicts in this pull request. Can you please address the conflict?

**Comment by tuteng** [comment]
retest this please

**Comment by tuteng** [comment]
run integrations tests

**Comment by tuteng** [comment]
run integration tests

**Pull request merged**
