### PR TITLE
[Managed Ledger] Resolved race by fixing order of adding OpAddEntry to pendingAddEntries

### PR DESCRIPTION
**Pull request by devinbost**
It looks like it's possible for `pendingAddEntries` to have an `OpAddEntry` instance that hasn't had a `ledgerId` set before `checkAddTimeout()` is called. 
We add the `OpAddEntry` to `pendingAddEntries` here: https://github.com/apache/pulsar/blob/a223cc214be7594e9b37bcbf0b078dc78b157b74/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L716
and set the `ledgerId` later on `OpAddEntry` in that method: https://github.com/apache/pulsar/blob/a223cc214be7594e9b37bcbf0b078dc78b157b74/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L760

If `checkAddTimeout()` is called before the `ledgerId` is set, the `ledgerId` will show as -1 (https://github.com/apache/pulsar/blob/a223cc214be7594e9b37bcbf0b078dc78b157b74/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L3678), and if that's still -1 when the handler reaches `ledgerClosed(..)`, we may not close the ledger that was timing out.

### CODE REVIEW

**Comment by devinbost** [comment]
@lhotari thoughts?

**Comment by Anonymitaet** [comment]
@devinbost thanks for your contribution. For this PR, do we need to update docs?

**Comment by devinbost** [comment]
@Anonymitaet Thanks for asking. I don't think that will be necessary for this PR.

**Comment by devinbost** [comment]
@merlimat ?

**Comment by eolivelli** [comment]
I believe that we should not add the operation to the list until it is fully prepared

**Comment by devinbost** [comment]
@eolivelli I moved the `pendingAddEntries.add(addOperation)` calls to after we're done making changes on the `addOperation` in the different code branches. 

What happens if this block in `[ManagedLedgerImpl].createComplete(..)` is called before the thread processing `pendingAddEntries` has had a chance to process all the operations (for example, if there was backpressure)?
```       if (pendingAddEntries.isEmpty()) {
                STATE_UPDATER.set(this, State.ClosedLedger);
            } else {
                STATE_UPDATER.set(this, State.WriteFailed);
            }
```
(https://github.com/apache/pulsar/blob/380cf924f81a906759811b7a5e861ca66bb2c7ab/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L1403)

Seems like a race... The state could be set to `State.WriteFailed` when in reality the `addOperation` just hasn't been processed yet. If they're set to WriteFailed, what happens? Do they get automatically reprocessed? I wonder if there could be an edge case there.

**Comment by devinbost** [comment]
I think we have more flaky tests.

> Error:  Tests run: 6, Failures: 1, Errors: 0, Skipped: 4, Time elapsed: 14.843 s <<< FAILURE! - in org.apache.pulsar.metadata.ZKSessionTest
> Error:  testReacquireLeadershipAfterSessionLost(org.apache.pulsar.metadata.ZKSessionTest)  Time elapsed: 4.231 s  <<< FAILURE!
> java.lang.AssertionError: expected [null] but found [NoLeader]

Another one that failed earlier was:

> ManagedLedgerTest.testExpiredLedgerDeletionAfterManagedLedgerRestart()

but that test passed for me locally. 

@lhotari FYI.

**Comment by devinbost** [comment]
@eolivelli PTAL. All the tests are passing.

**Comment by devinbost** [comment]
@sijie ?

**Comment by devinbost** [comment]
or @codelipenghui

**Comment by devinbost** [comment]
Due to this race, if the ledger isn't attached to the `addOperation` by the time the op is picked up from `pendingAddEntries`, then we can't run `asyncAddEntry(..)` on the op. But, at that point, I'd expect an NPE to be thrown.

**Comment by codelipenghui** [comment]
The pr had no activity for 30 days, mark with Stale label.

**Pull request closed without merging**
