### PR TITLE
Fix Spellings

### PR DESCRIPTION
**Pull request by aahmed-se**

### CODE REVIEW

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run integration tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
resolved by https://github.com/apache/pulsar/pull/3181

**Pull request closed without merging**
