### PR TITLE
[fix][broker][functions-worker] Ensure prometheus metrics are grouped by type (#8407, #13865)

### LINKED ISSUE #8407: Metrics are not grouped by type
**Describe the bug**
When calling the metrics endpoint I would expect them to be grouped by type. However, some metrics are grouped under the incorrect type header

**To Reproduce**
1. Run Pulsar v2.6.0
2. Fire some messages to topics
3. Access metrics endpoint

**Expected behavior**
All metrics are grouped appropriately.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Docker on MacOS, Amazon Linux on AWS

### LINKED ISSUE #13865: Many Prometheus metrics don't expose type information and/or descriptions
**Describe the bug**

```
pulsar_subscriptions_count{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/metadata",partition="-1"} 0.0 1642717994922
pulsar_producers_count{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/metadata",partition="-1"} 1.0 1642717994922
pulsar_consumers_count{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/metadata",partition="-1"} 0.0 1642717994922
pulsar_rate_in{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/metadata",partition="-1"} 0.0 1642717994922
pulsar_rate_out{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/metadata",partition="-1"} 0.0 1642717994922
pulsar_throughput_in{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/metadata",partition="-1"} 0.0 1642717994922
pulsar_throughput_out{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/metadata",partition="-1"} 0.0 1642717994922
pulsar_storage_size{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/metadata",partition="-1"} 0.0 1642717994922
pulsar_storage_logical_size{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/metadata",partition="-1"} 0.0 1642717994922
pulsar_msg_backlog{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/metadata",partition="-1"} 0.0 1642717994922
pulsar_subscriptions_count{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 1.0 1642717994922
pulsar_producers_count{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_consumers_count{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 1.0 1642717994922
pulsar_rate_in{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_rate_out{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_throughput_in{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_throughput_out{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_average_msg_size{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_size{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_logical_size{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_msg_backlog{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_backlog_size{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_offloaded_size{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_backlog_quota_limit{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 10737418240.0 1642717994922
pulsar_storage_backlog_quota_limit_time{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} -1.0 1642717994922
pulsar_storage_write_latency_le_0_5{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_le_1{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_le_5{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_le_10{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_le_20{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_le_50{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_le_100{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_le_200{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_le_1000{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_overflow{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_count{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_sum{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_le_0_5{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_le_1{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_le_5{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_le_10{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_le_20{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_le_50{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_le_100{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_le_200{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_le_1000{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_overflow{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_count{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_sum{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_entry_size_le_128{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_entry_size_le_512{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_entry_size_le_1_kb{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_entry_size_le_2_kb{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_entry_size_le_4_kb{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_entry_size_le_16_kb{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_entry_size_le_100_kb{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_entry_size_le_1_mb{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_entry_size_le_overflow{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_entry_size_count{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_entry_size_sum{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_out_bytes_total{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1",subscription="participants",consumer_name="c-standalone-fw-localhost-8080:localhost:8080",consumer_id="0"} 0 1642717994922
pulsar_out_messages_total{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1",subscription="participants",consumer_name="c-standalone-fw-localhost-8080:localhost:8080",consumer_id="0"} 0 1642717994922
pulsar_in_bytes_total{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_in_messages_total{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/coordinate",partition="-1"} 0.0 1642717994922
pulsar_subscriptions_count{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_producers_count{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 1.0 1642717994922
pulsar_consumers_count{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_rate_in{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_rate_out{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_throughput_in{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_throughput_out{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_average_msg_size{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_size{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_logical_size{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_msg_backlog{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_backlog_size{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_offloaded_size{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_backlog_quota_limit{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 10737418240.0 1642717994922
pulsar_storage_backlog_quota_limit_time{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} -1.0 1642717994922
pulsar_storage_write_latency_le_0_5{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_le_1{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_le_5{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_le_10{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_le_20{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_le_50{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_le_100{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_le_200{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_le_1000{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_overflow{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_count{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_write_latency_sum{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_le_0_5{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_le_1{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_le_5{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_le_10{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_le_20{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_le_50{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_le_100{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_le_200{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_le_1000{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_overflow{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_count{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_storage_ledger_write_latency_sum{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_entry_size_le_128{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_entry_size_le_512{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_entry_size_le_1_kb{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_entry_size_le_2_kb{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_entry_size_le_4_kb{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_entry_size_le_16_kb{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_entry_size_le_100_kb{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_entry_size_le_1_mb{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_entry_size_le_overflow{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_entry_size_count{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_entry_size_sum{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994922
pulsar_producer_msg_rate_in{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1",producer_name="c-standalone-fw-localhost-8080-scheduler-manager",producer_id="0"} 0.0 1642717994922
pulsar_producer_msg_throughput_in{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1",producer_name="c-standalone-fw-localhost-8080-scheduler-manager",producer_id="0"} 0.0 1642717994923
pulsar_producer_msg_average_Size{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1",producer_name="c-standalone-fw-localhost-8080-scheduler-manager",producer_id="0"} 0.0 1642717994923
pulsar_in_bytes_total{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994923
pulsar_in_messages_total{cluster="standalone",namespace="public/functions",topic="persistent://public/functions/assignments",partition="-1"} 0.0 1642717994923
pulsar_topics_count{cluster="standalone",namespace="public/functions"} 3 1642717994923
pulsar_function_worker_rebalance_strategy_execution_time_ms{cluster="standalone",quantile="0.5",} NaN
pulsar_function_worker_rebalance_strategy_execution_time_ms{cluster="standalone",quantile="0.9",} NaN
pulsar_function_worker_rebalance_strategy_execution_time_ms{cluster="standalone",quantile="1.0",} NaN
pulsar_function_worker_rebalance_strategy_execution_time_ms_count{cluster="standalone",} 0.0
pulsar_function_worker_rebalance_strategy_execution_time_ms_sum{cluster="standalone",} 0.0
pulsar_function_worker_start_up_time_ms_count{cluster="standalone",} 1.0
pulsar_function_worker_start_up_time_ms_sum{cluster="standalone",} 1146.6572
pulsar_function_worker_drain_execution_time_total_ms{cluster="standalone",quantile="0.5",} NaN
pulsar_function_worker_drain_execution_time_total_ms{cluster="standalone",quantile="0.9",} NaN
pulsar_function_worker_drain_execution_time_total_ms{cluster="standalone",quantile="1.0",} NaN
pulsar_function_worker_drain_execution_time_total_ms_count{cluster="standalone",} 0.0
pulsar_function_worker_drain_execution_time_total_ms_sum{cluster="standalone",} 0.0
pulsar_function_worker_stop_instance_process_time_ms{cluster="standalone",quantile="0.5",} NaN
pulsar_function_worker_stop_instance_process_time_ms{cluster="standalone",quantile="0.9",} NaN
pulsar_function_worker_stop_instance_process_time_ms{cluster="standalone",quantile="1.0",} NaN
pulsar_function_worker_stop_instance_process_time_ms_count{cluster="standalone",} 0.0
pulsar_function_worker_stop_instance_process_time_ms_sum{cluster="standalone",} 0.0
pulsar_function_worker_schedule_strategy_execution_time_ms{cluster="standalone",quantile="0.5",} NaN
pulsar_function_worker_schedule_strategy_execution_time_ms{cluster="standalone",quantile="0.9",} NaN
pulsar_function_worker_schedule_strategy_execution_time_ms{cluster="standalone",quantile="1.0",} NaN
pulsar_function_worker_schedule_strategy_execution_time_ms_count{cluster="standalone",} 1.0
pulsar_function_worker_schedule_strategy_execution_time_ms_sum{cluster="standalone",} 0.0246
pulsar_function_worker_start_instance_process_time_ms{cluster="standalone",quantile="0.5",} NaN
pulsar_function_worker_start_instance_process_time_ms{cluster="standalone",quantile="0.9",} NaN
pulsar_function_worker_start_instance_process_time_ms{cluster="standalone",quantile="1.0",} NaN
pulsar_function_worker_start_instance_process_time_ms_count{cluster="standalone",} 0.0
pulsar_function_worker_start_instance_process_time_ms_sum{cluster="standalone",} 0.0
pulsar_function_worker_instance_count{cluster="standalone",} 0.0
pulsar_function_worker_schedule_execution_time_total_ms{cluster="standalone",quantile="0.5",} NaN
pulsar_function_worker_schedule_execution_time_total_ms{cluster="standalone",quantile="0.9",} NaN
pulsar_function_worker_schedule_execution_time_total_ms{cluster="standalone",quantile="1.0",} NaN
pulsar_function_worker_schedule_execution_time_total_ms_count{cluster="standalone",} 1.0
pulsar_function_worker_schedule_execution_time_total_ms_sum{cluster="standalone",} 29.2018
pulsar_function_worker_rebalance_execution_time_total_ms{cluster="standalone",quantile="0.5",} NaN
pulsar_function_worker_rebalance_execution_time_total_ms{cluster="standalone",quantile="0.9",} NaN
pulsar_function_worker_rebalance_execution_time_total_ms{cluster="standalone",quantile="1.0",} NaN
pulsar_function_worker_rebalance_execution_time_total_ms_count{cluster="standalone",} 0.0
pulsar_function_worker_rebalance_execution_time_total_ms_sum{cluster="standalone",} 0.0
pulsar_function_worker_total_function_count{cluster="standalone",} 0
pulsar_function_worker_total_expected_instance_count{cluster="standalone",} 0
pulsar_function_worker_is_leader{cluster="standalone",} 1
...
```

**To Reproduce**

```
curl -L http://localhost:8080/metrics
```

```yaml
version: '3'

services:
  pulsar:
    container_name: pulsar
    image: apachepulsar/pulsar:2.9.1
    command:
    - bash
    - -c
    - >
      bin/apply-config-from-env-with-prefix.py BOOKKEEPER_ conf/bookkeeper.conf &&
      bin/apply-config-from-env-with-prefix.py BROKER_ conf/broker.conf &&
      bin/apply-config-from-env-with-prefix.py STANDALONE_ conf/standalone.conf &&
      exec bin/pulsar standalone
    ports:
    - '6650:6650'
    - '8080:8080'
    environment:
    - BOOKKEEPER_enableStatistics=true
    - BOOKKEEPER_prometheusStatsHttpPort=8080
    - BROKER_exposeTopicLevelMetricsInPrometheus=true
    - BROKER_exposeConsumerLevelMetricsInPrometheus=true
    - BROKER_exposeProducerLevelMetricsInPrometheus=true
    - BROKER_exposeManagedLedgerMetricsInPrometheus=true
    - BROKER_exposeManagedCursorMetricsInPrometheus=true
    - BROKER_exposePublisherStats=true
    - BROKER_exposePreciseBacklogInPrometheus=true
    - BROKER_splitTopicAndPartitionLabelInPrometheus=true
    - STANDALONE_exposeTopicLevelMetricsInPrometheus=true
    - STANDALONE_exposeConsumerLevelMetricsInPrometheus=true
    - STANDALONE_exposeProducerLevelMetricsInPrometheus=true
    - STANDALONE_exposeManagedLedgerMetricsInPrometheus=true
    - STANDALONE_exposeManagedCursorMetricsInPrometheus=true
    - STANDALONE_exposePublisherStats=true
    - STANDALONE_exposePreciseBacklogInPrometheus=true
    - STANDALONE_splitTopicAndPartitionLabelInPrometheus=true
```

**Desktop (please complete the following information):**

 - OS: Windows 10

### PR DESCRIPTION
**Pull request by marksilcox**
Fixes #8407
Fixes #13865

### Motivation

Current broker prometheus metrics are not grouped by metric type which causes issues in systems that read these metrics (e.g. DataDog).

Prometheus docs states "All lines for a given metric must be provided as one single group" - https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md#grouping-and-sorting

Modifications
Updated the namespace and topic prometheus metric generators to group the metrics under the appropriate type header.
Updated function worker stats to include TYPE headers

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:

Added unit test to verify all metrics are grouped under correct type header

### Does this pull request potentially affect one of the following parts:

- Dependencies (does it add or upgrade a dependency): (no)
- The public API: (no)
- The schema: (no)
- The default values of configurations: (no)
- The wire protocol: (no)
- The rest endpoints: (no)
- The admin cli options: (no)
- Anything that affects deployment: (no)

### Documentation

Need to update docs? 

- [X] `doc-not-needed` 
Changes to match prometheus spec

### CODE REVIEW

**Review by asafm — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@marksilcox Sorry, I have to revert this PR since it introduced a memory leak that was detected by a long-running continuous verification test. 

The reproduction steps:

1. Start a standalone
2. Create a partitioned topic (100 partitions)
3. Start producer `bin/pulsar-perf produce test -r 100 -bm 1 -mk random`
4. Start consumer `bin/pulsar-perf consume -st Key_Shared -r 100 -n 50 test`
5. Access the metrics endpoint

```shell
for i in {1..1000}
do
curl -L localhost:8080/metrics/
done
```

image

After reverting this PR, the memory leak issue has been fixed.

image

I'm not sure where is the root cause yet. Since many people are built based on the Pulsar release branches, so we'd better revert first and then fix the memory issue and create a new PR again. @marksilcox If you need help with the memory leak issue, I believe @tjiuming or @asafm can provide some insight here.

**Comment by codelipenghui** [comment]
I can't reproduce the issue on the master branch with PR (https://github.com/apache/pulsar/pull/15558); it looks like the memory leak issue only happened on branch-2.9

**Comment by asafm** [comment]
@codelipenghui The implementation between 2.9 and master are indeed different, hence the reason why the memory leak was introduced only in 2.9 - I checked it.

**Pull request merged**
