### PR TITLE
[Issue 8204][bookkeeper] Estimate backlog size as total if no consumer is present

### LINKED ISSUE #8204: Automatic topic compaction never triggered if no durable subscriptions are found
**Describe the bug**
If we create a topic, publish to it but we never create a durable subscription automatic compaction will never be triggered on such topic. 

This is the case when we use `SubscriptionMode.NonDurable` or we use `Reader` to read from topic.

**To Reproduce**
1. Create a namespace with a "compactionThreshold" equal to `1`
```
  $  ./pulsar-admin topics create my-topic
```
2. Produce a pair of messages with same key to topic
```
  $ ./pulsar-client produce my-topic -k 1 -m msg1
  $ ./pulsar-client produce my-topic -k 1 -m msg2
```
3. Let one or two minutes to pass (default compaction monitor timeout is 1 minute)
4. Consume messages in compacted mode from the beginning using `Reader` interface:
```
     Reader<String> reader= getClient().newReader(Schema.STRING).topic("my-topic").readCompacted(true).startMessageIdInclusive()	.startMessageId(MessageId.earliest).create();
     Message<String> msg = reader.readNext(timeoutMillis, TimeUnit.MILLISECONDS);
     System.out.println("First message value: " + msg.getValue()); // ---> This should be "msg2" but it will always be "msg1"
```

**Expected behavior**
Automatic topic compaction should work with non-durable subscriptions as well or without any subscription at all (only published data).

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by fmiguelez**
Fixes #8204 

### Motivation

The origin of the BUG was found in ManagedLedgerImpl.getEstimatedBacklogSize() returning 0 if no subscription was found. Instead of returning 0 we return the total size of the ledger.

### Modifications

Return total size of ledger instead of 0 if no subscription is present (the case for reader or non-durable subscriptions). 

### Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)
  - If a feature is not applicable for documentation, explain why? (A very internal feature)

### CODE REVIEW

**Review by sijie — CHANGES_REQUESTED** [review]
@fmiguelez The fix itself is fine. But I don't think it is a fix that is aligned with Pulsar's concept. The `backlog` concept is tied with a subscription. If there are no subscriptions, there is no backlog. That's by design. I don't think we should change the meaning here.

**Comment by fmiguelez** [comment]
Hi @sijie thanks for your comments.

Well if a ledger has no subscriptions but has alredy messages published to it you suggest that its size is zero but from the first moment someone connects (a subscription is created) then zero goes to whatever size ledger has. But if there is at least one subscription that has not consumed anything yet then it is ok to return the total size of the ledger even if rest of subscriptions have already consumed all of it. 

I do not see that "bad" returning the total size of ledger if there are no durable subscriptions at all (take into consideration that `NonDurable` subscriptions do not count in this case) instead of zero size if there is actually data published to it. Indeed that is the backlog size all subscriptions will have that start out fresh from that moment on.

In any case if you do not feel confortable with the change or you think it could break other things it is perfectly fine for me but I think that original issue #8204 must be tackled other way then. 

The main problem is that if a topic receives data but no persistent subscription has been registered yet because consumers are still starting/stopped or because those consumers only use `NonDurable` subscriptions (such as with the `Reader` interface) automatic compaction will never be triggered. However if we trigger it manually it does work as expected. There is obviously a BUG there. The troubled logic is inside `PersistentTopic.checkCompaction()` method:

```
                if (compactionSub != null) {
                    backlogEstimate = compactionSub.estimateBacklogSize();
                } else {
                    // compaction has never run, so take full backlog size
                    // We enter here because "compaction" sub does not exist unless
                    // it has manually been triggered. This returns 0 as no other "durable" 
                    // subscriptions are available but ledger does has data
                    backlogEstimate = ledger.getEstimatedBacklogSize();  
                }

               // compactionThreshold must be configured over 0 si this can work 
               // but backlogExtimate will always be 0
               if (backlogEstimate > compactionThreshold) {
               }
```

**Review by eolivelli — CHANGES_REQUESTED** [review]
good fix

can we add a test case ?

**Comment by sijie** [comment]
@fmiguelez - Just want to be very clear on storage size and backlog. The storage size is the total amount of bytes in the topic. This is already exposed as part of topic stats. The backlog is a concept for measuring how many messages are not consumed by a subscription. The backlog conception is a concept of a subscription, not a topic. I recorded a session walking through those conceptions. You can watch it at https://www.youtube.com/watch?v=PIX570nyq_c&list=PLqRma1oIkcWhWAhKgImEeRiQi5vMlqTc-&index=4&t=1368s and view the slides at https://www.slideshare.net/streamnative/tgi-pulsar-episode-016-backlog-vs-storage-size.

If the intention is to fix #8204, we should just change the logic to use storage size for triggering topic compaction instead of using backlog size.

**Comment by fmiguelez** [comment]
> @fmiguelez - Just want to be very clear on storage size and backlog. The storage size is the total amount of bytes in the topic. This is already exposed as part of topic stats. The backlog is a concept for measuring how many messages are not consumed by a subscription. The backlog conception is a concept of a subscription, not a topic. I recorded a session walking through those conceptions. You can watch it at https://www.youtube.com/watch?v=PIX570nyq_c&list=PLqRma1oIkcWhWAhKgImEeRiQi5vMlqTc-&index=4&t=1368s and view the slides at https://www.slideshare.net/streamnative/tgi-pulsar-episode-016-backlog-vs-storage-size.
> 
> If the intention is to fix #8204, we should just change the logic to use storage size for triggering topic compaction instead of using backlog size.

Looks good to me.

**Comment by fmiguelez** [comment]
Original issue will be addressed in other pull request.

**Pull request closed without merging**
