### PR TITLE
PIP-119: Enable consistent hashing by default on KeyShared subscriptions dispatcher

### LINKED ISSUE #13305: PIP-119: Enable consistent hashing by default on KeyShared dispatcher
## Motivation

The consistent hashing implementation to uniformly assign keys to consumers
in the context of a KeyShared subscription, was introduced in
https://github.com/apache/pulsar/pull/6791, which was released in Pulsar 2.6.0.

While consistent hashing can use slightly more memory in certain cases, it is
more suitable as a general default implementation, as it leads to a fairer
distribution of keys across consumers, and avoiding corner cases that depend
on the sequence of addition/removal of consumers.

## Proposed changes

In 2.10 release, for the setting:

```properties
# On KeyShared subscriptions, with default AUTO_SPLIT mode, use splitting ranges or
# consistent hashing to reassign keys to new consumers
subscriptionKeySharedUseConsistentHashing=false
```

Change its default value to `true`.

The `AUTO_SPLIT` mode will not be removed nor deprecated. Users will still be
able to use the old implementation.

### PR DESCRIPTION
**Pull request by HQebupt**
Fixed #13305 
### Motivation
See #13305 

### Modifications
Change `subscriptionKeySharedUseConsistentHashing ` default value from **false** to **true** in the ` broker.conf `.

### Verifying this change

- [x]  Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:
If `yes` was chosen, please highlight the changes

- Dependencies (does it add or upgrade a dependency): (no)
- The public API: (no)
- The schema: (no)
- The default values of configurations: (no)
- The wire protocol: (no)
- The rest endpoints: (no)
- The admin cli options: (no)
- Anything that affects deployment: (no)

### Documentation
Check the box below and label this PR (if you have committer privilege).

Need to update docs? 
- [x] `doc`

### CODE REVIEW

**Comment by Anonymitaet** [comment]
Hi @HQebupt When submitting a PR, please provide doc related info in the PR description by ticking the box or labeling a PR directly, so that Bot will recognize the info and then label the PR correctly, or else Bot can not recognize the info and then label the PR with the `doc-info-missing` label.

Just now I re-label this PR and tick the box, please pay attention next time, thanks.

**Review by codelipenghui — APPROVED** [review]

**Review by merlimat — APPROVED** [review]

**Comment by HQebupt** [comment]
Thanks @merlimat

**Comment by lhotari** [comment]
This change seems to cause problems. 

See #13963 for more details:
"It looks like there is something wrong with the consistent hashing implementation of Key_Shared dispatcher."

**Comment by lhotari** [comment]
I filed an issue #13965 since there seems to be a real issue and not just a flaky test. @HQebupt do you have a chance to investigate it?

**Comment by HQebupt** [comment]
> I filed an issue #13965 since there seems to be a real issue and not just a flaky test. @HQebupt do you have a chance to investigate it?

Sure. I'll take a look.

**Comment by eolivelli** [comment]
we still have this problem to be fixed @HQebupt @merlimat 
https://github.com/apache/pulsar/issues/10750

**Pull request merged**
