### PR TITLE
[Issue 8340] [pulsar-testclient] Provide options to specify existing topics and subscriptions

### LINKED ISSUE #8340: [pulsar-testclient]Provide options to specify existing topics when allowAutoTopicCreation is disable and using multiple topics
**Is your enhancement request related to a problem? Please describe.**
Some users may encounter the following issues when using multiple topics with option `--num-topics` but `allowAutoTopicCreation` is disable:
```
$ bin/pulsar-perf consume persistent://public/default/test -s sub -st Exclusive -t 2
Exception in thread "main" java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException$TopicDoesNotExistException: Topic does not exist
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at org.apache.pulsar.testclient.PerformanceConsumer.main(PerformanceConsumer.java:343)
Caused by: org.apache.pulsar.client.api.PulsarClientException$TopicDoesNotExistException: Topic does not exist
        at org.apache.pulsar.client.impl.ClientCnx.getPulsarClientException(ClientCnx.java:1003)
        at org.apache.pulsar.client.impl.ClientCnx.handleError(ClientCnx.java:610)
        at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:170)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
```
or using multiple subscriptions with option `--num-consumers` but `allowAutoSubscriptionCreation` is disable:
```
$ bin/pulsar-perf consume persistent://public/default/test -s sub -st Exclusive -n 2
[pulsar-client-io-1-8] WARN  org.apache.pulsar.client.impl.ConnectionHandler - [persistent://public/default/test-partition-3] [sub-1] Could not get connection to broker: Subscription does not exist -- Will try again in 0.1 s
[pulsar-client-io-1-7] WARN  org.apache.pulsar.client.impl.ConnectionHandler - [persistent://public/default/test-partition-4] [sub-1] Could not get connection to broker: Subscription does not exist -- Will try again in 0.1 s
[pulsar-client-io-1-3] WARN  org.apache.pulsar.client.impl.ConnectionHandler - [persistent://public/default/test-partition-2] [sub-0] Could not get connection to broker: Subscription does not exist -- Will try again in 0.1 s
[pulsar-client-io-1-4] WARN  org.apache.pulsar.client.impl.ConnectionHandler - [persistent://public/default/test-partition-1] [sub-0] Could not get connection to broker: Subscription does not exist -- Will try again in 0.1 s
```

**Describe the solution you'd like**
Add some options to specify existing topics or subscriptions to meet the above scenario.

### PR DESCRIPTION
**Pull request by murong00**
### Motivation

Fixes #8340

### Modifications

- Add option `--explicit-topics` for CLI `pulsar-perf produce/consume/read` to specify existing topics.
- Add option `--explicit-subscriptions` for CLI `pulsar-perf consume` to specify existing subscriptions.
- Modify the corresponding `.md` file for these new added options.

### CODE REVIEW

**Comment by wolfstudy** [comment]
@jiazhai @codelipenghui @sijie @merlimat PTAL thanks.

**Comment by codelipenghui** [comment]
@murong00 I will remove the release/2.6.2 tag since this is a new feature and the release manager is starting to build the 2.6.2 release package. So it's better to onboard this feature in 2.7.0

**Comment by codelipenghui** [comment]
move to 2.8.0 first

**Comment by Anonymitaet** [comment]
@murong00 any progress on this PR?

**Comment by murong00** [comment]
> @murong00 any progress on this PR?

Need some discussion with penghui, I will try to accomplish it based on the master this week.

**Comment by Anonymitaet** [comment]
Hi @murong00, any blockers for this PR?

**Comment by Anonymitaet** [comment]
@murong00 thanks for your coding work.

1. Does this apply to 2.7.1?

2. Would you like to add docs for this change?

**Comment by murong00** [comment]
@Anonymitaet  I will close this pr and submit a new one by taking penghui's advice, I expect it can be applied to 2.7.1 if possible.

**Pull request closed without merging**
