### PR TITLE
[fix][client] Fix negative acknowledgement by messageId

### PR DESCRIPTION
**Pull request by izumo27**
### Motivation
related: https://github.com/apache/pulsar/pull/20750

When adding to `unAckedMessageTracker`, the messageId type is converted to `MessageIdImpl`.
- https://github.com/apache/pulsar/blob/v3.3.0/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java#L1162-L1167
- https://github.com/apache/pulsar/blob/v3.3.0/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L1820-L1827

If calling `ConsumerImpl#negativeAcknowledge(MessageId)` and the messageId type is `BatchMessageIdImpl`, the message will not be removed from the `unAckedMessageTracker`.
https://github.com/apache/pulsar/blob/v3.3.0/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L814

This will cause both negative ack redeliver and ack timeout redeliver.

### Modifications

Convert the messageId type to remove the message from `unAckedMessageTracker`.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change added tests and can be verified as follows:

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [x] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [x] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/izumo27/pulsar/pull/5

### CODE REVIEW

**Review by hanmz — COMMENTED** [review]
Good catch

**Review by Coselding — APPROVED** [review]

**Review by congbobo184 — APPROVED** [review]

**Comment by lhotari** [comment]
Great catch @izumo27 !

> This will cause both negative ack redeliver and ack timeout redeliver.

Would it be possible to add a test case for this scenario?

**Comment by izumo27** [comment]
@lhotari 
> Would it be possible to add a test case for this scenario?

This is testing whether the messages are deleted from the unAckedMessageTracker. 
https://github.com/apache/pulsar/pull/23060/files#diff-bdc977c55b8ac0f29e331906c5b166ebb868aa8e580eb48b162ff0e5439e3a6dR155
Is it necessary to check whether ack timeout redeliver occurs?

**Comment by izumo27** [comment]
@lhotari It seems that #20750 has not been cherry-picked into branch 3.0.
https://github.com/apache/pulsar/blob/v3.0.6/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L753-L766

**Pull request merged**
