### PR TITLE
[Issue #12495] Fix the serialization time attribute is not allowed to be empty by default

### LINKED ISSUE #12495: no properties discovered to create BeanSerializer
背景：客户端启动完毕，构建消息时报错

代码：
生产者客户端：
Producer<?> producer = pulsarClient.newProducer(Schema.JSON(RequestWrapper.class))
                    .......
                    .create();
producer.newMessage()
                .value(new RequestWrapper(message))
                .deliverAfter(delay, unit)
                .properties(properties)
                .sendAsync();

RequestWrapper对所有请求对象包装：
RequestWrapper{
    private Object req;
}
上面代码new RequestWrapper(message)
message是 ：new Pair<>(new User("小明", 26), new Person())；

Pair<K, V> {
    private K key;
    private V val;
    public Pair() {
    }
}

User {
    private String name;
    private int age;
}

Person {
    public Person() {
    }
}

当Person存在属性时：
发送、消费正常

当Person没有属性时：

Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class com.idanchuang.msgBroker.example.User and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.idanchuang.msgBroker.example.RequestWrapper["req"]->com.idanchuang.msgBroker.example.Pair["key"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1191)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:313)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:71)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3905)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3243)
	at org.apache.pulsar.client.impl.schema.writer.JacksonJsonWriter.write(JacksonJsonWriter.java:42)
	... 36 more

### PR DESCRIPTION
**Pull request by mingyifei**
Motivation
fix #12495

Implement
When the message object json is serialized, the attribute should be allowed to be empty by default

Verifying this change
Add the tests for it

Does this pull request potentially affect one of the following parts:
If yes was chosen, please highlight the changes

Dependencies (does it add or upgrade a dependency): (no)
The public API: (no)
The schema: (no)
The default values of configurations: (no)
The wire protocol: (yes)
The rest endpoints: (no)
The admin cli options: (no)
Anything that affects deployment: (no)

### CODE REVIEW

**Comment by mingyifei** [comment]
> @mingyifei hi, dose field is null the attribute have any meaning? we also provide a way to bypass the default not allowed to be empty. Why should we modify it?

Perhaps you think that null attributes are meaningless, but not necessarily for business people. Even null is meaningful in business. Too many restrictions increase the limitations of the message. Wouldn't it be better to send arbitrary messages?

**Comment by mingyifei** [comment]
> @mingyifei hi, dose field is null the attribute have any meaning? we also provide a way to bypass the default not allowed to be empty. Why should we modify it?

Perhaps you think that null attributes are meaningless, but not necessarily for business people. Even null is meaningful in business. Too many restrictions increase the limitations of the message. Wouldn't it be better to send arbitrary messages?

**Comment by mingyifei** [comment]
> > @mingyifei hi, dose field is null the attribute have any meaning? we also provide a way to bypass the default not allowed to be empty. Why should we modify it?
> 
> Perhaps you think that null attributes are meaningless, but not necessarily for business people. Even null is meaningful in business. Too many restrictions increase the limitations of the message. Wouldn't it be better to send arbitrary messages?

@congbobo184

**Comment by mingyifei** [comment]
> Great doc and user can define the custom `Serialization` following your doc if they have special requirements. But I am wondering if changing the default setup would bring some compatibility issue in some corner case.

You can see if the configuration reference in the code will cause compatibility issues

**Comment by Jason918** [comment]
> > Great doc and user can define the custom `Serialization` following your doc if they have special requirements. But I am wondering if changing the default setup would bring some compatibility issue in some corner case.
> 
> You can see if the configuration reference in the code will cause compatibility issues

I'm referring the compatibility issue during upgrade for previous pulsar user, since you are changing the default behavior.

**Comment by mingyifei** [comment]
> > > Great doc and user can define the custom `Serialization` following your doc if they have special requirements. But I am wondering if changing the default setup would bring some compatibility issue in some corner case.
> > 
> > 
> > You can see if the configuration reference in the code will cause compatibility issues
> 
> I'm referring the compatibility issue during upgrade for previous pulsar user, since you are changing the default behavior.

Understand that if the user upgrades the version and ignores this change point, it will cause unforeseen problems, right?

**Comment by Jason918** [comment]
> > > > Great doc and user can define the custom `Serialization` following your doc if they have special requirements. But I am wondering if changing the default setup would bring some compatibility issue in some corner case.
> > > 
> > > 
> > > You can see if the configuration reference in the code will cause compatibility issues
> > 
> > 
> > I'm referring the compatibility issue during upgrade for previous pulsar user, since you are changing the default behavior.
> 
> Understand that if the user upgrades the version and ignores this change point, it will cause unforeseen problems, right?

Yep.

**Comment by mingyifei** [comment]
> > > > > Great doc and user can define the custom `Serialization` following your doc if they have special requirements. But I am wondering if changing the default setup would bring some compatibility issue in some corner case.
> > > > 
> > > > 
> > > > You can see if the configuration reference in the code will cause compatibility issues
> > > 
> > > 
> > > I'm referring the compatibility issue during upgrade for previous pulsar user, since you are changing the default behavior.
> > 
> > 
> > Understand that if the user upgrades the version and ignores this change point, it will cause unforeseen problems, right?
> 
> Yep.

**Comment by mingyifei** [comment]
> > > > > Great doc and user can define the custom `Serialization` following your doc if they have special requirements. But I am wondering if changing the default setup would bring some compatibility issue in some corner case.
> > > > 
> > > > 
> > > > You can see if the configuration reference in the code will cause compatibility issues
> > > 
> > > 
> > > I'm referring the compatibility issue during upgrade for previous pulsar user, since you are changing the default behavior.
> > 
> > 
> > Understand that if the user upgrades the version and ignores this change point, it will cause unforeseen problems, right?
> 
> Yep.

How do you deal with similar pr?

**Pull request closed without merging**
