### PR TITLE
Issue 10236: [Doc] generate 2.7.2 docs

### LINKED ISSUE #10236: [Doc] generate 2.7.2 docs
2.7.1 has been released and the Pulsar is on the way to 2.7.2 (and 2.8.0). 

Since 2.7.2 docs might be different from 2.7.1, but now we[ do not have the 2.7.2 docs](https://github.com/apache/pulsar/tree/master/site2/website/versioned_docs) and can not update the 2.7.2 docs if needed. Consequently, 2.7.2 docs need to be generated.

### PR DESCRIPTION
**Pull request by eolivelli**
Fixes #10236

Create new directory structure to host 2.7.2 docs.
There should be no link to these pages when we generate the website, this way these pages won't be available to users until we release 2.7.2

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@eolivelli version ids need to be updated to 2.7.2, and other places need to be updated as well.
image

@Jennifer88huang is updating the release process, @eolivelli could u pls update this PR following that release process?

@Jennifer88huang pls correct me if I'm wrong.

**Review by Jennifer88huang — COMMENTED** [review]
@eolivelli thank you very much for taking the effort. You need to update the id and generate the `version-2.7.2-sidebar.json` file as well. I update the workflow at https://github.com/apache/pulsar/wiki/Release-process#update-the-site-for-minor-releases

**Comment by eolivelli** [comment]
@Anonymitaet I have replaced all of the occurrences of 2.7.1 with 2.7.2

**Comment by Jennifer88huang** [comment]
@Anonymitaet You're right, thank you.

**Comment by eolivelli** [comment]
I also updated the sidebars file according to the new instructions
https://github.com/apache/pulsar/wiki/Release-process#update-the-site-for-minor-releases

**Review by Jennifer88huang — APPROVED** [review]
Great, thank you.

**Comment by Anonymitaet** [comment]
@Jennifer88huang 

For this PR:

1. Does this PR need to update [`releases.json`](https://github.com/apache/pulsar/blob/master/site2/website/releases.json)? (according to the [instructions - step 4](https://github.com/apache/pulsar/wiki/Release-process#update-the-site-for-major-releases))

> 4. Update releases.json file by adding <release-version> to the second of the list(this is to make search could work. After your PR is merged, the Pulsar website is built and tagged for search, you can change it to the first list).

2. Does this PR need to update [`versions.json`](https://github.com/apache/pulsar/blob/master/site2/website/versions.json)? (according to the [instructions - step 3](https://github.com/apache/pulsar/wiki/Release-process#update-the-site-for-major-releases))
image

**Comment by Jennifer88huang** [comment]
@Anonymitaet No, it's not needed.
According to the workflow, this PR should have been submitted immediately after 2.7.1 release, so he follows the workflow for minor release, shown as follows:
image

**Comment by Anonymitaet** [comment]
@Jennifer88huang 

1. Does [`releases.json`](https://github.com/apache/pulsar/blob/master/site2/website/releases.json) point to [this page](https://pulsar.apache.org/en/versions/)?

2. Where does [`versions.json`](https://github.com/apache/pulsar/blob/master/site2/website/versions.json) point to?

**Comment by sijie** [comment]
@codelipenghui @tuteng Can you review this PR?

**Review by tuteng — APPROVED** [review]

**Comment by eolivelli** [comment]
It is better that the menu does not link to these pages until we release 2.7.2

**Comment by eolivelli** [comment]
@Anonymitaet I am not sure about the status of this patch.

can we merge ?

**Comment by Anonymitaet** [comment]
@eolivelli yes, pls go ahead.

**Review by Anonymitaet — APPROVED** [review]

**Comment by Jennifer88huang** [comment]
> It is better that the menu does not link to these pages until we release 2.7.2

The 2.7.2 menu will not be displayed after you merge this PR.
When you add the `2.7.2` to the `release.json` file when releasing the new version, 2.7.2 will be displayed on website.

**Pull request merged**
