### PR TITLE
Add "dashboard" to list of modules so that pom version gets auto updated

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Since the `dashboard` module is not listed in root pom, it's version won't get automatically updated once we prepare a release.

### CODE REVIEW

**Comment by jiazhai** [comment]
rerun java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by merlimat** [comment]
run integration tests

**Pull request merged**
