### PR TITLE
[fix] Fix Authentication metric has infinity label values

### PR DESCRIPTION
**Pull request by dao-jun**
### Motivation

The `pulsar_authentication_failures_count` metric is flooding with non-finite values in the reason label, which will cause a cardinality explosion on Grafana instances. 
This problem is impacting the performance and reliability of metrics.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [x] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/dao-jun/pulsar/pull/2

### CODE REVIEW

**Comment by codelipenghui** [comment]
@dao-jun Could you please send a discuss email since it changed the metrics. I support this change. Maybe we can try to add an enum for the common authn error types?

**Comment by dao-jun** [comment]
@codelipenghui 
> Could you please send a discuss email since it changed the metrics
Yes, I will send a discuss later

> Maybe we can try to add an enum for the common authn error types?
I tried to add an enum for error types, but we have to change a lot of code. So I'm not sure if it's possible

**Comment by ahothan** [comment]
> 
> > Maybe we can try to add an enum for the common authn error types?
> 
> I tried to add an enum for error types, but we have to change a lot of code. So I'm not sure if it's possible

There is no need to provide additional information in the labels as these are metric.
If needed additional information such as reason can be provided as an error level log message.

**Comment by ahothan** [comment]
diffs lgtm

**Pull request closed without merging**
