### PR TITLE
Update year to 2021

### PR DESCRIPTION
**Pull request by CalvinKirs**

### CODE REVIEW

**Review by merlimat — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Review by sijie — APPROVED** [review]

**Review by 315157973 — APPROVED** [review]

**Comment by CalvinKirs** [comment]
The modify file has nothing to do with CI. CI failure may be caused by other reasons.

**Comment by sijie** [comment]
@CalvinKirs  Yeah. The CI failure is not related to this. No worries about that. We are trying to get the CI pass so that we can merge this pull request.

**Review by Huanli-Meng — APPROVED** [review]

**Comment by CalvinKirs** [comment]
It’s better to have notice updates attached to subsequent releases. I noticed that our previous release version had almost no updates in the notice year.

I noticed that Justin mentioned this when he checked Sedona.

https://lists.apache.org/thread.html/r828873cbb2685dcfb0719680f3aac6dbf982720fcd9cd5f69a26ec55%40%3Cgeneral.incubator.apache.org%3E

**Pull request merged**
