### PR TITLE
[Issue 6114][Doc 2.5.0] Fix missing Swagger files for the version 2.5.0

### LINKED ISSUE #6114: [Doc 2.5.0] Wrong link address in doc
**Describe the bug**

Wrong link address in doc. doc version 2.5.

**To Reproduce**
1. Go to [rest-api](https://pulsar.apache.org/docs/en/admin-api-overview/#rest-api)
2. Click on 'document'
3. Redirect to https://pulsar.incubator.apache.org/en/admin-rest-api#/
4. Blank page

**Expected behavior**

should redirect to a valid page.

**Screenshots**
image
image

**Desktop (please complete the following information):**
 - OS:  MacOS 10.15  
 - Google Chrome

**Additional context**

use grep command find more domain `pulsar.incubator.apache.org`

```shell
grep -iR "pulsar.incubator.apache.org" .
```

### PR DESCRIPTION
**Pull request by vzhikserg**
Fixes #6114 

### Modifications

The swagger files were generated for the version 2.5.0 according to the [instruction](https://github.com/apache/pulsar/issues/6114#issuecomment-576696130) provided by @tuteng

### CODE REVIEW

**Comment by tuteng** [comment]
retest this please

**Comment by tuteng** [comment]
run cpp tests
run java8 tests

**Comment by sijie** [comment]
@tuteng do we need to generate the swagger files manually for each release? If so, we need to include this step in our release process documentation.

**Comment by sijie** [comment]
@tuteng @wolfstudy can you update the release process documentation to generate swagger files?

**Pull request merged**
