### PR TITLE
[docs]Add old version api document

### PR DESCRIPTION
**Pull request by tuteng**
### Motivation

https://lists.apache.org/thread.html/a6a91990907cf8d2458ff8b7e1e916a9bfb17ec0cd216d57c66ab96c@%3Cdev.pulsar.apache.org%3E

Currently, there is a lack of api documents for the old version, and the old version documents need to be added. 
http://pulsar.apache.org/api/python/2.5.0-SNAPSHOT/
http://pulsar.apache.org/api/client/2.5.0-SNAPSHOT/
http://pulsar.apache.org/api/pulsar-functions/2.5.0-SNAPSHOT/
http://pulsar.apache.org/api/admin/2.5.0-SNAPSHOT/
http://pulsar.apache.org/api/pulsar-broker/2.5.0-SNAPSHOT/
http://pulsar.apache.org/api/cpp/2.5.0-SNAPSHOT/

### Modifications

* Add API document for the old version
* support 2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.3.2, 2.4.0, 2.4.1

### CODE REVIEW

**Comment by sijie** [comment]
@tuteng It seems that the generated javadoc contains a lot of chinese characters. Can you change the locale of your laptop to english and regenerate the documentation?

**Comment by sijie** [comment]
@tuteng updates?

**Comment by sijie** [comment]
@tuteng can you regenerate the api documents?

**Comment by tuteng** [comment]
It seems to be my local language environment problem. I will regenerate these documents.

**Comment by tuteng** [comment]
@sijie PTAL

**Pull request merged**
