### PR TITLE
[zookeeper] bump zookeeper to version 3.5.6

### LINKED ISSUE #4448: Upgrade ZooKeeper to 3.5.5 (stable)
**Is your feature request related to a problem? Please describe.**
This is just a nice to have. The new version of ZooKeeper has many features such as dynamic membership reconfiguration. Hopefully this can also take out the need for some workarounds to maintain ZK version compatibility with BK as well.

**Additional context**
Release 3.5.5 is now stable https://zookeeper.apache.org/releases.html

### PR DESCRIPTION
**Pull request by addisonj**
With zookeeper 3.5.5 now marked as stable and 3.5 being reccomend for
the production branch (see https://zookeeper.apache.org/releases.html),
this moves pulsar up to 3.5.6.

Pulsar previously had 3.5.x support but was downgraded due to concerns
of 3.5 still being a "beta", so this is a fairly simple change

Fixes #4448

As a follow on to this work, we should introduce new configuration options to support TLS connections to ZK, however, that is out of scope for this initial dependency bump.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is already covered by existing tests 

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): yes
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no
  - The rest endpoints: no
  - The admin cli options: no
  - Anything that affects deployment: yes

### Documentation

  - Does this pull request introduce a new feature? no

There are some references to ZK 3.4 versions of docs that may need updated to 3.5 eventually. Assuming this is accepted, we should make a follow on item to change those

### CODE REVIEW

**Comment by eolivelli** [comment]
A fix for empty snapshot is coming for 3.5.6, see https://github.com/apache/zookeeper/pull/1069

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by addisonj** [comment]
run java8 tests

**Comment by addisonj** [comment]
It seems like there might be more going on here with the failed tests? Any help in debugging this would be appreciated!

**Comment by addisonj** [comment]
run integration test
run java8 tests
run cpp tests

**Comment by addisonj** [comment]
run integration tests

**Comment by addisonj** [comment]
rerun java8 tests
rerun integration tests

**Comment by addisonj** [comment]
run java8 tests

**Comment by addisonj** [comment]
run java8 tests
run integration tests

**Comment by addisonj** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by eolivelli** [comment]
What's the error? 
It is not normal to need to re run tests so many times

**Comment by aahmed-se** [comment]
@eolivelli jenkins has become unstable.

**Comment by addisonj** [comment]
AFAICT, the errors are different each time and it isn't consistent. None of the tests (AFAICT) look to directly depend on ZK, but perhaps it has caused some stability issue? Hard to say, but seems quite weird

**Comment by addisonj** [comment]
rerun java8 tests

**Comment by eolivelli** [comment]
Fyi now 3.5.6 is available :)

**Comment by merlimat** [comment]
> Fyi now 3.5.6 is available :)

Yes, and it includes fix for upgrading ZK with missing snapshot: 
https://issues.apache.org/jira/browse/ZOOKEEPER-3056

@addisonj

**Comment by aahmed-se** [comment]
@addisonj can you rebase this on master.

**Comment by addisonj** [comment]
@aahmed-se done

also I changed it to 3.5.6 as we want the fix for cleaner upgrades

**Comment by addisonj** [comment]
rerun java8 tests

**Comment by addisonj** [comment]
rerun java8 tests

**Comment by addisonj** [comment]
rerun java8 tests

**Comment by addisonj** [comment]
rerun java8 tests

**Comment by addisonj** [comment]
rerun java8 tests
rerun cpp tests

**Comment by aahmed-se** [comment]
@sijie please  take a look at unblock this.

**Pull request merged**
