### PR TITLE
[Doc][bugfix] Example broke Ensemble>=WriteQuorum>=AckQuorum Rule

### PR DESCRIPTION
**Pull request by dave2wave**
### Motivation

Our admin examples must not show users incorrect information.

### Modifications

Changed Bookkeeper persistence example.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] Anything that affects deployment

### Documentation

- [X] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by merlimat — COMMENTED** [review]
We should add a check that rejects the invalid configuration

**Comment by dave2wave** [comment]
> We should add a check that rejects the invalid configuration

There is a checkArgument if we set the policy through an admin call. Are you suggesting that we also test validity when a policy is created? This can be incomplete since the full check includes knowing the broker configuration to handle the currently allowed maximums for the ensemble size. I don't think testing without the max part is wrong, I'm just looking for clarification. In any case I think that check is a separate PR.

**Review by Huanli-Meng — APPROVED** [review]
LGTM

**Comment by Huanli-Meng** [comment]
@dave2wave could you please help confirm whether docs in other releases also need to be updated? Thanks.

**Comment by dave2wave** [comment]
@Huanli-Meng this change and #17955 need to be propagated to prior branches. Thank you.

**Comment by Huanli-Meng** [comment]
> @Huanli-Meng this change and #17955 need to be propagated to prior branches. Thank you.

@dave2wave thanks for your confirmation. BTW, would you like to help update these updates to prior branches? Thanks

**Pull request merged**
