### PR TITLE
Remove old Pulsar website

### PR DESCRIPTION
**Pull request by sijie**
### Motivation

The new pulsar website is under `/site2`. There is no need to keep `/site` directory.

### CODE REVIEW

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run integration tests

**Comment by codelipenghui** [comment]
run integration tests

**Comment by Jennifer88huang** [comment]
run integration tests

**Comment by sijie** [comment]
@merlimat oops. I missed that. fixed all the references.

**Comment by aahmed-se** [comment]
run java8 tests.

**Comment by sijie** [comment]
run java8 tests

**Pull request merged**
