### PR TITLE
[fix][fn] Fix function update error

### LINKED ISSUE #19721: [Bug] Cannot update Pulsar function in Pulsar standalone
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

**OS version:** Ubuntu 22.04
**Pulsar version:** 2.11.0 (using apachepulsar/pulsar-all:2.11.0 Docker image)

### Minimal reproduce step

Run 2.11.0 standalone:

```
$ docker run -it apachepulsar/pulsar:2.11.0 bin/pulsar standalone
```

Go into the container and create an arbitrary Pulsar function `test_function.py`.

Then register it:

```
$ bin/pulsar-admin functions create \
  --py test_function.py \
  --classname test_function.ExamplePulsarFunction \
  --tenant public \
  --namespace default \
  --name test-function \
  --inputs persistent://public/default/test-input-topic \
  --output persistent://public/default/test-output-topic
Created successfully
```

Now try to update it:

```
$ bin/pulsar-admin functions update \
  --py test_function.py \
  --classname test_function.ExamplePulsarFunction \
  --tenant public \
  --namespace default \
  --name test-function \
  --inputs persistent://public/default/test-input-topic \
  --output persistent://public/default/test-output-topic
```

### What did you expect to see?

I'd expect to see the `Updated successfully` message from updating a Pulsar function.

### What did you see instead?

I get the error

```
Package 'function://public/default/test-function@0' metadata already exists`.
```

The logs look a bit like this:

```
2023-03-06T06:34:58,426+0000 [pulsar-web-38-2] ERROR org.apache.pulsar.functions.worker.rest.api.FunctionsImpl - Failed process Function public/default/test-function package: 
org.apache.pulsar.client.admin.PulsarAdminException$NotFoundException: Package 'function://public/default/test-function@0' metadata already exists
        at org.apache.pulsar.client.admin.PulsarAdminException.wrap(PulsarAdminException.java:252) ~[org.apache.pulsar-pulsar-client-admin-api-2.11.0.jar:2.11.0]
        at org.apache.pulsar.client.admin.internal.BaseResource.sync(BaseResource.java:316) ~[org.apache.pulsar-pulsar-client-admin-original-2.11.0.jar:2.11.0]
        at org.apache.pulsar.client.admin.internal.PackagesImpl.upload(PackagesImpl.java:90) ~[org.apache.pulsar-pulsar-client-admin-original-2.11.0.jar:2.11.0]
        at org.apache.pulsar.functions.worker.rest.api.ComponentImpl.getFunctionPackageLocation(ComponentImpl.java:411) ~[org.apache.pulsar-pulsar-functions-worker-2.11.0.jar:2.11.0]
        at org.apache.pulsar.functions.worker.rest.api.FunctionsImpl.updateFunction(FunctionsImpl.java:459) ~[org.apache.pulsar-pulsar-functions-worker-2.11.0.jar:2.11.0]
        at org.apache.pulsar.broker.admin.impl.FunctionsBase.updateFunction(FunctionsBase.java:326) ~[org.apache.pulsar-pulsar-broker-2.11.0.jar:2.11.0]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        ...
```

### Anything else?

As far as I can tell `ComponentImpl.getFunctionPackageLocation()` is getting called when updating the Pulsar function, but when non-BookKeeper package management is being used (which is the case for standalone) it looks like `PackagesManagementImpl.upload()` happens, and that checks whether metadata exists or not + throws an error if it doesn't...

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by jiangpengcheng**
Fixes #19721 

Master Issue: #xyz

PIP: #xyz 

### Motivation

functions are failed to update when `--py|--go|--jar` is specified

### Modifications

add 1 to functions' version when uploading package while updating functions

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

- [x] This change added tests and can be verified as follows:

  - *Added integration tests for updating function code file*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/jiangpengcheng/pulsar/pull/8

### CODE REVIEW

**Comment by nlu90** [comment]
Without this fix, when users update a function with the new jar, py or go binary, they will get the following error:
```
➜  apache-pulsar-2.11.0 ./bin/pulsar-admin functions update \
--py examples/python-examples/exclamation_function.py \
--classname python-examples.ExclamationFunction \
--inputs public/default/test \
--output public/default/test-output2 \
--name ExPy2 \

Package 'function://public/default/ExPy2@0' metadata already exists

```

**Review by nlu90 — APPROVED** [review]

**Comment by Technoboy-** [comment]
@nlu90 Do we need to cherry-pick to other branches for this patch ?

**Review by freeznet — APPROVED** [review]

**Pull request merged**
