### PR TITLE
Use python 3.5 runtime and pulsar client

### PR DESCRIPTION
**Pull request by aahmed-se**

### CODE REVIEW

**Comment by merlimat** [comment]
run integration tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
ReplicatorGlobalNSTest

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Pull request merged**
