### PR TITLE
[schema] Batch message should propagate the schema version from single message

### PR DESCRIPTION
**Pull request by sijie**
*Motivation*

Schema version is set on single message's header. But it isn't propagated to
the batch message's header. So when the consumer receives the message batch,
it doesn't contain the schema version.

*Modifications*

When intializing a message batch, propagate the schema version from single message to batch message header.

*Verify this change*

Verified with an integration test. Need to write some unit tests for it.

### CODE REVIEW

**Comment by sijie** [comment]
run cpp tests
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by sijie** [comment]
run cpp tests
run integration tests

**Comment by codelipenghui** [comment]
run java8 tests
run integration tests

**Comment by merlimat** [comment]
Merged in 2.3.1 at 
a9c4738

**Pull request merged**
