### PR TITLE
set pulsar-all docker image config one time

### PR DESCRIPTION
**Pull request by dockerzhang**
Fixes https://github.com/apache/pulsar/issues/7112

### Motivation
It is redundant to modify at 8 places for using pulsar-all image which existed private repositories.

### Modifications
use one pulsar-all docker image config to avoid repeated configs in helm chart.

### CODE REVIEW

**Comment by jiazhai** [comment]
@dockerzhang, thanks for help on this issue. current way may be easier for user to config different components using different image

**Comment by sijie** [comment]
@dockerzhang: Currently the helm chart is designed to allow configuring different images for different components. This change breaks the flexibility. If you want to introduce a common image, that is fine. But we should also add the functionality to allow overwriting images for individual components.

Also, can you send the pull request to https://github.com/apache/pulsar-helm-chart.

**Comment by dockerzhang** [comment]
@jiazhai @sijie If we build components image separately in the future,  it's the best way to configuring  components using different image.
pulsar has built all components in pulsar-all, and if we will still use it. i think it's better to make easy for configuration but not flexibility.

**Comment by sijie** [comment]
@dockerzhang - I think it is not only about flexibility. It is more about operability in production. The problem of using one single image is - if you update the image and re-deploy the helm chart, you will trigger the updates on all components. For some of the components like zookeeper, you probably don't need to deploy it every time there is a new version.

**Pull request closed without merging**
