### PR TITLE
[CLEANUP] delete unused log4j.properties in pulsar proxy

### PR DESCRIPTION
**Pull request by Shoothzj**
### Modifications
now pulsar-proxy use log4j2.yaml, `log4j.properties` is unused.
delete unused `log4j.properties` in pulsar-proxy

### CODE REVIEW

**Review by liudezhi2098 — APPROVED** [review]

**Review by HQebupt — APPROVED** [review]

**Comment by michaeljmarshall** [comment]
> now pulsar-proxy use log4j2.yaml, `log4j.properties` is unused.

@Shoothzj - are you able to provide a reference PR that supports this statement? Thanks.

**Comment by Shoothzj** [comment]
@michaeljmarshall I am sorry that I can't provide a PR, but I checked from existing env and start script, there is nothing related to this file

**Review by michaeljmarshall — APPROVED** [review]

**Review by liangyuanpeng — APPROVED** [review]

**Review by Jason918 — APPROVED** [review]

**Pull request merged**
