### PR TITLE
fix improper class/method/field modifiers

### PR DESCRIPTION
**Pull request by hangc0276**
### Motivation
The some java class/method/field modifiers are improper used.

Oracle java modifier order documentation:
https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.1.1

#### Class Modifiers
```
Class Modifier:
(one of)
Annotation public protected private
abstract static final strictfp
```

#### Method Modifiers
```
MethodModifier:
(one of)
Annotation public protected private
abstract static final synchronized native strictfp
```

#### Field Modifiers
```
FieldModifier:
(one of)
Annotation public protected private
static final transient volatile
```

### Modification
Change mis-ordered modifiers.

### CODE REVIEW

**Review by congbobo184 — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
LGTM

IIRC there is a checkstyle rule, can we activate it please ?

**Comment by hangc0276** [comment]
> LGTM
> 
> IIRC there is a checkstyle rule, can we activate it please ?

@eolivelli good idea, i work for it.

**Comment by Anonymitaet** [comment]
@hangc0276 thanks for your contribution. For this PR, do we need to update docs?

**Comment by hangc0276** [comment]
> @hangc0276 thanks for your contribution. For this PR, do we need to update docs?

@Anonymitaet No need to update docs, thanks.

**Comment by hangc0276** [comment]
> LGTM
> 
> IIRC there is a checkstyle rule, can we activate it please ?

@eolivelli  I have add the modifier order check, PTAL.

**Review by eolivelli — APPROVED** [review]
looks great

**Pull request merged**
