### PR TITLE
[feat][cli] Add a cli tool to check whether the input schema is validated

### PR DESCRIPTION
**Pull request by liangyepianzhou**
### Motivation
Some users want to upload schema to a topic via `curl`. At the same time, they hope to check the schema they uploaded is validated before uploading. So, we add a tool in the CmdSchemas.
```
```bash
curl -X 'PUT' -H 'Content-Type: application/json' -d '{
  "type": "JSON",
  "schema": "{ \"type\": \"record\", \"name\": \"Test\", \"fields\" : [{\"name\": \"field1\", \"type\": \"string\"}] }",
  "properties": {
    "description": "JSON schema"
  }
}' 'http://<pulsar-url>/admin/v2/schemas/<tenant>/<namespace>/<topic>/schema'
```

### Modifications
Add a tool to check whether the upload schema is validated.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by dao-jun — APPROVED** [review]

**Comment by dao-jun** [comment]
do we need a PIP?

**Comment by codelipenghui** [comment]
+1 for adding a proposal for the new API

And I'd like to validate the schema at the broker side for couple of reasons

1. Users might don't want to use Pulsar Admin CLI. Pulsar Admin, Rest API should also have ability to validate the schema
2. Avro not the only solution for schema management. If we want to introduce a native JSON schema, we still need to add more dependencies to the Pulsar Admin CLI to catch up the feature.
3. There are other tools in the ecosystem, pulsarctl, pulsar manager. If the solution is not in the broker, they also need to catch up the new feature.

**Comment by codelipenghui** [comment]
Admin CLI: https://pulsar.apache.org/reference/#/3.2.x/pulsar-admin/schemas?id=compatibility
Admin REST API: https://pulsar.apache.org/admin-rest-api/?version=3.2.0#operation/SchemasResource_testCompatibility

@liangyepianzhou We already have such capacity to validate and test the schema compatibility.

**Comment by liangyepianzhou** [comment]
> Admin CLI: https://pulsar.apache.org/reference/#/3.2.x/pulsar-admin/schemas?id=compatibility Admin REST API: https://pulsar.apache.org/admin-rest-api/?version=3.2.0#operation/SchemasResource_testCompatibility
> 
> @liangyepianzhou We already have such capacity to validate and test the schema compatibility.

@codelipenghui I know that, but they are different. The one you provided is used to verify schema compatibility when you have a topic that already has schemas. This one is used to test whether the schema is validated when you send a schema to a new topic.

**Comment by liangyepianzhou** [comment]
Admin CI: https://pulsar.apache.org/admin-rest-api/?version=3.2.0#operation/SchemasResource_postSchema
Admin Rest API: https://pulsar.apache.org/reference/#/3.2.x/pulsar-admin/schemas?id=upload

@codelipenghui The `upload` API can validate the form of schema data. Is it necessary for us to add an API on the broker side just to check the schema's correctness without uploading it?

**Comment by liangyepianzhou** [comment]
The `testCompatibility` API also will check the schema form, so we can close this PR.

**Pull request closed without merging**
