### PR TITLE
[C++] Fixed the setting method of linker option.

### PR DESCRIPTION
**Pull request by shustsud**
### Motivation

I don't think the following `--exclude-libs,ALL` are reflected in linker.
 [https://github.com/apache/pulsar/blob/f8080f4eb690d751f1b07ca54c23e1cd7774473f/pulsar-client-cpp/CMakeLists.txt#L214](https://github.com/apache/pulsar/blob/f8080f4eb690d751f1b07ca54c23e1cd7774473f/pulsar-client-cpp/CMakeLists.txt#L214)

I think `--exclude-libs,ALL` needs to be set in `add_link_options`.
 [add_link_options](https://cmake.org/cmake/help/latest/command/add_link_options.html)

`add_link_options` can be used from v3.13.
Therefore, fixed(reverted) `add_compile_options` to `set`.([#4071](https://github.com/apache/pulsar/pull/4071))

### Modifications

* Fixed CMakeLists.txt.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Comment by codelipenghui** [comment]
@BewareMyPower Please help review this PR.

**Review by BewareMyPower — APPROVED** [review]

**Comment by BewareMyPower** [comment]
I'll remove the flaky cpp tests of `KeySharedConsumerTest`, so I think you can rebase after I push the PR.

**Comment by BewareMyPower** [comment]
I've pushed a PR #8568 to fix the flaky test. As you can see, the tests were passed without any rerun.

**Comment by shustsud** [comment]
Thank you so much.
I will rebase to this PR once [#8568](https://github.com/apache/pulsar/pull/8568) has been merged into master.

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
