### PR TITLE
[Issue:4726] Fix the problem that the log folder in `pulsa-function-go` is ignored

### LINKED ISSUE #4726: pulsar-function-go/log is not exist
**Describe the bug**
`pulsar-function-go/log` is not exist, trying to compile example failed.

**To Reproduce**
create a new pulsar go function and compile
```
go build -o examplepulsar helloFunc.go
```

get the error:

```
$ go build -o examplepulsar helloFunc.go
go: finding github.com/apache/pulsar/pulsar-function-go/log latest
go: finding github.com/apache/pulsar/pulsar-function-go latest
build command-line-arguments: cannot load github.com/apache/pulsar/pulsar-function-go/log: cannot find module providing package github.com/apache/pulsar/pulsar-function-go/log
```

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <ranxiaolong716@gmail.com>

Fixes #4726 

### Motivation

We repackaged the `logrus` log library and named it `log`. But at [.gitignore#L37](https://github.com/apache/pulsar/blob/master/.gitignore#L37), we ignored all `log` files. The log file in `pulsar-function-go` is not uploaded.

In `pulsar-function-go`, the log file is the key to implementing the `logtopic` function, we can't ignore it. So this pull request renames the `log` to `logutil` to avoid this problem.

### CODE REVIEW

**Comment by wolfstudy** [comment]
Thanks @freeznet for pointing this out, PTAL.

**Comment by sijie** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
run integration tests

**Comment by wolfstudy** [comment]
run integration tests

**Comment by wolfstudy** [comment]
run integration tests

**Comment by wolfstudy** [comment]
run java8 tests
run cpp tests
run integration tests

**Comment by wolfstudy** [comment]
run java8 tests

**Pull request merged**
