### PR TITLE
cleaned some code in GenericJsonRecord

### PR DESCRIPTION
**Pull request by abhilashmandaliya**
The do-while loop was executed only once so removed the loop and optimized an inner for-loop to find binaryValue

### Motivation

IDE warning

### Modifications

Simplified the code

### CODE REVIEW

**Comment by abhilashmandaliya** [comment]
@eolivelli @lhotari PTAL

**Review by lhotari — APPROVED** [review]
LGTM

**Review by congbobo184 — APPROVED** [review]
LGTM!

**Comment by hangc0276** [comment]
LGTM!

**Review by eolivelli — CHANGES_REQUESTED** [review]
Good work.
I left a suggestion PTAL

**Review by eolivelli — APPROVED** [review]

**Pull request merged**
