### PR TITLE
Fix the typo of BookKeeper, missing k/K

### PR DESCRIPTION
**Pull request by Shoothzj**
### Motivation
There are several typo of `BookKeeper`, missing k/K

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 
  
- [x] `doc` 
  
  This PR contains doc typo change.

### CODE REVIEW

**Comment by Anonymitaet** [comment]
Doc changes LGTM

**Review by codelipenghui — APPROVED** [review]

**Comment by Shoothzj** [comment]
merge the failure test from master

**Review by hangc0276 — APPROVED** [review]

**Pull request merged**
