### PR TITLE
fix: bundle-data metadata leak because of bundlestats was not clean

### PR DESCRIPTION
**Pull request by leizhiyuan**
Master Issue: #17087

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by gaozhangmin — APPROVED** [review]

**Review by yuruguo — APPROVED** [review]

**Review by RobertIndie — APPROVED** [review]

**Comment by mattisonchao** [comment]
Hi, @leizhiyuan 
Would you like to push a PR to branch-2.9 to fix this problem?

**Comment by Jason918** [comment]
Can you help open a new PR to branch-2.10? There are a lot conflict when cherry-pick directly. @leizhiyuan

**Comment by leizhiyuan** [comment]
> Can you help open a new PR to branch-2.10? There are a lot conflict when cherry-pick directly. @leizhiyuan

ok

**Comment by Jason918** [comment]
`release/2.10.3` moved to https://github.com/apache/pulsar/pull/17463

**Comment by congbobo184** [comment]
Hi @leizhiyuan 
Could you help cherry-pick this PR to branch-2.9? thanks

**Comment by leizhiyuan** [comment]
> [fix][broker]bundle-data metadata leak because of bundlestats was not clean #17316

https://github.com/apache/pulsar/pull/17316  

I have pushed before, please take a look

**Comment by congbobo184** [comment]
> > [fix][broker]bundle-data metadata leak because of bundlestats was not clean #17316
> 
> #17316
> 
> I have pushed before, please take a look

seem the test failed, could you please fix this test? Thanks.

**Comment by congbobo184** [comment]
@leizhiyuan  hi, I move this PR to `release/2.9.5`, if you have any questions, please ping me. thanks.

**Comment by tisonkun** [comment]
Cherry-pick PRs failed and stale. Close them and label this PR with `release/2.10.3`.

**Comment by michaeljmarshall** [comment]
As discussed on the mailing list https://lists.apache.org/thread/w4jzk27qhtosgsz7l9bmhf1t7o9mxjhp, there is no plan to release 2.9.6, so I am going to remove the release/2.9.6 label

**Pull request merged**
