### PR TITLE
[Issue 3364][pulsar-client-tools] Support CLI pulsar-client for concise description

### PR DESCRIPTION
**Pull request by murong00**
### Motivation
Fixes [#3364](https://github.com/apache/pulsar/issues/3364)

### Modifications

Print corresponding usage according to the parsed command.

### CODE REVIEW

**Comment by sijie** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by merlimat** [comment]
run integration tests

**Comment by jiazhai** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Pull request merged**
