### PR TITLE
[Issue 6000][pulsar-client] C++ client ACK grouping feature.

### LINKED ISSUE #6000: Sending Individual ACK for multiple messages in one command.
Shared subscription can only employ Individual ACK, which may limit the throughput. However, from [`PulsarApi.proto`](https://github.com/apache/pulsar/blob/5504dc6e280237ab1abc70fc2889be6149ae518a/pulsar-common/src/main/proto/PulsarApi.proto#L461) we find that Pulsar supports acknowledging multiple messages in one command even in Individual mode.

Java client supports this feature by adding `acknowledgeGroupTime` setting in [`ConsumerBuilder`](http://pulsar.apache.org/api/client/org/apache/pulsar/client/api/ConsumerBuilder.html#acknowledgmentGroupTime-long-java.util.concurrent.TimeUnit-), but C++ client does not.

So the questions are:

1. In Individual ACK mode, does *sending multiple message IDs in one `CommandAck`* really help achieving higher throughput?
2. If we implement this feature in C++ client (and later contribute back to community), shall it be implemented as an ACK interface, or as a setting like in Java. (Seems the previous one is easier.)
3. If it's implemented as an ACK interface, what should it be called? `acknowledgeGroup` or `groupAcknowledge`? We prefer the term `group`, because the C++ client has a data structure called `BatchAcknowledgeTracker`, which may confuse the code reader when we have two similar names for different purpose.

### BTW

**Does `acknowledge` interface in C++ client really send ACK synchronously?**

It actually calls the [`acknowledgeAsync`](https://github.com/apache/pulsar/blob/5504dc6e280237ab1abc70fc2889be6149ae518a/pulsar-client-cpp/lib/Consumer.cc#L87) and waits for triggering of the callback. But the [`doAcknowledge`](https://github.com/apache/pulsar/blob/5504dc6e280237ab1abc70fc2889be6149ae518a/pulsar-client-cpp/lib/ConsumerImpl.cc#L790) calls returns immediately anyway with `ResultOk`, because sending command is actually an asynchronous operation? Is this a known feature/issue? Or I just misunderstand the implementation? Is there any opened issues related to this?

### PR DESCRIPTION
**Pull request by tongsucn**
Fixes #6000 

### Motivation

In our production environment, we created a sinker: It combines messages read from Pulsar, and writes the combined data into ClickHouse, which is not good at processing highly concurrent inserting (max. 100 QPS).

In the sinker, we used failover subscription with cumulative ACK. The reason for not using shared subscription is that, individual ACK in C++ client siginificantly reduces throughput. Our analysis shows that huge amount of individual ACK requests results in highly concurrent accessing, which finally results in terrible throughput. BTW, the machines, where we deploy brokers and bookies, are not equipped with SSD. There could be some configuration for brokers or bookies helping improving the situation, but we don't find them.

Therefore, the idea is that combining individual ACK requests within one request. After reading the protocol (PulsarApi.proto:CommandAck), we find that this feature is supported. According to this issue #6000 , Pulsar C++ client SDK does not implement ACK grouping feature, but it's already implemented by Java client.

After discussing with @jiazhai and @sijie , we are authorized to implement this feature and contribute this feature back to community later. It should follow the Java client's behavior and provide similar interfaces that Java client provides.

#### Interfaces

Similar to Java client, C++ client implements three trackers to *cache* ACK requests within a configured time window:

1. `AckGroupingTracker`: this is the base class of the other two trackers, it defines interfaces and provides empty implementation which does not send ACK requests to broker. This tracker is used for non-persistent topic, which actually does not require ACK.
2. `AckGroupingTrackerDisabled`: child class of `AckGroupingTracker`. It does not provide ACK grouping ability, and acts just like the previous individual ACK.
3. `AckGroupingTrackerEnabled`: child class of `AckGroupingTracker`. This is the real implementation of ACK grouping.

The trackers provides following public interfaces:

1. `isDuplicate`: checking if the given message ID exists in the TO-BE-ACKED group.
2. `addAcknowledge` and `addAcknowledgeCumulative`: unlike Java client, which combines these two interfaces into one (`addAcknowledge`), C++ clients provides them for individual and cumulative ACK requests. Such design can provide slightly better performance than if-else implementation.
3. `close`: closing the tracker.
4. `flush` and `flushAndClean`: flushing all pending ACK requests, the later one also resets internal status.

#### Consumer's Configuration

Two new configuration options are added:

1. `ackGroupingTimeMs`: time window in milliseconds for grouping ACK requests. If setting to positive value, ACK requests are grouped and sent to broker every `ackGroupingTimeMs` milliseconds (`AckGroupingTrackerEnabled`). For non-positive values, ACK requests are sent one by one to brokers as before (`AckGroupingTrackerDisabled`). Default is 100.
2. `ackGroupingMaxSize`: maximum number of grouped message IDs. Java client hard-coded it to 1000 for now. However, 1000 is too small in our scenario. Once the grouped message number reaches this limit, the ACK requests will be packed into one and sent to broker, even the ACK grouping deadline (`ackGroupingTimeMs`) is not reached. Non-positive values remove such limit.

**In addition**, these configurations are added into C API as well.

#### Commands for this feature.

A few new command factory interfaces are implemented, just like in Java, incl.

* `newMultiMessageAck`: command object for multi-message ACK requests.
* `peerSupports*`: interfaces for checking versions.

#### Topic Domain

Used to help defining and distinguish non-persistent and persistent topics.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This PR added 7 unit tests in `BasicEndToEndTest`, all of them start with `testAckGroupingTracker`. They cover the ACK grouping tracker's logic.

### Does this pull request potentially affect one of the following parts:

NO

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by jiazhai** [comment]
@tongsucn Thanks for the great work. Would you please add a unit tests in BasicEndToEndTest to protect your code?

**Comment by tongsucn** [comment]
> @tongsucn Thanks for the great work. Would you please add a unit tests in BasicEndToEndTest to protect your code?

No problem. BTW, the *Backwards Compatibility* CI process failed because of storage issue. Do I need to deal with it or just try again later?

**Comment by tongsucn** [comment]
@jiazhai Hi, I added necessary unit tests and updated the description above. However, the `cpp-tests` continuously and randomly fail on different cases, which are passed in my container. Shall I keep trying rerunning failure checks?

**Comment by tongsucn** [comment]
@jiazhai Finally, all tests passed!

**Comment by tongsucn** [comment]
Hi, I just noticed that latest master branch has some conflicts with my test code, shall I resolve it? @sijie

**Comment by sijie** [comment]
@tongsucn yes. Can you rebase this pull request to the latest master?

**Comment by tongsucn** [comment]
> @tongsucn yes. Can you rebase this pull request to the latest master?

@sijie DONE

**Comment by codelipenghui** [comment]
@tongsucn Can you rebase this pull request to the latest master? Looks there are some conflicts with the master branch.

**Comment by codelipenghui** [comment]
@tongsucn Could you please take a look at the CI CPP tests? Looks related to the code format.

**Comment by tongsucn** [comment]
> @tongsucn Could you please take a look at the CI CPP tests? Looks related to the code format.

@codelipenghui Hi, it passes `make check-format` in my container, and running `make format` does not affect any code. This is really weird....

```bash
root@THOSTNAME:/pulsar/pulsar-client-cpp# git rev-parse HEAD
77c84c7efef4732534a38d126a26ba624f7e17f9
root@THOSTNAME:/pulsar/pulsar-client-cpp# git status
On branch ackgroup
Your branch is up-to-date with 'origin/ackgroup'.
nothing to commit, working directory clean
root@THOSTNAME:/pulsar/pulsar-client-cpp# make check-format
Scanning dependencies of target check-format
Built target check-format
```

**Comment by jiazhai** [comment]
last fix was on mac, I will make format under ubuntu env.

**Pull request merged**
