### PR TITLE
Ensure getting list of topics for namespace is handled asynchronously

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

The handler for the `GetTopicsOfNamespace` on broker side is processing the request in sync mode. This is used when periodically fetching the list of topics from regex consumers. 

Most of the time this is not an issue since the list of topics is locally cached in the zk children cache. Though when there is an eviction (eg. we discard all cached entries after 5mins), we're forced to do a blocking call.

This call will block the IO thread for extended amount of time, impacting other topics as well.

There must be no potentially blocking calls made from IO threads.

### CODE REVIEW

**Comment by merlimat** [comment]
run integration tests

**Comment by codelipenghui** [comment]
retests this please

**Comment by codelipenghui** [comment]
retest this please

**Comment by merlimat** [comment]
run java8 tests
run integration tests

**Comment by merlimat** [comment]
run cpp tests

**Comment by merlimat** [comment]
run cpp tests

**Pull request merged**
