### PR TITLE
Fix the problem that batchMessageId is converted to messageIdImpl

### LINKED ISSUE #8712: Flaky-test: TopicReaderTest.testHasMessageAvailable
TopicReaderTest.testHasMessageAvailable is flaky

[example failure](https://github.com/apache/pulsar/pull/8707/checks?check_run_id=1456314338#step:11:306):
```
Error:  Tests run: 46, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 367.157 s <<< FAILURE! - in org.apache.pulsar.client.api.TopicReaderTest
Error:  testHasMessageAvailable(org.apache.pulsar.client.api.TopicReaderTest)  Time elapsed: 3.903 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertTrue(Assert.java:45)
	at org.testng.Assert.assertTrue(Assert.java:55)
	at org.apache.pulsar.client.api.TopicReaderTest.testHasMessageAvailable(TopicReaderTest.java:973)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by 315157973**
Fixes #8712

### Motivation
TopicReaderTest.testHasMessageAvailable is flaky
Cause Analysis:
When there is only one message in the batch, calling Broker's `GetLastMessageId` will determine that this is not a batch message, and then return a `MessageIdImpl`. (See ServerCnx line 1553)
In the same scenario, the client will return a `BatchMessageId` after sending a message. (See ProducerImpl line 1151)

This will happen:
MessageIdImpl: `3:31:-1`
BatchMessageId: `3:31:-1:0`

When calling `reader.hasMessageAvailable()`, the two ids will be compared, like this: `lastMessageIdInBroker.compareTo(messageId)`
Although it is the same messageId, the results will not be equal.

### Modifications
When we call `admin.topics().getLastMessageId`, even if there is only one message in the batch, it is considered to be BatchMessageId. Client also acts like this.
Therefore, we keep consistent everywhere.
Even if there is only one message in the batch, we think it is `BatchMessageId`

### CODE REVIEW

**Review by codelipenghui — COMMENTED** [review]
@315157973 Is it possible to add a unit test for this change?

**Comment by zymap** [comment]
We have a fix of the integration tests. Please rebase your code. Thanks.

**Review by codelipenghui — APPROVED** [review]

**Review by sijie — APPROVED** [review]

**Pull request merged**
