### PR TITLE
Version docs for the 2.8.3 release

### PR DESCRIPTION
**Pull request by michaeljmarshall**
### Motivation

Add the 2.8.3 versioned docs for the 2.8.3 release, as the release process wiki documents.

### CODE REVIEW

**Review by Anonymitaet — COMMENTED** [review]
`release.json` and `versions.json` should be updated after 2.8.3 is released (after that, 2.8.3 should be shown on the website)
Reference: https://github.com/apache/pulsar/pull/10666

FYI  @D-2-Ed @DaveDuggins @momo-jun

**Comment by michaeljmarshall** [comment]
@Anonymitaet - can you clarify your statement? When do we consider 2.8.3 released? I would have thought it was already considered "released", as the binaries and the docker images are already available publicly. Updating the documentation and the release notes are my last step before sending out the "announce" email.

**Review by eolivelli — APPROVED** [review]

**Comment by Anonymitaet** [comment]
2.8.3 doc is not shown
image

Pulsar website build is down
https://github.com/apache/pulsar/actions/workflows/ci-pulsar-website-build.yaml
image

**Comment by michaeljmarshall** [comment]
@Anonymitaet - it looks like the failures started before I merged this. I can look at the logs to understand it more.

**Comment by michaeljmarshall** [comment]
It appears that the build is failing due to a timeout. @Anonymitaet - do you know why we're building the python client during the website build?

**Comment by Anonymitaet** [comment]
> It appears that the build is failing due to a timeout. @Anonymitaet - do you know why we're building the python client during the website build?

@urfreespace do you have any idea on this?

**Pull request merged**
