### PR TITLE
[fix][doc] Fix 404 in security-tls-transport.md

### LINKED ISSUE #16844: [Doc] The openssl.cnf file is missing
### What issue do you find in Pulsar docs?

In the doc, it metions to get the sample openssl.cnf from the below website. But the file is not there any more.

https://raw.githubusercontent.com/apache/pulsar/master/site2/website/static/examples/openssl.cnf

### What is your suggestion?

Please make the openssl.cnf availalbe.

### Do you have any references?

Doc link: https://pulsar.apache.org/docs/security-tls-transport#certificate-authority

### Would you like to fix this issue?

Do not know how to fix it.

### Note

- [X] I have researched my question.

### LINKED ISSUE #16877: [Doc]
### What issue do you find in Pulsar docs?

In the security > Transport Encryption using TLS the "openssl.cnf" is referenced to be downloaded and used create the certs. The problem is that it doesn't exist in that location, and cannot be downloaded.

wget https://raw.githubusercontent.com/apache/pulsar/master/site2/website/static/examples/openssl.cnf

### What is your suggestion?

Fix the link.

### Do you have any references?

wget https://raw.githubusercontent.com/apache/pulsar/master/site2/website/static/examples/openssl.cnf

### Would you like to fix this issue?

No

### Note

- [X] I have researched my question.

### PR DESCRIPTION
**Pull request by RobertIndie**
Fixes #16877,  fixes #16844

### Motivation

There is a 404 link in the doc of `security > Transport Encryption`.
```
wget https://raw.githubusercontent.com/apache/pulsar/master/site2/website/static/examples/openssl.cnf
```
### Modifications

* Fix the link

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [ ] `doc-not-needed` 
(Please explain why)
  
- [x] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by Anonymitaet — APPROVED** [review]

**Comment by Anonymitaet** [comment]
FYI @urfreespace

**Review by urfreespace — APPROVED** [review]

**Comment by delgemoon** [comment]
I am getting this again

wget https://raw.githubusercontent.com/apache/pulsar-site/main/site2/website/static/examples/openssl.cnf
--2022-11-19 14:09:57--  https://raw.githubusercontent.com/apache/pulsar-site/main/site2/website/static/examples/openssl.cnf
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8000::154, 2606:50c0:8003::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8000::154|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-11-19 14:09:57 ERROR 404: Not Found.

**Comment by JohnTangZX** [comment]
The issue is still there.

**Comment by tisonkun** [comment]
File structure is changed. And we should use url based on pulsar.apache.org instead of github.

I'll push a fix in hours.

cc @delgemoon @JohnTangZX

**Comment by tisonkun** [comment]
@JohnTangZX @delgemoon The link is updated to https://pulsar.apache.org/examples/openssl.cnf, and the latest doc is changed also.

If you still encounter the issue, please share what page (url) you see the link, as well as a screenshot.

**Pull request merged**
