### PR TITLE
[Authorization] Fix producer/consume permission can’t get v1/schema

### LINKED ISSUE #12419: Adjust the judgment logic of topic schema operation permissions
**Is your enhancement request related to a problem? Please describe.**
The `role`(not super-user) that has the `lookup` topic permission should also have the operation permission of the topic schema, for example, the `role` could get topic schema through `./bin/pulsar-admin schemas get tenant1/ns1/tp1`.
But I found that we first judge whether the `role` has access to the `tenant` of this topic, as below:
https://github.com/apache/pulsar/blob/a455d06af19a30aae6edf56d0b6570b23973c48d/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/SchemasResource.java#L82-L91
https://github.com/apache/pulsar/blob/a455d06af19a30aae6edf56d0b6570b23973c48d/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SchemasResourceBase.java#L87-L94
https://github.com/apache/pulsar/blob/a455d06af19a30aae6edf56d0b6570b23973c48d/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SchemasResourceBase.java#L309-L312
`L311`'s effect is to `check the http client role has admin access to the specified tenant`. 
Since the `role` only has the authority to `lookup` this topic, so it cannot be passed. 
I have doubts about the rationality of this judgment( call `L311`), and we should converge the scope of this judgment.

**Describe the solution you'd like**
Remove this judgment, and replace it with a judgment whether the `role` has the `lookup` permission for this topic, as below:
```
    private void validateDestinationAndAdminOperation(boolean authoritative) {
        try {
            // validateAdminAccessForTenant(topicName.getTenant());
            validateTopicOwnership(topicName, authoritative);
            validateTopicOperation(topicName, TopicOperation.LOOKUP);
```

### PR DESCRIPTION
**Pull request by yuruguo**
Fixes #12419 

### Motivation
The pr-#15956 has been fixed the problem that role has `producer/consume` permission can’t get `v2/schema`, but it 
missed `v1/schema`. So this pr solves the permission problem to get v1/schema.

### Modifications
- Get `v1/schema` need `GET_METADATA` permission

### Documentation
- [x] `doc-not-needed`

### CODE REVIEW

**Comment by nodece** [comment]
Could you make these methods async?

**Comment by yuruguo** [comment]
> Could you make these methods async?

**Review by AnonHxy — APPROVED** [review]

**Comment by codelipenghui** [comment]
@yuruguo There is a mailing list for discussing the V1 topic name https://lists.apache.org/thread/t3w9wjjkz4tfl5zwrmj44827vdpk2f4p

I will remove the 2.10.1 label to unblock 2.10.1 release.

**Comment by yuruguo** [comment]
> @yuruguo There is a mailing list for discussing the V1 topic name https://lists.apache.org/thread/t3w9wjjkz4tfl5zwrmj44827vdpk2f4p
> 
> I will remove the 2.10.1 label to unblock 2.10.1 release.
Thanks for your sharing @codelipenghui 
In fact, this should belong to the same kind of question, that is, whether to continue to update or maintain the existing problems in the `v1` version.
I will continue to track it.

**Comment by yuruguo** [comment]
> @yuruguo There is a mailing list for discussing the V1 topic name https://lists.apache.org/thread/t3w9wjjkz4tfl5zwrmj44827vdpk2f4p
> 
> I will remove the 2.10.1 label to unblock 2.10.1 release.


Thanks for your sharing @codelipenghui
In fact, this should belong to the same kind of question, that is, whether to continue to update or maintain the existing problems in the v1 version. And I will continue to track it.

**Comment by Jason918** [comment]
@yuruguo Can you help cherry-pick this PR to branch-2.10

**Comment by yuruguo** [comment]
> @yuruguo Can you help cherry-pick this PR to branch-2.10

We can do nothing after #16026 merged, because v1 & v2 schema both use `SchemasResourceBase` and this problem has
 been resolved in `SchemasResourceBase`.

**Comment by Jason918** [comment]
> We can do nothing after #16026 merged, because v1 & v2 schema both use `SchemasResourceBase` and this problem has
> been resolved in `SchemasResourceBase`.

OK, I will remove `release/2.10.2`. Thanks.

**Comment by poorbarcode** [comment]
@yuruguo 

This PR also fixed another issue that responds an incorrect HTTP header `Content-Encoding`. See the detail below: 

```
curl -X GET -H "Content-Type:application/json" http://127.0.0.1:50040/admin/v2/schemas/my-property/my-ns/test-client-version/schema 

{"version":0,"type":"STRING","timestamp":1700539331898,"data":"","properties":{}}                                                                                                                                                                  

HTTP/1.1 200 OK
Date: Tue, 21 Nov 2023 06:33:45 GMT
broker-address: localhost
Content-Encoding: application/json
Content-Type: application/json
Content-Length: 81
Server: Jetty(9.4.51.v20230217)
```

https://github.com/apache/pulsar/pull/16018/files#diff-4bd0e9058034ada018ee4d5a4e8b950163b851e6933bf22298eb563947d54d2eL361-L362


I cherry-picked this PR into `branch-2.11`, @yuruguo Could you cherry-pick this PR into `branch-2.10`?

**Pull request merged**
