### PR TITLE
[fix][website] website build fail due to invalid tab

### PR DESCRIPTION
**Pull request by urfreespace**
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

[fix][website] website build fail due to invalid tab

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #<xyz>

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `no-need-doc` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-added`
(Docs have been already added)

### CODE REVIEW

**Review by Anonymitaet — APPROVED** [review]

**Review by gaoran10 — APPROVED** [review]

**Review by HQebupt — APPROVED** [review]

**Comment by lhotari** [comment]
@Anonymitaet @gaoran10 @HQebupt This change doesn't look right. Did you review the changes?

It looks like you merged merge conflict markers in the files.
@urfreespace please fix this

**Comment by lhotari** [comment]
@urfreespace if you aren't going to provide any description, it's better to remove the template.

> _(If this PR fixes a github issue, please add `Fixes #<xyz>`.)_
> 
> [fix][website] website build fail due to invalid tab
> 
> _(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)_
> 
> Master Issue: #
> 
> ### Motivation
> _Explain here the context, and why you're making that change. What is the problem you're trying to solve._
> 
> ### Modifications
> _Describe the modifications you've done._
> 
> ### Verifying this change
> * [ ]  Make sure that the change passes the CI checks.
> 
> _(Please pick either of the following options)_
> 
> This change is a trivial rework / code cleanup without any test coverage.
> 
> _(or)_
> 
> This change is already covered by existing tests, such as _(please describe tests)_.
> 
> _(or)_
> 
> This change added tests and can be verified as follows:
> 
> _(example:)_
> 
> * _Added integration tests for end-to-end deployment with large payloads (10MB)_
> * _Extended integration test for recovery after broker failure_
> 
> ### Does this pull request potentially affect one of the following parts:
> _If `yes` was chosen, please highlight the changes_
> 
> * Dependencies (does it add or upgrade a dependency): (yes / no)
> * The public API: (yes / no)
> * The schema: (yes / no / don't know)
> * The default values of configurations: (yes / no)
> * The wire protocol: (yes / no)
> * The rest endpoints: (yes / no)
> * The admin cli options: (yes / no)
> * Anything that affects deployment: (yes / no / don't know)
> 
> ### Documentation
> Check the box below or label this PR directly.
> 
> Need to update docs?
> 
> * [ ]  `doc-required`
>   (Your PR needs to update docs and you will update later)
> * [x]  `no-need-doc`
>   (Please explain why)
> * [ ]  `doc`
>   (Your PR contains doc changes)
> * [ ]  `doc-added`
>   (Docs have been already added)

**Comment by RobertIndie** [comment]
@urfreespace This PR seems not right. It currently caused all the Pulsar website builds workflow to fail. https://github.com/apache/pulsar/runs/6023538038?check_suite_focus=true#step:9:145

```
/pulsar/site2/tools/build-site.sh: line 33: syntax error near unexpected token `<<<'
/pulsar/site2/tools/build-site.sh: line 33: `<<<<<<< HEAD'
```

**Comment by urfreespace** [comment]
@RobertIndie @lhotari  I'm so sorry, fixed with this PR: https://github.com/apache/pulsar/pull/15179

**Pull request merged**
