### PR TITLE
[fix][doc] fix typo in ConsumerConfigurationData and ServiceConfiguration.

### PR DESCRIPTION
**Pull request by SeasonPanPan**
fix typo in ConsumerConfigurationData and ServiceConfiguration.

img

### Modifications
threashold --> threshold
aconsumer --> a consumer
createdif --> created if

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: 
https://github.com/SeasonPanPan/pulsar/pull/1

### CODE REVIEW

**Review by AnonHxy — APPROVED** [review]

**Review by RobertIndie — APPROVED** [review]

**Review by lightzhao — APPROVED** [review]

**Review by momo-jun — APPROVED** [review]
LGTM

**Review by maxsxu — APPROVED** [review]

**Comment by Anonymitaet** [comment]
@SeasonPanPan please fill in this part in your PR description. 
image

Feel free to ping me to merge if all tests pass.

**Comment by SeasonPanPan** [comment]
> @SeasonPanPan please fill in this part in your PR description. image
> 
> Feel free to ping me to merge if all tests pass.

Done

**Comment by SeasonPanPan** [comment]
@Anonymitaet I checked the CI error, it was not code reason, maybe it was the env problem.

**Comment by Anonymitaet** [comment]
@SeasonPanPan I've tried re-running the failed tests several times but they still failed. Have you tried pulling the latest master and then merging?

**Comment by SeasonPanPan** [comment]
@Anonymitaet I've pushed a new PR for https://github.com/apache/pulsar/pull/19906

**Pull request closed without merging**
