### PR TITLE
[WIP][ci] Change packaging plugin from dockerfile-maven-plugin to docker-maven-plugin

### LINKED ISSUE #16652: Build the docker image without dockerfile-maven-plugin
As described in https://github.com/apache/pulsar/discussions/16642, dockerfile-maven-plugin doesn't support Apple M1 and the project itself is end-of-life.

For supporting developers using Apple M1 clip, we can migrate the building logic to other plugin. Here's some candidates:

* [docker-maven-plugin](https://github.com/fabric8io/docker-maven-plugin) is provided by fabric8io and actively maintained. However, the plugin logic is quite different from dockerfile-maven-plugin as the former may be over fruitful.
* maven-exec-plugin. dockerfile-maven-plugin is effectively a thin wrapper of `docker` commands. We may directly run those commands with maven-exec-plugin.
* A makefile. Apache SkyWalking uses a [Makefile](https://github.com/apache/skywalking/blob/master/Makefile) to hold logics about building docker image. It should be in the same direction with maven-exec-plugin but switches build system switch to Makefile.

cc @lhotari what do you think? At least I'd like to know the effectively executed `docker` commands so that I can run from command line interface and build those images manually.

### PR DESCRIPTION
**Pull request by skyleaworlder**
Fixes #16652 

### Motivation

dockfile-maven-plugin is archived now, and it doesn't perform on M1 as @tisonkun says.

### Modifications

I choose docker-maven-plugin to replace docker-maven-plugin.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

**This PR don't pass CI in my fork repo, because it seems that workflows related to "build-docker" were not invoked**. So I might need some help.

### Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): **yes**
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no
  - The rest endpoints: no
  - The admin cli options: no
  - Anything that affects deployment: **yes**

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 

All docs are available [here](http://dmp.fabric8.io/).
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Comment by tisonkun** [comment]
cc @lhotari could you check whether this change is in a good direction?

If so, please help trigger the CI workflow.

**Comment by merlimat** [comment]
@skyleaworlder I had tried to work on this in #16099 though there were some issues that I didn't get time to fix. Can you check and compare both PRs?

**Comment by skyleaworlder** [comment]
> @skyleaworlder I had tried to work on this in #16099 though there were some issues that I didn't get time to fix. Can you check and compare both PRs?

It's my pleasure. I have checked changes in #16099. I find some tags (registry or latest version) loss compared to dockerfile-maven-plugin version.

I've also checked failed workflows' result and I find https://repository.apache.org/snapshots/org/apache/pulsar/pulsar-docker-image/2.11.0-SNAPSHOT/pulsar-docker-image-2.11.0-SNAPSHOT-docker-info.jar is not available. But I don't know why others (e.g. [here](https://github.com/apache/pulsar/runs/7414676660?check_suite_focus=true)) have the same workflow.yaml passed.

```xml
     <dependencies>
        <dependency>
          <groupId>${project.groupId}</groupId>
          <artifactId>pulsar-docker-image</artifactId>
          <version>${project.version}</version>
          <classifier>docker-info</classifier>
        </dependency>
     </dependencies>
```

image

**Comment by tisonkun** [comment]
> I've also checked failed workflows' result and I find https://repository.apache.org/snapshots/org/apache/pulsar/pulsar-docker-image/2.11.0-SNAPSHOT/pulsar-docker-image-2.11.0-SNAPSHOT-docker-info.jar is not available. But I don't know why others (e.g. [here](https://github.com/apache/pulsar/runs/7414676660?check_suite_focus=true)) have the same workflow.yaml passed.

Generally if you cannot resolve an artifact from remote server, it should fallback to local maven repository and find it.

**Comment by tisonkun** [comment]
If you cannot find it locally, it's possibly that the execution generate the snapshot doesn't execute before the failure execution gets executed.

**Comment by tisonkun** [comment]
I'm going to work on this issue in the following weeks and see if I can offer some help.

**Comment by tisonkun** [comment]
It seems `docker-info` is something specific to `dockerfile-maven-plugin` and we can remove it.

**Comment by skyleaworlder** [comment]
> I'm going to work on this issue in the following weeks and see if I can offer some help.

Sorry I just saw this message and I have to say that I have little time to track this issue in the following days. 😢

**Comment by tisonkun** [comment]
@skyleaworlder never mind. Your patch is a good starting point. If you return here later and find the issue still open, you can continue it. Or you're always welcome to contribute to Apache Pulsar :)

**Pull request closed without merging**
