### PR TITLE
fix non threadsafe

### PR DESCRIPTION
**Pull request by MaiCw4J**
Signed-off-by: mak <610546069@qq.com>

*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #<xyz>

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #<xyz>

### Motivation
1. fix non threadsafe
2. track multiTopics batch message

when batchReceive request and batchReceiveTimeout task concurrent execution, may produce data race?.

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by MaiCw4J** [comment]
If I misunderstand, please correct me  ;)  
(I'm still reading the code)

**Comment by sijie** [comment]
@codelipenghui Can you review this?

**Review by eolivelli — CHANGES_REQUESTED** [review]
@MaiCw4J can you please set a better Title and a fill in the description of this PR ?

I also see that there are not test cases, is your change already covered by existing tests ?

**Review by MarvinCai — COMMENTED** [review]
Seem to me this pr is trying to remove some duplicate code, not sure how it's changing safeness of the method?

**Comment by zymap** [comment]
@MaiCw4J Could you please take a look at the comments? 

I will push this to the next release.

**Comment by codelipenghui** [comment]
The pr had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale and conflict. Please rebase and submit a new patch if it's still relevant.

**Pull request closed without merging**
