### PR TITLE
[fix][sql] Fix jline version to 3.21.0

### PR DESCRIPTION
**Pull request by tisonkun**
Using jline before 3.21.0 may cause a "Bad address" failure on Apple M1 environment. We're using 3.21.0 globally, so forcibly apply this version to pulsar-sql dependencies.

See also https://github.com/scala/scala/pull/9807.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [x] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by tisonkun** [comment]
cc @merlimat @nicoloboschi

**Review by nicoloboschi — APPROVED** [review]
LGTM, please update the pull description

**Comment by tisonkun** [comment]
@nicoloboschi Thanks for your review. Updated.

**Comment by tisonkun** [comment]
ping @merlimat @nicoloboschi

I think this patch is ready for merge now. Tests fail on:

```
  Error:  testSharedSamePriorityConsumer(org.apache.pulsar.broker.service.persistent.SimpleProducerConsumerTestStreamingDispatcherTest)  Time elapsed: 16.774 s  <<< FAILURE!
  java.lang.AssertionError: expected [500] but found [501]
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.failNotEquals(Assert.java:1037)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
  	at org.testng.Assert.assertEquals(Assert.java:122)
  	at org.testng.Assert.assertEquals(Assert.java:907)
  	at org.testng.Assert.assertEquals(Assert.java:917)
  	at org.apache.pulsar.client.api.SimpleProducerConsumerTest.testSharedSamePriorityConsumer(SimpleProducerConsumerTest.java:2513)
```

which is reported at https://github.com/apache/pulsar/issues/16795

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
