### PR TITLE
Statsd

### PR DESCRIPTION
**Pull request by KannarFr**
will write it..

### CODE REVIEW

**Review by eolivelli — COMMENTED** [review]
Nice feature!

I wonder if there is a way to make this an additional module, without the need to bundle it to the default distribution.

In BookKeeper the 'stats provider' is pluggable
https://github.com/apache/bookkeeper/blob/master/bookkeeper-stats/src/main/java/org/apache/bookkeeper/stats/StatsLogger.java

**Review by sijie — CHANGES_REQUESTED** [review]
@KannarFr as we discussed in a separate pull request, I don't think we should add a specific integration as part of brokers. 

You can have a sidecar running along with the broker to scrape broker metrics and send them to StatsD. I am not convinced by this approach.

**Comment by waxzce** [comment]
@sijie as I ask @KannarFr to work on it, I step in. Pulling the metrics is OK if you do not manage large clusters, but if you have few millions of topics (like we do), your pulling will load extensively the brokers and eventually timeout. As I assume lots of users want to rely on prometeus, it's great to provide it, but any sizeable deployment will ending up needing some push mechanism. For what is worth, event google who send us to the dark pattern of pull have made some communications acknowledging that they switch to push https://twitter.com/copyconstruct/status/1299949569057333249?s=19 I'm open to discuss If you need.

**Comment by KannarFr** [comment]
> Nice feature!
> 
> I wonder if there is a way to make this an additional module, without the need to bundle it to the default distribution.
> 
> In BookKeeper the 'stats provider' is pluggable
> https://github.com/apache/bookkeeper/blob/master/bookkeeper-stats/src/main/java/org/apache/bookkeeper/stats/StatsLogger.java

Yup!

**Comment by tisonkun** [comment]
Closed as stale and conflict. Please rebase and submit a new patch if it's still relevant.

**Pull request closed without merging**
