### PR TITLE
[Broker]Reset cursor with a non-exists position

### PR DESCRIPTION
**Pull request by yjshen**
`ManagedCursorImpl.asyncResetCursor` is used in three kinds of circumstances:
- REST API: create a subscription with messageId. Per the document: Reset subscription to message position closest to given position.
- REST API: reset subscription to a given position: Per the document: Reset subscription to message position closest to given position.
- Consumer seek command.

In all the cases above, when the user provides a MessageId, we should make the best effort to find the closest position, instead of throwing an InvalidCursorPosition Exception. 

This is because if a user provids an invalid position, it's not possible for he or she gets a valid position, since ledger ids for a given topic may not be continuous and only brokers are aware of the order. Therefore, we should avoid throw invalid cursor position but find the nearest position and do the reset stuff.

### CODE REVIEW

**Comment by yjshen** [comment]
@sijie @jiazhai  What do you think of the approach? If we get an agreement on the method, I'll add tests then.

**Comment by jiazhai** [comment]
@yjshen this looks good. `getNextValidPosition` did most of the handling.

**Comment by sijie** [comment]
+1

**Comment by yjshen** [comment]
Test added. PTAL.

**Comment by yjshen** [comment]
> looks good. please go ahead to add tests. and maybe add docs also?

Previous implementation doesn't match the Rest API documentation: `Reset subscription to message position closest to given position.` This PR just make it agree on the doc, so I think no more doc is needed?

**Pull request merged**
