### PR TITLE
[Issue 4981][docs] The reference page of Configuration updated

### LINKED ISSUE #4981: [Doc] update config docs
[Docs](https://pulsar.apache.org/docs/en/reference-configuration/#broker) not up-to-date with [conf](https://github.com/apache/pulsar/blob/branch-2.4/conf/broker.conf)

for example `isSchemaValidationEnforced=false` is not there

### PR DESCRIPTION
**Pull request by BGRichi**
Fixes #4981

### Motivation

The Doc content is out of date, with differences existing between broker.conf and the current doc. 

### Modifications

Items removed:

clientLibraryVersionCheckAllowUnversioned
loadBalancerBrokerComfortLoadLevelPercentage
loadBalancerBrokerUnderloadedThresholdPercentage
loadBalancerPlacementStrategy
s3ManagedLedgerOffloadRole
s3ManagedLedgerOffloadRoleSessionName
tokenPublicAlg

Items added:

anonymousUserRole
authenticateOriginalAuthData
authorizationAllowWildcardsMatching
authorizationProvider
backlogQuotaDefaultRetentionPolicy
bookkeeperUseV2WireProtocol
bootstrapNamespaces
brokerClientTlsEnabled
brokerClientTrustCertsFilePath
brokerServicePurgeInactiveFrequencyInSeconds
defaultNumberOfNamespaceBundles
defaultNumPartitions
delayedDeliveryEnabled
delayedDeliveryTickTimeMillis
dispatcherMaxReadBatchSize
dispatcherMaxRoundRobinBatchSize
dispatcherMinReadBatchSize
dispatchThrottlingOnNonBacklogConsumerEnabled
dispatchThrottlingRatePerReplicatorInByte
dispatchThrottlingRatePerReplicatorInMsg
dispatchThrottlingRatePerSubscriptionInByte
dispatchThrottlingRatePerSubscriptionInMsg
dispatchThrottlingRatePerTopicInByte
dispatchThrottlingRatePerTopicInMsg
enableReplicatedSubscriptions
enableRunBookieAutoRecoveryTogether
enableRunBookieTogether
exposeConsumerLevelMetricsInPrometheus
exposePublisherStats
exposeTopicLevelMetricsInPrometheus
failureDomainsEnabled
gcsManagedLedgerOffloadBucket
gcsManagedLedgerOffloadMaxBlockSizeInBytes
gcsManagedLedgerOffloadReadBufferSizeInBytes
gcsManagedLedgerOffloadRegion
gcsManagedLedgerOffloadServiceAccountKeyFile
globalZookeeperServers
isRunningStandalone
isSchemaValidationEnforced
loadBalancerAutoUnloadSplitBundlesEnabled
loadBalancerOverrideBrokerNicSpeedGbps
loadBalancerSheddingEnabled
managedLedgerAddEntryTimeoutSeconds
managedLedgerDigestType
managedLedgerMaxUnackedRangesToPersistInZooKeeper
managedLedgerMetadataOperationsTimeoutSeconds
managedLedgerNumSchedulerThreads
managedLedgerNumWorkerThreads
managedLedgerOffloadDeletionLagMs
managedLedgerReadEntryTimeoutSeconds
managedLedgerUnackedRangesOpenCacheSetEnabled
maxConcurrentNonPersistentMessagePerConnection
maxConsumersPerSubscription
maxConsumersPerTopic
maxMessageSize
maxProducersPerTopic
maxUnackedMessagesPerBroker
maxUnackedMessagesPerSubscriptionOnBrokerBlocked
numHttpServerThreads
numIOThreads
numWorkerThreadsForNonPersistentTopic
offloadersDirectory
proxyRoles
replicatedSubscriptionsSnapshotFrequencyMillis
replicatedSubscriptionsSnapshotMaxCachedPerSubscription
replicatedSubscriptionsSnapshotTimeoutSeconds
saslJaasBrokerSectionName
saslJaasClientAllowedIds
schemaRegistryStorageClassName
statsUpdateFrequencyInSecs
statsUpdateInitialDelayInSecs
subscribeRatePeriodPerConsumerInSecond
subscribeThrottlingRatePerConsumer
subscriptionExpirationTimeMinutes
subscriptionExpiryCheckIntervalInMinutes
subscriptionKeySharedEnable
tlsCertRefreshCheckDurationSec
tlsRequireTrustedClientCertOnConnect
ttlDurationDefaultInSeconds
webSocketConnectionsPerBroker
webSocketNumIoThreads
webSocketSessionIdleTimeoutMillis
zooKeeperOperationTimeoutSeconds

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  **- The public API: yes**
  - The schema: don't know
  - The default values of configurations: yes
  - The wire protocol: no
  **- The rest endpoints: yes**
  - The admin cli options: no
  - Anything that affects deployment: don't know

### Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? 
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by jiazhai** [comment]
@BGRichi , Seems some of the removed items are still useful?
e.g.
```
s3ManagedLedgerOffloadRole
s3ManagedLedgerOffloadRoleSessionName
tokenPublicAlg
```

**Comment by BGRichi** [comment]
@jiazhai the modification follows [broker.conf (2.4)](https://github.com/apache/pulsar/blob/branch-2.4/conf/broker.conf) in which I've double checked and confirmed that the items removed are not included. I think we may need engineer help confirm whether these items are still required in both broker.conf, and doc file? @Jennifer88huang would you please help forward this question? Thanks in advance!

**Comment by Jennifer88huang** [comment]
@jiazhai I've checked the removed items listed by @BGRichi, they are not in the [broker.conf](https://github.com/apache/pulsar/blob/branch-2.4/conf/broker.conf) file. If some removed parameters are still used in the current version, could you or some engineer help confirm, and update the `broker.conf` file first? Thank you.

**Comment by Jennifer88huang** [comment]
@tuteng could you help check removed parameters in the `broker.conf` file? Thank you.

**Comment by jiazhai** [comment]
@BGRichi @Jennifer88huang  Thanks for the work. `broker.conf` is not the source of truth, its content comes from `class ServiceConfiguration`, and regarding Offload, it comes from `class TieredStorageConfigurationData`. we should put all the needed configs from these 2 config class into broker.conf/standalone.conf

**Comment by Jennifer88huang** [comment]
@jiazhai Thanks for your clarification.
@BGRichi Could you please update the content accordingly? Thank you.

**Comment by BGRichi** [comment]
hi @jiazhai , I need your help. would you please pass me the links of `class ServiceConfiguration` and `class TieredStorageConfigurationData`, sorry that I didn't find them, thanks in advance!

**Comment by BGRichi** [comment]
thanks @Jennifer88huang , it's well noted.
hi @jiazhai , I need your help. would you please specify the files which includes `class ServiceConfiguration` and `class TieredStorageConfigurationData`? sorry that I didn't find them. thanks in advance!

**Comment by jiazhai** [comment]
Thanks @BGRichi .  Here is the link of the 2 class:
https://github.com/apache/pulsar/blob/master/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
https://github.com/apache/pulsar/blob/master/tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/TieredStorageConfigurationData.java

**Comment by Anonymitaet** [comment]
@BGRichi any updates for this PR?

**Comment by codelipenghui** [comment]
move to 2.7.0 first since no update on this PR.

**Comment by Jennifer88huang** [comment]
we've updated the file in another PR, so just close this one.
@BGRichi Thank you very much for your contributions~

**Pull request closed without merging**
