### PR TITLE
[improve][broker] Replace ScheduledExecutorService to ExecutorService in ModularLoadManagerImpl

### PR DESCRIPTION
**Pull request by AnonHxy**
### Motivation

An minor improvement by replacing `ScheduledExecutorService` to `ExecutorService` in ModularLoadManagerImpl

### Modifications

Replace ScheduledExecutorService to ExecutorService in ModularLoadManagerImpl

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Matching PR in forked repository
https://github.com/AnonHxy/pulsar/pull/30

### CODE REVIEW

**Review by coderzc — APPROVED** [review]

**Review by 315157973 — APPROVED** [review]

**Comment by heesung-sn** [comment]
@AnonHxy 

The PR is causing a test failure.

https://github.com/apache/pulsar/pull/17487#issuecomment-1454347491

**Comment by AnonHxy** [comment]
> @AnonHxy
> 
> The PR is causing a test failure.

Thanks for your reminder. Fix  it in this PR https://github.com/apache/pulsar/pull/19710 . PTAL

**Comment by lhotari** [comment]
Why was this cherry-picked to branch-2.11? The tests are broken in branch-2.11

```
  Error:  Tests run: 42, Failures: 1, Errors: 0, Skipped: 36, Time elapsed: 21.939 s <<< FAILURE! - in org.apache.pulsar.broker.namespace.NamespaceServiceTest
  Error:  testModularLoadManagerRemoveBundleAndLoad(org.apache.pulsar.broker.namespace.NamespaceServiceTest)  Time elapsed: 2.615 s  <<< FAILURE!
  org.powermock.reflect.exceptions.FieldNotFoundException: No instance field named "scheduler" could be found in the class hierarchy of org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl.
  	at org.powermock.reflect.internal.matcherstrategies.FieldNameMatcherStrategy.notFound(FieldNameMatcherStrategy.java:40)
  	at org.powermock.reflect.internal.WhiteboxImpl.findSingleFieldUsingStrategy(WhiteboxImpl.java:502)
  	at org.powermock.reflect.internal.WhiteboxImpl.findFieldInHierarchy(WhiteboxImpl.java:455)
  	at org.powermock.reflect.internal.WhiteboxImpl.findFieldInHierarchy(WhiteboxImpl.java:443)
  	at org.powermock.reflect.internal.WhiteboxImpl.getInternalState(WhiteboxImpl.java:427)
  	at org.powermock.reflect.Whitebox.getInternalState(Whitebox.java:292)
  	at org.apache.pulsar.broker.namespace.NamespaceServiceTest.waitResourceDataUpdateToZK(NamespaceServiceTest.java:830)
  	at org.apache.pulsar.broker.namespace.NamespaceServiceTest.testModularLoadManagerRemoveBundleAndLoad(NamespaceServiceTest.java:789)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by lhotari** [comment]
Nevermind, cherry-picking and backporting #19710 to fix the issue in branch-2.11.

**Pull request merged**
