### PR TITLE
Add doc set 2.7.4

### PR DESCRIPTION
**Pull request by Technoboy-**
### Motivation

As releasing 2.7.4, add related doc set.

### Modification
- Add 2.7.4 docs in `versioned_docs`
- Add sidebars in `versioned_sidebars`
- Update `release.json`
- Update `versions.json `

### Documentation
  
- [x] `no-need-doc`

### CODE REVIEW

**Review by Anonymitaet — APPROVED** [review]

**Comment by Anonymitaet** [comment]
Do not forget to update `versions.json` after 2.7.4 is announced, thanks

**Comment by Anonymitaet** [comment]
Example: https://github.com/apache/pulsar/pull/10666

**Comment by Technoboy-** [comment]
> Do not forget to update `versions.json` after 2.7.4 is announced, thanks

Updated

**Review by codelipenghui — APPROVED** [review]

**Review by Anonymitaet — APPROVED** [review]

**Pull request merged**
