### PR TITLE
Bug in Message Deduplication that may cause incorrect client/broker interaction

### LINKED ISSUE #5218: Enabling Deduplication may drop messages
**Describe the bug**
Since deduplication drops messages based on the the largest sequence id recorded pre-persist, if there’s an error persisting to BK, a retry attempt will just be “deduplicated” with no message ever getting persisted.
dedupe_fail_case

**To Reproduce**
1. Client connects successfully, producer send retry enabled (i.e. sendTimeoutMs at default of 30s)
2. Produce messages at something like 1msg/s and consume them, verifying messages were not lost.
3. Cause some BK failures by shut down of some nodes or a rolling restart
4. While that happens, Client reports `Received send error from server` (note it's send error, not just a normal connection error). One example of the several resulting errors are `PersistenceError : org.apache.bookkeeper.mledger.ManagedLedgerException: Waiting for new ledger creation to complete`
5. Looking at broker logs, will see `Message has been dropped for non-persistent topic producer-id ...` even though the first attempt was unsuccessful
6. Message was lost due to dedupe logic counting 2nd retry attempt as duplicate.

**Expected behavior**
Messages should not be dropped

**Desktop (please complete the following information):**
 - OS: OSX, AWS Linux

**Additional context**
Instructions for dedupe at this link, but the same problem can occur with those settings. Also, does setting sendTimeoutMs to 0 make it try forever, or does it drop the message on first fail? https://pulsar.apache.org/docs/en/cookbooks-deduplication/#message-deduplication-and-pulsar-clients-clients
Logic for dedupe in `MessageDeduplication.java`

### PR DESCRIPTION
**Pull request by jerrypeng**
### Motivation

Partially fixes #5218 

Will be making subsequent PRs to fix issues with handling BK write failures

### Modifications

The fix is two-fold:

Double check the pending messages and return error to producer when the dup status is uncertain (eg. message is still pending)
Sync back the lastPushed map with the lastStored map after the failures

### CODE REVIEW

**Comment by jerrypeng** [comment]
rerun java8 tests
rerun integration tests

**Comment by aahmed-se** [comment]
run integration tests

**Comment by jerrypeng** [comment]
rerun integration tests

**Comment by jerrypeng** [comment]
rerun integration tests

**Comment by jerrypeng** [comment]
rerun integration tests

**Comment by jerrypeng** [comment]
rerun integration tests

**Comment by jiazhai** [comment]
run integration tests

**Comment by jerrypeng** [comment]
run integration tests

**Pull request merged**
