### PR TITLE
[fix][fn] Configure pulsar admin for TLS

### PR DESCRIPTION
**Pull request by michaeljmarshall**
### Motivation

This PR is a combination of https://github.com/apache/pulsar/pull/20482 and https://github.com/apache/pulsar/pull/20513 because cherry picking those PRs produced too many conflicts.

### Modifications

* Made the same addition as the source PRs, though the code has changed a bit, so I had to make a few extra changes.
### Documentation

- [x] `doc-not-needed`

### CODE REVIEW

**Review by lhotari — APPROVED** [review]
LGTM

**Comment by michaeljmarshall** [comment]
The test failures are unrelated, merging anyway.

**Comment by michaeljmarshall** [comment]
As discussed on the mailing list https://lists.apache.org/thread/w4jzk27qhtosgsz7l9bmhf1t7o9mxjhp, there is no plan to release 2.9.6, so I am going to remove the release/2.9.6 label

**Pull request merged**
