### PR TITLE
[website] Fix the problem that tab click on the page did not response.

### PR DESCRIPTION
**Pull request by tuteng**
Fixes https://github.com/apache/pulsar/issues/4990

Master Issue: https://github.com/apache/pulsar/issues/4990

### Motivation
[pjax-api](https://github.com/falsandtru/pjax-api) conflicts with [scrollSpy](https://github.com/facebook/docusaurus/blob/e486d3d1b0e0a397f242368357fbedbe767104c7/packages/docusaurus-1.x/lib/static/js/scrollSpy.js). Cause that cache headingsCache used by variable findHeadings to not be update correctly.

Modifications
* Delete file pjax-api.min.js

### Verifying this change

Run ok locally

### CODE REVIEW

**Comment by tuteng** [comment]
run Java8 tests
run Integration tests

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by tuteng** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Pull request merged**
