### PR TITLE
Increase the retries count for PulsarFunctionStateTest

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

The test has been intermittently failing: 

```
2019-10-07\T\20:09:37.235 [ERROR] testPulsarFunctionState(org.apache.pulsar.functions.worker.PulsarFunctionStateTest)  Time elapsed: 2.607 s  <<< FAILURE!
java.lang.AssertionError: expected [1] but found [0]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:652)
	at org.testng.Assert.assertEquals(Assert.java:662)
	at org.apache.pulsar.functions.worker.PulsarFunctionStateTest.testPulsarFunctionState(PulsarFunctionStateTest.java:316)
```

Increasing the number of retries, since this seems related to slowness in Jenkins.

### CODE REVIEW

**Comment by jerrypeng** [comment]
rerun integration tests
rerun java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Pull request merged**
