### PR TITLE
[improve][test] Remove WhiteBox for ElasticSearchSinkTests 

### PR DESCRIPTION
**Pull request by tisonkun**
Master Issue: #16912 

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [x] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by nicoloboschi — APPROVED** [review]
👌

**Review by Shoothzj — APPROVED** [review]

**Comment by tisonkun** [comment]
```
Error response from daemon: write /var/lib/docker/tmp/docker-export-3539721826/b4b6ffd2e938fa5512aa646b2c22044e3e0b14e74d3dc8374a9b3723a7235c53/layer.tar: no space left on device
```

https://github.com/apache/pulsar/runs/8293519653?check_suite_focus=true Do we run out of our GitHub Actions Artifacts quota?

Rerunning...

**Comment by lhotari** [comment]
@tisonkun I filed a bug #17583 about the workflow.

**Review by Demogorgon314 — APPROVED** [review]

**Comment by tisonkun** [comment]
cc @Shoothzj @lhotari @Demogorgon314 @nicoloboschi all tests passed now. Could you help with merging this patch?

**Comment by Technoboy-** [comment]
Cherry-picked to branch-2.11, as #18577 relies on this.

**Pull request merged**
