### PR TITLE
[Issue 5425][docs-website] Add coding guide for Apache Pulsar contributing guide

### LINKED ISSUE #5425: website page `coding_guide` return 404
As @Retardust reported on slack, when you click the link to "coding guide" at  http://pulsar.apache.org/en/contributing/#code, it returns `404`. 
Actually, the link to http://pulsar.apache.org/en/coding_guide does not work.

### PR DESCRIPTION
**Pull request by Jennifer88huang**
Fixes #5425 

### Motivation
The link navigates to coding guide does not work in Contributing guide.

### Modifications
1. Add coding guide.
2. Add coding-guide.js file to the  `/pages/en` folder. (TBD)

### CODE REVIEW

**Comment by Jennifer88huang** [comment]
@tuteng could you please help add coding-guide.js file to the /pages/en folder? Thank you.

**Comment by Jennifer88huang** [comment]
Things to be confirmed:

- In Configuration section: if users want to add docs related to configuration setting, where shall they document?
- In Concurrency section: what's the preferred methods for executing any asynchronous actions?
Shall we add other compatibility types?
- Is this a typo?
image

**Comment by Jennifer88huang** [comment]
Updated things to be confirmed.
If there is no other issue, we can merge this PR. And then @tuteng will add coding-guide.js file to the /pages/en folder.

**Comment by sijie** [comment]
run cpp tests

**Pull request merged**
