### PR TITLE
[Documentation] Improve transaction-api.md

### PR DESCRIPTION
**Pull request by truongninh**
Added note to enable transaction support in standalone mode.

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]

**Review by Anonymitaet — APPROVED** [review]

**Comment by Anonymitaet** [comment]
Hi @truongninh can you re-run the tests? After the tests pass successfully, we can merge this PR.

**Comment by Anonymitaet** [comment]
Close this PR since transaction doc has been udpated.

**Pull request closed without merging**
