### PR TITLE
Update bookkeeper ver to 4.9.1

### PR DESCRIPTION
**Pull request by aahmed-se**
This updates the bookkeeper library version to 4.9.1

### CODE REVIEW

**Comment by sijie** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by merlimat** [comment]
@aahmed-se need to update LICENSE file

**Comment by aahmed-se** [comment]
updated license files

**Comment by aahmed-se** [comment]
lgtm

**Pull request merged**
