### PR TITLE
Re-enable running Python tests in CI PR validation

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

In #3386 an `exit 0` statement was introduced in `run-unit-tests.sh` which will make the CI job to actually skip the Python unit tests and tearing down the cluster.

### CODE REVIEW

**Comment by merlimat** [comment]
retest this please

**Comment by sijie** [comment]
run integration tests
run cpp tests

**Comment by merlimat** [comment]
run cpp tests

**Comment by merlimat** [comment]
run java8 tests

**Pull request merged**
