### PR TITLE
[Hotfix]Drop unused import for pulsar-broker

### PR DESCRIPTION
**Pull request by Renkai**
Signed-off-by: Renkai <gaelookair@gmail.com>

Depress warnings from IDE, keep code-base clean, no other side-effects.

### CODE REVIEW

**Review by eolivelli — COMMENTED** [review]
Thank you for the initiative.
Don't we have a checkstyle rule?
If not, would you like to try to add it?
Otherwise this precious work may be undone easily if it is not enforced automatically

**Comment by hangc0276** [comment]
@Renkai Thanks for your fix. I agree with @eolivelli, maybe you'd better add the code style check rule to force automatically.

**Comment by Renkai** [comment]
> Thank you for the initiative.
> Don't we have a checkstyle rule?
> If not, would you like to try to add it?
> Otherwise this precious work may be undone easily if it is not enforced automatically

Thanks, do you have a guide about how to add a checkstyle rule? I'd like to do it.

**Comment by Renkai** [comment]
Hi, @eolivelli @hangc0276 , I added a file `buildtools/src/main/resources/pulsar/checkstyle-pulsar-broker.xml` for style check. I hope it will be finally with `buildtools/src/main/resources/pulsar/checkstyle.xml`, but make them same in one pull request will change too many lines, so I only checked unused imports in this pull request.

**Review by eolivelli — COMMENTED** [review]
so basically we didn't have checkstyle on the main module ?

Then I am +1 in the current approach.
I recently tried to upgrade checkstyle to latest version and I though that pulasr-broker was affected

**Comment by Renkai** [comment]
> so basically we didn't have checkstyle on the main module ?
> 
> Then I am +1 in the current approach.
> I recently tried to upgrade checkstyle to latest version and I though that pulasr-broker was affected

We have a checkstyle on the main module, but some sub-module inherit from it, some not.

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
