### PR TITLE
[fix][ci] Fix pulsar shell bin file name

### PR DESCRIPTION
**Pull request by yaalsn**
### Motivation

The shell distribution files' name are like `apache-pulsar-shell-$VERSION-shell-bin.tar.gz` and `apache-pulsar-shell-$VERSION-shell-bin.zip` which are incorrect in `stage-release.sh`.

image

### Modifications

Add suffix `-bin`

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/yaalsn/pulsar/pull/17

### CODE REVIEW

**Review by nicoloboschi — COMMENTED** [review]
In the current master the names are:
- apache-pulsar-shell-2.12.0-SNAPSHOT-bin.tar.gz
- apache-pulsar-shell-2.12.0-SNAPSHOT-bin.zip

maybe this is only related to branch-2.11 ?

**Comment by yaalsn** [comment]
> In the current master the names are:
> 
> * apache-pulsar-shell-2.12.0-SNAPSHOT-bin.tar.gz
> * apache-pulsar-shell-2.12.0-SNAPSHOT-bin.zip
> 
> maybe this is only related to branch-2.11 ?

For master and branch-2.11, both have `-bin` suffix, so this PR needs to cherry-pick to branch-2.11.

**Comment by yaalsn** [comment]
image

**Comment by Technoboy-** [comment]
> > In the current master the names are:
> > 
> > * apache-pulsar-shell-2.12.0-SNAPSHOT-bin.tar.gz
> > * apache-pulsar-shell-2.12.0-SNAPSHOT-bin.zip
> > 
> > maybe this is only related to branch-2.11 ?
> 
> For master and branch-2.11, both have `-bin` suffix, so this PR needs to cherry-pick to branch-2.11.

I have fixed this on branch-2.11 when releasing 2.11

**Review by nicoloboschi — APPROVED** [review]

**Pull request merged**
