### PR TITLE
Message dispatch rate policies support cross multiple clusters.

### PR DESCRIPTION
**Pull request by mattisonchao**
Master Issue: #13444

### Motivation
Message dispatch rate policies support cross multiple clusters.

### Documentation
- [x] no-need-doc

### CODE REVIEW

**Comment by mattisonchao** [comment]
@315157973 @codelipenghui PTAL

**Comment by mattisonchao** [comment]
@Anonymitaet   

Sorry, it's my fault to missing doc information.
Could i have a way to remove this tag?

**Comment by Anonymitaet** [comment]
@mattisonchao You delete the backticks (``) so that Bot can not recognize the info and then labels the PR with `doc-info-missing`.
[x] `doc-required`  ✅
[x] doc-required ❌
Details: https://docs.google.com/document/d/1Qw7LHQdXWBW9t2-r-A7QdFDBwmZh6ytB4guwMoXHqc0/edit

I've labelled this PR with `no-need-doc`

**Review by 315157973 — APPROVED** [review]

**Pull request merged**
