### PR TITLE
[branch-2.10] Group prometheus metrics

### PR DESCRIPTION
**Pull request by marksilcox**
### Motivation

Cherry picked from https://github.com/apache/pulsar/pull/15558 with reference to fixes in https://github.com/apache/pulsar/pull/17852

- [X] Make sure that the change passes the CI checks.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [X] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/marksilcox/pulsar/pull/7

### CODE REVIEW

**Comment by codelipenghui** [comment]
@tjiuming @asafm Could you please help review the PR again?

**Review by tjiuming — APPROVED** [review]
LGTM

**Review by asafm — APPROVED** [review]
Very hard to do a meticulous review for this PR. I quickly reviewed it and mainly relied on the PR we did on the original one. Also validated the buffer release bug is not here.

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
