### PR TITLE
Remove corrupt visible testing annotation in function workers

### PR DESCRIPTION
**Pull request by Shoothzj**
### Motivation
Remove corrupt visible testing annotation in function workers, make code reader confusing

### Modifications
- Remove corrupt visible testing annotation
- fix a typo
- rename a unused method since 2017

### Documentation
Check the box below and label this PR (if you have committer privilege).
Need to update docs?  
- [x] `no-need-doc` 
  simple internal changes

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
Lgtm

What do you mean with 'corrupt'? Do you mean 'wrong ' ?

**Comment by Shoothzj** [comment]
> Lgtm
> 
> What do you mean with 'corrupt'? Do you mean 'wrong ' ?

I mean, After a long time, the method annotated `VisibleTesting` has already been used by src code

**Comment by Shoothzj** [comment]
> Lgtm
> 
> What do you mean with 'corrupt'? Do you mean 'wrong ' ?

I mean, After a long time, the method annotated `VisibleTesting` has already been used by src code

**Review by hangc0276 — APPROVED** [review]

**Pull request merged**
