### PR TITLE
[cleanup] [broker] Remove ledger instance from map by requested id when initialization fails

### PR DESCRIPTION
**Pull request by horizonzy**
### Motivation
code clean.

### Documentation
  
- [x] `no-need-doc`

### CODE REVIEW

**Review by RobertIndie — APPROVED** [review]

**Comment by RobertIndie** [comment]
Please change your PR title according to the convention:

>  PR title format should be *[type][component] summary*. For details, see *[Guideline - Pulsar PR Naming Convention](https://docs.google.com/document/d/1d8Pw6ZbWk-_pCKdOmdvx9rnhPiyuxwq60_TrD68d7BA/edit#heading=h.trs9rsex3xom)*.

**Comment by horizonzy** [comment]
> Please change your PR title according to the convention:
> 
done

**Review by lhotari — APPROVED** [review]

**Review by Technoboy- — APPROVED** [review]

**Comment by lhotari** [comment]
I renamed the title since "Reuse id to take place of ledgers.lastKey()" was hard to understand

**Comment by lhotari** [comment]
Good catch @horizonzy

**Review by Demogorgon314 — APPROVED** [review]

**Review by HQebupt — APPROVED** [review]

**Pull request merged**
