### PR TITLE
Revert "[Fix][Tiered Storage] Eagerly Delete Offloaded Segments On Topic Deletion (#15914)"

### PR DESCRIPTION
**Pull request by eolivelli**
This reverts commit 9026d1954d180cfb4b3a38f52217b14a3b5e3dc0.

PR is #15914

### CODE REVIEW

**Comment by mattisonchao** [comment]
Hi @eolivelli 

Could you tell us why we have to revert it?

**Comment by eolivelli** [comment]
@cbornet may add more details.
A few tests on master branch are now failing

**Review by lhotari — APPROVED** [review]

**Comment by cbornet** [comment]
Master fails consistently on several tests:
[testGetAllPartitions(org.apache.pulsar.broker.namespace.NamespaceOwnershipListenerTests)](https://github.com/cbornet/pulsar/actions/runs/3150096587/jobs/5122627965#step:10:864)
[producerBacklogQuotaExceededTest(org.apache.pulsar.websocket.proxy.ProxyPublishConsumeTest)](https://github.com/cbornet/pulsar/actions/runs/3150096587/jobs/5122627518#step:10:708)

I have the same failure locally on latest master.
Can someone else confirm ?

**Comment by eolivelli** [comment]
> mvn test -pl pulsar-broker -Dtest=NamespaceOwnershipListenerTests

```
Message: org.apache.bookkeeper.mledger.ManagedLedgerException$ManagedLedgerFencedException: Can't trim fenced ledger

Stacktrace:

org.apache.pulsar.broker.service.BrokerServiceException$PersistenceException: org.apache.bookkeeper.mledger.ManagedLedgerException$ManagedLedgerFencedException: Can't trim fenced ledger
	at org.apache.pulsar.broker.service.persistent.PersistentTopic$6.deleteLedgerFailed(PersistentTopic.java:1248)
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.lambda$asyncDelete$34(ManagedLedgerImpl.java:2737)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.asyncDelete(ManagedLedgerImpl.java:2734)
	at org.apache.pulsar.broker.service.persistent.PersistentTopic.lambda$delete$33(PersistentTopic.java:1220)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)

```

**Review by nicoloboschi — APPROVED** [review]

**Comment by eolivelli** [comment]
tests are now failing due to https://github.com/apache/pulsar/pull/17736

because "trim" cannot happen if a ManagedLedger is "fenced", and we set "fenced" in "delete".
so there is some code path in which we "delete" and then try to "trim".
we should do the opposite...trim and then delete.

**Review by coderzc — APPROVED** [review]

**Pull request merged**
