### PR TITLE
[fix] [admin] [branch-2.9] fix reach max tenants error if the tenant already exists

### PR DESCRIPTION
**Pull request by poorbarcode**
### Motivation

see #15932

At branch `master` REST API async change, there are many conflicts when cherry-picking #15932 PR, so I  create separate PR to fix branch-2.9

### Modifications

- Swap the execution order of duplicate validation and maximum validation
- Fixed incorrect logs 

### Documentation

- [ ] `doc-required` 
  
- [x] `doc-not-needed` 
  
- [ ] `doc` 

- [ ] `doc-complete`

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Review by mattisonchao — APPROVED** [review]

**Comment by codelipenghui** [comment]
@mattisonchao Need this PR to fix the test https://github.com/apache/pulsar/pull/16010

**Pull request merged**
