### PR TITLE
Use randomized names for kafka container in integration tests

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation 

There are several runs of integration tests that are failing with conflict on kafka container with same name. That can happen if multiple integration jobs are running on the same node.

### Changes

Use randomized name for test container.

### CODE REVIEW

**Comment by merlimat** [comment]
run cpp tests
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
run cpp tests

**Pull request merged**
