### PR TITLE
make maxEnsembleChangeSize can be config from pulsar broker

### PR DESCRIPTION
**Pull request by baomingyu**
Master Issue: #11367

make maxEnsembleChangeSize can be config from pulsar broker

### CODE REVIEW

**Review by Technoboy- — CHANGES_REQUESTED** [review]
There seems this param not works, did you miss some commits or classes?

**Comment by Anonymitaet** [comment]
Thanks for your contribution. For this PR, do we need to update docs?

(The [PR template contains info about doc](https://github.com/apache/pulsar/blob/master/.github/PULL_REQUEST_TEMPLATE.md#documentation), which helps others know more about the changes. Can you provide doc-related info in this and future PR descriptions? Thanks)

**Review by tomscut — COMMENTED** [review]
Could you add a unit test for it?

**Comment by Anonymitaet** [comment]
@baomingyu any feedback?

**Comment by codelipenghui** [comment]
The pr had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale and conflict. Please rebase and resubmit the patch if it's still relevant.

**Pull request closed without merging**
