### PR TITLE
Remove jetty-alpn-java-client-9.4.27.v20200227.jar from the LICENSE of the presto-distribution

### PR DESCRIPTION
**Pull request by codelipenghui**

### CODE REVIEW

**Review by sijie — APPROVED** [review]

**Comment by sijie** [comment]
@codelipenghui any ideas?

```
jetty-alpn-java-client-9.4.27.v20200227.jar unaccounted for in lib/presto/LICENSE

It looks like there are issues with the LICENSE/NOTICE.
```

**Comment by merlimat** [comment]
I think it's probably related to differences in the maven version that resolve a slightly different set of dependencies.

**Comment by lhotari** [comment]
Building with JDK 11 vs. JDK 8 makes a difference.

**Comment by eolivelli** [comment]
Yes, dependency management differs from Maven version to Maven version.

We should also probably upgrade to latest maven 3.8.1.

**Pull request closed without merging**
