### PR TITLE
PulsarAdmin: Fix last exit code storage

### PR DESCRIPTION
**Pull request by thomasleplus**
This line was actually assigning the method argument to itself instead of setting the static field of the same name.

### Motivation

Fix a simple mistake.

### Modifications

Trivial change.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no
  - The rest endpoints: no
  - The admin cli options: no
  - Anything that affects deployment: no

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 

- [ ] doc-required 
- [x] no-need-doc 
- [ ] doc

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Comment by thomasleplus** [comment]
I am investigating the failing test.

**Review by eolivelli — APPROVED** [review]

**Comment by eolivelli** [comment]
It is a flaky test. Don't bother


Thank you

**Comment by thomasleplus** [comment]
Hi @codelipenghui, I see that you assigned this PR back to me, does this mean there is something left for me to do?

**Comment by eolivelli** [comment]
it means that you are the author of the PR, nothing more.
this way it is easier to "count" your contributions, and finally someday invite you as a committer :-)

**Review by 315157973 — APPROVED** [review]

**Comment by 315157973** [comment]
@thomasleplus Sorry， I closed this PR by mistake, could you please open  it again?

**Comment by thomasleplus** [comment]
> @thomasleplus Sorry， I closed this PR by mistake, could you please open  it again?

GitHub doesn't let me because I've deleted my fork repo. My bad. Maybe their support team can reopen the request, they are pretty good and reactive in my experience. Otherwise I can create another PR. Let me know what you think is best.

**Comment by 315157973** [comment]
> > @thomasleplus Sorry， I closed this PR by mistake, could you please open  it again?
> 
> GitHub doesn't let me because I've deleted my fork repo. My bad. Maybe their support team can reopen the request, they are pretty good and reactive in my experience. Otherwise I can create another PR. Let me know what you think is best.

Let's create a new PR, I want to merge it as soon as possible, 2.8.2 is releasing

**Comment by thomasleplus** [comment]
Sure, here you go: #12581

**Pull request closed without merging**
