### PR TITLE
Clean up duplicate section in doc

### PR DESCRIPTION
**Pull request by liketic**
There are two sections name ```Java``` of List namespaces API. Remove one of them.

See http://pulsar.apache.org/docs/en/admin-api-namespaces/

### CODE REVIEW

**Comment by sijie** [comment]
run integration tests
run java8 tests

**Comment by sijie** [comment]
run integration tests

**Comment by liketic** [comment]
run integration tests
run java8 tests

**Comment by liketic** [comment]
run java8 tests

**Comment by liketic** [comment]
run java8 tests

**Pull request merged**
