### PR TITLE
[Issue 5287][docs] Add documentation on how to configure multiple broker services

### LINKED ISSUE #5287: presto connector - how to specify cluster (multi broker/zk) connection
**Describe the bug**
Trying to connect existing presto (not part of pulsar distro) to pulsar (multi host cluster)

**To Reproduce**

catalog/pulsar.properties in presto has

```
connector.name=pulsar
# the url of Pulsar broker service
pulsar.broker-service-url=http://yy:8080;xx:8080
# URI of Zookeeper cluster
pulsar.zookeeper-uri=yy,xx:2181
# minimum number of entries to read at a single time
#pulsar.entry-read-batch-size=100
# default number of splits to use per query
pulsar.target-num-splits=4
```

major (1st issue)
```
presto> select * from pulsar."public/functions".assignments;
Query 20190927_164934_00002_q7acj failed: Failed to get topics in schema public/functions: For input string: "8080;xx:8080"
```

There is no documentation about how to provide multi hosts for brokers or zk

minor (2nd issue)
`pulsar.entry-read-batch-size=100 --> this config causes error`

**Expected behavior**
presto can connect to pulsar/zk cluster (multi hosts)

env: using presto .220 and pulsar 2.41

### PR DESCRIPTION
**Pull request by Jennifer88huang**
Fixes #5287 

### Motivation
Users do not know how to specify cluster (multi broker/zk) connection for presto.

### Modifications
Add content on how to configure multiple hosts for `pulsar.broker-service-url`.

### CODE REVIEW

**Comment by Jennifer88huang** [comment]
@tooptoop4 @zymap could you please help to review? Thank you.

**Comment by sijie** [comment]
run cpp tests
run java8 tests

**Comment by tooptoop4** [comment]
try to run presto query with 3 hosts it does not work

**Comment by zymap** [comment]
@tooptoop4 Can you give me more info about why it does not work? like error logs and your configuration?

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
@tooptoop4 any comments about "try to run presto query with 3 hosts it does not work"?

**Comment by tooptoop4** [comment]
did u try it @sijie

**Comment by sijie** [comment]
@tooptoop4 yes. Can you comment about your setup, configuration and the exception you are seeing? Happy to troubleshoot your problem.

**Pull request merged**
