### PR TITLE
Add default ackTimeout(30s) for dead letter policy

### PR DESCRIPTION
**Pull request by codelipenghui**
Fix issue #2987 
### Motivation

In version 2.2.0, support DeadLetterTopic feature. This feature based on message redelivery. So ack timeout is necessary.

### Modifications

Set ackTimeout(30s) when enable the dead letter policy but not set the ackTimeout;

### CODE REVIEW

**Comment by sijie** [comment]
run cpp tests

**Comment by merlimat** [comment]
@sijie @codelipenghui I think we should consider change it back to no ack-timeout and instead encourage using negativeAck. 

If an application has a processing logic that can (even occasionally) take >30s, this default setting will degrade very badly.

**Comment by codelipenghui** [comment]
@merlimat Thanks for reminding, i'm writing the documentation for dead letter topic, this will be a nice practice to encouraging using negativeAck while using dead letter topic.

But I am worried about change this default now, because user properly already use dead letter topic for some scenes like delay message delivery, this change is likely to be abnormal when they upgrade the client version.

So, I tend to encourage using negativeAck by the documentation.

**Comment by sijie** [comment]
@merlimat I think the 30s is only applied when dead-letter policy is enabled and no ack timeout is specified. so if an application needs to use dead-letter topic, it is expecting some kind of timeout mechanisms, no? 

I don't think we should change the default. but I agree that we should encourage using negativeAck in the documentation.

**Pull request merged**
