### PR TITLE
[pulsar-sql]Expose configurations of managed ledger and bookkeeper client.

### PR DESCRIPTION
**Pull request by gaoran10**
### Motivation

Expose more configurations of managed ledger and bookkeeper client, this will provide ability for users to optimize performance of entries reading.

### Modifications

Expose some configurations related to managed ledger and bookkeeper client in pulsar.config.

### Verifying this change

Add unit tests to verify the default value of the configurations.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (yes)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by codelipenghui** [comment]
run cpp tests
run integration tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests
run integration tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run cpp tests
run integration tests

**Comment by codelipenghui** [comment]
run integration tests

**Comment by jiazhai** [comment]
run integration tests

**Comment by gaoran10** [comment]
run integration tests

**Comment by gaoran10** [comment]
run integration tests

**Comment by gaoran10** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by gaoran10** [comment]
run integration tests

**Comment by codelipenghui** [comment]
run integration tests

**Comment by gaoran10** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by sijie** [comment]
run cpp tests

**Comment by sijie** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by codelipenghui** [comment]
This PR need to fix the integration tests, i have checked with gaoran, there are problems when we disable entry cache and using pulsar sql to retrieve data while using publish_time to trim entries, gaoran will fix it soon

**Comment by jiazhai** [comment]
Hi @gaoran10, as @codelipenghui  suggested, Would you please take a look? Thanks.

**Comment by gaoran10** [comment]
run cpp tests
run java8 tests
run integration tests

**Comment by gaoran10** [comment]
Hi @jiazhai, ok, I will fix it, Thanks.

**Comment by gaoran10** [comment]
run cpp tests

**Comment by gaoran10** [comment]
run cpp tests

**Comment by gaoran10** [comment]
run cpp tests

**Comment by gaoran10** [comment]
run integration tests

**Comment by gaoran10** [comment]
run java8 tests

**Comment by gaoran10** [comment]
run integration tests

**Comment by gaoran10** [comment]
run java8 tests

**Comment by gaoran10** [comment]
run integration tests

**Comment by gaoran10** [comment]
run java8 tests

**Comment by gaoran10** [comment]
run integration tests

**Comment by codelipenghui** [comment]
@jia @sijie please take a look this PR, ran has fix the test issues

**Comment by jiazhai** [comment]
@codelipenghui @gaoran10 Seems currently the github action is required. we may need to fix them, if it is related.
image

```
[ERROR] COMPILATION ERROR : 
[ERROR] /home/runner/work/pulsar/pulsar/pulsar-flink/src/test/java/org/apache/flink/batch/connectors/pulsar/PulsarJsonOutputFormatTest.java:[36,9] no suitable constructor found for PulsarJsonOutputFormat(<nulltype>,java.lang.String,org.apache.pulsar.client.impl.auth.AuthenticationDisabled)
    constructor org.apache.flink.batch.connectors.pulsar.PulsarJsonOutputFormat.PulsarJsonOutputFormat(java.lang.String,java.lang.String) is not applicable
      (actual and formal argument lists differ in length)
    constructor org.apache.flink.batch.connectors.pulsar.PulsarJsonOutputFormat.PulsarJsonOutputFormat(org.apache.pulsar.client.impl.conf.ClientConfigurationData,org.apache.pulsar.client.impl.conf.ProducerConfigurationData) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /home/runner/work/pulsar/pulsar/pulsar-flink/src/test/java/org/apache/flink/batch/connectors/pulsar/PulsarJsonOutputFormatTest.java:[41,9] no suitable constructor found for PulsarJsonOutputFormat(java.lang.String,<nulltype>,org.apache.pulsar.client.impl.auth.AuthenticationDisabled)
    constructor 
```

**Comment by jiazhai** [comment]
I have re-triggered the github action. and @aahmed-se is help on the github action.

**Comment by jiazhai** [comment]
the failure of `CI - Misc / License check (pull_request) ` seems un-related.

**Pull request merged**
