### PR TITLE
Update release notes for v2.3.2 release

### PR DESCRIPTION
**Pull request by jerrypeng**

### CODE REVIEW

**Comment by codelipenghui** [comment]
run Java8 Tests

**Comment by jiazhai** [comment]
run Java8 Tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun java8 test

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun java8 tests

**Pull request merged**
