### PR TITLE
Update schema-get-started.md

### PR DESCRIPTION
**Pull request by boncheff**
Fix typo and make sentence more grammatically correct.

### Modifications

Update schema-get-started.md

### CODE REVIEW

**Comment by merlimat** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by boncheff** [comment]
can you advise me how to run the java8 tests or should this be automatic?

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Pull request closed without merging**
