### PR TITLE
Fix poms in package-management - set 2.8.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by eolivelli**
Fix a few poms related to patches committed during the switch to 2.8.0

### CODE REVIEW

**Comment by eolivelli** [comment]
@codelipenghui @sijie @jiazhai PTAL, master is currently broken

**Comment by codelipenghui** [comment]
@eolivelli there is already a fix https://github.com/apache/pulsar/pull/8695

**Comment by eolivelli** [comment]
thank you @codelipenghui I missed it

**Comment by codelipenghui** [comment]
Thanks @eolivelli I will close this PR first since #8695 merged.

**Pull request closed without merging**
