### PR TITLE
[enh][monitor]: add metrics for pulsar web service thread pool

### PR DESCRIPTION
**Pull request by tjiuming**
Fixes https://github.com/apache/pulsar/issues/14459

### Motivation

See the issue

### Modifications
1. Add WebExecutorStats to record web thread pool metrics

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [x] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [ ] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Comment by tjiuming** [comment]
this pr add following metrics:
|name|type|description|
|--|--|--|
|pulsar_web_executor_max_threads|GAUGE|The max threads of pulsar-web  thread pool|
|pulsar_web_executor_min_threads|GAUGE|The max threads of pulsar-web thread pool|
|pulsar_web_executor_idle_threads|GAUGE|The idle threads of pulsar-web thread pool|
|pulsar_web_executor_active_threads|GAUGE|The active-threads(doing task) of pulsar-web thread pool|
|pulsar_web_executor_current_threads|GAUGE|How many threads in the pulsar-web thread pool now|

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@tjiuming Thanks for the great contribution, this PR will bring more transparency to the web service thread pool. Please help open another PR to add the documentation.

**Review by gaoran10 — APPROVED** [review]
LGTM

**Comment by frankjkelly** [comment]
Bump - I'm excited for this - any chance the conflicts can get resolved?

**Comment by tjiuming** [comment]
> Bump - I'm excited for this - any chance the conflicts can get resolved?

Resolved

**Pull request merged**
