### PR TITLE
[fix][client-c++][branch-2.9] Close messages_ when PartitionedConsumer is closed

### PR DESCRIPTION
**Pull request by coderzc**
### Motivation

Cherry pick the #16887 and #15726

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Comment by mattisonchao** [comment]
Please check the failed test. thanks!

**Comment by coderzc** [comment]
> Please check the failed test. thanks!

Also need to cherry-pick #15726, I deal with it.

**Review by BewareMyPower — CHANGES_REQUESTED** [review]
Please don't merge this PR. This PR is a bug fix for https://github.com/apache/pulsar/pull/15726 that introduced a new `Result` enum. It's an API change so that we should not cherry-pick both of them to release branches.

**Pull request closed without merging**
