### PR TITLE
Fixed issue with Authorization header missing after client gets redirected

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Jersey client uses by default the standard `HttpUrlConnection` from JDK. One issues that has been found is that, in newer JDK 8 versions (eg: 1.8.0_181), the `Authorization` header is not being included in the HTTP request after a redirect. The request than will fail with auth error.

This is a problem for Token based authentication where we're using that header. 

The authorization after redirection used to work at least until JDK 1.8.0_121 and there seems to be no way to configure the same behavior.

### Modifications

Use Jersey JDK provider (based on Java NIO) instead of `HttpUrlConnectionProvider`. This is currently working correctly.

Avoided for now the Netty provider since it's not supporting following the redirections.

### CODE REVIEW

**Comment by KannarFr** [comment]
Hi, many thanks for this :)!

**Comment by merlimat** [comment]
Still there's a problem here. The Jersey JdkConnector only follows 307 redirect for GET requests..

**Comment by merlimat** [comment]
retest this please

**Comment by merlimat** [comment]
Fixed the JdkConnector issue by plugging directly the same AsyncHttpClient lib that we're already using in Pulsar client.

**Comment by merlimat** [comment]
rerun tests please

**Comment by merlimat** [comment]
retest this please

**Comment by sijie** [comment]
run integration tests
run java8 tests

**Comment by merlimat** [comment]
I'm fixing one last issue in this change regarding the hostname verification that gets enabled by default. That's why the tests are currently failing with TLS enabled

**Comment by KannarFr** [comment]
Nice!

**Comment by merlimat** [comment]
run integration tests

**Comment by merlimat** [comment]
run integration tests

**Comment by KannarFr** [comment]
run integration tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
run integration tests 
run java8 tests

**Comment by merlimat** [comment]
run java8 tests

**Comment by merlimat** [comment]
Merged in 2.3.1 at 
a15b6f0

**Pull request merged**
