### PR TITLE
[docs] [ISSUE 12366] Add doc of bundles metrics

### PR DESCRIPTION
**Pull request by gaozhangmin**
### Motivation

Add bundles metrics doc

### Modifications

Add bundles metrics doc

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no) no
  - The public API: (yes / no)  no
  - The schema: (yes / no / don't know)  no
  - The default values of configurations: (yes / no)  no
  - The wire protocol: (yes / no)  no
  - The rest endpoints: (yes / no)  no 
  - The admin cli options: (yes / no)  no 
  - Anything that affects deployment: (yes / no / don't know)  no

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [ ] `no-need-doc` 
  
  (Please explain why)
  
- [x] `doc` 
  site2/docs/reference-metrics.md

### CODE REVIEW

**Comment by gaozhangmin** [comment]
@Anonymitaet  PTAL

**Review by Anonymitaet — APPROVED** [review]
Approve from the tech writing perspective

**Comment by Anonymitaet** [comment]
@gaoran10 can you review this PR from the technical perspective? Thank!

**Review by gaoran10 — APPROVED** [review]

**Comment by Anonymitaet** [comment]
@gaozhangmin are the doc changes suitable for other doc versions? If so, can you update them? thanks

**Comment by gaozhangmin** [comment]
> @gaozhangmin are the doc changes suitable for other doc versions? If so, can you update them? thanks

Only master branch

**Pull request merged**
