### PR TITLE
[fix][sec]disable trace in web service

### LINKED ISSUE #18091: [Bug] Disable HTTP TRACE Method in webservice
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

master

### Minimal reproduce step

Pulsar uses embedded jetty which allows TRACE method by default. This is a widely-known security concern. Please disable HTTP TRACE method.

### What did you expect to see?

https://issues.apache.org/jira/browse/ZOOKEEPER-3731

### What did you see instead?

https://issues.apache.org/jira/browse/ZOOKEEPER-3731

### Anything else?

https://github.com/apache/zookeeper/commit/44de549657a539dcedba58d56e67b8c906c89580

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by leizhiyuan**
Fixes #18091

Master Issue: #18091

### Motivation

close TRACE 

refactor DisableDebugHttpMethodFilter ， use the ConstraintSecurityHandler to achieve this.

because we can not access proxyConfig and WorkerConfig in DisableDebugHttpMethodFilter , the proxy module and worker module depends on broker-common, if I use the interface, PulsarConfiguration ,I need to do some tricky thing.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by nodece — APPROVED** [review]

**Review by Shoothzj — APPROVED** [review]

**Review by nicoloboschi — APPROVED** [review]
Good catch, we have to cherry-pick it to release branches also

**Review by tisonkun — APPROVED** [review]
Nice catch!

**Comment by nicoloboschi** [comment]
@leizhiyuan the related test failed
```
WebServiceTest.testDisableHttpTraceAndTrackMethods

expected [405] but found [403]
```

And I think that we should add this to all the webservers in Pulsar (Proxy, Function Worker)

**Comment by leizhiyuan** [comment]
After I checked the testcase , I find it seems  disableHttpDebugMethods do the same thing. https://github.com/apache/pulsar/pull/7907

we can set disableHttpDebugMethods=true  to solve the issue?

and I can add the disableHttpDebugMethods to Proxy, Function Worker

**Comment by nicoloboschi** [comment]
> After I checked the testcase , I find it seems disableHttpDebugMethods do the same thing. #7907
> 
> we can set disableHttpDebugMethods=true to solve the issue?
> 
> and I can add the disableHttpDebugMethods to Proxy, Function Worker

Makes sense to me. Before merging the pull it would be good to advise on the dev@. Since this can be considered as breaking change we must be careful on cherry-picking on the release branches, although in this case it's a benefit for all the users/operators.

**Review by lordcheng10 — APPROVED** [review]
LGTM

**Review by liangyuanpeng — APPROVED** [review]

**Comment by michaeljmarshall** [comment]
As discussed on the mailing list https://lists.apache.org/thread/w4jzk27qhtosgsz7l9bmhf1t7o9mxjhp, there is no plan to release 2.9.6, so I am going to remove the release/2.9.6 label

**Comment by dave2wave** [comment]
@leizhiyuan Please either rebase and test, or close the PR.

**Pull request closed without merging**
