### PR TITLE
[improve][test] add a test to ensure the exclusive consumer will reconnect even if received ConsumerBusy error

### PR DESCRIPTION
**Pull request by poorbarcode**
### Motivation

**Background**
- When the customer disconnects, the consumer automatically tries to reconnect.
- When a connection is disconnected, the broker will remove the consumer related to this connection.
- The client does not reconnect when it receives a `ConsumerBusyException`.

---

**Issue**
| time | `client disconnect` | `broker disconnect` |
| --- | --- | --- |
| 1 | disconnect | 
| 2 | reconnect |
| 3 | Send `cmd-sub` to the broker | disconnect |
| 4 | Since the old consumer has not been removed in the broker memory, get a consumer busy error |
| 5 | | Remove the old consumer in memory |
| 6 | Stop reconnect |

At this time, there is no consumer under this subscription.

---

**A mechanism to fix the issue above**
Once a consumer has subscribed successfully, the consumer will try to retry regardless of any exceptions received. see: https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L875

### Modifications

Add a test to ensure that the above issue has been fixed

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: x

### CODE REVIEW

**Review by liangyepianzhou — APPROVED** [review]

**Comment by michaeljmarshall** [comment]
> Add a test to ensure that the above issue has been fixed

@poorbarcode - do you have a link to the PR where this issue was fixed?

**Comment by poorbarcode** [comment]
@michaeljmarshall 

> do you have a link to the PR where this issue was fixed?

The PR https://github.com/apache/pulsar/pull/20737 fixes a issue one consumer will reconnect more than one times.

Issue: if we use an exclusive consumer, and hit the issue which https://github.com/apache/pulsar/pull/20737 tries to fix, the consumer will get a `ConsumerBusyException`, which makes the consumer close. This test to confirm this scenario will not occur

**Comment by michaeljmarshall** [comment]
Thanks for the explanation @poorbarcode

**Pull request merged**
