### PR TITLE
Add pulsar_subscription_consumers_count metric

### LINKED ISSUE #15032: [Monitoring - Broker] - Need a metric to track how many consumers are connected and consuming from a given subscription
**Description**
I'm monitoring Pulsar and I would like the ability to monitor how many consumers are connected and subscribing from a given subscription.

Right now this metric already exists for topics`pulsar_consumers_count`
 
It tells how many consumers are connected to a given topic/partition.

I would like a similar metric for subscriptions, i.e `pulsar_subscription_consumers_count`

Specifically, I'm trying to detect a "Stuck" Subscriptions and alert on this case when it occurs

Here is the sample prometheus alerting rule I need
  ```
- name: stuck-subscription
      rules:
      - alert: StuckParitionOrTopic
        expr: pulsar_subscription_back_log > 0 and pulsar_subscription_msg_rate_out == 0 and pulsar_subscription_consumers_count > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          description: Subscription for {{ $labels.topic }} appears to be stuck.
          identifier: '{{ $labels.topic }}' 
```

### PR DESCRIPTION
**Pull request by cbornet**
Fixes #15032

### Modifications

Added metric `pulsar_subscription_consumers_count`

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:

Run `PrometheusMetricsTest::testNonPersistentSubMetrics`

### Does this pull request potentially affect one of the following parts:

no

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 

There are other undocumented subscription metrics. Should document all of them in another PR ?

  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Comment by cbornet** [comment]
Alternative PR to #15041 for discussion.

**Review by nicoloboschi — APPROVED** [review]
LGTM

**Review by eolivelli — APPROVED** [review]
Lgtm

**Review by Technoboy- — APPROVED** [review]

**Comment by cbornet** [comment]
Had to do a fix for when consumer metrics are not enabled. Can you review again ?

**Review by eolivelli — APPROVED** [review]

**Review by HQebupt — APPROVED** [review]
LGTM

**Comment by Anonymitaet** [comment]
ping @momo-jun for providing help on docs

**Comment by momo-jun** [comment]
Hi @cbornet, will you like to submit a follow-up PR to add docs? Let us know your plan or any other assistance you need.

**Comment by momo-jun** [comment]
#### Doc status update
@cbornet will submit a PR to add docs soon.

**Pull request merged**
