### PR TITLE
[Go Functions] Cache producers with sync.Map

### LINKED ISSUE #9511: [Go Functions] NewOutputMessage does not cache producers
The multi-dispatch functionality in go (as implemented with `NewOuputMessage()` in #8327) needs some rethinking. The primary concern of this issue is that it creates a new producer for every output message which is then immediately discarded after one message. At the very least, these producers should be cached, as [suggested here](https://github.com/apache/pulsar/pull/8327#discussion_r511014789). The other concern is one of API/Naming, which I have detailed in a separate issue.

### PR DESCRIPTION
**Pull request by flowchartsman**
This is an ideal use-case for sync.Map as producers (should) only ever
be written once, but will be retrieved many times.

fixes #9511

### Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

### CODE REVIEW

**Comment by freeznet** [comment]
hi @flowchartsman , thanks for your work on this issue. the `sync.Map` is LGTM, but seems not handling if cached producer been closed, do you think a cleanup work should be added when producer is no longer available? also, we should add some tests to verify this assumption.

**Comment by flowchartsman** [comment]
Hmm, what are you asking about? 

- If you're asking about closing the producer when the pfunc exits, you're right; I need to add that.
- If you're asking about a producer failing to send, I don't think the sdk handles that, all send failures are fatal, right?

**Comment by flowchartsman** [comment]
I agree that overall the SDK needs more tests. As near as I can tell, it does not test producer creation or closing at all and there are no integration tests whatsoever.  Is it tested outside of the Go code? If so, I will need assistance. If not, adding tests to the SDK for pfunc lifecycle is kind of a big job.

**Comment by flowchartsman** [comment]
From looking at the code, it looks as if the intent of the SDK is to simply just error out if there is a producer error, whereupon the function will be restarted. Is there a concern with continuing to do it this way?

**Comment by freeznet** [comment]
Just as you said, all send failures are fatal, but this is limited within `goInstance`’s `producer`. For user who get `producer` from `context.outputMessage()`, it might different. Before this pr, function user will always get a new and ready-to-use producer, because if we create producer with error, function crush (I also don’t think this is the correct way, but should been raised up as another issue separately). So user dont have to worry wether the producer is closed or non-existed. but in this pr, for some reason, i assume that user will get a closed producer from cache, and when user try to send message from a closed or non-existed producer, which might have some additional issue, like function been blocked with closed producer. Or user self cannot managed to get a new producer if the cached one is closed. I m not sure if I was over considered this issue, so @sijie @wolfstudy PTAL if you have time, thanks.

**Review by wolfstudy — CHANGES_REQUESTED** [review]
@flowchartsman If you don't deal with the issue of producer recycling, it will cause resource leakage. It seems that this is not a good way to deal with it.

**Comment by wolfstudy** [comment]
But here, a more difficult problem is that you don't know when the producer will be closed. This is determined by the user. The idea of cache producer is OK, but we need to figure out how to deal with these created producers at the same time. If they are not used for a long time, what should we do at this time?

A relatively simple but not very mature idea is: we have a timing task in the background to process these resources regularly, for example: 30 minutes, if the user does not use them, we will turn off these resources

**Comment by flowchartsman** [comment]
> Just as you said, all send failures are fatal, but this is limited within `goInstance`’s `producer`. For user who get `producer` from `context.outputMessage()`, it might different.

It depends on what the goal of the SDK is. If you look at the [python pfunc SDK example](https://pulsar.apache.org/docs/en/functions-overview/#content-based-routing-example), it is just `context.publish(topic, item)`  If that is the experience you are after, then, it seems best to keep it simple and consistent.  Given the way the Go pfunc SDK is structured, this seems like the option more in keeping with the intent.

> A relatively simple but not very mature idea is: we have a timing task in the background to process these resources regularly, for example: 30 minutes

Are there any objections to this idea? It makes sense to me.

**Comment by freeznet** [comment]
> It depends on what the goal of the SDK is. If you look at the [python pfunc SDK example](https://pulsar.apache.org/docs/en/functions-overview/#content-based-routing-example), it is just `context.publish(topic, item)` If that is the experience you are after, then, it seems best to keep it simple and consistent. Given the way the Go pfunc SDK is structured, this seems like the option more in keeping with the intent.

What I am really concerned is, `context.outputMessage()` might return user a dead producer, and user cannot recreate it because it is cached. 

such as 

```
producer := context.outputMessage("topic")
producer.Close() // <- user close the producer
```

later when user try to get a producer for `topic`, a closed producer will return since it is cached. 

> > A relatively simple but not very mature idea is: we have a timing task in the background to process these resources regularly, for example: 30 minutes
> Are there any objections to this idea? It makes sense to me.

I agree with this, in addition, this setting should be configureable.

**Comment by flowchartsman** [comment]
> What I am really concerned is, context.outputMessage() might return user a dead producer, and user cannot recreate it because it is cached.

My proposal is to deprecate `context.OutputMesage()` entirely, disallowing direct access to producers entirely. Alternatively, it could be replaced with `context.NewProducer()`, which does not use the cache at all, providing the best of both worlds.

**Comment by flowchartsman** [comment]
So perhaps it might be best to close this issue and then integrate the caching/upkeep with #9515, which could also take care of creating `context.NewProducer()` (without cache) and then aliasing `context.NewOutputMessage()` to this, with a deprecation warning. Thoughts, @freeznet, @wolfstudy?

**Comment by codelipenghui** [comment]
@freeznet @wolfstudy Could you please help take a look at this PR?

**Comment by codelipenghui** [comment]
The pr had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
Closed as stale, conflict, and no consensus.

**Pull request closed without merging**
