### PR TITLE
[fix] Fix concurrent containers concurrency issue

### PR DESCRIPTION
**Pull request by dao-jun**
Fixes https://github.com/apache/pulsar/issues/22603

### Motivation

Fix concurrent containers concurrency issue

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by lhotari — CHANGES_REQUESTED** [review]
Thanks for reporting the issue and starting the work to fix this issue.

Catching the exception would be the preferred solution since there's no point of using a StampedLock unless optimistic locking is used.

I think that we had this same bug discussed years ago, but for some reason we didn't fix this.

**Comment by dao-jun** [comment]
> Thanks for reporting the issue and starting the work to fix this issue.
> 
> Catching the exception would be the preferred solution since there's no point of using a StampedLock unless optimistic locking is used.
> 
> I think that we had this same bug discussed years ago, but for some reason we didn't fix this.

@lhotari Is there any discuss thread links? I don't see any discuss linked to the origin PRs.

**Comment by lhotari** [comment]
> > Thanks for reporting the issue and starting the work to fix this issue.
> > Catching the exception would be the preferred solution since there's no point of using a StampedLock unless optimistic locking is used.
> > I think that we had this same bug discussed years ago, but for some reason we didn't fix this.
> 
> @lhotari Is there any discuss thread links? I don't see any discuss linked to the origin PRs.

Perhaps in #18390

**Comment by lhotari** [comment]
Found it: https://github.com/apache/pulsar/pull/18390#discussion_r1016594541

**Comment by dao-jun** [comment]
Oh, I see, it looks like introduced local variables to avoid ArrayIndexOutOfBoundsExeception. It makes sense, we can sync https://github.com/apache/pulsar/pull/18390 to bookkeeper.

**Pull request closed without merging**
