### PR TITLE
[component/functions|component/go] Add access to the current message from the function context

### PR DESCRIPTION
**Pull request by vaihtovirta**
### Motivation

It may be helpful to access the current message in order to access its metadata (key, properties, etc).

### Modifications

- Implemented `FunctionContext#GetCurrentRecord` (similar to [Context#getCurrentRecord](https://github.com/apache/pulsar/blob/9c821cf940d422d2ea3d47687bd309fe698ab84e/pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/Context.java#L46))
- Implemented `FunctionContext#SetCurrentRecord`
- Set current message before executing a message handler in `goInstance#handleMsg`

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:

- Added unit tests for `FunctionContext#GetCurrentRecord`
- Added unit tests for `FunctionContext#SetCurrentRecord`
- Added unit tests for `goInstance#handlerMsg`

### Does this pull request potentially affect one of the following parts:

  - The public API: (yes)
  - The default values of configurations: (yes)

### Documentation

  - Does this pull request introduce a new feature? (yes )
  - If yes, how is the feature documented? (docs)

### CODE REVIEW

**Review by sijie — APPROVED** [review]

**Review by wolfstudy — APPROVED** [review]
LGTM +1

**Comment by Anonymitaet** [comment]
@momo-jun thanks, then I've unchecked the `doc-required` label.

**Pull request merged**
