### PR TITLE
support subscription position and expose the producer settings

### LINKED ISSUE #7622: [Pulsar Functions] How do I change the "subscriptionposition" of Pulsar Functions and the batching parameters?
Hi,

	I am making a comparison between Pulsar Functions and Kafka Streams. I have several questions when using Pulsar Functions.
	
	1) Before creating the Pulsar Functions, I already have a producer. It generates 1000 messages to topic A. Then I start the Pulsar Functions to read data from topic A and do some handling.
	I want the Pulsar Functions could read the 1000 messages which has been existed in topic A when Pulsar Functions starts. How to make the Pulsar Functions to read data from the beginning of a topic?

	2) Does Pulsar Functions use batching when reading data from the input topics and sending data to output topic? How to change the batching parameters, like BacthingMaxSize, BatchingMaxPublishDelay?

	I am looking forward to your response.
	
	Thank you very much

### PR DESCRIPTION
**Pull request by 315157973**
Fixes #7622

### Motivation
1 We cannot specify the consume position of the function
2 Pulsar Functions doesn't expose the producer settings publicly

### Modifications
1 The `subscription position` setting already exists in the code, but this parameter is not exposed to the outside, so I exposed this setting in `FunctionConfig`
2 Added the general parameter `producerProperties`, all producer settings can be passed in through it.
3 Expose the producer settings publicly to pulsar source as well

### Verifying this change
unit tests
org.apache.pulsar.io.PulsarFunctionE2ETest#testProducerSpecs
org.apache.pulsar.io.PulsarFunctionE2ETest#testReadPositionEarliest
org.apache.pulsar.io.PulsarFunctionE2ETest#testReadPositionLatest
org.apache.pulsar.io.PulsarFunctionE2ETest#testSinkProducerSetting

### CODE REVIEW

**Comment by 315157973** [comment]
Could someone help CR？
@sijie @codelipenghui

**Comment by codelipenghui** [comment]
@nlu90 Please help review this PR.

**Comment by wolfstudy** [comment]
@315157973 Can you merge the master code and fix conflict?

**Comment by 315157973** [comment]
OK, I will solve it as soon as possible

**Comment by 315157973** [comment]
> @315157973 Can you merge the master code and fix conflict?

@wolfstudy  Please help review

**Review by wolfstudy — CHANGES_REQUESTED** [review]
Thanks @315157973 work for this. In https://github.com/apache/pulsar/pull/7891, we have supported users to specify sub position.

**Pull request closed without merging**
