### PR TITLE
[improve][admin] getMessageById gets message by batch index

### PR DESCRIPTION
**Pull request by nodece**
### Motivation

When the message is a batch message, the `org.apache.pulsar.client.admin.Topics#getMessageByIdAsync(java.lang.String, long, long)` only returns the first message from the batch message, this affects our troubleshooting.

### Modifications

- Add `org.apache.pulsar.client.admin.Topics#getMessageByIdAsync(java.lang.String, long, long, int)` instead of `org.apache.pulsar.client.admin.Topics#getMessageByIdAsync(java.lang.String, long, long)`.
- Add `org.apache.pulsar.client.admin.Topics#getMessageById(java.lang.String, long, long, int)` instead of `org.apache.pulsar.client.admin.Topics#getMessageById(java.lang.String, long, long)`.
- Update `org.apache.pulsar.admin.cli.CmdPersistentTopics.GetMessageById#run` to print all message.
- Update `org.apache.pulsar.admin.cli.CmdTopics.GetMessageById#run` to print all message.

### Verifying this change

Test added.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by dao-jun** [comment]
Seems we need a PIP? 
https://github.com/apache/pulsar/blob/master/pip/README.md#:~:text=Any%20change%20to%20the%20public%20APIs%20(Client%20APIs%2C%20REST%20APIs%2C%20Plugin%20APIs)

**Comment by BewareMyPower** [comment]
@dao-jun Yeah I agree. And I left a comment my comment in the discussion: https://lists.apache.org/thread/olftk1n8ty05xwq59s1z75d72xjpj7no

**Comment by BewareMyPower** [comment]
>  the String format is ledgerId:entryId:batchIndex or ledgerId:entryId, what do you think?

LGTM

**Comment by nodece** [comment]
Closed by #21918

**Pull request closed without merging**
