### PR TITLE
[Improve][Doc] Add explanation about the Helm release script

### PR DESCRIPTION
**Pull request by Sherlock113**
### Motivation and Modifications

Add more explanation about how to use the script to create relevant secrets for Pulsar if using the Helm chart to install it.

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [ ] `doc-not-needed` 
(Please explain why)
  
- [x] `doc` 
(Your PR contains doc changes)

### CODE REVIEW

**Review by Anonymitaet — COMMENTED** [review]
@tjiuming 
can you review this PR from the technical perspective? If it is technically correct, then technical writers can review it from the technical writing perspective, thanks! 😊

**Comment by Anonymitaet** [comment]
@Sherlock113 
Thanks for your contribution!

1. Before submitting a doc PR, please [preview your changes locally](https://docs.google.com/document/d/1wszdtMRo6MhKbVaggPK7_bnKaC4TewuT--GWZZxJNGg/edit#). When submitting a PR, please attach the screenshots of your local preview. In this way, you can get your PR reviewed and merged more quickly.

2. Does this change apply to multiple doc versions? If so, please [update them all](https://github.com/apache/pulsar/tree/master/site2/website/versioned_docs).

Thank you! 😊

**Comment by tjiuming** [comment]
@Anonymitaet 
image
I've read the script, this change looks good to me

**Review by tjiuming — APPROVED** [review]
LGTM

**Comment by Sherlock113** [comment]
Hi @Anonymitaet I added the explanation to all versions and here is a preview image of the latest version for your reference:
Screen Shot 2022-06-16 at 09 10 14
Thanks!

**Review by Anonymitaet — APPROVED** [review]
@Sherlock113 
Thank you! Looking forward to more contributions! 😊

@DaveDuggins @momo-jun FYI: here is a new note for getting started chapter.

**Pull request merged**
