### PR TITLE
PIP-75: Perform serialization/deserialization with LightProto

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

As explained in https://github.com/apache/pulsar/wiki/PIP-75%3A-Replace-protobuf-code-generator , replace the patched Google Protobuf serialization with LightProto. 

 1. Removed all generated Java files (sources are now generated by maven plugin at build time)
 2. Removed everything related to the patched protobuf

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
Overall LGTM

I find it very nice that we are creating less builders and in general the overall simplification of the codebase.

Thank you for providing this improvement.

Most of the CI jobs failed, please take a look

**Review by rdhabalia — APPROVED** [review]
nice work. I think such changes should be merged after extensive testing. Is it already running in any of your test env?

**Review by sijie — CHANGES_REQUESTED** [review]
It is a great contribution! Thanks for working on this! But before merging this pull request, can you share some benchmark results between before this change and after this change? Because it changes the entire serialization and deserialization framework.

**Comment by merlimat** [comment]
> nice work. I think such changes should be merged after extensive testing. Is it already running in any of your test env?

@rdhabalia Not yet, this is a big change against a target that is moving very fast (master). There is no way this can go to production before getting merged to master first, though it will surely get extensively tested before the 2.8 release.

Also, we need to differentiate the 2 aspect: 
 1. Code generator has already extensive set of tests to ensure generated code behaves in the same exact way as protobuf
 2. The integration into the Pulsar repo is dependent on merge conflict, even testing a version today, a new change in master will be likely to introduce bugs in the integration and would need to be re-tested after the merge in any case.

>  can you share some benchmark results between before this change and after this change?

@sijie Good point, the micro-benchmark in https://github.com/splunk/lightproto is based on the default Protobuf 3.13. 

I've added a new benchmark targeting Pulsar specific serizalization at https://github.com/merlimat/LightProtoPulsarBenchmark

```
Benchmark                                                   Mode  Cnt   Score    Error   Units
SimpleBenchmark.deserialize_metadata_lightproto            thrpt    3  18.891 ±  1.675  ops/us
SimpleBenchmark.deserialize_metadata_protobuf_241_patched  thrpt    3   6.187 ±  3.399  ops/us
SimpleBenchmark.deserialize_send_lightproto                thrpt    3  23.830 ±  8.318  ops/us
SimpleBenchmark.deserialize_send_protobuf_241_patched      thrpt    3   7.926 ± 14.269  ops/us
SimpleBenchmark.serialize_metadata_lightproto              thrpt    3   6.699 ± 12.016  ops/us
SimpleBenchmark.serialize_metadata_protobuf_241_patched    thrpt    3   2.943 ±  0.662  ops/us
SimpleBenchmark.serialize_send_lightproto                  thrpt    3  22.905 ± 18.748  ops/us
SimpleBenchmark.serialize_send_protobuf_241_patched        thrpt    3   4.614 ±  1.750  ops/us
```

**Comment by merlimat** [comment]
@sijie PTAL since every days there are new conflicts to fix

**Comment by sijie** [comment]
@merlimat sorry. I am reviewing it today.

**Review by sijie — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
+1

**Pull request merged**
