### PR TITLE
[Client] java client support UnAvroBased Schema

### PR DESCRIPTION
**Pull request by hnail**
### Motivation

JAVA client support UnAvroBasedSchema

### Modifications

- `schema` division to **AvroBasedSchema** and **UnAvroBasedSchema** :

AvroBased Schema | UnAvroBased Schema
------------ | -------------
StructSchema | AbstractStructSchema
GenericSchemaImpl | AbstractGenericSchema

- `GenericSchema` add `of()` method , `GenericSchemaImpl` and `StructSchema` continue to have for backward compatibility and only support AvroBased Schema 。

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no )
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (yes)
  - If yes, how is the feature documented? (not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation (yes)

### CODE REVIEW

**Review by sijie — APPROVED** [review]

**Comment by sijie** [comment]
@hnail The change looks great to me! It is a great refactor to support both AvroBased and UnAvroBased schemas. Thank you for your contributions!

**Review by codelipenghui — APPROVED** [review]

**Comment by hnail** [comment]
> @hnail The change looks great to me! It is a great refactor to support both AvroBased and UnAvroBased schemas. Thank you for your contributions!

thank for your review ，I have commit a UnAvroBasedSchema `ProtobufNative` [PIP-Add ProtobufNative Schema Support](https://docs.google.com/document/d/1XR_MNOuSXyig-CKsdVhr6IXvFwziBRdSoS3oEUiLFe8/edit) and [PR-8372](https://github.com/apache/pulsar/pull/8372)  which depends this PR.  cc @codelipenghui

**Comment by Anonymitaet** [comment]
Confirmed w/ @congbobo184, no need to update doc for this PR.

**Pull request merged**
