### PR TITLE
This should be `isBuiltInSink` not `isBuiltInSource` #7271

### PR DESCRIPTION
**Pull request by sundar-10**
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #<xyz>

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #<xyz>

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by sundar-10** [comment]
@sijie Yeah i will start writing.

**Comment by sundar-10** [comment]
I am trying to write the test, but there seems to be an import error - org.apache.pulsar.functions.proto.Function which says "cannot resolve symbol Function". This error is present in a few other modules inside pulsar-functions as well. This is hindering me from using the debugger.

**Comment by jiazhai** [comment]
@sundar-10 Are you using IntelliJ idea?  
If yes, Try this:
```
A better workaround seems to be: Right-click on shard project "component" -> pom.xml in the project view in IntelliJ, choose "Maven" -> "Ignore Projects". Then do a "Maven" -> "Reimport" on the project pom.xml.
```

**Comment by sundar-10** [comment]
@jiazhai Yeah I am using Intellij idea. I tried what you suggested, I am not able to make it work. Would it be possible to get more detailed steps on resolving this issue? I have sent a private message to you in slack regarding the same.

**Comment by merlimat** [comment]
I think the same fix was already merged in #7272

**Pull request closed without merging**
