### PR TITLE
[improve][admin]namespace CLI set-offload-policy's thresholdBytes support negative and 0

### PR DESCRIPTION
**Pull request by ethqunzhong**
### Motivation
we could set namespace level offload-policy's offload-threshold In the following two `pulsar-admin CLI` ways:
1. `pulsar-admin namespaces set-offload-threshold -s $OFFLOAD_THRESHOLD demo/demo`
2. `pulsar-admin namespaces set-offload-policies --offloadAfterThreshold $OFFLOAD_THRESHOLD demo/demo`

while set offload-threshold value , Negative values disable automatic offload. 0 triggers offloading as soon as possible.
but we can't use `pulsar-admin namespaces set-offload-policies` to set offload-threshold'value to negative or 0 , show as follow：
image
`pulsar-admin namespaces set-offload-threshold` as expected.

image

we should keep `set-offload-threshold` and `set-offload-policies` CLI behavior consistent.

### Modifications
remove `positiveCheck` process while check offloadAfterThreshold value validity at `CmdNamespaces#SetOffloadPolicies`.

### Does this pull request potentially affect one of the following parts:

_If `yes` was chosen, please highlight the changes_

-   Dependencies (does it add or upgrade a dependency): (no)
-   The public API: (no)
-   The schema: (no)
-   The default values of configurations: (no)
-   The wire protocol: (no)
-   The rest endpoints: (no)
-   The admin cli options: (no)
-   Anything that affects deployment: (no)
### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Comment by ethqunzhong** [comment]
@Technoboy- @zymap @hangc0276  PTAL.

**Review by zymap — APPROVED** [review]

**Comment by ethqunzhong** [comment]
@hangc0276 @zymap @Technoboy- This patch is ready to merge.  PTAL.

**Comment by ethqunzhong** [comment]
it seems pass all CI, ready to merged. PTAL @zymap 
image

**Review by Technoboy- — APPROVED** [review]

**Comment by ethqunzhong** [comment]
@Technoboy- ready to merged. PTAL

**Comment by ethqunzhong** [comment]
@codelipenghui ready to merged. PTAL

**Review by Jason918 — APPROVED** [review]
LGTM

**Review by hangc0276 — APPROVED** [review]

**Pull request merged**
