### PR TITLE
[Issue 11205] Support to overwrite option --broker-conf when starting broker

### LINKED ISSUE #11205: Can only specify option --broker-conf once
**Describe the bug**

**To Reproduce**

```
./bin/pulsar broker --broker-conf conf/broker-1.conf
2021-07-03 08:50:38,465 [sun.misc.Launcher$AppClassLoader@55f96302] error Uncaught exception in thread main: Can only specify option --broker-conf once.
com.beust.jcommander.ParameterException: Can only specify option --broker-conf once.
	at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:240)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:913)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:894)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:724)
	at com.beust.jcommander.JCommander.parse(JCommander.java:356)
	at com.beust.jcommander.JCommander.parse(JCommander.java:335)
	at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.<init>(PulsarBrokerStarter.java:143)
	at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:314)
```

**Expected behavior**
Support for specifying configuration files from the command line

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by murong00**
### Motivation

Fixes #11205

### Modifications

Make parameter overwriting allowed.

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@murong00 thanks for your contribution. For this PR, do we need to update docs?

**Comment by murong00** [comment]
> @murong00 thanks for your contribution. For this PR, do we need to update docs?

No need, I have added the `no-need-doc` label.

**Review by tuteng — APPROVED** [review]

**Review by cckellogg — CHANGES_REQUESTED** [review]
I'm not sure this is the correct fix. To me it complicates things. What does `setAllowParameterOverwriting` do? Will apply to all flags? 

You can already provide a custom broker.conf file by setting the `PULSAR_BROKER_CONF` environment variable. 

I think a better way is to remove the flag in the bin/pulsar file as long as things are backwards compatible.

**Comment by tuteng** [comment]
> I'm not sure this is the correct fix. To me it complicates things. What does `setAllowParameterOverwriting` do? Will apply to all flags?
> 
> You can already provide a custom broker.conf file by setting the `PULSAR_BROKER_CONF` environment variable.
> 
> I think a better way is to remove the flag in the bin/pulsar file as long as things are backwards compatible.



> I think a better way is to remove the flag in the bin/pulsar file as long as things are backwards compatible.

@rdhabalia A scenario is to start multiple brokers on one server, because each broker uses a different port number, so use a different configuration file, when using the command `./bin/pulsar broker -c conf/broker-1.conf` to start the broker will throw an exception:

```
2021-07-03 08:50:38,465 [sun.misc.Launcher$AppClassLoader@55f96302] error Uncaught exception in thread main: Can only specify option --broker-conf once.
com.beust.jcommander.ParameterException: Can only specify option --broker-conf once.
	at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:240)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:913)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:894)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:724)
	at com.beust.jcommander.JCommander.parse(JCommander.java:356)
	at com.beust.jcommander.JCommander.parse(JCommander.java:335)
	at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.<init>(PulsarBrokerStarter.java:143)
	at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:314)
```

the current parameter `-c --broker-conf` is actually invalid, I think this is a bug. I tested this fix, I think it is backward compatible, the user can still continue to use the environment variables or the default way to start the broker, this parameter does not change the other commands, only affect the `./bin/pulsar broker` command. @murong00 Am I understanding this correctly?

**Comment by tuteng** [comment]
> I'm not sure this is the correct fix. To me it complicates things. What does `setAllowParameterOverwriting` do? Will apply to all flags?
> 
> You can already provide a custom broker.conf file by setting the `PULSAR_BROKER_CONF` environment variable.
> 
> I think a better way is to remove the flag in the bin/pulsar file as long as things are backwards compatible.

If this option is removed, the user will have to specify the configuration file when using it, which may lead to incompatibility

**Comment by murong00** [comment]
@cckellogg @tuteng Hi, how this issue going? Removing the option in the `bin/pulsar` seems incompatible, users can no longer use `PULSAR_BROKER_CONF` environment variable to start a broker. In addtion, `setAllowParameterOverwriting` only affects options in `PulsarBrokerStarter.StarterArguments` and we can disallow this overwriting within the `Parameter` annotation (`forceNonOverwritable = true`) for critical parameters.

**Comment by codelipenghui** [comment]
The pr had no activity for 30 days, mark with Stale label.

**Comment by tisonkun** [comment]
See https://github.com/apache/pulsar/issues/11205#issuecomment-1345166706.

Closed as won't do.

**Pull request closed without merging**
