### PR TITLE
[doc] Fix broken links to the info about schemas and Schema Registry

### PR DESCRIPTION
**Pull request by vzhikserg**
In the latest version of the documentation, I found a broken link to the concepts about Schema Registry. It seems that this markdown file (concepts-schema-registry.md) was removed. I fixed the same problem in a couple of other files.

### CODE REVIEW

**Comment by merlimat** [comment]
run java8 tests
run integration tests

**Comment by vzhikserg** [comment]
run java8 tests
run integration tests

**Comment by vzhikserg** [comment]
run java8 tests

**Comment by vzhikserg** [comment]
run java8 tests

**Comment by vzhikserg** [comment]
run java8 tests

**Comment by vzhikserg** [comment]
run java8 tests

**Comment by vzhikserg** [comment]
run java8 tests

**Comment by vzhikserg** [comment]
run integration tests

**Comment by vzhikserg** [comment]
run integration tests

**Comment by vzhikserg** [comment]
run integration tests

**Comment by vzhikserg** [comment]
run integration tests

**Comment by vzhikserg** [comment]
run integration tests

**Pull request merged**
