### PR TITLE
[improve][pip] PIP-389: Add Producer config compressMinMsgBodySize to improve compression performance

### PR DESCRIPTION
**Pull request by liangyepianzhou**
### Motivation
The motivation of this PIP is to provide a way to improve the compression performance by skipping the compression of small messages.
We want to add a new configuration `compressMinMsgBodySize` to the producer configuration.
This configuration will allow the user to set the minimum size of the message body that will be compressed. 
If the message body size is less than the `compressMinMsgBodySize`, the message will not be compressed.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [x] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by lhotari** [comment]
Please add the PIP number to the PR title as we usually do.

**Review by Technoboy- — APPROVED** [review]

**Comment by lhotari** [comment]
@liangyepianzhou Please go ahead and close the vote thread. We don't need 3 binding votes for PIPs anymore, that was clarified in #23387.

**Review by lhotari — APPROVED** [review]
LGTM

**Comment by thetumbled** [comment]
I have a question: Is the compression process before the messages batched or after?
If messages are compressed after they are batched, small message problem may be avoided?

**Pull request merged**
