### PR TITLE
[WIP] Commit for test ci, ignore this pr

### PR DESCRIPTION
**Pull request by horizonzy**
Commit for test ci, needn't view.

### CODE REVIEW

**Review by nicoloboschi — CHANGES_REQUESTED** [review]
could you explain more why you split the test? 
it doesn't show up correctly in the CI results? can you provide an example?

**Comment by horizonzy** [comment]
> could you explain more why you split the test? it doesn't show up correctly in the CI results? can you provide an example?

Not mint it, I'm trying to find the flaky test root case, split it just for find.

**Comment by nicoloboschi** [comment]
@horizonzy ok, I suggest you to set the pull as draft, add "WIP" in the title or create it in your fork to not cause confustion

**Comment by horizonzy** [comment]
> @horizonzy ok, I suggest you to set the pull as draft, add "WIP" in the title or create it in your fork to not cause confustion

I try it at my fork and upstream both... It will be faster for test.

**Comment by lhotari** [comment]
@horizonzy If you want to test the CI or modify it, please consider opening PRs to your own fork of apache/pulsar since we have very limited resources in apache/pulsar.
In your own fork, you can run GitHub Actions workflows independently and your builds won't cause the build queue to grow in apache/pulsar.

**Comment by horizonzy** [comment]
> @horizonzy If you want to test the CI or modify it, please consider opening PRs to your own fork of apache/pulsar since we have very limited resources in apache/pulsar. In your own fork, you can run GitHub Actions workflows independently and your builds won't cause the build queue to grow in apache/pulsar.

fine, after ci done at this time, I won't do it again.

**Comment by lhotari** [comment]
> fine, after ci done at this time, I won't do it again.

@horizonzy  +1. There are some instructions in https://lists.apache.org/thread/1ofdbd9j1hhj4c0rw3o7vv8y6rbsxrp0 about using "Personal CI".

**Comment by lhotari** [comment]
@horizonzy The additional benefit of the "Personal CI" is that you get ssh access to the build VMs when the build is running. That is handled by this logic in the pulsar-ci.yaml GitHub Actions workflow file:
https://github.com/apache/pulsar/blob/1682884d5d4860bfcbe25d54ac27e446f94f8716/.github/workflows/pulsar-ci.yaml#L77-L82
and inline composite action implementation: https://github.com/apache/pulsar/blob/master/.github/actions/ssh-access/action.yml

**Pull request closed without merging**
