### PR TITLE
[fix][client] Fix broker/Client CPU reaching 100% during retriable connection failure

### PR DESCRIPTION
**Pull request by rdhabalia**
Fixes : https://github.com/apache/pulsar/issues/23250

### Motivation

[PIP-91](https://github.com/apache/pulsar/pull/11627/) had added a change to accumulate list of Exceptions and attempt for not any good reasons. On connection failure, client lib always logs the exception and error  so, there is always a way to find out any previous exception for the connection issues. and there is no any good reason or standard to keep large number of  exception-list in memory and additionally generate huge huge logs which creates unnecessary string objects and consumes high CPU that eventually makes broker unavailable due to high CPU and high gc pauses.

### Modifications

Client lib keeps the previous exception list during connection failure which is unnecessary because of two reasons: 
1) in almost all cases, all previous Exceptions are with same type and same error message as intermittent connection failure and retry happens due to same the issue. 
2) Client lib always logs the exception so, no need to keep list of previous exception list in memory and user can always track all previous exceptions from the log. 
however, client lib can still keep the counter for previous-attempt in the exception context to see number of failures/retry and how far user should check in the logs. So, Client lib should remove the in-memory unnecessary previous exception objects to avoid huge logging data-print but still can keep the exception-counter to help users to do debugging in logs.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by nodece — APPROVED** [review]

**Comment by lhotari** [comment]
Thank you @rdhabalia. Good work!
One of the remaining challenges in addressing the problem is about retaining binary compatibility with previous versions of Pulsar clients. @rdhabalia do you think that there would be a way to make a change where this is achieved?

**Comment by rdhabalia** [comment]
@lhotari 
`PulsarClientException::toString()` returns a string message; ideally, there is no such contract to maintain the format. in fact, none of the exception message string should have that contract.
another solution is to add client-configuration to restrict the stacktrace by ignoring storing and printing any previous exception but then it will be really bad design to add a client-configuration which will be used to control Exception toString message format.
I guess, motivation of introducing previous-Exception to find out number of attempts happened with such exception, and this PR still keeps attempts-value and prints into the toString() method.
Also, this change should not break any application logic as it prints less information, and any application must handle such information.
So, I guess this change should not break backward compatibility.

**Comment by rdhabalia** [comment]
@lhotari please let me know if we have any additional concerns, or else we can merge this PR.

**Comment by lhotari** [comment]
> @lhotari please let me know if we have any additional concerns, or else we can merge this PR.

No other concerns that notifying the dev mailing about changing the public methods of a published class and removing a PIP-91 feature. You could make it a lazy consensus decision from my point and merge it in 24hrs unless someone stops you and has a good reason to block it. Makes sense?

**Comment by rdhabalia** [comment]
done. I have sent email and will wait for 1-2 days before merging this PR.

**Pull request merged**
