### PR TITLE
[improve] [admin] Make the default value of param --get-subscription-backlog-size of admin API topics stats true

### PR DESCRIPTION
**Pull request by poorbarcode**
### Motivation

In the PR https://github.com/apache/pulsar/pull/9302, the property backlog size of each subscription returned in the response of the API topics stats, by default this property is always equal to 0 in response, and this will confuse users. Since the calculation of backlog size is done in broker memory, there is no significant overhead(the process is described in the following section), so I think the correct values should be displayed by default.

#### Discuss in mail list
- https://lists.apache.org/thread/wvjrp3co9fyl596onwv037944kdz000d

#### The following two APIs should be affected:

In Pulsar admin API
```
pulsar-admin topics stats persistent://test-tenant/ns1/tp1
--get-subscription-backlog-size
pulsar-admin topics stats persistent://test-tenant/ns1/tp1 -sbs
```
the default value of parameter `--get-subscription-backlog-size` will be `true`

In Pulsar Rest API
```
curl GET "http://127.0.0.1:8080/test-tenant/ns1/tp1/stats?subscriptionBacklogSize=true"
```
the default value of the parameter `subscriptionBacklogSize` will be `true`

#### The following is the process of calculating backlog size:
- Divide `PersistentTopc.ledgers` into two parts according to the ledgerId of the mark delete position of the cursor. The second part is ledgers indicating the messages still need to be consumed, aka backlogSizeInLedgers.
- Find the LedgerInfo whose ledgerId is the same as the ledgerId of the mark delete position of the cursor, and we can also divide the ledger into two parts, the second part is entries indicating the messages still need to be consumed, multiply the average size of each entry in metrics by the number of still need to be consumed entries we can get the backlog size in this ledger. aka backlogSizeInEntries.
- `backlogSizeInLedgers` + `backlogSizeInEntries`

### Modifications

- Make the default value of param "--get-subscription-backlog-size" of admin API "topics stats" `true`
- Make the attribute 'backlogSize' in the response to be -1 when `-sbs` is false, for distinguish whether `--get-subscription-backlog-size` is set to true

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: 
- https://github.com/poorbarcode/pulsar/pull/54

### CODE REVIEW

**Review by gaoran10 — COMMENTED** [review]
LGTM, the calculation uses the data in memory, no IO operations, and maybe we can return -1 when the option param `--get-subscription-backlog-size` is false.

**Comment by poorbarcode** [comment]
@gaoran10 

> the calculation uses the data in memory, no IO operations, and maybe we can return -1 when the option param --get-subscription-backlog-size is false.

Good idea. Already make the attribute 'backlogSize' in the response to be -1 when if `-sbs` is false. Please take a look again

**Review by Technoboy- — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Comment by eolivelli** [comment]
@poorbarcode this is a breaking change.
We should not commit it to released branches.

**Comment by eolivelli** [comment]
cc @codelipenghui

**Comment by michaeljmarshall** [comment]
I agree, this is a change in a default, we should not cherry pick it.

**Comment by poorbarcode** [comment]
@eolivelli @michaeljmarshall 

Thanks for checking my mistakes

**Pull request merged**
