### PR TITLE
[improve][ci] Add schedule trigger to get master branch code coverage daily

### PR DESCRIPTION
**Pull request by yaalsn**
### Motivation

To improve code coverage accuracy and have a view of comparing PR and master branch, we need to run master branch CI daily and except flaky tests. The best way is to run master branch CI after PRs merged, but pulsar's Github action runners have few resource, running daily is a trade-off between cost and accuracy.

### Modifications

- Pulsar CI workflow run daily (12:00, lunch time or sleeping time)
- Except flaky test group to run code coverage, otherwise we cannot get an accurate base coverage.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/yaalsn/pulsar/pull/14

### CODE REVIEW

**Comment by nodece** [comment]
I wonder if it makes sense. The use of CI resources should be minimized.

**Comment by yaalsn** [comment]
> I wonder if it makes sense. The use of CI resources should be minimized.

I think running daily is minimized.

**Comment by yaalsn** [comment]
@lhotari Could you help to take a look?

**Comment by codelipenghui** [comment]
> I wonder if it makes sense. The use of CI resources should be minimized.

It should be ok. We just update the new code coverage for the master branch per day.

**Comment by lhotari** [comment]
After this PR, the scheduled build gets run on all forks. There's PR #18411 by @tisonkun  to fix this issue.

**Pull request merged**
