### PR TITLE
Force before and after methods to always run

### PR DESCRIPTION
**Pull request by aahmed-se**
This should improve test stability

### CODE REVIEW

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by rdhabalia** [comment]
how does it help if function-worker actually has the deadlock issue?

**Comment by aahmed-se** [comment]
@rdhabalia it's one part of the problem , if one test fails teardown doesn't run so it won't solve the issue but it will the right logs.

**Comment by srkukarni** [comment]
@aahmed-se is this still active?

**Comment by aahmed-se** [comment]
We still need this.

**Pull request closed without merging**
