### PR TITLE
[managed-ledger] [code cleanup] unused local variable in ManagedLedgerImpl

### PR DESCRIPTION
**Pull request by HQebupt**
### Motivation
Code cleanup, one local variable in ManagedLedgerImpl is not used.

- retentionSizeQuotaMet

### Modifications
Delete one local variable.

### Verifying this change

- [x]  Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:
If `yes` was chosen, please highlight the changes

- Dependencies (does it add or upgrade a dependency): (no)
- The public API: (no)
- The schema: (no)
- The default values of configurations: (no)
- The wire protocol: (no)
- The rest endpoints: (no)
- The admin cli options: (no)
- Anything that affects deployment: (no)

### Documentation
Check the box below and label this PR (if you have committer privilege).

Need to update docs?
- [x]  no-need-doc

Code cleanup.

### CODE REVIEW

**Review by Shoothzj — APPROVED** [review]

**Review by Jason918 — APPROVED** [review]

**Comment by Anonymitaet** [comment]
@HQebupt please do not delete the backticks (``) for no-need-doc (the correct format is `no-need-doc`), or else Bot can not recognize the label and fails to label the PR.

**Comment by HQebupt** [comment]
> 

Thank you very much. :)

**Comment by HQebupt** [comment]
> @HQebupt please do not delete the backticks (``) for no-need-doc (the correct format is `no-need-doc`), or else Bot can not recognize the label and fails to label the PR.
@Anonymitaet Thanks. It is my first time to create a PR. I had a quick question. Would I trigger the test again since there are 2 failing tasks in 27 test tasks ?

**Comment by Jason918** [comment]
> /pulsarbot run-failure-checks

@HQebupt We can use this to rerun flaky tests.

**Comment by HQebupt** [comment]
> > /pulsarbot run-failure-checks
> 
> @HQebupt We can use this to rerun flaky tests.

Great, thank you Ting brother. 👍

**Comment by HQebupt** [comment]
@Shoothzj Hi, Could you please help to merge it because the merging is blocked,  At least 1 approving review is required by reviewers with write access. Thank you in advance.

**Comment by HQebupt** [comment]
@hangc0276 @codelipenghui  Could you please approve it to merge since it is my first PR and is blocked ?  Thank you.

**Review by eolivelli — APPROVED** [review]

**Comment by eolivelli** [comment]
Committed to master branch


Thanks

**Comment by HQebupt** [comment]
> 

You are welcome.

**Pull request merged**
