### PR TITLE
[branch-2.10][improve][broker] Do not retain the data in the system topic

### PR DESCRIPTION
**Pull request by liangyepianzhou**
### Motivation

For some use case, the users need to store all the messages even though these message are acked by all subscription. So they set the retention policy of the namespace to infinite retention (setting both time and size limits to `-1`).  But the data in the system topic does not need for infinite retention.

### Modifications

For system topics, do not retain messages that have already been acknowledged.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by poorbarcode — APPROVED** [review]

**Review by Technoboy- — APPROVED** [review]

**Comment by liangyepianzhou** [comment]
@yaalsn I have no idea for the failed tests. Could you please take a look? Thanks!
```
java.lang.IllegalStateException: Check failed: Docker environment should have more than 2GB free disk space
```

**Review by dao-jun — APPROVED** [review]
lgtm

**Comment by liangyepianzhou** [comment]
The `Python - Build 3.9 client / build-wheel` and `CPP build on Windows / Windows x64` tests failed after https://github.com/apache/pulsar/pull/22044 is cherry-picked into branch-2.10. Do you mind taking a look?

**Comment by BewareMyPower** [comment]
We can ignore these two failed workflows because we no longer maintain the C++/Python code in main repo. I see it does not block merging this cherry-pick. If you have concern about the failed workflows, I think you can remove them from the CI.

**Pull request merged**
