### PR TITLE
[Doc] Fix JavaDoc issues. 

### PR DESCRIPTION
**Pull request by kellyfj**
Issues spotted by IntelliJ

### Motivation
IntelliJ complains and highlights these issues

### Modifications
Sync JavaDoc with code

### Verifying this change
This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): no
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no
  - The rest endpoints: no
  - The admin cli options: no
  - Anything that affects deployment: no

### Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by sijie — APPROVED** [review]

**Comment by sijie** [comment]
@kellyfj Can you rebase this pull request to latest master to include some CI fixes?

**Comment by kellyfj** [comment]
@sijie I've been rebasing every few days but still seeing a number of failures - do you have any advice?

**Review by vzhikserg — APPROVED** [review]

**Comment by BewareMyPower** [comment]
I've fixed the `testIndividualAck` cpp unit test failure in #8141 , please rebase and commit again, thx!

**Comment by kellyfj** [comment]
Thank you @BewareMyPower

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
