### PR TITLE
[fix][cli] Fix expiration of tokens created with "pulsar tokens create"

### LINKED ISSUE #22811: [Bug] [cli] Pulsar Tokens Create is mishandling time units (specifically, treating seconds as milliseconds)
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

The versions affected 3.2.0 3.2.1 3.2.2 and 3.2.3

### Minimal reproduce step

Create a JWT token using an affected version.
bin/pulsar tokens create --secret-key /pulsar/secret.key --subject test-user --expiry-time 3600s
Use a [JWT decoder](https://jwt.io/) and you will see that the expiry time is wrong.

### What did you expect to see?

A JWT token with the desired --expiry-time

### What did you see instead?

As a workaround, you can multiply the --expiry-time by 1000 if you specify s in at the end of --expiry-time. To convert it to mili sec.

The mentioned bug affects all time units, not just seconds.

### Anything else?

It appears that the bug was introduced in this pull request: [GitHub link](https://github.com/apache/pulsar/pull/21412/files). I'll work on fixing it and submit a pull request. Additionally, I'll look into adding test coverage.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by entvex**
Fixes #22811 

### Motivation

This fix addresses a regression caused by changes in this [pull request](https://github.com/apache/pulsar/pull/21412/files). It’s crucial for users who rely on `bin/pulsar tokens create` for creating JWT tokens.

The versions affected 3.2.0 3.2.1 3.2.2 and 3.2.3

### Modifications

In this fix, I have changed it back to use seconds and added additional tests to prevent similar issues in the future.

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [X] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [X] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by lhotari — CHANGES_REQUESTED** [review]
Good work!

Please use a TestNG parameterized test for the test cases since they are essentially the same test case with different parameters.
Here's one example how it can be achieved with TestNG: 
https://github.com/apache/pulsar/blob/47fd1a3e414982555d55ca92e669fc63d3095636/pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java#L1687-L1688
https://github.com/apache/pulsar/blob/47fd1a3e414982555d55ca92e669fc63d3095636/pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java#L199-L207

**Comment by entvex** [comment]
Thanks, @lhotari 😄
I have changed the tests as you requested.

**Review by lhotari — APPROVED** [review]
LGTM. Good work @entvex

**Comment by lhotari** [comment]
backported to branch-3.2 with commit f1c45476

**Pull request merged**
