### PR TITLE
[pulsar-client] Modify CmdProduce to avoid closing resource manually

### PR DESCRIPTION
**Pull request by murong00**
### Motivation

It is better to avoid closing resource manually in `CmdProduce`.

### Modifications

Use `Files.readAllBytes` instead of `FileInputStream`.

### CODE REVIEW

**Comment by sijie** [comment]
retest this please

**Comment by sijie** [comment]
retest this please

**Comment by sijie** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by sijie** [comment]
run integration tests

**Comment by merlimat** [comment]
run integration tests

**Pull request merged**
