### PR TITLE
Revert "[fix #9851] Add forwardSourceMessageProperty to SourceConfig …

### LINKED ISSUE #9851: Pulsar IO Source Connectors properties not added to message
**Describe the bug**
I have been developing a couple of Pulsar IO Source connectors. They are able to write out message bodies but properties (even though the getProperties() message does appear to be called) are not added to the messages published onto the destination topic.

A minimal test case can be demonstrated by adding properties to the Data Generator Source.

**To Reproduce**
Add the following to DataGeneratorSource.java and then build and deploy the connector:

            @Override
            public Map<String, String> getProperties() {
                HashMap<String, String> props = new HashMap<String, String>();
                props.put("hello", "world");
                props.put("foo", "bar");
                return props;
            }

**Expected behavior**
A message is published onto the destination topic with both the generated message contents (json representation of a person) and the properties as hard coded above. However the properties are missing.

Tested on Pulsar 2.7.0

### PR DESCRIPTION
**Pull request by jerrypeng**
…(#9907)"

This reverts commit d0249e5695c75d8d65a4180fd599b17971368f33.

### Motivation

We don't need to add additional configuration for message properties to be set for Pulsar messages produced by a source.  Why do we need to add a flag for the source? If the `getProperties()` of the Record interface returns a value, it should just automatically be set as a message property.  What is the use case to disable something like this? Why would the user want to disable an intentional behavior of a source? Unless the implementation of the source is sub-optimal. IMO the behavior should always be forwardSourceMessageProperty always be set to set if it is a source.  

We should not add more knobs for users to turn when there is no concrete use case that justifies it. Adding more configurations to be supported at the framework level adds more complexity to maintenance and future development.

I would also suggest not adding support on a framework level if it can be added at a higher level like Pulsar IO connector level which this switch can be.

### CODE REVIEW

**Comment by jerrypeng** [comment]
The correct solution should just be

https://github.com/apache/pulsar/pull/9943/files

**Comment by jerrypeng** [comment]
cc @david-streamlio @freeznet

**Comment by jerrypeng** [comment]
I do think the tests written as part of

https://github.com/apache/pulsar/pull/9907/files

we should still keep.

**Review by merlimat — APPROVED** [review]
It makes sense to me that if a source decides to emit a record with some properties, the normal case would be to always includes those. 

If a particular source is emitting a "problematic" amount of properties, it could be either a problem with that source or it could be a config option for that source.

**Comment by freeznet** [comment]
@jerrypeng Thanks for bring this here, and I get your point. I would also like to express my opinion here. 

The added knob is more concern from user's perspective, like if a source connector is maintained by another orgs or devs, and it passes `Record` with properties that user doesn't need, I think it would be less painful to Pulsar user if there is a knob provided by Pulsar.

**Comment by david-streamlio** [comment]
> I do think the tests written as part of
> 
> https://github.com/apache/pulsar/pull/9907/files
> 
> we should still keep.

FYI, I have added the tests to the alternative PR, https://github.com/apache/pulsar/pull/9943/files.  The integration test class was already in the code base so I only need to add just the `TestPropertySource` class

**Comment by merlimat** [comment]
@freeznet 

>  if a source connector is maintained by another orgs or devs, and it passes Record with properties that user doesn't need, I think it would be less painful to Pulsar user if there is a knob provided by Pulsar.

This seems to be more of an issue which regards a particular source implementation, which can be solved by having configuration specific to that connector.

**Comment by jerrypeng** [comment]
@freeznet first of all thank you for looking into a solution for an existing issue.  There definitely was a bug in the framework involving setting messaging properties. 

>  like if a source connector is maintained by another orgs or devs, and it passes Record with properties that user doesn't need

If the message properties not useful for users then why does the source set them.  It seems like an issue with the source implementation.  If there is a scenario in which setting message properties needs to be more configurable, then the source can support a configuration specific to the source and the end user can just use that knob.

Also the name of the config is called `forwardSourceMessageProperty` which also makes little sense in the context of sources.  It make sense in the context of the functions since functions do not necessarily control the the data it is reading but the source does.

I would strongly suggest we revert this change and don't make this configurable at a framework level.  The behavior for a source that sets properties is that they should automatically be applied to the underlying pulsar message.  If there is custom behavior that needs happen in regards to message properties it should be a source specific configurations.

**Pull request merged**
