### PR TITLE
[Transaction] Add transaction admin

### PR DESCRIPTION
**Pull request by liangyepianzhou**
## Motivation
Add the CmdTransactions to PulsarAdminTool.
## Modification
Add the CmdTransactions to PulsarAdminTool.
### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 

- [x] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [ ] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
+1

**Review by Shoothzj — APPROVED** [review]

**Review by congbobo184 — APPROVED** [review]

**Comment by congbobo184** [comment]
Add the CmdTransactions to PulsarAdminTool.

**Comment by Anonymitaet** [comment]
@liangyepianzhou `transaction` is shown on pulsar-admin website. https://pulsar.apache.org/tools/pulsar-admin/2.10.0-SNAPSHOT/#transactions
image

Thanks @urfreespace for fixing the display issue!

**Pull request merged**
