### PR TITLE
Enable checkstyle in pulsar-client-tools module

### PR DESCRIPTION
**Pull request by yuruguo**
### Motivation
I found that the code style in the `pulsar-client-tools` module is not standardized but can run through all `CI` When I review [PR#13624](https://github.com/apache/pulsar/pull/13624#discussion_r778916227), which easily leads to lack of standardization of the code.
The purpose of this PR is to introduce `checkstyle-plugin` to avoid the above problems.

### Modifications
- Enable CheckStyle Plugin
- Fix checkstyle violations

### Documentation
- [x] `no-need-doc`

### CODE REVIEW

**Review by Shoothzj — APPROVED** [review]

**Comment by yuruguo** [comment]
@codelipenghui @315157973 @hangc0276 PTAL

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
