### PR TITLE
[improve][broker][branch-2.11] Improve tls config on replication client and cluster cli

### PR DESCRIPTION
**Pull request by nodece**
### Motivation

This feature should be cherry-pick #17295 to branch-2.11, we have already made TLS improvements to broker and proxy.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Comment by nodece** [comment]
The branch-2.11 CI is broken, I'll make a PR to fix the CI.

**Review by coderzc — APPROVED** [review]

**Pull request merged**
