### PR TITLE
[improve][client] add externalListenerThreadName parameter

### LINKED ISSUE #22170: Aim to rename prefix 'pulsar-external-listener' in threads java client
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

While consuming a message, code executed by Consumers is done on a thread pool. Thread name are prefixed by `pulsar-external-listener-`. While logging, we are writing thread name as a prefix of each line. 

This hard-coded name 'pulsar-external-listener' is too generic for us and too long. We want to rename it by ourselves.

### Solution

Add a configuration option in the client to set the external-listener-thread name.

### Alternatives

_No response_

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by jbarotin**
Fixes #22170

### Motivation

Add a configuration option in the client to set the external-listener-thread name.

### Modifications

Modified client configuration

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:
- added a integration test to check the parameter is working

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by dao-jun — CHANGES_REQUESTED** [review]
it seems that we need a PIP for the change?
https://github.com/apache/pulsar/blob/master/pip/README.md

**Review by Coselding — APPROVED** [review]

**Comment by lhotari** [comment]
I'd suggest renaming `externalListenerThreadName` to `externalListenerThreadNamePrefix`.

The value is currently passed to io.netty.util.concurrent.DefaultThreadFactory under the covers where the parameter is called `poolName`.

The actual thread name is in format `poolName-[poolIdCounter]-[threadIdCounter]`. This can be seen from the source code of DefaultThreadFactory: https://github.com/netty/netty/blob/85cee9d1a8881a93e7c43a02baefea75b6ade2b5/common/src/main/java/io/netty/util/concurrent/DefaultThreadFactory.java#L93-L105

**Review by lhotari — CHANGES_REQUESTED** [review]
Please check the comment https://github.com/apache/pulsar/pull/22174#issuecomment-1979083454 . In addition to this a minimal PIP would be required since the API is modified. 

The use case is extraordinary and there's a chance that this gets rejected so please start the discussion on the dev mailing list before putting much effort. A PIP could be very minimal. 

The only thought is that I have is that if I could customize the external listener thread name prefix, why couldn't I customize the names of the other thread pools? I'd expect to have consistency across the API.

Since the problem for you was logging configuration, isn't there a way to limit the length of the thread name in the logging configuration?
In Log4J, this is possible with something like `%.10t` to truncate the thread name to 10 characters. Please check [the docs for `%` in Log4J pattern layouts](https://logging.apache.org/log4j/2.x/manual/layouts.html#PatternPercentLiteral).

**Comment by BewareMyPower** [comment]
> The only thought is that I have is that if I could customize the external listener thread name prefix, why couldn't I customize the names of the other thread pools? I'd expect to have consistency across the API.

+1 to me. If this new method is merged, should we add some other methods like `setXxxThreadName` as well? Would that be "over-configured"? Note: Pulsar already has too many configurations that might never be used.

**Comment by lhotari** [comment]
Since the problem for you was logging configuration, isn't there a way to limit the length of the thread name in the logging configuration?
In Log4J, this is possible with something like `%.10t` to truncate the thread name to 10 characters. Please check [the docs for `%` in Log4J pattern layouts](https://logging.apache.org/log4j/2.x/manual/layouts.html#PatternPercentLiteral).
With Log4J, you could also replace a string to shorten it. Check ["replace" in the patterns part of the doc](https://logging.apache.org/log4j/2.x/manual/layouts.html#patterns). 
For example, `%replace{%t}{pulsar-external-listener-}{pel-}` would replace `pulsar-external-listener-` with `pel-`.

**Comment by jbarotin** [comment]
> With Log4J, you could also replace a string to shorten it. Check ["replace" in the patterns part of the doc](https://logging.apache.org/log4j/2.x/manual/layouts.html#patterns).
> For example by using %replace{%t}{pulsar-external-listener-}{pel-} instead of %t in the logging pattern would result in pulsar-external-listener- getting replaced with pel- in the thread name.

For logging purpose, it should work, good idea, I'll try that.  

But, even, it's a nice workaround, the app will not lose coherence. I mean, if I execute a `jstack`, then the thread name printed will not be the same as the thread name written in logs. All my team members have to be aware of this workaround. 

I can try (next week) writing à PIP, in this way, and then, if it's accepted, update my PR.

**Comment by lhotari** [comment]
> But, even, it's a nice workaround, the app will lose coherence. I mean, if I execute a jstack, then the thread name printed will not be the same as the thread name written in logs. All my team members have to be aware of this workaround.

Well I'd consider this to not be a major issue. 

There's a chance that the PIP doesn't get accepted as-is since we might not want to litter the.main interface with configuration options that are used by 1 user out of 10000. 
One solution could be to have a way to hook into lower level configuration interfaces instead of adding all choices on the main interface. It would be great to see how such details are accommodated in other libraries.

**Comment by nodece** [comment]
I think you can add an external executor provider config to `ClientBuilder.java`.

It is more flexible.

**Comment by jbarotin** [comment]
To be franc, my real use case is to display the "topic name" on every log line executed in the Pulsar external listener. 

While developing this PR, I saw a misconception we had: we currently have one Pulsar Client by topic. My idea was to use the executor thread name prefix to identify the topic name. I read the we should better have one client instance by JVM instance.

This misconception comes from our historical message broker Apache ActiveMQ and its pool, because amq pool is working like this : one pool by "queue" (it's how topic are named in amq), and then pool thread name prefix is obtained from the Listener Interface we give to the pool, implementation of this interface has the same name the queue is consuming.

Anyway, have you got any idea how to display the topic name automatically in logs written by our code executed by the  external-pulsar-listener  ?

**Comment by lhotari** [comment]
> I think you can add an external executor provider config to `ClientBuilder.java`.
> 
> It is more flexible.

@nodece There's a draft PIP, "PIP-234: Support using shared thread pool across multiple Pulsar client instance",  for this purpose https://lists.apache.org/thread/5jw06hqlmwnrgvbn9lfom1vkwhwqwwd4 / https://github.com/apache/pulsar/issues/19074 . I don't think that the design is finished since there are some shaded class issues with the current design. We don't want to expose Netty in the Client API.

**Comment by lhotari** [comment]
> While developing this PR, I saw a misconception we had: we currently have one Pulsar Client by topic. My original idea was to use the executor thread name prefix to identify the topic name. I read around pulsar discussion that it's better to have one client instance by JVM instance.

Yes, it's better to share the instance. The only drawback currently is that rate limiting has a gap where all producers and consumers on the same connection get backpressured when any limit exceeds (mentioned in ["out of scope" for PIP-322](https://github.com/apache/pulsar/blob/master/pip/pip-322.md#out-of-scope)).

**Pull request closed without merging**
