### PR TITLE
[Issue #7660] [pulsar-cli] Add support for producing JSON object via Pulsar Client CLI

### PR DESCRIPTION
**Pull request by devinbost**
### Motivation
The current options for producing messages via the pulsar-client producer do not easily allow the publishing of JSON objects. The default separator (a comma) splits the JSON object into malformed parts when more than one key/value pair is provided. It is possible to change the default separator to a substring that is unlikely to be found, but for large messages, there is no guarantee that the substring won't exist in the message. Moreover, for new users who might not be aware that they can change the default separator, it can be difficult and confusing for them when they have trouble determining how to publish the JSON object. Publishing a JSON object is very common, so this feature is much needed. 

### Modifications

I added an additional parameter to allow passing the JSON object as a string. I considered adding support for passing multiple JSON objects, but that gets more complex to implement and may be unnecessary because most users can either create a script with multiple lines with inline JSON messages to produce repeatedly, or they can add an object splitter function or producer/consumer to split an array of JSON objects into single JSON objects for a downstream consumer. I chose to add the additional parameter (--json or -j) instead of modifying the existing contract for passing messages (via --message or -m) to ensure backwards compatability.  

### Verifying this change (Edited)

I added `PulsarClientToolTest.testJsonInitialization()` to verify the added feature.

### Does this pull request potentially affect one of the following parts:

  - Dependencies: (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - **The admin cli options: (yes)**
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? **(yes)**
  - If yes, how is the feature documented? (see below)

I updated documentation in several places to document the new feature, but I may have missed some places, so feedback on what other pages need to be updated would be helpful.

### CODE REVIEW

**Comment by devinbost** [comment]
@sijie @merlimat I'm ready for a review on this PR. Maybe someone can be assigned to it? It doesn't look like it will let me assign reviewers.

**Comment by devinbost** [comment]
@aahmed-se maybe you can take a look?

**Comment by devinbost** [comment]
@sijie JSON objects are passed as strings in this PR. In my description, I explained that it's currently not possible to do this with the CLI due to the string splitting issue that I described, which makes it harder to write scripts and test automation that uses the CLI.

**Comment by sijie** [comment]
@devinbost 

You can use "-f" to specify the content to produce. 

We can improve the tool to disable separator to allow user passing in the whole string as the message payload, instead of introducing a new option.

**Comment by devinbost** [comment]
@sijie You're suggesting that we add a boolean parameter to disable string splitting so we can use the existing message parameter to pass the string instead of introducing a new option?

**Comment by sijie** [comment]
I don't suggest adding a new option. I was suggesting instead of adding a new option just re-using existing option (i.e. if people provide an empty separate, that means the separator is disabled).

**Pull request closed without merging**
