### PR TITLE
Add missing version update for 2.4.1 website

### PR DESCRIPTION
**Pull request by jiazhai**
when release 2.4.1 leaked update latest version of website, this is to fix the error

### CODE REVIEW

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Pull request merged**
