### PR TITLE
[docs] Fix typo in prometheus metrics

### PR DESCRIPTION
**Pull request by k2la**
https://pulsar.apache.org/docs/en/reference-metrics/#subscription-metrics
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/TopicStats.java

### Modifications
- Fix typo `massage` => `message`

### CODE REVIEW

**Comment by k2la** [comment]
restest this please

**Comment by k2la** [comment]
run java8 tests
run integration tests

**Comment by massakam** [comment]
run integration tests

**Comment by merlimat** [comment]
run integration tests

**Comment by k2la** [comment]
run integration tests

**Comment by k2la** [comment]
run integration tests

**Pull request merged**
