### PR TITLE
fixed Producer semaphore permit release issue

### LINKED ISSUE #13671: Producer semaphore permit release issue
**Describe the bug**

```
23:41:11.360 [pulsar-client-io-1-1:org.apache.pulsar.client.impl.ProducerImpl@271] ERROR org.apache.pulsar.client.impl.ProducerImpl - Semaphore permit release count request greater then availablePermits : availablePermits=350, releaseCountRequest=380
```

**To Reproduce**

Run the following test.

```java
package io.streamnative.test;

import org.apache.pulsar.client.api.Consumer;
import org.apache.pulsar.client.api.Message;
import org.apache.pulsar.client.api.Producer;
import org.apache.pulsar.client.api.PulsarClient;
import org.apache.pulsar.client.api.PulsarClientException;
import org.apache.pulsar.client.api.Schema;
import org.apache.pulsar.client.api.SubscriptionInitialPosition;
import org.apache.pulsar.client.api.SubscriptionType;
import org.apache.pulsar.client.api.transaction.Transaction;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

public class TransactionTest {
    private static final Logger log = LoggerFactory.getLogger(TransactionTest.class);
    public static void main(String[] args) throws PulsarClientException, InterruptedException {
        final String sourceTopic = "s_topic";
        final String targetTopic = "t_topic";
        PulsarClient client = PulsarClient.builder()
                .serviceUrl("pulsar://127.0.0.1:6650")
                .enableTransaction(true)
                .build();
        Producer<String> producer = client.newProducer(Schema.STRING)
                .topic(targetTopic)
                .blockIfQueueFull(true)
                .sendTimeout(0, TimeUnit.SECONDS)
                .create();
        Consumer<String> consumer = client.newConsumer(Schema.STRING)
                .topic(sourceTopic)
                .subscriptionName("sub")
                .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest)
                .subscriptionType(SubscriptionType.Shared)
                .subscribe();

        final int totalTransactions = 100000;
        CountDownLatch latch = new CountDownLatch(totalTransactions);

        log.info("Prepare data!");

        Producer<String> sourceProducer = client.newProducer(Schema.STRING)
                .topic(sourceTopic)
                .sendTimeout(0, TimeUnit.SECONDS)
                .blockIfQueueFull(true)
                .create();

        for (int i = 0; i < totalTransactions; i++) {
            sourceProducer.newMessage().value(i + "").sendAsync();
        }
        sourceProducer.flush();

        log.info("Test started!");
        new Thread(() -> {
            for (int i = 0; i < totalTransactions; i++) {
                try {
                    Message<String> msg = consumer.receive();
                    log.debug("Received message!");
                    CompletableFuture<Transaction> txn = client.newTransaction().build();
                    txn.thenComposeAsync(transaction -> {
                        log.debug("Transaction opened!");
                            return producer.newMessage(transaction).value(msg.getValue()).sendAsync()
                                .thenComposeAsync(messageId -> {
                                    return consumer.acknowledgeAsync(msg.getMessageId(), transaction);
                        }).thenAcceptAsync(__ -> {
                            transaction.commit().thenRun(() -> {
                                log.debug("Transaction committed!");
                                latch.countDown();
                            }).exceptionally(e -> {
                                latch.countDown();
                                return null;
                            });
                        }).exceptionally(e -> {
                            transaction.abort().thenRun(() -> {
                                log.debug("Transaction aborted!");
                                latch.countDown();
                            }).exceptionally(ex -> {
                                latch.countDown();
                                return null;
                            });
                            return null;
                        });
                    });
                } catch (PulsarClientException e) {
                    e.printStackTrace();
                }
            }
        }).start();

        latch.await();
        log.info("Test Done!");
    }
}

```

**Expected behavior**
No error logs for producer semaphore permit release

**Additional context**
both master branch and branch-2.9

### PR DESCRIPTION
**Pull request by mattisonchao**
Fixes #13671

Master Issue: #13671

### Motivation

see #13671

### Modifications

- Fix wrong expression.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

- [x] `no-need-doc`

### CODE REVIEW

**Review by Technoboy- — APPROVED** [review]

**Comment by Technoboy-** [comment]
@mattisonchao Please help to check other branches (branch-2.8, branch-2.9) if exist the same issue.

**Review by Jason918 — APPROVED** [review]

**Review by codelipenghui — COMMENTED** [review]
@mattisonchao Nice fix, it's better to add a test to avoid regression. The fix LGTM!

**Review by gaoran10 — APPROVED** [review]
LGTM. Could you add a test?

**Review by RobertIndie — APPROVED** [review]

**Comment by mattisonchao** [comment]
@codelipenghui  @gaoran10 

Tests have been added.

PTAL :)

**Comment by mattisonchao** [comment]
@Technoboy- 

It seems just effect branch-2.9.

**Review by Shoothzj — APPROVED** [review]

**Comment by codelipenghui** [comment]
@eolivelli Why remove labels `release/2.8.3` and `release/2.9.2`?

**Pull request merged**
