### PR TITLE
Fix schema-understand doc.

### PR DESCRIPTION
**Pull request by congbobo184**
now complex type example are not right, so fix it.

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Review by BewareMyPower — CHANGES_REQUESTED** [review]
I think this part of docs is initially for protobuf native schema, see https://github.com/apache/pulsar/pull/9079. Is it proper to use Avro schema as the example here?

**Comment by congbobo184** [comment]
@BewareMyPower hi, I think this example is used to explain struct schema. Both avro and protobuf are good, what do you think?

**Comment by BewareMyPower** [comment]
OK, I also just found the original doc PR is a little confused because it contains both the schema definition part and protobuf native schema part.

**Review by BewareMyPower — APPROVED** [review]

**Comment by Anonymitaet** [comment]
Thanks for your contribution. Does this affect only master or other versioned docs? 
If latter, could you please help update all affected versions? Thanks

**Review by eolivelli — APPROVED** [review]

**Review by k2la — APPROVED** [review]

**Pull request merged**
