### PR TITLE
[Tiered Storage] Fix merge conflicts introduced by PR #6335

### PR DESCRIPTION
**Pull request by gaoran10**
# Motivation

The PR #6335 lost some PR changes, related PRs as below.

1. PR 4196 (2019/5/29 Merli)
Configure static PulsarByteBufAllocator to handle OOM errors (#4196)

2. PR 5356 (2019/10/30 Kelly)
[TIEREDSTORAGE] Only seek when reading unexpected entry (#5356)

3. PR 4433 (2019/6/4 Higham)
[tiered-storage] Add support for AWS instance and role creds (#4433)

### Modifications

Repair the lost PR changes.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### CODE REVIEW

**Comment by jiazhai** [comment]
@Renkai Would you please also help take a review of this PR?

**Review by codelipenghui — APPROVED** [review]

**Comment by Renkai** [comment]
Test errors seems related to this PR @gaoran10

**Comment by codelipenghui** [comment]
cherry-picked to branch-2.6

**Pull request merged**
