### PR TITLE
fix issue 3226 Unclosed consumer after calling closeAsync

### PR DESCRIPTION
**Pull request by legendtkl**
issue ticket: https://github.com/apache/pulsar/issues/3226

### CODE REVIEW

**Comment by legendtkl** [comment]
hi @sijie , just as discussed on wechat, would you help review this pr. 

thanks.

**Comment by legendtkl** [comment]
run python tests

**Comment by legendtkl** [comment]
run C++ / Python Tests

**Comment by legendtkl** [comment]
run cpp tests

**Comment by legendtkl** [comment]
@sijie  
* that's ok to change order
* yes, I have verified that.
* I found the integration tests in the path: pulsar/pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TopicsConsumerImplTest.java , so I don't add more tests. Do you think we need more?

**Comment by sijie** [comment]
run java8 tests

**Pull request merged**
