### PR TITLE
Add GitHub issue template for reporting flaky tests

### PR DESCRIPTION
**Pull request by lhotari**
### Motivation

It was suggested[ on the mailing list](https://lists.apache.org/thread.html/ra7931816ce745ac3dde6170e9186a4e9418358e5ad1edeec25d304a0%40%3Cdev.pulsar.apache.org%3E) by @sijie to add a GitHub issue template for reporting flaky tests.
By having an issue template for flaky tests, it's easier to report flaky tests consistently.

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
+1

**Review by merlimat — APPROVED** [review]

**Review by sijie — APPROVED** [review]

**Comment by zymap** [comment]
Failed test:

```
Error:  Tests run: 21, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 108.4 s <<< FAILURE! - in org.apache.pulsar.broker.service.ReplicatorTest
Error:  testResetCursorNotFail(org.apache.pulsar.broker.service.ReplicatorTest)  Time elapsed: 30.209 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.broker.service.ReplicatorTest.testResetCursorNotFail() didn't finish within the time-out 30000
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:371)
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:605)
	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:764)
	at org.testng.TestRunner.run(TestRunner.java:585)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:  org.apache.pulsar.broker.service.ReplicatorTest.testResetCursorNotFail(org.apache.pulsar.broker.service.ReplicatorTest)
[INFO]   Run 1: PASS
Error:    Run 2: ReplicatorTest.testResetCursorNotFail ? ThreadTimeout Method org.apache.pulsar...
[INFO] 
[INFO] 
Error:  Tests run: 20, Failures: 1, Errors: 0, Skipped: 0
```

**Review by zymap — APPROVED** [review]

**Pull request merged**
