### PR TITLE
[Doc] add explanations of packages for Java client

### PR DESCRIPTION
**Pull request by Anonymitaet**

### CODE REVIEW

**Comment by Anonymitaet** [comment]
@Technoboy- could you please help review? thanks

**Review by Technoboy- — APPROVED** [review]
LGTM

**Comment by syhily** [comment]
LGTM

**Review by syhily — CHANGES_REQUESTED** [review]
We can add extra information about why we provide a `pulsar-client-all`. Here is the original proposal.

## PIP-29: One package for both pulsar client and pulsar admin (#3662)

*Motivation*

Currently we are shipping pulsar-client and pulsar-client-admin separately. Both pulsar-client and pulsar-client-admin are shaded packages. But they shaded the dependencies independently.  It is quite common to see applications using both pulsar-client and pulsar-client-admin. These applications will have redundant shaded classes existed in both pulsar-client and pulsar-client-admin. Sometime it also causes troubles when we introduced new dependencies but forget to update shading rules. 

*Modifications*

This proposal is proposing introduced a new module called pulsar-client-all. It will include both pulsar-client and pulsar-client-admin and shade the dependencies only one time. This would reduce the size of dependencies for applications using both pulsar-client and pulsar-client-admin.

**Review by sijie — APPROVED** [review]

**Comment by Anonymitaet** [comment]
@syhily thanks for your suggestions! I've added explanations, PTAL.

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
