### PR TITLE
[improve][broker] Make read compacted entries support maxReadSizeBytes limitation

### PR DESCRIPTION
**Pull request by coderzc**
### Motivation

In https://github.com/apache/pulsar/pull/7060, we allow managed cursor to specify the max read batch in bytes to avoid reading too large data at a time, but reading compacted entries did not consider maxReadSizeBytes, we should make reading compacted entries also support maxReadSizeBytes limitation.

### Modifications

* Using the `applyMaxSizeCap` method to recalculate `numberOfEntriesToRead` before reading compacted entries.
* Update read stats after completion of reading compacted entries.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by gaoran10 — APPROVED** [review]
LGTM

**Review by Demogorgon314 — APPROVED** [review]

**Review by lifepuzzlefun — APPROVED** [review]

**Comment by coderzc** [comment]
`org.apache.pulsar.compaction.StrategicCompactionTest.testCompactCompressedBatching` always failed after applying this change. I noticed the StrategicTwoPhaseCompactor may write messages from the same batch into different entries, which will result in skipping some messages when reading compacted entries. Is that so?
Refer to: https://github.com/apache/pulsar/blob/d099ac4fa2f217b9c5f0a5e660c83048e829c5d7/pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java#L129-L135 

https://github.com/apache/pulsar/blob/d099ac4fa2f217b9c5f0a5e660c83048e829c5d7/pulsar-broker/src/main/java/org/apache/pulsar/compaction/StrategicTwoPhaseCompactor.java#L444-L455
/cc @heesung-sn @Demogorgon314

**Comment by Demogorgon314** [comment]
@coderzc Yes, this is a bug. We will fix this issue.

**Comment by Demogorgon314** [comment]
@heesung-sn Should we limit the `batchingMaxMessages` to `200`(default is `1000`), so the `ServiceUnitStateChannelImpl` will not hit this issue? Since the `StrategicTwoPhaseCompactor` uses `1000` as the max num messages in batch.

https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java#L301-L307

**Comment by heesung-sn** [comment]
> @heesung-sn Should we limit the `batchingMaxMessages` to `200`(default is `1000`), so the `ServiceUnitStateChannelImpl` will not hit this issue? Since the `StrategicTwoPhaseCompactor` uses `1000` as the max num messages in batch.
> 
> https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java#L301-L307

```
public class StrategicTwoPhaseCompactor extends TwoPhaseCompactor {
    private static final Logger log = LoggerFactory.getLogger(StrategicTwoPhaseCompactor.class);
    private static final int MAX_OUTSTANDING = 500;
    private static final int MAX_NUM_MESSAGES_IN_BATCH = 1000;
    private static final int MAX_BYTES_IN_BATCH = 128 * 1024;
```
Yes, if the big batching matters, then we could limit the batching in both the producer and the compactor side in BSC.

**Comment by lhotari** [comment]
There's a related really flaky test #21065 which slows down CI , @coderzc do you have a chance to check that? Thanks

**Comment by shibd** [comment]
@coderzc  Can you help create a PR to cherry-pick this change to `branch-2.11`?

**Pull request merged**
