### PR TITLE
Revert "Fix: LockManagerTest.updateValue is flaky (#13911)"

### PR DESCRIPTION
**Pull request by shibd**
### Motivation

https://github.com/apache/pulsar/issues/15091

The essential reason for https://github.com/apache/pulsar/pull/13911 is that two threads execute the refresh method concurrently. In PR https://github.com/apache/pulsar/pull/13911 change, it doesn't completely solve the problem, just avoid concurrent access by threads.

In #14283, The problem was radically resolved by changing below.
```
objCache.asMap().computeIfPresent(path, (oldKey, oldValue) -> readValueFromStore(path));
```

In #13911, although multi-threaded access is avoided, it will cause the test `future.get()` to not get the expected result. 
This will cause the `updateValueWhenKeyDisappears` test to fail. So, revert this commit. 

### Modifications
- Revert "Fix: LockManagerTest.updateValue is flaky (#13911)"

### Documentation
- [x] `no-need-doc`

### CODE REVIEW

**Comment by codelipenghui** [comment]
@shibd So we need another solution for the flaky test? this PR just revert the previous solution?

**Comment by shibd** [comment]
> @shibd So we need another solution for the flaky test? this PR just revert the previous solution?

No need, Because #14283 also solved these flaky tests.

**Review by Jason918 — APPROVED** [review]
LGTM

**Review by gaoran10 — APPROVED** [review]

**Review by dlg99 — APPROVED** [review]
LGTM

**Review by mattisonchao — APPROVED** [review]

**Pull request merged**
