### PR TITLE
website : fix jwt link and content

### PR DESCRIPTION
**Pull request by jiazhai**
### Motivation

image

JWT content is not linked well.  This PR tries to fix the link

### Modifications

Add support from 2.4.0.

### Verifying this change
build website locally, verify links for 2.4.0, 2.4.1, 2.4.2 works well.

### CODE REVIEW

**Comment by jiazhai** [comment]
@Jennifer88huang  Your comments seems be out of the motivation of this PR. Would you please open another issue for these requirements?

**Comment by jiazhai** [comment]
>Could you please also copy the security-jwt.md file into 2.4.1 and 2.4.2 folders?

2.4.1 and 2.4.2 will auto reference the current version. no need to copy them.

> We've updated the structure of the Security chapter, could you please update the sidebars.json file in 2.4.0, 2.4.1, and 2.4.2 with that in master?

For the old version, Maybe fix the bug is enough?

**Comment by Jennifer88huang** [comment]
If you think it's enough to fix the current issue, just go on with your process.

**Comment by tuteng** [comment]
run cpp tests

**Comment by tuteng** [comment]
run java8 tests

**Comment by tuteng** [comment]
run cpp tests

**Comment by sijie** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Pull request merged**
