### PR TITLE
[improve][client] Ignore InterruptedException when pulsar-perf finishing

### PR DESCRIPTION
**Pull request by yaalsn**
### Motivation

If I run the command `bin/pulsar-perf produce my-topic -time 5`, it returns a `java.lang.InterruptedException` before it exits.

image

The reason is that `doneLatch`  will be zero before `sleep(5000)`, and the main thread exits 0 when `doneLatch<=0`, so the `pulsar-perf-producer-exec` thread pool will be terminated and has a chance to throw an `InterruptedException` if it starts to run `sleep(5000)`.

https://github.com/apache/pulsar/blob/d1b7d0b7d86a7a8883407d3dc054bb8e21f96d60/pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java#L583-L584

https://github.com/apache/pulsar/blob/d1b7d0b7d86a7a8883407d3dc054bb8e21f96d60/pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java#L381-L390
https://github.com/apache/pulsar/blob/d1b7d0b7d86a7a8883407d3dc054bb8e21f96d60/pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java#L435-L436

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

https://github.com/yaalsn/pulsar/pull/3

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
This is always no harm.

But I wonder if we can just remove the sleep - if we already wait on `countDown`, why sleep again?

**Comment by yaalsn** [comment]
@tisonkun I think so, but I don't know the reason for `sleep(5000)`, so I choose a safe way.

**Review by RobertIndie — COMMENTED** [review]
I think we can just remove `Thread.sleep(5000)`. The initial reason for it may be to sync the close state between threads. That state is `isDone` in the previous code.
But it seems useless after we introduce the countdown latch in this PR:https://github.com/apache/pulsar/pull/5036

**Comment by yaalsn** [comment]
@RobertIndie Thanks for your investigation. Let's remove it.

**Comment by tisonkun** [comment]
Merging...

Thank you!

**Pull request merged**
