### PR TITLE
[Broker] Adjust topic exists check logic in http lookup process

### PR DESCRIPTION
**Pull request by gaoran10**
### Motivation

Currently, it's hard to check the non-persistent-non-partitioned topic exists or not, because it only exists in the broker cache, it doesn't have metadata.

If there is a non-persistent and non-partitioned topic exists in broker0 and the configuration `AllowAutoTopicCreation` is false, we perform an HTTP lookup request to broker1, it will return a TopicNotFound exception.

### Modifications

If the topic is non-persistent and non-partitioned, we'll return the true flag to ensure the http lookup can return a result.

### Verifying this change

Add a test to verify the HTTP lookup request to each broker could return a right lookup result.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Review by Jason918 — APPROVED** [review]
LGTM. Good catch.

I think we can go further and just skip this exist check if `pulsar().getBrokerService().isAllowAutoTopicCreation(topicName)` is true?

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
The related change introduced by #13055 and only for the master branch, so don't need to cherry-pick to other branches.
And this change is a 2.10 blocker, otherwise, we will introduce breaking change in 2.10.

**Review by RobertIndie — APPROVED** [review]

**Comment by Technoboy-** [comment]
> LGTM. Good catch.
> 
> I think we can go further and just skip this exist check if `pulsar().getBrokerService().isAllowAutoTopicCreation(topicName)` is true?

Seems a good idea.  @codelipenghui @gaoran10

**Review by Technoboy- — APPROVED** [review]
LGTM.
But the idea that @Jason918 commented looks perfect.

**Review by Jason918 — APPROVED** [review]
Great.

**Review by Technoboy- — APPROVED** [review]

**Pull request merged**
