### PR TITLE
[go-functions] fix metrics server handler error

### PR DESCRIPTION
**Pull request by freeznet**
### Motivation

#9318 add metrics server to go function, but didnt serve `"/"` endpoint in metrics server, which will cause some metrics calls failed.

### Modifications

add handler for `"/"` in `MetricsServicer`

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### CODE REVIEW

**Review by sijie — APPROVED** [review]

**Comment by sijie** [comment]
@freeznet the go functions test seems to fail.

```
2021/02/01 05:27:23.102 log.go:46: [info] Starting metrics server on port 50001
--- FAIL: TestMetricsServer (0.00s)
    stats_test.go:198: 
        	Error Trace:	stats_test.go:198
        	Error:      	Not equal: 
        	            	expected: <nil>(<nil>)
        	            	actual  : *url.Error(&url.Error{Op:"Get", URL:"http://localhost:50001/", Err:(*net.OpError)(0xc0001cd770)})
        	Test:       	TestMetricsServer
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb52c50]
```

**Review by jiazhai — APPROVED** [review]

**Pull request merged**
