### PR TITLE
[Pulsar C++ Client] make pool connections configurable in perf tools

### PR DESCRIPTION
**Pull request by ltamber**
### Motivation

make pool connections configurable in c++ performance test.

### CODE REVIEW

**Review by sijie — APPROVED** [review]

**Comment by BewareMyPower** [comment]
You should use clang-format 5.0 to reformat your code.

```diff
diff --git a/pulsar-client-cpp/perf/PerfConsumer.cc b/pulsar-client-cpp/perf/PerfConsumer.cc
index 7f2deb78792..6717fdeb827 100644
--- a/pulsar-client-cpp/perf/PerfConsumer.cc
+++ b/pulsar-client-cpp/perf/PerfConsumer.cc
@@ -301,7 +301,7 @@ int main(int argc, char** argv) {
          "Number of listener threads")  //
 
         ("pool-connections", po::value<bool>(&args.poolConnections)->default_value(false),
-         "whether pool connections used")   //
+         "whether pool connections used")  //
 
         ("encryption-key-name,k", po::value<std::string>(&args.encKeyName)->default_value(""),
          "The private key name to decrypt payload")  //
diff --git a/pulsar-client-cpp/perf/PerfProducer.cc b/pulsar-client-cpp/perf/PerfProducer.cc
index ffc365dde7f..6e71ce78b1c 100644
--- a/pulsar-client-cpp/perf/PerfProducer.cc
+++ b/pulsar-client-cpp/perf/PerfProducer.cc
@@ -279,9 +279,8 @@ int main(int argc, char** argv) {
          po::value<long>(&args.batchingMaxPublishDelayMs)->default_value(3000),
          "Use only is batch-size > 1, Default is 3 seconds")  //
 
-        ("pool-connections",
-         po::value<bool>(&args.poolConnections)->default_value(false),
-         "whether pool connections used")   //
+        ("pool-connections", po::value<bool>(&args.poolConnections)->default_value(false),
+         "whether pool connections used")  //
 
         ("encryption-key-name,k", po::value<std::string>(&args.encKeyName)->default_value(""),
          "The public key name to encrypt payload")  //
```

**Comment by ltamber** [comment]
@BewareMyPower done, PTAL

**Review by BewareMyPower — APPROVED** [review]

**Comment by ltamber** [comment]
@sijie @BewareMyPower PTAL

**Pull request merged**
