### PR TITLE
[branch-2.7] Upgrade netty to 4.1.68.Final

### PR DESCRIPTION
**Pull request by kellyfj**
### Motivation
Backport security fixes in Netty to 2.7 branch

### Modifications

Changed versions of netty dependencies in pom.xml and license files
 

This change is already covered by existing tests, such as *(please describe tests)*.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes)
  - The public API: (no)
  - The schema: (no )
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 
  
- [ ] `no-need-doc`

### CODE REVIEW

**Review by nicoloboschi — APPROVED** [review]

**Review by eolivelli — CHANGES_REQUESTED** [review]
+1

**Comment by michaeljmarshall** [comment]
I'm looking into why these tests are failing.

**Review by eolivelli — APPROVED** [review]

**Review by michaeljmarshall — APPROVED** [review]

**Comment by michaeljmarshall** [comment]
@eolivelli let me know over slack that these tests are very flaky. I am going to keep retriggering the builds a little bit more before I dig into the tests any more.

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@kellyfj Sorry, when I cherry-picking PRs I missed this one, so the original PR https://github.com/apache/pulsar/pull/12218 has been cherry-picked to branch-2.7, will close this one for now.

**Comment by frankjkelly** [comment]
Sounds good - thanks!

**Pull request closed without merging**
