### PR TITLE
Fix Test localhost resolution errors

### PR DESCRIPTION
**Pull request by aahmed-se**
Forcing tests to use localhost, this change is needed as due to variety in jenkins hosts, current machine hostname may not resolvable to localhost ip.

### CODE REVIEW

**Comment by rdhabalia** [comment]
rerun cpp tests
rerun integration tests

**Comment by merlimat** [comment]
With all the refactoring is very difficult to see what's the real fix in this PR.

**Comment by aahmed-se** [comment]
There are no refactoring Intellij is cleaning redundant code and imports when I edit files. It won't cause any functional change in the code. 

I have removed all references to getAddress with "localhost" string for test files only.

**Comment by aahmed-se** [comment]
@merlimat  @rdhabalia  this is ready  to merge.

**Comment by merlimat** [comment]
I know these are automated but still are not relevant to the fix in this pr

**Pull request merged**
