### PR TITLE
[dashboard] integrate peek into messages page

### PR DESCRIPTION
**Pull request by yittg**
### Motivation

messages page with full list would be under huge load if there are massive messages in backlog.

### Modifications

- render messages with a prompt and input to choose which message to peek instead of full backlog message list, and render message peeked within messages page.
- distinguish admin v1/v2 path from namespace.

### CODE REVIEW

**Comment by sijie** [comment]
@tuteng can you help review this?

**Comment by yittg** [comment]
A sample screenshot here,
image

**Comment by yittg** [comment]
by the way, we may fix other admin request base path in another PR @sijie

**Comment by tuteng** [comment]
LGTM
image
Can this error message be changed to English? @yittg

**Comment by yittg** [comment]
@tuteng This is a default message that seems to depend on the system language setting.

**Comment by tuteng** [comment]
> @tuteng This is a default message that seems to depend on the system language setting. Here in my browser is English.

I see, thank you very much.

**Comment by tuteng** [comment]
run java8 test

**Comment by tuteng** [comment]
run java8 tests

**Pull request merged**
