### PR TITLE
[transaction][buffer] add interfaces for transaction buffer and an in-memory implementation

### PR DESCRIPTION
**Pull request by sijie**
Master Issue: #2664

*Motivation*

Setup the project structure for developing transaction buffer.

*Changes*

- setup the project structure
- introduce common classes: `TxnID`, `TxnStatus`
- introduce `TransactionBuffer` for broker to store and manage entries for transactions
- enable checkstyle for `pulsar-transaction`

*NOTES*

All the changes are isolated into `pulsar-transaction` module. Hence it will not block any other changes or releases.

### CODE REVIEW

**Comment by sijie** [comment]
This PR shares some common changes with #4161

**Comment by sijie** [comment]
run integration tests
run java8 tests

**Comment by jiazhai** [comment]
run integration tests
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by jiazhai** [comment]
run java8 tests

**Pull request merged**
