### PR TITLE
Update Guava to version 30.0

### PR DESCRIPTION
**Pull request by cimura**
### Motivation

Guava with version lower than 30.0 has vulnerability.
https://snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-1015415

### Modifications

- Guava 25.1 -> 30.0

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
LGTM 
we did the same change in BK4.12
also Guava 30 breaks binary compatibility and some users of the Java client will be blocked in the upgrade if we do not upgrade Guava here.
usages of Guava 30 are compatible with Guava 29 (if you do not use new features, as usual)

**Review by jiazhai — APPROVED** [review]

**Review by wolfstudy — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Pull request merged**
