### PR TITLE
[Testing] Fix Maven Surefire default exclude

### PR DESCRIPTION
**Pull request by lhotari**
### Motivation

- Problem introduced in PR #9823
- In the shell script `**/*$*` gets replaced with `**/*` when using double quotes. This makes the test run skip most tests for the groups that use excludes.

### Modifications 

- Fix: use single quotes for the exclude parameter in `run_unit_group.sh` script

### CODE REVIEW

**Review by aahmed-se — APPROVED** [review]

**Review by zymap — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
+1

I hope we will have some day and aggregated report that tells the overall number of tests that run (like the one you can have on Jenkins)

This way we will be able to roughly see if the number for tests is the expected number

**Comment by lhotari** [comment]
For some reason 2 builds in a row have failed because of flaky PulsarClientToolWsTest. I added an attempt to fix flakiness in PulsarClientToolWsTest.

**Comment by lhotari** [comment]
It looks like the build for the last remaining check is stuck in the queue: https://github.com/apache/pulsar/pull/9836/checks?check_run_id=2056452413

**Comment by lhotari** [comment]
Finally the build for the last check is in progress, after 7 hours in the build queue.

**Comment by lhotari** [comment]
Finally the checks are passing, 7.5 hrs after pushing the commit.

**Comment by lhotari** [comment]
@merlimat Please review

**Pull request merged**
