### PR TITLE
Update the default producer settings for FlinkPulsarProducer

### PR DESCRIPTION
**Pull request by hlouf**
When do pulsar and Flink streamingWordCountTest,I get a error with( Producer send queue is full),then i modify the code create producer.This problem has been solved.I suggest that we can fix this problem.

<--
### Contribution Checklist
  
  - Name the pull request in the form "[Issue XYZ][component] Title of the pull request", where *XYZ* should be replaced by the actual issue number.
    Skip *Issue XYZ* if there is no associated github issue for this pull request.
    Skip *component* if you are unsure about which is the best component. E.g. `[docs] Fix typo in produce method`.

  - Fill out the template below to describe the changes contributed by the pull request. That will give reviewers the context they need to do the review.
  
  - Each pull request should address only one issue, not mix up code from multiple issues.
  
  - Each commit in the pull request has a meaningful commit message

  - Once all items of the checklist are addressed, remove the above text and this checklist, leaving only the filled out template below.

**(The sections below can be removed for hotfixes of typos)**
-->

*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #<xyz>

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #<xyz>

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by sijie** [comment]
> Is there a detailed log or operation?

@ambition119 you will only see such exception when running with large traffic. If you are just running an example, you won't see the exception.  @hlouf encountered the issue when he tries to run flink connector on production.

**Comment by shiv4289** [comment]
> or we can improve the FlinkPulsarProducer to accept a `Map<String, Object>` settings for Producer and use `loadConf` to build the producer.

I agree!

**Comment by hlouf** [comment]
I was sick the other day and didn't pay attention to the mail.Your suggestion is correct and can be followed by the operation of the second email.Thanks for your answer.
| |
shuai
|
|
hloufgss@163.com
|
签名由网易邮箱大师定制
On 3/30/2019 05:50，Shivji Kumar Jha<notifications@github.com> wrote：

or we can improve the FlinkPulsarProducer to accept a Map<String, Object> settings for Producer and use loadConf to build the producer.

I agree!

**Comment by sijie** [comment]
@hlouf - I am closing this issue since #3955 already adding `Map<String, Object>` to the constructor to allow users customizing the connector.

**Pull request closed without merging**
