### PR TITLE
Added metrics for producer throttling

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Added counters to track connections being throttled for outstanding messages or for reached global mem limit.

### CODE REVIEW

**Review by sijie — APPROVED** [review]

**Review by codelipenghui — COMMENTED** [review]
Looks good to me, could you please add a test for the new metrics? Avoid breaking it in future versions

**Comment by merlimat** [comment]
> Looks good to me, could you please add a test for the new metrics? Avoid breaking it in future versions

The metrics are static in the broker so it's very difficult to test them cleanly in isolation when the unit tests are running multiple broker instances

**Review by codelipenghui — APPROVED** [review]

**Comment by Anonymitaet** [comment]
@merlimat thanks for your coding work.

1. Does this apply to 2.7.1?

2. Would you like to add docs for this change?

**Comment by merlimat** [comment]
@Anonymitaet This is only from 2.8. Yes, we should have the new metric on `site2/docs/reference-metrics.md`

**Comment by Anonymitaet** [comment]
@merlimat thanks. Could you please help add docs accordingly?

**Pull request merged**
