### PR TITLE
Update supported  python osx version docs

### PR DESCRIPTION
**Pull request by aahmed-se**
Minor doc update

### CODE REVIEW

**Comment by sijie** [comment]
run integration tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run java8 tests

**Comment by aahmed-se** [comment]
run cpp tests

**Comment by aahmed-se** [comment]
run cpp tests

**Pull request merged**
