### PR TITLE
Add subscribe position param for consumer of sink

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <ranxiaolong716@gmail.com>

### Motivation

In some case, user wants to use a custom subscription position.

### Modifications

Add `--subs-position` for sink.

### CODE REVIEW

**Comment by codelipenghui** [comment]
@wolfstudy please take a look the tests, seems some files are not committed

**Comment by wolfstudy** [comment]
run java8 tests

**Comment by candlerb** [comment]
Does this new functionality apply to Pulsar functions, or just to sinks?

**Comment by candlerb** [comment]
Would it be useful if this option allowed to subscribe from an arbitrary point in time too? 

cf. [reset-cursor](http://pulsar.apache.org/docs/en/next/pulsar-admin/#reset-cursor).

`--time 0` would be latest (which I believe is default anyway). `--time 3h` would be starting from 3 hours ago.  Would need some sentinel value to reset to earliest available message - I'm not sure how you'd do that with `reset-cursor` either.

Aside: it's not documented in the link above, but `reset-cursor` also supports a `messageId` option.

```
$ apache-pulsar-2.4.1/bin/pulsar-admin topics reset-cursor --help
Unknown option: --help

Reset position for subscription to position closest to timestamp or messageId
Usage: reset-cursor [options] persistent://tenant/namespace/topic
  Options:
    --messageId, -m
       messageId to reset back to (ledgerId:entryId)
  * -s, --subscription
       Subscription to reset position on
    --time, -t
       time in minutes to reset back to (or minutes, hours,days,weeks eg: 100m,
       3h, 2d, 5w)
```

**Comment by wolfstudy** [comment]
> the change looks good to me. however can you please add unit tests for this?

Yes, the test for this option will be overridden in the existing `testDefaultSerDe` case.

**Comment by wolfstudy** [comment]
> Does this new functionality apply to Pulsar functions, or just to sinks?

Currently, the new functionality apply just to Sinks.

**Comment by wolfstudy** [comment]
run cpp tests

**Comment by sijie** [comment]
> Currently, the new functionality apply just to Sinks.

@wolfstudy can you also add the functionality to both functions? Just want to make sure we cover that using the same mechanism.

**Comment by wolfstudy** [comment]
Thanks @sijie work for this.

@candlerb 

> Aside: it's not documented in the link above, but reset-cursor also supports a messageId option.

Thanks @candlerb , has been fixed in #5551, PTAL.

> Would it be useful if this option allowed to subscribe from an arbitrary point in time too?

The feature will be add in [issue:5552](https://github.com/apache/pulsar/issues/5552).

**Pull request merged**
