### PR TITLE
Upgrade to Apache Avro 1.10.2

### LINKED ISSUE #9045: Can not use Avro 1.10 together with pulsar-client-admin
**Describe the bug**
When I have gradle dependencies defined as  
```
api("org.apache.pulsar:pulsar-client-admin:2.7.0")
api("org.apache.pulsar:pulsar-client:2.7.0")
implementation("org.apache.avro:acro:1.10.0")
```
then `AvroSchema.of(...)` triggers 
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/avro/data/JodaTimeConversions$TimestampConversion
```

**To Reproduce**

Adding `pulsar-client-admin` api dependency seems to have the curious side-effect to "unshade" avro in pulsar-client. 

(when having `implementation("org.apache.pulsar:pulsar-client-admin:2.7.0")` instead of `api("org.apache.pulsar:pulsar-client-admin:2.7.0")` the same bug occurs but only at runtime)

The exception is thrown from `AvroSchema.addLogicalTypeConversions` because `JodaTimeConversions` does not exist anymore for avro >= 1.10

**Expected behavior**
I should be able to use Avro >=1.10

### PR DESCRIPTION
**Pull request by eolivelli**
Fixes #9045

### Motivation

Upgrade to new Avro version 1.10.2

### Modifications

- Upgrade Avro
- Copy a class from Avro 1.9.1 (so little and trivial that there is no need to add a reference to NOTICE file) because Avro 1.10.x dropped JodaTimeConversions class

Important notice: since Avro 1.10.0 ReflectData returns field in alphabetical order, so schema generated with Schema.AVRO(Pojo.class) my result different from the ones created by the previous version. The new schema is 100% compatible with the old version.

### Verifying this change

This change is already covered by existing tests about Avro Schema 

### Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): yes

### CODE REVIEW

**Review by merlimat — APPROVED** [review]

**Review by sijie — CHANGES_REQUESTED** [review]
why it is 1.10.0 not 1.10.1?

**Comment by eolivelli** [comment]
@sijie 
I just missed Avro 1.10.1 release :) 

I have updated the patch, please take a look
thanks

**Review by codelipenghui — APPROVED** [review]

**Comment by geomagilles** [comment]
thx @eolivelli

**Comment by eolivelli** [comment]
I have found a real show stopper, in Avro 1.10.0 they changed the way we create an AVRO schema using reflection,
https://issues.apache.org/jira/browse/AVRO-2579

I noticed this behaviour by analysing failed tests

Actually 1.10 behaviour is somehow better but it will break compatibility.

I should also add that currently the reflection based approach (Schema.AVRO(pojoClass)) is risky because it depends on how the JVM returns the fields using reflection.

If you will upgrade an application that uses Schema.AVRO from Avro 1.9 to Avro 1.10 you will follow into schema compatibility issues

**Review by sijie — APPROVED** [review]

**Comment by eolivelli** [comment]
Avro 1.10.2 has been released today, I will update the patch once CI passes and I am sure that all tests are passing

**Review by RyanSkraba — APPROVED** [review]
This LGTM for a migration from Avro 1.9.x to 1.10.x!  We **just** released [1.10.2 ](https://github.com/apache/avro/releases/tag/release-1.10.2) if you're interested in bumping to the most recent version.

**Comment by eolivelli** [comment]
Thank you @RyanSkraba for your review

**Pull request merged**
